### ISSUE TITLE
Missing type parameters should be a warning.

### ISSUE THREAD

**Issue by mogmios** [dotnet/csharplang#1029]
A generic type parameter that is missing such as .MyFunc<> () should at least produce a warning on the guilty line. As it is, it sometimes causes a “failure to emit” error without pointing to a specific cause. Sometimes it doesn’t even do that (in VS 2017 anyway).

**Comment by svick** [comment]
Could you clarify what specific code causes the "failure to emit" error? Because that's almost certainly a bug.

And if there is some code with an error that does not produce an error, could you provide the specific code for that too?

It's certainly not that missing type parameters always behave this way, for example this code:

```c#
class C
{
    static void Main()
    {
        var c = new C();
        c.MyFunc<>();
    }

    void MyFunc<T>() { }
}
```

correctly produces this error for me in VS 2017:

> error CS0305: Using the generic method group 'MyFunc' requires 1 type arguments

**Comment by aluanhaddad** [comment]
Hasn't this always been an error outside of youth with the `typeof` operator? I'm starting to question my sanity.

**Comment by gafter** [comment]
@mogmios [Please report any compiler crash, or failure to detect an error, in the Roslyn repo](https://github.com/dotnet/roslyn/issues/new).
