### ISSUE TITLE
Champion "deprecate _ (underbar) as an identifier"

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#1064]
- [ ] Proposal added
- [ ] Discussed in LDM
- [ ] Decision in LDM
- [ ] Finalized (done, rejected, inactive)
- [ ] Spec'ed

It is unfortunate that the reader cannot easily distinguish at the use site between a discard and a use of an identifier named `_`. Presumably the latter is rare. Programs would be easier to read if one could reliably depend on `_` being a discard.

**Comment by jnm2** [comment]
I use `.Select(_ => _.Foo)` everywhere, and I want to continue doing so.

**Comment by HaloFour** [comment]
Relevant previous discussions/arguments/rants:

https://github.com/dotnet/roslyn/issues/14794
https://github.com/dotnet/roslyn/issues/14862

There might be a few more.

I think it's worth the discussion although it would probably be difficult to resolve without breaking a lot of existing code, particular like @jnm's example.

🍝 Perhaps the rules for identifiers could allow underbar for a lambda parameter in expression lambdas but not elsewhere?  That would be weird.

At the very least perhaps consider adding a warning wave to declaring a field or local using the underbar identifier.  You could differentiate the discard/local case by whether or not the local is ever used.

**Comment by bondsbw** [comment]
If there was an auto-upgrade conversion of existing usages of `_` as an identifier to `@_`, it might not break so much existing code.

**Comment by jnm2** [comment]
The point of `_ => _.Foo` is that `_` is the least possible visual clotter. I'm not a fan of `@_ => @_.Foo`.

**Comment by jnm2** [comment]
The point of `_ => _.Foo` is that `_` is the least possible visual clutter. I'm not a fan of `@_ => @_.Foo`.

**Comment by bondsbw** [comment]
@jnm2 Agreed, it would just keep from breaking existing code.

**Comment by eyalsk** [comment]
@jnm2 Well, you can always use something like `x`, however, I understand why you would dislike it. 

p.s. iirc @HaloFour made a proposal that addresses exactly this or something similar where we can do something like `@.Foo` instead of `_ => _.Foo`.

**Comment by jnm2** [comment]
I'd stop using `_ => _.Foo` in a heartbeat if I could use `@.Foo`.

**Comment by eyalsk** [comment]
@jnm2 Indeed, it would be awesome if they would at one hand get rid of `_` as a valid identifier and on another hand would allow people to do something like `@.Foo`.

**Comment by alrz** [comment]
I'd support any kind of deprecation at this point. This seemed impossible to me but now I can see the light. Please deprecate more.

**Comment by MgSam** [comment]
Is this seriously being considered or is this just a wish? Has the LDC suddenly had a change of heart where they're willing to take breaking changes?

**Comment by yaakov-h** [comment]
What does "deprecate" mean in this context? I assume it wouldn't be a full removal from the language?

**Comment by eyalsk** [comment]
@yaakov-h I assume that in any place where today you can use a single `_` as a valid identifier it wouldn't be possible with this change.

**Comment by Joe4evr** [comment]
> At the very least perhaps consider adding a warning wave to declaring a field or local using the underbar identifier.

I recall that something like this was already planned to be the case. And the whole process would likely be spread out over a few major language versions, regardless. (So for example, 8.0: Info, 9.0: Warning (maybe with exclusion from `/warningsAsErrors`), 10.0: Error. But that's just spit-balling.)

**Comment by kentcb** [comment]
Stumbled on this by accident and just had to add my 2c. I'd be very happy if `_` was treated as discard _consistently_ in C#. We're in a weird place right now where it's sometimes discard, sometimes not. I think that was a mistake, but one better fixed late than never.

As someone who makes heavy use of Rx, being able to discard with `_` in lambdas would be 💯. Random example of one place this would be useful:
```C#
this.WhenAnyValue(
    x => x.DepartureLocation,
    x => x.ArrivalLocation,
    x => x.JourneyMode,
    x => x.JourneyTime,
    x => x.ShowAll,
    (_, __, ___, ____, _____) => Unit.Default)
```
Having said that, I understand concern from @jnm2 et al regarding breaking changes. Personally, I think `_` (and `x`, and `@`) are all terrible names for lambda parameters _when a more descriptive name adds value_ (not the case above because the `x` there is just a stand-in for `this`). For example, this is much better:
```C#
items.Select(item => ...)
```
But of course, now we're getting into style arguments...

**Comment by jnm2** [comment]
There's no reason we couldn't have this, and there's even a proposal on it:

```cs
this.WhenAnyValue(
    _ => _.DepartureLocation,
    _ => _.ArrivalLocation,
    _ => _.JourneyMode,
    _ => _.JourneyTime,
    _ => _.ShowAll,
    (_, _, _, _, _) => Unit.Default)
```

`items.Select(item => item.Foo)` does not seem more descriptive than `items.Select(_ => _.Foo)`.

**Comment by kentcb** [comment]
> There's no reason we couldn't have this, and there's even a proposal on it

Er, yes. It's what I'm asking for. But it would require that this proposal be accepted so that `_` is not an identifier. Or maybe I'm missing something...?

> items.Select(item => item.Foo) does not seem more descriptive than items.Select(_ => _.Foo)

It was a very simple example based on yours. Add a `SelectMany` and a `Where`, all the while calling all variables (of differing) types `_`, then see how easy it is to read :)

**Comment by jnm2** [comment]
>> There's no reason we couldn't have this
> 
> Er, yes. It's what I'm asking for.

The code sample uses `_` for both parameter names and discard– it didn't sound like you were asking for that.

> Add a SelectMany and a Where, all the while calling all variables (of differing) types _, then see how easy it is to read :)

Though in fact it's most predominantly used only once in a chain, I do this on a regular basis and like it:

```cs
foos.SelectMany(_ => _.Bars).Any(_ => _.Start != null || _.End != null)
```

The project I have open: 16.9% of the files use `_.`, and in those files it occurs 6.59 times per file.

**Comment by kentcb** [comment]
> The code sample uses _ for both parameter names and discard

Ah, I overlooked your use of `_` for parameter names. That is certainly not what I'm asking for. Thanks for clarifying.

**Comment by DarthVella** [comment]
@eyalsk I'd assumed a compiler warning for a while, up until it is outright disallowed on the next major language update (or whenever).

**Comment by MkazemAkhgary** [comment]
**Attention please**

Why not make it an option to enable/disable usage of discards all over the place?

like how unsafe is optional. that way it wont be breaking change.

**Comment by DavidArno** [comment]
Whilst this is a breaking change, it is only breaking if one uses "treat warnings as errors" (which hopefully we all do; oh to have that as the default in new projects!) and it need only be breaking for as long as it takes to select a "ignore this warning in this project" code fix.

**Comment by eyalsk** [comment]
@DarthVella Yeah, probably. :)

**Comment by DavidArno** [comment]
@DarthVella, @eyalsk,

Warning in v8, error in v9 seems a nice timeline for phasing out the use of `_` as an identifier. I'd certainly not like to see either introduced in a minor release.

**Comment by eyalsk** [comment]
@DavidArno Yeah this is what I wrote in a comment to @MkazemAkhgary in his post. ;)

**Comment by MkazemAkhgary** [comment]
for a very rare case, `__` (two `_`) wouldn't be a warning. unless they decide to deprecate underbar-only identifiers.

```
(_, __) // former becomes discard, latter remain variable.
```

**Comment by DavidArno** [comment]
@MkazemAkhgary,

I'd personally like to see all underscore-only identifiers deprecated, even though I know this would break some of my own code (and thus the code of anyone who uses my library). The benefits of clarity would outweigh the small pain of fixing that broken code in my view.

**Comment by sharwell** [comment]
@gafter My previous understanding was it's possible to automatically turn all `_` identifiers in a scope into discards when there are two or more of them (a situation which previously resulted in a compiler error). This is a both a non-breaking change and delivers the "discards everywhere" feature. To me, the approach seems like an obvious choice; is there a reason why it didn't work in practice?

:memo: With this behavior in place, an analyzer could be used to deprecate `_` as an identifier in code bases - specifically to catch cases where a single `_` is not being used as a discard.

**Comment by jnm2** [comment]
If we get `.Select(@.Foo)` first, then this is okay. It's kind of harsh to deprecate a feature that is only used because we don't have anything better.

@sharwell's suggestion makes the most sense of any in this thread. Frankly I'm a little surprised at some of the supporters here– normally you'd be the first to say to allegations that a language feature is dirty, "If you don't like it, write an analyzer." 😃

**Comment by Vlad-Stryapko** [comment]
Totally agree with @jnm2 and @sharwell  on the matter. 

You either don't need a complex identifier, as in `items.Where` or you do need it and in that case `x` won't be a good name. 

I do like the way Scala solves it. Lambdas can be written as `items.Where(_.Property == property)` and lambdas with `_ => _` aren't used since `_` is a wildcard. So, IMHO, having a special syntax for short lambdas would be extremely nice and will play with this proposal very well. 

Otherwise, it will break the codebase in both pet and work projects I participate in. 

@DavidArno 
> The benefits of clarity would outweigh the small pain of fixing that broken code in my view.
There is absolutely no benefit of clarity if we replace `_` with `x`, `y`, `z` and so on. I've seen such lambdas and they're awful regardless of the symbol used. On the other hand, for simple cases `_` isn't worse than `x`.

**Comment by HaloFour** [comment]
@Vlad-Stryapko @jnm2 

Theoretically if C# takes the hardline approach and actually makes `_` an illegal identifier they could reuse `_` for lambda shorthand in a similar manner to Scala:

```cs
var foos = stuff.Select(_.Foo)
    .Where(_.Property == property);
```

**Comment by Vlad-Stryapko** [comment]
@HaloFour 
Yes, that's something I'd really love to have in C#. 

As far as I know, current proposal for shorthand in this repo is a bit different from the way Scala works with them, but I personally find Scala's choice not ideal so we definitely might have something even better in C#.

**Comment by bondsbw** [comment]
@HaloFour Do you know of any reason that couldn't be done today, allowed everywhere it is unambiguous?

**Comment by HaloFour** [comment]
@Vlad-Stryapko 

I'm less familiar with how `_` works in Scala, but after a brief read I can immediately see some behaviors that would be scary.  For example, what do you think the following would do?

```cs
int[] numbers = GetSomeInt32Array();
int[] doubled = numbers.Select(_+_).ToArray();
```

The proposal on this repo is a bit limited in scope, somewhat intentionally.  I modeled it more as a shorthand to instance method references from Java, where the type is inferred and it's only really the member that matters.  I can see there possibly being some value in supporting more complex expressions but, in my opinion, the goal is primarily to shine focus on the member that is relevant to the transform, not simply provide another lambda syntax that avoids naming things.  I don't care for the positional shorthand argument syntax in Swift, for example.  It just seems sloppy to me.  You're only going to have to write that code once but you're going to have to read and reason about it many times so it seems reasonable to require that the developer devise names to describe the relationship of those arguments.

@bondsbw 

> Do you know of any reason that couldn't be done today, allowed everywhere it is unambiguous?

Even if it could (and I imagine that it is probably possible), I would dislike the overloading of `_` with yet another special meaning where the syntax has overlap with legal syntax today.  If `_` remained a legal identifier my examples above are immediately ambiguous to the developer who then has to determine if there is a variable named `_` in scope.

**Comment by Vlad-Stryapko** [comment]
@HaloFour 

> For example, what do you think the following would do?

If we had it in C#, I would expect that to mean `Select(number => number + number)`. So basically we can refer to the function's argument as many times as we want but we're limited to functions with only one parameter.

With Scala's semantics, that would choose an overload of Select which takes `Func<TSource, int, TResult>` and treat the first `_` as an element of the sequence and the second `_` as its position. I don't think it's obvious for the majority of C# developers so I'd prefer the first version with `number => number + number`.

**Comment by svick** [comment]
> Presumably [using an identifier named `_`] is rare.

I thought it would be good to validate that assumption and since I performed a similar survey before (https://github.com/dotnet/roslyn/issues/14794#issuecomment-258961093), [I dusted off my old code and ran the analysis](https://gist.github.com/svick/5b791cedc55ed86db5734824efe70a0b). I looked at 875 recently updated C# GitHub repos with less than 100 stars (to exclude repos like Roslyn) to see how they use underscore as an identifier. The results:

* The analyzed repos contained 65 532 single-parameter lambdas. Out of those, 506 used `_` as parameter name, and 308 used `_` as parameter name, but didn't reference it inside the body of the lambda (so considering it to be a discard would be valid). That leaves **198 lambdas which would broken by this proposal**.
* The repos contained 15 674 lambdas with more than one parameter. Of those, 163 used underscore for one of their parameters, and none of the 163 lambdas used the underscore parameter in their body.
* The repos contained 30 uses of `_` as a discard.
* The repos contained **28 other uses of `_`**.

For the last point, a "use" means a use of a distinct symbol in a file. The 28 other uses were:

* [DEFRA/prsd-iws](https://github.com/DEFRA/prsd-iws) uses them to ignore arguments in FakeItEasy asserts. 7 uses, e.g. [src/EA.Iws.Domain.Tests.Unit/NotificationAssessment/NotificationAssessmentStatusTests.cs, line 92](https://github.com/DEFRA/prsd-iws/blob/e7faddc/src/EA.Iws.Domain.Tests.Unit/NotificationAssessment/NotificationAssessmentStatusTests.cs#L92):

   ```c#
    A.CallTo(() => progressService.IsComplete(A<Guid>._)).Returns(false);
   ```

   This is the most concerning "other" use I found, because it's a publicly exposed and [documented](http://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#ignoring-arguments) member in a popular library ([more than 1 million downloads on NuGet](https://www.nuget.org/packages/FakeItEasy/)). For fun, [here is its source code](https://github.com/FakeItEasy/FakeItEasy/blob/ba200ed/src/FakeItEasy/A.of.T.cs#L21-L32):

    ```c#
            /// <summary>
            /// Gets a constraint that considers any value of an argument as valid.
            /// </summary>
            /// <remarks>This is a shortcut for the "Ignored"-property.</remarks>
            [SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Justification = "This is a special case where the type parameter acts as an entry point into the fluent api.")]
            [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "_", Justification = "Some trickery is allowed, isn't it?")]
            [SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Justification = "But it's kinda cool right?")]
            [EditorBrowsable(EditorBrowsableState.Never)]
            [CLSCompliant(false)]
    #pragma warning disable SA1300 // Element must begin with upper-case letter
            public static T _ => Ignored;
    #pragma warning restore SA1300 // Element must begin with upper-case letter
    ```

* [RustServers-IO/oxideplugins](https://github.com/RustServers-IO/oxideplugins) seems to use it for various string manipulation helper functions. 14 uses, e.g. [rust/HuntPlugin.cs, line 802](https://github.com/RustServers-IO/oxideplugins/blob/94acba4/rust/HuntPlugin.cs#L802):

    ```c#
    sb.Append(_(HMK.Usage, player, _(skill.Usage, player)));
    ```

* [CatLib/Core](https://github.com/CatLib/Core) uses them in tests as `for`-loop iteration variables. 4 uses, e.g. [src/CatLib.Core.Tests/Support/SortSet/SortSetTests.cs, line 97](https://github.com/CatLib/Core/blob/d187aa2/src/CatLib.Core.Tests/Support/SortSet/SortSetTests.cs#L97):

    ```c#
    for (var _ = 0; _ < 100; _++)
    ```

* [Erroman/SF](https://github.com/Erroman/SF) seems to use it as the the `None` value of an `enum`. 1 use in [G.cs, line 123](https://github.com/Erroman/SF/blob/1ba30ce/G.cs#L123):

    ```c#
    case ParameterUnit._:
    ```

* [iiwaasnet/kino](https://github.com/iiwaasnet/kino) uses it for a value that's usually discarded, but not always. 1 use in [src/kino.Security/SecurityProvider.cs, line 96](https://github.com/iiwaasnet/kino/blob/935f7b2efd25da1bf0865e3a90224db73f4d87d2/src/kino.Security/SecurityProvider.cs#L89-L97):

    ```c#
    DomainPrivateKey _;
    if (!mappings.TryGetValue(messageIdentifier, out _))
    {
        mappings.Add(messageIdentifier, key);
    }
    else
    {
        throw new Exception($"Message {message.Identity} is already mapped to Domain {_.Domain}!");
    }
    ```

* [todor-dk/IronSmalltalk](https://github.com/todor-dk/IronSmalltalk) has it in its copy of the DLR, effectively as a discard. 1 use in [DLR/Microsoft.Dynamic/Generation/CompilerHelpers.cs, line 470](https://github.com/todor-dk/IronSmalltalk/blob/ba85ef0e412ae4487edff4793f291719bb9ef0f2/DLR/Microsoft.Dynamic/Generation/CompilerHelpers.cs#L469-L470):

    ```c#
     TypeConverter _;
    return TryGetTypeConverter(fromType, toType, out _);
    ```

**Comment by jnm2** [comment]
Not to mention that when I'm in pre-C# 7 codebases, I've been using `var _ = ` to discard values 😳

**Comment by jnm2** [comment]
@svick I love your approach. If I may ask, how long would it take to scale that up to cover another order of magnitude or more repos?

**Comment by DavidArno** [comment]
@Vlad-Stryapko,
>> The benefits of clarity would outweigh the small pain of fixing that broken code in my view.

> There is absolutely no benefit of clarity if we replace `_` with `x`, `y`, `z` and so on.

Whether there is benefit to replacing with `_` with `x` etc is orthogonal to what I said. To clarify, if `_` were to cease to be a valid identifier, then I feel it sensible to do the same with `__`. The two are already easily confused. Having one be a valid identifier and the other not, would just make that confusion worse.

**Comment by Vlad-Stryapko** [comment]
@DavidArno 
I've understood your initial statement as if making all underscores invalid would benefit the clarity of the code since people would have to replace their broken code with something more meaningful. That's the point I certainly disagree with.

>  if _ were to cease to be a valid identifier, then I feel it sensible to do the same with __

If we had short syntax for lambdas and `_` would act as a discard, I'd personally be fine with whatever happens to `__` and other similar identifiers. I think both 'single underscore has a special meaning, multiple underscores are identifiers' and 'single underscore has a special meaning, multiple underscores are not allowed' are fine.

**Comment by MkazemAkhgary** [comment]
@Vlad-Stryapko yet you provide no convincing reason why multiple underscores are meaningful. 

Ask yourself when you choose multiple underscores for variable names

Unless you are drunk you pretty much use it after you use `_` first. It makes perfecr sence to deprecate all underscore-only identifiers. That is if c# team already decided to make big change, moving a little higher isnt big deal.

**Comment by Vlad-Stryapko** [comment]
@MkazemAkhgary 
>you provide no convincing reason why multiple underscores are meaningful

They're already legal and that's why there must be a reason to make them illegal, not vice versa. The reason to make a single one illegal is to reserve it for the special purpose. I can't say I'm 100% sure multiple underscores must be disallowed so I refer to the principle 'don't create more restrictions and change anything unless it's really needed'.

**Comment by MkazemAkhgary** [comment]
@Vlad-Stryapko by all means, you wouldn't use `__` normally unless you have `_` somewhere declared. I'm pretty sure `_` fans wouldn't go for extra underscore after this limitation, they probably choose `x` anyway.

I just want to clarify how bad this feels for me, c# team is already ruining c# language, one that I used to love. now is getting dilapidated with these weird stuff. 😞

**Comment by eyalsk** [comment]
@MkazemAkhgary 

> c# team is already ruining c# language

Please... let's have some respect and try to keep it professional? just because you disagree with their decisions doesn't mean that they are ruining the language.

> one that I used to love.

I have plenty to say about these kind of statements but I'll be gentle and say it wouldn't help your cause.

> now is getting dilapidated with these weird stuff. 

Sometimes we need to try and see the world through a different lens and then maybe it wouldn't be so weird.

**Comment by MkazemAkhgary** [comment]
ok, my apologize to who are offended, I try to keep it to my self. you are right, maybe its just matter of time. @eyalsk

**Comment by aluanhaddad** [comment]
@eyalsk I most definitely agree with you, and I personally never write code using `_`, so this won't affect me, but I think everyone saw this coming and that it is an unnecessary breakage. This could have been avoided and it's not adding a lot of value vs. using a different character.

**Comment by eyalsk** [comment]
@aluanhaddad Yeah but the candidates were few and iirc required more changes to the language so they were pragmatic about it and given the amount of people that are using it, the amount of efforts required to make it work as an ignore character just make sense and let's be honest it looks good. 😉 

Sorry @jnm2. 😄

**Comment by kentcb** [comment]
As a related aside, I've thrown together [a Roslyn analyzer](https://github.com/code-heroes-pty-ltd/CodeHeroes.CodeAnalysis.Style/blob/develop/Src/Analyzers/UnderscoreIdentifierAnalyzer.cs) to detect the use of identifiers with discard names. I may have missed some cases. Feedback welcome.

**Comment by yaakov-h** [comment]
FWIW, StyleCop.Analyzers already disallows _ as a variable name - I had to run through my codebases and remove them when switching from StyleCop to StyleCop Analyzers.

**Comment by sharwell** [comment]
@yaakov-h I believe StyleCop Analyzers makes an exception for `_` as a parameter name.

**Comment by yaakov-h** [comment]
@sharwell Ah, you're right - it was the multiple-underscore ones it didn't like, and I changed single-underscore ones at the same time. https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1606

**Comment by quinmars** [comment]
[MoreLINQ](https://github.com/morelinq/MoreLINQ) uses the underscore for local functions all over the place. For example:


```csharp
public static IEnumerable<T> Pipe<T>(this IEnumerable<T> source, Action<T> action)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    if (action == null) throw new ArgumentNullException(nameof(action));

    return _(); IEnumerable<T> _()
    {
        foreach (var element in source)
        {
            action(element);
            yield return element;
        }
    }
}
```

It has more than 100 stars though.

**Comment by aluanhaddad** [comment]
@eyalsk 
> Yeah but the candidates were few and iirc required more changes to the language so they were pragmatic about it and given the amount of people that are using it, the amount of efforts required to make it work as an ignore character just make sense and let's be honest it looks good.

I'm sorry to belabor this and I agree that  `_` looks good.

However while I am, as you know, [by no means above quibbling over trite syntactic matters 😹](https://github.com/dotnet/roslyn/issues/115#issuecomment-73829314), my understanding from
@MadsTorgersen's comment in [https://github.com/dotnet/roslyn/issues/16640](https://github.com/dotnet/roslyn/issues/16640#issuecomment-274281922), is that `_` was chosen primarily because of user feedback.

There is a much user feedback, here on GitHub and elsewhere but the designers of C# are wise, doing what is best for the language. They know that some feedback, no matter how earnest, cannot be acted on.

However, we are now talking about deprecating an identifier to allow for new syntax.

Powerful features like the `var` keyword for local type inference did not break existing code.

The code
```C#
void M()
{
    int var = 1;
    Console.WriteLine(var);
}
```
still works fine. However, had `var` necessitated deprecated `var` as an identifier, I think it still would have been worth it.

Perhaps ironically, the preference for `_` is precisely why existing code like
```C#
var count = 0;
var button = new System.Windows.Forms.Button { Text = "Click me" };
button.Click += (_, e) => button.Text = $"Clicked {++count} time{(count is 1 ? "" : "s")}";
```
is now problematic.

I know that this is a done deal, and I will happily use `_`, I am just a bit concerned.

**Comment by AdamSpeight2008** [comment]
Can it not the meaning be inferred from usage? If the `_` is used as a parameter and also used within an expression / statement of this method, then infer it as an **identifier*, otherwise infer *discard*.  That way it should preserve the meaning of exist source-code.

**Comment by HaloFour** [comment]
@AdamSpeight2008 

That's exactly what the compiler does today.  The problem is that for a developer it can be difficult to tell when any particular identifier happens to be in scope.  That becomes problematic when you intend to use a discard for an `out` parameter, or intend to discard the return value from some function.  The compiler can't possibly determine the actual intent of the developer and since it must error on the side of backward compatibility the result is that the developer inadvertently overwrites some field or local.

Your two examples above only different academically.  Their behavior is identical.  In those cases even if there is ambiguity it doesn't matter in the least.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
There is a difference in how they are highlighted by the syntax highlight, which makes the discard a different colour. That difference will help the developer distinguish between discard / identifier usage.

**Comment by HaloFour** [comment]
@AdamSpeight2008

Which won't help outside of Visual Studio.  And that assumes that the developer even notices.  The difference between throwing a value away or accidentally overwriting something shouldn't be distinguished through syntax highlighting.

**Comment by AdamSpeight2008** [comment]
@HaloFour Having the ability to change the styling of discards vs identifier should be available, at the moment you can't do this.

**Comment by eyalsk** [comment]
@aluanhaddad 

> @MadsTorgersen's comment in https://github.com/dotnet/roslyn/issues/16640, is that _ was chosen primarily because of user feedback.

I understand, thanks. ;)

> However, we are now talking about deprecating an identifier to allow for new syntax.

I agree, when they made this decision they should have thought more about the consequences and maybe even be more transparent about it and say something like "Okay, community, bear in mind that if you want this then it means that if it will hindered readability we will have to deprecate it." then the feedback they have gotten back then might have been completely different but it seems like they asked for feedback but really already decided on it... 

> still works fine. However, had var necessitated deprecating var as an identifier, I think it still would have been worth it.

I think that it's not exactly the same because they are easily distinguishable at least to me and let's be honest how common is it? however, yeah it's weird spot.

**Comment by aluanhaddad** [comment]
@eyalsk 
> I think that it's not exactly the same because they are easily distinguishable at least to me and let's be honest how common is it? however, yeah it's a weird spot.

I agree. I was actually trying to make two points in a single statement and I failed miserably 😿.

I have no issues distinguishing `var` as an identifier and a keyword I was just using it as a perhaps poorly chosen point of comparison from C#'s past.

`var` is very powerful and yet introduced no breaking changes and no need for deprecating existing identifiers. That is still works today is a testament to good design. But `_` as an identifier is going to be deprecated for something offering less considerably less value, the use of a _particular_ character to denote discards.



> when they made this decision they should have thought more about the consequences and maybe even be more transparent about it and say something like "Okay, community, bear in mind that if you want this then it means that if it will hinder readability we will have to deprecate it." then the feedback they have gotten back then might have been completely different so it seems like they asked for feedback but really already decided on it...

Well said.

**Comment by DavidArno** [comment]
@aluanhaddad,

For what it’s worth, I’d like to see `var` deprecated as an identifier too.

**Comment by jnm2** [comment]
>  when they made this decision they should have thought more about the consequences and maybe even be more transparent about it and say something like "Okay, community, bear in mind that if you want this then it means that if it will hinder readability we will have to deprecate it." then the feedback they have gotten back then might have been completely different so it seems like they asked for feedback but really already decided on it...

Wait... are you saying @gafter doesn't believe in free will after all... 😁

**Comment by gafter** [comment]
To be clear, I do not believe we *have* to deprecate `_`. I just think it is worth considering. The LDM has not triaged this suggestion yet.

**Comment by quinmars** [comment]
> When Jon Skeet's code fails to compile the compiler apologises.

From the [Jon Skeet Facts list](https://meta.stackexchange.com/a/9138).

@gafter, you might consider this when adding the error message. 😉

**Comment by aluanhaddad** [comment]
@gafter thank you for the clarification.

@jnm2
> Wait... are you saying @gafter doesn't believe in free will after all... 😁

You're maming me feel philosophical ♥

**Comment by thomasd3** [comment]
Visually, '_' is good because it 'aerates' the display and I use _ extensively as (_ =. _.Data).

 If it gets deprecated, then I would also agree that (@.Data) would work; But don't deprecate something until there is  a better replacement.

**Comment by 4creators** [comment]
There is an old saying in .NET API world: _once something is released you are stuck with it for lifetime_. Reason: do not break existing code. The same applies to C# language requiring guarantee for backward compatibility. 

IMO weather someone likes it or not "_" - underbar is available as an identifier and it should remain to be available in the future.

Perhaps it would be better to extend design and prototyping stage for C# features to avoid that kind of issues in future rather than messing with existing code.

**Comment by GeirGrusom** [comment]
@4creators 

> Perhaps it would be better to extend design and prototyping stage for C# features to avoid that kind of issues in future rather than messing with existing code.

Absolutely what they normally do, but this was a bikeshedding issue.

**Comment by Pzixel** [comment]
@4creators and what would you do currently in this situation when all other characters are in use? Emoji instead?

**Comment by 4creators** [comment]
@Pzixel 

> It's good when language is backward-compatible, but sometimes it limits you without giving worthwhile profit. You can't develop language in centuries and still backward compatible.

Evolving language does not have to loose backward compatibility. Just look at how C++ has evolved over last 10 years and it allows for a lot of bad, and hard to understand code and at the same time you may find quite a lot of beautifully written code. It is the users of language who make it easy or hard to understand usually the same goes tru for natural language as well.

**Comment by MkazemAkhgary** [comment]
>I spend, don't know, half of minute until I realized what's happening here. It's weird, it's confusing and spending so much time for that simple code is not ok. So I would happy if this doesn't compile.

that's unfair argument, you can always write hard to understand code, you can always abuse options you have in hand.

**Comment by Pzixel** [comment]
> Evolving language does not have to loose backward compatibility. Just look at how C++

You know, this example doesn't help you as well as it helps me. C++ become unsupportable and sometimes it's better and easier to write and understand code on another language, e.g. Rust, than other C++ guy's code.

> that's unfair argument, you can always write hard to understand code, you can always abuse options you have in hand.

I understood this example as a sample of underscore-identifier feature fair use, not abuse.

**Comment by DavidArno** [comment]
@4creators,
> Evolving language does not have to loose backward compatibility. Just look at how C++ has evolved over last 10 years and it allows for a lot of bad, and hard to understand code...

You are right; a language doesn't have to sacrifice backward compatibility to evolve. But your example of C++ proves why keeping backward compatibility leads to problems. Sacrifice backward compatibility in a few cases and the language can evolve cleanly, not end up like a dog's dinner like C++.

Breaking backward compatibility just for the sake of it is not good. But occasionally, breaking it really helps. Getting rid of underscore-only identifiers would really help.

**Comment by MkazemAkhgary** [comment]
I think `_.Foo` is cleaner than `@.Foo`... I don't know how to describe it, so ill give example. you probably get headache if you try to read Chinese writing because of all of that crooked shapes.

`_` is way less crooked than `@`.

**Comment by Pzixel** [comment]
@MkazemAkhgary you don't choose between `_.Foo` is cleaner than `@.Foo`, but between `@.Foo` and `_ => _.Foo`. I find the latter much clearer.

**Comment by MkazemAkhgary** [comment]
@Pzixel if `_` becomes deprecated then `_.Foo` will be a valid syntax too. so between `_.Foo` and `@.Foo` I find `_.Foo` less noisy and cleaner.

I don't see how `_.Foo` is not valid in that case?

**Comment by eyalsk** [comment]
@MkazemAkhgary Well, if they will deprecate it then it will probably take some time before it's going to be completely disallowed whereas `@.Foo` can be done today.

**Comment by Pzixel** [comment]
@MkazemAkhgary if `_` is lambda parameter then it's better to use `@` and to not write arrows and so on at all. It it's a variable, please, don't name it so.

**Comment by MkazemAkhgary** [comment]
there are 3 ways I can think of, but I think only one of them should be eligible.

 1. `_` remains as identifier, new lambda syntax will be `src.Select(@.Foo)`, old syntax like  `src.Select(_ => _.Foo)` will be still valid.

 2.  soon `src.Select(@.Foo)` becomes new lambda syntax and  after that `_` becomes deprecated with only one usage i.e discards.

 3. `_` becomes deprecated in future, after that `src.Select(_.Foo)` becomes new lambda syntax. so `_` has both discards usage and shorthand lambda usage.

In my opinion, option 3 is best. don't rush on things, wait for language to slowly become evolved but in much cleaner form and shape.

**Comment by DavidArno** [comment]
@MkazemAkhgary,

Thanks for the three point description, as I was getting really confused by the talk of `_.Foo`.

However, I have to say that I think option 3 is a truly awful idea. Removing `_` as an identifier, to then make it both a discard and a lambda shortcut just makes no sense to me. The only option that I'd favour of the three is option 2: it gets rid of `_` as an identifier; it makes `_` only a discard; and it uses `@` as a lambda shortcut. That's a triple win in my view.

**Comment by orthoxerox** [comment]
On the other hand, it looks like F# might get `_.Foo` as a lambda shortcut (albeit only in this specific case): https://github.com/fsharp/fslang-suggestions/issues/506

**Comment by Vlad-Stryapko** [comment]
@DavidArno 
> both a discard and a lambda shortcut just makes no sense to me.
Once again bringing up Scala's design, that's exactly what they have and it's fine most of the time, though it does cause some confusion for newcomers in certain scenarios with lambdas.

Overall, I still think option 3 is the best one to have. We're a little bit in subjective syntax ground here, but for me `_` looks way cleaner than `@`.

**Comment by jnm2** [comment]
Just ran across this:

```cs
fixed (char* _ = str)
{
    // ...
}
```

The pointer is not used, so it's a more efficient equivalent to this:

```cs
var pinningHandle = GCHandle.Alloc(str, GCHandleType.Pinned);
try
{
    // ...
}
finally
{
    pinningHandle.Free();
}
```

**Comment by ErdoganKurtur** [comment]
I have a jQuery-like code library. instead  of `$` it uses `_`. Now you will break my library and all the codebase that references it just because you do not like it? This is another spaces vs tabs.

I believe that running analysis on github repositories for detection of use cases for `_` is a good intention, but all the code in the world is not on github.

**Comment by DavidArno** [comment]
@ErdoganKurtur,
> Now you will break my library and all the codebase that references it just because you do not like it? This is another spaces vs tabs.

This is not the case. The proposed change isn't "just because we do not like it". It is because `_` is the discard symbol, but it is also currently valid as an identifier. This causes confusion, and - assuming your `_` is a global identifier (" jQuery-like code library" suggests it is, but they may be a false assumption on my part), if I used your library, it would prevent me using `_` as a discard as the identifier takes precedence.

Thus the proposal: remove `_` as an identifier and only make it a discard, to make life simpler for everyone in the long run.

**Comment by IllidanS4** [comment]
This should have been thought about when the discard `_` was first introduced. With the already present mishmash of patterns and paradigms, this is a minor inconsistency in C#.

**Comment by gafter** [comment]
Pattern-matching will not permit you to reference a constant named `_` as a constant pattern. It will be interpreted as a discard. Given that, I withdraw this proposal.
