### ISSUE TITLE
try catch expressions.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1068]
this proposal is derived from #1067 so that must be supported first.

This is like relation between `if/else` and ternary operator `?:`, note that #1067 and #973  must be followed first so this proposal becomes just as valuable. 

limitations

 - try expression must have single bracket-less catch statement, use of finally is optional.
 - try and catch/finaly can not have semicolon until end of statement.

breaking any of these rules results in compile time error.

```
var result = try GetResult() catch(exception e) (var x = null, Log(e), x);  // notice only semicolon
```

finally can have block, since returning value in finally is already forbidden.

```
var result = try GetResult()
                   catch(exception e) (var x = null, Log(e), x)
                   finally {
                       // clean up
                   }; // notice only semicolon. semicolon is necessary.
```

**Comment by Richiban** [comment]
This has been requested so many times (or other features very similar to it).

It gets shot down every time because the C# team don't really want to make the use of exceptions any easier than it already is.

If you really want you can create your own utility method:

```csharp

void Main()
{
	var data = 
		Try(
			() => int.Parse("bob"),
			e => 0);
			
	Console.WriteLine(data);
}


public T Try<T>(Func<T> f, Func<Exception, T> @catch)
{
	try
	{
		return f();
	}
	catch(Exception e)
	{
		return @catch(e);
	}
}
```

**Comment by bondsbw** [comment]
I mentioned a similar syntax [here](https://github.com/dotnet/csharplang/issues/1019#issuecomment-337986244):

```c#
var t1 = T() catch C();
var t2 = T() catch (IOException ex) C(ex);
```

I'm not sure if `try` is necessary but I'm not opposed to keeping it.

**Comment by MkazemAkhgary** [comment]
@bondsbw I liked yours.

Its matter of proper discussion, as I mentioned in earlier proposal, people try to make it complicated, arguing multiple catch and finally statements.

but this syntactic sugar is here for simplicity, for simple cases. I don't know how else to convince others that this is not bad thing.

@Richiban 

>It gets shot down every time because the C# team don't really want to make the use of exceptions any easier than it already is.

can I ask why?

**Comment by Richiban** [comment]
@MkazemAkhgary 
>can I ask why?

I think because they feel that it will encourage developers to write methods that throw and then simply call them and catch exceptions instead of using methodologies such as TryXXX or Option types which are much better alternatives. Exceptions are expensive to throw and should only be used if you really do want to unwind the whole stack up to the top level (so your processing loop can continue or you can turn the exception into an error message for the user).

**Comment by bondsbw** [comment]
@Richiban What you are saying is that throwing exceptions is often not the best design.  I agree.

But this proposal is about _catching_ exceptions.  You can't control whether a third-party library throws an exception, but making that situation easier to deal with is worthwhile.

Besides, C# 7 added throw expressions to make throwing exceptions easier.  Surely handling exceptions should be at least as easy as throwing them.

**Comment by yaakov-h** [comment]
@bondsbw throw expressions are typically for exceptions that should not be caught - `ArgumentNullException` appears to be the most popular example and use. There doesn't need to be a symmetry.

**Comment by MkazemAkhgary** [comment]
@Richiban Programmers are human like you, they have brain. mind to decide! surely a good programmer is aware of try catch overheads. also `try` itself has almost no overhead. its catch that is expensive. 

see https://stackoverflow.com/questions/2075151/try-catch-blocks-always-expensive

**Comment by Richiban** [comment]
@MkazemAkhgary It's not catch that's particularly expensive either; it's `throw`.

Anyway, I want to point out that I'm trying to give the language team's opinions on the subject. While I do agree with them, my opinions are not particularly strongly held on this subject and I won't argue very hard to defend them!

Just wanted to give you a heads up that this is a duplicate issue.

**Comment by VisualMelon** [comment]
@bondsbw 
> Surely handling exceptions should be at least as easy as throwing them.

I would disagree: throwing an exception has a very definite effect of asking someone else to deal with it. That is fine, because it violently and visibly exits your code. Handling exceptions is something that people can discuss for _weeks_ and not decide on. Unless _all_ of your code is written to cope with exceptions, making it easier for bits of it to cover over them is probably a bad idea/indicative of bad design.

**Comment by MkazemAkhgary** [comment]
@VisualMelon 

> Unless all of your code is written to cope with exceptions

That's the problem, here is your misconception, _all_ of my code is **not** (and will not be) written to cope with exceptions, where did I say that?

we catch exceptions when ever its reasonable to do so, I don't catch exception where I may be passing null to somewhere, instead I always throw exceptions. that ensures your program will is on working branch.

you catch exceptions when continuation of program is still possible, for example when dealing with IO or when dealing with root of UI functions. 

Again as I said, fair programmer will know when to catch exceptions. programmers are not brainless. so stop arguing _bad design_

_bad design_ is phyton that has no semicolon or brackets because they thought people are brainless and cant understand very basic syntaxes.

**Comment by VisualMelon** [comment]
@MkazemAkhgary 

I do believe we agree on almost everything you have said!

My point was that if a codebase isn't written with the expectation of an exception being thrown (which is common, and is often a _good_ thing) then when an exception is thrown it is easy to end up in invalid (potentially unrecoverable) state, and this does not warrant an 'easy' way to catch the exception. This is not a condemnation of the proposal; I was just disagreeing with one of your comments by saying that I don't think there is a good reason to make catching stuff easier even though rethrowing is.

My comment about bad designs (which I agree python is a stellar example/source of) was - other than just badly worded - that this proposal could be use to 'cover up' existing less-than-ideal designs which the programmer writing the try...catch expression will have to cope with and can't directly modify: good code being used for the purpose it was intended will rarely warrant a feature like this, so its use-cases are limited.

<hr>

I would oppose this feature because I think the cost of added syntax in such a procedural language is greater than the benefit that this feature would provide when applicable. I think that in most of the places that the feature _could_ be used that it would be inappropriate, which could lead to poor quality code in the name of 'keeping things terse' (and judging by some of the other proposals... people really do just seem to want to avoid typing... just ask any python programmer what 'np' means), but this is very much a subjective decision that the Language Design team will surely have their own stance on, and we are sure to disagree on, which is no bad thing.

**Comment by bondsbw** [comment]
The real benefit isn't on making exception handling easy.  It is being able to do so in an expression context, for those who choose to program in a more functional style.

(Interesting observation, the main argument against this seems to be to punish functional-style developers into using procedural-style code.)

**Comment by HaloFour** [comment]
@bondsbw 

Punishment is a strong word.  In functional languages *everything* is an expression.  That's not true in procedural languages and that creates a gap in the expected shape of the two language paradigms.

My concern is always in introducing new syntax which only encourages bad behavior.  A simple `try` expression could do just that.  The nature of such an expression is to convert a failure state into an alternative valid value.  But how frequently does that actually happen?  Is that something that C# should be encouraging?  We'll either end up with sentinel values representing failure, or worse, swallowed exceptions and default values.  With `throw` expressions now at least you can blend rethrowing into the mix.

I'd be all about exploring try expressions.  Maybe C# could borrow a page from F# and include a `try` version of `match`.  Or, [merge it into regular pattern matching](https://github.com/dotnet/csharplang/issues/989) somehow.  But I'm very wary of anything that would be as succinct as a conditional ternary operator.

**Comment by MkazemAkhgary** [comment]
@VisualMelon  I get your point now. try-catch expression by nature translates to try-get-value, rather than dealing with actual exception, even though that default values could be really the final outcome of handling that exception. 

so in conclusion Ill close this proposal, but ill keep #1067.
