### ISSUE TITLE
Unexpected default expression behavior with generics

### ISSUE THREAD

**Issue by d1mnewz** [dotnet/csharplang#1080]
Today I faced pretty dirty bug in my code which I recently updated to the latest version of C#. 
So, the main problem is in the default expression which we used to have like `default(TKey)`. 
Please, have a look at the attached piece of code to better understand the problem. 
```
	public class BaseRepository<TEntity, TKey> : BaseRepository<TEntity>
		where TEntity : class
		where TKey : struct
```

It looks like a casual repository with some entity and for instance int id. 

And the problem is that previously I had 
```
		protected virtual TEntity Upsert(TEntity item, TKey id, bool commit = true)
		{
			if (id.Equals(default(TKey)))
			{
                              ...
			}
```
which worked pretty well for me, but then I I simplified this to `if (id.Equals(default))`
And the behavior of the program turned out to be unexpected for me because now default literal for int translates into `null ` instead of 0. Even through TKey is defined as the structure. Previously default(TKey) defined this thing as 0 for int TKey. 

So the main problem is that default and default(TKey) are considered to be the same, but in fact, they have slightly different behavior which could possibly lead to bugs.

**Comment by Richiban** [comment]
@d1mnewz 

> default and default(TKey) are considered to be the same

Actually, they're not the same (at least, not always). `default` is target-typed, meaning it gets changed to `default(T)` at compile time where `T` is the type expected at the point where you used the `default` expression.

Since the method you called has the syntax `Equals(object other)` what you were getting when you wrote this before:

```csharp
    if (id.Equals(default(TKey)))
    {
        ...
    }
```

was actually equivalent to this:

```csharp
    if (id.Equals((object)default(TKey)))
    {
        ...
    }
```

So `default(TKey)` gives you your struct type but it is then immediately boxed so that it can be passed to the Equals method as an object.

The second way you wrote it, as `default`, the the fact that the expression is supposed to be of type `TKey` is lost and you get:

```csharp
    if (id.Equals(default(object)))
    {
        ...
    }
```

That is why you get null. You need to be very careful when swapping `default` for `default(T)` in existing cases. You might be changing behaviour without realising it.

**Comment by benaadams** [comment]
Does the behavior change if you add the `IEquatable<TKey>` constraint on `TKey`?
```
where TKey : struct, IEquatable<TKey>
```

**Comment by d1mnewz** [comment]
@Richiban 
Yeah, now I understand why it's like that, but actually, that was a surprise for me because I thought default & default(T) are the same.
So I decided to clarify few things here just in case someone else would get into the same trap. 


@benaadams 
That helped a lot, checked the [sources](http://referencesource.microsoft.com/#mscorlib/system/int32.cs,13ad4f778352f7c4,references):72, it does exactly the same thing - boxing object back into struct type and checks with the default value for that struct. 
Probably gonna stay with that solution. 

But the problem is that the default is still `null` and default(TKey) is still 0.

**Comment by benaadams** [comment]
Adding the constraint should mean it would prefer the  [sources](http://referencesource.microsoft.com/#mscorlib/system/int32.cs,80):80 `bool Equals(Int32 obj)` over `bool Equals(Object obj)`

However, with it being `null` would suggest `default` is picking `default(TEntity)` over `default(TKey)`? Maybe it should be giving an ambiguous warning?

**Comment by d1mnewz** [comment]
Basically, that's what my IDE tells me about this code. 
id is [TKey](http://prntscr.com/h6u5gd), Equals uses [IEquitable ](http://prntscr.com/h6u5p2)implementation, [default ](http://prntscr.com/h6u5r9) is from TKey.
The only warnings I get are also [attached](http://prntscr.com/h6u7o6).

**Comment by Richiban** [comment]
@d1mnewz You're right; the real problem here is that Visual Studio is offering the quick fix. Maybe the suggestion code is a bit dumb but they are not the same at all.

This should definitely be filed as a bug but not here. It's a VS / Roslyn issue. Does anyone know where would be best to move this to? Is this merely a UI concern?

**Comment by d1mnewz** [comment]
@Richiban 
I agree that it's not a C# issue, but a code refactoring analyzer's one. 
And the case is to define where default should be simplified and where it shouldn't be.

**Comment by HaloFour** [comment]
https://github.com/dotnet/roslyn/issues/22184

**Comment by CyrusNajmabadi** [comment]
This does not repro for me on 15.5.  If you have 

```c#
        if (id.Equals(default(TKey)))
        {

        }
```

Then it does not offer to change to ```default```.  However, if you have ```where TKey : IEquatable<TKey>```, then it does offer to change it.
