### ISSUE TITLE
foreach?

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1081]
It would be great to have a foreach? construct that would skip if the enumerable was null.

````
IEnumerable<object> Source = null;

foreach?(var item in Source){
  //This won't cause an error.
}

````

**Comment by MgSam** [comment]
Not as concise, but `Enumerable.Empty` works perfectly.

``` C#
IEnumerable<object> Source = null;

foreach(var item in Source ?? Enumerable.Empty<object>()){
  //This won't cause an error.
}
```

**Comment by MkazemAkhgary** [comment]
usually I throw exception if source is null but sounds nice.

**Comment by scalablecory** [comment]
I have an extension method that is simply MgSam's code, so I do:

    foreach(var item in Source.Touch())

This change wouldn't be a big win but I do it often enough that I wouldn't say no to a `foreach` that treats a null collection as one with zero elements.

**Comment by jnm2** [comment]
I'd hate to see a language construct that encourages people to conflate 'null' and 'empty' worse than they already do. Some people would see it as a "safer" foreach and use it defensievly, not realizing that the NRE was actually better. (Far better still, ArgumentNullException or a separate code path to deal wit the separate semantics. Or if a null and empty are semantically equivalent in a certain case, make that explicit using `if` before the `foreach`.)

**Comment by MkazemAkhgary** [comment]
@jnm2 alright then, how does `if(x is {} y)` makes you feel like, it makes me vomit 😭

**Comment by scalablecory** [comment]
@jnm2 there is only so much benefit to catering to green devs, when it is at the expense of everyone else.

**Comment by CyrusNajmabadi** [comment]
> I'd hate to see a language construct that encourages people to conflate 'null' and 'empty' worse than they already do

I disagree.  I've used several languages that are lenient with nil-like constructs, and it honestly feels fine to me when I use them.  For better or worse, nulls permeate the entire ecosystem, and making them painful to deal with just means pain and aggravation when coding.  For example, before ```?.``` and ```??``` code was so much less pleasant to write and maintain.  I'm not against just accepting that nulls exist, and giving simple ```?``` mechanisms to deal with them, instead of having to go full hog into other forms.

That said, for this specific case, it does seem like there are acceptable existing workarounds.  So my support of this particular situation is pretty low.

> @jnm2 there is only so much benefit to catering to green devs, when it is at the expense of everyone else.

This doesn't have anything to do with devs being green or not.  It has to do with the pervasiveness of 'null' and the cost of the excess ceremony necessary to deal with it.  It was precisely this that led to the introduction of things like the null-propagation operator, and it's why there has been so much effort in C# 8 toward better analysis and exposure of null handling.   Better handling of null is a significant feature for most C# devs, not just 'green' ones.

**Comment by CyrusNajmabadi** [comment]
> not realizing that the NRE was actually better at preventing state corruption.

This is only true if you equate null with state corruption.  Whereas, for an enormous number of apis and domains, it's a completely legal and *expected* value representing non-corrupt state.  

This is the crux of the problem.  There is no one true ideology around 'null'.  At least not in .net/c#.  And even if we could pick an ideology that people liked for it, it wouldn't likely never get enough widespread adoption until we got to a point of everything being rewritten (at which point, we'd likely be using a different language anyways).  The reality of the situation is that null exists.  Is here to stay.  And is enormously pervasive.  We can't avoid any of that, or wish it away.  As such, the language embraces that and accepts that being opinionated against that fact only serves to cause people more pain than good.  It's also why, when we have accepted and worked to improve things in this area, the response has been nearly universally positive, with huge adoption across the ecosystem of these new constructs due to their value and convenience so outweighing these sorts of concerns that have been raised.

**Comment by jnm2** [comment]
@CyrusNajmabadi 

> This is only true if you equate null with state corruption. 

I do not equate null with state corruption. Nothing could be further from accurate. `null` for a collection means "take a different approach" at least as often as it means "treat as an empty collection." Right now you have to encode your expectations explicitly. I reject the notion that it's good to blur that line because it's already enough of a pit of failure.

**Comment by scalablecory** [comment]
The line is already blurred, you can't un-blur it. I'd even argue that the blurriness necessary: .NET putting everything on the heap makes `null` the most intuitive way to avoid unwanted GC pressure.

**Comment by CyrusNajmabadi** [comment]
> I reject the notion that it's good to blur that line

I disagree, purely because (IMO), the thought experiment has been tried elsewhere and i've personally not found it to be an issue.  Indeed, the blurring of the lines is what transforms it from a "pit of failure" to a totally fine programming paradigm :)     In other words, it's precisely because null has to be handled so differently that it becomes a pit of fail.

**Comment by CyrusNajmabadi** [comment]
Note: i don't forsee a lot of value coming from a huge back and forth on this :)  I understand and can respect your position.   Needless to say, i think making null handling more pleasant is valuable.  but i also think the primary cases have already been handled well, and not much more work here is necessary at the language level.  (Although, i do really think an ```await?``` feature would be nice, and would be personally preferred before a ```foreach?``` feature.

**Comment by DavidArno** [comment]
@MkazemAkhgary,

How can the follow do anything but fill you with joy? 😆 
```cs
foreach (var item in Source is {} source ? source : new object[]{})
{
  //This won't cause an error.
}
```

**Comment by yaakov-h** [comment]
What's the actual motivation for this?

- If it's symmetry with the `if?` and `await?` proposals, then as much I don't like it, it makes sense to have as a cohesive group of language features.

- If it's because you keep getting NREs when `foreach`-ing, then the warnings from [Non-]Nullable Reference Types should stop you doing that.

- If it's because your codebase regularly uses `null` interchangeably with empty-enumerable, I'd argue that you just shouldn't do that.

I'm mostly in agreement with @jnm2 - there's a big difference between "this box has no items in it" and "there is no box". Null may be pervasive and here to stay, but that doesn't mean we should be using it everywhere, either.

**Comment by CyrusNajmabadi** [comment]
> If it's because your codebase regularly uses null interchangeably with empty-enumerable, I'd argue that you just shouldn't do that.

What's the argument for not doing that?  It seems reasonable to me.

Note: this is one of those areas where the language/APIs incestuously impact each other.  If, for example, the language had been null-tolerant here from the beginning (like you see in some other languages), then it would likely be the case that many APIs would use null routinely for collections.  But, it doesn't, so it's less common.  

> there's a big difference between "this box has no items in it" and "there is no box"

That's domain specific.  For many domains it suffices to mean "i don't have any items".  This is why, for example, APIs like "string.IsNullOrEmpty" exist.  Certainly, one could make the same argument "there's a big difference between no string and an empty string", and that's certainly true *some of the time*.  But for a large set of cases, it's not actually a big difference at all.  

Given that .net has not at all really pushed that there's deep difference, and given that many out there are fine conflating, and given that other languages/domains certainly do this sort of conflation, i don't think it's reasonable to state that everyone has to think there is a large difference here.

Indeed, as i mentioned earlier, i think one of the huge pain points around null is precisely that it blows up on you in domains where people don't need or want it to blow up.  For example, when i did Objective-C development, nil wasn't really painful.  That's because the majority of the language, APIs, and patterns worked well with it.  As such, coding was pleasant without having to continually think about hte distinction, and without having to worry about code blowing up *as much as i need to* with .Net/C#.  

It's not wrong to want to move toward patterns that try to remove null entirely, but it's also not wrong to try to make the experience better when working in domains where null is common.

**Comment by yaakov-h** [comment]
Objective-C's `nil` isn't painful to deal with directly, the pain comes from when something is `nil` that you didn't expect to be, and then have to trace it back to figure out at what point you went from "I expect an object" to "I got `nil`", before it flowed through to the point where you actually have a problem. And sometimes, you can accidentally have a `nil`, and not even notice.

Objective-C and Swift have been moving away from that - Swift has `Optional` now, and Apple mark which APIs return or accept a `nil` value and which ones do not, which allows analysis to throw up warnings, similar to what we're trying to do with C# and NNRT.

When Apple have changed their mind on null value handling after 30 years, it's worth having a huge amount of caution when our proposals approach the behaviour that they are moving _away_ from.

**Comment by lillo42** [comment]
@TonyValenti I like your idea,
but I change sometime,

```
IEnumerable<object> Source = null;

foreach(var item in Source?){
  //This won't cause an error.
}

```

C# can generate this code

```
IEnumerable<object> Source = null;

if(Source != null){
   foreach(var item in Source){
     //This won't cause an error.
   }
}
```
---------------------
I think the discution about null vs/and empty is not here, I think would be better if you make this discution on roslyn or CoreCLR

**Comment by Joe4evr** [comment]
> .NET putting everything on the heap makes `null` the most intuitive way to avoid unwanted GC pressure for oft-empty collections.

Except that the result of `Enumerable.Empty<T>()` remains cached (per `T`), so you can reuse with no GC pressure at all.

**Comment by yaakov-h** [comment]
At which point, the only overhead is method calls to `GetEnumerator()` and `MoveNext()`, versus a simple `cgt.un` check against `0`...

**Comment by alrz** [comment]
Using https://github.com/dotnet/csharplang/issues/867 you could do any of these
```cs
foreach (var item in list ?? return) {}    // if you're not interested in the rest of the method
foreach (var item in list ?? continue) {}  // if nested in another loop
foreach (var item in list ?? break) {}     // if nested in another loop or switch
foreach (var item in list ?? goto label) {} label: // if you're ok with goto
```

**Comment by MkazemAkhgary** [comment]
@alrz but there is not such thing as 

    foreach (var item in list ?? letgo) {} // continue the execution

**Comment by HaloFour** [comment]
@MkazemAkhgary 

> `foreach (var item in list ?? letgo) {} // continue the execution`

Is that the "Frozen" operator?

**Comment by jnm2** [comment]
🤢 lol.

**Comment by Joe4evr** [comment]
> At which point, the only overhead is method calls to `GetEnumerator()` and `MoveNext()`

[Even that enumerator is cached,](http://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,2134) [and is quick to return `false`](http://referencesource.microsoft.com/#mscorlib/system/array.cs,2589) (which puts the "overhead" down to 2 tiny stack-frames now).

[Microsoft's official guidelines also state](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections)
>  **X DO NOT** return null values from collection properties or from methods returning collections. Return an empty collection or an empty array instead.
The general rule is that null and empty (0 item) collections or arrays should be treated the same.

---
@MkazemAkhgary 
`var letgo = Enumerable.Empty<T>();` *Now* that'll work. 🙃 

---
So the moral today is, please don't ever return `null` collections; `Enumerable.Empty<T>()`/`Array.Empty<T>()` is much more optimized than *you* trying to be clever.

**Comment by jnm2** [comment]
> much more optimized than you trying to be clever.

Yes; there's the sometimes counter-intuitive effect that the additional optimization, if any is even measurable, can't compete with the expense of bugs on end users' time and ambiguities on developers' time.

**Comment by aluanhaddad** [comment]
I tend to add
```C#
using static System.Linq.Enumerable;
```
almost everywhere and religiously initialize all values.
So if it is a WebAPI project
```C#
public class OrderModel
{
    public IEnumerable<ItemModel> Items { get; set; } = Empty<ItemModel>();
}
```
and then throw in
```C#
services.AddMvc()
    .AddJsonOptions(options =>
    {
        options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
    });
```
Part of this is precisely to avoid all of the defensive coding that would otherwise lead me to write
```C#
foreach (var item in product.Items.EmptyIfNull()) {...}
```
which I find obscures the logic and often leads to sloppiness.

Now you can't trust third party code in the same way, but I try to avoid being defensive at least within an assembly.

**Comment by Normanator** [comment]
When one's code interacts with multiple sources of data, of multiple SLAs or cleanliness, over multiple choices/revs of IO packages, and multiple sub-types from expanding domains, etc. it is conceivable someone will set null (or skip assigning non-null) on a collection instead of empty.  And, conceivably, what you hold in your hand is the same whether there's nothing inside the box or there just is no box, so some methods can justify treating the cases identically.  

A foreach?(...) really is a nice idea.  Fears of inciting widespread dev debauchery seem a tad reactionary.

**Comment by aluanhaddad** [comment]
@Normanator alright, fair enough. I certainly have comported myself in a reactionary manner in some of these discussions.

So assuming that, for the sake of argument, I am now totally open to this idea, I have a question.

In your day to day work, and assuming the existence of a `foreach?`, about how often would you use the standard `foreach`?

**Comment by Normanator** [comment]
@Aluanhaddad TL;DR  Yes, I think so.

A regrettable percentage of any production code-base is devoted to error-handling, logging, and validation -- cruft that's not business-logic.  A regrettable percentage of bugs are due to gaps in validation often consequent of dev focus on business-logic (not the [billion-dollar null-mistake](https://www.linkedin.com/pulse/20141126171912-7082046-tony-hoare-invention-of-the-null-reference-a-billion-dollar-mistake/)).  Moreover, in reading code, each if-statement makes us pause and parse assuming business-logic, waylaid by cognitively-dismiss-able validation.  

So when [Null-Conditional Operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators) appeared -- halleluiah! -- I rammed C#6 through our dev tool-set fast as I could!   You write what you mean, and deny nulls their attention-seeking.  
Lacking foreach?() left the story incomplete for me.    

Now, when I do need to flag a null as an integrity problem, I can easily explicitly add the null checks -- only now they express business-logic, not obscure it.  

Just my opinion, after working w/ lots of dirty data.

**Comment by aluanhaddad** [comment]
@Normanator I understand the practicality but that is precisely why I don't care for this proposal.

**Comment by Joe4evr** [comment]
> When one's code interacts with multiple sources of data, of multiple SLAs or cleanliness, over multiple choices/revs of IO packages, and multiple sub-types from expanding domains, etc. it is conceivable someone will set null (or skip assigning non-null) on a collection instead of empty.

Well, I would consider that a problem of your data sources and not the language.

**Comment by huysentruitw** [comment]
May I kindly suggest:

```csharp
foreach (var item in Source) when (Source != null)
{
}
```

**Comment by YairHalberstadt** [comment]
@huysentruitw
At which point why not just do 

```csharp
if(source != null)
    foreach (var item in Source) {...}

**Comment by huysentruitw** [comment]
because of nesting of course.

we also didn't need `?? throw new Exception()` or `catch () when ()`, but they're damn handy when you need them.

**Comment by YairHalberstadt** [comment]
But your syntax is no more concise, and is adding a completely new syntactic structure to the language.

**Comment by huysentruitw** [comment]
But you don't have to explain anyone what it does... `foreach? ()` on the other hand is very confusing, it could also mean the foreach skips elements that are `null` f.e.

**Comment by YairHalberstadt** [comment]
Neither do you have to explain an if statement to anyone.

**Comment by huysentruitw** [comment]
And we're back to https://github.com/dotnet/csharplang/issues/1081#issuecomment-443209795

**Comment by YairHalberstadt** [comment]
What I'm saying is `when` is no better than `if`. So there might or might not be point introducing a `foreach?` syntax, but there's definitely no point introducing a `when` syntax, even if it arguably better than `foreach?`

**Comment by DanFTRX** [comment]
I would say that when would avoid an extra nested scope, so it is better than if....

**Comment by markusschaber** [comment]
> we also didn't need `?? throw new Exception()` or `catch () when ()`, but they're damn practical when you need them.

I don't want to nitpick here, but `catch () when ()` actually has semantic differences compared to always catching, and then examining the exception and conditionally rethrowing. Maybe that's the reason why VB.NET (and the CLR itself) had this possibility since ever. :-) (Apart from the fact that it can be abused for side-effects in the `when` condition, e. G. by a logging function which always returns false.)

Note that this is not intended as a counter-argument of conditional foreach...
