### ISSUE TITLE
vararg for local functions

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1099]
I think that signature of local methods can be declared in much more abstract way than normal methods. because local methods are not visible to outside of method and who cares about _exact_ signature?

allow to use `var` for parameter types. **the restriction is that local method must be called at least once, and if called more than once, passed arguments must be match for each call.**

```
int LocalFunction(var x, ref var y) // automatically infer type based on method call.
{
     // type of x and y is defined based on how they are called.
}

var result = LocalFunction(0, ref foo);
```

Yes, for normal methods, type of parameter is important and must be well defined, but for local methods this can be simplified, in my opinion. in my view its not error prone either, because its just like `var` assignment.

**Comment by lillo42** [comment]
I think this will make hard to know type of parameter LocalFunction need,

If I call 2 time localfunction passing different type of  parameter, What should happen in this case?

sample:

```
public void DoSomething(int a, int b)
{
     int c = LocalFunction(a,b);
     int d = LocalFunction(c.ToString(),b); 
     int LocalFunction(var x, ref var y) {  ...   }
}
```

**Comment by MkazemAkhgary** [comment]
@lillo42 I should've bold that 😄 

> the restriction is that local method must be called at least once, and **if called more than once, passed arguments must be match for each call**.

**Comment by HaloFour** [comment]
I think that this proposal would make it incredibly difficult to look at a local function and understand what it does.  The tiny amount of savings of time and verbosity isn't worth making the code much less understandable.

**Comment by MkazemAkhgary** [comment]
well, ofcourse I'm not replacing `int` with `var`. if it was that simple I woudnt propose this. I had a generic type that became fairly large. having types explicitly defined doesn't help too much when half of your screen is gulped by parameters.

Its unfair to say `make it incredibly difficult`, No It doesn't. its a local method, your working area is much smaller, its just inside a single method. and if that method is not small and makes it _incredibly difficult_  to know what it does then you better split it up. @HaloFour

**Comment by HaloFour** [comment]
@MkazemAkhgary 

The size of the function doesn't matter.  The point is that you can no longer look at the function and reason what it will do.  You have to then find the invocation of that function somewhere in the method and try to reason as to the types of the arguments, which could themselves be expressions.  That gets even weirder if you have multiple invocations and the first invocation drives the types.  Further invocations might rely on implicit coersion or conversion to work and a minor refactor which reordered those invocations could completely change the semantics of the local function.

**Comment by HaloFour** [comment]
I'll also add that for these local functions the IDE experience would be terrible.  As the compiler would have no idea what `var` actually meant you couldn't have any reasonable autocomplete or type checking.

**Comment by jnm2** [comment]
[`varargs` means something totally different.](https://github.com/dotnet/roslyn/issues/37)

**Comment by MkazemAkhgary** [comment]
@jnm2 yes, I have that in mind first (passing variable arguments), so the title. but then I didn't see that much reasonable and changed proposal to use var instead.

**Comment by CyrusNajmabadi** [comment]
> because its just like var assignment.

It'snot.  "var assignment" has the expression it uses to analyze directly in line with the variable declaration.  Local functions may not be used until much later.  Furthermore, they themselves may be used in quite complex scenarios where other forms of inference are already happening.  

Furthermore, this means analysis of the function can only happen once it has been seen to be used.  You can't tell if the code in it is legal until that point.  

--

Note: i'm not saying this isn't possible.  But i am saying this adds an enormous amount of complexity.  And it's a bad form of complexity.  Today, 'var' is ok because you can grok enogh information *at the declaration* point about what it is.  i.e. "var customer = GetTheCustomer()".  With local functions you now have no local information to make it clear what the function is doing.  At least with lambdas you have something like ```customers.Where(c => ...```.  Here, these lightweight functions are declared and used in contexts that make their actual signatures clear.  By disconnecting out local functions declarations and their actual signatures, clarity of code diminishes greatly.

**Comment by CyrusNajmabadi** [comment]
> Its unfair to say make it incredibly difficult

No, it is pretty fair :)   You've taken a part of the language that has no complexity currently (figuring out the types of a local function signature is dead simple, and operates just like it does for all other methods), and you're making it get involved with inference (already something enormously complex), and also introducing an entirely new *concept* altogether.  The idea of type signatures (note: actual signatures, not instantiations) being determined at use site instead of declaration site does not exist in C# *at all*.  

--

NOte: when we did 'var' we had the option of trying to allow something like:

```c#
var x;
...
x = ...;
```

whereby we'd examine the usage to figure out the type.  We avoided this *simple* form of the problem because of both the complexity around it, and because we also felt that it really did reduce clarity.  That's just an example where there's a single type involved.  With local functions you now have complex (potentially generic) signatures in play.  The complexity level jumps up another level because of that.
