### ISSUE TITLE
covariance for operator casts.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1101]
Allow something like this

```
public static implicit operator Foo<out T>(Bar<T> bar)
{
    return new Foo<T>(bar);
}
```

so that such implicit assignment becomes possible

```
Foo<object> foo = new Bar<string>();
```

**Comment by svick** [comment]
How exactly would that work? Assuming `Foo` and `Bar` are classes, then neither of them can be covariant. Could you sketch how would `Foo` and `Bar` look like to make this work?

**Comment by MkazemAkhgary** [comment]
Well, this is not exactly covariance, as you can see, the object is cast inside operator implementation, you basically create a new object. @svick

**Comment by CyrusNajmabadi** [comment]
I would much rather have the user call a method on the object to do this.  Your code makes it look as if you have the same object, when you really are getting a new instance (necessary due to CLR restrictions on generics).  Having the code have an explicit method makes that clear and easy to reason about.

**Comment by svick** [comment]
@CyrusNajmabadi 

> Your code makes it look as if you have the same object, when you really are getting a new instance (necessary due to CLR restrictions on generics).

Isn't that an argument against all implicit conversion operators, at least on reference types?

**Comment by svick** [comment]
@MkazemAkhgary 

> the object is cast inside operator implementation, you basically create a new object

Yes, but that's the part that's confusing to me. I'm assuming `Foo` looks something like this:

```c#
class Foo<T>
{
    public Foo(Bar<T> bar) { … }
}
```

But this couldn't work. If your example calls `new Foo<object>(bar)`, with `bar` being `Bar<string>`, then that wouldn't work. That's why I was asking for the code of `Foo`, since maybe you have a different idea of how it looks?

Even better, do you have a real example where this would be useful?

**Comment by CyrusNajmabadi** [comment]
> Isn't that an argument against all implicit conversion operators, at least on reference types?

Yes.

**Comment by MkazemAkhgary** [comment]
You are right, I don't see definite behavior from this proposal.

**Comment by jnm2** [comment]
What about reference conversions that unwrap an encapsulated value?

**Comment by jnm2** [comment]
What about reference conversions that unwrap an encapsulated value? Having those be implicit is quite nice.
