### ISSUE TITLE
Ability to override default(Foo) 

### ISSUE THREAD

**Issue by d1mnewz** [dotnet/csharplang#1105]
I suppose would be handy to have such syntax:
```
	public class Foo
	{
		public int Dummy;

		public override Foo default()
		{
			return new Foo { Dummy = 42 };
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			Foo bar = default; // bar.Dummy is 42
		}
	}
```
or even `public static override Foo operator default()`
Possible problem is that this might lead to unexpected behavior with default literals in code, so this also might need some hint given by analyzers.

**Comment by GeirGrusom** [comment]
Duplicate of #167

**Comment by whoisj** [comment]
The default value of anything is 0. That's because CPU instructions to initialize memory to 0 is cheap. With this suggesting, default would go from a very cheap operation to, at a minimum, a moderately expensive one. 

Consider this code using @d1mnewz suggestion:

```C#
var array = new Foo[500];
```

With the current model the runtime allocates a block of memory `500 * sizeof(reference)` then performs a memory set operation on the new block. Perhaps something like `memset(pnew_mem, NULLPTR_VALUE, sizeof(reference) * 500)`.

However, with the suggested change the code would have to replace the `memset` with a for loop over the constructor at a minimum. This would be multiple orders of magnitude more expensive to initialize an array.

**Comment by GeirGrusom** [comment]
My opinion is that redefining `default` is very bad idea. No offense to @d1mnewz  or @orthoxerox. It requires CLR support and in my opinion there simply is no benefit.

Implicitly assigned values are bad, but when they suddenly turn unpredictable it's even worse.

**Comment by d1mnewz** [comment]
I agree that it might lead to unpredictable behavior and that's why it makes sense to highlight the overridden defaults. 
My point here not to stick to this `default` keyword, but to find out the way for to fill some objects with default values without explicitly setting them in the constructor or something. 
Let's say I'm ok with `var array = new Foo[500];` because I further I am going to fill these objects with the default values I want. But again, there should be a hint/warning that the default is overridden and I should take that into account.

And we can go even deeper with default implementations of interfaces in C# 8.0:
	
```
public class Foo : IFoo
	{
		public int Dummy { get; set; }


		public override Foo default()
		{
			return new Foo { Dummy = 69 };
		}
	}
```
```
interface IFoo
	{
		int Dummy { get; set; }
		IFoo default()
		{
			return new Foo
			{
				Dummy = 42
			};
		}
	}
```

```

class Program
	{
		static void Main(string[] args)
		{
			var foo = default(IFoo); // type is Foo, foo.Dummy is 42
			var Foo = default(Foo); // type is Foo, foo.Dummy is 69
		}
	}

```
Actually, this might be a great illustration of how unpredictable it can be.

**Comment by jnm2** [comment]
Guys, this is a duplicate as has been pointed out. The discussion is cycling. Please close and discuss over at #167 after reading the existing discussion.

**Comment by d1mnewz** [comment]
@jnm2 Sorry for that, closing the issue
