### ISSUE TITLE
concat arrays and values with + operator

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1109]
allow arrays of similar types to be concatenated without use of linq, similar to strings.

```
int[] x ={1, 2, 3};
int[] y ={4, 5, 6};
int[] xy = x + y; // {1,2,3,4,5,6}
```

and also allow to concatenate single parameters to arrays as well.

```
int[] x ={1, 2};
int[] y = x + 3; // {1,2,3}
int[] z = 0 + x; // {0,1,2}
```

It would be nice if this doesn't translate into linq methods for performance reasons. alternative for concatenating many arrays, (eg. `x + y + z + w`)

```
int[] result = new int[x.Length + y.Length + z.Length + w.Length];

Array.Copy(x, 0, result, 0);
Array.Copy(y, 0, result, x.Length);
Array.Copy(z, 0, result, x.Length + y.Length);
Array.Copy(w, 0, result, x.Length + y.Length + z.Length);
```

and alternative for wrapping array in 0 and 1 , (eg. `0 + x + 1`)

```
int[] result = new int[1 + x.Length + 1];
result[0] = 0;
Array.Copy(x, 0, result, 1);
result[1 + x.Length] = 1;
```

**Comment by orthoxerox** [comment]
Could probably by done with shapes/extensions.

**Comment by MkazemAkhgary** [comment]
@orthoxerox it may worth to mention it here so here it goes :) #164 

but I think this needs to be treated by compiler as special case. in order to prevent garbage arrays when concatenating multiple arrays. 

in fact, there is no `+` operator declared anywhere for arrays, but this will be handled by compiler and gets translated to efficient concatenating code.

**Comment by benaadams** [comment]
Doesn't need a change to language; so would be an api request? https://github.com/dotnet/corefx
```csharp
public static T[] operator +(T[] a, T[] b)
{
    var array = new T[a.Length + b.Length];
    Array.Copy(a, 0, array, 0);
    Array.Copy(b, 0, array, a.Length);
    return array;
}
```
> and also allow to concatenate single parameters to arrays as well.

Or would that be add value to all elements? 

Probably would want a `List<T>` at that point as multiple single concats would be very expensive.

**Comment by MkazemAkhgary** [comment]
@benaadams I know what list is :) and I know its value. I gave `0 + x + 1` example to make it more complete example.

but sometimes you want to prefix or postfix an array with single item. I'm pretty sure this happened to any programmer at some point. 

common scenario is when method accepts `params` and you want to pass a value plus array of other values. but that doesn't mean you want a list. because size of array is constant, you just want a prefix or posfix to pass it to next method. (if you want repetitive post/prefixes then you need a list of course)

problem with having actual operator, is that you get temporary arrays. but I see it reasonable now because Its not very common scenario for me to merge two arrays, let alone merging multiple arrays.

I appreciate if you can move this discussion to corefx. thank you.

I also acknowledge that this may give new programmers a bad habit to not to use list. but they shall proceed with caution, If its correctly documented then no one gets confused.

**Comment by CyrusNajmabadi** [comment]
@MkazemAkhgary I've noticed you've opened a *lot* of language requests on csharplang.  Honestly, that's great :).  It's clear you've got a lot of passion, and you really are interested in improving C# and making in a better language.

What i would ask of you moving forward is that when you think you have an idea you want to submit, ask yourself a few questions.  For example:

1. Is this really just something that would make my life better? Or is this something that *many* C# users would benefit from.  
2. Is this feature really necessary?  Can I already accomplish what this feature is asking for in the language today?
3. Do i have a fully fleshed out idea?

I say this because a lot of your suggestions feel (to me at least), like off-the-cuff reactions to a running into an issue while coding, and being unhappy the language didn't work the way you wanted it to.  Or wasn't as terse as you wanted it to be.  That's a normal reaction, and it's totally reasonable to want to want the language to be a better match for you.   However, note that changes to the c# language happen slowly, methodically, and through the work of sponsors who have to really believe in the feature.  So, in order to be successful, you need to be able to do a good job of convincing people:

1. This is important.  It will benefit lots and lots of people.
2. This really really improves the language.  The existing solutions just are not good enough.
3. This idea really works.  It's well thought out, considers the implications, and doesn't have lots of pesky questions blocking it.

--

Or, another way to look at it.  Per language version, the team may take... maybe 5 or so features to completion.  If you open 45 small issues, do you think you can get even 1 of them to make it into the language?  On the other hand, if you took the ones you felt the most strongly about and deeply investigated and fleshed out a full idea, with strong community backing, you could have a chance of it being successful in the future.

All the best!

**Comment by MkazemAkhgary** [comment]
Thanks for the advice. I feel you were in my head for a moment!

Ill keep those in mind. 👌👍

**Comment by benaadams** [comment]
> I appreciate if you can move this discussion to corefx. thank you.

I'm just a random person from the community. If you'd like it I'd suggest [opening the issue](https://github.com/dotnet/corefx/issues/new) yourself as the requester following the [corefx API Review Process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

I'd suggest the api you are after might look something like this:

For operator
```csharp
public static T[] operator +(T[] a, T[] b)
```
For array to array concat
```csharp
public static T[] Concat(T[] arg0, T[] arg1)
public static T[] Concat(T[] arg0, T[] arg1, T[] arg2,)
public static T[] Concat(T[] arg0, T[] arg1, T[] arg2, T[] arg3)
public static T[] Concat(params T[][] list)
```
For item concat
```csharp
public static T[] Concat(T[] array, T arg1)
public static T[] Concat(T[] array, T arg1, T arg2,)
public static T[] Concat(T[] array, T arg1, T arg2, T arg3)
public static T[] Concat(T[] array, params T[] list)
```

If the `operator+` api is approved and implemented; there *could* be a C# language follow up to convert a chain of `+` to one of the `.Concat` methods as per `string` as an optimization on the api. However you would need the api first.
