### ISSUE TITLE
proposal: ref struct should support destructor 

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#1110]
Since ref struct is stack-only, it could have a destructor, which would be executed when the struct goes out of scope. If I write a function library for others, although I provide dispose function, users can still ignore it and forget to release resources. I can't force them to use "using". But if ref struct supports destructor, I can use it to wrap my functions to ensure releasing resources.

For example:
```C#
ref struct A
{
    FileStream file;
    public A(string filename)
    {
        file = new FileStream(filename, FileMode.Open);
    }
    ......  //other member functions
    ~A() //destructor 
    {
        if(file)
        {
           file.Close();
           file=null;
        }
    }
}

static void test()
{
    A a=new A("D:\test.txt");
    ......
} //destructor of "a" would be executed here automatically
```
related issue: https://github.com/dotnet/csharplang/issues/231

--------
Add a rule: ref struct with destructor can't assign each other.

**Comment by jnm2** [comment]
Not thrilled with having two subtly different ways to do the same type of thing. If people get excited about using this construct where they would have used Dispose for resource cleanup, instead of just checking whether the type is IDisposable I now also have to check if it has a destructor and create an inner scope in which to put the declaration to deterministically clean up before running the next code in the method.

**Comment by benaadams** [comment]
Destructible Types https://github.com/dotnet/csharplang/issues/121

**Comment by ygc369** [comment]
@jnm2 
The class lib author should choose just one way, not provide both ways. If he chooses this way, you can use it easier, not harder.

**Comment by jnm2** [comment]
@ygc369 Exactly, the class library authors will only provide one and that means that I'll have to remember to look for _both_ ways every time I use something resource-y.

**Comment by ygc369** [comment]
@jnm2 
You don't have to remember to look for both ways, you can just do the same as before. Because if the class lib author use this way, you could just use it and don't have to release anything, the destructor would be called automatically.

**Comment by jnm2** [comment]
@ygc369 That only works if I don't care how long the resource is held. Sometimes I need to release it before the end of the method. A trivial example is something holding a file lock.

**Comment by ygc369** [comment]
@jnm2 
You can always remember to release resources, so you don't need this feature. But for those people who always forget to release resources, they would be very happy to have this feature.

**Comment by jnm2** [comment]
For those people who always remember to release resources, this feature will slow us down and make it hard to express what's going on when we add an inner scope.

**Comment by ygc369** [comment]
@jnm2 
Look at this:
```C#
ref struct A: IDisposeable
{
    FileStream file;
    public A(string filename)
    {
        file = new FileStream(filename, FileMode.Open);
    }
    
    ......  //other member functions

    public void Dispose()
    {
        if(file)
        {
           file.Close();
           file=null;
        }
    }

    ~A() //destructor 
    {
        Dispose();
    }
}

static void test()
{
    A a=new A("D:\test.txt");
    ......
} //destructor of "a" would be executed here automatically
```
You can still call "Dispose" method, if you want to release resources earlier. But once you forget, the destructor would help you. Does this satisfy you?

**Comment by theunrepentantgeek** [comment]
Instead of adding the new concept of a **destructor** when .NET already has both `IDisposable` and **finalizers**, what if `IDisposable` was used to clean up a `ref struct`?

That is, if the `ref struct` implements `IDisposable`, the compiler emits a call to `Dispose()` automatically, ensuring the resource is cleaned up.

This interoperates cleanly with a **using** clause because of the *existing contract* that allows `Dispose()` to be called multiple times (though, admittedly, it's not uncommon for developers to foul this up).

**Comment by ygc369** [comment]
@theunrepentantgeek 
> if the ref struct implements IDisposable, the compiler emits a call to Dispose() automatically, ensuring the resource is cleaned up when it leaves scope.

Does the C# team have the plan to support this? Or does the current ref struct already have the feature?

**Comment by Joe4evr** [comment]
@theunrepentantgeek One problem here is that [`ref struct`s are not allowed to implement interfaces](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#language-constraints).

**Comment by Joe4evr** [comment]
@ygc369 It looks like your problem *really* comes down to [CS0575: Only class types can contain destructors](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChLsBmfBOAM31gQFcBjGfAZUoG9K+YfgB+PABQBKISMEUR+AL6UlQA==), which applies to *all* structs.

As you are finding out, using a `ref struct` to hold on to resources is not something they should be used for. I get that you want to reap the performance benefits for this stuff, but the mantra here is
![](https://i.imgur.com/Vo20UsT.png)

**Comment by ygc369** [comment]
@Joe4evr 
What is the meaning of "use the new and shiny responsibly"?

**Comment by benaadams** [comment]
An issue is `ref structs` are still copied by value
```csharp
static void test()
{
    A a = new A("D:\test.txt");
    A b = a;
    A c = a;
    ......
} // destructor of "a", "b" and "c" executed here automatically?
```

**Comment by ygc369** [comment]
@benaadams
I've noticed this problem, so I want to add a rule: ref struct with destructor can't assign each other.

**Comment by Pzixel** [comment]
@ygc369 so you want them to be local only? You cannot even return them from the method.

**Comment by benaadams** [comment]
> I've noticed this problem, so I want to add a rule: ref struct with destructor can't assign each other.

At that point you might want to look at [Project Snowflake [pdf]](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/07/snowflake-extended.pdf) 
/cc @mjp41

**Comment by ufcpp** [comment]
@ygc369 

>  I want to add a rule: ref struct with destructor can't assign each other.

It's Destructible Types https://github.com/dotnet/csharplang/issues/121

**Comment by theunrepentantgeek** [comment]
@ygc369 I didn't realise that `ref struct` couldn't implement interfaces; I made the assumption based on your earlier example.

I think the idea still stands though - instead of trying to repurpose **finalizers** as **destructors**, what if the compiler called `Dispose()` if it's present? 

Conceptually, this would be similar to the way **foreach** will properly dispose of an enumerator that implements `IDisposable` without requiring all enumerators to implement it.

**Comment by ygc369** [comment]
@theunrepentantgeek 
That would be OK.

**Comment by ygc369** [comment]
@stephentoub
Is the Destructible Types #121 still in plan?

**Comment by stephentoub** [comment]
> Is the Destructible Types #121 still in plan?

It was never a plan, merely a proposal.

**Comment by ygc369** [comment]
@stephentoub 
It seems that you posted that proposal first. You work for Microsoft, do you know any progress with your proposal? 
I think that if we add such a rule: "ref struct with destructor can't assign each other", then ref struct would become Destructible Type, do you think so?
Furtherly, if this proposal and [Project Snowflake](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/07/snowflake-extended.pdf) both come true, they could work together to provide a mechanism of automatic memory management, instead of GC.

**Comment by ygc369** [comment]
Any progress?

**Comment by ppervink** [comment]
I tend to think of a desire for stack based dispose as both a misunderstanding of the intent of a ref struct and a sign of misuse of the technology.  Think of it more like a reference to a 'something' created (and managed) somewhere else higher in the call stack.  For instance, Memory is a disposable struct (lets go of its handle making it invalid - even for other copies of that Memory struct), MemoryManager is a disposable class (actually manages memory lifetime, not just handles to it).  If you have an instance of MemoryManager class, you can get a Memory struct to pass around a reference to that region of memory (an array or a GCHandle, which may or may not still be valid), but when you get a Span, it's more like saying there's something higher in the stack managing this reference (making it kind of a 'safe' pointer/contract for access to a certain kind of element).  It can only live on the stack, so provided the dispose scope of your Memory is the only place calling methods with the Span it provides and the Manager (if) used to get the Memory isn't asynchronously disposed, your Span should remain valid through any method calls made with it.

A ref struct should, IMO, always follow this nature.  It should be lightweight and specialized for a specific purpose with no need for cleanup, etc. within some parent scope (which is responsible for cleanup, etc).  

Polymorphism makes no sense on a ref struct because it's specialized purpose should be known to consumers of it (it already is the specialized interface - you got it from somewhere and that somewhere is where your polymorphism comes in).  Additionally, it can only live on the stack - it can't be boxed up for consumption by something looking for a specific interface.

**Comment by ygc369** [comment]
Now C# 8.0 has supported disposable ref structs (see https://blogs.msdn.microsoft.com/dotnet/2019/01/24/do-more-with-patterns-in-c-8-0/).
It's getting closer to this proposal, but still lack of following two features:
(1) forbid copy
(2) call dispose() automatically when going out of scope.

**Comment by qrli** [comment]
I don't think it will. It has already got _using declaration_, so I don't think we will have another way to do the same:
```cs
    using var fileStream = File.Open("abc.txt");
```

**Comment by ceztko** [comment]
For me _using declaration_ is almost perfect and adds RAII to C# without really adding RAII. What I'm missing here is at least a warning for not calling the `Dispose` method in case of structs implementing `IDisposable` (or ref structs having a `Dispose` method, I guess). The warning could be automatically silenced if the struct is copied somewhere in the flow, for example in a return method. Also `ref` variables should not issue warning. This assumes it makes no sense having a disposable struct passed to different terminal blocks and not calling `Dispose` in some of them, which I am not entirely sure it's always the case, but it makes 100% sense to me that the `Dispose` method has to be called in at least one terminal block, hence the need for a warning. Apart from silencing the warning, letting copy enabled for structs with `IDisposable` is actually useful/necessary for me: just think for example when passing a _guard_ struct object through different wrapped objects, a pattern that is commonly used in C++. This should answer also @ygc369 who was asking struct that can't be copied, which I think can't really be added to C#. Would it make sense to suggest this warning to roslyn team?

**Comment by sharwell** [comment]
I think it would be difficult to implement this proposal before "Non-copyable structs (#859)"
