### ISSUE TITLE
generic constraint:   where T : ref struct     

### ISSUE THREAD

**Issue by lucasmeijer** [dotnet/csharplang#1148]
Today it's not possible to use a ref struct as a type argument to a generic method or method of a generic type. We'd love to see it become possible to:

```C#
    class A<T> where T : ref struct
    {
        // T t;   <-- this would generate a compiler error. not allowed to leak a T to the heap.

         static void SomethingLegit(T t)
         {
                //totally fine to do ref-struct compatible things with t here.
         }
    } 
```

this feature would be valuable to us especially in combination with: https://github.com/dotnet/csharplang/issues/1147

## Design Meetings

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-09-26.md#ref-struct-improvements

**Comment by VisualMelon** [comment]
Would be nice also if `ref structs` could implement interfaces, and these interfaces be generic constraints. Naturally the `ref struct` can't be converted to an object known to implement an interface, but the members could still be accessible on the type itself. If the runtime emitted independent functions for `ref struct` as it does for normal `struct` this ought to have no within-method cost. I don't know if the call-site is specialised or requires indirection, but this could be an overhead. I should expect that such generic specialisation would at least be applicable to performance-hungry domains that `ref struct` is targeting, even if an extra indirection is required (if I've correctly understood how it already works in the CLR).

``` c#
// generic method is JITted independently for each combination of struct/ref struct type params
void Terminate<T>(T t) where T : ref struct, IAdvanceable
{
    IAdvanceable a = t; // error: illegal conversion

    while (t.Advance()) // statically dispatched
    { }
}
```

There may be some syntax horror if interface disambiguation is required, because `((IFace1)refTypeArg).CommonMethodName()` at least _looks_ like a conversion, but I don't know enough about the compiler to know if this is a significant technical concern.

Again, this would be a somewhat limited capability, but I don't see why it can't run as far as `ref struct`, and would allow, e.g. `ReadonlySpan<T>` to implement `IReadonlyList<T>`, which - while requiring a new method owing to the `ref struct` constraint requirement - would at least preserve implementation independence, and allow such existing and familiar APIs to be adopted from the outset.

**Comment by jcouv** [comment]
Tagging @VSadov @OmarTawfik for thoughts.

**Comment by airbreather** [comment]
@lucasmeijer can you please explain more about how you envision this to tie in with #1147?

> would allow, e.g. `ReadonlySpan<T>` to implement `IReadonlyList<T>`

`IReadOnlyList<T>` inherits from `IEnumerable<T>`, which has `IEnumerator<T> GetEnumerator()`.  Without further changes, that enumerator could legally be stored off somewhere for `MoveNext()` to be called when the original span has gone out-of-scope.

I guess you could have the compiler play detective on everything that originated from the `T` parameter's methods, but that sounds to me like a ton of work (both for the developers to implement and for the compiler to validate) for an unclear amount of benefit.

Obviously, a new interface could be created, but that sorta defeats this:

> allow such existing and familiar APIs to be adopted from the outset.

I'm bringing this up because if we want to support the use case of having one method that accepts either `IReadOnlyList<T>` or `ReadOnlySpan<T>` and then (after JIT) performs no worse than a method that accepted just one or the other, then let's make start an open-ended proposal for **that**, and then maybe the development and design effort would be better spent on a more specific language feature instead of serving as auxiliary justification for more weird generic type constraint soup to enable more ugly code.

Like, a method `where TList : T, maybeRefStructButMaybeNot, IReadOnyList_RefStructCompatible<T>` leaves a bad taste.  But we're looking at designing / developing the language itself here, so we're not restricted to just thinking inside the box.  We're writing the rules, so this is fair game (please go easy on this idea, I don't claim to be a good language designer, it's just a top-of-my-head idea to illustrate a point):
```csharp
static void ActOnAllEvens<T>(listlike_parameter<T> lst, Action<T> action)
{
    for (int i = 0; i < lst.Count; i += 2)
    {
        action(lst[i]);
    }
}

static void Main()
{
    Span<int> someList = stackalloc int[10];
    /* populate someList */
    ActOnAllEvens(someList, Console.WriteLine);

    // lots of businessy code at my work returns ReadOnlyCollection<T>
    ReadOnlyCollection<int> someCollection = SomeBusinessyCode();
    ActOnAllEvens(someCollection, Console.WriteLine);
}
```
That doesn't seem impossible to implement (minimally, you could make overloads for a well-defined set and then restrict how such a method could be overloaded, though that feels ugly), and IMO the code would look a lot cleaner than a magic set of generic type constraints.

I don't expect anything like that to actually happen, but only because I don't see much value in the use case of being able to have one method that accepts either `IReadOnlyList<T>` or `ReadOnlySpan<T>`.

**Comment by VisualMelon** [comment]
@airbreather  I suspect you meant to ping me!

You are absolutely right, `GetEnumerator()` would effectively preclude a `ref struct` inheriting from `IEnumerable` or `IReadOnlyList` etc. which wouldn't work. I'd completely missed that. However, I don't think this is a general concern: if an interface doesn't make sense to be implemented by a `ref struct` then that can be left to the `ref struct`'s author's discretion, and the compiler will already prevent a 'correct looking' implementation of `GetEnumerator()`. I wouldn't support any 'detective' work on the compiler.

I reckon that a `maybeRefStructButMaybeNot` - horrendous as it looks - would be an interesting feature (has all the restrictions of a `ref struct`, but allows another things (perhaps just `struct`s, I haven't thought the possibilities through). I should really further my understanding of `ref structs`: perhaps the `ref struct` constraint _itself_ would allow `ref` variants of normal structs, or something daft like that. This became wishy-washy rather quickly...

> I'm bringing this up because if we want to support the use case of having one method that accepts either IReadOnlyList<T> or ReadOnlySpan<T> 

Yeah, that would certainly be nice. I think we can already wrap an `IReadOnlyList<T>` in a `ReadOnlySpan<T>`, so it shouldn't be a dire concern for new APIs.

**Comment by airbreather** [comment]
> @airbreather I suspect you meant to ping me!

@VisualMelon I should have, yes, though my first line was in reference to this line:

> this feature would be valuable to us especially in combination with: #1147

As for my reply...

> However, I don't think this is a general concern: if an interface doesn't make sense to be implemented by a `ref struct` then that can be left to the `ref struct`'s author's discretion, and the compiler will already prevent, for example, a 'correct looking' implementation of `GetEnumerator()`.

My comments here were in response to:

> I don't see why it can't run as far as `ref struct`, and would allow, e.g. `ReadonlySpan<T>` to implement `IReadonlyList<T>`, which - while requiring a new method owing to the `ref struct` constraint requirement - would at least preserve implementation independence, and allow such existing and familiar APIs to be adopted from the outset.

I don't have data to support the following claim, but my intuition is that **many** "familiar APIs" have such "showstoppers".  Each "showstopper" weakens the value of this part of the proposal, and I think that if it can't buy us the ability for `ReadOnlySpan<T>` to stand in for pretty much any interface that ultimately inherits from `IEnumerable<T>`, then I'm **really** not seeing much value (which is why I prodded about #1147).

> I reckon that a `maybeRefStructButMaybeNot` - horrendous as it looks - would be an interesting feature (has all the restrictions of a `ref struct`, but allows another things [...]

I was thinking that that would be the semantics of the generic type constraint proposed in this issue.  My intuition is that nobody actually wants to literally constrain `T` to be a `ref struct` type; rather, the desire is to be able to use `ref struct` types as generic type parameters.

e.g., I see no **fundamental** reason why your `Terminate<T>` method should reject a reference-type argument that implements `IAdvanceable`.

> I think we can already wrap an `IReadOnlyList<T>` in a `ReadOnlySpan<T>`, so it shouldn't be a dire concern for new APIs.

Can you please elaborate more on what you mean by this?  As-written, that's true for **some** implementations of `IReadOnlyList<T>`, but there exist perfectly valid `IReadOnlyList<T>` implementations that cannot be wrapped in `ReadOnlySpan<T>`, such as implementations that compute their output on-the-fly.

**Comment by benaadams** [comment]
I don't this this would be a constraint on the type; as it wouldn't allow you to use a non-ref struct or class in the method; which I assume isn't the desire. Rather prevent boxing to the heap; so its more of a promise of what the method/class will do with the type; rather than constraining what the type can be.

Perhaps to this end a modifier on the type would be more useful (like `out` and `in` for variance). 

So `ref interface`? Meaning the interface cannot be boxed; but you can still apply it to classes and non-ref structs?

```csharp
public ref interface IReadOnlyIterable<T>
{
    int Length { get; }
    readonly ref T this[int index] { get; }
}

public ref interface IIterable<T> : IReadOnlyIterable<T>
{
    new ref T this[int index] { get; }
}
```

**Comment by VisualMelon** [comment]
@airbreather 
>I don't have data to support the following claim, but my intuition is that many "familiar APIs" have such "showstoppers".

Yes, I would be inclined to agree with your intuition. Even if the use of existing APIs is limited, I'd still be keen to see this capability, so that 'performance hungry' code isn't constrained in expressivity. Assuming it is technically feasible, my main concern is that the syntax could be misleading.

>I see no fundamental reason why your Terminate<T> method should reject a reference-type argument that implements IAdvanceable.

If that is the case... then all the better! However, there are good reasons why the `class` and `struct` constraints exist, so I'm not sure that this is necessarily viable (again, I've not thought this through properly, but it feels too good to be true).

> Can you please elaborate more on what you mean by this?

No, what I wrote doesn't make any sense... terribly embarrassing...

@benaadams
>So ref interface? Meaning the interface cannot be boxed; but you can still apply it to classes and non-ref structs?

This is interesting. Can you provide a more substantial example (i.e. with concept implementation and consumption)? If I'm understanding correctly, it could allay any concerns about code which would be correct when handling a reference-type being illegal/wrong when handling what might be a `struct` or `ref struct` if clearly annotated where the type is consumed.

**Comment by benaadams** [comment]
@VisualMelon extended the sample; that work?

**Comment by nietras** [comment]
I could really use this feature as well in combination with https://github.com/dotnet/csharplang/issues/1147 for eliminating code redundancy in e.g. `Span.Sort` (https://github.com/dotnet/corefx/issues/15329) that I am working on. Using this I could define a generic type argument for the case when just sorting a single span or when there is an extra `Span<TValue>` of items in the same code with zero overhead. And this is hundreds of lines of code. I can give an example of what I would do if poeple are interested.

And I am sure lots of other possibilities will open up if we get it. C++/STL like code for example.

**Comment by BreyerW** [comment]
Do we really need new constraint for that though? By ref structs cannot implement interfaces anyway if i remember correctly (and object -derived methods are expected to throw anyway) so boxing seems to be non issue. I think relaxing rules for ref structs to allow to use them as type argument in methods and delegates ONLY, should suffice?

The benefit would be that existing net core API would instantly benefit from this change after making internal only changes to languages while constraint route would require changes in languages internally AND on surface then discovering ALL apis that would benefit from said constraint and apply this constraint accordingly

**Comment by HaloFour** [comment]
@BreyerW 

I don't think so.  An arbitrary generic method could attempt to box that `ref struct` by casting to an object, or assigning to a field on a reference type somewhere.

**Comment by MichalStrehovsky** [comment]
For allowing interface calls on `ref struct`-constrained generic arguments we need to consider the interplay with the [default interface methods](https://github.com/dotnet/csharplang/issues/288) feature. Consider:

```csharp
interface IAdder​
{​
    void Add(int x);​
    void PlusPlus() => Add(1);​
}​
​
ref struct Adder : IAdder​
{​
    public int Value;​
​
    void IAdder.Add(int x)​
    {​
        Value += x;​
    }​
}​
​
class Program​
{​
    static void Perform<T>(ref T val) where T : ref struct, IAdder​
    {​
        val.Add(1);​

        // 💣 Implicit boxing
        val.PlusPlus();​
    }​
​
    static int Main()​
    {​
        Adder a = default;​
        Perform(ref a);​
        return a.Value;​
    }​
}​
```

I *think* we would currently throw while JITting the `Perform` method with an `InvalidProgramException` because JIT would attempt to generate boxing code for the ref-like type.

Obvious way out would be to error out if the ref struct doesn't implement all interface methods, but that would mean after updating a NuGet package reference that defines the `IAdder` interface (and adds the `PlusPlus` method), we would get a build error, completely defeating the purpose of the default interface methods feature (the purpose being allowing library authors to add methods to their interfaces without breaking consumer code).

We would probably need to annotate the interface in a way that disallows default interface methods for the interface, and any interfaces that require it.

**Comment by MichalStrehovsky** [comment]
> Shouldn't we disallow explicit interface implementation for ref struct anyway? (as they are only available through interface casting which is not compatible with ref struct)

They're callable without boxing through the `constrained. (callvirt)` IL instruction prefix, which is what the C# compiler emits in the `Perform` method above. For the purposes of interface dispatch within the `Perform` method above it doesn't matter whether the interface is implemented implicitly or explicitly. What matters is where the resolution ends up going - whether to an instance method on a value type (where the `this` pointer is a byref), or whether to an instance method on an interface (where the `this` points to an object).

**Comment by xoofx** [comment]
I see. So it means that default interface method on structs will always end-up into an implicit boxing , until there is a plan for the JIT to reify the default interface method at some point...

Ok, not sure I want default interface method anymore... 😅

**Comment by MichalStrehovsky** [comment]
> until there is a plan for the JIT to reify the default interface method at some point

Removing the boxing later would be observable, and a breaking change.

**Comment by scalablecory** [comment]
I'd very much like this constraint added. It should not enforce that what you pass in is a ref struct, but only that your usage of the type is compatible with ref structs.

My goal is to have heterogeneous lookup for our keyed collections, like so:

```c#
class Dictionary<TKey, TValue>
{
   bool TryGetValue<TOtherKey>(TOtherKey key, IEqualityComparer<TKey, TOtherKey> comparer, out TValue value) where TOtherKey : ref struct;
}

var stringMap = new Dictionary<string,int>();

var key = new ReadOnlySpan<char>(...);
var spanStringComparer = ...;
if(!stringMap.TryGetValue(key, spanStringComparer, out int foo))
{
    stringMap.Add(new string(key), 0);
}
```

Given the focus we have now on in-situ parsing, where we try to reuse buffers rather than copying them, this will enable reducing allocations.

**Comment by jcdickinson** [comment]
It might make more sense to make this a modifier of the generic parameter itself, not a constraint:

```c#
public ref struct Span<ref T>
{
}

// or

public ref struct Span<refable T>
{
}
```

This alleviates the `maybeRefStructButMaybeNot` problem that @airbreather mentioned: generic parameter modifiers (covariance and contravariance) have always been constraints that a types/delegates imposes on it itself. This is seemingly the correct place to put this.

As an aside: there is still an argument for `where: maybeRefStructButMaybeNot` because it could be seen as a variant of `unmanaged` (which is basically `definitelyRefStruct`).

**Comment by Gnbrkm41** [comment]
While we're at it.... could we perhaps allow pointer types to be passed when T is constrained to be `ref struct`?

https://github.com/dotnet/runtime/issues/13627 suggests that the only issue with allowing pointer types in generic is issue with boxing (as the runtime currently does not allow boxing pointers). Since `ref struct`s disallow boxing of instances I think it should be okay to allow doing so from the language perspective.

While it does not solve all the problems (pointers are allowed on heap/regular fields, whereas `ref struct`s can't) this certainly would solve some of the problems.

It does look like it'll still require changes in the runtime / IL spec since ECMA-335 disallows pointer types in type parameter, so it might be just better to take dotnet/runtime#13627's approach though.

**Comment by benaadams** [comment]
> While we're at it.... could we perhaps allow pointer types to be passed when T is constrained to be ref struct?

Aside: you can do that with the `unmanaged` constraint (struct that contains no references)

```csharp
public unsafe void M<T>(T* value)
	where T : unmanaged
{
}
```

**Comment by Gnbrkm41** [comment]
Not quite. I meant something like `Example<int*>` where the method definition is `void Example<T>(T value)`.

**Comment by xoofx** [comment]
> Not quite. I meant something like Example<int*> where the method definition is void Example<T>(T value).

You can't, because pointers are not objects (unlike other primitives and structs), so they can't be boxed: `object Example<T>(T value) {  return (object)value; }` is just not possible with a pointer.

**Comment by benaadams** [comment]
> Not quite. I meant something like `Example<int*>` where the method definition is `void Example<T>(T value)`.

What could you do with it in that situation? `int*` as a vague `T` would have no methods and no operations.

With `Example<T>(T* value) where T : unmanaged` you can do pointer arithmetic and casting...

**Comment by Gnbrkm41** [comment]
> You can't, because pointers are not objects (unlike other primitives and structs), so they can't be boxed: `object Example<T>(T value) { return (object)value; }` is just not possible with a pointer.

Which is why I asked if we could make it possible with `where T : ref struct` as the constraint would disallow boxing.

> What could you do with it in that situation? 

For example, basic generic collection types e.g. types under `System.Collections.Generic` can't be used because `T` can't be pointers, even though there would be no problem for doing so since they're just special numbers. 

Note that in this specific example allowing pointers when T is constrained to be `ref struct` is going to help (`System.Collections.Generic` allows any types), but IMO allowing pointer types to be freely used in unconstrained generic can help simplify certain codes around the use of pointers.

...Maybe it's a bit backwards to allow this first here. Probably a separate issue for this would be a better idea.

**Comment by 333fred** [comment]
We're going to be doing some feature triage on Monday. I'm somewhat interested in championing this proposal, as well as a sibling proposal (that hasn't yet been opened as far as I can tell, I'll open one later) that would allow ref structs to implement interfaces, just never be boxed or converted to that interface. This would theoretically allow you to write generic code that operates on a ref struct where you have constrained that struct to an interface type, so you can do more than just treat it as an opaque holder of data. IE, something like:

```cs
public string M<T>(T t) where T : ref struct, Formattable
{
    return Formatter.Format(Resources.Message, t.Args);
}
```

**Comment by YairHalberstadt** [comment]
@333fred 

> as well as a sibling proposal (that hasn't yet been opened as far as I can tell, I'll open one later) that would allow ref structs to implement interfaces, just never be boxed or converted to that interface.

Is #2975 what you're looking for?

**Comment by 333fred** [comment]
Yep, something like that. I had been thinking about the DIM scenario there, and a ref interface is an interesting way to handle it. I'm not sure how acceptable it would be, given that you'd have to introduce an entirely new set of interfaces, but it's an idea to consider.

**Comment by YairHalberstadt** [comment]
I'm not sure that's possible:

Consider the following example that must be legal:

```csharp
public interface I { int P { get; } }
public int M<T>(T t) where T : ref struct, I => t.P;
```

And this which must be illegal:

 ```csharp
public interface I { int P =>  this.GetHashCode; }
public int M<T>(T t) where T : ref struct, I => t.P;
```

That would make adding a DIM a breaking change, which would defeat the purpose of DIMs.

**Comment by 333fred** [comment]
@YairHalberstadt I understand that. The question is if that tradeoff is worth having to redefine many base interfaces in order to make use of the feature. Regardless, these are all questions we'd need to address in LDM. I'd probably lean more towards ref interfaces, but we probably want to consider all possibilities.

**Comment by YairHalberstadt** [comment]
I think a suitable compromise would be to add a marker to an interface that promises it will never implement any DIM. Adding that to IEnumerable would be non-breaking. Ref structs could then implement such interfaces, and be used ( combined with the ref struct constraint) as a type parameter.

**Comment by benaadams** [comment]
Would be nice to have an open constraint; so you could enforce "this method doesn't do any boxing/storing on heap"; so it would be valid for `ref struct`s; but also valid for classes and regular structs to use (since you can't overload by constraint)

**Comment by benaadams** [comment]
@VictorNicollet's [NoAlloq](https://github.com/VictorNicollet/NoAlloq) : LINQ for Span\<T\> might be something to consider when designing this feature.

Especially the ["Issues and Limitations"](https://github.com/VictorNicollet/NoAlloq#issues-and-limitations) section

> ## Issues and Limitations
> 
> Since any type capable of reading from a `Span<T>` must be a `ref struct`, the `SpanEnumerable` defined by NoAlloq cannot be stored as a member in a class or non-`ref` struct and cannot be used within the same function as `await` or `yield return`. 
> 
> Moreover, since `ref struct` types cannot implement interfaces, there is no easy way to hide the complexity of the types used by NoAlloq. For example, by writing: 
> 
> ```csharp
> Span<User> span = ...;
> var alive = span.OrderBy(span, x => x.Name).Where(x => x.IsAlive);
> ```
> 
> The type of the `alive` variable is: 
> 
> ```csharp
> SpanEnumerable<User, User, 
>     SecondaryWhereDelegateProducer<User, User, 
>         OrderingProducer<User, string, DelegateExtractor<User, string>, Comparer<string>>>> 
> ```
> 
> As such, creating a function that returns such a value, or takes such a value as argument, is rather tedious, even by using generics and constraints: 
> 
> ```csharp
> WithAliveUsers(SpanEnumerable<User, User, TProducer> aliveUsers)
>     where TProducer : NoAlloq.Producers.IProducer<User, User>
> ```

**Comment by ThiagoT1** [comment]
So, IIUC, is it safe to say DIM just made ref structs adoption a whole more difficult?

**Comment by jcdickinson** [comment]
> @benaadams Would be nice to have an open constraint

Just to reiterate, today this is done with the covariance and contravariance constraints (which disallow return and parameters of that type in the type that defines them). This might be the most consistent place for this (but it would now work in places where the `in`/`out` constraints don't):

```
public ref struct Span<ref T> {
}
```

`where T: ref` would make vastly more sense when you actually want a type parameter to be a stack type, instead of when you can support a stack type safely.

**Comment by IllidanS4** [comment]
I feel I should emphasize one thing (to reiterate @benaadams): `ref` constraint should constrain only the creator of the generic type/method and not the consumer, unlike other constraints, which do the precise opposite. Optimally, you should be able to use any type for a generic parameter with just a `ref` constraint.

```cs
class A<T> where T : ref
{
} 
```

`A<Span<int>>` should be obviously usable, but also `A<int>` or `A<string>`. That's why I use just `ref`, since although `ref struct` could be usable (instead of `ref, struct`), `ref` alone is enough.

Also I don't really see why the following code should be illegal:
```cs
public interface I { int P => this.GetHashCode(); }
public int M<T>(T t) where T : ref struct, I => t.P;
```
If a normal `struct` is passed as `T`, it is boxed and there is no issue. If a `ref struct` is passed as `T`, well then it should *completely* implement `I`, ignoring all default methods. Adding a default method to `I` would simply be considered a breaking change for `ref struct` implementers.

Or, as a wild thought:
```cs
public interface I
{
    int P { get; }

    int M() where this : ref
    {
        return P + 1;
    }
}
```

`M` would be translated to something like this:
```cs
static int M(ref T self) where T : ref
{
    return self.P + 1;
}
```

**Comment by timcassell** [comment]
A generic constraint tells me that it can _only_ be that, because constraints cannot say "this or that" only "this and that", so it wouldn't work with regular structs or classes. Perhaps an attribute on the generic type could do the trick instead of a constraint to indicate to the compiler that it does not escape.

```cs
public void DoStuff<[DoesNotEscape] T>(T arg)
```

**Comment by IllidanS4** [comment]
Thinking about this more, I agree that `ref T` as a parameter is the best way to express this, because it matches perfectly what `in` and `out` already mean in the same position, and is intuitive in the way it affects the code. Think of it this way:
```cs
IEnumerable<T>
// Allows everything inside, but restricts the consumer

IEnumerable<out T>
// Disallows some things inside (using T as a parameter), but gives the consumer additional options (can contravariantly cast)
```
Compared to `ref T`:
```cs
IEnumerable<ref T>
// Disallows some things inside (which could cause an instance of T to escape), but gives the consumer additional options (passing Span<byte> etc.)
```
Like `in` and `out` constitute a *promise* that nothing inside the type would break their specific restrictions, `ref` is also a promise that every method inside the type is safe when a `ref struct` is passed.

This also means that it should be perfectly safe to add `ref` to *almost every* delegate and interface in the BCL, without breaking *anything*. Just like it was `IEnumerable<T>` once, "upgrading" it to `IEnumerable<out T>` was backwards-compatible since it only gave more options to its users, without impairing the implementers of the interface.

As far as I can tell, this would prevent any sort of duplication of interfaces or delegates, since adding `ref` should be backwards-compatible too. So why not make these changes in .NET together with this?
```cs
public interface IEnumerable<out T> {}
public interface IEnumerator<out T> {}
// Changed to
public interface IEnumerable<ref out T> {}
public interface IEnumerator<ref out T> {}
```
Note that this doesn't impair any prior user of `IEnumerable<T>` since adding `ref` only allows more things to do with it, not less, and it also doesn't affect any implementer (like `List<T> : IEnumerable<T>`) because if a generic parameter is not marked `ref` there, all is the same as usual.

The same for delegates; why not change this?
```cs
public delegate TResult Func<in T, out TResult>(T arg);
// Changed to
public delegate TResult Func<ref in T, ref out TResult>(T arg);
```

----

To sum it up:

* `ref T` is a backwards-compatible *promise* that the type only uses `T` in situations which are safe for a `ref struct` (or any `ref`-like type, perhaps including references in the future if they are allowed as members).
* Adding `ref` to `T` does not affect any user of the type, since `T` still allows any type to be provided and if a non-`ref` type is provided, nothing special happens.
* Adding `ref` to `T` does not affect any implementer, since they would also have to add `ref` to "opt-in" to `ref`-safety. In other words, `ref T` does not "spread", it only limits what the type can do inside itself.
* Removing `ref` from `T` is a breaking change, like removing `in` or `out` is (but perhaps worse).
* Constraints can still be added on `T` like usual, so something like `ref T where T : IDisposable` should work, even though `ref struct`s would have to be allowed to implement interfaces in order for that to work (why can't they anyway? Boxing would still be prevented).
* I don't see any need of also having a separate `where T : ref struct` constraint that would actually limit `T` to be a `ref struct`. Is there a situation where this would be necessary? I think `ref T where T : struct` makes sense, but `ref structs` don't give the user any more options in general by themselves.

----

In the future, I can imagine all of this working (but perhaps not all from the same point in the future):

* `IEnumerable<Span<byte>>`, `Func<Span<char>, Span<byte>>` because that's what people want the most.
* `IEnumerable<TypedReference>` `Func<RuntimeArgumentHandle, TypedReference>` because `TypedReference` finally deserves some love.
* `IEnumerable<byte*>`, `Func<char*, byte*>`. Anything you can't do with a pointer (box it) also cannot be done with a `ref struct`.
* `IEnumerable<ref byte>`, `Func<ref char, ref byte>`. Perhaps a long stretch, but once references are possible as members of `ref struct`s, they could be treated as values in this context. I can imagine `List<T>` implementing `IEnumerable<ref T>` for example, since all you need is to implement `ref T IEnumerator<ref T>.Current` and `List<T>` can do that pretty well (now ain't that nice? 😉).

**Comment by IllidanS4** [comment]
> @IllidanS4 I like the syntax, but you're wrong about IEnumerable and delegates. Existing implementers today can escape the values. The whole point of ref struct is that it cannot be escaped. That is not a backwards compatible change.

@timcassell Existing implementers of IEnumerable *can* escape the values, but the *actual precise* types like IEnumerable and delegates cannot, in their own code. Or I may be mistaken, but in that case, please show me a situation where this could happen. If you have `List<T> : IEnumerable<T>` and `IEnumerable` is defined as `IEnumerable<ref T>`, you cannot create `List<Span<byte>>` because it doesn't have `ref T`, and you cannot cast it to `IEnumerable<Span<byte>>` because that interface is not implemented.

**Comment by timcassell** [comment]
@IllidanS4 Oh I see, I retract my statement.

**Comment by 333fred** [comment]
@IllidanS4 remember that `IEnumerable<T>` implements `IEnumerable`. This wouldn't work for `ref struct` types.

**Comment by IllidanS4** [comment]
> @IllidanS4 remember that `IEnumerable<T>` implements `IEnumerable`. This wouldn't work for `ref struct` types.

@333fred It would work just fine, you just couldn't implement it by returning the same thing like for `IEnumerable<T>`.

Say you have a class that implements `IEnumerable<ReadOnlySpan<byte>>`. Well, you can always implement `IEnumerable` by returning something different, like `byte[]` instead of `ReadOnlySpan<byte>`. Or just `throw new NotSupportedException()`, which is not the best but nobody uses non-generic `IEnumerable` anyway (and definitely not those who care about things like `Span<T>`). Sure, there are situations where you couldn't implement it in a satisfiable way, but that doesn't cause anything unsafe, just the inability to use certain (ancient) APIs.

In the case of `List<T>` implementing both `IEnumerable<T>` and `IEnumerable<ref T>`, it's again easy ‒ `List<T>` already implements `IEnumerable`, so there is no issue here too.

**Comment by atynagano** [comment]
@IllidanS4 
It doesn't seem to make sense to add `ref` to the type argument of the interface.
While `in` and `out` constrain the signature of the interface method, what `ref` constrains is boxing in its implementation. Therefore, there should be no reason to distinguish between interface with `T` and interface with `ref T`, and if `<ref T>` means that `T` is compatible with the ref struct, then it should simply be written as follows.
```cs
interface IEnumerator<out T> {
    T Current { get; }
}

class Enumerator : IEnumerator<Span<int>> {
    public Span<int> Current => /**/;
}

void M<ref T>(IEnumerator<T> enumerator) {
    T current = enumerator.Current;
    // object current = enumerator.Current; <-- error
}

M(new Enumerator());
```

**Comment by IllidanS4** [comment]
> @IllidanS4 It doesn't seem to make sense to add `ref` to the type argument of the interface. While `in` and `out` constrain the signature of the interface method, what `ref` constrains is boxing in its implementation. Therefore, there should be no reason to distinguish between interface with `T` and interface with `ref T`, and if `<ref T>` means that `T` is compatible with the ref struct, then it should simply be written as follows.

@atynagano It would be nice to be able to use an interface with `ref struct` without adding `ref`, but how would the language determine that it is safe?
```cs
interface Interface1<T>
{
    T Method(T arg); // this is fine
}

interface Interface2<T>
{
    T Method(T arg) => arg; // this is fine
}

interface Interface3<T>
{
    T Method(T arg) => (T)(object)arg; // this is not fine
}
```
The compiler would have to be aware of the latter two cases, but *adding* a default implementation shouldn't prevent the interface from being usable, so it would likely have to disallow both default implementations from being used, since it can't inspect the code. But that is more limiting because now you can't use any default implementation with `ref struct`, while with `ref T`, the compiler would check that it behaves well, and thus the implementation would be available as usual. Compare it with `readonly` on structs for example ‒ yes, the compiler could check that a struct can be implicitly `readonly`, but a promise shouldn't be implicit if you could later break it without even realizing.

Also it doesn't seem much consistent to me if you don't want `ref T` on interfaces, but allow it everywhere else: methods, classes, structs, and delegates. Note that `ref`-safety is not determined *solely* by the implementation:
```cs
interface Interface4<T>
{
    T Method(Class<T> arg);
}
```
Here, based on what you imply, the `ref`-safety of `T` would be determined by whether `Class` is defined as `Class<T>` or `Class<ref T>`. I don't like the possibility that changing a class that might be only used once among lots of parameters in one method amongst many would change the whole interface, without you possibly noticing (note that the behaviour of `ref T` would again be consistent here with `in T` or `out T`, as it also imposes a requirement on the usage of `T` as a type argument).

No, it's better to give the promise explicitly, be consistent about it, and let the compiler warn you when it would be broken, like what already happens for `in` and `out`.

**Comment by timcassell** [comment]
> @IllidanS4 It doesn't seem to make sense to add `ref` to the type argument of the interface. While `in` and `out` constrain the signature of the interface method, what `ref` constrains is boxing in its implementation. Therefore, there should be no reason to distinguish between interface with `T` and interface with `ref T`, and if `<ref T>` means that `T` is compatible with the ref struct, then it should simply be written as follows.
> 
> ```cs
> interface IEnumerator<out T> {
>     T Current { get; }
> }
> 
> class Enumerator : IEnumerator<Span<int>> {
>     public Span<int> Current => /**/;
> }
> 
> void M<ref T>(IEnumerator<T> enumerator) {
>     T current = enumerator.Current;
>     // object current_ = enumerator.Current; <-- error
>     // IEnumerator<object> enumerator_ = enumerator; <-- error
> }
> 
> M(new Enumerator());
> ```

I think for that case, the compiler could just not implicitly implement `IEnumerator.Current` if the return value of `Current` is incompatible, and force the implementer to implement it explicitly. I don't think it breaks the `IEnumerator<ref T>` interface in any way.

**Comment by atynagano** [comment]
@IllidanS4
> ```cs
> interface Interface4<T>
> {
>     T Method(Class<T> arg);
> }
> ```

I see, I was not aware of that case. I just didn't feel like making changes to all existing interfaces, but I like the `<ref T>` syntax.

**Comment by atynagano** [comment]
For reference, rust language attaches `Sized` constraints(bounds) to most types, and type arguments are assumed to be `Sized` by default. To loosen this constraint, you must explicitly specify `where T: ?Sized`. To follow this syntax, it become `where T : ?boxable`...?

**Comment by irvnriir** [comment]
related: https://github.com/dotnet/csharplang/discussions/7581?notification_referrer_id=NT_kwDOANTbCLM3OTY5NjkzMDY5OjEzOTQ5NzA0#discussioncomment-7214852

**Comment by jaredpar** [comment]
There is a championed issue with a proposal available now. It has taken into account the feedback here. Going to close this one so we can centralize the conversations on the championed issue / proposal. 

https://github.com/dotnet/csharplang/issues/7608

Thanks for getting the convo started here and everyone for the feedback
