### ISSUE TITLE
Discussion: Static Field Initialization Order in Static Class

### ISSUE THREAD

**Issue by kcragin** [dotnet/csharplang#1153]
This has bitten me several times: https://stackoverflow.com/questions/22927167/strange-behavior-on-static-members-of-a-class-hows-this-possible. This is a direct result of section 10.4.5.1 of the C# language spec, which says static members are initialized from top to bottom, so I understand why it happens.

It seems to me that there is enough information at compile time to generate at least a warning if not an error that initialization will result in some unexpected nulls, or that the behavior could be changed to fully initialize the static members prior to another static member that references the problematic ones.

I guess what I am saying is that if initialization order was basically top to bottom unless it depended on something else (i.e. topologically ordered).

That said, I'm aware there may be breaking changes; if so what are they?

**Comment by theunrepentantgeek** [comment]
In the case shown in that link:
```
public class MyClass
{
    public static string[] SomeAmazingConsts = { Const1 };
    public static string Const1 = "Constant 1";
    public static string Const2 = "Constant 2";
}
```
You could probably generate a warning.

But, the problem gets much, much, harder very quickly. Even without considering calls to static methods, it's easy to create a set of members where there's no topological ordering because of a dependency loop - and as soon as you allow method calls, I suspect it's isomorphic to the halting problem.

Also, you **wouldn't** want a warning for this case:
```
    public static Lazy<string[]> SomeAmazingConsts = new Lazy<string[]>( () => new []{ Const1 });
    public static string Const1 = "Constant 1";
    public static string Const2 = "Constant 2";
```
The problem here is the the compiler can't tell whether the constructor for `Lazy<T>` uses the lambda immediately (which should cause a warning) or whether it's retained for later use (which should not).

**Comment by CyrusNajmabadi** [comment]
> It seems to me that there is enough information at compile time to generate at least a warning if not an error that initialization will result in some unexpected nulls

If you want a warning, you can accomplish this by writing an analyzer that checks for this sort of thing. :)

**Comment by MkazemAkhgary** [comment]
@CyrusNajmabadi why lift it on users if it can be written by _genius_ Microsoft developers?

oh, well I guess ill report it to resharper team instead. they seem to be more active on making smart analyzers 😺  (yes, I don't know how to write one myself. I don't bother learning it though hehe)

**Comment by yaakov-h** [comment]
@MkazemAkhgary Adding new warnings to the compiler is a breaking change, and Microsoft don't have any existing analyzer projects that this would fit into.

**Comment by theunrepentantgeek** [comment]
@MkazemAkhgary Writing a new analyzer isn't rocket science, largely because the support provided by Roslyn is really good. Here's a talk from Microsoft Ignite New Zealand 2015 that shows how it's done:

https://channel9.msdn.com/events/Ignite/Microsoft-Ignite-New-Zealand-2015/M385

Admittedly, Ivan probably qualifies as a *genius Microsoft developer* (I've worked with him), but this talk shows that you don't have to be one yourself.

**Comment by yaakov-h** [comment]
The first time you do it, it **is** like rocket science.

It gets progressively easier after that. 🙂

**Comment by jnm2** [comment]
> The first time you do it, it is like rocket science.

In my experience, yes. Because things that work one day don't seem to work the next. Which is what would happen to me if I became a rocket scientist. 😆 Though I'm still impressed that SpaceX was founded by people who didn't know rocket science either.

(To be fair, it's the whole debug-VSIX experience I'm really complaining about here. I simply ran out of time to cope with it at work; it wasn't practical.)

**Comment by kcragin** [comment]
Yes I can see the problem getting exponentially harder. Still I wonder if it would be worth it for the simple cases, perhaps involving properties only and at a few levels at most. Solve 90% and let the rest of the 10% go.

While it's bit me I don't feel *that* strongly about it even though it forces one to think of ordering when elsewhere in the language we don't think about that (usually).

**Comment by CyrusNajmabadi** [comment]
> why lift it on users if it can be written by genius Microsoft developers?

I didn't say users needed to write it.  I said it could be accomplished through an analyzer.  That would be a lot cheaper and more effective than trying to push a breaking change through the language.

**Comment by CyrusNajmabadi** [comment]
> Still I wonder if it would be worth it for the simple cases, perhaps involving properties only and at a few levels at most. Solve 90% and let the rest of the 10% go.

That's definitely a case for an analyzer.  By and large this is *not* how the language/compiler likes to operate (especially when it would cause breaking changes).
