### ISSUE TITLE
Extended expression tree syntax

### ISSUE THREAD

**Issue by ijsgaus** [dotnet/csharplang#1273]
1. Еnable all available Expression in lambda syntax (include Loops. Ifs, Variable declaration, Cases, ? and ?? operators).  
This is only language changes.
2. Enable quasi-quotation in expression. This may need additional library.

**Comment by svick** [comment]
There is already an issue for point 1: https://github.com/dotnet/csharplang/issues/158.

Could you explain what quasi-quotation is how would it be useful?

**Comment by ijsgaus** [comment]
Quasi-quotation can enable conditional generation of expression, EG:

**Comment by ijsgaus** [comment]
#158 need to implement new expression subtypes. I propagate only use existings

**Comment by svick** [comment]
> Quasi-quotation can enable conditional generation of expression

You can do this with [LinqKit](https://github.com/scottksmith95/LINQKit):

```c#
public static Expression<Func<Data, bool>> Filter(Expression<Func<Data, bool>> expression)
{
    Expression<Func<Data, bool>> result = p => p.BirthDate > new DateTime(2000, 1, 1) && expression.Invoke(p);

    return result.Expand();
}
```

Doing something like this is certainly a common requirement, but I'm not sure if adding special syntax for this would be worth it, since it can be done using a library. Also, the syntax couldn't be `@expression(p)`, because that's already valid syntax. `@` is used for escaping keywords (and can be also used to "escape" any other identifier).

> #158 need to implement new expression subtypes. I propagate only use existings

I think that's not different enough for a separate issue. You might want to comment on that issue about your suggestion.
