### ISSUE TITLE
Proposal: unassigned pattern variables be assigned the default value of their type.

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#1326]
@taori commented on [Thu Feb 15 2018](https://github.com/dotnet/roslyn/issues/24879)

**Version Used**: 
C# 7.1

**Steps to Reproduce**:

![grafik](https://user-images.githubusercontent.com/5545184/36285095-9770926e-12aa-11e8-9419-cff6171f0ef5.png)

**Expected Behavior**:
no initializer error
**Actual Behavior**:
initializer error

A workaround is to rename variables on the end of it with another pattern matching expression, which is obviously rather ugly. Could pattern matching be modified so the null check resolves this issue?

---

@gafter commented on [Thu Feb 15 2018](https://github.com/dotnet/roslyn/issues/24879#issuecomment-366092620)

No, it is not supposed to be used like this.

A pattern variable is only _definitely assigned_ when the pattern matches. Since you're using the pattern variable `activateFeedbackPage` outside of the `if` statement where the pattern-matching operation occurs, it might not be definitely assigned where you use it.

---

@gafter commented on [Thu Feb 15 2018](https://github.com/dotnet/roslyn/issues/24879#issuecomment-366092994)

> Could pattern matching be modified so the null check resolves this issue?

Moving to csharplang to be considered there.

**Comment by bondsbw** [comment]
Are there other cases where a null check removes an error condition?

**Comment by gafter** [comment]
> Are there other cases where a null check removes a compile error condition?

I don't think that is literally what is proposed. Unless I'm mistaken, the proposal is that pattern variables are always definitely assigned in their scope. They have the appropriate value after the pattern-matching operation succeeds, or the default value of their type (e.g. `null`) otherwise.

**Comment by taori** [comment]
@gafter that is exactly what i was hoping for. yes.

**Comment by Joe4evr** [comment]
I don't like this proposal. The definite assignment rules exist for a reason, and we've already gone through a debate of "it should just be default value" with Make-man.

Why are you not just doing this instead?
```cs
if (sender is IBusyFeedback activateFeedbackPage)
{
    await activateFeedbackPage.QueueBusyAsync();
    await activateFeedbackPage.DoNextThingAsync();
}
```

**Comment by jnm2** [comment]
I don't like the way this interacts with value types.

**Comment by yaakov-h** [comment]
I feel like this makes logical sense for reference types, but I really _really_ don't like the idea of defaulting for value types.

**Comment by HaloFour** [comment]
I'm with @Joe4evr, these conversations have already happened multiple times.  The definite assignment rules are probably the best way to guard against accidentally using the pattern variables when the pattern hasn't matched.

**Comment by taori** [comment]
@Joe4evr You should take into account the actual code instead of simplifying the code to match your argument. I am doing ActivateAsync on a different async, while my 3rd set of instruction is based on the pattern for the first set of instructions

**Comment by taori** [comment]
Besides all this i see why you wouldn't want pattern matching to work like this, but using pattern matching in that very scenario renders me unable to use pattern matching at all.

**Comment by taori** [comment]
> I'm with @Joe4evr, these conversations have already happened multiple times. The definite assignment rules are probably the best way to guard against accidentally using the pattern variables when the pattern hasn't matched.

I imagine that those rules most likely do make sense, but if it comes up that often, does that not indicate that something could be improved about it?

Maybe i'm missing another way of writing this code, but for the sake of briefness, the proposed syntax would be the most comfortable one. What about allowing it on reference types and blocking it on value types? While i see that one would never want to accidentally have a pattern provide a value type at its default, i am sure it would be very useful for code blocks where you're dealing with reference types.

**Comment by gafter** [comment]
> I imagine that those rules most likely do make sense, but if it comes up that often, does that not indicate that something could be improved about it?

Maybe it indicates that we've found the right balance between convenience and safety.

Note that you can assign to the offending variable in an else clause, because part of the compromise is that pattern variables are mutable.

**Comment by Joe4evr** [comment]
> I am doing ActivateAsync on a different async, while my 3rd set of instruction is based on the pattern for the first set of instructions

Extract that out into a local function and call that in between? ¯\\\_(ツ)_/¯

**Comment by DavidArno** [comment]
I still hang on to a desperate hope that the decision to allow pattern variables to leak into surrounding scope in an unusable way will be fixed. But the only way I'd ever want them fixed is by not allowing them to leak.

This proposal is therefore the absolute antithesis to what I'd like to see happen. It takes a bad idea (letting unassigned pattern variables to leak) and makes it even worse (by magically assigning a value to that variable, even though the match failed). Please, never let this happen.

**Comment by DavidArno** [comment]
@taori,

> Besides all this i see why you wouldn't want pattern matching to work like this, but using pattern matching in that very scenario renders me unable to use pattern matching at all.

Even when you use pattern matching the way you are asking it to work (in your example in the OP), you still end up with an ugly approach of having to retest those pattern variables for `null`. I think you are selecting the wrong tool for the job. Your "Ugly code 2" solution seems by far the least ugly, simplest solution to this specific problem.

**Comment by DavidArno** [comment]
One last point here, this proposal would cause problems with nullable reference types. 

As already established by @gafter, `x is T? y` doesn't make sense as a pattern as type patterns never match when `x` is `null`. So with this proposal, we could end up with:
```cs
if (x is SomeType y)
{
    y is not null here. All is good.
}

DoSomethingWithY(y); // y is of type SomeType, not SomeType?, yet it could be null
```
So we'd be removing a restriction (accessing an unassigned variable) and replacing it with the need for a confusing nullable warning around `y` being of a non-nullable type but possibly could be `null`.

**Comment by taori** [comment]
Ok so there are plenty valid reasons about why you don't want them to leak to the outside scope. However the declaration of the variable does leak to the outer scope - What about completely removing it leaking to outer scope?

That way i could write code like proposed, guarding would be safe and i don't have a declared variable which outside of the pattern scope is uninitialized and unusuable anyway. 

Is there an important reason why those variables are leaked to outside scope at all? Personally i've always found it annoying that i can't reuse variable names which have been declared in a different scope. I know you're gonna say "just extract and call that" - which is obviously the correct approach to keep methods slim and single-purposy. But outside of MS there is lots of code maintained, which is just a mountain of spaghetti where you don't want the basic structure of the code refactored because unit testing is just a buzzword thrown around by people. I do hate that myself too, but it's not my decision.

So essentially my point is this: I would love to write code like this:

Version 1
![grafik](https://user-images.githubusercontent.com/5545184/36285095-9770926e-12aa-11e8-9419-cff6171f0ef5.png)

This would be possible if leaking also provided a default value - why you wouldn't want that is perfectly sound to me now. Not happening. I get it.

or this:

Version 2
![grafik](https://user-images.githubusercontent.com/5545184/36310325-f14d9e44-1327-11e8-86b4-20827e620ebd.png)

This would be possible if the pattern variable scope was more strict, similar to how scope behavior works with "let" in javascript. Is there any important reason why it is this way? Currently i'm converting a 25 year old application to C# and i really have to say that their method of coding (declare variables at method entry) and reusing them all the way through the method for assignment and it really is just horrible. So the feeling i got from that during conversion is that reusing variables ist absolutely horrible from a mainteanance point of view.

What if the problem i actually desire to be solved here, is solved by either making the pattern variable scrope behavior even more strict and not leaking variables to outer scope or by introducing "let" to C#. 

So as @DavidArno said:

> I still hang on to a desperate hope that the decision to allow pattern variables to leak into surrounding scope in an unusable way will be fixed. But the only way I'd ever want them fixed is by not allowing them to leak.

Would also perfectly resolve my code scenario too.

**Comment by HaloFour** [comment]
@taori 

That ship has long since sailed after quite a number of somewhat heated debates.  Changing the behavior now would be a breaking change.

The reason the variable scope leaks is to allow for guard blocks like the following:

```cs
if (!(o is int i)) {
    i = 123;
}
// use i here

// or

if (!int.TryParse(s, out int i)) {
    i = 123;
}
// use i here
```

Without the leaking that variable would be locked with the scope and completely unusable, requiring a separate variable to be declared outside of the scope and assigned.  Increasing the verbosity, and in the case of `out` declarations, making the language feature near pointless in numerous scenarios.  To a lot of people that was acceptable, but that's not the decision that the language team took.

Fortunately they did walk back the extent to which the variables leak, which at least helps avoid mutating capture with closures in loops.

**Comment by taori** [comment]
@HaloFour beat me by 11 minutes then. I just typed some code and realized that the variable is not actually unusable and could just be declared in either side of a conditional block, which marks the variable as initiaized onwards. So the only scenario where the code i pointed out would actually work then would be if something like "let" were introduced, since changing leaking now would indeed be a breaking change. Guess i'll look for that proposal here since it most likely has come up already.

Thanks for your input

**Comment by DavidArno** [comment]
@HaloFour,

I had thought fixing leaky patterns wouldn't be a breaking change. I forgot about that horrific botched use of `is`:
```cs
if (!(o is int i)) {
    i = 123;
}
// use i here
```
where a ternary expression can be used to achieve the same thing:
```cs
var i = o is int x ? x : 123; 
```
and then would have allowed those pattern variable names to be reused in subsequent patterns:
```cs
var i1 = o1 is int x ? x : 123; 
var i2 = o2 is int x ? x : 456; 
var i3 = o3 is int x ? x : 789; 
```
Instead, I have to think up different names for those temporary pattern variables.

Oh well, as you say we are where we are. It can't now be changed. 😞

**Comment by taori** [comment]
@DavidArno Unfortunately i can also think of cases where the state of what we do have now, does makes sense. Assigning a variable in the else block of a condition to use its value in the outer scope onwards. My desire is the same as yours here - reusing the variable names without having to make up different names for the same thing. I don't see this changing ever because i see why the language team made it work that way. I didn't find a let proposal so i'm writing one now. That would essentially allow reusage of names and enable both our scenarios.

**Comment by HaloFour** [comment]
> That would essentially allow reusage of names and enable both our scenarios.

Local shadowing has been proposed a couple of times before.  The C# language very intentionally made that impossible to avoid the known logic errors that can result in doing so in languages like C++, so I don't see that as being likely to happen.

**Comment by taori** [comment]
@HaloFour What about a "let" keyword which limits the visibility and usage of a variable to the scope of an expression or the scope in which it is used? Has that been proposed before?

**Comment by theunrepentantgeek** [comment]
I'm pretty sure there's an existing proposal for **let** to be a single-assignment **var** - declaring and assigning a local variable in a single statement with a prohibition on later assignment. I couldn't find it with a quick search though.

**Comment by HaloFour** [comment]
@taori 

I want to say that it's come up in conversation with other proposals but I don't believe I've seen a proposal opened specifically for that.  There have been other proposals that had an eye on that keyword, such as for a statement for of pattern decomposition (which was made irrelevant by scope leakiness) and as shorthand for `readonly var`.

**Comment by taori** [comment]
@HaloFour What do you mean by "made irrelevant by scope leakiness"? My idea of let would be that it strictly limits scope leaking. Was that other proposal different in the way how let works? My thought of it is essentially very similar to javascript

**Comment by HaloFour** [comment]
@taori 

Originally the plan was that pattern variables would be limited in scope, and `let` was proposed as a way to decompose patterns into the outer scope (as well as `guard`):

https://github.com/dotnet/roslyn/issues/6400

**Comment by taori** [comment]
@HaloFour 
That is rather very interesting. So back then let would have been used to extend usage to outer scope. Since that didn't come to happen wouldn't it make sense, to then now use "let" to fill the gap on scenarios where the developers desire is to restrict the scope from leaking? The function of the let keyword would be rather intuitive as well for anyone who experienced how it works in javascript.

Just read some of your statements in the link you referenced. I can see that you dislike the idea of shadowing, but is there a specific reason why you dislike the idea of it if shadowing if it is only possible if the developer explicitly decides to do so? From what i can imagine the SymbolFinder would have to be modified in order to even deal with scenarios where one identifier name results in potentially multiple unique symbols. Are those considerations which make you dislike shadowing or is my impression that you dislike it in general wrong?

**Comment by HaloFour** [comment]
@taori 

> I can see that you dislike the idea of shadowing, but is there a specific reason why you dislike the idea of it if shadowing if it is only possible if the developer explicitly decides to do so?

It makes it too easy to accidentally refer to what you think is the shadowing variable when you intended to refer to the original variable.  Such shadowing also makes it impossible to refer to the original variable.  Neither are desirable and are known vectors for bugs, which is why C# (and Java) forbids it.  To reverse that decision would enable these kinds of bug vectors without solving any real problems, other than making developers name things.

**Comment by svick** [comment]
I think the code that motivated this proposal could benefit from `await?` (https://github.com/dotnet/csharplang/issues/35, currently a candidate for C# 8.0). With that, it could be written as:

```c#
private static async void ViewOnAppearing(object sender, EventArgs eventArgs)
{
    Log.Trace($"{nameof(ViewOnAppearing)}");

    var activateFeedbackPage = sender as IBusyFeedback;
    var feedbackPage = sender as Page;
    var feedbackContext = feedbackPage?.BindingContext as IBusyFeedback;

    await? activateFeedbackPage?.QueueBusyAsync();
    await? feedbackContext?.QueueBusyAsync();

    await? (feedbackPage?.BindingContext as IActivate)?.ActivateAsync();

    await? activateFeedbackPage?.ReleaseBusyAsync();
    await? feedbackContext?.ReleaseBusyAsync();

    Log.Trace($"{nameof(ViewOnAppearing)} end.");
}
```

Another alternative would be to use async disposable (https://github.com/dotnet/roslyn/issues/114), with that, the code could look something like:

```c#
private static async void ViewOnAppearing(object sender, EventArgs eventArgs)
{
    Log.Trace($"{nameof(ViewOnAppearing)}");

    var feedbackPage = sender as Page;

    using (await Busy(sender as IBusyFeedback))
    using (await Busy(feedbackPage?.BindingContext as IBusyFeedback))
    {
        await? (feedbackPage?.BindingContext as IActivate)?.ActivateAsync();
    }

    Log.Trace($"{nameof(ViewOnAppearing)} end.");
}
```

Where `Busy` is a method that returns noop `IAsyncDisposable` (wrapped in a `Task`) when passed `null`.

**Comment by taori** [comment]
@HaloFour 

> It makes it too easy to accidentally refer to the shadowing variable when you intended to refer to the original variable. Such shadowing also makes it impossible to refer to the original variable. Neither are desirable and are known vectors for bugs, which is why C# (and Java) forbids it. To reverse that decision would enable these kinds of bug vectors without solving any real problems, other than making developers name things.

The way i see it, it would be impossible to refer to the original variable. Maybe i'm missunderstanding the concept of shadowing here. The bit on bug vectors without solving real problems is fair enough of course.

if(someVariable is SomeType let casted)
 DoSomethingWithIt(casted)
if(someVariable is SomeType let casted)
 DoSomethingElseWithIt(casted)
if(someVariable is SomeOtherType let casted)
 DoSomethingWithIt(casted)
if(someVariable is SomeOtherType let casted)
 DoSomethingElseWithIt(casted)

I don't see how shadowing would potentially introduce bugs here though. Maybe i don't have the necessary fantasy to think of edge cases where it would, but in my mind introducing let would result in the variable ceasing to exist beyond the scope of the expression or the block where it is used so it's scope would never go beyond if/else, foreach, switch etc. 

I'm not going to argue about it beyond this point though, since you probably have a better idea about this and i just thought it would be neat if it could be used that way.

@svick Yes. the code would greatly benefit from await?. I can't wait for that feature to show up.

**Comment by HaloFour** [comment]
@taori 

> The way i see it, it would be impossible to refer to the original variable.

This is pretty contrary to the existing design of C#.  In those cases where you are permitted to shadow in C# you can always refer back to the shadowed version.

> I don't see how shadowing would potentially introduce bugs here though.

It creates the potential for bugs when the shadowing variable accidentally replaces attempts to refer to the shadowed variable within the same scope during a refactor.  The behavior you described is how shadowing and scoping works in C and it was experience with the potential for bugs in that language which inspired the Java designers (and eventually the C# designers) to forbid it.

**Comment by gafter** [comment]
For many of the reasons raised in this discussion, we're not going to do this.

**Comment by rjgotten** [comment]
While this has, for very good cited reasons been closed, has any considered making the definite assignment _user-specified_ by supplying a fallback value similar to default parameters?

E.g. 

```cs
if (x is SomeClass y)
{
  // y is not null
}

DoSomething(y) // y not guaranteed assigned.
```

-vs-

```cs
if (x is SomeClass y = null) 
{
  // y is not null
}

DoSomething(y); // y guaranteed assigned.
```


This also resolves the earlier cited issue with nullable reference types:

```cs
if (x is SomeClass y = null) // not allowed - `null` is not of type `SomeType`, but is of type `SomeType?`
{
  // y is not null
}

DoSomething(y);
```

And it allows definite assignment of a proper fallback value type. E.g.

```cs
if (x is TimeSpan y = TimeSpan.FromSeconds(5))
{
  // y was already a proper caller-provided TimeSpan, so run potentially some logic here
  // e.g. like somthing that validates its upper bound
}

DoSomething(y); // y is definitely assigned, and might have fallen back on the 5 seconds.

**Comment by 333fred** [comment]
That seems significantly less clear than the existing approach:

```cs
if (x is SomeClass y = null)
{
     // y is not null
}
else
{
    y = null;
}

DoSomething(y);
```
