### ISSUE TITLE
Arrays of tuples don't work with `is`

### ISSUE THREAD

**Issue by lcsondes** [dotnet/csharplang#1334]
using System;
    class A
    {
        void Test()
        {
            (object, object)[] a = new (object, object)[1]; // This line has no errors
            var b = a as (object, object)[]; // No errors
            if (a is (object, object)[]) // CS1525: Invalid expression term 'object', CS0443: Syntax error; value expected
            {
                Console.WriteLine("Hello");
            }
            if (a is (object, object)[] c) // CS1525: Invalid expression term 'object', CS0443: Syntax error; value expected
            {
                Console.WriteLine("World");
            }
        }
    }

Naïvely, I expect that if a type can be used to declare a variable, used with `as`, then it would also work with `is`.

**Comment by Happypig375** [comment]
This looks like a compiler bug. Please file this over at https://github.com/dotnet/roslyn.

**Comment by jnm2** [comment]
@Happypig375 I'm not so sure this is a bug. Allowing tuple type syntax, rather than forcing `ValueTuple<object, object>`, would conflict with pattern matching or at least be very confusing.

**Comment by HaloFour** [comment]
I'd conjecture that this syntax is probably not allowed to leave it open for recursive patterns.

**Comment by svick** [comment]
> Naïvely, I expect that if a type can be used to declare a variable, used with `as`, then it would also work with `is`.

This is true for most types, but tuples are an exception. This is because tuple patterns are planned for a future version fo the compiler and so e.g. `a is (object, object)` is intentionally disallowed for now (and will become a special tuple pattern in the future).

But I don't know if this also applies to some types that *contain* tuples, like your example. It certainly seems inconsistent to me that e.g. `a is List<(object, object)>` works, while `a is (object, object)[]` doesn't. Though it's possible this is part of the same limitation as `a is (object, object)`.

**Comment by YairHalberstadt** [comment]
This was fixed by https://github.com/dotnet/roslyn/pull/26088
