### ISSUE TITLE
Proposal: Modify a struct-type property directly, and allow intialization from existing instance

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1347]
# Suggestion:
Use special symbol (such as <=) to modify struct-type properties directly.

# Example:
Suppose we have this struct:

```
struct Person
{
    public int ID;
    public string Name;
    public int Points;
}

```
and this property:

`public Person User { get; set; }`

We can't directly use:
`User.Points += 1;`
It will not compile.

So we have to do this:

```
Person p = User;
p.Points += 1;
User = p;

```
I suggest to use this syntax instead to do the same job as the previous code:

`User <= Points += 1;`

# Another approach:
it will be easier if the  Type initializer can initialize the new instance by the values of another instance:

`User = User {Points += 1};`

In this syntax we allow two new things:
1-	use an existing instance instead of a "new Person ()".
2-	use the += inside the {} because ID have a previous value and can be modified.

The last syntax can be re-written as:

`User += {Points += 1};`

**Comment by svick** [comment]
Is [using `ref`-returning property](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMACAwgWAFADe+GJGKALBgLIAUAlMaUXqaxgKoDO0AdAAoB7GADtgnDAGoAvBgCMAbkYkAvkoxq+0TgOEYArtyiKWpFAGYMUCHAyao23V2gYCGAOYRgGKQD5L1/UN5DFU8UPxOYCg9AGMvOwd8ZlZzDBEvAEkAEWMUixRZAAYMADkAQwBbCFzTC3TbIVFOY1CgA=) not acceptable for you?

**Comment by MohammadHamdyGhanem** [comment]
How can I use it with exsisting properties in framework?
If the problem is about program defined properties and structures, one can define many other ways to solve the problems.

**Comment by HaloFour** [comment]
Value copy semantics is *the* distinguishing characteristic of structs.  You're not updating a property of that struct, you are overwriting the entire thing.  I think that glossing over this would encourage using structs in ways that are discouraged.

**Comment by svick** [comment]
> How can I use it with existing properties in framework?

You can't. But what framework properties return mutable value types that you want to modify often?

**Comment by MohammadHamdyGhanem** [comment]
The one that I recall, although it's not about structs is:
textBox1.Lines[0] = "abc";
This will compile, but will not affect the textbox!
acourding to my suggesion it can be re-written as:
`textBox1.Lines<=[0] = "abc";`
Or:
`textBox1.Lines = textBox1.Lines {[0] = "abc"};`

Note that this matter affcts third-party codes as well: COM,  NuGet .... etc.

**Comment by MohammadHamdyGhanem** [comment]
Addition: Any method that returns a Point, a Size, or a Rectangle in framework face the same problem, and it is widely used.

**Comment by orthoxerox** [comment]
Withers (#162) could be extended to work not only with immutable types, but with struct properties as well: `User = User with { .Points += 1 }`

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

Indeed, that has nothing to do with structs.  It will happen with any property that returns a disconnected value.

These situations should be sufficiently rare and since you'd need a separate syntax anyway I don't see why it's such a problem to explicitly have to reassign the property.  Again, in the case with `TextBox.Lines`, you are rewriting the entire contents of the textbox based on the array, regardless of whether you only modified a single element.  I think it's important for the developer to understand that.

**Comment by jnm2** [comment]
The only times I can recall having to deal with setting struct properties:

- Once in a great while `obj.Size.Width = 42` which I resolve with extension methods, so `obj.Size = obj.Size.WithWidth(42)`. I like that because it doesn't gloss over the fact (like HaloFour said) that there is no way to set just the width; `set_Size` must be called. I wouldn't mind a `with` syntax to save me the trouble of maintaining extension methods.

- Slightly more commonly I'll have builder structs in a dictionary and have to do an extra hash lookup to store the modified struct back into the dictionary. To svick's point, we now have https://github.com/dotnet/corefx/issues/25189 in 2.1 (https://github.com/dotnet/corefx/issues/20684 for ordinary Dictionary still open) which addresses that.

**Comment by MohammadHamdyGhanem** [comment]
@orthoxerox 

> Withers (#162#162, Champion "pattern-based `with` expressions") could be extended to work not only with immutable types, but with struct properties as well: User = User with { .Points += 1 }

**Comment by orthoxerox** [comment]
@MohammadHamdyGhanem Or `User with= { ... }`? :trollface:

**Comment by MohammadHamdyGhanem** [comment]
With= does not imply that the object should keep its old values.

**Comment by jnm2** [comment]
@MohammadHamdyGhanem Yes, it does. If the word `with` appears, it means all other previous values are preserved.

**Comment by AustinBryan** [comment]
Why not use `<-` or something else instead of `<=` which already means something and could cause conflicts. 

Besides that, just use a class..
