### ISSUE TITLE
Allow return void function with void function

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#135]
In some condition we would do short logic and return from function immediately

So I think we should allow to return from void function with another void

```C#
void LoadAndDoSomething(string url)
{
    var obj = Load(url);
    if(obj == null)
        return Console.WriteLine("Not found " + url);

    // Do Something
}
```

Should also work with `Task`

```C#
async Task LoadAndDoSomethingAsync(string url)
{
    var obj = await LoadAsync(url);
    if(obj == null)
        return Console.WriteLine("Not found " + url);

    // Do Something
}
```

There are suggestion that we should be able to explicit cast `(void)` to be able to return function with any return type

```C#
void LoadAndDoSomething(string url)
{
    var obj = await LoadAsync(url);
    if(obj == null)
        return (void)Debug.Log("Not found " + url); // This Debug.Log return int

    // Do Something
}
```

This was ported from https://github.com/dotnet/roslyn/issues/11330

### Alternative

`guard statement` #138
I was propose it should use `return if` syntax. Which would be more generalize

```C#
if(condition)
    return DoSomething()

/// equivalence to
return if(condition)
    DoSomething();
```

**Comment by lachbaer** [comment]
I think it looks confusing, because it looks as if I am really returning something.
Currently you would write it like
```C#
void LoadAndDoSomething(string url)
{
    var obj = Load(url);
    if(obj == null)
        { Console.WriteLine("Not found " + url); return; }

    // Do Something
}
```
though putting the return on a single line would be better, because you should *always* mark the places good visible when returning before the end of a function.

**Comment by Thaina** [comment]
`{ Console.WriteLine("Not found " + url); return; }`

This hack is so dirty. Too dirty. And will be gone with auto formatting

While in any other return type function except void we could return function that has same return type

```C#
int CountOrSingle(IEnumerable<int> ints)
{
    int i = Load(url);
    if(ints.Count() > 1)
        return ints.Count();

    return ints.Single();
}
```

To not allow return void actually make inconsistent syntax

**Comment by GeraudFabien** [comment]
This thread is close to https://github.com/dotnet/roslyn/issues/11330. no ?

**Comment by lachbaer** [comment]
@Thaina 
Yes it is dirty 😈 😄 
But when you return from a called function you actually *do return* something. 

`return ints.Count()` says me _literally_ that I return and that I return the result of `ints.Count()`.
In case of a `Console.WriteLine()` 'like a mixed up language to me it is' 😉 
Because actually I 
* first 'Console.Writeline()'
* and *then* 'return'
That's why we should write it in two lines.

**Comment by Thaina** [comment]
Yes, I return void
`void` is something. It is return type. So return void is returning the return type

**Comment by bbarry** [comment]
I'd like to be able to use `System.Void` for things (specifically for delegates, expressions and tasks and potentially to be able to return `default(void)`) but I don't think it would be good to have conversions to `void`.

**Comment by lachbaer** [comment]
In my understanding of the word 'void' it is not kind of a type `void`, but also an expression of not being applicable, being even 'less than nothing' (with nothing being at least something 😉 ).
So you do not return *a* void, you not even return *void* because any return would be voided. So void is not a type, it is kind of a modifier. At least that's my point of view - others allowed :bowtie: 

([Oxford Dictionaries](https://en.oxforddictionaries.com/definition/void))

**Comment by fanoI** [comment]
Well it is a type in .Net "System.Void" but it is not exposed to high level languages!

**Comment by louthy** [comment]
`void` in type theory is a type that can have `0` values (like `bool` can have two: `true`, `false`).  So a type that can't have a value, can't be instantiated, and therefore can't be 'returned'.

Instead of a new language feature, just use a type that can have exactly `1` possible value:  namely `unit`.

I have [an implementation here](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Unit.cs)

But at its simplest:

```c#    
    public struct Unit : IEquatable<Unit>
    {
        public static readonly Unit Default = new Unit();

        public override int GetHashCode() => 0;
        public override bool Equals(object obj) => obj is Unit;
        public override string ToString() =>"()";
        public bool Equals(Unit other) => true;
        public static bool operator ==(Unit lhs, Unit rhs) => true;
        public static bool operator !=(Unit lhs, Unit rhs) => false;
    }
```
Also if you [define a static field like so](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude.cs#L36):
```c#
 public static class Prelude
 {
    public readonly static Unit unit => Unit.Default;
 }
```
And include the containing class:
```c#
    using static Prelude;
```
Then you can do stuff like this:
```c#
    public Unit Foo()
    {
        // ... Do something ...
        return unit;
    }
```
Which makes the method usable in plenty of places where a return type is needed (LINQ expressions, `Func<...,R>` etc.)

**Comment by Thaina** [comment]
@lachbaer Well , in my understanding, void is nothing. And that's it, nothing is a thing and we can return nothing. It abstraction like we return `NaN` for float. We just want to say it nothing and always nothingness

void of space is common wording

But anyway. I don't think we need that much philosophy. I just think it useful to keep code compact and being one line

Also in lambda expression. It also assume that you return void when you call void function in lambda. By this assumption I think anywhere should be the same

I mean

```C#
int X() { return 0; }
void A() { }

Func<int> action = () =>X(); // lambda can guess that you return int
Action action = () =>A(); // lambda can guess that you return void
```

**Comment by louthy** [comment]
> in my understanding, ...  nothing is a thing

'no  thing' is not a thing.  Your understanding is wrong I'm afraid.

**Comment by Thaina** [comment]
@louthy What you said is like 0 is not a thing. Space is not a thing

You are not wrong. We have zero things means we don't even have a thing.

But I think it's all about context. We have zero as number. We has spacebar and space character to make space. And we have void of space to define volume that really have nothing

But is empty volume is a thing?

As someone already pointed out. We even have `System.Void` which is really something in context of C#

Programming make use of abstraction and we make abstraction of void mean a thing in programming. So we can have void as return type. Why we can have return type be void but cannot return void?

I think we actually always return void

**Comment by louthy** [comment]
`0` as an integer doesn't mean 'no integer' though, it's one of the valid set of integers.  Which is the same as the space character, it's still a valid character, with a real representation (`0x20`).  But a type that has no representative values can't be instantiated.  That's why `void` can't be returned, and that's why a unit-type is better:

Take a look at [Core Computational Type Theory](http://www.cs.cornell.edu/courses/cs5860/2011fa/documents/Constable-CoreTypeTheory-Sept13-Supplemental.pdf)

> void is a type with no elements
> unit is a type with one element

Personally I would love to see all uses of `void` in the BCL be replaced with `Unit`, because it would make working with expressions much simpler.  But I can't back the change of meaning of `void`.

**Comment by Thaina** [comment]
@louthy I don't think you need to change any meaning of `void` it just that in context, nothing is being something

Like you said, in context of programming 0 is number. But in context of natural number. 0 is not a number. Even negative is not natural number. So as space that in writing it is nothing. Just an empty gap between word. But in context of computer it must have value `0x20`

So would you choose to have `void` being a thing in context of coding or not?
I think we have `System.Void` is already a proof of being `thingness` in C#

In some language like js there are concept of `undefined` that you will get if you return void. Is `undefined` a thing?
At least `undefined` and `void` is information. Information that tell us about no information. Like 0 tell us that there are no natural number

**Comment by lachbaer** [comment]
Boy (girl), what a disussion... 😜 

I think the discussion should just be about whether we can *treat* `void` as a valid return type.

I myself have a discussion on [dotnet/roslyn#9834 ](https://github.com/dotnet/roslyn/issues/9834) about allowing the `void` keyword as parameter for methods and lambdas to make the code a bit more verbose in places where otherwise would be only a bunch of non-alphanumeric characters
```C#
void AMethod(void) { }
var t = Task.Run( (void) => { /* ... */ } );
```
The last line currently being
```C#
var t = Task.Run( () => { /* ... */ } );
```
So `( () => {` all being slender characters. But I digress, that's out of scope in this discussion.

On a logical side I totally see what @Thaina wants to achieve.
But just by looking at something like
```C#
  return Console.WriteLine("We are leaving the procedure now");
```
my stomach turns 😧 It's just my guts...

**Comment by Thaina** [comment]
@lachbaer Well... I just don't felt anything because that is valid in some other language like C++ and js

http://stackoverflow.com/questions/3383090/is-returning-void-valid-code

**Comment by lachbaer** [comment]
@Thaina yeah, but this isn't C++ :wink: In C++ you can also evaluate (nearly?) all types to boolean.

Can you name other scenarios other than logging ("Console.WriteLine") where this would be useful?

When talking about [Roslyn](https://github.com/dotnet/roslyn) and code analysis there is always the tutorial about *enforcing* curly braces for *every* `if` and loop (`for`, `while`, ...). This is, because many serious companies have them *mandatory* in their programming style guides - for good reasons. So, every serious programmer *should* consider doing so as well. (I admit that I also often don't for one-liners :wink:).

Also, as I have already shortly mentioned in [post above](https://github.com/dotnet/csharplang/issues/135#issuecomment-280635585), I once learned that returning in the mid of a functionshould only be the exception, or for special design patterns where you spontaneous know that you're going to return (like condition checking at the beginning). And even in those places you should clearly mark the place where you return.

So a "quick'n'dirty"
```C#
void foo(object obj)
{
    /* maybe some expressions at the beginning... */
    if (obj == null)
        return Console.WriteLine("Returning from foo()");
    /* go ahead */
}
```
should be better written as
```C#
void foo(object obj)
{
    /* maybe some expressions at the beginning... */

    /* RETURN if condition is not met */
    if (obj == null)
    {
        Console.WriteLine("Returning from foo()");
        return;
    }
    /* go ahead */
}
```
Even without the `/* RETURN... */` comment it jumps much more into the eye that I have the intention to leave the function, because the `return` statement is not cluttered with other characters on the same line.

Well, I'd like to add a counter propose - if there's really need
```C#
void foo(object obj)
{
    /* maybe some expressions at the beginning... */
    if (obj == null)
        return after { Console.WriteLine("Returning from foo()"); }
    if (obj is string)
        return after {
                ProcessessString((string)obj);
                OnStringProcessed(new OnStringProcessedEventArgs((string)obj));
                Console.WriteLine("obj processed as string");
        }
    /* go ahead */
}
```
Due to the indention the `return` stands out and it is directly clear that after processing the block we're going to return. But when the block is a bit longer, you already might have forgotten that it is a `return after` block. It would have been better to make `return after` a comment like `/* RETURN after */` and add the ordinary `return` statement at the end of the block.

#### Summary
Except for very, very quick and dirty code I don't see any need for this.

**Comment by Thaina** [comment]
@lachbaer This is not C++ is not an argument about adding feature or not. I just mention C++ to tell that it not so unfamiliar in programming language. I too hate many aspect of C++ so I use C#. But it does not mean everything in C++ it bad for C#

We could do everything normally do in `if` block in one line if we refactor that block into another function

```C#
void DoSomething()
{
    if(!condition)
    {
         // 20 line of code
    }
    else
    {
        // 40 lines of code
    }
}
```

could be changed into

```C#
void DoSomething()
{
    if(!condition)
        return DoSomethingForFailCondition();

    // 40 lines of code with less indent
}

void DoSomethingForFailCondition()
{
     // 20 line of code
}
```

> there is always the tutorial about enforcing curly braces for every if

This maybe my personal. But I hate this coding convention. If it is one line block it should not make any junk brace
Not that I hate bracing, I am also a fan of new line brace so end of line brace is my enemy too. It just that, I think brace is used for marking many lines to be a scoped block so it redundant and just make code longer if you only have one line

> This is, because many serious companies have them mandatory in their programming style guides - for good reasons

No it's just convention. Many serious company use python too and they never care about bracing. It just convention that make higher up satisfied with their familiar pattern. It more like zombie virus that spread through people. If there is a good reason it would not be valid syntax in the first place
This is just like there are more people with right hand making society comfortable for right hand then condemn lefty to have problem with it

So I still thinking that return in one line block is more compact

ps.

For you proposing `return after`. I think you should look at proposal `guard statement` #138 
Where I was propose `return if` syntax which would be alternative to this

**Comment by lachbaer** [comment]
>> This is, because many serious companies have them mandatory in their programming style guides - for good reasons

> No it's just convention.

It is for two major reasons.
1a. consistency - all statements that could have blocks, should have ordinary blocks, with braces
1b. Because of the consistency, code analysis and automatic code correction/generation works better
2. In case you need to add a statement to the one-liner it could happen that you forget about adding the braces and so getting a semantic error in your code. (Happend to me, too in PHP already some times).
```C#
void DoSomething()
{
    if(!condition)
        return DoSomethingForFailCondition();

    // 40 lines of code with less indent
}
```
The 40 lines with less indention are also achievable when putting `DoSomethingForFailCondition();` and `return;` in a block.

Though the reducing of curly braced blocks would really be nice! Why do many (if not actually most) of us write one-liners instead of blocks? Because of the overhead of curly braces... isn't it so?

**Comment by Thaina** [comment]
@lachbaer Did you know some people who love one line brace block also write it like this

```C#
void DoSomething()
{
    if(condition0) DoSomeOtherThing();

    if(condition1) return;
}
```

I am not make this up. This is really the same person who told me to always put brace on one line block. But for him to be write short code he just write it like this

And he said never new line if it short. It convenient for him
But for me this is worse

As I said it really just convention
We should really always have auto formatter do the job
Talk about consistency, then the best consistency is let formatter always format your code. So the hack like `{ DoOther(); return; }` is just cheap trick. Every `;` should always in one line

For autoformatting. Adding brace to return make it more line than it should

```C#
void Main()
{
    if(!condition)
        return DoMain();

    // Do other
}
// vs
void Main()
{
    if(!condition)
    {
        DoMain();
        return;
    }

    // Do other
}
//vs
int Main()
{
    if(!condition)
        return DoMain();

    // Do other
}
```

From just 2 lines it expanded to 5 lines just because the return type is void

**Comment by DavidArno** [comment]
Chiming in late here but, @lachbaer, I completely disagree that it's confusing over what's being returned. Functional languages use this concept of returning `nothing`, `none` etc as every function must have a return value, even if that value is nothing. Returning `void` therefore makes complete sense.

This could then be taken further to treat eg `void M() { ... }` as a `Func<void>`, removing the need to distinguish actions and functions.

**Comment by fanoI** [comment]
While "return Console..." does not convince me much, when I call an helper void function inside a void function I always liked the idea that should do really do "return DoSomethingForFailCondition()".
The possibility to unify Actions and Functions is another big plus to have void as return value!

But what for the case in which the helper functions return int? A cast to void would be needed if we want to ignore the return value and do return!

```
       return (void) DoSomethingForFailCondition();
```

This is seem a natural thing but it is a little weird...

**Comment by eyalsk** [comment]
@DavidArno The issue I have with this proposal is the motive, people seems to want this for the wrong reasons where Func<...., Void> is one of THE reason to add it.

**Comment by GeraudFabien** [comment]
I have read this thread ten time and still don't understand the intrest of it. If you want you can have a class you could use instead of void that can wear also the reason of the error or just be empty and propose coposition. Is there performance reason to not do this?
```
public class M{}

public class M2{
        public string Result { get; set; }
}

public M C(){
        static public M Main(){
            return new M();
        }
}
```
I know some enterprise convention fobidden void to return at least bool (If succeed). I personnally don't see the interest of Func<void> vs Func<bool> vs Func<M>. I understand some built in .net function are void and you can't return on them. But i never feel like it was a problems to add "return;" and for that i feel like you should have this line only when you can't do in other way. For me i always try to make the method having only one leave point.

**Comment by lachbaer** [comment]
@GeraudFabien 
> I have read this thread ten time and still don't understand the intrest of it.

The initial intention was just to allow `return {void returning function}` to reduce the necessaty of creating a curly braced block with two lines.
> For me i always try to make the method having only one leave point.

Correct. But I wouldn't go with *always*, because in many cases a premature return eases the algorithms and/or readability a lot.

About `Func<void>`, how should Aggregate behave then?
```C#
public static TSource Aggregate<TSource>(
	this IEnumerable<TSource> source,
	Func<TSource, TSource, TSource> func
)
```
I think it is a matter of type safety to have both, `Func<...,, TResult>` and `Action<...>`
> `return (void) DoSomethingForFailCondition();`

Casting to `void` seems absolutely legitimate to me.
An by reading the above statement I must admit that it doesn't even look too bad, because of the `(void)` cast making absolutely clear what is going on.
I could live with the proposal, if *always* casting to `void` is *mandatory*, even for void returning functions.

Alternatively `return void [ Void expression ]`, without the casting braces should also be legitimate, if not even better, because that already makes clear that the outcome of the following expression will always be treated void.

**Comment by eyalsk** [comment]
@lachbaer 

> The initial intention was just to allow return {void returning function} to reduce the necessaty of creating a curly braced block with two lines.

This is the reason I downvoted, it seems like the main concern here is not really to allow us to return void but to write less.

**Comment by DavidArno** [comment]
@lachbaer,

> About Func<void>, how should Aggregate behave then?

`Aggregate` takes a `Func<TSource, TSource, TSource>` parameter, so to make it work with a void function, you'd need two void parameters too. Unlike returning void, having void parameters makes no sense to me at least.

**Comment by Thaina** [comment]
@GeraudFabien 

> For me i always try to make the method having only one leave point.

I see this is the main reason that you will never like this idea. Which I understand very well. However my convention is opposite from you. If we need brach then it must return immediately. Or you would end up with nested if

```C#
void DoSomething()
{
    if(condition0)
    {
        // do A 5 lines
    }
    else
    {
        // do B 5 lines

        if(condition1)
        {
             // do B.A
        }
        else
        {
             // do B.B and maybe so on and so on
        }
    }
}

// vs

void DoSomething()
{
    if(condition0)
    {
        // do A 5 lines
        return;
    }

    // do B 5 lines

    if(condition1)
    {
        // do B.A
        return;
    }

    // do B.B and maybe so on and so on
}
```

This is common in my code. And I would like to make it more compact if it is only one line

**Comment by lachbaer** [comment]
@DavidArno Exactly, that is why it makes no sense to have `Func<void>` - too many irregularities.

@eyalsk Many syntax extensions have been designed inter alia with the goal to reduce the code, ie. expression bodied members and auto-properties. So, why not? 😄

**Comment by eyalsk** [comment]
@lachbaer Haha.. well, I don't think you can really contrast this with expression bodied members or auto-properties, I mean the impact these features made is pretty huge when it comes to boilerplate and readability, I don't feel like it's the same thing here. :p

**Comment by DavidArno** [comment]
@lachbaer,

I disagree. `Func<void, void>` makes no sense, but `Func<void>` or `Func<T, void>` makes complete sense. I have code that uses a `Unit` type and methods that convert eg `Action` to `Func<Unit>` in order to avoid lots of code duplication. But this creates overhead that `Func<void>` would avoid.

**Comment by lachbaer** [comment]
@DavidArno 
But that wouldn't solve the problem with ` Aggregate<TSource>` unless the compiler has a special treatment for `Func<T1, T2, T3>`.

**Comment by DavidArno** [comment]
@lachbaer,

Either the following would be a compilation error, as `void` could not be used as the type for `List<>` and/or the type of a parameter, or the result would be `void`. Either way, I don't see why it would be an issue:
````cs
void SomeMethod(List<void> list) => list.Aggregate((a, b) => void);
````

**Comment by lachbaer** [comment]
@DavidArno 
```C#
List<void> list
```
really???? I think that would really lead to looots of runtime errors :joy:

**Comment by HaloFour** [comment]
The entire `void` generic type argument proposition would involve a lot of CLR chicanery to make happen.  Even in the "simpler" cases of delegate arguments it still requires different il to be emitted.  `void` is not `unit` and it doesn't make sense to try to forcefully shoehorn it to play like one, especially just to satisfy FP ideologues.  It solves no actual problems.

Besides, it's also unrelated to this proposal.

**Comment by DavidArno** [comment]
@HaloFour,

Do you know how F# handles this, then? As I understand it, `unit` is just the F# name for `void` and a 
`unit -> unit` function can be assigned to a `Func<unit>` delegate. I'm guessing I've got (at least) some of this wrong though.

**Comment by HaloFour** [comment]
@DavidArno 

The F# `unit` is just a class defined in `Microsoft.FSharp.Core`.  The source is here:

https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L28

**Comment by DavidArno** [comment]
@HaloFour,

Ah, now I understand. When F# folk say "unit is sort of like void", they mean "unit is nothing at all like void" 😁

**Comment by user1568891** [comment]
So it seems this thread got a little off topic. I personally really support this idea. It would result in cleaner code for at least my team with our code styles. No style fits all teams that isn't compiler enforced - so no syntactic sugar is going to apply to everyone. For those this would apply to though it would be really nice.

**Comment by CyrusNajmabadi** [comment]
Another case where i'd like this is switches:

I dislike having to write:

```c#
switch (something)
{
    case ExpressionSyntax e: HandleExpression(e); return;
    case StatementSyntax s: HandleStatement(s); return;
}
```

or

```c#
switch (something)
{
    case ExpressionSyntax e:
        HandleExpression(e);
        return;
    case StatementSyntax s:
        HandleStatement(s);
        return;
}
```

With non-void cases, i can just write: 

```c#
switch (something)
{
    case ExpressionSyntax e: return HandleExpression(e);
    case StatementSyntax s: return HandleStatement(s);
}
```

I'd like to be able to do the same even in the void case.

**Comment by DavidArno** [comment]
@CyrusNajmabadi,

This idea could be extended to the hopefully-coming-soon `match` keyword, to allow it to be used with `void` statements:
````cs
void F(int x) =>
    x match (
        case 0 : SomeVoidMethod(),
        case 1 : SomeOtherVoidMethod(),
        case * : DefaultVoidMethod()
    );
````

**Comment by alrz** [comment]
I like how this has been done in JS: explicitly via the `void` keyword,
```
return void F();
```
[source](https://twitter.com/controlflow/status/838517800566149120).

**Comment by CyrusNajmabadi** [comment]
I would not mind that style.

**Comment by dmitriyse** [comment]
> @bbarry I'd like to be able to use System.Void for things (specifically for delegates, expressions and tasks and potentially to be able to return default(void)) but I don't think it would be good to have conversions to void.
edit:
Right now there is an annoying quirk that you need to double your api size to support the dichotomy of generic things that return values and ones that don't.

Do we need to create additional proposal for this target ?

**Comment by lachbaer** [comment]
@alrz Or by explicitly casting to `void`
```C#
return (void) F();
```
because in case you are calling a function with (discarded) return value, an explicit *cast* to `void` would feel more natural to me.

A cast could make sense in other places where encapsulation in a block would otherwise just blow up the code.
```C#
extern int IncreaseErrorCount();
if (b == null)
{
    IncreaseErrorCount();
    Dashboard.ShowErrorLight();
}
```
vs.
```C#
if (b == null)
    Dashboard.ShowErrorLight( (void) IncreaseErrorCount() );
```
The cast is necessary here, because otherwise the non-existent ShowErrorLight(int) overload would be called.

**Comment by lachbaer** [comment]
For the ones who prefer Python-like indentions (and no blocks):
```C#
if (b==null)
    return (void)
        Dashboard.ShowErrorLight( (void)
        IncreaseErrorCount());
```
:wink:

**Comment by lachbaer** [comment]
In case of calling method overloads, all `void` arguments must be wiped from the parameter list.
So, a call of `Method( (void) A(), int, (void) B(), float )` would essentially call 
```C#
A();
B();
Method(int, float);
```
In this scenario an explicit cast with `(void)` is **mandatory** in all cases where it is used.

For this proposal this would also mean, that in a `void`-returning scenario, a *mandatory* cast after the `return` (`return (void) Method();`) would feel more consistent to me. As it is mandatory, it implies `return void`.

##### Other question
Should this be extended to `break` and `continue` also?
```C#
string[] sarr = ...;
string searchword = ...;
int i;
for (i=0; i<sarr.Length; i++)
    if ( sarr[i].Equals( searchword ) )
        break Logger.Log($"Found {searchword} at position {i}");
ProceedWithPosition( i );
```

**Comment by alrz** [comment]
@dmitriyse I believe zero-length tuples will resolve that issue. Just that it requires language support to not require `return ();` when the method returns `()`. I'm not sure if promoting `System.Void` as a first-class citizen is a viable option, though.

@lachbaer Perhaps, but `void` is not a type per spec and it's part of the method declaration syntax. It could be special cased in a cast (and parser will be happy anyways). I was proposing a "void expression" that does require syntax change, while a void cast would not.
```cs
Dashboard.ShowErrorLight( (void)
        IncreaseErrorCount());
```
This is even more confusing and probably affects overload resolution. It should not be allowed even with a "void expression" IMO. Note that void denotes an empty parameter list in C at the declaration-site but yet it's not applicable to argument lists.

**Comment by orthoxerox** [comment]
On one hand, promoting `void` to a real type would simplify a lot of corner cases. On the other hand, both C# and CLR in general behave like `void` doesn't exist at all. A function that returns `void` leaves *nothing* on the stack, not `default(void)` or `null`. You won't really get rid of special cases, just push them into the compiler. I feel like the ship has sailed on this change, just like it has sailed on unifying statements and expressions.

I won't mind seeing `System.Unit` / nuple / `()` added into the language, though. Or adding a small compiler hack to allow "returning" `void`, either. I don't think it will even affect the codegen.

**Comment by alrz** [comment]
@orthoxerox I'd prefer to be able to use `void` instead of `()` mainly because languages that use `()` does not feature `void`. Special-casing `()` return type to not require `return` is rather hacky. Consider this:
```cs
abstract C<T>
{
  protected abstract T M();
}

class Y : C<void>
{
  // looks like a regular void-returning method but actually returns System.Void
  protected override void M() { } 
}

class X : C<()> // wut 1
{
  protected override () M() { } // wut 2
}
```
At any rate, `()` does not *feel* C#ish. Anyhow, I think this discussion is a little off-topic but IMO that is far more important than being able to actually return void.

**Comment by alrz** [comment]
I also note that for a method like `void M()` reflection returns `System.Void` for return type. So if it actually does return `System.Void` that behavior remains intact.

**Comment by orthoxerox** [comment]
@alrz `()` would be the (only) value, `unit` would be its type. Then you would be able to create instances of `Func<unit, unit>` (a.k.a. `Action`) and have to `return ();` inside them.

Your example shows quite well that it's too late to make `void` a real type. With `unit` you would complicate the language further, of course, but at least you would be able to indicate that you're writing something very FP:

```c#
abstract class C<T>
{
  protected abstract T M();
}

class X : C<unit>
{
  protected override unit M() => ();
}
```

I think we should split the discussion of `unit` into a new issue.

**Comment by alrz** [comment]
>Your example shows quite well that it's too late to make void a real type.

I've intended the exact opposite.

**Comment by orthoxerox** [comment]
@alrz Are `void Foo()` and `void Foo(void)` the same method or two different ones? If they are two different methods, why would anyone do that?

**Comment by alrz** [comment]
@orthoxerox that should be possible only in case of type substitution and should not be permitted in a regular method declaration. And yes they are different, using `unit` won't make any difference.

**Comment by DavidArno** [comment]
I would argue that `Foo()` and `Foo(void)` are identical. Both have a `void -> void` signature. This relies on `Foo(void, void)` being a meaningless construct though, otherwise its signature would be `void -> void -> void`, which seems a pointless construct.

Also, I don't see a need for `unit`; `()` could represent `void`.

**Comment by alrz** [comment]
@DavidArno How exactly are they "identical"?

```cs
interface X<T> {
  void F();
  void F(T);
  void F(T, T);
}
```
You are saying that you should be able to implement `X<void>` with a single method?

**Comment by DavidArno** [comment]
@alrz,

My reaction is that it shouldn't be possible to implement `X<void>` as that would make `void F(T)` and `void F(T, T)` meaningless. This probably means I haven't thought this through properly 😀

**Comment by alrz** [comment]
@DavidArno 

>My reaction is that it shouldn't be possible to implement `X<void>`

That would painfully restrict the feature. It's not meaningless; Java requires to pass `null` for void parameters, but I think the `default` literal (https://github.com/dotnet/csharplang/issues/102) makes more sense in C#.

**Comment by orthoxerox** [comment]
@alrz that's because `void` is a reference type in Java. If they had value types in Java 1, you wouldn't be able to call `void M(void a)`.

**Comment by HaloFour** [comment]
`java.lang.Void` is a reference type in Java, a placeholder type used for reflection and generics.

`void` is not a type at all.  As in the CLR, it indicates a lack of something being pushed onto the stack.

**Comment by alrz** [comment]
@HaloFour

 What I'm proposing is literally just that: "allowing `void` in type arguments". And reflection is already making use of `System.Void`. So as I said, even if a method returns `System.Void` resulting from type substitution, that behavior remains intact.

**Comment by orthoxerox** [comment]
Found this [good old post by Eric Lippert](https://blogs.msdn.microsoft.com/ericlippert/2009/06/29/the-void-is-invariant/) where he goes into detail about `void`.

You *could* argue that making it a real type should still be possible - you could actually push a void value before `ret`, the codegen for the expression statement would dutifully pop it, and the jitter would try its best to optimize both away, but why? `return VoidMethod();` is a compiler trick, but it's a much smaller and localized compiler trick (it's likely there's no trick at all, if I remember it right).

**Comment by alrz** [comment]
This thread is about "syntactically" returning void-returning methods mainly to control control flow. Using void as type argument is clearly a separate proposal. Please open an issue if anyone want to continue the discussion.

**Comment by jnm2** [comment]
I don't know, [this felt really good](https://github.com/jnm2/Elevate/blob/23f6b4131f99510faeb0fc2c37e37ba086320bef/src/Elevate/Elevate.cpp#L94) 😆

**Comment by tyrotoxin** [comment]
Folks, let's look at the problem from another perspective. You can define your own `Void` type like this:
```csharp
    [StructLayout(LayoutKind.Sequential, Size = 0)]
    public struct Void { }
```
Now you are allowed to use this type anywhere you want - you can return it as a result of a function, you can use it as a generic parameter. What it means to use such type is a different question, but you are allowed to do so, and the runtime does not break.

`System.Void` and your own `Void` are semantically equal, they are just 2 different types. Should zero-length value types be not allowed then?

Please see another proposal where relaxing rules on `Void` might be useful:
[Proposal: Allow Void type as a Generic parameter](https://github.com/dotnet/csharplang/issues/696).

**Comment by Akronae** [comment]
Why not something like:

```cs
if (credentials.Code == Codes.BadCredentials) vreturn Console.WriteLine("Bad Credentials !');
```

instead of:
````
if (credentials.Code == Codes.BadCredentials)
{
    Console.WriteLine("Bad Credentials");
    return;
}
```

`vreturn` could be a keyword that says "return void".

**Comment by lachbaer** [comment]
@Akronae I'd prefer `void return` over `vreturn`, because then there was no need for an additional keyword. And it's not worse than `yield return`. To me the question is rather whether returning `void` itself could be a valid C# construct in the sense of the language. I would go with _yes_ as long as type safety is guaranteed, meaning that there must exist any kind of void casting to value returning functions.

**Comment by Akronae** [comment]
So we might go with something like `return Console.WriteLine as void` ?

**Comment by Thaina** [comment]
@Akronae `Console.WriteLine("")` is already `void`

**Comment by Akronae** [comment]
I know but it could be a way to implicitly tell the compiler "I want you to return void" and if the conversation fail (null) then the compiler throw an error.

**Comment by Thaina** [comment]
@Akronae conversion from null to void is not an error. returning void is not really return anything. Just return from current stack to upper stack, same as `return;`

There are mention about conversion because some function can return state as result, and it should be casted to void

This proposal just propose syntactic sugar for one line returning but not changing any behaviour

**Comment by Joe4evr** [comment]
> "I want you to return void" and if the conversation fail (null) then the compiler throw an error.

Your supposed syntax would not even be legal outside of a void (or `async Task`) method in the first place.

[Quoting myself from a related thread:](https://github.com/dotnet/csharplang/issues/696#issuecomment-310541444)
> The main take-away from this and the related issues is the fact that people desire a standard, Microsoft-supported implementation of `Unit`.

Let's stop trying to "enhance" `void` and create a better solution instead.

**Comment by Thaina** [comment]
@Joe4evr We don't really want `Unit` type to do anything and it not backward compatible with all of the void function we already have in BCL or any C# library in the world

Your `Unit` cannot make me able to `return Console.WriteLine("")` when I need to return it inside if clause

**Comment by MBeran** [comment]
Hi, the `return Console.WriteLine("");` looks very weird. 
I came here for
```csharp
async Task SomeMiddlewareInvoke()
{
    /* ... */

    if (somethingWentWrong)
        return CleanUpAndTerminate();

    /* ... */
}

Task CleanUpAndTerminate()
{
    /* ... */
}
```
instead of 
```csharp
async Task SomeMiddlewareInvoke()
{
    /* ... */

    if (somethingWentWrong)
    {
        await CleanUpAndTerminate();
        return;
    }

    /* ... */
}
```

**Comment by jnm2** [comment]
@MBeran To me, not-really-returning a Task instance seems just as weird as not-really-returning void. You can't think of this as actually returning the Task instance returned by CleanUpAndTerminate.
