### ISSUE TITLE
Compile-Time method inlining

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/csharplang#1413]
The problem:
-----
Currenty inlining only awailable on a JIT level, this approach have benefits (cross-module inlining) but this type of inlining is very restricted (method size, control flow restrictions, etc.)

In many cases inline is required within the same module or even class. This type of inlining can be performed at compile-time and have less restrictions than JIT inlining.

The solution:
-----
Compile-Time  attribute based inlining.
```CSharp
// Defines true CLR method, but also allow compile-time inlining
public class AllowInlineAttribute: Attribute {}

// Defines Inline-only method that is invisible for CLR
public class InlineOnlyAttribute: Attribute {}
```
Example:
```CSharp
public class MyComponent
{
    private int _state;

    [AllowInline] 
    private int MyCalc(int a, int b, Func<int, int> postCalc)
    {
        return postCalc (a+b);
    }

    public int SomeAction(int arg)
    {
         // Compiles by C# to:
         // return (_state + arg) ^ 397;
         return MyCalc(_state, arg, XorPostCalc);
    }

    private int XorPostCalc(int a)
    {
         return a ^ 397;
    }

    // This method is not compiled to the IL, but can be used by another methods.
    [InlineOnly]
    private void DoLock(Action a)
    {
         lock(this)
         {
              a();   
         }
    }
}
```

P.S. We can close this issue only with proof that "Type Classes" proposal (https://github.com/dotnet/csharplang/issues/110) can easily be used to perform this kind of inining.

P.P.S 
C# moves closer and closer to C++ and this capability is a "must-have" feature for a high-performance language.
Otherwise some projects can choose C++ instead of C# only due to an aspects oververbosity of C# for certain project. (while C++ metaprogramming can be an overkill adding some postprocessing capabilities to C# would be great)

**Comment by svick** [comment]
> In many cases inline is required

What are those cases?

**Comment by dmitriyse** [comment]
@svick Inlining in generial helps to reduce "call" overhead in a performance critical code. Performance critical methods fequently are very complicated and contains many code duplication. Smart inining helps to reduce code duplication and avoid calls overheads. You can find 100500+ examples in the CoreFX where inline can be useful. (Also you can open any C++ project and find the "inline" directive and code injected through "#DEFINE").

**Comment by HaloFour** [comment]
The team hasn't seemed terribly interested in taking up language proposals which involve specific optimizing at the compilation step.  I believe that this proposal would fall under that umbrella.  This is something better probably suited to a post-compilation link/optimization phase, where any language would immediately benefit rather than just C#.

I'm going to assume that you're proposal isn't just to inline "DoLock" but also to inline any potential delegate being passed to "DoLock".  This feels like something that would quickly be approaching compile-time templates.

**Comment by Unknown6656** [comment]
I'll just mention the slightly related issues:

#1028 
#504 
dotnet/roslyn#15079
dotnet/roslyn#12238
dotnet/roslyn#14665
dotnet/roslyn#10506
dotnet/roslyn#11259
dotnet/roslyn#9627
dotnet/coreclr#3633
#776

They are more concerned with compile-time expressions and constants and less inlining ..... but it goes into the same general direction, so I am mentioning them solely for completeness....

**Comment by dmitriyse** [comment]
@HaloFour, I agree that code-templating can be performed as a file-postprocess step or at IL level. And every approach has it's props and cons.

1) Out-of C# language template engine or postprocessor will still require the C# Roslyn infrastructure and same complexity for the multi-file project-wide templating.

2) IL level optimizer will require additional decompile step to invite Roslyn infrastructure into play (optimizer algorithms that works directly on IL code is extremely complex) and additional attribute markup is still required. It can be implemented as a plugin for Fody or PostSharper, but it's better that it will be at least a Roslyn plugin.

In any case debugging experience probably need to be improved with this sort of optimization.

**Comment by svick** [comment]
@dmitriyse 

In general, I do think the CLR is best equipped for this kind of optimization, even if it can't do it today (like delegate inlining). I think what you're proposing would require a significant amount of effort, and a lot of it would be just duplicating something the CLR can already do.

That being said, I think that if you want this to happen, you would need to demonstrate really well why Roslyn is the right place to do it. What makes adding all of this to Roslyn easier than improving the CLR?

Also:

> you can open any C++ project and find the "inline" directive

According to [this Stack Overflow answer](https://stackoverflow.com/a/1759575/41071), C++ compilers pretty much ignore `inline`.

**Comment by CyrusNajmabadi** [comment]
Being in Roslyn seems strange for me.  If you added this attribute to an F# method, it would not be inlined... which seems non-sensical.

**Comment by jnm2** [comment]
A little compile-time inlining here, a few binding redirects there... what could possibly go wrong? 😇

**Comment by yaakov-h** [comment]
@CyrusNajmabadi I would expect that if something can be inlined, it cannot be part of the assembly's public API surface.

That said... doesn't the compiler already try to inline Local Functions? Would it be a huge amount of work to extend this to other `private` functions?

**Comment by HaloFour** [comment]
@yaakov-h 

> That said... doesn't the compiler already try to inline Local Functions? Would it be a huge amount of work to extend this to other `private` functions?

The C# compiler doesn't attempt to inline local functions.  Even if all they do is return a constant the compiler still fully emits the static method and invokes it.  The CLR can inline them, tho.

**Comment by gafter** [comment]
> This type of inlining can be performed at compile-time and have less restrictions than JIT inlining.

I don’t understand why you aren’t requesting that the JIT lift whatever restrictions you find excessive. The JIT already knows how to in-line.

**Comment by gafter** [comment]
What would be the language semantics of the proposed attributes? If there are none, then this is a compiler feature request and does not belong in this repo.

**Comment by dmitriyse** [comment]
> What would be the language semantics of the proposed attributes? If there are none, then this is a compiler feature request and does not belong in this repo.

@gafter This proposal should not extend syntax or modify any symantic of the language, and probably yes it can be a compiler feature. But I think some C# specs should be still improved.

**Comment by dmitriyse** [comment]
>Being in Roslyn seems strange for me. If you added this attribute to an F# method, it would not be inlined... which seems non-sensical.

1) It's not supposed to be cross-assembly inlining solution
2) F# should add this kind of inining support by it's own
3) C# probably is the only language where this feature is hardly required. So high-performance CLR frameworks/components with 99% probability will be implemented in C#.

**Comment by mikedn** [comment]
> // Defines Inline-only method that is invisible for CLR

Sounds a bit more like macros rather than inlining.

> but this type of inlining is very restricted (method size, control flow restrictions, etc.)

Evidence? `MethodImplOptions.AggressiveInlining` makes the JIT rather, well, aggressive.

> You can find 100500+ examples in the CoreFX where inline can be useful.

Wow, CoreFX must have millions and millions of line of code if 100500+ examples of anything can be found in it.

>  Smart inining helps to reduce code duplication and avoid calls overheads.

Until it turns out that it isn't that smart and ends up producing code bloat that slows down the application.

> Also you can open any C++ project and find the "inline" directive and code injected through "#DEFINE"

As already pointed out, `inline` in C++ doesn't do what you think it does. Some compilers may use it as a hint but it's first and foremost a semantic feature, not an optimization feature. As for `#define`, many developers know well enough to stay away from it. In many cases it is used not for its "inlining" abilities but for its "macro" abilities.

**Comment by dmitriyse** [comment]
> MethodImplOptions.AggressiveInlining makes the JIT rather, well, aggressive. 

MethodImplOptions.AggressiveInlining may fail due to unpredictable reason. For example:
```CSharp
public struct MyStruct
{
    private Actioin _myAction;

    // SURPRISE! This method will not be inlined. 
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Test()
    {
         _myAction();
    }
}
```
Every time you should ensure that some method is inlined or not. It takes a lot of time in a profiling process.

C# Roslyn based inlining can notify you about inlining problem simply on compile.

!!! MethodImplOptions.AggressiveInlining is NOT AGGRESSIVE ENOUGH.!!!

**Comment by yaakov-h** [comment]
How do you expect the compiler to inline that call if the JIT can't do it?

**Comment by CyrusNajmabadi** [comment]
> That said... doesn't the compiler already try to inline Local Functions? 

I'm 99.999999% certain it does not.  If it does, that would be pretty interesting, and i would love someone to point me to an example that shows that happening.

> Would it be a huge amount of work to extend this to other private functions?

Since i don't htink any inlining exists today... yes :)

**Comment by CyrusNajmabadi** [comment]
> @gafter This proposal should not extend syntax or modify any symantic of the language, and probably yes it can be a compiler feature. But I think some C# specs should be still improved.

I think neal's point is:

You're not asking to change anything about C# **the language**.  i.e. you haven't changed the syntax of it.  You have not changed the semantics of it.  "dotnet/csharplang" is the repo for "C# **the language**".  And, as your proposal does not do anything with it, this is not right location for such a proposal. :)

**Comment by mikedn** [comment]
> !!! MethodImplOptions.AggressiveInlining is NOT AGGRESSIVE ENOUGH.!!!

Yes, there are certain cases where the JIT fails inlining due to technical limitations. It makes more sense to investigate and fix such limitations in the JIT instead of adding workarounds to C#/Roslyn. Similar technical JIT limitations have been fixed in the past (e.g. in the past methods that modified their arguments were not inlined).

**Comment by CyrusNajmabadi** [comment]
>     It's not supposed to be cross-assembly inlining solution

I didn't say anything about cross-assembly.  I'm saying that it doesn't make sense to me to have a method inlining feature that every language has to implement themselves.  Why would this not just be at  the IL level, so that it would work for *any* language.

>  F# should add this kind of inining support by it's own

You've now double the work :)    Add VB, tripled it.  Add any other .net language, etc. etc.

Why not just do this at the IL level and get it for all languages.  On hte plus side, it seems like it would be simpler given IL's smaller surface area.  I can't even fathom how ths would work in C# with the complexity of things like lambdas and async and all sorts of other rewriting that would then have to happen.  

>   C# probably is the only language where this feature is hardly required. So high-performance CLR frameworks/components with 99% probability will be implemented in C#.

Practically 100% of all c# apps are written on top of IL.  So high performance CLR frameworks/components would benefit if this was just done as some IL transformation step.

**Comment by CyrusNajmabadi** [comment]
> C# Roslyn based inlining can notify you about inlining problem simply on compile.

Why can the jit not inform you of this?  And if the JIT has no mechanism to inform you when inlining fails, then why not just make a request of the JIT to supply this information through one of their many diagnostic mechanisms?

**Comment by yaakov-h** [comment]
I find the JIT is actually surprisingly aggressive, even without `MethodImpl`.

e.g. https://sharplab.io/#v2:C4LghgzgtgPgAgZgARwExIMJIN4FgBQSRKyAlgHbBICyAFAJQ4HEtIBuYATkgEYCupADYATAKbcAvEnKiA7kgASkABYYA9mIBCAkeNoBGVAnoBuZqyL8hYzgDoAgsOG0ALAFYAbKfMWruu47OAOwAHACc3oQWKEG8Oja2AGpggnyiZlFEAL4+SLkQwJx8AMZUShCqGqLa1uK5eJmsiIoq6lrxehRUEKKiwowSAHzsKWlIUj19GdF5jSxdI6npxLksq8TNcC5IgbQLHEsDw8DKpBC2B2MA1FKX6etEDyRIC8lL48N308Q5+FlAA==

**Comment by CyrusNajmabadi** [comment]
```
C.M()
    L0000: mov eax, 0x558
    L0005: ret
```

Lol.

**Comment by zippec** [comment]
You can use hint `System.Runtime.CompilerServices.MethodImplAttribute(MethodImplOptions.AggressiveInlining)`

Also I would like to point out that Kotlin has inlining as language feature. https://kotlinlang.org/docs/reference/inline-functions.html
It have some semantic implications though, like `return` in inlined lambda returns from enclosing method.
```Kotlin
object Inlining
{
    inline fun test(lambda: (Int) -> Unit)
    {
        println("This will be printed");
        lambda(5);
        println("This will not");
    }
}

fun main(args: Array<String>)
{
    Inlining.test({_ -> return});
}
```
Not sure if it is of any use to C# but thought this is interesting. 😄

**Comment by 4creators** [comment]
> !!! MethodImplOptions.AggressiveInlining is NOT AGGRESSIVE ENOUGH.!!!

Fortunately it is not true

> AggressiveInlining is already as aggressive as we can get -- if the jit can inline, it will. We are not holding anything back. The dial is already turned up to 11.
> There are necessary limitations.
> Some methods can't ever be inlined, or can't currently be inlined. And we pass on inlining in some rare situations -- for instance you can't use AggressiveInlining and recursion to create unboundedly large methods.

This explanation by @AndyAyersMS in response to my question see: https://github.com/dotnet/coreclr/pull/16797#discussion_r172976832

IMO there is no reason to implement inlining in C# or Roslyn since in multi lang frameworks with intermediate code it is JIT or AOT Compiler role to do all optimizations. Otherwise, implementing optimizations into language compilers would be mostly a waste of time.

**Comment by AndyAyersMS** [comment]
If you ever run across cases where `AggressiveInlining` doesn't work and you can show it leads to a large missed performance opportunity, please let me know. Many of the inlining restrictions in the jit have now been removed, though some still remain (full list for RyuJit is [here](https://github.com/dotnet/coreclr/blob/master/src/jit/inline.def), look for things classified as `FATAL`, but note many of these are obscure corner cases, eg invalid IL of some sort).

Some prominent examples:
* The jit will not inline methods with EH constructs. This is fixable but there are a number of other EH related codegen issues that we need to address first before inlining such methods becomes really interesting.
* The jit cannot (in most cases) inline a shared generic method from some class into a shared generic method from some other class. This is harder to fix as the runtime also needs to become more flexible.
* The scope of inlining is limited in prejitted code because we don't want to bake cross-assembly dependencies into prejitted code. But recent work in tiered jitting now allows us to re-jit prejitted code when that code is called frequently, and during re-jit we can inline more broadly.

**Comment by CyrusNajmabadi** [comment]
As these are requests for runtime/jit improvements, can you please move the discussion to a more appropriate repo?  Thanks!

**Comment by mikedn** [comment]
> JIT will not capable to do this :

That's the 3rd example you come up with where inlining fails due to delegate invoke. Do you have anything new?

**Comment by dmitriyse** [comment]
It's not enough ? I provided at least two totally different simplest examples where JIT fails to inline.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi This is just an example.

> As these are requests for runtime/jit improvements, can you please move the discussion to a more appropriate repo? Thanks!

**Comment by mikedn** [comment]
> It's not enough ? I provided at least two totally different simplest examples where JIT fails to inline.

All examples you have provided fail inlining for the exact same reason - delegate invoke.

> I am afraid that I receive the same answer from RuiJIT team: "This feature is more likely should be a language feature - like C++ postprocessing. Delegate/Labmda inlining is too comples for JIT", please move your issue to CSharpLang repo.

That won't happen. In the worst case the issue won't be fixed anytime soon simply because nobody has time to do that. But nobody will tell you to move such an issue to csharplang/roslyn repos.

**Comment by mikedn** [comment]
> It may be that tiered jitting with some guarded speculation may get us closer to what you want, but that is a ways off.

There may be some misunderstanding here. In all these examples inlining of a method fails because it contains a delegate call. That seems like a rather arbitrary restriction in the JIT (though I guess there's a some sort of technical limitation that leads to this restriction).

Inlining of actual delegate calls (like the last example appears to suggest) is, of course, a different matter.

**Comment by AndyAyersMS** [comment]
Ah, that could be... I don't know the reason for the restriction either. But I don't see how inlining methods that simply call delegates is going to help all that much in general.

**Comment by CyrusNajmabadi** [comment]
> ```    // WHY NOT INLINED! It's a pain!```

Why is it a pain?  Is the overhead of calling an instance method on a struct actually that impactful for your scenario?  I've done apps where i'm trying to hit 60fps, and this sort of direct function call has not been problematic.

**Comment by mikedn** [comment]
> But I don't see how inlining methods that simply call delegates is going to help all that much in general.

Well, I don't know but all 3 examples suffer from this problem. Only the last one would require inlining delegate calls (I guess so from the // Inline me please totally, without any call! comment) but even there you'd need to first be able to inline `DoTwice` before even considering inlining `PrintHello` and `PrintBye`.

**Comment by CyrusNajmabadi** [comment]
> How do you think how man years is required to get JIT (Not AOT!) be capable to do inlining described above?

Certainly far less than trying to get the C# compiler to do it :)  It's an entirely different model for C# than has ever existed before.  First, it requires interprocedural knowledge.  Something that has never existed in the entire history of the compiler.  Second, it requires some ability to deeply understand dataflow such that the code of one function can actually be inlined sensibly into another.  Third, this would truly require the language to define what the semantics here actually meant.  For example, what do control flow constructs do in inlined scenarios.

Finally, if this was done in C# it wouldn't beneift anything else in the .net ecosystem.  

It's an enormous work item, for gain that i'm just not seeing.  Interprocedural analysis and modification has always been something far more suited to parts of the system that can actually see into all those procedures and can understand what's going on when they have the full picture.  The compiler, by design, is written such that it actually likes to know as little as possible.  It only wants signatures for things.  It wants to treat source decls effectively the same as metadata decls effectively the same as ref-assembly decls, etc. etc.  

ON the other hand, interprocedural analysis and mutation has been the break and butter of IL/jit systems.  It's what they do.  It's what they want to be good at.  It's the appropriate place for this sort of thing.

It would be vastly more man years to get anything done here in C#.  Just designing alone would be enormous, let alone the implementation costs.

**Comment by tannergooding** [comment]
> I don't see how inlining methods that simply call delegates is going to help all that much in general.

I think inlining is one of those things where a million tiny wins "can" add up to a big win. But I don't think the C# language is the place to add those wins (and I don't the impact of adding it to C# would be "big enough").

For the JIT, these are only a handful of scenarios where the JIT will refuse to inline a function (even with `AggressiveInlining`) and those should probably be reviewed (eventually) to determine if the restriction can be relaxed. I think the places where the JIT doesn't generate good inlined IL are much more important to look at.

I know one of the biggest areas today (where the JIT doesn't generate "great" IL) is when producing better code would change the observable side-effects of the program (such as a check that results from passing the argument to a method). This makes it difficult to write helper functions and have your code still be optimal.

**Comment by AndyAyersMS** [comment]
Looks like Jit64 is able to inline a method that invokes a delegate, so it seems likely to be straightforward to enable this ability in RyuJit.

@dmitriyse if this specific capability is important to you please open a targeted issue on coreclr to unblock inlining methods that invoke delegates and I will take a closer look. If you know of a case where this will measurably improve performance please add it to the issue.

@tannergooding I don't really understand your comment. Carefully preserving visible side effects while speeding up everything else is the entire goal of optimization. But best to follow up on this elsewhere.

**Comment by mikedn** [comment]
> I know one of the biggest areas today (where the JIT doesn't generate "great" code) is when producing better code would change the observable side-effects of the program (such as a check that results from passing the argument to a method). 

Hurray for taking things out of context and blowing them out of proportion too...

**Comment by AndyAyersMS** [comment]
FWIW here are the jit changes to unblock inlining a method that invokes a delegate: [master...AndyAyersMS:UnblockInliningDelegateCallers](https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:UnblockInliningDelegateCallers). Didn't test these extensively but they seem to work. Feel free to grab them and build your own jit to see if it helps your scenario.

Looking at the impact on things I can measure easily shows that this doesn't kick in very often, by itself doesn't lead to any downstream optimization opportunities, and causes some modest code growth as mainly we just end up duplicating the delegate invoke sites. So probably not something I would merge without some evidence that it actually helps performance.
```
Total bytes of diff: 5889 (0.04% of base)
    diff is a regression.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file regressions by size (bytes):
        1779 : Microsoft.CodeAnalysis.dasm (0.22% of base)
        1168 : System.Net.Sockets.dasm (0.67% of base)
         860 : System.IO.FileSystem.Watcher.dasm (7.18% of base)
         796 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.03% of base)
         697 : Microsoft.CodeAnalysis.CSharp.dasm (0.03% of base)
Top file improvements by size (bytes):
          -8 : System.Net.Http.dasm (0.00% of base)
12 total files with size differences (1 improved, 11 regressed), 67 unchanged.
Top method regessions by size (bytes):
         860 : System.IO.FileSystem.Watcher.dasm - System.IO.FileSystemWatcher:ParseEventBufferAndNotifyForEach(ref):this
         385 : Microsoft.CodeAnalysis.dasm - Microsoft.CodeAnalysis.AbstractSyntaxNavigator:GetLastToken(struct,ref,ref):struct:this (2 methods)
         333 : Microsoft.CodeAnalysis.dasm - Microsoft.CodeAnalysis.AbstractSyntaxNavigator:GetPreviousToken(struct,struct,ref,ref,byref):struct:this
         198 : System.Net.Sockets.dasm - System.Net.Sockets.SocketPal:ReceiveMessageFrom(ref,ref,ref,int,int,byref,ref,byref,byref,byref):int
         174 : Microsoft.CodeAnalysis.dasm - <DescendantTriviaIntoTrivia>d__161:MoveNext():bool:this
Top method improvements by size (bytes):
          -8 : System.Net.Http.dasm - System.Net.HttpKnownHeaderNames:TryGetHeaderName(ref,int,int,ref,ref,byref):bool
78 total methods with size differences (1 improved, 77 regressed), 80589 unchanged.
```

**Comment by dmitriyse** [comment]
@AndyAyersMS thank you for your tip with custom jit.
1) I found that everybody wants to stay all inlining logic at JIT level
2) Probably more developer control through additional hints (attributes) is required. Developer have better knowlage what to do. For example some attribute to force "inlining with delegate invocation" just for a specific methods. Anoher example to force inlining regardless of size of resulting code and inlining depth.
3) To develop performance-critical library targeting DotNet it's sufficient that only one language (C#) has rich-set of features to write performance code. Other languages can just link well-built library.
4) Tons of code written in a way to workaround JIT limitation, so do not expect that tweaks in JIT will instantly give benefits. Developers should be able to relay on JIT behavior.
5) Pushing inlining to JIT we also push inlining to AOT compiler so probably it's also a double work, copared to C# only inlining implementation.
6) JIT works on IL level and it works by pattern matching, it's extremely complex to write inlining logic on IL level. Different languages can produce different IL for the same things. Decompile IL to some another abstraction is required to write smart algorithms (decompile to C# ?!!!).

So "move issue to JIT" is not an obvious answer.

I will post issues to JIT(CoreCLR) repo, but also provide a link to this issue as an alternative approach.
We can close this issue after some time, if no any developer will also ask this feature.

**Comment by mikedn** [comment]
> I found that everybody wants to stay all inlining logic at JIT level

What everybody actually wants is to keep optimizations that don't belong in the C# compiler out of the C# compiler. That's the way it works in pretty much all other compilers, the "parser" (usually known as front-end in the compiler world) doesn't do optimizations, it's the code generator (usually known as back-end) that does most optimizations. Front-ends may do some trivial optimizations (constant folding) or high level, language specific optimizations (e.g. I would expect Roslyn to produce reasonable IL code out of pattern matching and not offload that onto the JIT).

> Pushing inlining to JIT we also push inlining to AOT compiler so probably it's also a double work, copared to C# only inlining implementation.

Existing AOT compilers do that already. CoreRT uses the CoreCLR JIT compiler and .NET Native uses the VC++ backend. Both do inlining and have done so for many years. You're suggesting doubling the work by adding inlining capabilities to the C# compiler.

> JIT works on IL level and it works by pattern matching, it's extremely complex to write inlining logic on IL level.

Inlining logic is complex because it requires heuristics that are difficult to get right. Otherwise it would be relatively trivial compared to other optimizations that the JIT does.

> Decompile IL to some another abstraction is required to write smart algorithms (decompile to C# ?!!!).

Generally speaking, optimizations require a different abstraction than what the C# compiler uses now to represent code. So I fail to see the problem(s) you are seeing.

**Comment by svick** [comment]
@AndyAyersMS 

As far as I can tell, your modification changes the code from "never inline methods with delegate invocations" to "freely inline methods with delegate invocations". How hard would it be to change it instead to "only inline methods with delegate invocations if we're aggressively inlining"?

That way, it doesn't hurt the common case where inlining such methods is not worth it, but I can also apply `AggressiveInlining` if it does improve performance in my code.

I'm assuming doing this would be just changing a few lines, similar to the change you showed. If it was more effort, this is probably not worth doing without further evidence.

**Comment by AndyAyersMS** [comment]
That is certainly doable, yes.

**Comment by dmitriyse** [comment]
OMG, how much troubles already issued with JIT inlining:
![image](https://user-images.githubusercontent.com/10322215/37991744-01195e78-321b-11e8-9888-726fa3ba61f6.png)

**Comment by CyrusNajmabadi** [comment]
> OMG, how much troubles already issued with JIT inlining:

How would this be solved by C#?  Why do you expect C# to be better at inlining anything versus the JIT?  We have literally 0 experience with it.  It's not something defined at all in the language.  It's something incredibly complex given the enormous size of the C# language.  It isn't even defined (as far as i can tell) for totally normal scenarios like "i am referencing a dll".  Saying that you don't like how well the JIT does inlining in no way constitutes an argument for why C# should have any involvement with inlining.

**Comment by mikedn** [comment]
> OMG, how much troubles already issued with JIT inlining:

Can you please drop off this "OMG" childish attitude? It doesn't solve any problems. There are plenty of issues in that search that do not have anything to do with JIT inlining or just mention it in passing or that are plain bogus. You're not going to convince anyone that there is some kind of cosmic proportion issue that needs to be addressed in the specific manner you think it can be addressed.

**Comment by dmitriyse** [comment]
Sorry I am not correct, I have changed my comment.

**Comment by dmitriyse** [comment]
I create an issue with the delegate invocation inlining problem: https://github.com/dotnet/coreclr/issues/17270

**Comment by mikedn** [comment]
> Sorry I am not correct, I have changed my comment.

What would be more useful is to try to understand the problem before proposing solutions or drawing conclusions. Just an example: the second issue in your screenshot is not exactly an inlining problem. That dispatch stub isn't an IL method that the JIT could inline like any other method, it's just some code automatically generated by the runtime for interface calls. There's nothing that the C# compiler or the JIT inliner proper can do about that.
