### ISSUE TITLE
Downcasting generics

### ISSUE THREAD

**Issue by TheUnlocked** [dotnet/csharplang#1422]
Why does this produce an error? If there's no real reason, I suggest that generics should be able to implicitly downcast.

```csharp
class Thing{
    // ...
}

class Thang : Thing{
    // ...
}

List<Thang> thangs = new List<Thang>();
List<Thing> things = thangs; // Can't implicitly convert List<Thang> to List<Thing>
```

**Comment by HaloFour** [comment]
`List<T>` is not variant.  If it was you could try to stick `Thing`s in it that aren't `Thang`s which would not be legal.  This is very much by design.

**Comment by portal-chan** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-generic-modifier

You can make this work with `IEnumerable<out T>`s, since those are covariant
```csharp
IEnumerable<Thang> thangs = new List<Thang>();
IEnumerable<Thing> things = thangs;
```

Though if you really need lists, do something like
```csharp
List<Thang> thangs = new List<Thang>();
List<Thing> things = thangs.Cast<Thing>().ToList();
```

**Comment by TheUnlocked** [comment]
@HaloFour But why? What are the drawbacks from always allowing that? I'm curious.

**Comment by TheUnlocked** [comment]
To be clear, I'm not suggesting that `things` would contain a `List<Thang>`, but that it would automatically cast the list to a `List<Thing>`

**Comment by HaloFour** [comment]
@TheUnlocked 

Allowing that would defeat the type safety that generics are intended to provide.  If you could cast `List<Thang>` to a `List<Thing>` you could then attempt to `Add` a non-`Thang` to it and the compiler wouldn't know to stop you.

In the CLR the generic type arguments are reified and actually produce incompatible types at runtime.  Only through explicit variance (through the `out` and `in` keywords applied to generic type parameters) will the CLR allow you to safely cast.  For example, you can cast a `List<Thang>` to an `IEnumerable<Thing>`, because the compiler and the runtime can guarantee that you can only get values compatible with `Thing` out of the enumerable.

In the CLR arrays are variant and you can freely cast from `Thang[]` to `Thing[]`.  This is widely regarded as a bad design decision because you lose the compile-time type safety since you wouldn't get an error until runtime if you try to assign a non-`Thang` to the array.

**Comment by TheUnlocked** [comment]
Okay, thanks.
