### ISSUE TITLE
Proposal: using fields

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/csharplang#1451]
We currently have the ability to scope and automatically dispose of `IDisposable` objects via the `using` statement.

    using (var stream = new MemoryStream())
    {
        ...
    }

Here the stream is automatically cleaned up at the end of the `using` block.

This proposal adds a new syntax for the `using` keyword: on read-only fields.

    class MyClass
    {
        using private readonly Timer _timer = new Timer();
    }

The above implies that as a `MyClass` instance is garbage-collected, the `_timer` field would be automatically disposed, just like at the end of the `using` block.  It effectively defines the scope as the lifetime of its owner rather than within a block of code.

This would be roughly equivalent to

    class MyClass
    {
        private readonly Timer _timer = new Timer();

        ~MyClass()
        {
            _timer?.Dispose();
        }
    }

Requirements:

1. The field must be of a type that implements `IDisposable` (just like `using` statements).
2. The field must be read-only to ensure that the value at destruction is the same as it was when construction completed.

**Comment by SIkebe** [comment]
You can do this using any DI container today.
No need to have the function in language itself.

**Comment by gregsdennis** [comment]
> You can do this using any DI container today.

I don't know that you can assume someone is going to be using a DI container on every project where this scenario may arise.

**Comment by Joe4evr** [comment]
Also this is a duplicate of #542.

**Comment by PathogenDavid** [comment]
@Joe4evr Definitely not the same feature being proposed, but that proposal was and interesting one that I hadn't seen before so thanks for sharing it.

**Comment by Joe4evr** [comment]
@PathogenDavid It actually is the same thing being proposed (setting a `readonly IDisposable` field to `null` after disposing); it's just that the thread went off-topic discussing immutability and why mutable structs are not inherently evil.

**Comment by PathogenDavid** [comment]
@Joe4evr This proposal suggests automatically implementing the finalizer to dispose of `IDisposable` fields marked with a special `using` keyword, it doesn't contain anything about mutability of `readonly` fields.

**Comment by jnm2** [comment]
I think automatically tying finalizers to disposal is going the wrong direction. Plus, finalization happens in the finalizer thread; disposing from some other thread would be surprising. More often than not it seems finalizers hide a code smell; for example, when people use Dispose(bool) and call it from a finalizer when they should be using .NET 4.0's SafeHandle with superior guarantees.

**Comment by PathogenDavid** [comment]
In addition to what @jnm2 said, the implementation as given in the proposal directly goes against the [recommendations for implementing `IDisposable`](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.7.2#examples).

Specifically:
```csharp
        // If disposing equals false, the method has been called by the
        // runtime from inside the finalizer and you should not reference
        // other objects. Only unmanaged resources can be disposed.
```

**Comment by qrli** [comment]
To put it simpler:
* A finalizer must not call other objects' Dispose(). They may have already been GC'ed. It may cause them to be resurrected in invalid state.
* Finalizer is not reliable for releasing unmanaged resources, even though it was designed to do that. Use SafeHandle instead.

So, finalizers should not be used in normal applications at all, or maybe never.

**Comment by gregsdennis** [comment]
So it seems that at least one of the following is true:

1. This isn't really necessary since the garbage collector will handle the managed resources that implement `IDisposable` (which *should* clean up their own unmanaged resources).
2. There's likely a better pattern for handling `IDisposable` fields (like the containing class also implementing `IDisposable`).

In either case, this proposal probably needn't be implemented as it is.

**Comment by qrli** [comment]
@gregsdennis 
> 1. This isn't really necessary since the garbage collector will handle the managed resources that implement IDisposable (which should clean up their own unmanaged resources).

To be accurate, GC knows nothing about `IDisposable`. It only looks for finalizers.
`IDisposable` objects are still better to be `Dispose()`'ed explicitly, or via `using()`, but _not in finalizer_.
GC is the safenet.

> 2. There's likely a better pattern for handling IDisposable fields (like the containing class also implementing IDisposable).

I don't feel there is a _better_ pattern. As soon as a field is `IDisposable`, its container is better to be `IDisposable` too, so be its container's container, and so on. This was a real problem in WinForm days. But since WPF, `IDisposable` become much rare. As of now, `IDisposable` are less than 5% in my experience, and their lifecycle are mostly managed by either `using()` or IoC container. So, it is no longer a concern to me.

**Comment by Korporal** [comment]
@gregsdennis 

The example:

```
class MyClass
{
    using private readonly Timer _timer = new Timer();
}
```
raises the question "How would a consumer of `MyClass` force the instance to get disposed"?

The dispose pattern supports two things 1) Reduce scope for leaking unmanaged resources and 2) Reduce the time that unmanaged resources remain active.

Your suggestion seems to remove 2 as an option for the coder, because `MyClass `does not implement `IDisposable `one cannot do:

```
uisng (var s = new MyClass())
{

}

```
Which begs the question "When exactly would the Timer get disposed?"

**Comment by GlassGrass** [comment]
RAII, the approach of C++ or D or so on against resource management, is regarded as really successful idiom. Implicitly combining resource lifecycle with object ownership releases programmers from annoying resource management. The goal of `using` statement in C# is same, but onerousness still remains because of complexity of `Dispose` pattern.

BTW, [improvement of `using` statement](https://github.com/dotnet/csharplang/issues/1623) will make `void Dispose()` method as special position and resource releasing will become independent of `IDisposable` type. This may bring new improvement to this proposal. That is to clean up in `void Dispose()` in place of destructor.

```C#
// convert from:
public class Owner
{
    private readonly using Owned _field;

    public void Dispose()
    {
        // ~~~ Some managements ~~~
    }
}

// convert to:
public class Owner
{
    private readonly Owned _field;

    public void Dispose()
    {
        // ~~~ Some managements ~~~

        <Dispose>__DisposeUsings();
    }

    private void <Dispose>__DisposeUsings()
    {
        _field.Dispose();
    }
}
```

`Owner` and `Owned` only have to provide `public void Dispose()`, do not have to be implementation of `IDisposable` interface. In past time, the language should not depend on strict type, but discarding will no longer rely on `IDisposable`.

Actually I like C++ RAII, but I cannot assume whether it will be welcomed in C# world.
How do you think about?

**Comment by gregsdennis** [comment]
When I first created this proposal, I think I was trying to figure out a way to have the `using` statement span the method boundary (instantiate in one method and clean up in another) or something similar.

Reading over it again, I'm not convinced that maybe I was just *doing it wrong* and should have just implemented the dispose pattern.

Given that and the proposal's generally lackluster reception, I'm going to close this issue.

Thanks everyone for their thoughts.
