### ISSUE TITLE
Proposal:  Non-Positional Parameters

### ISSUE THREAD

**Issue by bondsbw** [dotnet/csharplang#1478]
Positional arguments can be easy to write but difficult to read:
```c#
AddStudent("Amanda Jones", true, false, false, true, 10, 5, 10);
```
To fully understand this call, you need to cross-reference the `AddStudent` method signature.
```c#
public void AddStudent(string name, bool lockerAssigned, bool outOfStateTransfer, bool overwrite, 
   bool throwOnError, int gradeLevel, int retryCount, int timeout)
{
    ...
}
```
The caller can optionally choose to name the arguments:
```c#
AddStudent("Amanda Jones", lockerAssigned: true, outOfStateTransfer: false, overwrite: false, 
    throwOnError: true, gradeLevel: 10, retryCount: 5, timeout: 10);
```
But this is unenforceable.
## Proposal ##
Allow the method writer to require arguments to be named.

`NonPositionalAttribute`, applied to a parameter, will require the argument to be named.
```c#
public void AddStudent(string name, 
    [NonPositional] bool lockerAssigned,
    [NonPositional] bool outOfStateTransfer,
    [NonPositional] bool overwrite,
    [NonPositional] bool throwOnError,
    [NonPositional] int gradeLevel,
    [NonPositional] int retryCount,
    [NonPositional] int timeout)
{
    ...
}
```

In this case, only `name` is allowed to be called without a name, while all the others must be named.

#### Considerations ####

1. `NonPositionalAttribute` could be applied at the method level to require all arguments to be named.  This could be applied even more broadly, such as the class or assembly levels.
2. When applied at levels higher than argument, allow types to act as a filter.  The following would be equivalent to the above example (syntax borrowed from #124):
```c#
[NonPositional<bool, int>]
public void AddStudent(string name, bool lockerAssigned, bool outOfStateTransfer, bool overwrite, 
   bool throwOnError, int gradeLevel, int retryCount, int timeout)
{
    ...
}
```
3. As mentioned by @HaloFour, this would be unenforceable for previous versions of the language.

**Comment by Logerfo** [comment]
This can be achieved with a custom analyzer. I don't see a reason for this to be added as a new syntax restriction.

**Comment by HaloFour** [comment]
I agree with @Logerfo , the behavior from the compiler can already be enforced through an analyzer, especially given that your proposal pretty much builds on existing syntax (except where you get into generic attributes, but you can always use a `params Type[]` constructor parameter instead).

I also think that tooling support in the IDE, either built-in or through an extension, could give this behavior to you for free without requiring any changes to the language/compiler, as mentioned here:  https://github.com/dotnet/csharplang/issues/1462#issuecomment-382030440

**Comment by bondsbw** [comment]
@HaloFour 
> (except where you get into generic attributes, but you can always use a `params Type[]` constructor parameter instead)

Right, that is not part of this proposal.  I just think it looks nicer.  :slightly_smiling_face:

**Comment by bondsbw** [comment]
@Logerfo I can't enforce that consumers of my API add my analyzer.  Your suggestion would limit applicability.

(At least I don't think I can.  Correct me if I'm wrong.)

**Comment by bondsbw** [comment]
Fluent APIs tend to enforce descriptive usage.  I use them regularly.

This proposal is a small step toward adding a fluent API but without all the hassle.

**Comment by bondsbw** [comment]
@stakx  I agree, this does look nicer:
```c#
AddStudent("Amanda Jones", lockerAssigned, outOfStateTransfer, throwOnError, overwrite, gradeLevel, retryCount, timeout);
```

Except that I accidentally switched two arguments.

And you probably had to look at the top of this page to see which ones.

**Comment by stakx** [comment]
@bondsbw - My point was that a method writer would perhaps better invest their time in designing a sensible, user-friendly API than staying with a badly-designed one and deciding when to force upon consumers a particular call syntax that may not even be desirable in *their* opinion. It's *your* responsibility as a method writer to design it well. Your consumers' coding style is mostly *their* business.

Since I mentioned API design, here's some alternatives that might reduce or even obliterate the need for enforcing named arguments:

* Use object initializer syntax:

   ```csharp
   Add(new Student { LockerAssigned = true, OutOfStateTransfer = false, ... });
   ```

* I'm sure you've heard the "Boolean parameters are evil" argument. In that vein, perhaps replace all your `bool` parameters with `enum` ones; or, instead of plain `int`s, use custom structs that convey some meaning and let the type system help you out: You won't be able to accidentally put an `Area`-typed argument in a `Distance`-typed parameter, even though both might simply be wrappers around the same primitive type (e.g. `double`).

There's probably many more options. What I'm saying is that a not-to-well-designed method (IMHO) like `AddStudent("Amanda Jones", true, false, false, true, 10, 5, 10);` is not an ideal starting point for requesting a new language feature.

**Comment by stakx** [comment]
P.S.: In case this feature request gains traction, I'd be happy if at least the compiler deemed e.g. `frobbler` a valid short form for `frobbler: frobbler` for enforced non-positional params, to avoid unnecessary redundancy.

**Comment by DavidArno** [comment]
The crappiness quotient of a method can be expressed as (number of parameters)^(number of boolean parameters+1), with 1 being "not at all crappy" and this example, of 8^5, or 4096, is pretty damned crappy.

I'm with @stakx here: don't fix this with compiler bodges; fix it by reducing the number of parameters.

**Comment by bondsbw** [comment]
@stakx 
> I'm sure you've heard the "Boolean parameters are evil" argument.

Of course.  That's the point of this proposal, reducing hidden intent.

The problem goes beyond Booleans and includes most types of constants.  We can't tell what those integers mean any more than we can tell what the Booleans mean.

**Comment by bondsbw** [comment]
@stakx 
> My point was that a method writer would perhaps better invest their time in designing a sensible, user-friendly API

That's the other goal of this proposal, KISS.

Alternatives inevitably require more _stuff_.  Maybe you need an enum for your flags.  Or a class to hold all the parameters.  Or more methods (and possibly more types) to create a fluent API.

Those all work great, but they aren't as user-friendly.

**Comment by bondsbw** [comment]
@HaloFour 
> there's nothing that you can do as an API author to force any consumer of your API to actually use a version of the compiler that can enforce such a behavior

This is somewhat minor (IMHO).  Existing behavior is a reasonable fallback.

**Comment by HaloFour** [comment]
@bondsbw 

> This is somewhat minor (IMHO). Existing behavior is a reasonable fallback.

Which then breaks if the user updates the compiler, even if they are entirely unaware of whether various APIs they consume might try to enforce this behavior.

**Comment by Opiumtm** [comment]
The best solution to make method parameters a less mess is a `struct` which would hold all the parameters and embed all required parameter logic into the struct. So, by introducing a struct you gain 

1. Better level of backward compatibility. You can totally avoid lots of method overloads if you introduce additional parameters or change method signature.
2. Enforce required positional parameters in non-default struct constructor and optional non-positional parameters as struct fields that isn't initialized by constructor.
3. You could have additional logic embedded into the struct to validate or correct parameters even before struct is passed to method as argument.
4. Structs introduce little overhead and doesn't allocate unnecessary memory.

I often use structs for public APIs parameters instead of long parameter lists.

**Comment by bondsbw** [comment]
@Opiumtm As stated above, it's more work for the implementer and still not a solution for required parameters.

**Comment by Opiumtm** [comment]
@bondsbw Required parameters could be at non-default struct's constructor, of course.

**Comment by bondsbw** [comment]
@Opiumtm It misses the point of this proposal.  There is no way to require the caller to specify the argument names.

**Comment by theunrepentantgeek** [comment]
> As stated above, it's more work for the implementer and still not a solution for required parameters.

It's more work for the implementer *once*.  
It's less opportunity for mistakes *every time* a developer writes code to call the method.  
It's easier comprehension *any time* a developer reads the method call in the future.

A struct with **readonly** values for required parameters, initialized from a constructor, handles required parameters quite well, I believe.

Note also that there's no requirement for everything to be contained in the one struct. 

Take your original example:

```
public void AddStudent(string name, bool lockerAssigned, bool outOfStateTransfer, bool overwrite, 
   bool throwOnError, int gradeLevel, int retryCount, int timeout)
{
    ...
}
```

One possible restructuring of this would be:

```
public void AddStudent(NewStudentInformation student, ServiceOptions options)
{
    …
}

public struct NewStudentInformation
{
	public string Name { get; }
	public bool LockerAssigned { get; set; }
	public bool OutOfStateTransfer { get; set; }
	public int GradeLevel { get; set; }
	
	public NewStudentInformation(string name) { ... }	
}

public struct ServiceOptions
{
    public bool Overwrite { get; set; }
	public bool ThrowOnError { get; set; }
	public int RetryCount { get; set; }
	public int Timeout { get; set; }
}
```

In this scenario, it's likely that `ServiceOptions` wouldn't be constructed anew for each call; I'd create a standard one that I passed in wherever required, only creating a custom one when the requirements for that service call were different.

**Comment by bondsbw** [comment]
@theunrepententgeek

How does your example force the caller to supply parameter names for required parameters?

That's the purpose of this proposal, so failing to address that specific need is pointless.

**Comment by DarthVella** [comment]
Because the NewStudentInformation and ServiceOption bool/int settings are not part of their respective constructors, and so must be explicitly set.

```csharp
var newStudent = new NewStudentInformation("James Smith")
{
   LockerAssigned = true,
   GradeLevel = 9
};
```

etc, etc.

**Comment by theunrepentantgeek** [comment]
@bondsbw I think you're missing my point, so let me be more explicit.

I think this proposal provides an approach for papering over problems in badly designed method signatures. 

1. It doesn't actually address the underlying problem of bad design; it just provides a way for bad designs to be "justified" as usable instead of fixed.
1. It places a higher burden on every consumer of the API instead of putting the onus on the method author to make things simple to use.

I'd suggest that enhancements to C# should primarily fall into one of two categories: features that make the language more powerful and expressive (async/await, shapes, records, etc) or that encourage good development practices (e.g. expression bodied members encouraging short implementations). I don't think proposal falls into either category.

**Comment by HaloFour** [comment]
> I don't feel this is a problem in Objective-C for example, where parameter names are required.

This was a part of the initial design of Objective-C, not added in a much later version.  It's interesting that in Swift they make it possible to define functions that don't require the argument labels.

**Comment by bondsbw** [comment]
Some who come from an Obj-C background feel that aspect of Swift was a mistake.

That said, I concede that there is little support for this in C#.

**Comment by DarthVella** [comment]
@bondsbw The example I gave relied on the default for OutOfStateTransfer being false, but I'll concede the point.

**Comment by bondsbw** [comment]
Coincidentally, I just found out via a mailing list that Python added this concept in version 3.0.

https://www.python.org/dev/peps/pep-3102/

**Comment by HaloFour** [comment]
@bondsbw 

> Coincidentally, I just found out via a mailing list that Python added this concept in version 3.0.

Sounds nearly identical to #1458.

**Comment by bondsbw** [comment]
Indeed, if we really were trying to copy the concept from Python 3 then this proposal might extend #1458 in this way:

```c#
public void AddStudent(string name, params, bool lockerAssigned, bool outOfStateTransfer, 
    bool overwrite, bool throwOnError, int gradeLevel, int retryCount, int timeout)
{
    ...
}
```
