### ISSUE TITLE
[Proposal] let declaration keyword

### ISSUE THREAD

**Issue by taori** [dotnet/csharplang#1509]
![grafik](https://user-images.githubusercontent.com/5545184/39845508-8f1e352a-53f6-11e8-8467-e99ba02efc58.png)

While writing this code i thought how convenient it would be if there were a let declaration, which would stop leaking to the outer scope, like in javascript.

That would remove the need to duplicate variable names and altering them slightly - the given code sample isn't ideal because the differences are minor and refactoring the code would be an option too. Just thought i'd post this suggestion if it wasn't proposed before. Unfortunately "let keyword" issue search returned plenty of pages given that let is a very common word.

**Comment by ufcpp** [comment]
search "let_statement" in https://github.com/dotnet/csharplang/blob/1918cb06e1c8b79e024c688d1c4159046479276d/proposals/patterns.md

**Comment by HaloFour** [comment]
IIRC the `let` statement for pattern decomposition probably won't happen since pattern variables were changed to "leaky".

The `let` keyword has been thrown around for a lot of different purposes in different proposals, though.  It's also a possible contender for shorthand for `readonly` local variables.

I do want to say that there was at least a conversation on one of the threads about using `let` to narrow the scope of `out` declaration variables (probably over on Roslyn, buried in the deep in the comments of design notes) and that the team was fairly cold to the idea of adding a scope modifier of this nature.  But who knows.

**Comment by taori** [comment]
@HaloFour That's a pitty. i sure hope some pattern does come around which is intentionally not leaky. In the past around scenarios such as this i had quite some bugs arising from c&p code which was similar where some variables were not changed accordingly. 

If all variable names could be the same within a block those bugs wouldn't happen.

**Comment by HaloFour** [comment]
@taori 

Could always exploit the non-leakiness of `out` declaration variables in `switch` case guards:

```cs
switch (true) {
    case true when GetComboRecyclerView(view, out var recyclerView): {
        var adapter = new ProfileCombosAdapter();
        // other stuff here
    } break;
    case true when GetServicesRecyclerView(view, out var recyclerView): {
        var adapter = ProfileServicesAdapter();
        // other stuff here
    } break;
    default: break;
}
```

But this is probably a bit uglier and you have to be diligent to use blocks to keep variable scope from leaking between case labels.

Or you can just wrap each `if` in a block:

```cs
{
    if (GetComboRecyclerView(view, out var recyclerView)) {
        var adapter = new ProfileCombosAdapter();
        // other stuff here
    }
}

{
    if (GetServicesRecyclerView(view, out var recyclerView)) {
        var adapter = ProfileServicesAdapter();
        // other stuff here
    }
}
```

**Comment by taori** [comment]
That is some very creative use of switch! The second workaround however seems perfectly usable for me! certainly gonna share this with other developers. Thanks a lot.
