### ISSUE TITLE
Type constrained by 'Enum' failing to qualify as a 'struct'

### ISSUE THREAD

**Issue by SteveK-GS** [dotnet/csharplang#1511]
C# 7.3, Visual Studio 15.6.7, with Microsoft.Net.Compilers version 2.8.0.

I have an issue which is best explained with code:

```
using System;

public interface IStruct<T> where T : struct { }

// An enum satisfies a struct constraint:
public class EnumIsAStruct : IStruct<DateTimeKind> { }

// Yet this doesn't compile:
//public class MVCE<T> : IStruct<T> where T : Enum { }

// But this does compile:
public class MVCE<T> : IStruct<T> where T : struct, Enum { }
```
I would expect a generic type constrained by `Enum` to be usable as a type argument where the type is constrained by `struct` but this doesn't seem to be the case - I am having to change my `Enum` constraint to `struct, Enum`. Is my expectation wrong?

**Comment by HaloFour** [comment]
This is an odd behavior by the CLR itself.  `System.Enum` is a class, but every type that derives from `System.Enum` is a struct.  So a constraint on `System.Enum` by itself doesn't imply struct since you could pass `System.Enum` as the generic type argument.  So if you want to constraint to a specific type of enum you do have to combine it with the `struct` constraint as well.

It is weird, but it was easier to simply remove the imposed limitation on the compiler than to argue over different syntax for "enum" constraints that might have different behavior.

**Comment by SteveK-GS** [comment]
That's a nice explanation HaloFour, thank you. I'm now wondering if I should make it my standard practice to constrain to `struct, Enum` as I am always making concrete with specific enumerations and not the class `System.Enum`. Does that sound sensible?

**Comment by HaloFour** [comment]
@SteveK-GS 

Yes, I think that sounds about right.  I don't know what scenarios exist where one might want to accept `System.Enum` itself as the generic type argument.
