### ISSUE TITLE
Feature proposal: let 'is' operator compare run-time values (variables)

### ISSUE THREAD

**Issue by martinpetrovaj** [dotnet/csharplang#1529]
Hey there! I'm quite new to programming and I'm not pretending that I understand programming languages in depth (so feel free to briefly correct me, if this is not possible for some reason and why), but I was wondering why the 'is' operator requires constant values to be used.

E.g. the following produces a CS0150 error (where ExceptionType is a variable set in constructor):
`if (context.Exception.GetType() is ExceptionType)
{
    //…
}`

For the sake of simplicity, comfort and mainly readability, why couldn't the is operator also be used as a shorthand for this? At least like a syntactic sugar.
`if ( context.Exception.GetType() == ExceptionType || context.Exception.GetType().IsSubclassOf(ExceptionType) )
{
    //…
}`

I'm not 100% sure, but this might be already possible with generics. Still, using a generic class might not always be desired / feasible (e.g. if the discussed class is an attribute). Or is there a simpler way for such cases that I'm not aware of?

Thanks for all replies in advance.

**Comment by alrz** [comment]
>why the 'is' operator requires constant values to be used.

Because the evaluation order is explicitly undefined in pattern matching, this is particularly useful to generate better code for switch and recursive patterns, so the compiler is allowed to reorder checks however it wants. The fact that constants are always side-effect-free facilitates further optimizations which could be incorrect otherwise.

That said, in your example it could be safe but since the RHS is a pattern, we're still limited to constants.



>At least like a syntactic sugar.
>```cs
>if ( context.Exception.GetType() == ExceptionType ||
>context.Exception.GetType().IsSubclassOf(ExceptionType)
>```
That's one way to compare types. how about `IsAssignableFrom`? I think it's actually better to spell out the method here. there's a proposal to permit typeof in patterns for an exact match (https://github.com/dotnet/csharplang/issues/356).

**Comment by martinpetrovaj** [comment]
Thanks a lot for the tip and an insightful explanation, at least I now have some inspiration for what to learn next. `IsAssignableFrom` must have been evading me for a long time and it fits very well into most of my code.

As the suggested operation appears to be already provided by the `IsAssignableFrom` method, I'm closing this thread. Thanks once again!
