### ISSUE TITLE
Which language features should be implemented in C# v8.0 

### ISSUE THREAD

**Issue by 4creators** [dotnet/csharplang#1600]
Next major milestone in C# language development will be a release of v8.0 version (AFAI understand). Community and language team should go through a public discussion about prioritizing work on features supported by both lang team and community.

New features which would be most desired by me fall into 2 groups:

1. Major syntax improvement.
2. High performance / machine learning related features. 

Group 1:

i) Type classes, shapes or similar
ii) Higher level generics
iii) Structure inheritance (see below)

Group 2:

i) Improvements to base numeric types support (new IEEE and similar floats and decimals accompanied by literal constants and new operators allowing to skip numeric promotions);
ii) static delegates
iii) Structure inheritance - this feature spans Group 1 and 2, however, the reason I do propose it is that structs are basic data blocks used in high performance code where usually heap allocation is avoided.

**Comment by HaloFour** [comment]
If any of those issues that you've mentioned aren't currently proposed as individual issues I would recommend creating a new Issue for each one individually.  It's much easier to follow the conversation if it is limited to one topic, and the team doesn't really look through aggregate issues to parse out proposals.

If any of the above might depend on CLR changes you're probably SOL for C# 8.0.

**Comment by gafter** [comment]
The community holds its discussion and prioritization of language features on issues in https://github.com/dotnet/csharplang. You are welcome to join and chime in.

The language design and implementation teams at Microsoft take their input from those discussions and other sources to prioritize the work that we undertake. You can find a list of the language features that we are seriously considering for C# 8.0 [HERE](https://github.com/dotnet/csharplang/issues?q=is%3Aopen+is%3Aissue+milestone%3A%228.0+candidate%22). Not all of those features will actually make C# 8.0 due to resource constraints. There are many other language features that could be included based on community work, particularly the smaller features found [HERE](https://github.com/dotnet/csharplang/issues?q=is%3Aopen+is%3Aissue+milestone%3A%228.X+candidate%22), [HERE](https://github.com/dotnet/csharplang/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22X.0+candidate%22) and [HERE](https://github.com/dotnet/csharplang/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22X.X+candidate%22); any person desiring to contribute the implementation of a feature should ask us to prioritize its design. Features not on those lists are not yet supported by a minimum number of language design team participants (that minimum being one).

**Comment by 4creators** [comment]
@gafter Thanks for explanation, however, I am active user of this repo with several feature proposal filed and one PR still open. My hope is that selection of features for C# 8.0 would be based on discussion of lang team with community. As you have seen this repo discussions follow simple pattern: proposal is made, discussion is held, discussion dies. It is very rare that discussion is continued thereafter and any new proposals which are duplicate are flagged as such and usually closed.

Therofore, IMO it is very important to have discussion which would be moderated by lang devs about choice of features for C# 8.0 out of the proposals which have been already made. I understand that some choices have been already made but I would prefer to see more open and explicit discussion about choices made based on explicit community input. Surely

> The language design and implementation teams at Microsoft take their input from those discussions 

Does not live up to community expectations. Probably the reason this thread did not receive expected input is a bit unclear title wording - pls feel free to modify it.

**Comment by hypeartist** [comment]
@4creators It would be nice to have this discussion look something like this one in roslyn section: [#10378](https://github.com/dotnet/roslyn/issues/10378) or this in coreclr: [#9908](https://github.com/dotnet/coreclr/issues/9908)

**Comment by eyalsk** [comment]
@hypeartist The difference between the posts you linked to this post is that the former has a specific theme whereas the latter does not, I mean, speaking what about should be implemented in C# 8.0 when we don't get to decide that is just a waste of time.

**Comment by 4creators** [comment]
@eyalsk Than why bother with posting anything here? If you think that community has no impact on lang team decisions than perhaps we should start questioning why this repo at all exists?

@gafter @jaredpar @MadsTorgersen 

Do you think that we should not discuss what community would like to see in C# 8.0 release? Do you ignore opinions expressed in this thread or in this repo?

**Comment by HaloFour** [comment]
@4creators 

The repo is for discussing proposals, not timelines.  The team figures out timelines based on their priorities and resources.  Anything that *might* make it into C# 8.0 at this point is already in flight, and the team is very clear that there is never a guarantee as to when any particular feature might ship.  It's not like the team clears the backlog and starts fresh for each major version.  A number of the proposals slated for 8.0 have been in discussion since before C# 6.0, many have actively developed prototypes.  The team isn't going to "stop the presses" everytime someone has an opinion on the Internet.

**Comment by gafter** [comment]
> Do you think that we should not discuss what community would like to see in C# 8.0 release? Do you ignore opinions expressed in this thread or in this repo?

Such discussions belong in this repo, and we do follow them. Not every suggestion requires or deserves continuous ongoing discussion.

**Comment by 4creators** [comment]
> You can discuss what should be in the language just not when it's going to be available

@eyalsk Sounds like a censorship - _when_ is equally important as _what_.

> but you know what they say good things come in small packages

This point of view is particularly _true_ due to the introduction of generics in C# 2.0 _LOL_ which should be _bad thing_ according to your saying

**Comment by 4creators** [comment]
> Such discussions belong in this repo, and we do follow them. Not every suggestion requires or deserves continuous ongoing discussion.

@gafter Your response pretty much misses the point

**Comment by Joe4evr** [comment]
> *when* is equally important as *what*

Man-hours needed to actually *implement* features are limited. The team already has a backlog of features they want to add to the language, and the slate for 8.0 has already been set, so there's no point in changing that.

**Comment by tannergooding** [comment]
> when is equally important as what.

@4creators, It is also important to remember that the people commenting on issues here, while vocal, may not be an accurate representation of all feedback given.

GitHub is not the only place Microsoft gets feedback from. Feedback is also provided internally (from within Microsoft), from other companies (some who may not use GitHub), and from other feedback channels (those that aren't GitHub).

All of these inputs have to be taken together, and not all of the data is necessarily shareable.

**Comment by tannergooding** [comment]
(that applies to any issue, features, etc; and not just to C# Language Design)

**Comment by HaloFour** [comment]
@4creators 

> Sounds like a censorship - when is equally important as what.

You can discuss it all you want.  Just be aware that you demanding a timeframe won't yield you one and demanding that a feature end up in version *x* is very certainly going to result in being ignored.  The team is extremely reluctant to commit to timeframes for anything that isn't very close to completion and even then there is (and will always be) the possibility that any given feature is going to be punted.  The team isn't going to hold up a version of C# indefinitely just because they (or anyone else) *really* wants to try to cram some difficult and time consuming feature into the language.  The language will ship, that feature will slip, and if it gets back on track it'll be under consideration for the next possible release.

**Comment by 4creators** [comment]
> GitHub is not the only place Microsoft gets feedback from

> It is also important to remember that the people commenting on issues here, while vocal, may not be an accurate representation of all feedback given

@tannergooding Yeah, I am fully aware of this. However, I still think that most critical resource allocation which in this case is developer time should be discussed. We have plenty of proposal spanning a lot of different syntactic and semantic C# features and I would like to see some discussion about prioritizing them.

For instance for me personally it is a waste of time to go after syntactic sugar right now while fixing some serious deficiencies around type system and low level performance oriented language features should be a top priority. Due to several serious C# deficiencies which seems to not going to be addressed in v 8.0 I am starting to analyze possible switch to another language as my first programming lang despite the fact that I use C# from 2002 onward and love it. Most probably it may happen in gradual form where parts of new projects will be implemented without use of C#.

Large version language update is always very significant step as any major change which requires runtime changes is slated for such milestone and IMO requires careful planning which should involve community. As such this discussion should be part of large feedback loop - I do not expect to have decisive role in decisions taken but I would expect that community at least deserves some voice on this subject.

If it is not happening as many of ppl think that I would rather rise a warning flag about sorry state of C# team vs. C# community relations.

**Comment by HaloFour** [comment]
@4creators 

> For instance for me personally

Yes, for you, personally.  There are a massive number of people in this ecosystem all with competing ideas of what should be prioritized.  The backlog is huge and the team isn't going to address all of their highest priority items for C# 8.0, let alone anyone else's.

> some serious deficiencies around type system

The team is exploring shapes, concepts, HKTs and traits.  These things are complicated and require time to bake.  With the exception of traits, which has been in progress for several years now, none of these are likely to fit within a timeframe appropriate for releasing C# 8.0.  Anything requiring CLR changes, which is where many of the type system limitations come from, will take significantly more time and require significantly more justification.

> and low level performance

A good portion of C# 7.x was dedicated around improving performance-sensitive scenarios, such as `ref` locals and returns.  If you have specific proposals to expand on that feel free to open them here.  Again, if they involve changes to the CLR their likelihood of happening and timeframe change significantly.  Changes that would negatively impact existing code are likely to not be considered at all, re numeric promotion.

> Due to several serious C# deficiencies which seems to not going to be addressed in v 8.0 I am starting to analyze possible switch to another language as my first programming lang despite the fact that I use C# from 2002 onward and love it.

Good.  Learn some more languages and use them.  If you find their features compelling and want to engage the C# team about them all the better.  C# is one tool in a toolbox.  It's not meant to nor will it solve every possible problem.  Being polyglot is a virtue.

**Comment by tannergooding** [comment]
Every single person on this repo has slightly different priorities, but the general trends tend to align.

I would much rather see my proposals (static delegates, IntPtr operators, general purpose Fixed Sized Buffers, blittable constants, etc) go in than some of the other C# 8.0 features. But I am also not the only target customer and am, in fact, a relative minority for the type of code I actually write.

It also isn't just as simple as deciding some proposal looks good and implementing it. Many of the proposals are very similar, but slightly different. These similar proposals need to be "merged" into a single proposal that fits the various needs, goals, and will be cohesive in the language. Then that feature has to be taken into context with relation to every other championed feature to ensure that if we do X in 8.0 we can still do Y in 9.0. This is a lot of work, but overall, ensures that the language doesn't get backed into some corner that prevents forward progression.

**Comment by tannergooding** [comment]
For every good proposal, there is also just as many (if not more) bad proposals. These also have to be gone through and nicely told why it is a "bad" idea (and telling someone there idea isn't the greatest, or in some cases that it is down right terrible, is never easy, especially over the internet 😄).

Just remember, there are people who would like the language to do things like:
* Remove curly braces
* Become whitespace sensitive
* Remove semicolons
* Only add functional features
* Never add functional features
* etc

**Comment by 4creators** [comment]
> Good. Learn some more languages and use them.

@HaloFour  Red flag is very high up indeed. Arguments _ad personam_ tend to be treated very nasty since even before Schopenhauer wrote about them.

**Comment by 4creators** [comment]
@tannergooding 

Very much agree with you point that many developers would have somehow divergent priorities for language development due to nature of code they write.  However, once we start discussion about what is important and what less so or terrible in general it is much easier to narrow down community preferences for the very precious time window we have before .NET v3.0 release which I understand will be accompanied by major language version release. It is once couple of years opportunity to make something significant for both C# and .NET runtime.

**Comment by HaloFour** [comment]
@4creators 

> Arguments ad personam tend to be treated very nasty since even before Schopenhauer wrote about them.

This isn't a personal argument.  *Everyone* should learn and use multiple programming languages.  This is true of the C# community and *especially* of the C# team themselves.  They're all tools with different use cases, strengths and weaknesses.

If you know of a tool now that solves your problems then by all means use it.  Claiming that you're going to stop using C# unless it immediately shifts focus to meet those use cases is not a threat.

> However, once we start discussion about what is important

Those discussions are constantly happening.  The C# team can and does weigh the community feedback that they get through their various channels (of which Github is probably the tiniest minority).

**Comment by jnm2** [comment]
@4creators What's wrong with the suggestion to learn more languages? It's a very good point and charitably made.

**Comment by tannergooding** [comment]
> it is much easier to narrow down community preferences 

Right, but as has been stated multiple times, the community is only part of the voice here (even if it is the most visible voice).

> It is once couple of years opportunity to make something significant for both C# and .NET runtime.

I'm not quite sure this is true. The release cadence has been fairly fast already (especially since C# 7.0 came out). On the other hand, however, the set of features that are planned for C# v8.0 and CoreCLR/FX v3.0 has already been discussed, extensively (both here and elsewhere). Many of the features that are going in are some of the top requested features (and have been "top requested" features for quite some time)

Core Runtime:
* v1.0: JUN 2016
* v1.1: NOV 2016
* v2.0: AUG 2017
* v2.1: MAY 2018
* v2.2: Q4 2018 (https://github.com/dotnet/core/blob/master/roadmap.md)
* v3.0: Q1 2019

Language:
* v1.0: JAN 2002
* v1.1: APR 2003
* v2.0: NOV 2005
* v3.0: NOV 2007
* v4.0: APR 2010
* v5.0: AUG 2012
* v6.0: JUL 2015
* v7.0: MAR 2017
* v7.1: AUG 2017
* v7.2 NOV 2017
* v7.3: MAY 2018
* v8.0: ???

**Comment by yaakov-h** [comment]
> It is once couple of years opportunity to make something significant for both C# and .NET runtime.

This is actually true, @tannergooding, if you consider the words "and .NET runtime."

Most likely, v8.0 will be March 2019 alongside .NET Framework 4.8, .NET Core 3, Windows 10 v1903, and probably Visual Studio 2019.

Microsoft do seem to enjoy getting all their ducks in a row.

If this does turn out to be the case, that would make it 2 years after v7.0, which would be the second-quickest major version release so far, on par with C# 2.0 -> 3.0.

Core Runtime and C# are each getting frequent updates, but adding a new major feature to C# that depends on new runtime changes has to be coordinated across the language, Roslyn, and at least two different CLRs. That _does_ only happen once every few years.

That said, however, it does only get released in alignment once every couple of years, but these things take much longer in preliminary design, planning, prototyping, testing, etc. Some of the features slated for C# 8 have been in prototyping since C# 6 or earlier.

@4creators, you can't come along when C# 8.0 is the immediate next release and demand to have a discussion about prioritisation and scheduling. This stuff has been in the works for years already.

If you want to have a talk about C# 9.0 or 10.0, this might be a good time to start, but 8.0 is already well on it's way, and it's far too late to start a public discussion about that.

**Comment by eyalsk** [comment]
@4creators 

> Sounds like a censorship - when is equally important as what.

Discussing it won't change their prioritization so it's not important at all, in fact, it's a waste of time so by all means discuss it, it's your time.

**Comment by jaredpar** [comment]
> If you want to have a talk about C# 9.0 or 10.0, this might be a good time to start, but 8.0 is already well on it's way, and it's far too late to start a public discussion about that.

What *exactly* will constitute C# 8.0 is not written in stone at this point. There are still a number of features up for consideration and we continue to take feedback on how to prioritize these and other items. Input is always welcome but realities of shipping are always there 😄 

That being said though your point about how long we've been seeding these features is very true. Big features take a **lot** of time. Consider this iteration of nullable reference types. We first started prototyping that when I re-joined the C# product team 3 years ago and there is still considerable design work left. All told it will be a 4+ year project if it ships in C# 8.0. And that's not even counting all of the previous attempts at non-null that failed but helped inform our current design. That's a bit of an outlier but in general our bigger features take a lot of time, coordination which make it hard to pivot to them suddenly.

**Comment by asyncawaitmvvm** [comment]
> This isn't a personal argument. Everyone should learn and use multiple programming languages. This is true of the C# community and especially of the C# team themselves. They're all tools with different use cases, strengths and weaknesses.

I hate to say it but C# 7+ is easily the best of all the programming languages. You can throw them all out except C/C++ and ignore them forever. You'll learn more CS theory by engaging C# coding patterns than you will by drowning in every other glue language's boilerplate and lack of design discipline.

**Comment by orthoxerox** [comment]
@asyncawaitmvvm That's just [the blub paradox](https://en.wikipedia.org/wiki/Paul_Graham_(programmer)#Blub) in action.

**Comment by tannergooding** [comment]
@ViktorSize, there are a number of existing issues related to this. You should be able to see them here: https://github.com/dotnet/csharplang/search?q=backing+field&type=Issues

**Comment by TheFanatr** [comment]
I just want to point out that while it is understandable that the C# language designers are not likely to and/or are reluctant to suddenly change their priorities for the next upcoming release of the specification simply due to some keyboard warriors on GitHub, I do believe that the public side of the "C# feature request community", which this repo's "issues" section is supposed to be a voicing platform for, should have more of a say in what the designers should be focussing on, even if our thoughts are only a small minority of the feedback being sent to them. The reasoning behind this is simply that in general terms, the opinions voiced here are of the people who actually use C# on a day to day basis for real projects in diverse domains, specifically more likely to be outside of the Microsoft community. I am saying this because if an individual is a part of the internal Microsoft community, I would assume they would address their suggestions through Microsoft-internal pathways. As such, the discussions held here should be given more weight if anything, because by deductive reasoning the opinions expressed here are generally coming form people with more diverse viewpoints, and represent the thoughts of the people who actually use the language outside of Microsoft-specific applications, in a broad sense. Basically, I, likely as well as many others, would greatly appreciate a channel we can use to suggest features for the language designers to specifically focus on for a suggested potential release, in order to create some resemblance of a representation of the thoughts of the people who use C# in general. Please correct me if I have been mistaken with what I have stated.

To explicitly clarify, when I mention that the thoughts posted here are likely to not be Microsoft-internal, what I am trying to express is that the people who use this channel to communicate suggestions to the language designers are probably not directly linked with or subordinated by Microsoft, because, I'd imagine, if they were, they'd have much more effective ways of communicating their proposals. If a Microsoft employee, or an employee of a Microsoft subsidiary, such as Unity Technologies where to propose a language feature, they'd likely get more people on their team to publicly support the idea, then send an email or a management-chain-telephone request (asking a manager to ask their manager) to present the idea to the team, instead of creating a proposal on GitHub, especially if more people on their team would find it useful, as previously mentioned. I do not know if this is the case, but I would imagine it to be so, and I would ask that anyone knowledgeable of the actual situation please correct me if what I have stated is inaccurate. If my statements are not functionally or practically incorrect, I would like to reiterated that this matters because then the opinions presented here are more likely to be from "us", "the developers".

Lastly, I would like to ask if there is a more official or direct channel for discussions such as what should be contained in a future release of the language, as a community-generated proposal for which features should be focussed on. If there is not one, for the reasons I have mentioned above, if still valid after correction, a channel specifically for this purpose should be created.

Thank you for you time, and my apologies for the long post.

**Comment by svick** [comment]
>  a Microsoft subsidiary, such as Unity Technologies

Unity is not a subsidiary of Microsoft.

> channel specifically for this purpose should be created

Why? What makes this repo insufficient?

**Comment by yaakov-h** [comment]
> even if our thoughts are only a small minority of the feedback being sent to them

You want a disproportionately large say in the matter? That doesn't sound fair.

> the opinions voiced here are of the people who actually use C# on a day to day basis for real projects in diverse domains

As are their other channels, I'm sure. Microsoft do, AFAIK, have other feedback channels which take input from extra-Microsoft companies, not internal-only.

> in order to create some resemblance of a representation of the thoughts of the people who use C# in general

but you just said that this repo might be a minority... 😕 ❓

**Comment by HaloFour** [comment]
@TheFanatr 

The C# language is not a democracy.  It is a benevolent dictatorship.

This is the official channel through which you can make suggestions for features.  C# language designers spend a lot of time here and often weigh in on proposals.  But the C# language designers are also have the final say as to what proposals go forward (are championed) and the C# language designers are responsible for going through that design process.  If a proposal isn't championed, it's not going anywhere.

As for timing, the features intended to make the next release are tagged with milestones, and the team discusses them openly here and through various other venues.  But the team never makes any promises as to the release version or date or a particular feature.  Any feature slated for 8.0 can easily slip.  It's happened before.  The team also doesn't attempt to curate a long list of features ahead of time.  They already have a long enough backlog of work and proposed features for several major versions.

**Comment by jnm2** [comment]
@ViktorSze That is exactly what https://github.com/dotnet/csharplang/issues/140 proposes.

**Comment by TheFanatr** [comment]
To everyone, for clarification, the reason I repeatedly mentioned or implied that the feedback received through this repository is a minority of the total feedback received by the team is because such a thing was mentioned earlier in this issue as far as I could remember when writing the post.

@svick 
> Unity is not a subsidiary of Microsoft.

What I trying to get to is that they own it, so it's not an external entity.

> Why? What makes this repo insufficient?

The fact that we are being told to not discus suggestions for the future of the language, or to do so if we choose to, but that it would not make a difference.

@yaakov-h 
> You want a disproportionately large say in the matter? That doesn't sound fair.

My point was that it's not disproportionate in a relative sense; if Microsoft-internal feedback comes through Microsoft-internal feedback channels, then everyone else's opinion should come through here, unless there are other major public feedback channels that I have not been made aware of.

> As are their other channels, I'm sure. Microsoft do, AFAIK, have other feedback channels which take input from extra-Microsoft companies, not internal-only.

Extra-Microsoft companies yes, likely through relations personnel, but I was referring to other existing channels for the masses. I do not believe there are any other than this one. My point was that even though the team may be uninclined to take major direction feedback from only one out of many sources, maybe they should weigh it more, because as far as I am concerned, it is the only public channel.

> but you just said that this repo might be a minority... 😕 ❓

See the message to everyone at the top of this post.

@HaloFour 
I understand this; however, I believe that it is important that we be welcome to contribute to a community-curated focus-point list for the future direction of the language, for the team to consider as a representation of what the independent community thinks, because such a thing coming from users on this repo would likely be created based on the opinions of people that Microsoft wouldn't see in other feedback channels. They don't need to take it as a requirement, but rather as a list of things that people want to see. Basically, what I am trying to point out is that every other feedback channel would probably see the thoughts of Microsoft-internal users of the language or "corporate project" users of the language, but this one is the only one that should really represent the average C# user that doesn't fit into the previous criteria for people who would use other channels; as in, these are explicitly different voices and perspectives than those they see from other sources and likely represent a larger proportion of the overall populous of C# users. If the main issue is that the team would prefer to not take any directional feedback from anyone, I would understand why this request is being treated negatively, but I assumed this should not be the case because if Team Y needs Potential C# Feature X very badly, it would be prioritized, and I should be explicit in saying that I do not know if this is the case.

To reiterate my point as simply as possible, I would declare it as so: Microsoft likely has very many internal feedback channels, none of which would see the opinions of anyone except large corporate clients and/or Microsoft-internal employees, so if those channels are allowed to influence the direction of the language based on need, I believe that this ability should be granted to this community as well because the inputs received here represent a more diverse set of perspectives and a larger percentage of the C# userbase purely based on the fact that it's the only channel they have access to. If however no one may influence such things, I am requesting that a way to do that be created, because I think it is important that an open-source project with such a broad following and interest as C# have a way for the community to influence it's direction. This could even be implemented as a separate website where people can upvote and downvote feature or change ideas posted as issues to this repository.

I hope this explanation and these responses have clarified my stance on this issue, and what I am trying to articulate.


Also, it would seem that if I had $5 for every time I've written "feedback channel" in this thread, I could buy Microsoft and fix this myself.

**Comment by HaloFour** [comment]
@TheFanatr 

This repo is already exactly that.  The community may make proposals.  The community may submit feedback to design notes.  The team has expressed interest in both by championing and implementing community proposals and sometimes pivoting their design decisions based on our commentary.  I don't know what you're looking for beyond that.  It's not our place to tell the C# team what to do or where to focus.  There team is not going to start time boxing themselves as to what features must be in which version of the compiler, nor will they allow the community to do that to them.

**Comment by jnm2** [comment]
@TheFanatr 

> > Unity is not a subsidiary of Microsoft.
> 
> What I trying to get to is that they own it, so it's not an external entity.

An external entity is precisely what Unity is. Microsoft is listed among its partners at https://unity3d.com/partners.

**Comment by tannergooding** [comment]
GitHub is not the only public feedback place, there is also UserVoice, VS Feedback, etc.
Private feedback also doesn't just come internally, it also comes from external partners. Sometimes that feedback is made privately (due to various business needs) and it will not be made visible.

In the end, the language team takes all the input, looks at what is needed, what will be used, and what they want to work on and prioritizes accordingly.

**Comment by tannergooding** [comment]
It may also be good to keep in mind that input from someone who is writing an app/framework that will be used by 10 people is very different from input that comes from someone who is writing an app/framework being used by 10,000 people.

Both are very important inputs, but they make very big differences when you are talking about how big an impact this feature will have (how many people will use it, how much faster will it make code, how much complexity can it reduce, etc).

**Comment by tannergooding** [comment]
`Span` as an example, is a relatively niche performance-oriented feature; but it was determined to have a major impact because it could speed things like string processing operations by a very significant margin; thus benefiting everyone by reducing the amount of copying that things like CoreFX or ASP.NET have to do behind the scenes.

Something like async on the other hand is a very widely used feature and significantly reduced the amount of code the average developer has to write and significantly reduced the complexity of code to achieve the required "major impact" to be implemented.

Something like `IntPtr` operator support, on the other hand, is something that is championed (so it will probably get implemented, in some form, eventually); but is both a niche feature and doesn't have very much estimated impact; so it gets deprioritized behind other features (regardless of what I, or other people from the community want for it).

**Comment by 4creators** [comment]
Created separate issue with proposal to follow RFC process for major releases.

**Comment by 4creators** [comment]
#1838 forgot to add link 😄

**Comment by 333fred** [comment]
I'm going to close this issue out. The proposals in this thread have been split out into separate issues.
