### ISSUE TITLE
proposal: public and protected local functions

### ISSUE THREAD

**Issue by lazyloader** [dotnet/csharplang#1617]
local functions are scoped to the main function, which causes issues

```csharp
public void Foo()
    {
    return bar();

    int bar() 
        {
        return 3;
        }
    }

public void Baz()
    {
        bar();   // error
    }
```

so i suggest we make the option to have `public` so we can do this
```csharp
public void Foo()
    {
    return bar();

    public int bar() 
        {
        return 3;
        }
    }

public void Baz()
    {
        Foo.bar();   // works
    }
```

this maintains the same benefits of local functions but allows it to be used for the one or two other functions that need it. `protected` would work in a similar way, but with `virtual` functions

```csharp
public class C 
{
    public virtual void Foo()
        {
        protected int Bar() => 3;
        }
    
    public void Fuzz() 
        {
      	// cant use Bar
       }
}

public class D : C
    {
    public override void Foo()
        {
        base.Foo();

        // can use either one of these
        Bar();
        base.Foo();
        }
    
    public void Baz()
        {
    	// cant use bar
	}
    }
```

`protected` allows the local functions to be visible to only those who `override` them, or inherit from using `: this()` or `: base()` for constructors

**Comment by Neme12** [comment]
That's not an issue, that's the purpose of local functions.

**Comment by lazyloader** [comment]
@Neme12 it is when i want to use them in overriding functions, such as i am in this example

**Comment by jnm2** [comment]
I think if something participates in polymorphism, it should be a direct member of the class. Otherwise overriding is unnecessarily painful.

**Comment by Neme12** [comment]
I don't understand. If you want the function to not be local, why do you want a local function?

**Comment by jnm2** [comment]
It also suffers from the same name qualification issues as https://github.com/dotnet/csharplang/issues/1329.

**Comment by lazyloader** [comment]
@Neme12 its still is local though. it will only be visible to that function and those who override it, making things cleaner. how can a function properly override one if it cant use the same tools it used. i wouuld have to redefine it which is bad practice

**Comment by Neme12** [comment]
> it will only be visible to that function and those who override it

how does that work with

> so i suggest we make the option to have public so we can do this
> ```c#
> public void Foo()
>    {
>    return bar();
>
>    public int bar() 
>        {
>        return 3;
>        }
>    }
>
> public void Baz()
>    {
>        Foo.bar();   // works
>    }
>```

**Comment by eyalsk** [comment]
@lazyloader What happens when consumers override the method? should it be available to them too? It's a strong sign that it shouldn't be a local function.

**Comment by Neme12** [comment]
But most importantly, local functions can capture.

```c#
using System;

class C
{
    public void Foo()
    {
        var s = Console.ReadLine();

        void PrintIt() => Console.WriteLine(s);
    }

    public void Baz()
    {
        Foo.PrintIt(); // what happens now?
    }
}
```

**Comment by Neme12** [comment]
> how can a function properly override one if it cant use the same tools it used. 

It is called a "local" function for a reason. The overriding method doesn't have access to the same scope. It doesn't even have to be executed. You can't use local variables from an overriden method either.

**Comment by lazyloader** [comment]
@Neme12  A few things could happen. It could follow the execution change all the way up and call `Console.ReadLine`, they would get an error for using a method that has captured variables or it doesn't show up in intelisense, or they can use the captured variables if they did `override var s;`

**Comment by lazyloader** [comment]
@eyalsk So you mean this

```csharp
public virtual void Foo()
    {
    public int Bar() => 4;
    }

...

public override Foo()
    {
    Bar();   // works
    base.Bar(); //works
    Foo.Bar(); //works
    }
```

**Comment by HaloFour** [comment]
@lazyloader 

Local functions, like locals in general, are entirely private to the method in which they are defined.  Overriding methods don't have access to locals of the method they override.  Other than occupying the slot in the type's virtual table they are entirely unrelated methods.

As already mentioned, local functions can implicitly capture the enclosing scope.  Because local functions are hoisted this is doubly-complicated.  An overriding method, being a *completely* separate method, has no access to that enclosing scope.  It would make no sense for an overriding method to invoke a local function that encloses a scope that doesn't exist.

Second, this would require promoting all of the compiler-generated plumbing for local functions to something that must be both strictly specified in the language specification and stable as now that local function could be called from a completely different assembly.  That means names and signatures that cannot change between compilations or even between compilers.  In the best of circumstances this would be something that is incredibly fragile.

But in the case of local functions it's even worse because the local function could be implemented in multiple completely different and incompatible ways depending on how that local function is defined and what the enclosing method does.  For example:

```cs
public virtual int M() {
    int x = 3;
    int y = 5;
    return local();

    int local() {
        return x + y;
    }
}
```

In this case `local` is implemented as a private static function and the enclosed variables `x` and `y` are promoted to fields on a private struct which is passed by ref to the function.

But if I make this seemingly unrelated change:

```cs
public virtual int M() {
    int x = 3;
    int y = 5;
    Func<int> add = () => x + y;

    return local();

    int local() {
        return x + y;
    }
}
```

The entire code generation has to change.  Now `x` and `y` are promoted to fields on a *class* and `local` is implemented as an internal *instance* method of that class.  This is required to support the different lifecycle of delegates.

**Comment by gafter** [comment]
I cannot imagine that this is something that we would ever do, for all of the reasons discussed in this thread. Using a local function elsewhere is semantically meaningless because the captured scope does not exist elsewhere..
