### ISSUE TITLE
add then keyword to improve readabilty

### ISSUE THREAD

**Issue by lazyloader** [dotnet/csharplang#1619]
```csharp
if (true)
   {
   }
```
vs
```csharp
if (true) then
    {
    }
```

this change should be forced by the compiler so that everyone can benefit fromt he readabilty. this might break some code but the gains outweigh the cost in this case

**Comment by benaadams** [comment]
Might prefer VB.NET which has that syntax? https://github.com/dotnet/vblang/blob/master/spec/statements.md#conditional-statements

e.g.
```vb
If a < b Then
    a = b
Else
    b = a
End If
```

**Comment by HaloFour** [comment]
Done, and it's been backported to C# 1.0:

```cs
if (true) // then
    {
    }
```

**Comment by stakx** [comment]
> but the gains outweigh the cost in this case

Yeah, this change would only break pretty much every C# program that ever existed. I can see that the gains here are truly enormous.

Please, just close this issue.

**Comment by lazyloader** [comment]
@benaadams I used to use VB, so that's what I'm used to, but I'm working in Unity now so I need to use C#

**Comment by yaakov-h** [comment]
![a39661e0-9afe-4645-84fa-4807b58c0091](https://user-images.githubusercontent.com/426009/41202843-667c4cc6-6d12-11e8-8f41-8352676c7576.gif)

**Comment by theunrepentantgeek** [comment]
> this might break some code

As a conservative estimate, you just suggested breaking hundreds of billions (yes, with a *b*) of lines of code written by tens of millions of developers over the last fifteen years.

Fortunately, the folks in charge of the evolution of C# would never do such a thing.

**Comment by DavidArno** [comment]
@lazyloader,

If you want to improve the readability of your code, I'd suggest you have a long hard think about the weird brace style that you are using and switch to one of the conventional styles used in C#. You don't make your C# code more readable by trying to redesign the syntax to look like another language that you are used to. Readability is hugely improved by following language conventions though.

**Comment by orthoxerox** [comment]
@DavidArno what do you have against Whitesmiths style? Although I'm afraid it's "my first language was Python" style these days.

**Comment by theunrepentantgeek** [comment]
***Without*** getting into a debate on the "right style", it's worth pointing out that by far the majority of C# code you will see in the wild uses [Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), perhaps for no other reason than "that's what Visual Studio enforces out of the box".

@lazyloader, presentation counts. If you want your suggestions for language improvements to be taken seriously, it's worth you taking the time to make your proposal as appealing as possible. In this case, using a brace style that's unfamiliar to the majority of your audience just serves to distract them from your suggestion.

**Comment by jamesbascle** [comment]
Is this makeloft? 🤔

**Comment by yaakov-h** [comment]
@jamesbascle 
![image](https://user-images.githubusercontent.com/426009/41264386-bc3c6efc-6e2f-11e8-83b8-52455ee05741.png)

**Comment by DavidArno** [comment]
@orthoxerox,

I have nothing against the Whitesmiths style of braces. The point I was trying to make is the same as @theunrepentantgeek makes, likely better than me: "*using a brace style that's unfamiliar to the majority of your audience just serves to distract them from your suggestion*". Distracting folk with unconventional syntax makes the code less readable.

**Comment by Korporal** [comment]
@lazyloader - The simple reason C# has the (poor) syntax that it does is that it was decided by the team to follow conventions and grammars established already for Java which itself had intentionally followed the (poor) syntax of C++ and C.

Thus it is purely historic and a means of "helping" developers migrate to C# when they had been using any of those other languages.

I'd rather the team had reviewed some alternative grammars and made a truly bold decision to advance programming language design.

As I've mentioned many times on forums and so on, the old PL/I (or PL/1) language designed by IBM had a very advanced grammar that I've never seen before or since in any imperative language.

The key step taken by the designers of PL/I was to support no reserved words and allow identifiers to be named anything including keywords.

The reason was not to show off or anything but to make it straightforward to introduce new keywords in the future without breaking existing source code something that the C# team could have considered but in their obsession with C++/C syntax did not do.

As we've seen over the years adding new features to C# is a challenge partly because of this syntactic ball and chain.

**Comment by Nukepayload2** [comment]
@lazyloader 
Actually, you can use VB.NET in Unity3D. Here is my [Unity3D calculator application](https://github.com/Nukepayload2/Unity3DCalculatorVB). All calculation logics and 95% of UI codes were written in VB.NET. I have tested that app on my Android 4.4 phone and a Windows 10 PC.

**Comment by jrmoreno1** [comment]
I’d like to see more questions closed as rejected...including this one

**Comment by YairHalberstadt** [comment]
Hi

I'm going to close this issue, as it's suggesting a major breaking change, for no real benefit.

If you'd like to discuss this further, let me know, and I'll move it to a discussion.
