### ISSUE TITLE
Showing empty space warning when there is no empty space in the code.

### ISSUE THREAD

**Issue by anirugu** [dotnet/csharplang#1637]
(bool) /\ 0

This is the invalid c# code, first it's have invalid expression '/' and second is '\'
when I am executing the code it's showing 4 issues.

I know this code is terribly incorrect but it should only show 3.  I am thinking that invalid expression term
'' should not be shown in the errors because there is no empty space there at the 1,9.

![image](https://user-images.githubusercontent.com/2105258/41454322-92e708d2-7096-11e8-89ea-3e8c9fa052c3.png)

**Comment by Pretasoc** [comment]
I don really get, what you trying, but since this is related to the compiler output i think [dotnet/roslyn](https://github.com/dotnet/roslyn) repository might be the correct. Invalid expression term '' means, roslyn exprect an expression therm but only finds '' which is no expression term. You can use [sharplab.io](sharplab.io) to see the parse tree.

**Comment by jnm2** [comment]
@Pretasoc Your link is `sharplab.io` which is a relative URL and 404s. `//sharplab.io` would have worked, though.

**Comment by anirugu** [comment]
Hello @Pretasoc 

My code was invalid, it can not be compiled. please clear this confusion that I can see my parse tree for invalid code or code that can't be compiled.
