### ISSUE TITLE
Typo in `proposals/csharp-7.2/readonly-ref.md`, or bad implementation in Roslyn?

### ISSUE THREAD

**Issue by stakx** [dotnet/csharplang#1655]
@zvirja noticed in https://github.com/castleproject/Core/pull/370#issuecomment-399370350 that there appears to be a typo in [proposals/csharp-7.2/readonly-ref.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md#metadata-representation-of-in-parameters):

> ## Metadata representation of `in` parameters
>
> [...] In addition, if the method is *abstract* or *virtual*, then the signature of such parameters (and only such parameters) must have `modreq[System.Runtime.CompilerServices.IsReadOnlyAttribute]`.

Roslyn actually appears to encode a `modreq([mscorlib]System.Runtime.InteropServices.InAttribute)`.

So which party has got it right: Roslyn, or the proposal in this repository?

I suppose the answer will be that Roslyn is right, that proposal seems out-of-date. Or has specification really not started yet even though the feature has already shipped?

> * [X] Proposed
> * [X] Prototype
> * [X] Implementation: Started
> * [ ] Specification: Not Started

**Comment by bbarry** [comment]
`InAttribute` has been in the framework since at least 1.1 and shouldn't need to be duplicated and is defined in the mscorlib assembly in .net standard 2.0: https://github.com/dotnet/standard/blob/e2cbc66c56edf5dc43cc00902ead04d20e32795e/netstandard/ref/mscorlib.cs#L10036

The test cases in Roslyn utilize the assembly qualifier, but the actual code in the compiler doesn't seem to depend on anything more than the namespace qualified type.  I think it would be a breaking change to the compiler to require an assembly qualifier and is inconsistent with other well known types. 

Perhaps the business of `modreq` should be said differently. The CIL representation is omitted elsewhere in places where the language spec discusses attribute usage.  Elsewhere in the specification language such as "`...Attribute` is used on ..."  and `...Attribute` is defined ...`.

Maybe this would be better:

> In addition, if the method is *abstract* or *virtual*, then the signature of such parameters (and only such parameters) must have the attribute `System.Runtime.CompilerServices.IsReadOnlyAttribute` defined.

**Comment by stakx** [comment]
Seeing that #1658 was approved and merged, I will take this to mean that the updated documentation reflects how things ought to be. Closing.
