### ISSUE TITLE
[Proposal] Parameter list null check

### ISSUE THREAD

**Issue by lumlune** [dotnet/csharplang#1661]
Imagine a world where you can put `!` on nullable types in your function signature to indicate that, if the type is null, the function call should not proceed.

```cs
void QueueAsset(Data data)
{
    if (data != null) { /* Function body */ }
}
```

Becomes:

```cs
void QueueAsset(Data data!)
{
    /* Function body */
}
```

##### Advantages

1. It parallels `?` as an existing null-check character.
2. It eliminates a lot of noisy null checking. Too many methods are simply contingent on certain elements existing and don't have particular `else` logic.

##### Complications

1. Functions with return types have to be considered. If the return type is nullable and the function is skipped (as per a null parameter), the return value could default to `null`.
2. If the return type is not nullable, either forbid this type of syntax or engineer additional syntax to let the user configure a default return value.

**Comment by Joe4evr** [comment]
[This is already being considered as part of Nullable Reference Types](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md#tweaks) (except the `!` is on the *type*, not the variable).

**Comment by stakx** [comment]
@Joe4evr: Are you referring to this?:

> We could consider a shorthand `T! x` on parameters, that auto-generates a runtime null check.

Assuming that "null check" means either (a) cause a compile-time error/warning if `null`, or (b) throw a `ArgumentNullException` at run-time if `null`, then this isn't the same as what this issue is asking for. Here we're talking about null-conditional execution.

I'm not sure I can think of many use cases where this feature would come in handy. I feel much more comfortable trying to get rid of `null` as much as possible in the first place, so that I'll need as few null checks at runtime as possible.

**Comment by Joe4evr** [comment]
The quote you posted yourself says `runtime null check`, so the answer is pretty obvious. 

Additionally, skipping execution would be the responsibility of the *caller*. If the callee wants to not blow up from being passed a `null`, then it should be stating that it can be gracefully handled by marking the parameter with `T?`. Should that make the return value `null` as well, the method should be adorned with `[NullInNullOut]` so that the compiler's flow analysis is able to track that.

**Comment by stakx** [comment]
@Joe4evr: I totally agree with your above response, just a small nit: _"runtime null check"_ only says that a check is being made. It doesn't say what the action would be (throwing? returning early? running a hot bath for the programmer?), so I personally didn't actually it very clear.

**Comment by jnm2** [comment]
> (throwing? returning early? running a hot bath for the programmer?)

Only one of these options is close to making sense to me, personally. 😁

**Comment by DarthVella** [comment]
That's such a good idea! Except, if the tap stops working, you'd have to catch the System.BathException...

**Comment by LeonG-ZA** [comment]
> Functions with return types have to be considered. If the return type is nullable and the function is skipped (as per a null parameter), the return value could default to null.

This is really bad. An exception should rather be thrown in these cases.

> If the return type is not nullable, either forbid this type of syntax or engineer additional syntax to let the user configure a default return value.

The only way I can really see this working is if you somehow specify a default value returned on skipping for both nullable and non-nullable types. At least this way the programmer will know what will get returned.

I think the best solution would be just add an one 'if' statement instead of complicating the language and readability.
