### ISSUE TITLE
[Proposal] LINQ Syntax the same SQL Syntax

### ISSUE THREAD

**Issue by ricardogaldino** [dotnet/csharplang#1679]
Hello guys,

Many programmers are familiar with SQL, would not it be better if the LINQ syntax were the same SQL syntax?

For example, keep the syntax of SQL statements such as "select" (at the top), "inner join", "left join", "right join", "group by", ..., same in LINQ.

I've always wondered why LINQ is different from SQL. Is it because of performance or intellisense? Could not be created something based on the engineering used in SQL Server to be able to not harm in this aspect?

**Comment by HaloFour** [comment]
@ricardogaldino 

> I've always wondered why LINQ is different from SQL. Is it because of performance or intellisense? 

The latter.  SQL as a language makes it impossible to design good tooling because you start with the columns before you've defined the tables and the context could be affected by any number of the clauses that follow.  Anytime I use a query tool with autocomplete I usually pound out the `SELECT *` just to get to the `FROM` clause and I revisit the `SELECT` clause at the end.  LINQ was designed very specifically to flow naturally so that as you type the Intellisense knows exactly what the current context is.  LINQ also has to deal with object models rather than tabular results so the clauses have to be designed accordingly.

As for some join syntax to simplify outer joins, I agree that it would be nice if the language could offer that because the current syntax isn't exactly the most intuitive.  There are proposals to explode that:  #361.

**Comment by ricardogaldino** [comment]
I think I expressed myself, I'm sorry!
But what I meant is that if it is possible to do it in SQL Server or Oracle, regardless of versions or distributions and without losing performance or intellisense, it could also be done in LINQ C # based on SQL-ANSI syntax.

**Comment by juniorgasparotto** [comment]
I would very much like if it were possible to write LINQ queries with the same SQL nature.

But I would be very happy if the "left join" was created. ;)

**Comment by bondsbw** [comment]
I would prefer the opposite.  All SQL databases should accept LINQ syntax.

**Comment by ricardogaldino** [comment]
The reason for my preference for SQL syntax is this:

SQL, or Structured Query Language, is the **default** declarative search language for relational database.
SQL was originally developed in the early 1970s and became a **standard** of the American National Standards Institute (**ANSI**) in 1986, and of the International Organization for Standardization (**ISO**) in 1987. Since then, the standard has been revised to include a larger set of features.

Is used by the best SGBs including SQL Server, Oracle, PostgreSQL and DB2.
