### ISSUE TITLE
Access Tuple Items By Index:

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1699]
I suggest C# allows us to access each item in ValueTuple by its index. Ex:
```
var x = ("test", 1, new[]{1, 2});
var y = x[0];
var z = x[2];
```

C# can infer y to be string, and z to be int[], because it will simply convert the above code to:
```
var y = x.Item1;
var z = x.Item3;
```

This is better than casting x to ITuple, and use its indexer, because it returns an object value!

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

This idea was already argued during the design of tuples and dismissed by the team.  

You can do this through the `ITuple` interface already.  There's no way for the C# compiler to index into the tuple while knowing the type of the element unless you're using literals/constants for the indexer.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
ITuple's indexer is readonly (why?) 
C# can use reflection to access the filed with name ```"Item"+ index + 1``` to get or set the value of [index]
I look at ValueTuple as a collection with element of different types (without boxing all elemnts in objects). So, I think of ValueTuple as a solution to many of my problems or to write geneic short code and so on.
Thanks anyway.

**Comment by HaloFour** [comment]
@MohammadHamdyGhanem 

If the indexer of `ITuple` was writable it still wouldn't enable the situation you want.  The reason is because `ValueTuple` is a struct and structs copy by value.  In order to cast the struct to an interface requires boxing, which causes a copy onto the heap.  Mutation through a property on the interface would modify the copy on the heap, but the original copy would remain unchanged.

If C# can use reflection to access those members, so could you.  It's not a terribly good idea, though.  It's painfully slow and not remotely type safe.

**Comment by Johnrobmiller** [comment]
I do wonder whether it is possible for the C# compiler and the IDE's type checker know the type of the tuple item. But I'm guessing it would require quite a lot of complicated "code gymnastics" to figure it out.
