### ISSUE TITLE
Allow implicitly-typed variables to have multiple declarators

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1715]
Allow Implicitly-typed variables to have multiple declarators
In VB.NET I can declare different types with one statement:
```Dim x As Integer = 2, name As String = "Adam"```
This is not allowed in C#:
```int x = 2, string name = "Adam";```
Tht was not a problem because I need only to use a ; :
```int x = 2; string name = "Adam";```

But, there is a side effect. In VB.NET, I can use type inference with different values in one statement:
```Dim x = 2, s1 = "a"```
But not in C#:
```var x = 2, name = "Adam";```
C# says:
> Implicitly-typed variables cannot have multiple declarators.

I think this should be fixed.

**Comment by CyrusNajmabadi** [comment]
This is by design.  The LDM has discussed this many times and there is too much confusion here when people experience this.  For example, some people think that "var" should mean "object" here since it's the common base class of ints and strings.  Some people think that 'var' should be something like IComparable, as this is a common interface of both.  Some people thing that each variable should have a different type, and 'var' has no type itself.

This is especially confusing if you have:

```c#
var x = 2, y = 3.0;
```

What are these?  Should 'x' and 'y' both be doubles?  should 'x' be an int? and y a double?   When actually asking people, there tends to be opinions all over the map.  In LDM meetings people ended up flip-flopping themselves over and over how they wanted this to work.

**Comment by HaloFour** [comment]
```cs
var (x, name) = (2, "adam");
```

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Why complicate simple things? In VB.NET:
```Dim x = 2, y = 3.0```
x is Integer and y is Douple.
Do the same in C#.

**Comment by MohammadHamdyGhanem** [comment]
@HaloFour 
Nice workarround, but I think using tuples and deconstruction  is an unnecessary overhead.

**Comment by CyrusNajmabadi** [comment]
> Nice workarround, but I think using tuples and deconstruction is an unnecessary overhead.

There is no overhead.  The compiler generates this:

```il
        IL_0000: nop
        IL_0001: ldc.i4.2
        IL_0002: stloc.0
        IL_0003: ldstr "adam"
        IL_0008: stloc.1
        IL_0009: ret
```

**Comment by CyrusNajmabadi** [comment]
> Why complicate simple things?

I already gave you the reason.  As we discovered, there is wild disagreement on people as to what they think this should mean.  We don't want to release a feature that will cause lots of confusion here.  VB and C# are different here.  VB has 'dim' (which has never been intuited by people to be 'the type of the variable').  C# has 'var' (which is often thought of by people as 'a substitute for typing a *type* in that location).

This intuition breaks badly for users when 'var' now no longer has that meaning.

Since the gain is so small, and the confusion/disagreement is so large, it's not a good idea.

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
Ok. Then I will use @HaloFour suggestion with simple data types. It will be confusing if used with more complex data such as lists with intila values and so.
It is a simple matter of coursebut it will waste some time when converting some VB code to C# manually.
Thanks

**Comment by CyrusNajmabadi** [comment]
> It is a simple matter of coursebut it will waste some time when converting some VB code to C# manually.

You could write a converter that uses roslyn to just convert hte code over.  It can use the appropriate constructs in C# here.

**Comment by AustinBryan** [comment]
> I think this should be fixed.

But it's not broken. 

> In VB.NET:

Really sick of the "in C++ we could do this," or "in VB.NET this was allowed..." Congrats? This is C#, not C++, not VB, etc. 

> but I think using tuples and deconstruction is an unnecessary overhead.

*think*? Instead of thinking and then complaining about overhead, why not actually test it to see if it makes that much of a difference before talking about what you don't know about.

> it will waste some time 

How much time will it *really* take to it enter again and type `var` or wrap both sides around in parans?
