### ISSUE TITLE
Discussion: narrow the scope of declaration expressions from the point of their declaration

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#1741]
This is the case for *all* variables in C++, which may be confusing, but with declaration expressions in C#, it could be actually useful.
```cs
void M()
{
    if (...)
    {
        if (TryGetFoo(out Foo foo)) ...
    }

   // ...

   if (TryGetFoo(out Foo foo)) ... // ERROR: what on earth, oh right
}
```
```cs
void M()
{
    void LocalFunction(...)
    {
        if (e is Foo foo) ...
    }

    // ...

    if (e is Foo foo) ... // ERROR: not this again
}
```

**Comment by theunrepentantgeek** [comment]
You've pointed out the problem - but what do you suggest the scope should be instead?

The existing scope rules where very carefully thought through, with extensive debate, so they're unlikely to change.

Also, keep in mind that this would be a breaking change to existing code - if you reduce the visibility of a variable to a smaller scope, you'll definitely break someone. Breaking changes have to surpass *very* high bar - offer substantial benefits - to even be considered.

**Comment by alrz** [comment]
Note that the scope of the *second* variable is leaking out to blocks before its declaration - where any kind of usage is already an error, so this would not be a breaking change.

**Comment by Joe4evr** [comment]
As pointed out, the scoping was extensively debated and this was the ultimate decision, primarily to enable a *negated* check to still put the variable in scope:
```cs
void M()
{
    if (!TryGetFoo(out Foo foo))
        return;

    //'foo' is in scope and definitely assigned here
}
```

**Comment by jnm2** [comment]
^ Which I do, prolifically

**Comment by SilentSin** [comment]
It seems to me that the proposed solution is that this:
```
void M()
{
    if (...)
    {
        Foo foo;// I'm actually getting the error here, not on the second one.
    }

   Foo foo;
} 
```
Should compile as:
```
void M()
{
    if (...)
    {
        Foo foo;
    }

   // Nothing here, just curlies for scoping.
   {
      Foo foo;
   }
} 
```
That wouldn't break any existing code because the old version wouldn't have compiled.

**Comment by AustinBryan** [comment]
To me, the obvious solution is this:

```csharp
void M()
{
    Foo foo;

    if (...)
    {
        if (TryGetFoo(out foo)) ...
    }

   // ...

   if (TryGetFoo(out foo)) { ... }
}
```
The only downside is that you don't get to use a new feature i'm sure we're all very exicted to use, but it's much better than changing the scoping of variables, possibly breaking everyone's code.

**Comment by SilentSin** [comment]
No existing code would break because the suggestion only applies to code that isn't currently allowed to compile.

Similar to how you can have a local variable with the same name as a field, this would allow you to have a local variable in an inner scope with the same name as one in its enclosing scope. The only difference is that the inner scope wouldn't be able to access the variable in the enclosing scope like you can for fields with this.fieldName. But it wouldn't actually change the scope of anything, it just hides the outer variable while the inner one is in scope.

**Comment by SilentSin** [comment]
@HaloFour 

While that seems logical, why doesn't it apply to other forms of shadowing? I've seen plenty of bugs caused by having a parameter or local variable with the same name as a field, and also confusion caused by having a property with the same name as a class you're trying to access a static member from. Is local shadowing really so much worse that it should go from "perfectly legal, no warning" straight to "not allowed at all"?

**Comment by HaloFour** [comment]
@SilentSin 

> why doesn't it apply to other forms of shadowing?

Because in those other forms there is explicit syntax to disambiguate.

Sure, bug vectors still exist in the language.  It's impossible to eliminate them entirely, and even if the team might look at some situations as possibly having been preventable it's not like they can do anything about them now.  I don't think that the fact that the language isn't perfect is a good reason to reintroduce more known imperfection.

**Comment by alrz** [comment]
Agreeing to all the points. Just had this bug me for a few times, thought I'd share it. Thanks.
