### ISSUE TITLE
LinQ and non-generic collections

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1743]
This LinQ will npt compile in C#:
```var result2 = from c in this.Controls select c;```
It says:
> Could not find an implementation of the query pattern for source type 'Control.ControlCollection'.  'Select' not found.  Consider explicitly specifying the type of the range variable 'var1'.

it is OK in VB:
```Dim result2 = From c  In Me.Controls Select c```

Why  can't C# infer c to be Object like VB does?  Of course it will be better to infer it as Control. We discussed this before https://github.com/dotnet/csharplang/issues/1492 and seems there is no easy solution.
This will work in C#:
```var result2 = from Control c in this.Controls select c;```

**Comment by huoyaoyuan** [comment]
Do you use `Option Strict On` in your VB project? It will make behavior closer to C#.
By design, you should use `.Cast<T>()` and `.OfType<T>()` to use LINQ on non-generic collections.

**Comment by CyrusNajmabadi** [comment]
> Why can't C# infer c to be Object like VB does?

Because ControlCollection doesn't expose the linq pattern.  Neither does IEnumerable.  You are welcome to create a library that exposes hte linq pattern on top of IEnumerable.  The language itself is not responsible for this.

Note that C# has no knowledg e of ```IEnumerable<T>```, it's simply that the BCL exposes the linq pattern on top of tihs.

**Comment by MohammadHamdyGhanem** [comment]
@huoyaoyuan 
Option Strict On doesn't cahnge how VB treats:
```Dim result2 = From c  In Me.Controls Select c```
It is still OK. But this will not be OK:
```Dim result2 = From c As Control In Me.Controls Select c```

**Comment by MohammadHamdyGhanem** [comment]
@CyrusNajmabadi 
How does VB.NET make this work:
```Dim result2 = From c In Me.Controls Select c```

**Comment by theunrepentantgeek** [comment]
The more important question is **why** does VB.NET make that work?

Automagically inferring `IEnumerable<object>` is next to useless, because **object** is _almost certainly_ not going to be useful to the developer. With **object**, you can use `Equals()`, `GetHashCode()` and `ToString()` and that's about it.

This is a case where the developer knows more than the compiler - adding a `.Cast<T>()` or a `.OfType<T>()` is an easy way for the developer to express that intent, with no possibility of the compiler making an incorrect magical guess. The bonus is that following code gets to deal with the exact type and isn't stuck with the extremely limited API of **object**.

There are a **lot** of examples of languages introducing automatic type inference and coercion. Such features almost universally end up causing far more pain and confusion than they solve. Check out the history of `===` in JavaScript, of Truthy and Falsy in Python, and of more things in PHP than I care to mention.

**Comment by svick** [comment]
In my opinion, the right solution here is to change `ControlCollection` so that it implements `IEnumerable<Control>`. The language and the standard library should not spend effort to make it easier to work with libraries that refuse to implement an interface that's more than a decade old. It's the library that should change.

**Comment by CyrusNajmabadi** [comment]
> How does VB.NET make this work:
> ```Dim result2 = From c In Me.Controls Select c```

IMO, poorly.

**Comment by MohammadHamdyGhanem** [comment]
@theunrepentantgeek 
I agree, but I think C# should infer the nob-generic collection type to be object as VB.NET does, and both langs should give a warning not an error about this.

**Comment by CyrusNajmabadi** [comment]
> but I think C# should infer the nob-generic collection type to be object as VB.NET does,

You can make it do that.  Just provide the appropriate extension methods.  Once you let the compiler know how this types supports the linq pattern the compiler will pick this up for you.

> I agree, but MS Teams don't! 

Then you have your answer.  The teams don't think this is necessary for them to address.  Give that you can solve this with just a few characters, i'm not surprised. :-/

**Comment by CyrusNajmabadi** [comment]
> Maybe type inference is not a big deal, but there are more important issues that can be reviewed to make CoreFx API make use of new syntaxes, like what I mentioned here dotnet/corefx#28285

CoreFx already mentioned what you should do there:

> @MohammadHamdyGhanem, it would be awesome if you could get us started by taking on some of these enhancements and submit a PR.

You did not take them up on their offer.

**Comment by Happypig375** [comment]
@CyrusNajmabadi
What about the last comment from @tarekgh?
>We cannot change the old APIs though. 

I interpret this as fully declining the issue, overriding the previous comment and expect a decline to merge the PR even if it is created. What would be the point of even creating the PR if the whole idea is declined?

**Comment by CyrusNajmabadi** [comment]
>  What would be the point of even creating the PR if the whole idea is declined?

It could help foster discussion on what a suitable approach can be.  

--

Note: the entire conversation is a bit weird to me.  There are *existing* *supported* *trivial* ways to solve this problem.  So it seems weird to me that all of those are avoided.
