### ISSUE TITLE
Champion "Permit IEnumerable<T> as the type of a params parameter"

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#179]
- [ ] Proposal added
- [ ] Discussed in LDM
- [ ] Decision in LDM
- [ ] Finalized (done, rejected, inactive)
- [ ] Spec'ed

See also
- github.com/dotnet/roslyn/issues/36
- https://github.com/dotnet/csharplang/issues/178

### Design meetings

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-08-31.md#params-ienumerable
https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-09-26.md#params-improvements

**Comment by Richiban** [comment]
I would assume that params was originally introduced so that the programmer didn't have the duality of having to write two methods just so that a piece of functionality could work with either a T or a collection of T, such as below:

    public void MyMethod(string item) 
    {
        MyMethod(new string[] {item});
    }

    public void MyMethod(string[] items)
    {
        // ... Do something with items
    }

While this was great, unfortunately as soon as IEnumerable<T> was introduced and it became the de facto standard base collection type we're back to the duality again:

    public void MyMethod(params string[] item) => MyMethod(items);

    public void MyMethod(IEnumerable<string> items)
    {
        // ... Do something with items
    }

Actually, since we're on the subject, I'd like to propose that not only is `params IEnumerable<T>` allowed, but so should `params IReadOnlyList<T>`, `params IList<T>` etc. These types are all allowed because they are all implemented by `T[]`. So, more formally:

`params M<U> identifier` is allowed if `U[] : M<U>`.

This works because at the callsite of method

    public void MyMethod(params T<U> items)

the call:

    MyMethod(item1, item2, item3)

gets converted to:

    MyMethod(new[] {item1, item2, item3})

So the `params` keyword should be allowed on any type that is assignable from an array.

This is desirable because, as an API designer, it can sometimes feel dangerous to accept `IEnumerable<T>` as a parameter when you expect an in-memory collection because you don't know that the given argument is actually a collection at runtime. It could be lazily-loaded like a database query, or it might even be infinite, in which case you cannot safely call `Count()` or even `foreach`.

**Comment by aluanhaddad** [comment]
@Richiban I'm not sure I agree. There are many extension methods on `IEnumerable<T>` that will fail if it is an infinite sequence but work fine if it is implemented by an arbitrary but ultimately terminal enumerator. In practice I do not think that this has been a problem.

Also, this introduces a lot of complexity in terms of the number of possible signatures and potentially unexpected type requirements and allocations. What if I want `params IImmutableSet<T>`? While it would be weird if a method implicitly constructed a one from a varargs call, it is also vaguely justifiable since the callee determines the semantics.

I think `params IEnumerable<T>` is really all that is needed and provides enough value without support for additional types.

**Comment by jnm2** [comment]
I have so many methods that take `IReadOnlyCollection<>` or `IReadOnlyList<>`. Just support for those two would be phenomenal for me.

**Comment by CyrusNajmabadi** [comment]
It would require teh compiler having some baked in knowledge, but i would also love "params ImmutableArray<T> array" support.  

Perhaps you could have "params SomeType array" and the compiler would look for "SomeType.Create(...)"  as what it would call in that case.

**Comment by yaakov-h** [comment]
I don't see any issue with `params IList<>` or anything else that `Array` already implements.

`IReadOnlyList<>` would require the compiler knowing about `AsReadOnly()` etc.

`<AConcreteType>.Create(...)` would work for concrete types, but not for additional interfaces - unless you told the compiler about a specific concrete type, e.g. `void Foo([ParameterList(typeof(SomeConcreteType))] params ISomeInterface bar)` - but that seems ripe for abuse.

**Comment by aluanhaddad** [comment]
@CyrusNajmabadi that certainly would be useful but if infrastructure is going to be put in place for using such patterns to instantiate `params` collections, would it make sense to make this part of a larger feature supporting collection literals?

There have been many requests for a collection literals as well as for JSON literals (collection linerals) so if such a pattern is codified it would be great it were generalized to enable these scenarios as well.

Personally I think collection literals would be great, but only if you could customize the target type to be, as you say, `ImmutableArray`.

I don't think JSON literals make any sense at all but people ask for them.

**Comment by Richiban** [comment]
I think that talk of the compiler automatically inserting calls to extension methods is taking it a bit far...

What is very easy to understand and (I'm assuming) easy to implement would be that anywhere you could previously write this:

```csharp
public void MyMethod<U>(M<U> items)
{
	// Do stuff...
}

public void Callee()
{
	MyMethod(new [] { 1, 2, 3 });
}
```

You can now write this:

```csharp
public void MyMethod<U>(params M<U> items)
{
	// Do stuff...
}

public void Callee()
{
	MyMethod(1, 2, 3);
}
```

and there's no further magic than that.

**Comment by alrz** [comment]
@Richiban 

>So the params keyword should be allowed on any type that is assignable from an array.

I think accepting any type that is assignable from `T[]` is not enough because we can't always determine `T`. Perhaps we should check assignability to the non-generic `IEnumerable`.

**Comment by alrz** [comment]
if that's desirable, it's pretty easy to implement, I should see if I can handle stackalloc optimization for Span (https://github.com/dotnet/csharplang/issues/535).

**Comment by alrz** [comment]
there is a special case in which does not clearly translate to `IEnumerable`, 
```cs
void M(params string[] args) {}
M(null); // OK args = new string[] { null }

void M(params IEnumerable args) {}
M(null); // ERROR?
```
Permitting any type that implements `IEnumerable<T>` doesn't seem to address the issue either. what if a type implements multiple `IEnumerabe<T>` (directly or indirectly) with a different `T`?

Perhaps we should only allow `IEnumerable<T>` directly.

**Comment by gafter** [comment]
> ``` c#
> void M(params string[] args) {}
> M(null); // OK args = new string[] { null }
> ```

That is not how it works. A method will be called in unexpanded (normal) form preferentially to being called in expanded form. `M(null)` will pass a null array.

**Comment by alrz** [comment]
Yeah, I missed that null is a special case, but my point was that we can't use an inferred array creation `new[]` for a params parameter of type `IEnumerable` since `T` in `params T[]` does contribute to the method resolution. And if we rely on assignability to `IEnumerable<T>` (as @Richiban suggests) there can be issues on the call-site (which doesn't exist for `T[]` - because you can't inherit from an array). Simply allowing `params IEnumerable<T>` seems to the safest option here.

**Comment by rossdempster** [comment]
Given the variety of solutions now proposed, and especially considering the latest #1366 issue, would it make sense for the compiler to _support any type that supports collection initialization?_

This would mean we could put `params` in front of any type.
`public void SomeMethodCall(params CustomType p) { ... }`

The callsite is where the magic happens. Anywhere it would be possible to type:
`SomeMethodCall(new CustomType {p1, p2, p3})`

It would also be possible to type:
`SomeMethodCall(p1, p2, p3)`

Or is that crazy?

**EDIT: Actually, it is crazy, and doesn't really help with all the interfaces. Ignore me!**

**Comment by airbreather** [comment]
> It would require teh compiler having some baked in knowledge, but i would also love "params ImmutableArray array" support.

I like that too, though dotnet/corefx#22625 would give most of the benefits with `params ReadOnlySpan<T>`.

Speaking of which, I'm in favor of `params ReadOnlySpan<T>`, and even having just that one instead of `params Span<T>` if it has to be just one or the other.  It doesn't feel like the ability to write back to the original array is an important part of the `params` story, and the fact that you can do that today is probably just an unfortunate consequence of the tools that were available during the original .NET Framework design.

I'd be perfectly satisfied if all I had were:
- `params T[]` so existing things don't break
- `params IEnumerable<T>` for most things
- `params ReadOnlySpan<T>` for new things where I worry about performance at all

Given those, even if I found myself in a situation where I could **really, really** benefit from knowing the count in advance if available without forcing `ReadOnlySpan<T>` (and this feels like a stretch), this looks OK enough:
```csharp
void Do(params IEnumerable<int> args)
{
    int count;
    switch (args)
    {
        case null:
            throw new ArgumentNullException(nameof(args));

        case ICollection<int> coll1:
            count = coll1.Count;
            break;

        case IReadOnlyCollection<int> coll2:
            count = coll2.Count;
            break;

        default:
            List<int> argsList = args.ToList();
            args = argsList;
            count = argsList.Count;
            break;
    }

    // count is now available to us
    // same idea works for IList<T> / IReadOnlyList<T> if the indexer matters too
}
```

**Comment by TonyValenti** [comment]
I can't tell you how much I would love this feature.

**Comment by alrz** [comment]
I'm working on a prototype for this (https://github.com/dotnet/roslyn/pull/24080). here's my open questions for LDM to confirm:

- do we want to support all generic array interfaces? (supporting all these types is not nontrivial)
- do we want to support `params Span<T>` and `params ReadOnlySpan<T>`? (https://github.com/dotnet/csharplang/issues/535) (we can reuse stackalloc initializer lowering in codegen)
  - this probably need dotnet/roslyn#22046 to be implemented first.
- do we want to frobbid conflicting `params` overloads with identical element types? (otherwise no invocation in the expanded form would be applicable)

**Comment by CyrusNajmabadi** [comment]
> (supporting all these types is not nontrivial). 

Do you mean that it's trivial?  Or that it's nontrivial?  The 'not' in there is throwing me off.

**Comment by CyrusNajmabadi** [comment]
> do we want to support params Span<T> and params ReadOnlySpan<T>

I think this would be fantastic.  One of hte primary concerns around params in teh first place (and thus extending it to more situations) is that it incurs a array allocation.  If we could have nice synchronous variadic APIs that didn't require allocations, i think that would be fantastic for the ecosystem.

**Comment by alrz** [comment]
>Do you mean that it's trivial? Or that it's nontrivial?

I meant the former; just not wanted to stress on "trivial". I've implemented that part by relaxing some checks in the compiler (and because an implicit conversion exists, there was no need to adjust lowering), but since it's not thoroughly tested I wasn't confident that's all it would take to support it.

**Comment by CyrusNajmabadi** [comment]
>  I meant the former; just not wanted to stress on "trivial".

In that case, my preference would be to support them all.  It's reasonable for me to say ```params IReadOnlyList<int>``` or ```params IList<int>``` and whatnot.  And, in most cases, where one of my APIs is already taking one of those types, i would like to be able to just add "params" to it and enable these scenarios.

The one thing that's a pity is that i would really love ```params ImmutableArray<T>```.  But that would def take more interesting work to figure out how to supply that sort of thing.

**Comment by alrz** [comment]
>`params ImmutableArray<T>`

we *could* lower to collection initializers for params on arbitrary types, but currently, there's no mechanism that enables it for a type like `ImmutableArray<T>`. if/when we extend collection initializers to work with `ImmutableArray<T>` (probably through some convention), we can add params support on top of it.

**Comment by svick** [comment]
@alrz The worst part is that collection initializer on `ImmutableArray<T>` compiles, but doesn't actually work (it throws `NullReferenceException`, since `new ImmutableArray<T>()` a.k.a. `default(ImmutableArray<T>)` is not really a valid value).

**Comment by CyrusNajmabadi** [comment]
> @alrz The worst part is that collection initializer on ImmutableArray<T> compiles, but doesn't actually work (it throws NullReferenceException, since new ImmutableArray<T>() a.k.a. default(ImmutableArray<T>) is not really a valid value).

Note: it wouldn't work even if it started with an empty instance.  Collection initializers work by calling .Add for each element added.  But adding to an immutable array does nothing to the original instance.

No matter what, we'd need some sort of new system that recognizes, by some system, the appropriate way to actually initialize things like ImmutableArray.

**Comment by alrz** [comment]
>Collection initializers work by calling .Add for each element added. But adding to an immutable array does nothing to the original instance.

If collection initializers could recognize the return type and call Add methods on that instance we could make this work somehow, but I think that's a breaking change now. (and still it wouldn't work with the current implementation because `new ImmutableArray<T>().Add(e)` throws -- it's not supposed to be used that way.)

>we'd need some sort of new system that recognizes, by some system, the appropriate way to actually initialize things like ImmutableArray.

Actually, `ImmutableArray<T>` is carefully designed to not expose the underlying array and therefore has some specific properties that makes it really hard to define a general convention for its creation. IMO it's something that we should have in the language in the first place, (e.g. https://github.com/dotnet/csharplang/issues/955 or more generally #421)

That being said, I think it wouldn't worth it to support arbitrary types for params parameters or even worse, to make ImmutableArray a well-known type in the compiler.

**Comment by Richiban** [comment]
@alrz The discussion you're having now sounds like it would be eminently relevant to my recent proposal for target-typed collection literals https://github.com/dotnet/csharplang/issues/1399. Namely around how the compiler might figure out how to construct a collection it doesn't recognise explicitly.

Perhaps the features even have enough overlap to be merged?

**Comment by bartdesmet** [comment]
I formulated an alternative proposal for `params` improvement over [here](https://github.com/bartdesmet/csharplang/blob/ExpressionTypes/proposals/params-builders.md), based on observations related to revamping expression tree APIs, which suffer from defensive copies (for sake of guaranteeing immutability after construction) of `params Expression[]` arrays passed to factory methods.

**Comment by alrz** [comment]
@bartdesmet 

>which suffer from defensive copies (for sake of guaranteeing immutability after construction)

Don't you think this is better to be addressed via a "readonly arrays" feature, something like https://github.com/dotnet/csharplang/issues/955?
also see https://github.com/dotnet/csharplang/issues/955#issuecomment-333922170 regarding validation issues.

**Comment by zippec** [comment]
@bartdesmet 
> A good example is the System.Linq.Expressions API where factory methods accept a params Expression[] but need to create a defensive copy of the array to ensure immutability (using an internal TrueReadOnlyCollection<T> type). This causes excessive allocations, even if the params array was constructed by the compiler, which ensures only the callee can observe the reference to the array, so external mutation by the caller is not possible.

To avoid defensive copy to ensure immutability, you would need to have sealed-class collection type in the method signature which I don't believe is a good idea for public API as it discloses internal workings of said method.

**Comment by bjorn-ali-goransson** [comment]
I, for one, see no urgency in opening flood gates (collection initializers and whatelse) just to have only IEnumerable<> supported. It's the overwhelmingly most useful and broadly applicable situation, imo.

**Comment by IngmarBitter** [comment]
I find that **params** has constraints that are not useful in practice, namely that it has to be at the end of the parameter list, which eliminates the possibility of default parameters. The main inconvenience I find often is a single item vs a collection that in either case should be handled the same.

```
public void Foo(int number, bool flag=true) {
   Bar(new int[] {number}, flag);
}

public void Bar(IEnumerable<int> numberSet, bool flag=true) {
    foreach (int num in numberSet)
       // ...
}
```

So what I'd like is a prefix that allows auto wrapping a single item into an IEnumerable such that I do not need that first wrapper method Foo. The name for that prefix could be **params** since it is similar in behavior, but better should be **multi** since it is a short word that indicates the idea that the following parameter has multiple API signatures. The above code would become:
```
public void Bar(multi IEnumerable<int> numberSet, bool flag=true) {
    foreach (int num in numberSet)
       // ...
}
```

Since there is no restriction to have the **multi** parameter at the end, I could even use more than one **multi** parameter:

```
public void Bar(multi IEnumerable<int> numberSet, multi IEnumerable<string> labelSet, bool flag=true) {
    foreach (int num in numberSet)
       // ...
}
```
And of course it would be great if the **multi** keyword could be prefixed to any type of container/set to auto convert a single item into a container/set with having that one item. So besides IEnumerable also for arrays, lists, etc.

**Comment by DanFTRX** [comment]
@IngmarBitter What would this do?

```CSharp
public void Method()
{
    Method1(true, false); // Does boolSet have 2 elements or is flag false?
    Method1(false); // Does boolSet have an element or is flag false?
}

public void Method1(multi IEnumerable<bool> boolSet, bool flag=true) {

}
```

**Comment by IngmarBitter** [comment]
@DanFTRX your example would be:
```
public void Foo() {
    Bar(true, false); // same as {true}, false
    Bar(false); // same as {false}, true
}
public void Bar(multi IEnumerable<bool> boolSet, bool flag=true) {
}
```
I suppose I was not clear enough before that I do not find useful the **params** feature of collecting multiple comma separated parameters into a set. **multi** should not do that. A **multi** parameter is always a single parameter. The only flexibility it adds is that a single element is converted into a set with that element.
The case that someone wants to explicitly declare the set of multiple elements at the point of method call is rare. I that case one can do:

`Bar(new bool[] {true, true, false}, false); `

PS: how did you add the syntax coloring?

**Comment by DanFTRX** [comment]
@IngmarBitter Oh I see, interesting.  As for coloring, you surround the code block with "\```CSharp" and "```"

**Comment by StefanBertels** [comment]
Maybe there should be no special handling for one argument. We could argue that when passing one argument this should be taken as `numberSet` in your example (I think this is the current behavior when passing an array to `params ...`).

**Comment by IngmarBitter** [comment]
@StefanBertels "no special handling" but still one argument to "'be taken as numberSet'". Do you mean auto convert from single instance to set without the addition of a new keyword such as **multi**? Could that not be considered breaking type safety? What if you really want to treat a singe item different from a set? The compiler then would find two competing equally valid implementations?
Seems to me that asking the compiler to do non-standard type conversions should not happen silently under the hood, but needs the developer to explicitly communicate that intent. **multi** is the shortest option to do so.

**Comment by HaloFour** [comment]
@IngmarBitter 

I'd suggest opening a separate issue for this `multi` idea as it is not related to the championed proposal of allowing `params` parameters to be `IEnumerable<T>`.

**Comment by TonyValenti** [comment]
Perhaps instead of using ````params IEnumerable<T>```` we should think about explicitly specifying the type that should be constructed.  For example:

````params Hashset<T>```` or ````params List<T>````.  In situations like that, the compiler would basically follow the rules for collection initializers (ie. calling any acceptable ````Add``` member/extension method).

**Comment by IngmarBitter** [comment]
@HaloFour OK. Forget all my comments here. I instead created the new issue #3133.

**Comment by StefanBertels** [comment]
@TonyValenti: nice idea. Ideally this would work with immutable data structures, too. Maybe search for some conversion operator?

**Comment by canton7** [comment]
@TonyValenti The downside with that is that if the user already has a variable of type `IEnumerable<T>`, they wouldn't be able to pass it. That is one of the main pain points which this proposal is trying to solve.

**Comment by crfrolik** [comment]
This should have been done years ago. Please make it happen.

**Comment by CleanCodeX** [comment]
I also want to say, this should be implemented as soon as possible. It is very disappointing that you can't pass a IEnumerable/IList7IReadOnlyList variable as a params argument as it demands to be an array and therefore in most cases a unnecessary copy needs to be created.

**Comment by john-h-k** [comment]
Personally, I like the idea of `params T foo` where there is an implicit conversion from `T[]` -> `T` to be fine. That way, you support `Span<T>, ROS<T>, IEnumerable<T>, IReadOnlyList<T>` for free, as well as custom types and non generic types. You can then also get stack-based span params at a later point

**Comment by yaakov-h** [comment]
It gets you Span and ReadOnlySpan, but with allocations. I’d rather params Span and params ReadOnlySpan were allocation-free...

**Comment by AroglDarthu** [comment]
@MadsTorgersen Would be nice to get this in C#10, but I'm guessing the `X` in `X.0` does not stand for `10` in this case?

**Comment by BreyerW** [comment]
@AroglDarthu  no the X in this case stands for ANY major version eg.  It can equally likely happen in c# 20 or 11. (Btw c# 10 is practically done by now they ship GA in october if i remember correctly)

**Comment by AroglDarthu** [comment]
@BreyerW Thanks 😊
Just trying to get some traction on this feature. If I understood correctly, it got specified at the time C#6 was still in development.

It's labeled "Smallish Feature" (don't know if that means "small amount of work" or if it's considered "no huge benefit"). Perhaps it can be considered for the `11.0` milestone.

**Comment by TonyValenti** [comment]
I would like to be able to use any collection type as the type of Params.  Ie. params HashSet<T>.

**Comment by Shadowblitz16** [comment]
This would help make math libraries easier especially with INumber
```cs
public static class Math
{
    public static float   Mean(params float  [] a)
    {
        var result = 0f;
        var count = 0;
        foreach (var target in a)
        {
            result += target;
            count++;
        }

        return result / count;
    }
    public static Vector2 Mean(params Vector2[] a)
    {
        var result = Vector2.Zero;
        var count = 0;
        foreach (var target in a)
        {
            result += target;
            count++;
        }

        return result / count;
    }
    public static Vector2 Mean(params Node2D [] a)
    {
        var result = Vector2.Zero;
        var count = 0;
        foreach (var target in a)
        {
            if (target is not { } target2D) continue;
            
            result += target2D.Position;
            count++;
        }

        return result / count;
    }
```
to...
```cs
public static class Math
{
    public static T Mean<T>(params IEnumerable<T> a) where T : INumber
    {
        var result = default(T);
        var count = 0;
        foreach (var target in a)
        {
            result += target;
            count++;
        }

        return result / count;
    }
```

**Comment by TahirAhmadov** [comment]
I came up with a quick prototype:
<details><summary>Definitions</summary>
<p>

```cs
public ref struct Params<T>
{
  public ref struct Enumerator
  {
    public Enumerator(Params<T> owner)
    {
      if (owner._enumerable != null)
      {
        this._enumerator = owner._enumerable.GetEnumerator();
        this._span = null;
      }
      else
      {
        this._span = owner._span!.Value;
        this._enumerator = null;
      }
    }

    public T Current
    {
      get
      {
        if (this._enumerator != null) return this._enumerator.Current;
        return this._span.Span[this._index];
      }
    }

    public bool MoveNext()
    {
      if (this._enumerator != null) return this._enumerator.MoveNext();
      return ++this._index < this._span.Length;
    }

    readonly ReadOnlyMemory<T> _span;
    readonly IEnumerator<T>? _enumerator;
    int _index = -1;
  }

  public static implicit operator Params<T>(T[] array) => new(new ReadOnlyMemory<T>(array));
  public static implicit operator Params<T>(List<T> list) => new(list);

  public Params(IEnumerable<T> enumerable)
  {
    this._enumerable = enumerable;
    this._span = null;
  }
  public Params(ReadOnlyMemory<T> span)
  {
    this._span = span;
    this._enumerable = null;
  }

  public Enumerator GetEnumerator()
  {
    return new Enumerator(this);
  }

  readonly IEnumerable<T>? _enumerable;
  readonly ReadOnlyMemory<T>? _span;
}
public ref struct ParamsList<T>
{
  public ref struct Enumerator
  {
    public Enumerator(ParamsList<T> owner)
    {
      if (owner._list != null)
      {
        this._enumerator = owner._list.GetEnumerator();
        this._span = null;
      }
      else
      {
        this._span = owner._span!.Value;
        this._enumerator = null;
      }
    }

    public T Current
    {
      get
      {
        if (this._enumerator != null) return this._enumerator.Current;
        return this._span.Span[this._index];
      }
    }

    public bool MoveNext()
    {
      if (this._enumerator != null) return this._enumerator.MoveNext();
      return ++this._index < this._span.Length;
    }

    readonly ReadOnlyMemory<T> _span;
    readonly IEnumerator<T>? _enumerator;
    int _index = -1;
  }

  public static implicit operator ParamsList<T>(T[] array) => new(new ReadOnlyMemory<T>(array));
  public static implicit operator ParamsList<T>(List<T> list) => new(list);

  public ParamsList(IList<T> list)
  {
    this._list = list;
    this._span = null;
  }
  public ParamsList(ReadOnlyMemory<T> span)
  {
    this._span = span;
    this._list = null;
  }

  public int Count => this._list?.Count ?? this._span!.Value.Length;
  public T this[int index] => this._list != null ? this._list[index] : this._span!.Value.Span[index];

  public Enumerator GetEnumerator()
  {
    return new Enumerator(this);
  }

  readonly IList<T>? _list;
  readonly ReadOnlyMemory<T>? _span;
}

```

</p>
</details>

Usage:
```cs
static void Foo(Params<int> list)
{
  Console.WriteLine("Foo");
  foreach (int x in list)
  {
    Console.WriteLine(x);
  }
}
static void Bar(ParamsList<int> list)
{
  Console.WriteLine("Bar: " + list.Count);
  Console.WriteLine(list[0]);
  Console.WriteLine(list[1]);
  Console.WriteLine(list[2]);
}

int[] array = new[] { 1, 2, 3, };
var list = new List<int> { 4, 5, 6 };
IEnumerable<int> enumerable = new[] { 7, 8, 9 };
Foo(array);
Foo(list);
Foo(new Params<int>(enumerable));
Bar(array);
Bar(list);
```
Basically, the method's author chooses what the method needs - enumeration only (`Params<T>`), or accessing individual elements (`ParamsList<T>`), as well. 
Then, then the method's caller can pass in any of the types: `IEnumerable<T>` (unless it's `ParamsList<T>` for obvious reasons), `T[]`, `Span<T>`, etc.
Language support is added for `params`, which are done with the to be developed stack operations, but can in the meantime be added to the language with array allocation fallback.
Additional methods can be defined on `Params(List)<T>` types to convert to `IEnumerable<T>` and other collection types, to allow passing it around; these may incur and allocation, if the source was a stack-based `Span<T>`, but it's still a total of 1 allocation, which is no worse than the old `params T[]`.
For interfaces like `IEnumerable<T>`, we can either a) relax the conversion rule for interfaces so that implicit operators can convert from interfaces to non-interface types; or b) create a special trans-piling rule which only allows `IEnumerable<T>`/etc. to `Params<T>` conversion.

**Comment by TonyValenti** [comment]
In light of collection expressions coming up, I wanted to revitalize this thread and suggest that ```params``` be a "hint" that instructs the compiler to use the collection expression rules to construct the desired collection.

ie.
```csharp
public static void Foo(params IEnumerable<int> x);
Foo(1, 2, 3); //same as Foo([1,2, 3])
```

This would play nice with target typing for collection expressions and solve the question of "What is the type of ```params IEnumerable<T>```?"

**Comment by HaloFour** [comment]
> In light of collection expressions coming up, I wanted to revitalize this thread and suggest that `params` be a "hint" that instructs the compiler to use the collection expression rules to construct the desired collection.

My understanding is that with collection literals the need for this proposal has kinda gone away as it's very light syntactically to just wrap the arguments in a collection literal rather than adding `params` as a feature for less performant use cases.

**Comment by CyrusNajmabadi** [comment]
Correct.  We don't see substantive value here in allowing this anymore, as you can always just do `[x, y, z]` instead of `x, y, z`.

We do see substantive value in `params ReadOnlySpan<T>` as that means code does *not* need any modification to just start running faster.

**Comment by MadsTorgersen** [comment]
This proposal is now subsumed by the championed proposal #7700 for Params Collections.
