### ISSUE TITLE
Proposal: Async events

### ISSUE THREAD

**Issue by juunas11** [dotnet/csharplang#1791]
Events are one of those things that require you to use `async void` currently.

What if we could have something like this:

```cs
public class MyClass
{
    public delegate Task MyEventHandler(object sender, EventArgs args);
    public async event MyEventHandler MyEvent;

    public async Task RaiseEvent()
    {
        await MyEvent.InvokeAsync();
    }
}

public class MyListener
{
    private readonly MyClass _myClass;

    public MyListener()
    {
        _myClass = new MyClass();
        _myClass.MyEvent += HandleEventAsync;
    }

    public async Task HandleEventAsync(object sender, EventArgs e)
    {
        await Task.Delay(1000);
    }
}
```

This is just an idea I had, it would remove usage of `async void` in event handlers.
The event delegate could call the listeners using `await Task.WhenAll()`.
Now I may not be aware of a thousand issues this would have so please do point those out.
I also understand this would not be a trivial amount of work :)

**Comment by orthoxerox** [comment]
What will be the benefit of doing that?

**Comment by juunas11** [comment]
Better exception handling would be one thing, as exceptions thrown after an await don't propagate to the caller

**Comment by mcosmin222** [comment]
Also fixes the issue of early returns async void event handlers suffer from.

**Comment by HaloFour** [comment]
It's considered bad form for an event to have a return value.  This is largely because events are multicast and the return value is indeterminate.  Instead of getting some composite `Task` back representing all of the invocations, you'll get a single `Task` from one of the invocations.  The rest would be lost.  That behavior of multicast delegates is something built into the CLR.

It is true that multicast delegates can be unwrapped into an invocation list of delegates via [Delegate.GetInvocationList](https://docs.microsoft.com/en-us/dotnet/api/system.delegate.getinvocationlist?view=netframework-4.7.2).  Theoretically the C# compiler could emit invocation code which unwraps the delegate, invokes each delegate individually, collects each `Task` and then waits on all of them.

I'd suggest that this could be solved via code without requiring language changes.  You can define a common generic delegate which follows the `EventHandler<T>` pattern and then have a helper function which does the same invocation unwrapping mentioned above.  This would give you additional control over the policy of how the handlers would be invoked, cancellation, etc., that a language feature would not likely extend.

```cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

public delegate Task AsyncEventHandler<TEventArgs>(TEventArgs args, CancellationToken cancellationToken) where TEventArgs : EventArgs;

public static class AsyncEventHandlerExtensions {
    public static Task InvokeAsync<TEventArgs>(this AsyncEventHandler<TEventArgs> handler, TEventArgs args, CancellationToken cancellationToken) where TEventArgs : EventArgs {
        var tasks = new List<Task>();
        foreach (AsyncEventHandler<TEventArgs> d in handler.GetInvocationList()) {
            tasks.Add(d(args, cancellationToken));
        }
        return Task.WhenAll(tasks);
    }
}

public class C {
    public event AsyncEventHandler<EventArgs> MyEvent;
    
    protected async Task OnMyEvent(EventArgs args, CancellationToken cancellationToken) {
        await MyEvent.InvokeAsync(args, cancellationToken);
    }
}
```

**Comment by juunas11** [comment]
@HaloFour Thanks for that! That actually does not look half bad.

@jnm2 Ahh so there was previous discussion on this, couldn't find it with a quick search earlier, my bad :/

**Comment by jnm2** [comment]
@juunas11 It's okay, it happens to all of us. GitHub search is not Google.
