### ISSUE TITLE
Proposal: Cascade notation (..)

### ISSUE THREAD

**Issue by listepo-alterpost** [dotnet/csharplang#1825]
Cascades (..) allow you to make a sequence of operations on the same object. In addition to function calls, you can also access fields on that same object. This often saves you the step of creating a temporary variable and allows you to write more fluid code.

Consider the following code:
```
querySelector('#confirm') // Get an object.
  ..text = 'Confirm' // Use its members.
  ..classes.add('important')
  ..onClick.listen((e) => window.alert('Confirmed!'));
```
The first method call, querySelector(), returns a selector object. The code that follows the cascade notation operates on this selector object, ignoring any subsequent values that might be returned.

The previous example is equivalent to:
```
var button = querySelector('#confirm');
button.text = 'Confirm';
button.classes.add('important');
button.onClick.listen((e) => window.alert('Confirmed!'));
```
### Example:

[Dartlang](https://www.dartlang.org/guides/language/language-tour#cascade-notation-)

**Comment by TheUnlocked** [comment]
This is ambiguous:

```csharp
class Foo{
    public int val = 0;

    public Foo(int val){
        this.val = val;
    }

    Foo SquareMe(){
        return new Foo(val * val);
    }
}

Foo f = new Foo(2)..SquareMe()..SquareMe();
```

Is `f.val` supposed to be 2, 4, or 8?

**Comment by CyrusNajmabadi** [comment]
> Cascades (..) allow you to make a sequence of operations on the same object.

There are already fluent patterns that work for C#/.Net code.  Is there a reason you can't use any of the existing ones?

**Comment by AustinBryan** [comment]
Pretty sure this is a duplicate. I think I saw a post with syntax like this:

```csharp
with (button)
{
    Text = "Confirm";
    Classes.Add("important");
    OnClick.Listen((e) => window.alert("Confirmed!");
}
```

Which should have less ambiguity.

And technically, you could do:
```csharp
with (button) { Text = "Confirm"; }
```
Which is the same as:
```csharp
button.Text = "Confirm";
```

**Comment by listepo-alterpost** [comment]
@TheUnlocked will be 2, it's just an alternative for:
```
Foo f = new Foo(2)
f.SquareMe();
f.SquareMe();
```
syntax sugar does not help you write a clear code

**Comment by listepo-alterpost** [comment]
@CyrusNajmabadi Can  you write examples that already exist in the language and solves a similar problem?

**Comment by listepo-alterpost** [comment]
@AustinBryan ```with``` I also like, but I'm still interested in the opinions of others

**Comment by listepo-alterpost** [comment]
@theunrepentantgeek thanks, I think LINQ, NHibernate criteria querying, Fluent Assertions too bulky for simple purpose. I'm talking about simple syntax sugar.

**Comment by listepo-alterpost** [comment]
@CyrusNajmabadi this is not applicable in many cases. Imagine that the method returns void

**Comment by HaloFour** [comment]
While I think that such syntax might make it slightly easier to write fluent-like code over non-fluent APIs, it comes at the expense of being able to quickly read and reason about that code.  Something like `..` would easily be lost.  Worse, it's also an amazingly easy typo-vector, and could quickly change the meaning of that code unintentionally.

**Comment by CyrusNajmabadi** [comment]
Make it nor return void? :)   

Also there's already an existing proposal for allowing Fluent over 'void' methods: https://github.com/dotnet/csharplang/issues/781

**Comment by CyrusNajmabadi** [comment]
precedence of `..` is also not at all clear (nor intuitive given the precedence of `.`).  They have wildly different precedences here.

**Comment by CyrusNajmabadi** [comment]
I actually can't figure out the grammar here.  What do you propose the grammar rules are.  Trying to make something work that allows for the following is super strange:

```..text = 'Confirm'``

Presumably `..` would be something like:   `expr .. expr`?  But what would the allowed expr types be?  You need to ensure in your example that with `'Confirm'..classes.add('important')` that `..classes` was not actually operating on hte `'Confirm'` string...

**Comment by JeroMiya** [comment]
@listepo-alterpost Please re-open. I feel this proposal warrants further discussion and clarification.

@TheUnlocked Your example is not ambiguous. If used as an expression, a chain of `expression .. statement .. statement` evaluates to the value of the first expression after all statements in the `..` chain are evaluated. In your sample `new Foo(2)..SquareMe()..SquareMe()` will return 2, because `SquareMe` has no side effects. The return values of the both `SquareMe()` are ignored. If `SquareMe` mutated its instance (and returned void) instead, then the result would be 16, though the instance would still be that first `new Foo(2)` instance, mutated twice by `SquareMe`.

@HaloFour I disagree that the syntax makes a series of statements harder to read. Based on my experience with this exact syntax in Dart, I feel it greatly improves readability in a number of scenarios by eliminating syntactic clutter and repetitive code. Moreso than the `with` proposal.

@theunrepentantgeek This syntax is not strictly speaking a "Fluent API All The Things" proposal. It's meant to reduce syntactic clutter for an otherwise repetitive and redundant series of statements. For example, it can be used to set a number of properties on an object in one statement without needing to repeat the object name. As you say, a fluent API needs to be designed and return values carefully chosen, which is overkill for a great many use cases this proposal is intended for.

@CyrusNajmabadi Perhaps it would help to clarify the syntax a bit:

- First of all, the left hand side of the first `..` must be a non-void expression. 
- After the first `..` and each subsequent one are statements and not expressions, so their values are ignored. If used as an expression, the value of the whole chain is the value of the FIRST expression in the chain, AFTER all statements in the chain are evaluated.
- This syntax, in many cases, eliminates the need to introduce temporary variables in places where a constructor or initializer syntax is not enough to initialize a value before assigning it to something else.
- If any of the statements in the chain start with `await` in an async function then the value of the chain is `Task<T>` where T is the type of the expression value. If more than one statement starts with `await`, then the task is resolved when all statements are resolved.

One issue with this syntax is with async/await. It doesn't currently support it. Maybe if you allow the 'await' keyword before the first member reference, you can do something like this:

```
// each line starting with .. is a statement, evaluated in the order they appear.
Foo x = new Foo()
    .. InitializeSync()
    .. SomeProperty = 32
    .. await InitializeAsync()
    .. await AnotherAsyncMethodAsync();
```

**Comment by HaloFour** [comment]
@JeroMiya 

C# is a whitespace insensitive language, which means that the following must also be legal:

```cs
Foo x = new Foo()..InitializeSync()..SomeProperty = 32..await InitializeAsync()..await AnotherAsyncMethodAsync();
```

Which clearly doesn't make any sense.  The property setter would be immediately ambiguous as the `..` could apply to `32` and not to the result of assigning `SomeProperty`, and `await` doesn't make sense at all.

**Comment by JeroMiya** [comment]
I'd like to propose an alternate syntax that might eliminate the typo-sensitivity of this proposal, instead of `..` use `then`.

```
// each line starting with .. is a statement, evaluated in the order they appear.
Foo x = new Foo()
    then InitializeSync()
    then SomeProperty = 32
    then await InitializeAsync()
    then await AnotherAsyncMethodAsync();
```

**Comment by CyrusNajmabadi** [comment]
> I'd like to propose an alternate syntax that might eliminate the typo-sensitivity of this proposal, instead of .. use then.

1. this is still ambiguous.    

i.e.:

```
    ... 32
    then await InitializeAsync()
```

What makes the 'then' apply to `new Foo()` insead of to `32`?

2.  I still don't understand the semantics here.  Say you have `then SomeProperty = 32`.  So this is supposed to be equivalent to the statement `SomeProperty = 32;`.  But what is SomeProperty?  Why would this statement work?

**Comment by YairHalberstadt** [comment]
Just throwing spaghetti at the wall, an alternative syntax could be something like this.

```csharp
return A.B.{
    SomeMethod(),
    SomeProperty = 87,
    SomeExtensionMethod()
    };
```

This would be converted to

```csharp
var temp = A.B;
temp.SomeMethod();
temp.SomeProperty = 87;
temp.SomeExtensionMethod();
return temp;
```

As you can see, this is taking some inspiration from initialisers, but with added power.

I think this was discussed in another proposal recently.

I don't actually think this is a good idea. I do however think it's a more C-sharpy way of achieving the aim of this proposal, and less ambiguous.

**Comment by CyrusNajmabadi** [comment]
So the idea is, you provide a list of 'statements'.  Then he language acts as if *lexically*, `temp.` (with a unique name obviously) is prepended to the statement?  

And the idea is... what is in the statement should be in a form that can then make sense after `temp.`?

So, like, how would i do the following:

```
var whatever = new A.B.C();
whatever[1] = 2;
```

?

```[1] = 2``` is not a valid statement, so it's unclear how it would work in that list.  (Similar points made for all the other things you might want to do with a value that wouldn't be clear how to do after a `.`).

**Comment by JeroMiya** [comment]
@CyrusNajmabadi As expressions are evaluated left to right, the expression to the left of the first `then` is evaluated eagerly. Thus, if you want to nest `then` chains you need parenthesis:

```
new Foo() then FooProperty = (new Bar() then BarProperty = 12);
```

> I still don't understand the semantics here. Say you have then SomeProperty = 32. So this is supposed to be equivalent to the statement SomeProperty = 32;. But what is SomeProperty? Why would this statement work?

Within the context of a `then` statement, the accessible properties, fields, and methods of the expression object become lifted into scope and can be referenced without an instance name or expression. Further, those symbols have priority over other symbols higher in the scope. You don't even need to reference them first after the `then`, though you typically would:

```
class A {
    static async Task DoSomethingAsync(String b) {...etc... }
}

class B {
    public B(string value) {  Value = /* Some special transformation of value */; }
    public string BProperty { get; set; }
}

var foo = new B("test") then await A.DoSomethingAsync(BProperty);
```

**Comment by CyrusNajmabadi** [comment]
> Within the context of a then statement, the accessible properties, fields, and methods of the expression object become lifted into scope and can be referenced without an instance name or expression

So, then it's *not* equivalent to `temp. ...` Instead, it would be that any usages of any names would now lookup in the temp val first?  That alone seems pretty far out there for C#.  

How would i, for example, reference a local with the same name as the member names of something?

---

This inverts the established pattern of C# lookup that local names always take precedence over member names.  This would now allow member names to have higher precedence which would certainly be confusing and unexpected for people.  Furthermore, having locals have precedence was never a problem in the past because you could always qualify to get to a member name.  But how do you 'qualify' to get to a local?

**Comment by CyrusNajmabadi** [comment]
i.e. in this example:

`onClick.listen((e) => window.alert('Confirmed!'))`

'onClick' and 'window' *both* might now be found on the instance.  That's a big swing away from how the langauge has been expected to work up until now.

**Comment by YairHalberstadt** [comment]
@cyrusNajmabadi

Rethinking it, I think for consistency with object initialisers, I would remove the ., which would also solve your indexer problem.

So it would be:

```csharp
return A.B{
    SomeMethod(),
    SomeProperty = 87,
    SomeExtensionMethod(),
    [1] = 2
};
```

Then Object Initialisers become a special case of this.

I agree await does not belong there.

Is it nice? 
No.

Does it really make sense from a purist perspective?
Possibly not.

Would I use it all the time if it were introduced?
Hell yeah!

Do the benefits outway the costs?
That's not my decision to make.

**Comment by JeroMiya** [comment]
> So the idea is, you provide a list of 'statements'. Then he language acts as if lexically, temp. (with a unique name obviously) is prepended to the statement?

No, anywhere in the statement. Not just the first thing. 

> [1] = 2 is not a valid statement, so it's unclear how it would work in that list.

```
var x = new string[] { 1, 2, 3} then this[1] = 3;
```

> This idea of just grabbing something random, and lexically inserting it into another statement seems super strange and out there for C#.

It's not actually. We have the same rules within the body of class methods and properties.

> This inverts the established pattern of C# lookup that local names always take precedence over member names. This would now allow member names to have higher precedence which would certainly be confusing and unexpected for people. Furthermore, having locals have precedence was never a problem in the past because you could always qualify to get to a member name. But how do you 'qualify' to get to a local?

It doesn't, because each `then` statement is a new scope, below the outer local scope. Hypothetically similar to the body of a lambda expression with all of the expression object's public members passed in as arguments.

**Comment by CyrusNajmabadi** [comment]
> No, anywhere in the statement. Not just the first thing.

I do not see how that could work.  You would basically need a generalized syntax for "what can come after a expression".  That's fundamentally ambiguous.  For example, if i have:

```
var v = whatever {
    (x) = 1 + (y + z)
}
```

The first `(x)` will be an invocation on 'whatever' (maybe returning a ref value).  For consistency `(y + z)` would need to be the same.  But this makes both parsing and evaluation of parenthesized expressions *super* confusing/complex.

**Comment by CyrusNajmabadi** [comment]
> It's not actually. We have the same rules within the body of class methods and properties.

How so?  Where does this happen elsewhere.  Normally, if you have a name in an expr context, it's *always* "look up in local scopes", then look into 'member scope' for this the current type.

This changes that.  This brings in *members* that bind more tightly than locals.  This is not a good thing because there's no way to get to locals anymore.  i.e. having locals hide members is fine since you always have a way to get to members.  i.e. you can write `this.` or `Type.`.  So you can always reach your locals by simple name, and your members by qualified name.  This proposal breaks that.  Members would now block locals, and there would be no way around that.

**Comment by YairHalberstadt** [comment]
@cyrusNajmabadi

> How do you get this to parse. for example:

> var v = whatever {
>   [2] = [1].ToString()
> }
> ?

Same as object initialisers:

```csharp

class Class
{
public int X {get; set;}
}

...

var X = 32;

new Class{
X = X; //X on the left is a property, X on the right is a local
};

Similarly 

```csharp
var v = whatever {
   [2] = [1].ToString()
}
``` 
would be dissallowed

**Comment by CyrusNajmabadi** [comment]
> would be dissallowed

Ok.  So now i'm confused by the proposal.  It was saying: 

> Within the context of a then statement, the accessible properties, fields, and methods of the expression object become lifted into scope and can be referenced without an instance name or expression.

and

> It doesn't, because each then statement is a new scope, below the outer local scope. Hypothetically similar to the body of a lambda expression with all of the expression object's public members passed in as arguments.

Are the members lifted into scope of the entire statement or not?

**Comment by YairHalberstadt** [comment]
We are two different people suggesting two different proposals 😄

**Comment by CyrusNajmabadi** [comment]
Can you open a separate proposal then?

**Comment by YairHalberstadt** [comment]
I don't believe in it enough to. I was just speculating

**Comment by JeroMiya** [comment]
@cyrusnajmabadi

> How so? Where does this happen elsewhere. Normally, if you have a name in an expr context, it's always "look up in local scopes", then look into 'member scope' for this the current type.

There are two places mentioned that behave similarly: class method/property bodies and lamda expression bodies with arguments. Just like in a member function, all the accessible members of that class or struct can be accessed without an explicit `this.Member = "Foo"`. If the body of a then expression introduces its own local, then that local would take precedence over members of the expression object.

In the body of a lambda expression, the arguments to the function take precedence over local variables outside the lamda body. Further, there too there is no way to access that outer local, if a lambda argument has the same name. You must store the local in another name to access it in the lambda body. In terms of name resolution, you can think of the body of a then statement as like the body of a lambda expression with every accessible member of the expression object passed in as an argument:

```
var x = "Foo";
((String Length) => Console.WriteLine(Length))( x.Length);
```

Note: this only applies to name resolution rules. Functionally, the names are expanded in the statement body with a reference to the object itself, as if you saved it to a temp variable and closed over it:

```
var x = new Foo();
(() => x.Property = 20)();
```

And, in reality, it gets compiled to this:

```
//From this
var x = new Foo() then Property = 20 then Console.WriteLine(Property);

// To this
var temp = new Foo();
temp.Property = 20;
Console.WriteLine(temp.Property);
var x = temp;
```

**Comment by JeroMiya** [comment]
@CyrusNajmabadi It should also be noted that name collisions between local variables and public members are relatively unlikely given that the default naming conventions for .NET use pascal case for public members and camel case for local variables.

@YairHalberstadt This is an interesting proposal as well, though I think I would prefer to reduce the use of brackets overall rather than add another bracket syntax with a different context. We already have flow control blocks, scope blocks, lambda expression bodies, local function bodies, class definitions, array and other initializers. 


The goal of this proposal, in my view, is to help improve C#'s usability for more declarative code. There are a number of examples of this feature being used for that purpose in Dart and Flutter, for example, which were the inspiration for this proposal.

**Comment by CyrusNajmabadi** [comment]
> There are two places mentioned that behave similarly: class method/property bodies and lambda expression bodies with arguments.

Neither of these are similar.  With method/prop bodies, locals always mask members, not the other way around.

The is hte same with lambdas.  They don't have arguments, they ahve parameters, which are essentially identical to locals.

In both these cases, locals/params have the narrowest scope, and you can used qualified-member-access to get to members if you need to.  Your approach is flipping this around such that members now mask locals, with no way to get to locals.

**Comment by CyrusNajmabadi** [comment]
> In the body of a lambda expression, the arguments to the function take precedence over local variables outside the lamda body.

You are mistaken how lambdas work.  They cannot have parameter names that conflict with locals.

**Comment by CyrusNajmabadi** [comment]
> between local variables and public members 

And what about private members?  That's why we allow qualified member lookup in the first place.  Because it's very common to have a local and field with the same name.  if you "when'ed/with'ed/whatever'ed" over your own types, you would block your own locals.

Again, this is something the language steadfastly works to avoid.  You should not have members taking precedence over locals.  They should not ever be hidden from you.

**Comment by JeroMiya** [comment]
> In both these cases, locals/params have the narrowest scope, and you can used qualified-member-access to get to members if you need to. Your approach is flipping this around such that members now mask locals, with no way to get to locals.

OK, this is a valid point, but I think I can address it. Let's combine the `then` keyword with `..`. For a start, locals would take precedence over member functions. Then we use `..` as a way to do qualified member lookup on the _unnamed_ expression object. Like so:

```
class Bar { 
  public int Foo { get; set; }
  public int Foo2 { get; set; }
}
class A {
    public int Foo { get; set; }
    public Bar SetFooAndCreateABar(int value) {
        Foo = value; // sets ((A)this).Foo to value
        return new Bar() 
            then ..Foo = Foo // creates a Bar, sets that Bar's Foo property to ((A)this).Foo
            then Foo2 = Foo + 1; // don't need .. for Foo2 as there is no conflict
    }
}
```
See also how `..` sort of slots into the same theme as `?.` and `!.` as a kind of modified `.`.

Also note that `then` statements can also introduce their own locals, which also take precedence over members too:

```
var widget = new Widget() then Clicked += (s, e) => {
                          // note lambda-param-name/local-name conflict rules enforced here with s, e above.
                            var localVariable = 20;
                     };                   
```

**Comment by JeroMiya** [comment]
Given that this issue is closed and that my proposal is somewhat diverging from the original one in this thread, does anyone have a problem with me opening a new issue?
