### ISSUE TITLE
Proposal: allow sizeof in any context

### ISSUE THREAD

**Issue by jaredpar** [dotnet/csharplang#1828]
Presently `sizeof` is an operation that is restricted to `unsafe` code only. This restriction exists because ... well it seems it's just an accident of history. It should just be allowed in all places the IL operation `sizeof` is legal.

**Comment by eerhardt** [comment]
@jaredpar - I almost just put a bug into my library because of https://github.com/dotnet/roslyn/issues/26513.

I wanted to write something like:

```C#
            private void CreateBuffers<T>(PrimitiveArray<T> array)
                where T: unmanaged
            {
                _buffers.Add(CreateBuffer(array.ValueBuffer, array.Length * sizeof(T)));
            }
```

I assumed that `sizeof(T)` would be fine, since I was restricting to `unmanaged`. However, I got the compile error:

```
Severity	Code	Description	
Error	CS0233	'T' does not have a predefined size, therefore sizeof can only be used in an unsafe context (consider using System.Runtime.InteropServices.Marshal.SizeOf)
```

And I thought "Oh great, I don't need to drop to `unsafe` I can just use `Marshal.SizeOf`". However, I was completely unaware of the difference between `Marshal.SizeOf<bool>` and `sizeof(bool)`.

If this language proposal doesn't get traction, do you think we could at least fix the error message to not point users in the wrong direction?

**Comment by jaredpar** [comment]
@eerhardt I don't think there is any objection to the proposal. It's just finding time to implement it.

**Comment by eerhardt** [comment]
How about finding time to fix the error message? 😝

**Comment by YairHalberstadt** [comment]
@jaredpar
Is this issue championed then?
And if so would it be suitable for a community member to implement?
From the sound of it , it doesn't seem too complex.

**Comment by jaredpar** [comment]
@eerhardt 

> How about finding time to fix the error message?

If it's a priority then why not send a PR? Probably less characters than the content of this thread.

**Comment by jaredpar** [comment]
@YairHalberstadt 

> Is this issue championed then?

It is now. I often forget to champion issues I open for some reason. 

> And if so would it be suitable for a community member to implement?

Yes this is a reasonable size for community. I'd suggest though getting your existing PRs done first. Then moving onto this. At the moment we're in C# 8.0 lock down and don't have much bandwidth for reviewing new features that are post C# 8.0. In a month or so hopefully things will calm down and we'll have more bandwidth for doing so.

**Comment by YairHalberstadt** [comment]
> I'd suggest though getting your existing PRs done first. 
I'm working on that 😉

**Comment by tannergooding** [comment]
@jaredpar, if this won't be possible in the C# 8.0 timeframe, then is an alternative (such as changing the error message: https://github.com/dotnet/roslyn/pull/33725) a better temporary solution?

The concern is that the error message points people in the wrong direction as it implies `Marshal.SizeOf` is a suitable replacement for `sizeof`. When, in actuality, what you use depends on your scenario.

The safest option, IMO, would be to remove the suggestion to use any alternative API which forces users to either use `unsafe` or to google the issue which brings up plenty of results from others who have hit the same issue and had to learn the differences.

**Comment by YairHalberstadt** [comment]
This is what the ecma specification says about the sizeof IL operator:

> ### III.4.25 sizeof – load the size, in bytes,of a type
> 
> Format | Assembly Format | Description
> -- | -- | --
> FE   1C <T> | sizeof _typeTok_ | Push the size, in bytes, of a type as an unsigned int32.
> 
> 
> #### Stack Transition:
> …, 🡲 …, size (4 bytes, unsigned)
> 
> #### Description:
> 
> Returns the size, in bytes, of a type. typeTok can be a generic parameter, a reference type or a
> value type.
> 
> For a reference type, the size returned is the size of a reference value of the corresponding type,
> not the size of the data stored in objects referred to by a reference value.
> 
> [Rationale: The definition of a value type can change between the time the CIL is generated and
> the time that it is loaded for execution. Thus, the size of the type is not always known when the
> CIL is generated. The sizeof instruction allows CIL code to determine the size at runtime
> without the need to call into the Framework class library. The computation can occur entirely at
> runtime or at CIL-to-native-code compilation time. sizeof returns the total size that would be
> occupied by each element in an array of this type – including any padding the implementation
> chooses to add. Specifically, array elements lie sizeof bytes apart. end rationale]
> 
> #### Exceptions:
> None.
> #### Correctness:
> typeTok shall be a typedef, typeref, or typespec metadata token.
> #### Verifiability:
> It is always verifiable. 

Currently C# only allows sizeof on an unmanaged struct, in an unsafe context. However IL allows it on any type, and considers the operator safe on any type.

However `sizeof referenceType` will always return the sizeof a native pointer (4 on 32 bit, 8 on 64 bit).

This is both confusing, and useless.

As such I suggest the following specification for when sizeof is allowed:

1. sizeof(T) should be allowed in any context.
2. sizeof(T) should be allowed if T is a concrete value type.
3. sizeof(T) should be allowed if T is a generic type which is unconstrained, or constrained to a type which may be a value type.
4. sizeof(T) should be forbidden if T is a concrete reference  type.
5. sizeof(T) should be forbidden if T is a generic type constrained to a type which cannot be a value type.

In practice this means that 
a) if `T` is a concrete reference type, then sizeof(T) is forbidden.
b) if `U` is a concrete reference type other than `object`, or `object?`, then `sizeof(T) where T : U` is forbidden.
c) if `U` is a generic type, but `sizeof(U)` is forbidden, then `sizeof(T) where T : U` would also be forbidden.
d) Otherwise, `sizeof(T)` is permitted.
This means that whether sizeof(T) is permitted can be calculated recursively very simply.

Thoughts?

**Comment by yaakov-h** [comment]
> 3. sizeof(T) should be allowed if T is a generic type which is unconstrained

What meaning does `sizeof(ValueTuple<>)` give? If you're going to forbid it in places you consider useless, why is this one useful?

**Comment by YairHalberstadt** [comment]
Sorry I misspoke. I meant, without a constraint, i.e. no `where T : U`

**Comment by YairHalberstadt** [comment]
I've updated my previous comment to reflect your point.

**Comment by YairHalberstadt** [comment]
I have put together a prototype using my suggested implementation at https://github.com/dotnet/csharplang/issues/1828#issuecomment-473829692.

https://github.com/YairHalberstadt/roslyn/tree/SizeOfInAnyContext

**Comment by YairHalberstadt** [comment]
@jaredpar 
Would you like me to create a pull request from my prototype implementation for this?

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-08-28.md#allow-sizeof-in-safe-code

Do we not think it's valuable to avoid `unsafe` when it really isn't needed? For interop heavy code like WinForms this is really annoying and leads to wasted cycles trying to analyze why methods are marked unsafe and removing unnecessary usages of `Marshal.SizeOf` which keep sneaking back in.

**Comment by tannergooding** [comment]
> For interop heavy code like WinForms this is really annoying and leads to wasted cycles trying to analyze why methods are marked unsafe and removing unnecessary usages of Marshal.SizeOf which keep sneaking back in.

`sizeof(T)` and `Marshal.SizeOf<T>()` are also not the same thing (and the compiler currently recommends the latter if you use `sizeof(T)` in a safe context today). The correct alternative is `Unsafe.SizeOf<T>()` (which only exists to workaround this language limitation).

For reference:
* `sizeof(T)` and `Unsafe.SizeOf<T>()` return the size of a type in managed code (e.g. `sizeof(bool)` is `1`)
* `Marshal.SizeOf<T>()` returns the size of a type if it were marshaled to native code (e.g. `Marshal.SizeOf<bool>()` returns `4`). This also includes any attributes or other modifiers applied (so `Marshal.SizeOf<bool>()` could be made to return `1` instead, if for example you had `UnmanagedType.U1`)

**Comment by JeremyKuhne** [comment]
> sizeof(T) and Marshal.SizeOf<T>() are also not the same thing 

Thanks for pointing this out. To be completely explicit about the WinForms case: there are still places where `Marshal.SizeOf<T>()` is still the right choice, but I'm actively pushing to get rid of those by making the data structures blittable. `Marshal.SizeOf<T>()` is a code smell for sure.

**Comment by BoyBaykiller** [comment]
https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-08-28.md#allow-sizeof-in-safe-code

> Rejected, until we hear compelling use cases.

Why does `sizeof` require `unsafe` in the first place? Why do we need justification to lift this (arbitrary?) restriction?
