### ISSUE TITLE
Keyword similar to Enum

### ISSUE THREAD

**Issue by srburton** [dotnet/csharplang#1860]
I see a lot of my need and other programmers something similar to the more string-focused enum  

**Ex:**
```
public estr Templates
{
  CLIENT = "client.cshtml",
  MASTER = "master-admin.cshtml", 
}

Console.Write("Template name: {0}",  Templates.CLIENT );

```
**Output:**

`Template name: client.cshtml`

**Comment by srburton** [comment]
@DavidArno 

Very unnecessary to have to type and reorder several times this snippet of code besides leaving very loaded visually and confused  

**public const string**

**Comment by CyrusNajmabadi** [comment]
>  besides leaving very loaded visually and confused

This has been idiomatic since C# 1.0.  Up till now it hasn't been confusing :)

**Comment by srburton** [comment]
My example 
public estr Templates
{
 CLIENT1 = "client.cshtml",
 CLIENT2 ="client.cshtml",
 CLIENT3 ="client.cshtml",
 CLIENT4 ="client.cshtml",
 CLIENT5 ="client.cshtml",
 CLIENT6 ="client.cshtml",
 CLIENT7 ="client.cshtml",
 CLIENT8 ="client.cshtml",
 CLIENT9 ="client.cshtml",
 CLIENT10 ="client.cshtml",
 CLIENT11 ="client.cshtml",
 CLIENT12 ="client.cshtml",
 CLIENT13 ="client.cshtml",
}


Your example

```
public static class Templates
{
  public const string CLIENT1 = "client.cshtml";
  public const string CLIENT2 = "client.cshtml";
  public const string CLIENT3 = "client.cshtml";
  public const string CLIENT4 = "client.cshtml";
  public const string CLIENT5 = "client.cshtml";
  public const string CLIENT6 = "client.cshtml";
  public const string CLIENT7 = "client.cshtml";
  public const string CLIENT8 = "client.cshtml";
  public const string CLIENT9 = "client.cshtml";
  public const string CLIENT10 = "client.cshtml";
  public const string CLIENT11 = "client.cshtml";
  public const string CLIENT12 = "client.cshtml";
  public const string CLIENT13 = "client.cshtml";
  public const string CLIENT14 = "client.cshtml";
  public const string CLIENT15 = "client.cshtml";

}
```
In my example the code gets cleaner, this is called **Clean Clode**

**Comment by CyrusNajmabadi** [comment]
I don't see anything unclean about the latte rform.  Same number of lines.  a couple of extra tokens per line :)  Seems totally reasonable give how you'll only create a few of these and then writes tons more conde that consume them.

**Comment by srburton** [comment]
Look I see a lot of difference and searching in Google there is a lot of demand about enum to support the string if you are looking to be thought to implement in C# this is not something useless, I assure you will be very well accepted by the community because it has a lot of demand for it.

**Comment by srburton** [comment]
If implemented and you do not like the implementation is just not use, I will use and very this feature if it comes to be implemented.

**Comment by HaloFour** [comment]
What benefit does this offer than a slightly less verbose syntax?

**Comment by bondsbw** [comment]
I have to agree with @srburton on this one.  The `public const string` version is not as good as the one proposed, which is much more readable and enforces consistency.

Integer enums aren't strictly necessary either for the same reason, but plenty of developers prefer them.

There are other valid reasons this might not get off the ground.

**Comment by YairHalberstadt** [comment]
@DavidArno: One advantage is you could then accept an instance of the Template estr as a parameter, rather than just a string.

**Comment by YairHalberstadt** [comment]
@srburton: I think you underestimate the cost involved in implementing a new feature. A feature cannot be added simply because you would find it useful.

To get an idea of the difficulty of adding a feature, try forking the Roslyn repo and adding the feature yourself. And note that for real it would take at least 10 times that effort in testing and making sure the feature is fully supported by Intellisense etc

**Comment by HaloFour** [comment]
@srburton

> Benefit is a cleaner and clearer implementation.

I mentioned verbosity already.  "Cleaner" and "clearer" are very subjective.  In my opinion, unless it could bring the same behavior as integral enums they would only be confusing.  And `estr` would be an awful keyword.  `enum` or bust.

**Comment by CyrusNajmabadi** [comment]
enums are actually a different type.  i.e. i can't do the following `Foo(5)` instead of `Foo(Color.Red)`.  Do you envision that being the same here?  Would you make it so that you couldn't pass a string where a Template was required, or vice versa?

**Comment by CyrusNajmabadi** [comment]
> Benefit is a cleaner and clearer implementation.

It's not "clear" to me (har har) what is clearer here over a const-string.  Const-strings have been understood and idiomatic in C# since 1.0.  To me, it would be less clear because i would be wondering "what is the difference here...?"

**Comment by SilentSin** [comment]
Also consider that numeric enums are quick and easy to cast back and forth, but to cast `(Templates)"master-admin.cshtml"` would be significantly more expensive.

**Comment by SilentSin** [comment]
@srburton 
```
public static class Templates
{
    public const string
        CLIENT = "client.cshtml",
        MASTER = "master-admin.cshtml";
}
```

**Comment by orthoxerox** [comment]
I feel like this can be done using a simple T4 template that takes a file of key-value pairs and generates a static class full of const strings. Or even an instance class full of static readonly fields, so you actually get a distinct type.

**Comment by zippec** [comment]
I usually use System.ComponentModel.DescriptionAttribute and custom extension method ToFriendlyName instead of implicit ToString when in need of this.
I think this could be made easier by creating new attribute specificaly for this purpose that enum ToString method would understand. It would not be unprecedented as FlagsAttribute already changes behavior of enum ToString. Something like:
```C#
public enum Templates
{
    [FriendlyName("client.cshtml")] Client,
    [FriendlyName("master-admin.cshtml")] Master
}
```

**Comment by willard720** [comment]
While I don't think this is very necessary, the main benefit here is type safety. It would be nice to use switch statements or parameters that only accept this enum, not just any string. That being said:

```csharp
public enum Template { Client1, Client2, Client3, Client4, Client5, Client6, Client7, Client8, Client9, Client10, Client11, Client12, Client13 }

...
public static string GetString(this Template template)
{
    switch (template)
    {
        case Client1:  return "client1.cshtml";
        case Client2:  return "client2.cshtml";
        case Client3:  return "client3.cshtml";
        case Client4:  return "client4.cshtml";
        case Client5:  return "client5.cshtml";
        case Client6:  return "client6.cshtml";
        case Client7:  return "client7.cshtml";
        case Client8:  return "client8.cshtml";
        case Client9:  return "client9.cshtml";
        case Client10: return "client10.cshtml";
        case Client11: return "client11.cshtml";
        case Client12: return "client12.cshtml";
        case Client13: return "client13.cshtml";
    }
}
```

Works just fine, and you just have to use `GetString` whenever you want the string value. However, when C# 8 comes out, you'll be able to use extension everything to make `GetString` an implicit cast from `Template` to `string`. It may not be as convient, but I don't think it's a big enough burden to warrent adding a new feature.

**Comment by DavidArno** [comment]
[
isn't listed in the possible features for v8.0](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) and issue #192 (Champion "Extension function members") is marked as `X.0`.

**Comment by willard720** [comment]
@DavidArno Well that's a bummer. So that means, since it's `X.0`, it won't be on `X.1` or something either, but rather C# 9.0, 10.0, etc?

**Comment by bondsbw** [comment]
@willard720 As an observer, I wouldn't put much faith in those tags.

If the tag has a specific major/minor version number, _and_ that number is the very next one due out, _and_ the feature is already fully implemented, then you can probably be safe assuming it will appear in that version.  _Maybe._

Otherwise there isn't much reason to believe that the version number has any worthwhile meaning.

**Comment by DavidArno** [comment]
@willard720, yes, that is exactly what `X.0` means: the feature is felt, by the team, to be too big a change to add in a "point release" and should be in a major release. So there's very little chance of it making 8.0 at this stage, but might be in 9.0. Or it might never see the light of day, of course.

**Comment by Vivelin** [comment]
I think this is a good idea and maybe just a bad example. [The pattern is common enough](https://stackoverflow.com/questions/424366/string-representation-of-an-enum), and there are more benefits to this than simply saving characters:

- Type safety; providing a closed set of (string) values (explicit casting notwithstanding);
- Not having to re-implement functions like Enum.GetNames, Enum.GetValues, Enum.Parse, Enum.TryParse for each "string enum" you want to use;

**Comment by Davilink** [comment]
Some feature has been integrated in the C# only for sole purpose to been shorter to write, the first to come to my mind is the keyword « var ».

**Comment by gafter** [comment]
> Some feature has been integrated in the C# only for sole purpose to been shorter to write, the first to come to my mind is the keyword « var ».

That is not why `var` was introduced into C#. It was introduced at the same time as Linq and anonymous types so that it would be possible to assign the result of a Linq expression to a local variable when the Linq expression results in an anonymous type.

**Comment by MgSam** [comment]
I don't like the syntax of the proposal but the need for a string enum is a valid one.

I'm also surprised how many people (including @CyrusNajmabadi ) have made the absurd claim that a string enum is equivalent to a static class of const strings. This is the C# language design forums right, where static typing is one of the pillars of the language? Having a collection of strings is not the same as having a type. The reasons why should be obvious.

I'll also point out that Java has had string enums for decades, and TypeScript added string enums because the community demanded them despite heavy initial resistance from the design team. I also happen to write a lot of TypeScript and a lot of C#, so I'll mention anecdotally that my enums in TypeScript are almost exclusively strings because they're useful in many more scenarios than integers. (And that I always miss having this feature in C#.)

@gafter That was obviously a major motivating factor but I highly doubt it was the only one. Any statically typed language worth its salt has added a way to infer the types of local variables to save typing and allow simpler refactorings. [Eric Lippert's blog post](https://blogs.msdn.microsoft.com/ericlippert/2005/09/27/c-3-0-is-still-statically-typed-honest/) from the time lists saving typing as the 1st reason for adding it, and LINQ as the 2nd reason.

**Comment by theunrepentantgeek** [comment]
@MgSam wrote:

> I'm also surprised how many people (including @CyrusNajmabadi ) have made the absurd claim that a string enum is equivalent to a static class of const strings. 

As long as the "value" of the enum can be passed where a string is expected, the two are isomorphic. It doesn't matter whether the values are actual strings or are strongly typed, as soon as the values are strings (or implicitly castable to strings), you lose all type safety.

Now, if you're talking about an actual strongly typed "enum" like this …

``` csharp
public class CustomerType
{
    private readonly string _name;
    private CustomerType(string name) => _name = name;
    public override GetHashCode() => ...
    public override Equals(Object other) => …
    public override ToString() => _name;

    public static CustomerType General = new CustomerType("General");
    public static CustomerType Bronze = new CustomerType("Bronze");
    public static CustomerType Silver = new CustomerType("Silver");
    public static CustomerType Gold = new CustomerType("Gold");
    public static CustomerType Platinum= new CustomerType("Platinum");
    public static CustomerType Black = new CustomerType("Black");
}
```

Then I'm totally onboard with the strongly typed approach; it's one I've used multiple times with good success. (Reminds me - I've got a draft blog post on the subject I really should finish and publish.)

But …

… we already have good tooling for this sort of thing. Even doing it by hand isn't actually onerous, and I'd rather see the C# team focus their energy on features with a higher ROI.

**Comment by CyrusNajmabadi** [comment]
> I'll also point out that Java has had string enums for decades, and TypeScript added string enums because the community demanded them despite heavy initial resistance from the design team. I also happen to write a lot of TypeScript and a lot of C#, so I'll mention anecdotally that my enums in TypeScript are almost exclusively strings because they're useful in many more scenarios than integers. (And that I always miss having this feature in C#.)

The resistance was because of concerns we had over the redundancy of such a feature versus the unbaked, but tickling-the-back-of-our-heads, "union types" feature.  You'll note that with union types, having string-enums is far less important, and seems to now be used far less as well in APIs.  Why need to declare an enum to specify the strings that can eb taken, when i can just say: `{ p: "foo" | "bar" | "baz" }`.  This also follows much more of the JS style of developement, where someone would say `{ p: "foo" }`, not `{ p: SomeEnum.Foo }`. 

String enums came about at an early time in TS when it was less clear what the MO of the language was.  If the language were done again now, with everythign we know, i think there would be almost no chance they would happen now.

**Comment by CyrusNajmabadi** [comment]
> I'm also surprised how many people (including @CyrusNajmabadi ) have made the absurd claim that a string enum is equivalent to a static class of const strings. This is the C# language design forums right, where static typing is one of the pillars of the language? Having a collection of strings is not the same as having a type. The reasons why should be obvious.

None of hte proposal said anything about these being anything but normal strings.

**Comment by YairHalberstadt** [comment]
I'm going to close this as a 'duplicate' of #2849. Although this is earlier, that issue is more detailed, so I think it's best to continue conversation there.
