### ISSUE TITLE
Full featured g4 file for ANTLR generator

### ISSUE THREAD

**Issue by Chris2011** [dotnet/csharplang#1902]
Is it possible, that you can create a full featured grammar (g4) file, that I can use to generate the other needed files (Tokens, Leser, Parser, etc.) with ANTLR?

That would be awesome.

Cheers

Chris

**Comment by ufcpp** [comment]
There are some related issues in [Roslyn](https://github.com/dotnet/roslyn/search?q=ANTLR&type=Issues)

**Comment by Chris2011** [comment]
I know, the first one was originially created by me too :). I didn't know, where it is better to ask for such files, here or there. Because of the naming csharplang of this repo, I thought it would be right to ask here.

**Comment by gafter** [comment]
I think this is a reasonable place to ask, but I'm not sure that producing a *fully functional* parser (i.e. a reference implementation) would reasonably be in the scope of the language specification.

**Comment by gafter** [comment]
Having said that, if someone wrote such a thing, and we believed it were correct, I think it would be reasonable for it to be hosted here.

**Comment by DanFTRX** [comment]
A quick google search found this: https://github.com/antlr/grammars-v4/tree/master/csharp   Not sure if its helpful or not.

**Comment by YairHalberstadt** [comment]
@DanFTRX
That is only valid for C#6

**Comment by Chris2011** [comment]
@DanFTRX already knows it and created tickets too. So everything is in a circle now. C# grammer from the antrl comes from here: https://github.com/ChristianWulf/CSharpGrammar. More or less. So the topic is quite complex for me. I'm searching long time for a right grammar file to use it. I mean I already use the one from antlr but it is not official, that's why I asked.

One little example:
```csharp
var var = 2; // Valid and the first var is hightlighted correctly;
```
When I use the generated stuff, I got this:

```javascript
var var = 2; // Valid but the second will also highlightes as a keyword.
```

In the end, I have to say, that I don't have enough knowledge about lexer, parser, grammar shizzle whatever. So I don't know whether I have to fix the var var thingy inside of the grammar to treat it correctly and color it as a normal variableName or not.

Long story short, I'm in this project to create a NetBeans C# plugin: https://github.com/Chris2011/CSharp-for-netbeans

**Comment by Chris2011** [comment]
But anyway, thx for the discussion and the topic :)

**Comment by theunrepentantgeek** [comment]
C# Intellisense and syntax highlighting for a number of non-VisualStudio editors (including Visual Studio Code) is driven by the [OmniSharp](http://www.omnisharp.net/) project - this might be worth checking out as a more fruitful approach than that ANTLR grammar.

**Comment by CyrusNajmabadi** [comment]
> In the end, I have to say, that I don't have enough knowledge about lexer, parser, grammar shizzle whatever. So I don't know whether I have to fix the var var thingy inside of the grammar to treat it correctly and color it as a normal variableName or not.

It's worth pointing out that this can not be handled in a grammar.  The case you're referring to needs actual *semantic* analysis to do properly.  In Roslyn, we do this by actually taking the tree, and having a classifier pass over it, accessing the semantics of hte compiler to figure out what's going on.

So even if you had a antlr/g4 grammar for this, you'd still be SOL because, from the language's perspective, both of these `var`s are just identifiers with the letter `v` `a` `r`, and nothing more...

**Comment by Chris2011** [comment]
@CyrusNajmabadi understood. Thx. That's enough for the moment to know, that I have to change the plugin code and rethink my work.

Maybe out of topic but can you tell me what SOL is? In the end, we can close this ticket here. The rest was discussed in the other ticket: https://github.com/dotnet/roslyn/issues/8379#issuecomment-427104237

**Comment by theunrepentantgeek** [comment]
TIL (Today I Learned) that SOL doesn't mean what I thought it did ... it's not _Sweet Out of Luck_. 😊

Definition: https://www.urbandictionary.com/define.php?term=SOL

**Comment by KvanTTT** [comment]
```
var var = 2; // Valid but the second will also highlightes as a keyword.
```

@Chris2011 you have to use not only lexer but parserfor proper processing of such context keywords. ANTLR can handle such cases successfully, https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpParser.g4#L406

Some improvements are still required for ANTLR grammar for building full-fidelity tree:

* Leading and Trailing trivia
* Correct preprocessor directives handling (the most difficult)

Moreover, it's better to rewrite [expression rules](https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpParser.g4#L83-L163) on left-recursion manner because it's more clear and faster.

**Comment by Chris2011** [comment]
Atm I don't have tests. As I said, I don't have enough knowledge about lexer/parser/grammar, so I thought it is nice to find a good working one. Help with that stuff, will be much appreciated to bump into this lexer/parser stuff etc. But if everyone thinks, that any other solution is better, I would prefer that solutions too. Like OmniSharp or LSP for C#.

**Comment by CyrusNajmabadi** [comment]
> @Chris2011 you have to use not only lexer but parserfor proper processing of such context keywords. ANTLR can handle such cases successfully, https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpParser.g4#L406

How can antlr handle this?  it takes semantic understanding to know that "var" is intended to be a keyword here, and not the name of an actual type called "var".  Note: this is not hypothetical.  There are codebases out there that create a type named "var" so that people can't use the "var" keyword :) 

This is why Roslyn's (and by extension, OmniSharp's) 'highlighter' uses semantics so it can figure this out properly.  It's def why we recommend using these existing tools (or using a LSP system backed by them) so that this is all computed correctly :)

**Comment by KvanTTT** [comment]
I suppose the `var` problem can be handled by the following grammar:

```antlr
// Lexer
VAR: 'var';
ID:  [0-9a-zA-Z];

// Parser
varDeclaration
    : VAR identifier ('=' expression)? ';'
    ;

identifier
    : ID
    // Other conflicted tokens
    | VAR;
```

With this grammar, the code `var var = 100500;` will be parsed into the following tokens:
`VAR (var) ID (var) EQ (=) NUMBER (100500) SEMI (;)`

Is it correct?

**Comment by jnm2** [comment]
@KvanTTT No, this is what you're up against. It takes semantic understanding to know whether `var` is an explicit type or the contextual keyword `var`:

```c#
public struct var { }
    
public class C
{
    public void M()
    {
        var test = 42;
    }
}
```

**Comment by KvanTTT** [comment]
Ok, you are right, got it.

**Comment by Chris2011** [comment]
So long story short, I can't handle the var var "problem" with a grammar file, right?

**Comment by KvanTTT** [comment]
In common case - not. But maybe this is not a very big problem.

**Comment by 4creators** [comment]
IMHO **it is possible to handle this in g4 ANTLR grammar** but the effort is not worth the result. Fastest solution is to use Roslyn parts to create fast and semantics aware solution.

**Comment by jnm2** [comment]
@4creators g4 ANTLR grammar can handle parsing IL from assembly references to find out if a type named `var` is in scope? The file paths to the referenced assemblies aren't even in the source code. They are a side channel.

**Comment by 4creators** [comment]
> g4 ANTLR grammar can handle parsing IL from assembly references to find out if a type named var is in scope? 

Why would I need that? You cant assign numeric literal unless type has a language built in ability to be assigned with integrals. Just due to the limitation imposed by grammar on assignment operator it cannot be overloaded. It is enough info to resolve the case using plain g4 grammar. Don't forget that ANTLR grammar is quite flexible and allows for very advanced constructs for example I have written fully functional C++ g2 ANTLR grammar more than decade ago. And C++ is far far more complex and treacherous for lexer and parser writers than C#.

**Comment by jnm2** [comment]
> Why would I need that?

To check for invalid programs, maybe?

**Comment by 4creators** [comment]
> To check for invalid programs, maybe?

Common !, fully fledged parser and lexer need to know full semantic context during operation, you need to be able to provide full info on referenced assemblies to have an ability to validate all constructs. Sometimes in languages using compiled modules instead of headers devs forget about the nature of info carried by modules and treat it as `side channel`, `non grammatical construct` whereas info contained in them is just a part of source input which always goes to lexer and parser. The fact that Roslyn calls comprehensive type system analysis `samantics` does not mean that it is something different from parsing headers in C++, right 😄 

ANTLR allows to extend grammar with functionality which is based on programming language which was chosen as a basis for lexer / parser development. You can choose from `Java`, `C++`, `C#` and many others and just use full power of underlying language.

ANTLR is a framework which comprises much more than plain grammar writing and lexer/parser generation and you need to use its all functionality to get expected results for mature programming languages. And it is always important to weight effort required with final value of your work.

**Comment by jnm2** [comment]
It's different from C++ headers because references assemblies are binary IL. I suppose if you plug in a metadata provider and account for normally-invalid method declarations...

**Comment by gafter** [comment]
Roslyn's syntax trees do not treat `var` as a contextual keyword. It is simply an identifier. Whether it binds to a type or not is not determined until later during semantic analysis.

**Comment by Chris2011** [comment]
Hm I learned today, that it is not possible to have syntax highlighting with LSP (yet). So this is not an option. I thought it will handle everything but ok. So there is only one option for me, using OmniSharp, until this was implemented: https://github.com/Microsoft/vscode-languageserver-node/pull/367

**Comment by Chris2011** [comment]
I think I will close this ticket, I will use the textmate lexer file for the syntax highlighting. Same which is used for VS Code. So thx for the explanation and your patients :). The textmate file seems to have good support :)

**Comment by 333fred** [comment]
@CyrusNajmabadi actually added support for a generated antlr grammar to the c# compiler a month or two ago: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4. This grammar is not perfect, as it doesn't do precedence correctly for many constructs, but it might serve your purposes.

**Comment by CyrusNajmabadi** [comment]
It also doesn't contain the lexical specifications.  

The main purpose of it is not to drive tooling, but rather to serve as a much easier way to tell what is changing in the language when we add new language constructs.
