### ISSUE TITLE
[Question] readonly ref and defensive copies

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1986]
In the latest released version of C#, when you work with a struct that is mutable, according to [this article](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code) ...

> However, the compiler can't know if any member method modifies the state of the struct. To ensure that the object isn't modified, the compiler creates a copy and calls member references using that copy. Any modifications are to that defensive copy.

My question is, why cannot the compiler know whether a member method/property changes the state of a struct? Couldn't be possible in future versions of the compiler to find a way to avoid defensive copies without having to define an immutable struct?

Currenlty, if you declare ...

```csharp
public struct Vector2A
{
    public float x, y;
}
```
... or ...

```csharp
public struct Vector2B
{
    public float X { get; }
    public float Y { get; }
}
```
... no defensive copies will be declared. But as soon as you change it to something like ...

```csharp
public struct Vector2C
{
    private float _x, _y;

    public float X { get => _x; set => _x = value; } 
    public float Y { get => _y; set => _y = value; }
}
```
... defensive copies are or may be generated when you pass the latter as a readonly ref parameter in a method like:

```csharp
public static float Add(in Vector2C left, in Vector2C right, out Vector2C result) { ... }
```
If the compiler cannot analyze struct methods for all operations like Add to avoid defensive copies, wouldn't be possible to do something like this?

```csharp
public struct Vector2C
{
    private float _x, _y;

    public float X 
    { 
      [Readonly] get => _x; 
      set => _x = value; 
    } 

    public float Y
    { 
      [Readonly] get => _y; 
      set => _y = value; 
    } 

    [Readonly]
    public override string ToString() => $"({x}, {y})";

    [Readonly]
    public void AddOne() => (_x, _y) = (1 + _x, 1 + _y);   // Compilation error since it is marked as readonly.
}
```
So, the compiler would enforce at compile time that only the getters of Vector2C cannot change its state, and that, when calling operations like Add, only those getters can be called from its method (ditto for any other property or method not marked as readonly) ...

```csharp
public static float Add(in Vector2C left, in Vector2C right, out Vector2C result) 
{
    result = left + right; // pseudo-code.
    left.X = 5; // compilation error.
    var foo = right.ToString(); // ok
    var temp = left; // copy
    left.X = 5; // ok. 
}
```
This is not a proposal. I'm thinking out loud here to avoid defining immutable versions of existing structs (say, "public readonly struct ReadOnlyVector2"). Thoughts?

**Comment by svick** [comment]
There's already a proposal for this: https://github.com/dotnet/csharplang/issues/1710.

**Comment by CyrusNajmabadi** [comment]
> My question is, why cannot the compiler know whether a member method/property changes the state of a struct?

Because bodies of members aren't known to the compiler.  Consider that many/most types will come from metadata.  And that metadata may not even have bodies for the methods.  So there is truly nothing to examien to make this determination.  The compiler must be conservative to preserve semantics.  When you have a 'readonly struct' the compiler can see this in metadata and use this as proof positive that the implementer wanted the non-defensive-copying behavior.

> wouldn't be possible to do something like this?

Yes it would.  And this was something considered during the design of 'readonly structs'.  Namely that 'readonly-ness' could be specified at the member level.  At the time it was considered, but rejected, primarily because of complexity IIRC.  We wanted the language feature to be simple, even if it meant it couldn't handle cases like this.  AFAIK though, the idea was never outright rejected for the future.  It may be something that is reintroduced later if there is enough demand.  IIRC, instead of being attribute based though, it woudl be more like:

```c#
public void AddOne() readonly { ... }
```

See https://github.com/dotnet/csharplang/issues/1710 for more details.

**Comment by CyrusNajmabadi** [comment]
Oh, looks like latest thinking is that 'readonly' would be in the modifiers list: https://github.com/dotnet/csharplang/issues/1710#issuecomment-429992790   So ignore my example of it appearing after the signature.

**Comment by Ultrahead** [comment]
Thanks both for letting me know. Closing issue.
