### ISSUE TITLE
[Suggestion] Grave accent strings in C#

### ISSUE THREAD

**Issue by CreatorVilius** [dotnet/csharplang#2058]
What about using `` ` `` in C#?
What it would do you might ask?

There are 3 possible ways this would behave:

> ### \# 1
It would be same as `"`.
Imo, I don't like `"`, don't ask why.
That's why I always use `'` in JS.
I am trying to move from main language being JS(Node js to be specific), to C#.
I know all Strongly typed languages use `"` for string.
Having `` ` `` would make more acceptable to people who don't like ` " `.

Example:

```cs
public class RandomClass {
      public static string something = `Lorem ipsum`;
      public static string somethingElse = "Lorem ipsum";
      // Both are same
}
```

> ### \# 2

This would be more logical imo.
Make some special string.
For example, `@" "`, is well, special because you can't escape characters in it.
Making `` ` ` ``  special string would be kinda more logical really.
It could be template string, like in JS.

> ### \# 3

Probably most logical, it would be for new class which is similar to string.
For example, there is std::wstring in C++, which is slightly different than std::string.
Some sort of new string with new mechanics and making it use `` ` ` `` would be cool.
Of course, if you would be able to convert it to normal string.

So yeah, I know this suggestion is kinda bad, but hope you will read and use `` ` `` in C#.

**Comment by theunrepentantgeek** [comment]
> It would be same as ".

Using ` to replicate functionality we already have would introduce complexity for no benefit.

> Probably most logical, it would be for new class which is similar to string.

The multitude of different kinds of string is a constant source of pain and inefficiency in C++, for the API you want to call is often expecting a different kind of string to the one you have. 

Having just one **string** type is a (very, _very_) good thing.

One way that ` could be used would be to define symbols. There are a number of other languages where `red `green `blue are symbol values that can be passed around easily. They're not strings. 

But ... those languages tend to be weakly typed, so I'm not sure how this would work in C#.

**Comment by yaakov-h** [comment]
This sounds like a hammer in search of a nail.

**Comment by YairHalberstadt** [comment]
Perhaps, the best thing to do, would be to reserve the use of ` until the C# team thinks to themselves:

Hmm. There's this great feature we want to introduce, but we just need a decent syntax for it... I know! Let's use ` !

**Comment by CyrusNajmabadi** [comment]
For example, perhaps this could be how you'd write a utf8 string.  But i agree.  We shuld not have yet another syntax that means the same thing.  The amount of available syntax for new features is limited.  And we should only use that limited space for important things.

**Comment by willard720** [comment]
> Imo, I don't like ", don't ask why.

No, why? If you're gonna request such a pointless feature, back it up.

> I know all Strongly typed languages use " for string.

Therefore it is illogical to use anything else.

>This would be more logical imo.

None of these are logical. We're getting zero benefit. You're asking to create a new type of string, or a "special string" just because you don't like the semantics of `"`, which is very logical as in English, and other languages, we use `"` to describe "words" or "quotes people have said."

Another tiny issue with \` is that it isn't going to translate well into websites like Github or SO that use \` as a delimiter for code. 

For example, if I tried to say, 
`string foo = "foo"  + "bar"`, using \`, what I get is: 
`string foo = `foo` + `bar``

Which is unreadable. For that reason, `'` would make more sense, and because `'` is also used for quotes. 

Regardless, this feature is pointless. C# devs say that features have to be overwhelmingly positive to even be considered. This is not. I mean, what next? Do we need to \`, ", ' ~, ''', "", etc., so that everyone can use the flavor of strings that they want?

**Comment by jnm2** [comment]
`` ` `` is being considered for markdown-based documentation comments, I believe.
