### ISSUE TITLE
Allow leaving out generic parameters in nameof when accessing a member

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/csharplang#2064]
For example, instead of writing `nameof(List<int>.Count)` allow `nameof(List<>.Count)`.

And instead of writing `nameof(Dictionary<string, int>.Count)` allow `nameof(Dictionary<,>.Count)`.

### Use case

I was using reflection, and needed to make sure an object structurally matched part of an interface. The interface had a type parameter, so I was not able to use `nameof(Interface.Property)`.

Instead I tried to write `nameof(Interface<object>.Property)`.

However the interface had some generic constraints, which required me to make up some dummy types which matched the constraints, just so I could use nameof!

I understand that this is a rare scenario, and probably not worth changing the language for, but I thought I'd raise an issue anyway, in case other people also feel this would be useful.

**Comment by jnm2** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/702.

**Comment by jnm2** [comment]
Because type arguments are required, it's possible to prevent `nameof` from being usable at all if you add a generic constraints such as a base class with a private constructor together with an interface not implemented by the base class.

This is highly unusual, but it's also possible for `nameof` to force you to declare a type just to satisfy multiple generic constraints.

**Comment by YairHalberstadt** [comment]
Closing as duplicate
