### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by CreatorVilius** [dotnet/csharplang#2106]
[Deleted]

**Comment by HaloFour** [comment]
I'm thinking that the C# team kept the number of operators very small on purpose, to prevent C# from turning into an ASCII mess.  They even intentionally hobbled the overloadable `>>` and `<<` operators so that they couldn't be used to simulate C++ streams.  Aside from supporting mathematic operations between pseudo-numeric types I don't think that operators are the right way to go.

**Comment by johnkellyoxford** [comment]
These just seem pointless. Operators *do* something specific. `+` is addition. `<<` is a left shift, etc. They aren't just "arbitrary symbols" that can be overloaded. Semantically I see them primarily used only for value types as they are not virtual (but can be dynamically dispatched to emulate virtual behaviour).
*  Why use a cryptic, unnecessary grave operator when you can just use a method which has a descriptive name? 
* Also, you suggest this grave operator "can be static". ALL operator overloads are static. Your code wouldn't compile even with these operators, as it is not static. 
* Why have 2 operators which do the same thing, made more complex by the fact both are already symbols in the language? (`@` and `#`)
* Worth saying again because it's so important. Why!!? There's no reason to add them. Just more confusing and effectively useless

**Comment by willard720** [comment]
This is bad because I have no idea what any of your operators do. Can you imagine how unpredicatable the language would become if this code:

```csharp
public void DoFoo()
{
    var foo = new Foo();
    Console.WriteLine(foo.GetValue());

    var bar = foo.GetValue();
    bar.DoBar();
   
    var result = Foo.GetNumber() + Bar.GetNumber();
}
```

Turned into this:

```csharp
public void DoFoo()
{
    var foo = new Foo();
    Console.WriteLine(`foo);

    var bar = `foo;
    @bar;
   
    var result = ~Foo # Bar ~;
}
```

How are we supposed to know what's going on here?

Also, `@` is already in use to name a variable a preexisting keyword. You can make a field called `@this` and in the metadata it's name would be `this`. Why would you want to overload that?

When we overload, it's to add or expand the base functionality, such as this:

```csharp
public static Vector2 operator+ (Vector2 a, Vector2 b) => new Vector2(a.X + b.X, a.Y + b.Y);

...

var a = new Vector2(1, 2);
var b = new Vector2(2, 1);
var c = a + b;    // This == (3, 3);
```

It's predictable and we know what's going to happen. Having `foo@` is completely unreadable and inferior to `foo.DoSomething();` in every way besides time it takes to type (which isn't that important).
