### ISSUE TITLE
Question about Index Type

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#2140]
Hi All,
I just downloaded and started playing with .NET Core 3.0 and C# 8.0.  I have a question about the Index type.
```
var Items = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
var FirstItem = Items[0];  //This makes sense
var LastItem = Items[^0]; //This is Not Correct!
```

Why was the decision made that ^0 should exist after the last item in the array instead of at the last item in the array?  Using Indexes, how do you apply an offset?  For example, I want to do this:
````
            var Items = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
            for (int i = 0; i < Items.Length; i++) {
                var Match = Items[i] == Items[^i +1]; //<<------
            }
````

**Comment by orthoxerox** [comment]
@TonyValenti the way to recalibrate your intuition is to think of indices as pointing between the items. That's how Python explains its indexing system, for example:

```
 +---+---+---+---+---+---+
 | S | a | m | p | l | e |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
^6  ^5  ^4  ^3  ^2  ^1  ^0
```

**Comment by TonyValenti** [comment]
@orthoxerox 
Hmm.  Interesting.  I was hoping that the index notation would allow us to get rid of Count/Length -1.

**Comment by jnm2** [comment]
Along the same lines, another way to phrase it:

`0` means "don't skip any items before reading."
`1` means "skip one item before reading."
`^1` means "skip all but one item before reading."
`^0` means "skip all items before reading."

**Comment by YairHalberstadt** [comment]
For example, it would be ugly if the range operator for all items from i till the end  of the array was `i..^-1` as opposed to `i..^0`

**Comment by TonyValenti** [comment]
@YairHalberstadt Maybe that's what I'm missing.  I can imagine a lot of scenarios where I think ^0 should be the last item and I can't think of any where I feel it should throw an exception.  Can you share a brief example?  I think that would really help me out.

**Comment by YairHalberstadt** [comment]
@TonyValenti
I shared an example above:

> For example, it would be ugly if the range operator for all items from i till the end of the array was i..^-1 as opposed to i..^0

**Comment by TonyValenti** [comment]
Would you put a small snippet showing a full block?
Tony Valenti

Schedule a meeting with me <https://Fasterlaw.com/schedule-meeting>

**Comment by Joe4evr** [comment]
I know, right? I've been trying to get the team to change their mind and make the counting symmetrical with normal indexing [since their first public demo](https://github.com/dotnet/csharplang/issues/185#issuecomment-388573976).
> ```
>  +---+---+---+---+---+---+
>  | S | a | m | p | l | e |
>  +---+---+---+---+---+---+
>  0   1   2   3   4   5   6
> ^6  ^5  ^4  ^3  ^2  ^1  ^0
> ```

The hole in this argument is that if you're indexing backwards, your reading direction is, in my view, logically also right-to-left. Hence, `^0` actually *is* the last element, not beyond it.

Needing the last element to be `^1` just makes me cry:
![](https://camo.githubusercontent.com/44219f89c19e79b8f715229e3f33d6a15e690c07/68747470733a2f2f692e696d6775722e636f6d2f714854743954642e706e67)

**Comment by TonyValenti** [comment]
@Joe4evr 
AGREED!

**Comment by jnm2** [comment]
> The hole in this argument is that if you're indexing backwards, your reading direction is, in my view, logically also right-to-left.

You've said this before and I meant to engage you on this. I don't buy the argument that you'd be reading backwards after skipping all items. Reading a single element is always done in a forward direction. Imagine an array of multi-byte structs. Reading an element backwards wouldn't make sense. it's more consistent to consider indexing to be forward-only: skip all but one, then read one.

**Comment by Korporal** [comment]
> @Joe4evr
> 
> > The hole in this argument is that if you're indexing backwards, your reading direction is, in my view, logically also right-to-left.
> 
> You've said this before and I meant to engage you on this. I don't buy the argument that you'd be reading backwards after skipping all items. Reading a single element is always done in a forward direction. Imagine an array of multi-byte structs. Reading an element backwards wouldn't make sense. You'd get the bytes scrambled for that element. It's more consistent to consider indexing to be forward-only: skip all but one, then read one.

@jnm2 

Accessing an array element isn't 'reading' nor is there any 'direction' use of these misleading terms only clouds the discussion.

**Comment by jnm2** [comment]
@Korporal On what basis can you say that it is misleading to call array access 'reading'?

As for direction, the indexing order itself implies the forward direction.

**Comment by jnm2** [comment]
@Korporal On what basis can you say that it is misleading to call array access 'reading' (or 'writing')?

**Comment by TonyValenti** [comment]
@jnm2 -
I think @Korporal's use of misleading might be been a bit strong, but I understand what he means.  Reading/writing implies a direction.  When you read a book, you start at the beginning and turn pages.  When you read a stream, you start at the beginning and move toward the end.  With you read an enumerator, you start at the beginning and continue until the end.  Etc.

Arrays are, by their nature, random access and both read and writable.  Because of that, when people talk about arrays, it makes more sense to say "accessing" or "accessing from".  For example, I would argue that array[0] should be read "I am accessing the 0th element from the start" (the very first item) and that array[^0] should be read "I am accessing the 0th element from the end".

I still don't understand why it was determined that array[^0] should throw an exception.  I strongly believe that should be the last element in the array.

**Comment by jnm2** [comment]
I hope that the folks doing demos and documentation really capitalize on terminology like this which most intuitively matches what indexes *do*. The language in which the feature is introduced can set folks up for certain ideas and expectations.

**Comment by CyrusNajmabadi** [comment]
There are pros and cons to both forms of indexing.

That said, the Roslyn team (and, tansitively, the C# LDM members) have had a *ton* of experience with both sorts of indexing and have come to prefer that the default form be the one that System.Index/System.Range follows.  As you can imagine, both IDEs and compilers need to express these concepts *a lot*.  We've had approaches in the past where either or both sorts of forms were supported.  However, in the end, the form picked as the default was the one most universally consistent and useful.

Personally, i would like there to be a way to express the other form, for people who find that intuitive.  Similarly, i'd like an easy way to define inclusive instead of exclusive ranges.  That said, such features are orthogonal and can be done in an additive manner at some point in the future.  So, i think it's totally fine for the LDM to pick an initial set of types/semantics to start with, then reassess in the future if there is a need to expand on things further.

**Comment by TonyValenti** [comment]
@jnm2 -
Thank you!  Reading ^x as "Skip all but x" really helps me understand it better.

**Comment by HaloFour** [comment]
C# is basically copying the behavior of languages that support negative indexes to read from the end, except that they can't use negative indexes as that already means something in both C# and the BCL.

```python
list = range(10) # [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
last = list[-1] # 9
slice = list[5:-1] # [ 5, 6, 7, 8 ]
slice = list[5:] # [5, 6, 7, 8, 9 ]
```

```cs
int[] array = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
int last = array[^1]; // 9
Span<int> span = array[5..^1]; // { 5, 6, 7, 8 }
Span<int> spanToEnd = array[5..^0]; // { 5, 6, 7, 8, 9 }
```

**Comment by Thaina** [comment]
Personally I don't like this syntax because we can't argumentizing the negative index cleanly

```C#
int i = await IndexFromServer(); // -1
array[i]; // throw exception
array[i >= 0 ? i : ^(-i)]; // is the same as next line just save some spaces
array[i >= 0 ? i : ((array.Length + i) % array.Lenth)];
```

**Comment by Korporal** [comment]
> That's a good point. I'll keep in mind that element access should be thought of as atomic.
> 
> > I am accessing the 0th element from the end
> 
> Zeroth is not a natural concept. "First from the end" is what we say. Zero-based indexes aren't naturally thought of as labels for each element (that's one-based indexes); zero-based indexed are naturally in terms of distance. I think we might agree there, so the question comes back to this:
> 
> ➡ After finding the point between elements naturally described by `[x]` or `[^x]`, is the existing convention of reading forward inherent to the single-item indexing syntax itself (`[` and `]`), or is the convention flipped if the index passed to the indexer is a from-end index (`^`)?
> 
> I see pros and cons to both. No matter which one you pick, you will have to do by-one corrections in a large set of scenarios. I'm not sure which set is larger, but don't be mistaken and think that one of these choices makes off-by-one go away.
> 
> Also, each way of thinking about it has a powerful mnemonic that will keep you on the right track once this is part of the language and you have to deal which whichever way it is.
> 
> For the language design team's current choice:
> 
> * `x` means "skip `x` elements"  (implies forward direction)
>   `^x` means "skip all but `x`" (implies forward direction)
> 
> If they change their minds:
> 
> * `x` means "distance from start" (implies forward direction)
> * `^x` means "distance from end" (implies backward direction)
> 
> I suspect I'll be doing less by-one math with the team's current choice because that's what I gather that their own conclusions were (from what I've read). But either way, I know I'll be able to emphasize the most useful mindset and make the most of it.
> (Because of this, I'm not really invested in the outcome. I'm more invested in fending off FUD by showing how usable each alternative really is.)



> C# is basically copying the behavior of languages that support negative indexes to read from the end, except that they can't use negative indexes as that already means something in both C# and the BCL.
> 
> Python:
> 
> ```python
> list = range(10) # [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
> last = list[-1] # 9
> slice = list[5:-1] # [ 5, 6, 7, 8 ]
> slice = list[5:] # [5, 6, 7, 8, 9 ]
> ```
> 
> C# vNext:
> 
> ```cs
> int[] array = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
> int last = array[^1]; // 9
> Span<int> span = array[5..^1]; // { 5, 6, 7, 8 }
> Span<int> spanToEnd = array[5..^0]; // { 5, 6, 7, 8, 9 }
> ```

@HaloFour - An array index is (typically) an offset, the offset of the desired element from the 'base' address of the array. That's why the 'first' element has an index of zero - zero byte offset from the base address. 

Therefore it's entirely logical to use 'index' in the reverse manner, the 'last' element having a zero byte offset from the end address (address of the last, (highest address) element.

The way it's been done is frankly horrible and counter intuitive.

**Comment by jnm2** [comment]
@Korporal Yes, an offset is the same thing as a distance. See "If they change their minds:" in my comment above. You're entitled to that conclusion, but it's not at all a convincing or practical stance to me.

Also, you credited me with @HaloFour's comment. It's probably not necessary to copy our comments. Would you please remove or clarify attribution? Thanks!

**Comment by CyrusNajmabadi** [comment]
> and counter intuitive.

Seems very clean and intuitive to me FWIW :)  Perhaps there are just multiple ways to think about the problem, and any solution will not necessarily be the best fit for all perspectives here?

**Comment by CyrusNajmabadi** [comment]
> Personally I don't like this syntax because we can't argumentizing the negative index cleanly `int i = await IndexFromServer(); // -1`

What is the scenario where the server is providing negative indices?


Also... if you are getting negative indices to represent wrap-around, then you don't really need system.index.  just do a simple `foo[(foo.Length + index) % foo.Length]` to put it back in bounds.  this works for positive or negative values (up to negative foo.Length).  

That said, it's not clear under what circumstances you actually need this.  Do you have APIs you're calling that actually return negative values to indicate wrap-around?  If so... can they not be updated to just do the wrap-around logic themselves?

**Comment by Korporal** [comment]
> > and counter intuitive.
> 
> Seems very clean and intuitive to me FWIW :) Perhaps there are just multiple ways to think about the problem, and any solution will not necessarily be the best fit for all perspectives here?

@CyrusNajmabadi 

There are indeed various way, and symmetry is a highly desirable trait in such things. The concept of "first being an offset of zero from the beginning" and "last being an offset of zero from the end" strikes me as fundamentally the simplest and most symmetrical way to do this and is probably what most developers would assume.

The increasing level of idiosyncrasy we're seeing in the language concerns me and you risk making the language harder and harder to work with.

**Comment by CyrusNajmabadi** [comment]
> There are indeed various way, and symmetry is a highly desirable trait in such things

It's symmetrical to me, and works in an intuitive manner given the "this is the location at which to start reading" perspective.  This interpretation is a common way that i've seen people thinka bout things for decades:

```
 +---+---+---+---+---+---+
 | S | a | m | p | l | e |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
```

That's the benefit of 0-indexing.  When you say `a[0]` (in C languages especially) it's literally saying "the location pointed at by 'a' plus the zero-times-the-length-of-your-elements".  "Accessing" is then just going to that locatoin and reading out "one-times-the-length-of-your-elements" starting from that position.  

In this interpretation (which is common, and seen across a wide set of languages), the `^` indexing intuitively slots in (no pun intended) :)

> strikes me as fundamentally the simplest and most symmetrical way to do this and is probably what most developers would assume.

Fortunately, from talking to developers and communicating and seeing what the rest of the industry is doing, that doesn't seem to be the case.  Your view is certainly not isolated.  But it also doesn't seem to be predominant.  

 >The increasing level of idiosyncrasy we're seeing in the language concerns me and you risk making the language harder and harder to work with.

Then don't use it.  The goal isn't to make the ideal language for Hugh Gleaves.  the goal is to provide substantive value to the entirety of the C# ecosystem for the types of problems it is commonly facing.  The LDM feels this language proposal fits into that mindset.  

As mentioned before, if you want to wax philosophical about this stuff, then these *closed* issues are likely not the right place to do so.  Feel free to come over to gitter which is more oriented toward that sort of discussion.

**Comment by TonyValenti** [comment]
Given the list below:
````
int[] array = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
int last = array[^1]; // 9
Span<int> span = array[5..^1]; // { 5, 6, 7, 8 }
Span<int> spanToEnd = array[5..^0]; // { 5, 6, 7, 8, 9 }
````

I would say that I agree with everything except for the second item:
````
int last = array[^1]; // 9
````

Which I feel should be:
````
int last = array[^0]; // 9
````

**Comment by YairHalberstadt** [comment]
@TonyValenti
Given that the `a..b` syntax means 
"From `a` inclusive till `b` exclusive"
Your desired meaning for `int last = array[^0];` is at odds with your desired meaning for `Span<int> spanToEnd = array[5..^0];`
You cannot have your cake and eat it too

**Comment by CyrusNajmabadi** [comment]
A good example of why i like it is that this makes total sense now:

`[0..^0]`.  This would be a range that gives you the *entirety* of the original.  If `^0` actually pointed at the last element, then this would give you all the elements but the last one.  and `[0..^1]` would give all but the last two.  To get all teh way to the end, you'd need something like `[x..^-1]`.

**Comment by TonyValenti** [comment]
It seems that if there was a .. (exclusive) and ... (inclusive) operator, it would take care of this.

**Comment by Korporal** [comment]
@CyrusNajmabadi 

> > There are indeed various way, and symmetry is a highly desirable trait in such things
> 
> It's symmetrical to me, and works in an intuitive manner given the "this is the location at which to start reading" perspective. This interpretation is a common way that i've seen people thinka bout things for decades:
> 
> ```
>  +---+---+---+---+---+---+
>  | S | a | m | p | l | e |
>  +---+---+---+---+---+---+
>  0   1   2   3   4   5   6
> ```
> That's the benefit of 0-indexing. When you say `a[0]` (in C languages especially) it's literally saying "the location pointed at by 'a' plus the zero-times-the-length-of-your-elements". "Accessing" is then just going to that locatoin and reading out "one-times-the-length-of-your-elements" starting from that position.

Why you said that I don't know because my remarks so far have been **emphasizing** 0-indexing but for **both** first and last When using `^ `operator) elements.

> 
> In this interpretation (which is common, and seen across a wide set of languages), the `^` indexing intuitively slots in (no pun intended) :)
> 
> > strikes me as fundamentally the simplest and most symmetrical way to do this and is probably what most developers would assume.
> 
> Fortunately, from talking to developers and communicating and seeing what the rest of the industry is doing, that doesn't seem to be the case. Your view is certainly not isolated. But it also doesn't seem to be predominant.

It's bizarre Cyrus to say [0] refers to the element at offset 0 from the start but [^1] refers to the element at offset 0 from the end, tell me how that's symmetrical?

> 
> > The increasing level of idiosyncrasy we're seeing in the language concerns me and you risk making the language harder and harder to work with.
> 
> Then don't use it. The goal isn't to make the ideal language for Hugh Gleaves. the goal is to provide substantive value to the entirety of the C# ecosystem for the types of problems it is commonly facing. The LDM feels this language proposal fits into that mindset.

I will use it, simply because I am critical of some of what I see doesn't automatically mean I have to stop using the language, these are my opinions take it or leave it.

> 
> As mentioned before, if you want to wax philosophical about this stuff, then these _closed_ issues are likely not the right place to do so. Feel free to come over to gitter which is more oriented toward that sort of discussion.

There you go again changing the subject. I'm expressing an informed opinion Cyrus not "waxing philosophical" its to be expected that we may disagree from time to time, get over yourself.

**Comment by HaloFour** [comment]
@Korporal 

> It's bizarre Cyrus to say [0] refers to the element at offset 0 from the start but [^1] refers to the element at offset 0 from the end, tell me how that's symmetrical?

Because neither refers to the element, they refer to the position which would be between the elements.  If you're at position 0 it's illegal to read backwards.  If you're at position ^0 it's illegal to read forwards.  That is symmetrical.

**Comment by jnm2** [comment]
@Korporal Would you please fix your earlier comment as I asked in https://github.com/dotnet/csharplang/issues/2140#issuecomment-455223801?

> tell me how that's symmetrical?

It's getting to be obvious that you haven't absorbed the information in this thread. You are not making much of an attempt to listen to at least four folks in this thread who have patiently explained the symmetries, and your tone which was initially abrasive is turning personal. You have already stated your opinion, and we can see what information you did and did not take into account when you did so. Please leave it at that. If you have questions that you can't figure out by reading the thread, please hop over to https://gitter.im/dotnet/csharplang and we will be happy to answer them in good faith.

**Comment by CyrusNajmabadi** [comment]
> It seems that if there was a .. (exclusive) and ... (inclusive) operator, it would take care of this.

Indeed.  However, as i've mentioend above, the latter doesn't have to ship along with the former.  An inclusive form can always come *down the line* if it turns out it's valuable enough of there's enough demand for it.

The LDM is *very* aware of this and made a specific decision to place that 'out of scope' *for now*.  Nothing prevents it from coming in the future.  But they're starting with what is felt to be a minimal viable approach that doesn't restrict what might be desirable in the future.

**Comment by CyrusNajmabadi** [comment]
> Why you said that I don't know

Because you said it's not symmetrical and it's idiosyncratic.  I'm pointing out that that's not the case for me because i can see the perspective that leads to this being isometrically and regular, and that perspective jives with how C-style languages have commonly explained indexing, and how many other languages do it as well.

You seem to be under the impression that everyone either sees things your way, or that they should be seeing things your way.  I'm pointing out there are other valid ways of looking at this space that make the current approach make total sense in an entirely consistent manner.

**Comment by CyrusNajmabadi** [comment]
> It's bizarre Cyrus to say [0] refers to the element at offset 0 from the start but [^1] refers to the element at offset 0 from the end, tell me how that's symmetrical?

Simple, in the C branch of languages, something like an array is actually a memory location in space somewhere.  So, `array` is just that beginning location.  indexing into that array is basically saying: take that memory location and move forward (we'll ignore negative indices on the array for now), some number of element-size locations.

So `array[0]` is saying "give me the location of the array plus 0 jumps forward" and `array[x]` is "give me the location of the array plus x jumps forward".

An array is effectively a chunk of memory that has this starting point, and an ending point (which is array+length*element-size).  So, just as `array[0]` maps cleanly right to the start of htat memory, defining `array[^0]` to be the *end* location of the array is nicely symmetrical with that as well.  

`array[^n]` now means `go to the end of the array, and walk *backward* (instead of forward) `n` element sizes.  

--

Now, once you have this as the intuition for memory and indexing, it naturally maps out to any sort of collection/indexable api.

**Comment by CyrusNajmabadi** [comment]
> There you go again changing the subject. I'm expressing an informed opinion Cyrus not "waxing philosophical" its to be expected that we may disagree from time to time, get over yourself.

You seem to be under the impression that those who made this decision were not informed.  But that's not the case at all. This was actually researched extensively, and strong and clear arguments were made for why this was a preferred and ultimately more consistent approach than the other proposed options.

**Comment by CyrusNajmabadi** [comment]
Just saw @jnm2 's response.  I agree with him.  This discussion seems to be going in circles.  If you want to continue the discussion, gitter would be far more effective/fruitful.
