### ISSUE TITLE
Range based loop like in C++ (foreach shorter syntax)

### ISSUE THREAD

**Issue by lust666** [dotnet/csharplang#2183]
https://en.cppreference.com/w/cpp/language/range-for

it would be easier to write things:

`foreach (var player in players)` vs `for (var player : players)`

**Comment by kkravtsov** [comment]
Ha-ha

**Comment by YairHalberstadt** [comment]
Why is one easier than the other?

The only difference  I can  see  is that you save a total of 5 characters. But the language does not have any aim of saving characters so that's irrelevant.

On the other hand, the language does have an aim of not introducing two different ways of doing the same thing unless there is a very good reason.

What is the good reason for this?

I have heard developers complain about many things. Not once have I heard them complain that foreach was to difficult to write!

**Comment by lust666** [comment]
> Why is one easier than the other?
> The only difference I can see is that you save a total of 5 characters. But the language does not have any aim of saving characters so that's irrelevant.
> What is the good reason for this?

It's not easier but faster to write, and less words to read. Just my opinion though.

**Comment by YairHalberstadt** [comment]
@lust666
Typing speed is rarely a limiting factor in software development. So long as a name isn't unwieldy, it's short enough.

As for reading, most C# developers are so used to the current syntax that anything new would have the same effect on them as branch misprediction does on a processor.

On the other hand concept count is a very real limiting factor when learning a new language, and having two syntaxes to do the identical thing unnecessarily increases concept count.
