### ISSUE TITLE
Implicit var in foreach

### ISSUE THREAD

**Issue by Thorusus** [dotnet/csharplang#2184]
What if `var` was redundant (implicit) in foreach?:

```csharp
foreach (foo in foos) // look how easy it is for eyes to read
{
  //...
}
```

See: https://haxe.org/manual/expression-for.html (haxe supports var too, but you can write for loops without var)

**Comment by YairHalberstadt** [comment]
There are three separate proposals here.

1. Make var optional in foreach
2. Allow for to be used wherever foreach is currently allowed.
3. Add a range syntax `...`

I suggest you stick to just the first in this issue, and move the other two to seperate issues, so that each can receive the attention it deserves.

**Comment by lust666** [comment]
@YairHalberstadt range syntax is already tracked here: https://github.com/dotnet/csharplang/issues/198

**Comment by johnkellyoxford** [comment]
A few things:
* It is inherently different to everything else. `var` is effectively saying 'Type I can't be bothered to write', which maintains the idea of a declaration as roughly the syntax `<type> <name> [= <value>];`. By saying you don't need to do this it just muddys the water and makes what is a declaration less clear

* Pretty much useless. 3 letters aren't that much and most IDEs will have a shortcut for it anyway
