### ISSUE TITLE
'ref structs' with 'ref fields' for consolidating 'ref locals'

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#2191]
When working with geometric algorithms, there is a need for reusing heap memories (arrays of int, double, vectors) for intermediate calculation ... across algorithms.

The awesome 'ref local' feature make the code cleaner by allowing the contextless shared heaps to be mapped with named 'ref local' ...
```csharp
ref Vector3[] vertices = ref context.vector3_3;
ref int[] triangles = ref context.int32_1;
```
... with such scenario, we are wondering if **ref struct** can be extended to take 'ref local' as to **consolidate** bunch of 'ref locals' (or, ref params) into a single struct, allowing a set of 'ref locals' to be passed (as one) to next level stack calls ...
```csharp
private ref struct Struct1
{
    public ref int[] data1;
    public ref int[] data2;
    public Struct1(ref int[] data1, ref int[] data2)
    {
        this.data1 = data1;
        this.data2 = data2;
    }
}

...

ref int[] local1 = ref array1;
ref int[] local2 = ref array2;
Struct1 obj = new Struct1(ref local1, ref local2);

...
```
Here's an example of our current usage scenario ...
```csharp
public class SharedContext
{
    public int[] int32_1;
    public int[] int32_2;
    public int[] int32_3;
    public int[] int32_4;
    public Vector3[] vector3_1;
    public Vector3[] vector3_2;
    public Vector3[] vector3_3;
    public Vector3[] vector3_4;
}

public class Mesh
{
    public int VertexCount { get; }
    public int TriangleCount { get; }
}

public static class Sample1
{
    public static void Process(Mesh mesh, SharedContext context)
    {
        // ... mapping to named context, reuse existing heap ..
        ref Vector3[] vertices = ref context.vector3_3;
        ref int[] triangles = ref context.int32_1;
        ref int[] hull = ref context.int32_2;
        ref Vector3[] temp = ref context.vector3_4;

        Extract(mesh, ref vertices, ref triangles);
        Subdivide(ref vertices, ref triangles, ref hull);
        Smooth(vertices, triangles);
        // ... do something ...
    }

    private static void Extract(Mesh mesh, ref Vector3[] vertices, ref int[] triangles)
    {
        // ... just to show heap (re)allocation" requirement ...
        int vertexCount = mesh.VertexCount;
        int triangleCount = mesh.TriangleCount;
        if (vertices == null || vertices.Length < vertexCount) vertices = new Vector3[vertexCount];
        if (triangles == null || triangles.Length < triangleCount) triangles = new int[triangleCount];
        // ... copy mesh stuffs into "vertices" and "triangles" ...
    }

    private static void Subdivide(ref Vector3[] vertices, ref int[] triangles, ref int[] hull)
    {
        // ... just to show "heap (re)allocation" requirement ...
        int hullSize = 100, vertexMax = 1000, triangleMax = 3000;
        if (hull == null || hull.Length < hullSize) hull = new int[hullSize];
        if (vertices.Length < vertexMax) vertices = new Vector3[vertexMax];
        if (triangles.Length < triangleMax) triangles = new int[triangleMax];
        // ... do something ...
    }
    ...
}
```
... and, if 'ref field' are allowed in 'ref struct', the code can be refactored as follow ...
```csharp
public static class Sample2
{
    private ref struct MeshObj
    {
        public ref Vector3[] vertices;
        public ref int[] triangles;
        public ref MeshObj(ref Vector3[] vertices, ref int[] triangles)
        {
            this.vertices = vertices;
            this.triangles = triangles;
        }
    }

    public static void Process(Mesh mesh, SharedContext context)
    {
        // ... mapping to named context, reuse existing heap ..
        MeshObj obj = new MeshObj(
            vertices: ref context.vector3_3,
            triangles: ref context.int32_1
            );
        ref int[] hull = ref context.int32_2;
        ref Vector3[] temp = ref context.vector3_4;

        Extract(mesh, ref obj);
        Subdivide(ref obj, ref hull);
        Smooth(ref obj);
        // ... do something ...
    }

    private static void Extract(Mesh mesh, ref MeshObj obj)
    {
        // ... just to show "heap (re)allocation" requirement ...
        int vertexCount = mesh.VertexCount;
        int triangleCount = mesh.TriangleCount;
        if (obj.vertices == null || obj.vertices.Length < vertexCount) obj.vertices = new Vector3[vertexCount];
        if (obj.triangles == null || obj.triangles.Length < triangleCount) obj.triangles = new int[triangleCount];
        // ... copy mesh stuff into "obj.vertices" and "obj.triangles" ...
    }

    private static void Subdivide(ref MeshObj obj, ref int[] hull)
    {
        // ... just to show "heap (re)allocation" requirement ...
        int hullSize = 100, vertexMax = 1000, triangleMax = 3000;
        if (hull == null || hull.Length < hullSize) hull = new int[hullSize];
        if (obj.vertices.Length < vertexMax) obj.vertices = new Vector3[vertexMax];
        if (obj.triangles.Length < triangleMax) obj.triangles = new int[triangleMax];
        // ... do something ...
    }
    ...
}
```

Thank you, and thanks so much for 'ref local' !

**Comment by svick** [comment]
> When working with geometric algorithms, there is a need for reusing heap memories (arrays of int, double, vectors) for intermediate calculation ... across algorithms.

I don't understand how `ref` helps you with that. An array is already a reference type, I don't see how adding another level of indirection on top of that  by having a `ref` to an array helps.

**Comment by SarahLee2k** [comment]
> > When working with geometric algorithms, there is a need for reusing heap memories (arrays of int, double, vectors) for intermediate calculation ... across algorithms.
> 
> I don't understand how `ref` helps you with that. An array is already a reference type, I don't see how adding another level of indirection on top of that by having a `ref` to an array helps.

(I have the feeling that I might had mislead you guys with the lengthy post, And, here comes another one.  Sorry!)

Just to make sure, the **ask** here is 'ref field' in **Ref Struct**.  The 'mapping' can already be done in C# 7.3.

Regarding the question.  Yes functionally, it makes no difference.  Syntactically, it's crazy ... in term of **code readability** and **maintenance**.  C# 7.3 'ref local' eases the problem.  Here's an example ...

Before 7.3, we used to do what **MkazemAkhgary** noted.  Now, imagine 50+ of those lines, in a single host method.  It's also a common task to switch 'temp array' during perf tuning.  These, make direct referencing of the generic names (ex: context.int32_1) error prone.

To reduce dev cost (before 7.3), we opted to align each of those 'temp array' to a named local variable (when local access is needed) ...

```csharp
int[] triangles = context.int32_1
```

... and use the named variables instead of (ex: context.int32_1, main holder of the heap).
But, this requires the remapping of the local variables if helper method (ex: Extract) resizes the array ...

```csharp
Extract(mesh, ref context.vector3_3, ref context.int32_1);
// ... remap, as 'triangles' holds old array if 'Extract()' resized 'int32_1' ...
triangles = context.int32_1;
```

... and if 'triangles' is resized', it needs to 'map back' ...

```csharp
ResizeMe(ref triangles, 1000);
context.int32_1 = triangles;
```

With (7.3) 'ref local', and mapping to 'ref int[] triangles', 'triangles' array can be used without caring where the heap is.

The style (without 7.3) is essentially the same as wrapping an extra method call.  For example ...

```csharp
public static void Process(Mesh mesh, SharedContext context)
{
    ProcessInner(
        mesh,
        ref context.vector3_3,
        ref context.int32_1,
        ref context.int32_2,
        ref context.vector3_4);
}

private static void ProcessInner(
    Mesh mesh,
    ref Vector3[] vertices;
    ref int[] triangles;
    ref int[] hull;
    ref Vector3[] temp)
{
    ...
}
```

... though doing such style all over the place is not ideal.

With both styles, the problem remains which is the **ask** here.   To **reduce** (syntactically) number of **params** in method call and enabling structural context grouping ... via **Ref Struct** (avoiding heap promotion).

Thanks!

**Comment by MkazemAkhgary** [comment]
note that your SharedContext is not thread safe especially if you try to resize the arrays. 

Could you explain why you have 4 pair of arrays of int and Vector3? sharing and reducing the memory usage is reasonable for your problem, but there are other patterns that may work better in your case. I think your actual problem is the current design and you are probably trying to adopt with a wrong design.

I'm not saying i can give you a better solution. but I'm sure others can.

**Comment by svick** [comment]
@SarahLee2k I apologize, I read what you wrote, but didn't really look at the code, so I didn't realize you need reallocation, which indeed makes `ref` arrays useful.

What I still don't understand: Why are you using a `ref` array instead of a class that contains the array as a field? That class could be very similar to `List<T>`. Doing that should give you the advantages of using `ref` array (like being able to reallocate) in current version of C#. It would cause some additional allocations for instances of the class, but I think that shouldn't be a problem, because you would have just a few of them.

**Comment by SarahLee2k** [comment]
> note that your SharedContext is not thread safe especially if you try to resize the arrays.

Thanks for the observation.

Sorry, looks like the naming might had mislead you.
So, the **Shared** in this context is **across methods** within a thread, not across threads.

For example,
Imagine 100,000 meshes to be processed, in a machine with 10 cores.
10 threads will be created (aligning 1 thread per core).
Each thread with it's own 'SharedContext' instance, processing 10,000 mesh each.
 
> Could you explain why you have 4 pair of arrays of int and Vector3? sharing and reducing the memory usage is reasonable for your problem, but there are other patterns that may work better in your case. I think your actual problem is the current design and you are probably trying to adopt with a wrong design.

First of all, note that this is not a style we use for stuffs that are **heavy** (web services, database, processing text). It's only for performance critical area or avoiding GC is required.

The idea of **int[]** is that, it is kind of **structure-less**.  So they can be reused as different other type of data structure that are primary of **indexer family** (stack, queue, min-heap, binary-tree, ...) linking the actual geometry data (vertices)

The **style** is basically **inside out** compare to **OOP** ...

For example, instead of ...
    
```csharp
    List<int> list = new List<int>(1000);
    ...
    list.Add(j)
```
... it becomes ...
```csharp
    ref int[] stack_array = ref context.int32_1
    Stack.Init(ref stack_array, capacity:1000)
    ...
    Stack.Push(ref stack_array, j)
```
... where 'stack_array[0]' holds the count. And then later, the same int[] can be reused as 'stack' or 'min-heap'.

It's just an implementation **style**. :-) Like, how the **world of Linq** looks like **SQL**, **ref** looks like **old C function** without pointers.

**Comment by SarahLee2k** [comment]
> What I still don't understand: Why are you using a `ref` array instead of a class that contains the array as a field? That class could be very similar to `List<T>`. Doing that should give you the advantages of using `ref` array (like being able to reallocate) in current version of C#. It would cause some additional allocations for instances of the class, but I think that shouldn't be a problem, because you would have just a few of them.

The short answer: The **reason** is more about **style** than overcoming technical shortcomings.
It's the **world of Ref** vs **world of OOP**.

For some of us, who are **performance obsessed** and bunch of **memory control freaks** :-), 
the usage of **ref** (alternative to unsafe pointer) keeps us in-check of being aware about cache misses, memory alignment, stack vs heap .. in perf critical area.  Some, goes as further as not using 'class' at all and only 'struct'.  I'm not there yet :-)

Yes, the 'memory reusing stuff' can be done in OOP, without ref.  Something like the following (as you'd mentioned) ...
```cSharp
public class Buffer<T>
{
    private T[] data;
    public T[] Data => this.data;
    public void FitSize(int size) ...
}

public class SharedContext
{
    public readonly Buffer<int> int32_1;
    ...
    public readonly Buffer<Color> color_1;
    ...
}
```
... then usage ...
```cSharp
Buffer raw = content.color_1;
raw.FitSize(w * h);
image.CopyTo(raw.Data, w, h);
// ... iterate 'raw.Data' elements (or unsafe + lock) ...
```
But respectfully, from **ref world** point of view, we also ask : why the extra instance levels, when you can get to the memory directly and nothing is **intermediately hidden** (reminder: *bunch of control freaks*) :-)

It's very exciting to see C# is continuing to expand features allowing closer access to memory ... without pointer.

**Comment by MkazemAkhgary** [comment]
you may look for array pooling implementations in c#. there is a `ArrayPool` in c# already that might help you out. (basically you want to follow object pool pattern)

In summary you will rent part of a big array for temporary use and once you are done you will return that array to the pool so it may be used later. renting and returning arrays are also thread safe (you can rent from multiple threads at the same time.)

**Comment by svick** [comment]
@SarahLee2k 

>  The reason is more about style than overcoming technical shortcomings.
It's the world of Ref vs world of OOP.

If it's really just a matter of style, and the same thing could be achieved in C# today with practically the same performance, then I don't thing it's worth changing the language for this.

> But respectfully, from ref world point of view, we also ask : why the extra instance levels, when you can get to the memory directly and nothing is intermediately hidden

If you expose the array as a `public` field, then you're not actually hiding anything. You *want* a level of indirection. And sure, `class` is a more complicated indirection than `ref`, but it doesn't have to be by much, if the `class` is very simple.

**Comment by SarahLee2k** [comment]
> you may look for array pooling implementations in c#. there is a [`ArrayPool`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1.shared?view=netcore-2.2) in c# already that might help you out. (see [object pool pattern](https://en.wikipedia.org/wiki/Object_pool_pattern))
> 

Thanks for the link.

It appears ArrayPool is only available for **.NET Core** (we are restricted to .NET Framework).
Though we did consider some kind of memory manager (either outsourced or inhouse built).  But, after analysis, it provided minimum gains for the specific requirements.

For example, stuffs like ArrayPool (maintaining a pool of **dynamic size** object), requires **search**
when acquiring the object of specific size.  As well as, there is **not guarantee** you get the **same objects** (in **same order**) as last frame (if repeated execution is required).  Without such guarantee, overtime, all pooled arrays will likely converge into approximately the same size .. or worse, over allocating.

It's perfectly ok using ArrayPool (or other mem manager), if it fits your application.
At the end, it's all about how much control you are willing to give up in exchange for certain conveniences.
**Primitive arrays** approach is also not perfect in general, it just perfect for us in particular scenarios.

Btw, how would something like ArrayPool helps with **reducing ref parameters** (the **ask** here)?

**Comment by SarahLee2k** [comment]
> If it's really just a matter of style, and the same thing could be achieved in C# today with practically the same performance, then I don't thing it's worth changing the language for this.

Thanks for your input.

There are obviously perf gained using **ref** approach. I just didn't want to end up doing a powerpoint about it. :-)

The reason I came to observe and thought of proposing **extending ref struct** for **ref local**, as it seems like a logical extension.  And, if such feature becomes available, code can be simplified further (hopefully, retain perf) for those devs using **ref** as their approaches.

At the end, just like any features since C# 3.0, this is just another **nice to have** feature if implemented. :-)

> If you expose the array as a `public` field, then you're not actually hiding anything. You _want_ a level of indirection. And sure, `class` is a more complicated indirection than `ref`, but it doesn't have to be by much, if the `class` is very simple.

Btw, once the field is exposed (allowing field to be **set**), the wrapper class (ex: Buffer) loses it's point.
As, there is **not guarantee** the buffer instance will hold the **latest heap** ... So, somewhere alone the code path, *someone* will likely make use of 'ref local' (or ref param, or *back and forward assignments*).

That's why I thought that, if I was to take the **non-ref** route, I would encapsulate 'resize' and only expose for 'write'.

Btw, I'm not actually disagreeing with your approach. :-) I'm just trying to let you see that, the **primitive array** approach was a **conscious** and **intentional** trade off of good design for perf, in an isolated problem domain.
So, thank you for your thoughts.

**Comment by yaakov-h** [comment]
> It appears ArrayPool is only available for **.NET Core** (we are restricted to .NET Framework).

@SarahLee2k: `ArrayPool<T>` is available in .NET Framework 4.5 and higher, thanks to [the power of NuGet](https://www.nuget.org/packages/System.Buffers/).
