### ISSUE TITLE
combined return and if statement like ruby

### ISSUE THREAD

**Issue by gregveres** [dotnet/csharplang#2195]
I was coming here to suggest a return <value> if <condition> type statement and Github suggested a [previous proposal from last summer](https://github.com/dotnet/csharplang/issues/1397). 

I don't think the original poster on that proposal articulated the right solution, but one of the [responses pointed out that Ruby has this construct already.](https://github.com/dotnet/csharplang/issues/1397#issuecomment-374693186).

I guess I should do some research into how well this construct performs in Ruby, but I can say that my code is littered with things like this:

```
var value = somefunction();
if (value == null) {
    return <error>;
}
```

I believe that the code would be more readable if that code could look like this:

```
var value = somefunction();
return <error> if (value == null);

```

Thanks

**Comment by svick** [comment]
I think https://github.com/dotnet/csharplang/issues/1785 is very close to what you're proposing (but there are quite a few proposals for similar features, so I'm not surprised it's not the one you found).

I think the main issues with this proposal are:

1. `if (value == null) return <error>;` is already valid. If it's a company code style, or something like that, that doesn't allow you to write it on one line, then you should consider changing the code style, instead of changing the whole language.
2. It has a fairly high chance of being confusing. Consider a line like:

    ```c#
    return "a string literal, or another expression whose character count is fairly considerable" if (value == null);
    ```

    If the `if` is at the end of the line, I think it effectively hides the most important information about the line. And that's a problem, especially when you're scanning code, when trying to understand what it does.

**Comment by willard720** [comment]
Instead of 

```csharp
var value = somefunction();
if (value == null) {
    return <error>;
}
```

Just do

```csharp
var value = somefunction();
if (value == null) return <error>;
```

Tada.
