### ISSUE TITLE
Exception instead of NaN/Infinity

### ISSUE THREAD

**Issue by gdalsnes** [dotnet/csharplang#2198]
Silent NaN/Inf must be one of the most stupid constructs ever?

Suggestion: on project level make it possible to enable strict FP that will throw instead of producing NaN/Inf. In places where you want to allow NaN/Inf instead of exception (when strict FP is enabled) I suggest following:

```
unsafefp
{
   // will produce NaN/Inf instead of exception
}
```

Implementation: on some arch it can be setting a FP flag in cpu and the cpu will fault. On other cpus it can be manual NaN/Inf checks after every FP operation. This will be done by individual runtimes. The unsafefp block translate to two compiler generated calls to the runtime that turn strictfp off and on (in try/finally fashion). If strict FP project setting is off (default), no such compiler generated calls are generated (100% opt-in functionality). Will need a new runtime method eg. SetStrictFP(bool enable).

Easy peasy:-)

Keywords:
NaN considered harmful
Infinity considered harmful

**Comment by CyrusNajmabadi** [comment]
> Silent NaN/Inf must be one of the most stupid constructs ever?

I don't know what would lead to that conclusion.  NaN/Inf are how FP makes sense mapping an infinite space to a fixed-size representation.  

They are all well defined in IEEE754, and are properly understood and propagated through all calculations as would be expected.

**Comment by CyrusNajmabadi** [comment]
> Suggestion: on project level

Project level suggestions are not part of the language (which has no concept of 'projects').  If you want a compiler option, you can suggest it at dotnet/roslyn.

**Comment by MkazemAkhgary** [comment]
If you are concerned you should do the checks where you think division by 0 happens or anything unexpected.

NaN is easy to find. it's like a virus and spreads every where, so you don't have to check numbers for being NaN after every floating point operation. (for example you can put checks at end of the loop)

notice that these checks will slow down your program if you are dealing with many floating point operations. I think that is one reason to why NaN/Inf is silent. much more important reason is that NaN and Inf are both existing concepts in math.

At the end, you have the knowledge of where your calculations can actually become NaN/Inf. it's your responsibility to strictly put checks where ever required.

I have made a small struct for you that you can use for debug purposes. this construct is made so that your code would be very similar to double usage (so you can quickly make a release mode)

```c#
public struct FiniteDouble
{
    double val;

    public FiniteDouble(double d)
    {
        if (double.IsNaN(d)) throw new ArgumentOutOfRangeException("double is Not a Number.");
        if (double.IsInfinity(d)) throw new ArgumentOutOfRangeException("double is Infinite.");

        val = d;
    }

    // implicit cast is safe, exception is thrown if number is not finite.
    public static implicit operator FiniteDouble(double d)
    {
        return new FiniteDouble(d);
    }

    // explicit cast because we dont want to accidentally get out of finite range.
    public static explicit operator double(FiniteDouble d)
    {
        return d.val;
    }

    public static FiniteDouble operator +(FiniteDouble x, FiniteDouble y)
    {
        return new FiniteDouble(x.val + y.val);
    }

    public static FiniteDouble operator -(FiniteDouble x, FiniteDouble y)
    {
        return new FiniteDouble(x.val - y.val);
    }

    public static FiniteDouble operator *(FiniteDouble x, FiniteDouble y)
    {
        return new FiniteDouble(x.val * y.val);
    }

    public static FiniteDouble operator /(FiniteDouble x, FiniteDouble y)
    {
        return new FiniteDouble(x.val / y.val);
    }

    // etc
}
```

Here is an example

```c#
FiniteDouble x = 435d; // just change FiniteDouble to double
x *= 10000;
x /= 0;
x = x + 3453;
```

Once again, doing checks after every operation can be costly depending on your usage. struct is value type and has no overhead by it self, the problem is those checks in constructor.

**Comment by orthoxerox** [comment]
@CyrusNajmabadi technically, IEEE 754 allows the implementation to treat FP exceptions as errors provided it's not the default mode. It could work similar to `checked/unchecked`.

**Comment by gdalsnes** [comment]
> 
> 
> > Suggestion: on project level
> 
> Project level suggestions are not part of the language (which has no concept of 'projects'). If you want a compiler option, you can suggest it at dotnet/roslyn.

unsafefp keyword is part of language. the methods to turn it off/on will be part of runtime. plus the project setting. it is pretty similar to checked/unchecked as @orthoxerox said. but it may not belong here.

**Comment by gdalsnes** [comment]
> 
> 
> @CyrusNajmabadi technically, IEEE 754 allows the implementation to treat FP exceptions as errors provided it's not the default mode. It could work similar to `checked/unchecked`.

Yes, for arch\cpu that support it, the runtime would utilize that. For others the runtime must do "manual" NaN/Inf checks.

**Comment by gdalsnes** [comment]
> 
> 
> If you are concerned you should do the checks where you think division by 0 happens or anything unexpected.
> 
That will be some million checks in our code:-)
> NaN is easy to find. it's like a virus and spreads every where, so you don't have to check numbers for being NaN after every floating point operation. (for example you can put checks at end of the loop)
> 
My last NaN encounter was an integrator that went into infinite loop because of invalid input. I have many stories like that.
> notice that these checks will slow down your program if you are dealing with many floating point operations. I think that is one reason to why NaN/Inf is silent. much more important reason is that NaN and Inf are both existing concepts in math.
Yes perf can be a problem, but its possibly to use unsafefp at hotspots. And some cpu may have option to enable FP unit to fault it.
> 
> At the end, you have the knowledge of where your calculations can actually become NaN/Inf. it's your responsibility to strictly put checks where ever required.
>
Yes I know, but that will be a lot of checks. In practice these checks are just sometimes added and mostly  turn into bugs. 
> I have made a small struct for you that you can use for debug purposes. this construct is made so that your code would be very similar to double usage (so you can quickly make a release mode)
> 
Nice. Thanks!
> Once again, doing checks after every operation can be costly depending on your usage. structs are value types and for this particular struct it has no overhead by it self (its just a double), the problem is those checks in constructor.

**Comment by CyrusNajmabadi** [comment]
> My last NaN encounter was an integrator that went into infinite loop because of invalid input. I have many stories like that.

A algorithm that doesn't properly handle the spec'ed behavior of the domain it operates on will def have problems.  People have had similar problems not understanding how to properly do FP comparisons and whatnot.  

My advice would be to study up *a lot* on IEEE754 and all it's behaviors.  Then write your code according to that.

**Comment by gdalsnes** [comment]
> 
> 
> Can you place that code in an ``` block?

done

**Comment by gdalsnes** [comment]
> 
> 
> > Implementation: on some arch it can be setting a FP flag in cpu, on others it can be manual NaN/Inf checks after every FP operation.
> 
> This seems... undesirable. If you want this behavior, why do you need language support? Why not just create a library that you call into to 'flip/enable' this behavior? That way you can decide if the impact here is appropriate for your needs.

Not sure what you mean. Where can I flip this behavior? Its not part of the runtime afaik.
But I think I understand: most of the suggested function belong in runtime, it is only the unsafefp "sugar" (that could be simulated with try/finally) that is the language feature.

**Comment by DavidArno** [comment]
It's worth pointing out that your suggestion of,
```cs
unsafefp
{
   // will produce NaN/Inf instead of exception
}
```

is a definite non-starter. You are changing the default behaviour of FP, which would cause code that currently runs to now fail with exceptions. If this idea were considered, it would have to be an opt-in with the current behaviour being the default.

**Comment by yaakov-h** [comment]
Essentially I think it's just a floating-point version of `checked`/`unchecked`.

It's a shame that adding it to `checked` would be a breaking change, but as its own keyword you would need to apply both `checked`/`unchecked` and the floating-point equivalents each time you want to turn on or off safety.

Having two sets of safety mechanisms seems like a bit much.

**Comment by tannergooding** [comment]
This should probably be an API proposal against CoreFX requesting that the framework/runtime expose a mechanism to allow IEEE compliant exceptions. Not only is this non C# specific, but it requires runtime changes to enable/support. The proposal could start off as a discussion initially, but it eventually needs to be a formal API proposal (the API review process and a template to follow for the issue can be found here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps).

The runtime spec indicates:
> While the IEC 60559:1989 standard also allows for exceptions to be thrown under unusual conditions (such as overflow and invalid operand), the CLI does not generate these exceptions.
Instead, the CLI uses the NaN, +infinity, and –infinity return values and provides the instruction ckfinite to allow users to generate an exception if a result is NaN, +infinity, or –infinity.

I have been working on updating the various code in CoreFX/CoreCLR to be IEEE 754:2008 compliant. The issue tracking this support is here: https://github.com/dotnet/corefx/issues/31901. However, `exception` support was considered "out-of-scope" at this time since it does require significant design/support/etc and since the majority of customers end up not wanting it and instead (much like with `checked` vs `unchecked`) preferring speed over safety checks. This lead us to determine that the cost-to-benefit ratio was not worthwhile and we should come back if and when we had customers ask for the feature.

It is worth noting that, if the language (or framework/runtime) were to expose some mechanism to allow toggling IEEE compliant exceptions, this proposal is not currently sufficient as the IEEE 754:2008 standard defines a number of exceptions each of which can be toggled on/off independently from the others. A user wanting the current behavior (no exceptions) would be just as valid as a user wanting exceptions for Overflow/NaN (this proposal), users wanting exceptions for Underflow (not listed as part of this proposal, but also generally applicable), users wanting exceptions only for NaN, users wanting signalling for "inexact" results, etc. The total exceptions defined are: `Invalid Operation`, `Division By Zero`, `Overflow`, `Underflow`, and `Inexact`.

It is also worth noting that, for IEEE compliant exceptions; `NaN` and `Infinity` are not themselves invalid. Each operation has its own behavior that may deviate from your expected result. For example: most say `NaN` is valid and will only throw for `SNaN`. Most also consider `Infinity` to be a valid input and only consider overflow when all non-finite inputs produce an infinitely precise result (which is not `Infinity`), which must then round to `Infinity` to be represented in the destination format (`Log2(0)` for example is exactly `Infinity`, and would not be considered `Overflow`; the same with `double.PositiveInfinity + 2.0`).

**Comment by YairHalberstadt** [comment]
The details sound horribly complex, and would probably cause a huge amount of confusion along the lines of "why are/nt I getting an exception here".

Whilst initially I thought that this would be a reasonable idea if it could be done easily, now I think that the extra complexity of this feature are not worth it.

**Comment by tannergooding** [comment]
> The details sound horribly complex, and would probably cause a huge amount of confusion along the lines of "why are/nt I getting an exception here".

Yes. IEEE floating-point is already fairly confusing by itself. For example, plenty of people don't understand that `double d = literal` does not give you exactly `literal`, but instead `literal` rounded to the nearest representable result.

Once you start adding in exceptions, rounding modes, etc. it just gets more confusing.

**Comment by bbarry** [comment]
Supposing the language were able to enable IEEE compliant exception behavior, what might that look like?

Presumably the semantics would be something like a using statement at the block level:

```csharp
using (FloatingPointCompliance.Enable(invalidOperation: true, divideByZero: true, overflow: true, underflow: true, inexact: true)) {
    ...
}
```

or maybe an attribute at the method level?

That doesn't seem to require a language syntax change outside of mentioning a special named type that the CLR should react to. Perhaps one would be nice to sugar over such an implementation?

**Comment by gdalsnes** [comment]
So it may seem the FPU doesn't have an option for fautling at !IsFinite (per @tannergooding comment). In case the only remaining alternative is IsFinite checks generated by the runtime after every FP operation that can manifest them (it may not be than many?). So it is doable off course. And it will hurt perf. It's not as generic as you want it to be (adhering to IEEE defined exceptions). But I can understand you want a solution that not only fixes my problem:-)

Thank you for the consideration.

**Comment by GSPP** [comment]
I am very sympathetic to the idea of disallowing "unusual" floating point values. I have wanted this multiple times. Most of the time any such value at any point indicates a bug.

I'd argue that *most* code wants to use only finite floats. Certainly any kind of business logic style code (don't say you should use decimal, I'm not talking about money). Math-heavy code likely wants to allow non-finite values for performance.

You can of course check the end result but it can amount to a lot of checking. It's easy to forget and the check does not flag where the bug occurred (it might occur in an intermediate step).

`checked` arithmetic is useful for integers. At the CLR level it's a per-operation check. Could be the same for floats. Certainly, there should *not* be any process-global setting. That would alter the behavior of other code in the process.

The IEEE standard defines all kind of behavior and different exceptions and modes. It is not necessary to expose all of this. It could be a single type of exception thrown for any kind of non-finite value.

I like the idea of the `FiniteDouble` proposed above. It's easy to implement. Any runtime changes would likely not carry their weight.
