### ISSUE TITLE
C# 8 switch expression exhaustiveness

### ISSUE THREAD

**Issue by jcberleur** [dotnet/csharplang#2228]
with the following code

```csharp
        abstract class Sum
        {
            private Sum() { } // disallow external extension
            public sealed class A : Sum { }
            public sealed class B : Sum { }
        }
        static int TestExhaustive(Sum sum)
        {
            return sum switch
            {
                Sum.A _ => 1,
                Sum.B _ => 2,
                Sum _ => throw new NotSupportedException("Unreachable"),
                null => throw new NullReferenceException("Unreachable Sum"),
            };
        }
```

I am wondering why the `Sum _ =>` case is required (warned against not being exhaustive) while being impossible to reach (even through reflection, I believe)

**Comment by gafter** [comment]
Because nothing in any language specification says such a switch is exhaustive. The compiler doesn't root around to see how many constructors there are and where they may be used and how many derived types are declared and where they are declared, because it is unlikely that the language specification would require it to do so.

We're looking at adding some kind of discriminated union type, which would both permit the switch to be known exhaustive and also permit it to be implemented more efficiently (dispatching on a compiler-generated tag field).
