### ISSUE TITLE
Efficient Params and String Formatting

### ISSUE THREAD

**Issue by jaredpar** [dotnet/csharplang#2302]
[Proposal Document](https://github.com/dotnet/csharplang/blob/master/proposals/format.md)

- [x] Proposal added
- [x] Discussed in LDM
- [ ] Decision in LDM
- [ ] Finalized (done, rejected, inactive)
- [ ] Spec'ed

This is issue is related to the following:

- https://github.com/dotnet/csharplang/issues/1757
- https://github.com/dotnet/csharplang/issues/179
- https://github.com/dotnet/corefxlab/pull/2595

LDM history:
- https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-03-04.md#params-and-string-interpolation

**Comment by yaakov-h** [comment]
> Overload resolution rules will be changed to prefer `ValueFormattableString` over `string` when the argument is an interpolated string.

🎆 🎉 🎆 🎉 🎆 🎉 🎆 🎉 🎆

**Comment by ufcpp** [comment]
Can the `Variant` be optimized with runtime support? So far, the `Variant` is 32 byte struct because the .NET runtime can't over-wrap structs and objects. Is there any chance to avoid the extra 'object' field?

**Comment by MgSam** [comment]
Great proposal!

Is there a link to a proposal, spec, or even code file for `Variant`? I'd be interested in reading further about it. Being able to store heterogeneous data without boxing would be fantastic in the context of data frames.

**Comment by bbarry** [comment]
@MgSam current variant code is here: https://github.com/dotnet/corefxlab/pull/2595

Basically it is a wrapper around a union struct with some unsafe manipulation going on to get at the values without boxing as long as those values are from a small set of well known types. 

I'm not sure I like the conversion operators on it but otherwise it is reasonable. As @morganbr points out some ok looking code gives perhaps unexpected results like `(long)(Variant)(-1)` (as opposed to `(long)(Variant)(-1l)`)

**Comment by qrli** [comment]
> Variant2 and Variant3

Why not use `ValueTuple<Variant, Variant, ...>` and have an extension method to create a `Span<Variant>` from it?

**Comment by svick** [comment]
> When [the `IEnumerable<T>` variant is] invoked in `T` argument form the backing storage will be allocated as a `T[]` just as `params T[]` is done today.

If it was guaranteed by the language that `params IEnumerable<T>` uses an array, wouldn't that prevent some optimizations?

As a somewhat contrived example, consider:

```c#
string Format(string format, params IEnumerable<string> args);

…

foreach (var format in formats)
{
    Format(format, "foo", "bar", "baz");
}
```

A smart compiler could allocate a single custom implementation of `IEnumerable<string>` and use it for every iteration of the loop, if that was allowed. But if it used an array, it couldn't reuse it, because the called method could cast to array and then mutate it.

Though I'm not sure such optimization would ever be implemented in the compiler; it's certainly much less useful than the other optimizations that are proposed here.

---

```c#
readonly struct ValueFormattableString
```

Should `ValueFormattableString` be a `ref struct`, so that it could store the `params ReadOnlySpan<Variant> collection` without allocations?

---

```c#
ValueFormattableString.Create("hello {0}", new Variant(DateTime.UtcNow))
```

Since this API is not meant for human consumption, could you consider approaches that avoid the cost of parsing the format string?

For example, the code: `ValueFormattableString vfs = $"Weight: {weight,7:f1} kg";` could be compiled into something like (using `stackalloc` as a shorthand for `RuntimeIntrinsic.StackAlloc`):

```c#
ReadOnlySpan<string> texts = stackalloc[] { "Weight: ", " kg" };
ReadOnlySpan<Variant> args = stackalloc[] { (Variant)weight };
ReadOnlySpan<int?> alignments = stackalloc[] { (int?)7 };
ReadOnlySpan<string> formats = stackalloc[] { "f1" };

var vfs = ValueFormattableString.Create(texts, args, alignments, formats);
```

**Comment by yaakov-h** [comment]
> A smart compiler could allocate a single custom implementation of IEnumerable<string> and use it for every iteration of the loop, if that was allowed.

Assuming the callee doesn't store the `IEnumerable` for use after the method has returned, which is not an assumption you can easily make at a compiler level.

**Comment by svick** [comment]
@yaakov-h 

> > A smart compiler could allocate a single custom implementation of IEnumerable and use it for every iteration of the loop, if that was allowed.
> 
> Assuming the callee doesn't store the `IEnumerable` for use after the method has returned, which is not an assumption you can easily make at a compiler level.

Why would storing it be an issue? Iterating it will always return the same values, so multiple pieces of code (even multiple threads) iterating that `IEnumerable` should be fine.

**Comment by yaakov-h** [comment]
Oh right, because it's all constant values.

**Comment by Thaina** [comment]
Is this related to #535 ?

**Comment by jaredpar** [comment]
Closing as this proposal has been broken off into three different items that are being pursued. 

- [X] https://github.com/dotnet/csharplang/issues/4487
- [ ] https://github.com/dotnet/csharplang/issues/1757
- [ ] https://github.com/dotnet/csharplang/issues/179
