### ISSUE TITLE
System.Range should implement IEnumerable<int>

### ISSUE THREAD

**Issue by lostmsu** [dotnet/csharplang#2306]
All in the subject.
Usage: `(1..20).Concat(40..60).ToArray()`

**Comment by yaakov-h** [comment]
1. This is not part of the C# language and would be better suited to https://github.com/dotnet/corefx
2. This would not work with ranges that have an index from the end.

**Comment by YairHalberstadt** [comment]
The correct way to do this is IEnumerable.Range()

**Comment by sonergonul** [comment]
C# does not have a "range" or "slice" mechanism until `System.Range`. We did these things with `Enumerable.Skip`, `Enumerable.Take` or Jon Skeet's generic `Batch<T>` method from [MoreLINQ ](https://github.com/morelinq/MoreLINQ )usually. But what we are described here is a part of C# language itself, not BCL.

As @YairHalberstadt mentioned in [his comment](https://github.com/dotnet/csharplang/issues/2306#issuecomment-470034995), you should definitely consider to use `IEnumerable.Range` method for this requirement. That's the right way to do it.

**Comment by RikkiGibson** [comment]
Thanks to @YairHalberstadt's work it is [now possible](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKGIAYACY8gOgGEB7AGy7gGMYASw6YoAbhr0m5ACwTqNAGYcEcCHwAWDABQA3CAgYAPBoMwMArCxbk6AShoBvGg1fSAnNqN35AXxqSAMwMsBgCDABKEJgA5nAAopjoYIgQMCoMIAwAkonJqekIADxmMAB8Ti5uAA4IgvrwDKoQOCJcAJ6mmDAMAPpwmDjybgy19WlwXT29fOgIqt3yVa7EwVGxCUkpCGkq2qUhMAYwSFMMAzgO1CPO1yNuM3MLPQC8h8fD9679gwxvF59XP4FHcVsEDmwngNXmU+rN5tDAQwOMAAFb8Hq5LYFFTsKHdP6wyEIxYBUFMYLADjcBgAWQ4ujgADk4EYYNo7ISGPh8I8ST0in0AWSRqsmDIGAARQRQaocKBwDkMRwMYGi4LECUROAK9lXG7Le4wDQIDgAdwYmDgFqZHBg2TA1V4KW6cBw8SMfDg1SEIg5SOBwKC0gAbExSJFonEPZVyWLmGH1tHsTtCgwAOJwGB5ba7BDaY0yyMbJpRuD6ty3L6uQSKHQ7DYsADKRwQMBY2SgADFTWBEjgGIRCKXG/2O93e/2K18q9WRsbTRarRaAIIIGL5boer0+4SYbSYCApDiKbQNuJ2HyGkZq6vXtzEADslutxeT+VTe3PcGbrfbADUIC4dA4FOb8WDHQDgPLAMaGBIA==) to 'foreach' over a System.Range by defining an extension method:

```cs
using System;
using System.Collections;
using System.Collections.Generic;

foreach (var x in 5..10)
{
    Console.WriteLine(x);
}

public struct RangeEnumerator : IEnumerator<int>
{
    private readonly int _end;
    private int _current;

    public RangeEnumerator(int start, int end)
    {
        _current = start;
        _end = end;
    }

    public int Current => _current;
    object IEnumerator.Current => Current;

    public bool MoveNext() => ++_current < _end;

    public void Dispose() { }
    public void Reset()
    {
        throw new NotImplementedException();
    }
}

public static class RangeEx
{
    public static RangeEnumerator GetEnumerator(this Range range)
    {
        if (range.Start.IsFromEnd || range.End.IsFromEnd)
        {
            throw new ArgumentException(nameof(range));
        }
        
        return new RangeEnumerator(range.Start.Value, range.End.Value);
    }
}
```

I am closing this issue because as noted above, the decision to implement `IEnumerable<int>` lies with https://github.com/dotnet/runtime.

I personally think this might be reasonable to have out of the box, with sensible semantics defined for the case where either index is `IsFromEnd` (probably throwing an exception), with SDK built-in warnings when such a range literal is used as an `IEnumerable<int>`. e.g. `foreach (var i in 0..^1)` or `(0..^1).Select(x => ...)`.

**Comment by qdoz** [comment]
> All in the subject.
> Usage: `(1..20).Concat(40..60).ToArray()`

## Usage
```csharp
(0..100)
.ToEnumerable()
.Select(x => x)
```

## Extension
```csharp
public static class RangeExtensions
{ 
	public struct RangeEnumerator
	{
		public RangeEnumerator(int start, int end) => (Current, _end) = (start - 1, end);
		public int Current { get; private set; }
		private int _end;
		public bool MoveNext() => ++Current < _end;
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static RangeEnumerator GetEnumerator(this Range range)
	{
		if (range.Start.IsFromEnd || range.End.IsFromEnd)
			ThrowIsFromEnd();

		if (range.Start.Value > range.End.Value)
			ThrowStartIsGreaterThanEnd();

		return new RangeEnumerator(range.Start.Value, range.End.Value);

		static void ThrowIsFromEnd() => throw new ArgumentException("range start and end must not be from end");
		static void ThrowStartIsGreaterThanEnd() => throw new ArgumentException("start is greater than end");
	}

	public static EnumerableRange ToEnumerable(this Range range)
	{
		return new EnumerableRange(range);
	}

}

public class EnumerableRange : IEnumerable<int>
{
	public Range Range { get; private set; }

	public EnumerableRange(Range range)
	{
		Range = range;
	}

	public IEnumerator<int> GetEnumerator()
	{
		var enumerator = Range.GetEnumerator();
		while (enumerator.MoveNext())
			yield return enumerator.Current;
	}

	IEnumerator IEnumerable.GetEnumerator()
	{
		throw new NotImplementedException();
	}
}

```
