### ISSUE TITLE
How do I set a breakpoint in an attached process in visual studio

### ISSUE THREAD

**Issue by xarzu** [dotnet/csharplang#2392]
How do I set a breakpoint in an attached process in visual studio

I have started a local host application and I attached a project in visual studio to this iexplorer process what was running the app.  But I am unable to set break points in the code. I have tried to set break points but the errors says:

"This breakpoint will not currently be hit.  No symbols have  been loaded for this document."

Please advise.

**Comment by Unknown6656** [comment]
This is the wrong repository for such questions. We discuss the C# language design here.
You should redirect your questions to https://stackoverflow.com/, https://developercommunity.visualstudio.com/ or https://social.msdn.microsoft.com/.

The reason you cannot hit any breakpoint inside of VS is -- as the message rightly says -- that no code symbols could be loaded.
This means: The code you are currently executing (in the attached process) has some differences to the actual code file. This could be due to compiler optimizations, removal of debugging information in the compiled executable or changes in the code file.

In which language has the target application been written in?
C#/F#/VB.NET? If so, try either decompiling it using DnSpy or similar and then debugging the decompiled application. Otherwise you could try running the application directly from VS if you are already in possession of the source code.
If the language is a native one (C++ etc.) you may be out of luck here.

Either way, this is the wrong repo for this issue.

**Comment by gafter** [comment]
Closing, as this is not actionable with respect to the C# programming language.
