### ISSUE TITLE
Automatically changing return type of Range Indexer of Array 

### ISSUE THREAD

**Issue by aobatact** [dotnet/csharplang#2406]
https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-12-03.md

It seems like the return values of array range indexer is copied array, but it's not so efficient and we have to use AsSpan() method. 
It might be better to change return type to Span<T> or ReadOnlySpan<T> when the required return type is clear.
``` csharp

void ArrayUsingMethod(T[] values){}
void SpanUsingMethod(Span<T> values){}

var copied = array[1..3];//copy and return T[] 
Span<T> span = array[1..3];//no copying and return Span<T>

ArrayUsingMethod(values[1..3]);//copying

SpanUsingMethod(array.AsSpan(1..3));
SpanUsingMethod(array[1..3]);//return Span<T> (Looks better than above?)
```

**Comment by Joe4evr** [comment]
The reason you should call `.AsSpan()` explicitly is to [remove surprises](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Sure, you're gonna allocate when you don't want to, but there's an explicit opt-out for that, instead of needing a separate thing that would opt-in the moment that Spans can't be used (class fields, iterator/async methods, etc.).

**Comment by YairHalberstadt** [comment]
I'm going to close this as this is an issue for dotnet/runtime.

Also as ranges have now shipped, this would be a breaking change, as the following is already legal:

`Span<T> span = array[1..3];`
