### ISSUE TITLE
Implicitly scoped lock statement

### ISSUE THREAD

**Issue by skarllot** [dotnet/csharplang#2451]
## Motivation:
Allow `lock` keyword to be used to lock a variable that will be unlocked at the end of the current block. This avoids creating a new block with an additional level of indentation:

### Before:
```csharp
public void Foo() {
    lock (numberGate) {
        number += 5;
        if (number > 1000) {
            number = 0;
        }
    }
}
```

### After:
```csharp
public void Foo() {
    lock numberGate;
    number += 5;
    if (number > 1000) {
        number = 0;
    }
}
```

**Comment by YairHalberstadt** [comment]
It is absolutely vital that locks are as short as possible. As such this might be considered a bad idea.

**Comment by marksmeltzer** [comment]
Same rationale as was used for simplifying `using`, and I love that simplification.

**Comment by theunrepentantgeek** [comment]
@marksmeltzer wrote:

> Same rationale as was used for simplifying using, and I love that simplification.

The simplification for **using** makes sense because the vast majority of using statements finish at the end of the enclosing block:

```
{
    // code

    using (var thing = ...) 
    {
        // more code
    }
}
```

However, because of the need for **lock** statements to enclose as little as possible, my experience is that those blocks typically finish well before the enclosing block:

```
{
    // code

    lock (_thing) 
    {
        // more code
    }

    // yet more code
}
```

Creating a variation of **lock** that encourages longer lock retention would be a bad idea.

I'd also offer the observation that **using** statements are extremely common - so the new **using** declarations will benefit a lot of developers. By contrast, **lock** statements are relatively rare, so any benefit would accrue to a significantly smaller group.

**Comment by PathogenDavid** [comment]
> I'd also offer the observation that **using** statements are extremely common - so the new **using** declarations will benefit a lot of developers.

It's also more common to end up with many using statements in the same method, so using statements can keep the number of blocks and levels of indentation required under control in a method when omitting the blocks isn't possible.

**Comment by HaloFour** [comment]
Another difference between `lock` and `using` is that the latter is tied to the declaration of a variable, and the resource is disposed at the point that the variable goes out of scope.  You can't use a `using` declaration on an existing variable.  `lock` must be used on an existing variable, but the duration of the lock certainly wouldn't be associated with the scope of that variable.

**Comment by HaloFour** [comment]
@SilentSin 

I'm referring to the new feature slated for C# 8.0:

```cs
void M() {
    using var foo = new Foo();
    // do stuff here
} // foo automatically disposed here
```

Sorry, should have clarified.

**Comment by skarllot** [comment]
@theunrepentantgeek for me when using locks, is common that the scope of locks are the method/property itself.

Another side effect is to provide a feature closer to Java synchronized methods.

**Comment by HaloFour** [comment]
@skarllot 

> Another side effect is to provide a feature closer to Java synchronized methods.  

This already exists in .NET:

```cs
[MethodImpl(MethodImplOptions.Synchronized)]
public void Method()
{
    MethodImpl();
}
```

C# doesn't expose it at the method level because it behaves identically to how `synchronized` is implemented in Java and even at that time it was known to be a bad idea.  Sadly it wasn't yet understood that locking arbitrary `object` instead of a specific lock primitive was also a bad idea.

This is really a sidebar as I assume your proposal would keep to the concept of locking on some arbitrary object and not trying to replicate Java `synchronized` methods by implicitly locking `this` or the `Type`.  When you are using `synchronized` on an arbitrary object in Java you are still required to supply a block.  It's pretty much identical to C# in that regard.

**Comment by ghord** [comment]
Please consider fixed for the same feature!

**Comment by DavidArno** [comment]
```cs
public void Foo() 
{
    lock (numberGate) restOfFoo();

    void restOfFoo()
    {
        number += 5;
        if (number > 1000) number = 0;
    }
}
```

🤡
