### ISSUE TITLE
Proposal: allow `set`-less (non auto) properties to be constructor-initialized, under certain circumstances

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/csharplang#2468]
The C# [language spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#automatically-implemented-properties) says that an_automatically implemented_ property, even when no `set` accessor is provided (i.e., a **read only** property), can be initialized in the constructor.

In my opinion, this rule is a design defect. The ability to initialize a `set`-less property in the constructor is conceptually contradictory (after all, there's not "setter"), and it brings certain inconsistency to the language. For instance, it might be surprising that:

  1. a perfectly valid piece of code

```
class Abc
{
    Abc() { SomeProp = 1; }   
    int SomeProp { get; }
}
```

  2. is not longer compilable once the programmer *extends* it through another (valid) piece of code,

```
class Abc
{
    Abc() { SomeProp = 1; }    // error
    int SomeProp { get { return _field; } }
    int _field;
}
```

  3. even though the 2 programs likely have the exact same semantics.

While I'm not formally defining here the details of an "extension through another (valid) piece of code", I hope that my point can be understood. 

In addition to the reasoning I mentioned above, this feature also makes it non-trivial to perform a source rewrite, like the one I described (while it could have been otherwise).

That being said, I'm not proposing to deprecate this feature, since it'd break a log of existing code. Instead, my proposal is to as well allow constructor-initialization of a non auto-property under certain circumstances:

  - whenever a `set` accessor isn't present, and the `get` accessor is implemented simply with a *return-statement <expr>* (likewise, for expression body), where *<expr>* unambiguously identifies (e.g., an `IdentifierNameSyntax` or a corresponding `MemberAccessSyntax`) a field of the enclosing type declaration. 

At first sight, this solution would bring consistency and it's not less obvious than what the current rule is. This way, the second code I illustrated above would be valid, just like this one:

```
class Abc
{
    Abc() { SomeProp = 1; }  
    int SomeProp { get { return this._field; } }
    int _field;
}
```

**Comment by svick** [comment]
> At first sight, this solution would bring consistency and it's not less obvious than what the current rule is.

I think this would actually make the language much less consistent and it's also less obvious.

It's less consistent, because the original inconsistency you mentioned still exists, though for smaller amount of code. But it also introduces a brand new (and in my opinion, worse) inconsistency, where setting a get-only non-auto property from the constructor sometimes works and sometimes doesn't.

It's less obvious, because to me, the existing situation is quite obvious: for an auto-property without a setter, there is a clear target for setting it: the auto-generated backing field, just like for the getter. For a non-auto-property, the target is not clear, and the rules for when divining it from the `get` accessor works will never be obvious.

Also, I think the proposed feature is not particularly useful: Being able to set a `get`-only auto-property means you avoid having an explicit backing field and a `get` accessor body. Being able to set `get`-only non-auto property means you'll be able to change `_field = 1;` to `SomeProp = 1;`, which is not simpler (at least in the common case).

**Comment by HaloFour** [comment]
This proposal solves no problems.  You can already set the field directly for normal properties, and the claim that changing some code might break other code applies pretty much everywhere.  You don't eliminate it, as it would still have to fail on a computed property, but you make it more difficult to reason about.

With a read-only auto-property there is no accessible field to set.  The alternative to allowing it to be written to in the constructor would be that read-only auto-properties could only be written by initializer, which would have limited the feature substantially.

**Comment by Thaina** [comment]
So you want a `readonly` property?

Why not just use a `readonly` field though?

Though I think this issue has some value. Maybe we should allow `readonly set` in addition to `private set`

```C#
public int SomeInt { get; readonly set; } // same as private set but cannot set outside constructor
```

**Comment by CyrusNajmabadi** [comment]
> Though I think this issue has some value. Maybe we should allow readonly set in addition to private set

> `public int SomeInt { get; readonly set; } // same as private set but cannot set outside constructor`

That's what `public int SomeInt { get; }` already is.

**Comment by Thaina** [comment]
@CyrusNajmabadi Thanks, never know before when that was possible

**Comment by CyrusNajmabadi** [comment]
You're welcome :)

**Comment by ltcmelo** [comment]
I guess I should close this issue... I understand the pointers raised by others and see that my proposal isn't good for the user (although it'd make things easier for those manipulating the source, in my opinion).
