### ISSUE TITLE
Proposal: do not require a return statement after recursion 

### ISSUE THREAD

**Issue by DimitarBogdanov** [dotnet/csharplang#2470]
Often there is a situation like this:

```csharp
static void Something(bool somethingElse) {
    if (statement) {
        return true;
    } else if (anotherStatement) {
        return false;
    } else {
        Something(somethingElse);
    }
}
```

This code is invalid, because the last part (the else statement) needs to return something. That however shouldn't be like that, because the method does recursion so there is no point in ever reaching that part of the code.

**Comment by svick** [comment]
> That however shouldn't be like that, because the method does recursion so there is no point in ever reaching that part of the code.

That doesn't make sense to me. The recursive call does end and when it does, the current method has to return (and if it's not a `void` method, it has to return a value). If the call is [tail recursive](https://en.wikipedia.org/wiki/Tail_call), then it can be optimized so that control never returns to the current method, but that's all it is: an optimization. Logically, the method still returns.

Though worse than not making logical sense, I think this proposal does not make practical sense: calling a method and returning the result of calling a method are two very different operations. If they used exactly the same syntax, it would be really hard to understand what the code does. And that's assuming you could actually make a reasonable version of this proposal work without breaking backwards compatibility.

**Comment by DavidArno** [comment]
> This code is invalid, because the last part (the else statement) needs to return something

Looking at your code example, the complete opposite seems to be the case: the code is invalid because of the `return false` and `return true` in a `void` method. The last part not returning anything is actually the only valid part. It'll give you a stack overflow exception, but it's valid as far as the compiler is concerned.

**Comment by DimitarBogdanov** [comment]
i am actually dumb.

**Comment by theunrepentantgeek** [comment]
_Preface: I know this is off topic, but I think this needs to be said._

> i am actually dumb.

@DimitarBogdanov, I've got two responses to you.

Firstly, optimizing tail recursion into a loop is a common optimization technique that is often used to avoid stack blowout and to improve performance. Creating a proposal suggesting that the the C# compiler directly support expressing this is exactly what should happen in this repo. 

Secondly, we work in an industry with a very large amount of negative talk. Even in this repo (which is one of the more civilized areas of the internet), we have our share of argumentative trolls etc etc. Please don't talk yourself down.
