### ISSUE TITLE
Let me require to check all enum values in a switch

### ISSUE THREAD

**Issue by miloush** [dotnet/csharplang#2472]
This is an alternative, less restrictive proposal to #782. It annotates the enum usage rather than its declaration. A compile time check is proposed, neither the runtime behaviour nor the compiled binary would be changed.

---

I am nowadays finding myself quite often adding values to enums and having to search for all its usage in the solution to check whether I need to add `case` statements to `switch` or not.

(Even the search itself is annoying, because FAR does not return `switch` usages, only `case` usages when searching for an enum.)

At some places, the `switch` statements can do with `default` or missing cases, but at some places it is certain that by not considering the added cases, the application will throw at runtime (often by means of `default: throw` case).

I am looking for a way how to get a compilation error in these cases, i.e. a way to mark the `switch` side that the case statements need to explicitly exhaust all enum values as of compilation time. Being this usage dependent rather than declaration dependent, attributes are not an option as far as I know. I was thinking about using the `checked` keyword:

```C#
enum Fruit { Strawberry, Banana, BrushCherry }
...
Fruit fruit;
switch (fruit) // normal switch as expected
{
    case BrushCherry: return "Brush Cherry";
    default: return fruit.ToString();
}

checked switch (fruit)  // error, does not have BrushCherry case
{
    case Strawberry: return 0;
    case Banana: return 1;
}

checked switch (fruit)  // still error despite having a default case
{
    case Strawberry: return IsBerry;
    case Banana: return IsBerry;
    default: return NotABerry;
}
checked switch (fruit)  // ok
{
    case Strawberry: return IsBerry;
    case Banana: return IsBerry;
    case BrushCherry:
    default: return NotABerry;
}

checked switch (fruit) // ok, conditions count as usage, default not required
{
    case Strawberry when false: break;
    case Banana:
    case BrushCherry:
       break;
}
```

The `checked switch` would be only allowed when switching on enums that are not flags (could formally be on any constant expression, but I don't find that very useful, as either the exhaustive cases are fixed (e.g. `bool`) too many (e.g. `int`) or infinite (e.g. `string`)).

Passing `(Fruit)47` behaves as usual, and similarly fine is if the enum gets updated in a different assembly. It's up to the consumer whether they want to throw or not in such cases.

The arithmetical checked context would not be affected by `checked switch`, and the normal `switch` would not be affected by current arithmetical checked context. However, the `checked switch` syntax might prevent contexts like `unsafe` and `checked` from becoming allowed inline in the future.

---

I am open to other solutions. The closest idea with the current syntax I could come up with was to require a special `default` case - for example one that unconditionally throws the `NotImplementedException` - and have an analyser that flags all of these instances. It doesn't allow the more advanced scenarios, but might be a reasonable compromise.

**Comment by yaakov-h** [comment]
> attributes are not an option as far as I know

You could put an attribute on the method that contains the switch statement, though this wouldn't allow for mixing normal switch statements and 'checked' switch statements in the same method without some local function hackery.

This definitely seems like something that's (currently) Analyzer territory.

**Comment by HaloFour** [comment]
All of your use cases are perfect candidates to be rewritten as switch expressions which do have exhaustiveness checking.  I do believe that as of now they require a default case (`_`) for enums due to the possibility of an arbitrary integral value being cast to the enum.

**Comment by miloush** [comment]
@HaloFour interesting point, I wasn't aware of that. If I understand it correctly, that only helps when the switch is producing a value right? If it is a general list of statements, potentially modifying a state, the switch expression doesn't seem to be the best option, the statements would have to be separated out into individual methods, possibly with a dummy return value.

The switch expression as well as separation of cases into individual methods disallow `goto case` statements.

**Comment by HaloFour** [comment]
@miloush 

> If I understand it correctly, that only helps when the switch is producing a value right?

I believe that they're working on a statement version as well where each arm can produce `void` and it doesn't return a value.  But they are still limited to single expressions and you can't use blocks or the like.  It doesn't allow for `goto` between cases either.

If you're looking for this feature with general `switch` statements you're probably better off with an analyzer.  The exhaustiveness checking in the compiler does not consider switching on an enum to be exhaustive even if you check for every value defined by the enum due to the fact that you can technically use any integral value due to casting and bitwise operations, so any compiler feature would warn unless you always had a `default` case.  I personally don't see the LDM introducing some of those features to `switch` statements back from `switch` expressions, or expanding on the `switch` statements further (beyond supporting new patterns).  I could be wrong, though.

**Comment by miloush** [comment]
@HaloFour okay if the compiler is not at the right level to perform this check then I guess I have to figure out what's the best way to tell the analyser which blocks should be checked.

Actually, per the spec the arithmetical `checked` operator has no effect on called members, so although semantically different, looks like `switch (checked(member_or_variable)) { ... }` would be a good pattern to catch with an analyser without any side effects, or am I overlooking any?

**Comment by PathogenDavid** [comment]
Another possibility with no risk of unintentional side-effects is using comments. I needed something similar a while back and modeled after https://github.com/dotnet/csharplang/issues/1452 in case it ever came to fruitition:

```csharp
//[[Exhaustive]]
switch (fruit)
{
...
}
```

The obvious downside to this approach being there's no syntax checking on these pseudo-attributes. So nothing will tell you when you accidentally type `[[Exaustive]]` by mistake unless you make your analyzer pretty strict (which would interfere with other analyzers wanting to use the same pattern.)

**Comment by huoyaoyuan** [comment]
By the way, adding a value to an `enum` is considered unbreaking now. If exhausting check is enabled, it will be a source breaking change. Microsoft's breaking-change-hating culture dislike this.

**Comment by miloush** [comment]
@huoyaoyuan it would still be unbreaking until the developer explicitly opts in to the checked behaviour. Even then, it would be unbreaking only within your own code. There is no currently existing code that would suddenly stop compiling as a result of this proposal.

**Comment by AartBluestoke** [comment]
@huoyaoyuan At the moment we have silently breaking code where someone upstream adds something to an enum, and eventually a user of that set of values hits obscure runtime error results when a switch statement doesn't do what it is supposed to. In my opinion, Compile errors should be preferred over eventual runtime errors (otherwise i'd be using Node).

**Comment by CyrusNajmabadi** [comment]
Isn't this all possible by writing an analyzer here?

**Comment by miloush** [comment]
@CyrusNajmabadi The tricky part is, being it usage site dependent, communicating to the analyzer which switches should be analyzed. There are few options (naming conventions, dummy extension methods, comments as suggested by @PathogenDavid, checked context as suggested by myself, even pragmas directives perhaps) but all of them are bit hacky.

Based on the discussion I managed to write an analyzer using the checked operator, it's identical to the `PopulateSwitchDiagnosticAnalyzer` (I even wondered why I can't simply inherit it) with a few modifications:
1. if `!(switchBlock.Expression is CheckedExpressionSyntax)` it doesn't do anything
2. the diagnostics descriptor is `DiagnosticSeverity.Error`
3. the default case check is omitted

Seems to work as desired (technically it should check the checked expression to make sure it isn't a real one, and if you wanted to perform check even in such case you could simply do `switch(checked(checked(...))`) - that is, until you ship an analyzer that flags `unchecked`/`checked` operators as redundant. As a bonus, you don't need to write a code fix provider, since that already exists. Had I had this idea before the discussion, I wouldn't probably have submitted the issue.

It's a still hack though. The proposal was seeking a means of syntax in the language to selectively perform stricter checks, in this case on a switch. It seemed to be a somewhat popular behavior in #782. The `checked` keyword felt like a reasonable fit because it already means "perform stricter checks" although I am aware it's different ones. If this ought to be an analyzer, it requires a way to enable/disable analyzers in the code, i.e. check some of the switches but not others.

**Comment by yaakov-h** [comment]
> If this ought to be an analyzer, it requires a way to enable/disable analyzers in the code, i.e. check some of the switches but not others.

```csharp
public static class CheckedHelpers
{
    public static T Checked<T>(this T t) => t;
}

switch( foo.Checked() )
{
    /* ... a 'checked' switch statement? */
}

**Comment by miloush** [comment]
@yaakov-h Thank you, that's what I meant by the "dummy extension method". On that one I don't like the fact that all code would have to include its declaration, plus it would cause conflicts if you reference two such projects.

**Comment by yaakov-h** [comment]
> all code would have to include its declaration, plus it would cause conflicts if you reference two such projects.

You could make your Analyzers package automatically include it as an internal class, then you don't have to worry about declaration and it won't cause conflicts.

The Code Contracts tooling does something very similar and it works quite well. Well, this bit at least does...

**Comment by miloush** [comment]
> make your Analyzers package automatically include it as an internal class

Wouldn't that make the code non-compilable if the analyzer is disabled or not present in the system? All the other options compile fine or don't affect the compilation at all.

Anyway, as for this issue if there isn't demand (or technical feasiblity) for this to be part of the language I am happy to close it.

**Comment by Korporal** [comment]
@miloush 

You won't like this but it was interesting crafting the code and it is _a way_ of doing this but far from ideal.

We can craft something so that this is legal and runs:

```cs
            Test X = Test.A;

            Switch(X,

                Case(Test.A, x =>
                {
                    Console.Write('A');
                }),

                Case(Test.B, x =>
                {
                    Console.Write('B');
                }),

                Case(Test.C, x =>
                {
                    Console.Write('C');
                })
            );

```

the supporting code I crafted looks like this:

```cs
        public class CaseBlock<T> where T : System.Enum
        {
            public T EnumValue;
            public Action<T> EnumAction;
            public CaseBlock(T enumValue, Action<T> enumAction)
            {
                EnumValue = enumValue;
                EnumAction = enumAction;
            }
        }

        public static CaseBlock<T> Case<T> (T Value, Action<T> Block) where T : System.Enum
        {
            return new CaseBlock<T>(Value, Block);
        }
        public static void Switch<T>(T X, params CaseBlock<T>[] Cases) where T : System.Enum
        {
            // is there a case for every enum...

            var names = Enum.GetNames(typeof(T));

            // is every enum value handled...

            foreach (var name in names)
            {
                if (Cases.Where(c => Enum.GetName(typeof(T), c.EnumValue) == name).Count() != 1)
                {
                    throw new InvalidOperationException($"The enum value '{name}' does not have a corresponding unique case.");
                }
            }

            Cases.Where(c => c.EnumValue.Equals(X)).Single().EnumAction(X);
        }

        public enum Test
        {
            A,
            B,
            C,
            D
        }

```

This gives a runtime check that in the "switch" there is a "case" for every enum value, if you add one more and run you'll get an exception.

Of course you lose use of keywords like `break` and `continue`, however you also indirectly get a simple pattern for each "case" which can help in making switches neater and more consistent (switch statement are notorious for trickery and idiosyncracies).

**Comment by miloush** [comment]
I appreciate your effort @Korporal but this seems to be the opposite of what I suggested - a compile time check with no penalty at runtime.

**Comment by Korporal** [comment]
@miloush - It's always puzzled me why the language hasn't offered this already - in some way, seems such an obvious and very helpful check for the compiler to do - even a warning would be great!

**Comment by CyrusNajmabadi** [comment]
> even a warning would be great!

A warning would be a breaking change.

> @miloush - I told you you wouldn't like it! It's always puzzled me why the language hasn't offered this already

Roslyn provides a way to handle this.  Just write an analyzer.  This a core case for analyzers.  i.e. if you want to take legal code, but supply additional restrictive rules on how it can be used, you can.  It's very simple to do, and an analyzer for this would probably take less than a half hour to complete.

--

Note that this is why it *isn't* offered in the language.  It would be orders of magnitude more expensive to do it that layer than to just to it with a user written analyzer (which may already exist today!).

**Comment by Korporal** [comment]
@CyrusNajmabadi - Perhaps an analyzer is indeed the way to go, but developers today are burdened with work by the truckload and learning yet another library, yet another API, debugging it, proving it to be correct, testing it all add up.

The industry is currently burdened by a vast array of languages far more than 20 years ago, there are hundreds of "APIs", REST, MVC, Dapper, Typescript, .Net Core, .Net Standard, C# 8 and even more stuff with weird names like Bouncy Castle (for f***'s sake!).

The we have users and companies that are migrating to the "cloud" with Azure, DevOps, ADFS and many many other challenges, these are the kinds of things that I face weekly and every few weeks something else comes along.

So the oft repeated and rather glib "just write an analyzer" isn't always an appealing solution.

I've developed real compilers and optimizers and code generators and I'm sure I could jump onto the analyzer stuff a bit easier than most, but I haven't yet, why? I have simply more to do each week than I can achieve that's why.

Perhaps if you worked for a user of these technologies rather than a creator of them you'd begin to understand.

**Comment by YairHalberstadt** [comment]
@Korporal

> developers today are burdened with work by the truckload

And the members of the C# team aren't?

> The industry is currently burdened by a vast array of languages far more than 20 years ago, there are hundreds of "APIs"

What makes you think that learning a new language feature is easier than learning a new API?

> So the oft repeated and rather glib "just write an analyzer" isn't always an appealing solution.

Writing an analyser is far less work than writing a new language feature. And once it's done everyone can use it via nuget. So it makes no sense to create a new language feature because creating an analyser takes too much time.

Now you may ask Microsoft to write the analyser for you. And they may or may not, depending on whether it makes business sense for them to so so. If they don't, then the 'glib write an analyser' response is the best your gonna get.

> Perhaps if you worked for a user of these technologies rather than a creator of them you'd begin to understand.

Cyrus no longer works for Microsoft. As it happens his contributions to Roslyn tend to be exactly around areas where he feels it's not working well enough for him.

BTW he often implements IDE features that other people request if he feels they are valuable. Note that he is doing so entirely in his free time. He also gives a lot of help and advice to other people working with roslyn. He's certainly given me a lot of help. So if you were to persuade him that this is valuable, rather than be rude about his perspective on things, you might find him a very helpful person to have on your side.

**Comment by Korporal** [comment]
> @Korporal

> BTW he often implements IDE features that other people request if he feels they are valuable. Note that he is doing so entirely in his free time. He also gives a lot of help and advice to other people working with roslyn. He's certainly given me a lot of help. So if you were to persuade him that this is valuable, rather than be rude about his perspective on things, you might find him a very helpful person to have on your side.

Disagreeing with someone else's position @YairHalberstadt does not constitute being rude.

**Comment by YairHalberstadt** [comment]
Saying he doesn't begin to understand, is being rude.

**Comment by Korporal** [comment]
> Saying he doesn't begin to understand, is being rude.

Good Lord, OK in which case you should report my post.

**Comment by YairHalberstadt** [comment]
It's not offensive. But it's unpleasant, and doesn't do you any favours when you're trying to get other people to do your work for you.

Anyway I don't want to bother everyone subscribed to this thread, so I'll stop here. If you want to discuss more, I'm happy to chat on gitter.

**Comment by miloush** [comment]
@Korporal because it isn't important enough to invest half an hour and that is understandable. It doesn't look like this issue is even as popular as the one its criticism it tried to address.

It was important enough to me to create one as I mentioned above (it indeed took me about an hour). As also mentioned above the problem with analyzer is how to tell it that a particular block should or should not be checked. Various methods were suggested, of which only two or compatible with current compiler and language (comments and the checked context). I have hoped we could have more discussion on this aspect, perhaps generally applicable to other future analyzers as well.

However it looks like the issue is not getting much discussion related to these problems or to the proposed feature, hence I don't find it very useful to stay open. Thanks everyone for their thoughts.

**Comment by Korporal** [comment]
@miloush - Yes, I understand and closing this is probably the right move, but before you go - is there a particular place to discuss analyzers? Is gitter the place? I may try to write one now since I have a clear day today!

**Comment by YairHalberstadt** [comment]
> is there a particular place to discuss analyzers? Is gitter the place? I may try to write one now since I have a clear day today!

Writing analysers, try Roslyn gitter.

Asking Microsoft to write an analysers, create an issue on Roslyn analysers repo

**Comment by miloush** [comment]
@Korporal there is https://github.com/dotnet/roslyn-analyzers but I guess for general chat gitter (for roslyn) is the place I would suggest.

**Comment by Korporal** [comment]
@miloush - I'll take a look there as I begin to look into this subject, I may have a simple solution to your problem...

**Comment by Korporal** [comment]
@CyrusNajmabadi @YairHalberstadt  - So I decided to spend some time this morning looking into writing an analyzer, somewhat enthusiastic and having a no pressure day ahead of me. But lo and behold it looks like VS 2019 does not provide a project template for this, I was reading this:

https://www.meziantou.net/2018/12/17/writing-a-roslyn-analyzer

VS 2019 has no project type "extensibility" only "extensions" are these the same? no idea. The list of offerings when one chooses "extensions" does not include analyzers and searching for templates yields nothing.

Do you begin to see what I mean about the increasing burden on developers? I must now push my mind onto my "stack" and begin a hunt for "Can I write an analyzer in VS 2019?" who knows what I'll find...

**Comment by Korporal** [comment]
Ha, typical:

"@Neme12 any reason you still using the VSIX instead of NuGet package? We are very likely not going to support this VSIX on VS2019 and recommend everyone to use the NuGet package instead."

How about because VS 2019 offers me the option!!! - Jeez.

**Comment by miloush** [comment]
Make sure you have the .NET Compiler Platform SDK checked 

![image](https://user-images.githubusercontent.com/10546952/57196077-9db26f00-6f59-11e9-8260-30d507726a61.png)

Then you will get the analyzer template:

![image](https://user-images.githubusercontent.com/10546952/57196084-bae73d80-6f59-11e9-88d4-60d29508943c.png)

Unfortunately it doesn't have any tags, so filtering will hide them.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi - Perhaps an analyzer is indeed the way to go, but developers today are burdened with work by the truckload and learning yet another library, yet another API, debugging it, proving it to be correct, testing it all add up.

Yes.  But this can at least spread out the burden to a capable and intelligent community.  Instead, of making everything bottleneck ed on a team that literally has +10 years of work in front of them already at a bare minimum.

> The industry is currently burdened by a vast array of languages far more than 20 years ago, there are hundreds of "APIs", REST, MVC, Dapper, Typescript, .Net Core, .Net Standard, Owin, C# 8, Docker and VS 2019 full of bugs then even more stuff with weird names like Bouncy Castle (for f***'s sake!).

And that's a good thing.  It gives lots of tools and options for solving problems, instead of being dependent on someone else having the time and resources to solve that problem for you.  Right now, there is likely to be no way this would happen from the LDM.  So hte options are:

1. not have it and not have a way around that.
2. not have it, but have a way to solve things.

We invested in '2' so that at least people would have a way forward.  You may not like that option, but that's not going to change teh calculus at all.  

> Then we have users and companies that are migrating to the "cloud" with Azure, DevOps, ADFS and many many other challenges, these are the kinds of things that I face weekly and every few weeks something else comes along.

I think it's valuable for developers to be polyglots and to have mastery of many APIs.  I consider it necessary for our profession and to deal with the myriad challenges thrown our way.  In that regard i don't see a problem here.   Personally, i've spent the last 18 months getting myself very knowledgable about the entirety of several the different cloud stacks out there (i.e. AWS/Azure/GCP).  A few years back, i spent a ton of time learning mobile development.  etc. etc.

> So the oft repeated and rather glib "just write an analyzer" isn't always an appealing solution.

I don't see why it's more appealing to have it be done by the LDM and the rest of the team when there are vastly more important things to work on either...

> I've developed real compilers and optimizers and code generators and I'm sure I could jump onto the analyzer stuff a bit easier than most, but I haven't yet, why? I have simply more to do each week than I can achieve that's why.

The same holds for everyone on roslyn.  

> Perhaps if you worked for a user of these technologies rather than a creator of them you'd begin to understand.

I don't know what this means.  I don't work for MS.  I work for another company.  But i routinely write analyzers/fixers/etc.  I even contribute a whole lot back to Roslyn to help *other* people out as well.

> Consumers of these technologies are being swamped in work, which creates further deadline pressure, reduces education time and so negatively impacts quality and so on, I do wonder sometimes if this industry actually is moving forwards or if this is an illusion fostered by the firms that create "new" stuff all the time.

I am swamped with work myself.  I have literally months of work costed out in front of me.  But i still contribute and do what i can.

**Comment by HaloFour** [comment]
That would still be a breaking change.  It's normal to use values outside of the enums range for flags.  The compiler also really can't prevent that as it doesn't know what values an arbitrary `int` could be.  You'd have to rely on the runtime inserting some kind of validation logic that could throw at runtime.

**Comment by emlai** [comment]
We now have CS8509 and CS8524 for customizing the exhaustiveness checking of switch _expressions_.
Should we have similar error codes for switch _statements_ as well, for consistency?

**Comment by emlai** [comment]
[This](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/patterns-objects#:~:text=CS8524%20indicates%20the%20switch%20expression%20doesn%27t%20cover%20all%20possible%20inputs) is the only mention of CS8524 I could find in the official C# docs.
