### ISSUE TITLE
default constructor to initialize not nullable reference types

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2480]
With nullable reference types implementation, we should as well get a way to create a default instance so the type will actually never be null.

Example syntax:

```cs
public class Foo
{
    public bool Active { get; set; }
    default Foo() 
    {
        Active = true;
    }
}

var foo = default;
Console.WriteLine(foo.Active); // true
```

This would also be useful for long name classes/with too many generic arguments, to reduce verbosity. example:

```cs
public class SomeClass
{
    private readonly Dictionary<SomeAnotherClass, SomeLongNameClass _dict = default;
    // this would create an empty dictionary rather than assign null with #nullable enable
    // and we don't have to write new Dictirionary<..., ...>()
    // default ctor may take parameters as well (?)
}

**Comment by HaloFour** [comment]
You can already use `new` for this:

```cs
public class SomeClass
{
    private readonly Dictionary<SomeAnotherClass, SomeLongNameClass> _dict = new();
}
```

The problem with trying to do this with `default` is that it wouldn't work in the places where you would be mostly likely to use `default`, namely with generics.

**Comment by Logerfo** [comment]
@HaloFour about that... did the "target-typed new expression" feature get postponed to 8.x?

**Comment by johnkellyoxford** [comment]
no, I want default to mean default. But maybe there should be warnings around it

**Comment by cgbeutler** [comment]
The keyword is working as designed. Currently `default` is setting up the reference to its default, not the class that that reference refers to. It's proposed that in C# 8 there will be non-nullable reference types. I imagine that under that change, the default keyword would work in this proposed way. Until then, you can almost image every object that refers to a class as being a nullable-reference like `string?`, but that the `?` is currently implicit. With the implicit null-ability, the `default` is null because the type is, in a way, `Nullable<string>` (not really, but conceptually.) Currently, to get the behavior you want, you can define a `struct` instead of a `class`. Course, that's a whole different discussion. A struct's default, though, is a struct built with `default` called on all it's members.

**Comment by YairHalberstadt** [comment]
@cgbeutler

default will not change its behaviour in C#8

Instead it will simply result in a warning when assigning default to a non-nullable reference type.
