### ISSUE TITLE
[Proposal] Static extension methods

### ISSUE THREAD

**Issue by ashmind** [dotnet/csharplang#2505]
#### Problem

In modern C#, it is possible to add extension methods that imitate instance methods, but not static methods.

There are quite a few use cases for this:
1. Direct API extension for popular static classes
   `Console`, `Assert`, `Path`, etc.
   This can be worked around if library authors switch to statically imported instance properties instead of classes, but it is extremely unlikely to be the right design choice for BCL APIs.
2. Polyfilling future functionality
   At some point, TPL team was using `TaskEx` for future previews, since they couldn't extend `Task` -- complicating migration from preview to the real thing. And if someone wants to implement new `Task.FromException` in pre-4.6 .NET -- they are out of luck as well, unless they choose a different class name.
#### Design

Given the syntax currently used by instance methods, extending this to static doesn't feel straightforward. 

One simple idea could be just to extend `[ExtensionAttribute]`:

``` csharp
[Extension(typeof(Task))]
public static Task FromException(Exception ex) { ... }
```

But please feel free to propose better designs. And I assume C# team did have some potential design for this in mind then choosing the instance syntax?
#### Pros
1. Allows extension of static APIs, which is currently awkward
2. Allows polyfilling of static APIs, which is currently impossible
#### Cons
1. I don't have a good syntax proposal (though I personally would be just as happy with an attribute)
#### Community
1. StackOverflow: [Can I add extension methods to an existing static class?](http://stackoverflow.com/questions/249222/can-i-add-extension-methods-to-an-existing-static-class) has 247 votes, 45 :star:
2. UserVoice: [C# support static extension methods like f#](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2060313-c-support-static-extension-methods-like-f) has 549 votes

**Comment by YairHalberstadt** [comment]
Related: #1988

**Comment by theunrepentantgeek** [comment]
See also #1711 - Exploration: Roles, extension interfaces and static interface members

**Comment by Korporal** [comment]
> #### Problem
> In modern C#, it is possible to add extension methods that imitate instance methods, but not static methods.
> 
> There are quite a few use cases for this:
> 
> 1. Direct API extension for popular static classes
>    `Console`, `Assert`, `Path`, etc.
>    This can be worked around if library authors switch to statically imported instance properties instead of classes, but it is extremely unlikely to be the right design choice for BCL APIs.
> 2. Polyfilling future functionality
>    At some point, TPL team was using `TaskEx` for future previews, since they couldn't extend `Task` -- complicating migration from preview to the real thing. And if someone wants to implement new `Task.FromException` in pre-4.6 .NET -- they are out of luck as well, unless they choose a different class name.
> 
> #### Design
> Given the syntax currently used by instance methods, extending this to static doesn't feel straightforward.
> 
> One simple idea could be just to extend `[ExtensionAttribute]`:
> 
> ```cs
> [Extension(typeof(Task))]
> public static Task FromException(Exception ex) { ... }
> ```
> 
> But please feel free to propose better designs. And I assume C# team did have some potential design for this in mind then choosing the instance syntax?
> 
> #### Pros
> 1. Allows extension of static APIs, which is currently awkward
> 2. Allows polyfilling of static APIs, which is currently impossible
> 
> #### Cons
> 1. I don't have a good syntax proposal (though I personally would be just as happy with an attribute)
> 
> #### Community
> 1. StackOverflow: [Can I add extension methods to an existing static class?](http://stackoverflow.com/questions/249222/can-i-add-extension-methods-to-an-existing-static-class) has 247 votes, 45 ⭐️
> 2. UserVoice: [C# support static extension methods like f#](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2060313-c-support-static-extension-methods-like-f) has 549 votes

@ashmind - What might be a better alternative is to add support to C# for allowing a static class to inherit from some other static class. I don't know the full implications of this but it would solve your problem at a stroke.

**Comment by tamerfahmy** [comment]
It is a great idea, many times I need to add an extension method to static classes for example classes in a library where I reference in my project and can't control its source code, Also as @HaloFour mentioned as an example `IEnumerable<T> or Task<T>`.

@Korporal  Your alternative is good but I think it is another topic or can be used in different area and also I guess the scope will be bigger having extension method on Types, For static class extensions I think it will be better to invoke extension method from the original Type. To clarify more I would say you proposal to have something like this:

```C#
public static class MyConsole : Console
{
	public static void WriteLine(string message, ConsoleColor color)
	{
		Console.BackgroundColor =color;
                Console.WriteLine(message);
	}
}
```
And will be used like this:

```C#
public class Program
{
	public static void Main()
	{
		MyConsole.WriteLine("Hello World", ConsoleColor.Red);
              // Console.WriteLine("Hello World", ConsoleColor.Red);   We can't invoke this method by the base type
	}
}
```

We must call this new method from the new static class type not from the parent class type.

Regarding the syntax it can be by replacing the "this" keyword from the instance extension syntax to be "static" and without parameter name, while here you don't need an instance of an object, only the type is required to be defined.

```C#
public static class ConsoleExtensions
{
	public static void WriteLine(static Console, string message, ConsoleColor color)
	{
		Console.BackgroundColor =color;
                Console.WriteLine(message);
	}
}
```

**Comment by cyraid** [comment]
The static instead of this might be nice, as it brings people in the same mindset as "hey, I wonder if static methods are allowed" .. One of my instincts was to try "static". Seeing as it's in the same line of thinking.

**Comment by gsuberland** [comment]
Adding my support for this proposal. I'm working on extensions for the `Process` and `Thread` classes to add support for managing processor groups, and would like to overload the static `Create` methods on both to accept a group affinity. As noted by others, I could create a helper or wrapper class, but that would hinder discoverability.

**Comment by toddlucas** [comment]
@gsuberland This syntax is similar to explicit interface implementation. Since static classes cannot implement interfaces, there would be no overlap with that case (even after C# 8 introduces static interface members). It seems logical from a syntax perspective, and it's consistent with an existing feature.

**Comment by cyraid** [comment]
What's wrong with a nameless parameter only for this case? It wouldn't make too much sense to have an alias/named parameter.. "static Console SomeConsole" then using SomeConsole.Log() makes you have to remember 'hey look, my naming rules suggest a capital at the front in this case means it's a class.. And it must exist.. Wait no, it's just for this extension method'. Then you also break your parameter naming rules.

From the example above, if you're accessing other Console static methods, you already have access to (eg. Console.StaticMethod and Console.SomeOtherStaticMethod).

For refactoring, it'd only make sense too, if you'd want to rename Console (as an example), at this point you'd want to rename the entire class anyway.

**Comment by cimonfortierg** [comment]
Adding my 2 cents and my support to this proposal. This is a feature that I've wanted for a while and I'm happy to see that I'm not the only one.

Last comment is 5 months old, so not sure how much progress has been made on this. I've noticed that no one has suggested using generics syntax. Is it because the idea is ridiculous? Because I would see something like
```
public static class ClassExtensions {
	public static void DoSomething<SomeClass>(...) {...}
}
```

Somehow to me this seems clear and clean to read.

**Comment by CyrusNajmabadi** [comment]
That syntax is already legal today and means something entirely different.

**Comment by cimonfortierg** [comment]
Right! Thank you for pointing it out.

**Comment by CyrusNajmabadi** [comment]
Absolutely! :)

**Comment by JoshFlash** [comment]
I'm definitely in favour of the original proposition to use Attributes in order to achieve this. I'd be happy with either 
`[StaticExtension(typeof(Console)]` or `[Extension(typeof(Console))]`
Seeing as the compiler automatically emits ExtensionAttribute for extension methods, anyway, it would make sense to at least implement it using this and then try to reach a concensus on the nicest syntax sometime in the future.

**Comment by KoromaruKoruko** [comment]
i would say, in regards to how we should implement something like this, there's a big issue that isn't being explored much. Currently best practice is you create a type called FooExtensions and fill it with extension methods such as
```csharp
public class FooExtensions {
   public static String Bar(this Foo) => "Bar";
}
```
the problem is that extension methods seems to have been an after thought and no matter how you make the syntax now it will be vastly different from how instanced extensions work.

And so i propose we rewrite how extension methods are written, still allowing the old way for compatibility's sake just throwing a warning that it should be updated to the new way.

As for the new way im all for creating an Extension class like so.
```csharp
public extension class Foo {
    public String Bar() => "Bar";
    public static String StaticBar() => "Bar";
}
```
Not allowing overloading, nor replacement of any original functions.

In regards to overcoming the issue of multiple extensions overlapping and causing problems, we should use the same ambiguity rules as Duplicate Type Names, if both extension classes are in the same namespace throw an error in the extension class, if they are in separate namespaces but are called we could use this form of syntax to fix it.
```csharp
// Foo.cs
namespace Foo {
    public class Foo { }
}
// Bar.cs
using Foo;
using System;
namespace Bar {
    public extension class Foo {
        public String Bar() => "Bar";
        public static String StaticBar() => "Bar";
    }
}
// Bla.cs
using Foo;
using System;
namespace Bla {
    public extension class Foo {
        public String Bar() => "Bla"; // ILegal: Ambiguity with other Extension class in same Namespace 
    }
    public extension class Foo {
        public String Bar() => "Bla2"; // ILegal: Ambiguity with other Extension class in same Namespace 
        public static String StaticBar() => "Bla2";
    }
}
// Gha.cs
using System;
namespace Gha {
    public extension class Foo { } // ILegal: Type Not Found
}
// Main.cs
using Bla;
using Bar;
namespace Program {
    public static class Program {
        public static void Main() {
            Console.WriteLine(Foo.StaticBar()); // ILegal: Ambiguity with Extension class in Bar & Bla
        }
    }
}
// Main2.cs
using Bla;
using Bar;
using Foo.StaticBar from Bla;
namespace Program {
    public static class Program {
        public static void Main() {
            Console.WriteLine(Foo.StaticBar()); // uses StaticBar from namespace Bla;
        }
    }
}
```

As for how this should look inside the assembly i'd say we should keep the old way for compatibility but now implement a simple Attribute that goes into a Type for example:
```csharp
namespace Bar {
    public extension Foo { }
}
```
would become (in IL)
```csharp
namespace Bar {
    [ClassExtension]
    public class e_Foo { }
}
```

Of course this isn't the end all solution, there might be a case where someone wants to call `StaticBar` once from `Bla` and another time from `Bar` (see: the big code blob) and so the `using X.Func from Namespace` isn't really a good solution, and in those nesh cases we would need to implement another form of syntax or we would need to use a better way of identifying when to use function X from extension Y.

**Comment by bazzilic** [comment]
Oh man, five years of discussions on what the syntax should be like, and we still can't do static extensions... Will this ever be added? Seems like everybody is supportive of the feature. IMO, having the feature with mediocre syntax is better than not having it with an amazing, well designed, state of the art syntax.

**Comment by CyrusNajmabadi** [comment]
> Will this ever be added? Seems like everybody is supportive of the feature.

There is no one on the ldm who thinks this is worth championing right now.

**Comment by bazzilic** [comment]
So... is that a "no"? Is there anything us people not on "ldm" can do?

**Comment by HaloFour** [comment]
@bazzilic 

I believe that static extension members falls under this category: #1711

It's an area that the LDM has expressed a lot of interest in pursuing, but it's a part of a larger body of work and it's unlikely to be tackled separately because settling on a syntax or behavior for extension members now could limit what the language can do in the future.

**Comment by CyrusNajmabadi** [comment]
> So... is that a "no"?

it is not a 'no'.  It just means that no one is interested in this currently, so it's not likely to happen soon.

**Comment by darrenoakey** [comment]
> I don't know if this is possible at the CLR level, but would it be enough if the compiler would not treat as ambiguous if the same fully qualified name of exists in more than one assembly?
> 
> I'm failing to see the benefit of:
> 
> ```
> Console.WriteColorodeLine(ConsoleColore.Balck, "test");
> ```
> 
> Over:
> 
> ```
> MyConsole.WriteColorodeLine(ConsoleColore.Balck, "test");
> ```
> 
> Specially now that we have static imports.

the benefit is discovery

**Comment by darrenoakey** [comment]
the problem seems to be the syntax - nobody can think of a correct one.  however.. two things:

a) I don't think people really understand what the value of this is.  it's not just a nice to have "convenience".  I reckon a lot of people here work in an environment where stuff is thought about, planned etc.    for the last 20 years I've been working environments where you have a team of like 16 devs coding full time every day - people leave, new people join.  anyone who feels like adds a new library whenever they want.  _no one_ is on top of even a tiny percentage of the code.

bottom line - if a helper method doesn't come up when you hit "." - then it doesn't exist.   There is zero chance someone will ever notice it.   Which is why we end up with tens of implementations of each thing.  Yes it would be better if the process was fixed - but that's life in corporate development.  the _only_ thing management cares about is how quickly a dev says that task 123211 is "done".  

Extension methods solve the discovery problem.   Someone hits "." and goes "bonus - there's something there that seems to do what I need" - and therefore are the single greatest tool for keeping the code in check, because suddenly someone who just started yesterday has a chance of using that helper function to create a copyright string that I wrote six years ago.

b) given that the problem is the syntax.... people like me just want the functionality - so pick a temp one that absolutely doesn't affect any future guidelines - eg I'm completely happy with

```
  #BEGIN_WE_AT_MICROSOFT_DONT_AGREE_WITH_THIS_CODE_PLEASE_DONT_USE_IT
   string STATIC_EXTENSION_METHOD_FOR<String>( int x) {....}
   #END_STUPIDITY
```
as long as it works

**Comment by darrenoakey** [comment]
also - there's another point that should be considered.   With almost every other language feature we ask for - there's some way of achieving the functionality ourselves.  I never code c# without a weaver, and can change almost anything - c# generators allow us to produce lots of things.   So most "problems" we have with C# have some sort of workaround.  We can achieve what we need to achieve in some way, even if that way is horrible - it can hide in our library and whoever is using our code doesn't have to care.

in this case - there is _no way_ - no workaround I can do - that allows me to add another factory method to system.String - I have no alternatives.   It is just not possible for me to create a c# library that does that. 

I'd argue that should raise the importance of this over anything which is just a shorter syntax, or cleaner way of doing something we can already do?

**Comment by stanislavorlov** [comment]
I'm voting for this feature. I want to add a static extension method for `JObject `called `TryParse()`. In this case all exception handling and e.t.c. can be added once in this method. And there will be the ability to call `JObject.TryParse(...)` once rather than a lot of `try/catch`. The same feature can be found useful also for `string`, `DateTime` and other data types.

**Comment by sgf** [comment]
i need this feature.

**Comment by gdalsnes** [comment]
Oh my, only 12 years since I added this suggestion on Microsoft Connect with suggested syntax 
public static TResult Method(static Type).
Response was like "What do you need them for? I am not even sure what you mean by static extension methods. Where would you use it?"
I see nothing has changed.

**Comment by CyrusNajmabadi** [comment]
@gdalsnes see https://github.com/dotnet/csharplang/issues/2505#issuecomment-634219800

No one on the team considers this important enough to explore the design or change the language.   There are many lang change requests that are that old (or older).  If we don't think it's worthwhile then they won't happen :-/

**Comment by toddlucas** [comment]
It really would be nice if GitHub allowed people to vote on issues. I understand that this will probably be addressed in the future with the roles work.

The problem is that the language has had this fundamental asymmetry since C# 3.0. Someone thought that extension methods were important enough to add at that time (leaving aside discussion of the consequences of the syntax choice). The language itself (indeed a large number of OO languages) have a concept of instance methods and class (static) methods. The runtime makes significant use of static methods. But this fundamental duality is not carried over to extension methods. Thus, the language has an unfortunate asymmetry that poses problems for non-runtime engineers who are designing their own libraries or APIs.

It would seem that, in lieu of a near-term syntax decision, adding or updating an attribute might be a workable solution. This is how VB handles extension methods.

**Comment by CyrusNajmabadi** [comment]
> It really would be nice if GitHub allowed people to vote on issues. 

Github does allow people to vote on issues.  Thumbsup/down is what is used for that.

> But this fundamental duality is not carried over to extension methods. 

Sure.  I think what i'm trying to say is: just because something is true, and people don't like that, doesn't mean we think we would ever address that.

i.e. our goal is not that language features should prioritize "unfortunate asymmetry" or will eliminate inconsistencies with "fundamental dualit[ies]".  Our goal is to work on the features we think will be the most valuable for the ecosystem.  This means, till the end of time, there will likely be inconsistencies that never get changed.  

To me, this literally just does not seem important in the very narrow slice of issues that it covers.  I'd rather a much more full featured approach that covers a broad set of concerns with a unified and composable design rather than a one-off feature here. :-/

**Comment by darrenoakey** [comment]
I get what you are saying (which is literally "we care about our priorities, and couldn't give a **** about yours") but honestly to some of us it's _really_ important - I'd swap it for every other unimplented feature I've seen combined - because as I mentioned before - unlike almost every other feature on the pending list - there's just no other way of doing it - it's not like a more convenient way of doing something that's possible - it's just completely impossible for me to apparently add a method to "String".

but what gets me a bit - is that unlike a lot of things that require a lot of thought to implement well, grow the language etc - this has such tight bounds on it in terms of ramifications - it has to be the easiest feature in the world to implement - ie bung them in a map, and look it up when resolving method calls, and you are done?

**Comment by HaloFour** [comment]
> (which is literally "we care about our priorities, and couldn't give a **** about yours")

Everyone has a different set of priorities.

> there's just no other way of doing it - it's not like a more convenient way of doing something that's possible - it's just completely impossible for me to apparently add a method to "String".

You still couldn't.  The method would exist somewhere else.  It would have to.  At most the compiler could pretend that the method existed on `string`, but actually emit a call to somewhere else entirely.  You don't need `String.Foo()`, you could write `MyString.Foo()`.   This is unlike extension methods where the intent was to be able to write a fluent API on top of existing types.  That's not something you can do with static types.

**Comment by CyrusNajmabadi** [comment]
> but honestly to some of us it's really important - I'd swap it for every other unimplented feature I've seen combined 

That holds true for every user  :-/


> we care about our priorities, and couldn't give a **** about yours

you're free to see it that way.  However, unless we accept every feature that people want, we invariably will be rejecting things and that will certainly always make people unhappy.  

I'ts actually worse than that.  Even if we took every feature, that would still make people unhappy due to:
1. some people not liking the features we take
2. some people not liking that we're changing the language so much

Every choice we make will *always* make people unhappy.  That includes both doing features and not doing features.  So no matter where you land, you will almost always end up unhappy unless you happen to agree with LDM on every decision.

Note: i'm on the LDM and i'm often unhappy.  My own proposals get shot down, and the team routinely makes decisions i disagree with.  This is how any sort of process is going to work with any project of complexity and any user base this large.

**Comment by darrenoakey** [comment]
>. You don't need `String.Foo()`, you could write `MyString.Foo()`. This is unlike extension methods where the intent was to be able to write a fluent API on top of existing types. That's not something you can do with static types.

??? this is exactly the same as extension methods - it's just a discovery method for helper functions - and of course you can do it with static types.   What if I want to create String.Repeat( "A").Times(20).   Or JObject.ParseString("...") ... or List<String>.From( "a", "b", "c")...   Literally _any_ point you can make about extension methods, you can equally apply to justify static extension methods.

however - while it's nice to be able to add creation methods to objects like string or json or whatever - the #1 reason I want it is things like pluggable interfaces.   Suppose you are making a graphics library for instance where you support differnet formats - so you create an interface GraphicsFormat, and you have a bunch of included libraries all of which make formats available.  There's currently no way of advertising which formats are available.   If you had this, then you each format could just create an extension method, so if someone says "GraphicsFormat."  - you get a list of creation functions.  The alternative is to have to have some _instance_ somewhere, so you end up with an interface, some static creator with a function on it that returns some other pointless interface, which _then_ can be extended - so three class definitions where one would do.

**Comment by CyrusNajmabadi** [comment]
> Literally any point you can make about extension methods, you can equally apply to justify static extension methods.

That's not really true.  The major reason we needed extension methods was that Linq was pattern based.  i.e. when you do `from x in y select x.Count` that gets translated to `y.Select(x => x.Count)`.  As such, thre needed to be a way to have a method (like 'Select') show up on a type that didn't already have it.  This was critical as we needed this for IEnumerble, a type that it would have been impossible to add member to back then (DIM was flat out impossible).

The same situation does not hold for static extensions.  There were no scenarios then, or now, where this functionality is required.  I get that from an organizational or discovery perspective it woudl be nice-to-have.  But it lacks any sort of 'necessary' justification like what fell out from Linq.

**Comment by CyrusNajmabadi** [comment]
> so three class definitions where one would do.

This honestly isn't really a compelling reason for me.  `GraphicsFormat.Factory.CreateXXX` seems totally fine.  I get why you would prefer jut `GraphicsFormat.CreateXXX`, but it's such a minor win for me that almost anything else would have higher priority.

**Comment by HaloFour** [comment]
@darrenoakey 

> ??? this is exactly the same as extension methods - it's just a discovery method for helper functions

It's not exactly the same.  Static extension methods must always be the root of the expression.  Without static extension methods the worst thing is that you have to reference a different type name.  Without instance extension methods you have to turn your entire series of calls inside out.  It has a much bigger impact.

**Comment by darrenoakey** [comment]
I get what you are saying - but it's not as simple as that.  It's all about discovery.  I work in a world where you typically have ~16 devs adding code to a codebase all day every day.   No one knows even a tiny percentage of it  - if stuff doesn't come up in intellisense, it doesn't exist.    It's not that GraphicsFormat.Factory.Create is so much worse than GraphicsFormat.CreateXxx - it's that you _can't_ do GraphicsFormat.Factory...   In Java you can - because you can add static stuff to an interface (which I also want) - but in C# - just like in reactive world, you have to name it something different and end up with something horrible like an IObservable interface, but a completely different class Observable with all the creation methods on it.

and guess what... 9/10 developers will never even have the faintest clue that other creation class exists - just like half the people in the real world who work with reactives and iobservable every day have never heard of the the Observable class (I see it constantly).  Unless something magically comes up when you hit "." and you go "oh cool - maybe I should use that" - it might as well not exist.

**Comment by CyrusNajmabadi** [comment]
>  It's all about discovery.

If it's all about discovery, then i would not do a language feature *at all*.  I would instead do an intellisense feature that helps out with stuff like this. i.e. `[IncludeMeIn(typeof(Console))] static class NiftyConsole`

Now, those mthods could be shown in `Console`, but completing it would rewrite the code to `NiftyConsole.XXX`.  

> but in C# - just like in reactive world, you have to name it something different and end up with something horrible like an IObservable interface, but a completely different class Observable with all the creation methods on it.

I don't really know what this means.

**Comment by gdalsnes** [comment]
"If it's all about discovery..."
Yes, it has always been about discovery/intellisense. But getting Foo() as intellisense on string and this suddenly changing to MyStringHelperExtensionClass42.Foo() I think we can all agree is insane.

**Comment by CyrusNajmabadi** [comment]
> I think we can all agree is insane.

i don't agree it's insane.  indeed, we're doing something similar to this right now.  i.e. we have a community PR open that says:

> if i type `foo.` i will get shown items like `operator (string)` which, if i complete, will rewrite the code to `((string)foo).`

effectively, completion items proffering things that cause rewrites of the code on the left.

**Comment by gdalsnes** [comment]
That is a  different matter. And following this logic then instance extension methods should have been rewritten as well (for concistency).

**Comment by darrenoakey** [comment]
Id be very happy with that.
When can we have it? :)

**Comment by HaloFour** [comment]
@gdalgas 

> And following this logic then instance extension methods should have been rewritten as well (for concistency).

Extension methods also offer substantially more benefits when reading code, as again, fluent APIs with extensions need to be written completely inside out.  If extension methods were instead written as a code completion replacing the methods with static invocations then any non-trivial LINQ query would be virtually impossible to read.  That's not the case with static extension methods because they can only ever apply once to the root of the expression, and at worst the name of that root static type is different.

**Comment by gdalsnes** [comment]
But I think the problem is not that this is difficult to implement but rather you see no use for it. Its the opposite problem of me: I originally saw no use of instance extensions methods but was missing static extension methods. And as I said 12 years ago: you just have to trust us, this is sorely needed:-D

**Comment by gdalsnes** [comment]
But if we can have intellisense and rewriting, it would help a lot, if alternative us nothing:-)
 Thanks.

**Comment by CyrusNajmabadi** [comment]
> And following this logic then instance extension methods should have been rewritten as well (for concistency).

Instance intellisense wouldn't have helped.  The language had to define the rules so that `x.Where(y => ...)` could bind as that's the syntactic translation the *language* performs for `from y in x where ...`.  There's no intellisense/IDE in that scenario.  It's just C# code that needs rules in the language to support.

**Comment by CyrusNajmabadi** [comment]
> And as I said 12 years ago: you just have to trust us, this is sorely needed:-D

:)

**Comment by darrenoakey** [comment]
> The same situation does not hold for static extensions. There were no scenarios then, or now, where this functionality is required. I get that from an organizational or discovery perspective it would be nice-to-have. But it lacks any sort of 'necessary' justification like what fell out from Linq.

yeah - but you get what you are saying...  if you stand back, and reason about them - then static or instance extension methods are _the same thing_... they are identical in every way.   What you are saying is that you only _needed_ one of them for linq, so only implemented one of them - but there are heaps of us who need the other one.

Are you saying tht the only point of extension methods is to implement linq?  For me it's all about discovery - out of every single feature _ever_ added to c# (with the possible exception of generics) - I value extension methods the most - and the majority of code I write is in them.   It's all about the DSL.  Some people like the idea of a language that you can build a real DSL - I don't really, because there's too much weirdness - but I _do_ like the idea of using the existing language structures to sort of form a dsl, and I do like the idea of trying to split off any functionality that's programming related - eg wrapping a string - from business functionality - eg show the description on the screen.   I reckon when you really look at it, and separate it out - at least 90% of code has nothing to do with the specific problem you are solving, but in _how_ you solve it - ie building hundreds, (thousands?) of little lego blocks that _do something_.   And when you code like that - the biggest question is... where do you put them.  Where do they fit in my language.   And almost always the answer is to hang them off existing classes.   

which is currently fine for everything except creation methods.  Or anything where the existing api is static (eg Console).  

I guess what I'm trying to say is that for me, and the way I code - we aren't talking the occasional edge case.  I'd be coding up one of these every week

**Comment by CyrusNajmabadi** [comment]
> Are you saying tht the only point of extension methods is to implement linq? 

yes. :)   that was literally the reason for it.

>  if you stand back, and reason about them - then static or instance extension methods are the same thing... they are identical in every way. 

I honestly don't agree. With static methods there's no concept of a dynamic receiver.  You literally can just state the receiver.  There's no dynamic pulling in of a separate type that you'd then pattern match a member from.  Extension methods are for something else entirely.  It's so you can write `Where` and have that be found in a different place depending on the receiver type and so that can be found even if the original type didn't have that.

No such dynamic sort of operation exists for static.

**Comment by CyrusNajmabadi** [comment]
> the biggest question is... where do you put them. 

I guess that hasn't seemed like much of a problem in my experience.

> eg show the description on the screen

`Screen.ShowDescription(...)` ?

**Comment by CyrusNajmabadi** [comment]
note: static extensions would make sense to me if we ever get around to static-virtuals.  Then i could see the benefit of needing to find the actual impl for any particular type either as a virtual or as an extension.

**Comment by toddlucas** [comment]
Another argument in favor of an attribute based solution is that any future syntax based solution should allow for the addition of instance and static extension properties. Extension properties have only been touched on here. There's a discussion at #514 that covers this and more.
