### ISSUE TITLE
[Proposal] Make events first class citizens in C#

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/csharplang#2506]
Currently in C# there is no clean way to pass an event around. There are workarounds, such as passing delegates for subscription/unsubscription, or using reflection, but they're not convenient at all. I want to be able to write something like this:

```
Task whenClicked = WhenEventRaised(button.Click);
```

The only two operations currently allowed on events are subscription and unsubscription. We could add a third: conversion to an `EventDescriptor` object (or some other appropriate name).

```
public class EventDescriptor<TDelegate> // note: ideally, having a delegate constraint here would be better...
{
    private readonly Action<TDelegate> _subscribe;
    private readonly Action<TDelegate> _unsubscribe
    public EventDescriptor(Action<TDelegate> subscribe, Action<TDelegate> unsubscribe)
    {
        _subscribe = subscribe;
        _unsubscribe = unsubscribe;
    }

    public event TDelegate Event
    {
        add { _subscribe(value); }
        remove { _unsubscribe(value); }
    }
}
```

Now the `WhenEventRaised` method could have the following signature:

```
public static Task WhenEventRaised<TDelegate>(EventDescriptor<TDelegate> @event);
```

And the compiler would implicitly transform this:

```
Task whenClicked = WhenEventRaised(button.Click);
```

into this:

```
Task whenClicked = WhenEventRaised(
    new EventDescriptor<EventArgs>(
        h => button.Click += h,
        h => button.Click -= h));
```

**Comment by YairHalberstadt** [comment]
Related to @svicks suggestion for first class properties: #1901

**Comment by TonyValenti** [comment]
Thoughts RE this and #1901 -
it would be great if you could reference the get, set, add, and remove handlers as follows:
object.Property.get;
object.Property.set;
object.Event.add;
object.Event.remove;

**Comment by weitzhandler** [comment]
I also feel this is an important area that could reduce a lot of tedious and redundant verbosity, plus remove many limitations and allow extension methods to run on events.

But I don't really like the `Task WhenEventRaise` idea by the OP.
To me there should be a `System.EventDescriptor` that is a reflection alternative to `EventInfo`, so that there is 

```c#
class EventDescriptor
{
  public void AddHandler(Delegate handler);  
  public void RemoveHandler(Delegate handler);
}

class EventDescriptor<TDelegate> : EventDescriptor
where TDelegate : Delegate
{
  public void AddHandler(TDelegate handler);  
  public void RemoveHandler(TDelegate handler);
}
```

This way we can pass events around and attach to them. Also introduce ex. methods on events, so we could do 

```c#
IObservable<EventPattern<PropertyChangedEventArgs>> observable = 
  myObj.PropertyChanged.ToObservable()`
```

But alternatively, at least if you'd removed the limitation of addressing an event from outside its owner class without `+=` or `-=`, we could just use reflection if we chose to, so that we could go:

```c#
public static void ToObservable<TSender, TDelegate>(
  this TSender sender,
  Expression<Func<TSender, TDelegate>> eventSelector) 
    where TDelegate : Delegate 
{
  /* getEventInfofrom Linq expression and attach/detach System.Rective handlers */ 
}

//usage
IObservable<EventPattern<PropertyChangedEventArgs>> observable =
  myObj.ToObservable(obj => obj.PropertyChanged);
```

**Comment by weitzhandler** [comment]
I also feel this is an important area that could reduce a lot of tedious and redundant verbosity, plus remove many limitations and allow extension methods to run on events.

Like people said above, I agree that `IObservable<T>` would make a perfect bridge here. It's a native .NET type and has matured and is covered with zillion of functionality anywhere.
This will bring C# to a new era.

But alternatively in the meantime, at least if you'd removed the limitation of addressing an event from outside its owner class without `+=` or `-=`, we could just use reflection if we chose to, so that we could go:

```c#
public static void ToObservable<TSender, TDelegate>(
  this TSender sender,
  Expression<Func<TSender, TDelegate>> eventSelector) 
    where TDelegate : Delegate 
{
  /* getEventInfofrom Linq expression and attach/detach System.Rective handlers */ 
}

//usage
IObservable<EventPattern<PropertyChangedEventArgs>> observable =
  myObj.ToObservable(obj => obj.PropertyChanged);
```
