### ISSUE TITLE
Allow ref assignment in ternary operator and switch expression

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#2507]
```C#
bool isRight = false;
SomeObject left,right;
ref var side	= isRight ? ref right : ref left;
side = new SomeObject(); // assign to left
```

Currently now this code above throw error

`A ref or out value must be an assignable variable [Assembly-CSharp]`

I think it should be available. Is it possible? It should also work with `switch expression` too

**Comment by CyrusNajmabadi** [comment]
Works fine for me as:

```c#
        bool isRight = false;
        string left = null, right = null;
        ref var side = ref isRight ? ref right : ref left;
        side = "whatever";
```

A couple of notes:

1. `left` and `right` must be assigned first.  You can't take a `ref` to something unassigned because you have no idea if it will be read or not.  There's no concept at the statement/expr-level in the language of "this is a ref which must first be assigned before you can read it".
2. You need to write your assignment as `= ref`.  `= ref` is the ref-assignment operator.  It's necessary even if sub-exprs are 'refs'.  That's why you can't do:

![image](https://user-images.githubusercontent.com/4564579/57269684-3968db80-703d-11e9-8130-14a7908a3063.png)

You still have to write it as:

![image](https://user-images.githubusercontent.com/4564579/57269690-42f24380-703d-11e9-9c7f-b21563b20bf5.png)


The same holds here.  So you need:  `ref var side = ref isRight ? ref right : ref left;` 

A bit of a mouthful, but totally supported.

**Comment by CyrusNajmabadi** [comment]
>  It should also work with switch expression too

Can you file a separate issue for that?  Compounding multiple requests into one issue just makes it harder to handle them.

**Comment by Thaina** [comment]
Oh I see, that was unexpected that we need `ref` for all places. I have tried to place `ref` in front before

This syntax is not so intuitive but still fine. I think the `switch expression` should work the same way so I would close this for now

Thank you very much

**Comment by CyrusNajmabadi** [comment]
You're welcome :)  The intuition here is that you can only assign a ref with `= ref`.  That's what ref-assignment is in the language.  

> I think the switch expression should work the same way so I would close this for now

I would personally agree.  :)  It might not happen in the initial release due to time constraints.  but i def think it could happen later down the line.
