### ISSUE TITLE
create array, shorter code

### ISSUE THREAD

**Issue by ChanyaKushima** [dotnet/csharplang#2540]
Now, if we want to create a new array, we may write like this code.
~~~
// arr1 and arr2 are string[]
var arr1 = new[] { "string0", "string1" };
string[] arr2 = { "string0", "string1" };
// both are the same
~~~
But, I want to write faster. So I propose the following syntax.
~~~
// arr is string[]
// this is the same as arr1 and arr2
var arr = { "string0", "string1" };
~~~
The syntax is so useful.
For example...
~~~
// we can write an array like a taple!
int[] M(int a, int b) => { a, b };
~~~
I want this syntax in C#.

**Comment by yaakov-h** [comment]
Personally I'd prefer `[ a, b ]` like many other languages.

This overlaps quite a bit with #414.

In particularly, it would be nice to not have array literal syntax tied to `System.Array`/`T[]`, and instead be usable for many types such as `ImmutableArray<T>` too.

**Comment by ChanyaKushima** [comment]
@yaakov-h, it is sound useful. I agree with it.

**Comment by CyrusNajmabadi** [comment]
> ```c#
// we can write an array like a taple!
int[] M(int a, int b) => { a, b };`
```

This would be highly difficult to parse, as `{` is already a legal start of a block for a lambda/method-body.

**Comment by YairHalberstadt** [comment]
@cyrusnajmabadi
Why? A non empty lambda/method using `{}` must contain a semicolon, whereas an array creation wouldn't.

**Comment by CyrusNajmabadi** [comment]
> Why? A non empty lambda/method using {} must contain a semicolon, 

1. Not necessarily :)  There are constructs without semicolons in the language.
2. I'm not saying that it would be ambiguous.  Just aht it would be more difficult to parse.  For example, `{ some.large().expression<That, Keeps>(going, onAndOn)`.  What is that?  

Also, i'm not happy that `=> {}` would be ambiguous as an empty block, or returning an empty array.  Clearly it couldn't be the latter because of the break.  But it's still unpleasant to me that syntactically this would be inconsistent in this manner.  i.e. if i have `=> { 0 }` and i remove 0, it changes from an expr to a block.

**Comment by kulics** [comment]
@ChanyaKushima 
This feature is supported in my language. [Xs Collection](https://github.com/kulics/xs/blob/master/book-en/collection-type.md)
In fact, it is translated into C# by derivation type.
Many grammars in C# are much simpler in this language.

**Comment by ChanyaKushima** [comment]
@CyrusNajmabadi
In my thinking, `{ 10, 20, ... }` equals `new[] { 10, 20, ... }`. So, `=> { }` has no returns, or `void`. (`new[] { }` is a compilation error.)

**Comment by Richiban** [comment]
This feature doesn't overlap syntactically with https://github.com/dotnet/csharplang/issues/1399, but the desired behaviour is the same.

**Comment by ChanyaKushima** [comment]
@Richiban
I think so, too. But, #1399 looks useful more  than my issue, #2540.
