### ISSUE TITLE
[Proposal] Support tail recursion

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#2544]
For performance reasons, it would be very helpful if some method invocations were to generate tail calls, in which the caller's stack is discarded and replaced by the callee's stack. When the method is calling itself, the compiler can generate a jump to the start of the method.

There are a few ways one might designate that one desires tail calls in the generated code:
1. The compiler could _always_ generate tail calls when applicable.
2. The compiler could generate tail calls when applicable in production builds but not debug builds. Equivalently, the compiler could recognize a command-line option (or project-wide option) that causes the generation of tail calls wherever possible.
3. The language could provide a syntax for tail invocations.
4. The compiler could recognize an attribute on the enclosing method and generate tail calls in the method's body wherever possible.

The advantages of a tail invocation is that it reduces the amount of stack used in a recursive call chain. That may improve performance due to improved memory locality. For some kinds of recursive code, it would allow the code to run with unbounded recursion; that makes it practical (without loss of performance) to replace loops with equivalent recursive code where the recursive code is more clear.

The disadvantages are that it makes debugging a bit harder, as stack frames with tail calls disappear from the call stack. Similarly they disappear from an exception stack trace. If the compiler does it automatically, this would be a behavioral change from previous releases, and would "break" any client that depends on the shape of the stack trace.

**Comment by Korporal** [comment]
Isn't the primary motive for tail recursion to avoid stack overflow? Recursion is the norm in functional languages but far less common in most imperative languages. So just how many people or scenarios would benefit from this?

This sound like a feature that would benefit a tiny fraction of use cases where C# is used.

**Comment by spydacarnage** [comment]
I would use recursion a lot more if tail recursion was a thing we could have

**Comment by gafter** [comment]
@Korporal Many Roslyn compiler failures can be traced to the fact that the compilers are recursive on the shape of the program.  Eliminating unnecessary frames would relax or eliminate many program size and shape constraints that cause the compiler to blow up.  So it would be at least very useful for the Roslyn compiler.  And every user of the Roslyn compiler, even if they don't use the feature directly.

**Comment by AartBluestoke** [comment]
The problem is that the following pattern is fundamentally dangerous unless you can GUARANTEE either:
a) quick termination of recursion (limited by an unknown stack size limitation)
b) an eventual termination, AND tail recursion

Because the first eliminates a large number of use cases (would you annotate a function "probably crashes with stack overflow if passed a list of more than 32k elements, or half that if you use this in ASP.Net")

This feature would be great. A DEMAND for tail recursion or compilation failure/warning? would allow us to actually use "potentially" tail recursive scenarios when you know it could loop 1 million times. 

At the moment even if roslyn reliably supported tail recursion, Using tail recursion would still be a "gosh, i hope this compile actually produces the specific byte code pattern that i *REQUIRE* for sane program behaviour".

When the creator of a program requires specific compile pattern for correctness, it would be helpful if the language/ compiler supports that request.

This results in recommendations to not use tail recursion unless your algorithm is O(log n) (eg https://softwareengineering.stackexchange.com/a/189537/111157  )

Code pattern many people would like to guarantee to be safe:
```
thing f(something){
..
return f(modifiedSomething);
}
```

**Comment by weltkante** [comment]
Recently I'm repeatedly running into this issue when implementing custom awaitables and async primitives. With awaiters you don't have any choice about being iterative or recursive, the `OnCompleted` callbacks force you to be recursive. I could really have used the ability to do a guaranteed tailcall to a delegate in the language.

Just throwing that in as a vote for "there is demand".
