### ISSUE TITLE
Force Inline support  MethodImplOptions.ForceInlining  

### ISSUE THREAD

**Issue by sgf** [dotnet/csharplang#2561]
Force Inline support  by MethodImplOptions.ForceInlining  

[MethodImpl(MethodImplOptions.AggressiveInlining)] is fuzzy uncertainty of conduct.

**Comment by YairHalberstadt** [comment]
The reason is fuzzy is because the JIT simply cannot inline in certain situations. For example a recursive (but not tail recursive) function.

There is no way round this.

**Comment by sgf** [comment]
> The reason it's fuzzy is because the JIT simply cannot inline in certain situations. For example a recursive (but not tail recursive) function.
> 
> There is no way round this.

But in some cases we repeatedly call a function in large batches, and we use AggressiveInlining to not work. Even if the function is bulky, inlining will bring more benefits due to the number of calls. For example, when a program sends and receives a large number of data packets.
and AggressiveInlining brings more uncertainty.

**Comment by sgf** [comment]
hope that in the future there will be better similar ForceInline APIs.

**Comment by YairHalberstadt** [comment]
The JIT will almost always respect AggressiveInlining.

If it's not, it's probably because it can't. It could be because you throw an exception in the method, or some other reason.

If you have a reproducible sample of code which shows AggressiveInlining not working on CoreCLR, you could open an issue there asking why it's not being inlined.

As an aside, this entire issue belongs on the CoreCLR repository, not the csharplang repository, as it's a runtime issue.

**Comment by sgf** [comment]
> The JIT will almost always respect AggressiveInlining.
> 
> If it's not, it's probably because it can't. It could be because you throw an exception in the method, or some other reason.
> 
> If you have a reproducible sample of code which shows AggressiveInlining not working on CoreCLR, you could open an issue there asking why it's not being inlined.
> 
> As an aside, this entire issue belongs on the CoreCLR repository, not the csharplang repository, as it's a runtime issue.

thank you
