### ISSUE TITLE
[Proposal]: Tuple default values

### ISSUE THREAD

**Issue by ichensky** [dotnet/csharplang#2570]
Proposal add ability to add default values to tuples. 
For simplifying code like: 
```csharp
var arr = new List<(int val1, bool val2)>();
arr.Add((1, false));
arr.Add((2, false));
arr.Add((3, false));
arr.Add((4, true));
```
to this: 
```csharp
var arr = new List<(int val1, bool val2 = false)>();
arr.Add((1));
arr.Add((2));
arr.Add((3));
arr.Add((true));
```

Another ex.
```csharp
var arr = new List<(int val1, bool val2 = false, int val3 = 10, int val4 = 55)>();
arr.Add((1, val4: 100500));
```

**Comment by DavidArno** [comment]
```cs
var arr = new List<(int val1, bool val2)>();
(int, bool) Tuple(int val1, bool val2 = false) => (val1, val2);

arr.Add(Tuple(1));
arr.Add(Tuple(2));
arr.Add(Tuple(3));
arr.Add(Tuple(4, true));
```
and 
```cs
var arr = new List<(int val1, bool val2, int val3, int val4)>();
(int, bool, int, int) Tuple(int val1, bool val2 = false, int val3 = 10, int val4 = 55)
    => (val1, val2, val3, val4);

arr.Add(Tuple(1, val4: 100500));    
```
Adding this requested feature would require many, many hours of work by the language design team and by those responsible for documenting the language and those creating tooling around the language spec. It would mean us all having to learn new syntax rules. It basically would require lots of work … all to avoid writing a local function. Is that really worth it?

**Comment by ichensky** [comment]
This feature not looks like without which not possible to live, but now ValueTuple structs began used in code more often then ever. Just for improving C# non-priority task can be created for this feature.

**Comment by HaloFour** [comment]
While tuples do have a similar syntax to argument lists, they do not behave identically to argument lists.  They are purely positional in nature, meaning that you can't reorder the tuple elements by name like you can with parameter lists.  Because of this optional elements doesn't make much sense because that alters the arity of the tuple and the positions of the elements.  Skipping an element reorders the remainder of the tuple, and without the names overriding the remaining positions there's no way to specify those elements.
