### ISSUE TITLE
[Proposal] virtual classes

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2572]
Basically, allow to make a class `virtual` and all its members are implicitly virtual. You can use `sealed` if you want to prevent a child class to override certain member.

Why? Under some circustance, we have big classes with almost all their protected/public members being virtual. Making the class virtual would be easier and seal the few members we don't want to get overriden from a child.

**Comment by HaloFour** [comment]
You only have to write those members once, but you'll have to read them many times.  It's much clearer when you're reading that method to see that it's virtual without having to backpedal to the class definition to see if that method is virtual.

It also clashes with the convention of `static` where when applied to a class it doesn't actually affect the signatures of any of the members.

**Comment by DaZombieKiller** [comment]
I feel that a "keyword block" feature ala what D has would be more appropriate, although I believe such a feature has been discussed and denied before already.

```CSharp
class A
{
    virtual
    {
        public void MethodA() {}
        public void MethodB() {}
        // ...
    }
}
```

**Comment by svick** [comment]
@DaZombieKiller That would be https://github.com/dotnet/csharplang/issues/818 and https://github.com/dotnet/csharplang/issues/1021. It seems the community is against those, but they have not been officially rejected.

**Comment by JoergMittagLawo** [comment]
Whatever you decide, *please* do not call this feature "virtual classes". [The term *virtual class* already has a well-defined meaning in Object-Oriented Programming](http://caesarj.org/files/Caesar/02_p270-ernst.pdf). It would be confusing to users to have a feature that is named the same as an already existing well-known one.

(Case in point, I opened this issue because I thought it would be about adding virtual classes to C#, and I got excited because virtual classes are an awesomely powerful feature for achieving type-safe modularity and extensibility.)

**Comment by JoergWMittag** [comment]
Whatever you decide, *please* do not call this feature "virtual classes". [The term *virtual class* already has a well-defined meaning in Object-Oriented Programming](http://caesarj.org/files/Caesar/02_p270-ernst.pdf). It would be confusing to users to have a feature that is named the same as an already existing well-known one.

(Case in point, I opened this issue because I thought it would be about adding virtual classes to C#, and I got excited because virtual classes are an awesomely powerful feature for achieving type-safe modularity and extensibility.)
