### ISSUE TITLE
Proposal: possibility to opt-out of array covariance

### ISSUE THREAD

**Issue by xen2** [dotnet/csharplang#2578]
Array covariance allows cast of `TDerived[]` to type `TBase[]`:
```
string[] strings = new string[10]; 
object[] objects = strings;
```

Array covariance has many times been mentioned as a huge mistake (when C# didn't include generics and copied that feature from Java).

Unfortunately, it impacts performance of the whole runtime on most array setters: it has to check if type matches the array type at runtime, and throw a ArrayTypeMismatchException if type doesn't match (please correct me if I am wrong, maybe there is recent development to avoid the cost?).

Considering arrays is an primitive types used to construct many other types, this probably has a widespread impact on performance. Even though CPU are nowadays pretty good at doing branch prediction, it probably would be much better without array covariance (not only for performance impact of such check, but also the missed opportunity to inline code, more cache misses, code size, etc.).

Many program/library depends on this so this obviously can't be disabled for everyone right away.

As a result, I would like to introduce a proposal to phase out array covariance so that program not using that "feature" don't pay the cost:
1. Add a runtime mode where array covariance is not permitted. A cast from `T[]` to `U[]` would always fail in a `InvalidCastException`, whatever the types `T` and `U`.
2. Allow the user to control this runtime behavior. User can test if program works without this "feature" and opt-out of it. This could be configured with `.exe.config`, or some other mechanism.
3. Improve core libraries to avoid array covariance wherever possible.
I am not completely familiar how much some part of the .NET Standard libraries depends on this, but hopefully this is possible.
4. Generate better JIT code when array covariance is disabled: disable ArrayTypeMismatchException on array set, skip array covariance cast checks, etc.

**Comment by HaloFour** [comment]
This sounds like it belongs on [CoreCLR](https://github.com/dotnet/coreclr/)?  The language itself can't disable array variance.  I'd say that it's probably way too late to apply it at the runtime level either as you'd never know what assemblies would fail at runtime due to depending on array variance to work.

**Comment by CyrusNajmabadi** [comment]
This woudl definitely have problems.  There are case where variance is *highly* desirable and utilized quite well.  For example, `ImmutableArray` allows you to do the following as a 'free' operation:

```c#
// Using the roslyn API as an example:
ImmutableArray<INamedTypeSymbol> namedTypes = ...

// later
ImmutableArray<ISymbol> symbols = ImmutableArray<ISymbol>.CastUp(namedTypes);
```

This is 'free' in that both immutable arrays share teh same underlying array, and because ImmutableArray itself is a struct, so there is no additional allocation on top of things here.

There is also zero array variance cost here.  As everything is just 'reads' (outside of hte initial creation), there is no need to check anything.  So in cases (like Roslyn) that write rarely, but read *heavily* you'd now pay a heavy burden because you'd actually need to create an expensive copy to move around the type system.

**Comment by xen2** [comment]
@HaloFour Makes sense, I could move the issue to CoreCLR (runtime). It might also affect Roslyn (analysis, warnings).
@CyrusNajmabadi I was curious if it was still used today (I assumed it was somehow deprecated). It seems you found some way to take advantage of it, interesting.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I was curious if it was still used today (I assumed it was somehow deprecated). It seems you found some way to take advantage of it, interesting.

Yup yup.  I simply don't see how this would be a viable thing to do.  Especially in an immutable world, it's super useful to have variance here so you don't pay for unnecessary copies.

**Comment by vladd** [comment]
@CyrusNajmabadi

**Comment by xen2** [comment]
@CyrusNajmabadi Even in an immutable world, and assuming `IReadOnlyList<T>` interface indirection is too slow, it could still be handled with proper coordination of runtime+core libs:
Allow `T[]` to be cast to some other interface/type such as `IReadOnlyArray<T>` that only arrays could implement. Runtime can then treat this type specially because it knows the underlying type is an array, and optimize code. As a result, it wouldn't suffer the usual performance issue of interface.
That way, setter can only be used on the array type, and read-only covariance can still be used by casting to the interface.

It might be too late now, but ideally it would be great to introduce an alternative proper construct so that code can migrate and hopefully in a long time, we could start to disable old-style array covariance.

**Comment by HaloFour** [comment]
@vladd 

Reads would be free since they don't have to perform the type check.

@xen2 

It sounds like a lot of work for little real reward and there can never be the guarantee that all libraries will port over.  Projects that exploit the feature for their own benefit would have to be rewritten for little real gain.  That includes Roslyn.  Many of us would probably agree that array covariance is probably a misfeature, but it's been around for nearly 20 years (and quite a bit longer if you consider that it was "borrowed" from Java) and while it's a minor nuisance I don't think it poses enough of a performance or type safety problem to be worth such effort.

**Comment by xen2** [comment]
@HaloFour Thanks, Agree with you analysis. It's probably too late and not worth it anymore.

Also it could also be done purely on runtime-side as an "unsafe mode" if it proves to be a perf issue in gamedev, thanks to the fact a custom CoreCLR can be embedded in self-contained deployment.

Closing the issue.

**Comment by Frassle** [comment]
> ImmutableArray<ISymbol> symbols = ImmutableArray<ISymbol>.CastUp(namedTypes);

Wouldn't this also be solved by covariant classes/structs (https://github.com/dotnet/csharplang/issues/2498). Then ImmutableArray itself could be variant with no perf lost.
