### ISSUE TITLE
Proposal: null-conditional call

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/csharplang#261]
```CSharp
Func<int, string> myFunc = null;
if (myFunc?(10) == null)
{
    Console.WriteLine("Every body happy now");
}
```

**Comment by HaloFour** [comment]
```cs
Func<int, string> myFunc = null;
if (myFunc?.Invoke(10) == null)
{
    Console.WriteLine("Every body happy now");
}
```

**Comment by dmitriyse** [comment]
Probably I need some sleep. :)
This proposal gives too few benefits. But we can close it. But if it have low cost, then it can be part of https://github.com/dotnet/csharplang/issues/35 improvement.

**Comment by alrz** [comment]
@dmitriyse

 AFAIK This was considered in the design of C# 6.0 and discarded because of ambiguities with ternary.

**Comment by dmitriyse** [comment]
Then closing it.

**Comment by dmitriyse** [comment]
@alrz Please provide some case, where it gives ambiguity. If you remember.

**Comment by dmitriyse** [comment]
Probably it was declined due to cost/scheduling more than ambiguity?

**Comment by jnm2** [comment]
I remember the ambiguity too. Plus, writing out `.Invoke` makes the code easier to read imo.

**Comment by ufcpp** [comment]
@dmitriyse 
It was due to ambiguity between null-conditional call `f?(10)` and conditional operator `f ? (10) : 20`.

**Comment by dmitriyse** [comment]
Good example, thanks.

**Comment by Mardoxx** [comment]
@ufcpp what ambiguity? `f?(10)` has no colon after it.

I'm surprised nullable shorthand wasn't rejected under the same logic. `typeNamedT ?` has ambiguity over `objectNamedT ? (a) : b`

**Comment by CyrusNajmabadi** [comment]
The problem is that whne you see the ?( you don't have enough information to make the determination.  The part that follows the ?( may be arbitrarily complex.  This means you'd have to do an enormous complex scan (or an expensive speculative parse) to figure out what was going on.  For example, if you had:

f?(a, b).ToString()

What is?  Well, you still can't tell.  Maybe it's your new nullable-call, or maybe it's a ternary that has a tuple on the 'true' side.  

Given that you have full expression facilities available to you (i.e. 'a' and 'b' can be arbitrarily large), it's quite difficult to make a determination about what's going on.

Remember that resolving ambiguities doesn't mean just handling the simple case.  It means handling all the cases :)

**Comment by Mardoxx** [comment]
Brilliant, thank you! I knew I was missing something :)

**Comment by CyrusNajmabadi** [comment]
You're welcome :)
