### ISSUE TITLE
[Proposal] Cleaner syntax

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#2615]
Instead of:

```c#
class MyClass
{
    public int myInt = 5;
    public readonly myImmutableInt = 8;
    string myPrivateString = "hi";

    public MyClass()
    {
    }
}
```
```swift
class MyClass
{
    public var a: int = 5;
    public let b: int = 8;
    var c: string = "hi";

    public this()
    {
    }
}
```

Makes stuff more readable, less stuff to write, and better structure

**Comment by RUSshy** [comment]
Why downvotes ? every new and modern languages adopted this style, it makes language cleaner, and easier on eyes

**Comment by canton7** [comment]
Please don't introduce multiple ways of doing very fundamental things, for very small gains. There's a much higher cost in being able to write both `public` and `pub`, than saving 2 chars sometimes.

**Comment by RUSshy** [comment]
You are right, i edited my post

**Comment by canton7** [comment]
Likewise `Int` vs `int`: please don't add another way for no gain. Also, `var b: int` vs `int b`. C# chose the latter for better or for worse, and the least bad option is to stick with it l.

**Comment by RUSshy** [comment]
there is ``Int32`` in c# alternatively, but yeah i agree

**Comment by orthoxerox** [comment]
@RUSshy

> every new and modern languages adopted this style

Exactly, and every old language has kept its warts. If Microsoft ever decides to create a new mainstream language they will certainly come up with a clean modern syntax for it. But C# is almost 20 years old,  too many programs using the current syntax have been written already.

**Comment by RUSshy** [comment]
Both can be supported, in the end everything is translated to IL

**Comment by YairHalberstadt** [comment]
@RUSshy

Having 2 ways to do the same thing is generally a bad idea. Its confusing, and provides very little benefit so late in the languages lifetime.

**Comment by HaloFour** [comment]
There are dozens of languages that target the CLR, take your pick.  C# isn't going to introduce redundant syntax for common things without extraordinary evidence that it provides benefits to the users.  Most of what you've proposed here looks like just moving things around, such as putting the type at the end of the declaration.

**Comment by RUSshy** [comment]
It is to make stuff more concise, i'm pretty sure a little syntax cleaning/lifting would benefit C# for the long run

**Comment by CyrusNajmabadi** [comment]
> It is to make stuff more concise,

```
public int myInt = 5;
public var myInt: int = 5;
```

```c#
string myPrivateString = "hi";
var myPrivateString: string = "hi";
```

Your new syntax is more verbose than what C#'s has already.   I don't see how it makes anything more concise.

**Comment by CyrusNajmabadi** [comment]
> Why downvotes ?

Your proposal creates dialects for C#, something we are hugely against unless there is *massive* gain.  Currently, your proposal also makes things *more* verbose, which isn't something we really ever want to do.  If it made things concise it would have to do so in an *extremely* significant way.  i.e. how properties went from:

```c#
public int Foo
{   
  get
  {
    return bar + baz;
  }
}
```

Into:

```c#
public int Foo => bar + baz;
```

**Comment by RUSshy** [comment]
On the eyes, the flow is easier on the eyes

![image](https://user-images.githubusercontent.com/18348637/59970149-780c1400-955f-11e9-8318-22de581f60b5.png)

Since type is know can be reduced to:

```kotlin
class MyClass
{
    public myInt = 5;
    public myStr = "hi";
    public myLong = 5L;
    public myVec = new Vector2();

    var myPrivInt = 5;
    var myPrivStr = "hi";
    var myPrivLong = 5L;
    var myPrivVec = new Vector2();

    public this()
    {
    }
}
```

**Comment by HaloFour** [comment]
@RUSshy 

> On the eyes, the flow is easier to follow

That is purely opinion, and I disagree.  I don't find it easier to follow.  You've moved the indentation of one element to stagger another.  It's not less verbose, it's just different syntax for the sake of having different syntax.  If that's the syntax you want, find a language that offers it.  C# isn't going to.

> Since type is know can be reduced to:

The LDM has already made it clear that they are not interested in introducing such type inference into the language.  It is massively complicated to implement due to fact that C# allows for circular/forward references and very difficult to read.

**Comment by CyrusNajmabadi** [comment]
```c#
Since type is know can be reduced to:

class MyClass
{
    public myInt = 5;
    public myStr = "hi";
    public myLong = 5L;
    public myVec = new Vector2();

    var myPrivInt = 5;
    var myPrivStr = "hi";
    var myPrivLong = 5L;
    var myPrivVec = new Vector2();
```

Due to extreme implementation complexity, C# will not get type-inferred members.

**Comment by CyrusNajmabadi** [comment]
> On the eyes, the flow is easier to follow

This is your personal opinion.  Now that C# will have multiple ways of doing things, and there are billions of line written with the previous form, things will be harder to follow because people will need to be able to scan and grok both forms.

**Comment by Emzi0767** [comment]
> every new and modern languages adopted this style, it makes language cleaner, and easier on eyes

[Citation needed]

The "cleaner" part is subjective. I greatly prefer existing syntax, and adding another one would introduce a lot of problems on all levels. What about a codebase that would suddenly decide to mix both? Would that be cleaner, easier to follow, or understand?

**Comment by Korporal** [comment]
@RUSshy - In principle yes, the syntax could be improved but doing that well would create a brand new grammar that would be incompatible with existing C# code, it would not be backward compatible.

I agree that the grammar of C# could have been better but for reasons I can guess at basing it on C and C++ was done to ease takeup of the new language when it was introduced.

Whether it would have had success with a new grammar though we can't say, it may well have had the same success or less or even more, we do not know.

Putting the identifier before the type name in a declaration is a fine approach (and there are languages that do that) as are a host of other things (like making the relative position of optional keywords arbitrary or not having reserved words) but this simply cannot and will not get support.

I've criticized the C# grammar here before but I never suggested it be changed much because I know it will never be backward compatible.

All one could hope to do is invent a better solid grammar that represents a new language that can do everything that C# can do, that might be fun (and a lot of work) but I doubt anyone would really adopt it.

**Comment by mcosmin222** [comment]
This looks like a combination of VB and some frontend Web framework. Both of which scale very poorly with large code bases. More words doesn't mean better readability.

Most "modern" programming languages are failures imo. No need to barrow anything from them.

**Comment by gafter** [comment]
Can I change the title to `Proposal: Different Language`?

**Comment by Unknown6656** [comment]
There is a concise alternative: F#.

**Comment by CreatorVilius** [comment]
C# already has syntax as `Type name = expression`. There's no reason to add `var name: Type = expression`. C# is quite popular and changing whole syntax will make old projects uncompileable, since syntax errors. 
Alternatively, you can use this:
```cs
int        a = 1000;
string     b = "10";
bool       c = true;
SomeType   d = new SomeType();
```
This make cleaner syntax. Overriding new syntax, would divide .NET Core newer versions and .NET Core 3.0. I think something like that happened in Java 9. People use Java 8 for older java projects, but not Java 9 or newer.

**Comment by yaakov-h** [comment]
@CreatorVilius new syntax doesn’t usually require a new runtime.

**Comment by Korporal** [comment]
If I had time Id enjoy specifying a brand new grammar which can be translated to C# just for the intellectual stimulation. It would begin with some goals and would be something done purely for its own sake. Tha compiler could (I imagine) consume the source and leverage Roslyn directly to compile the converted text streams. Is that possible, is Roslyn an API that can be leveraged programatically in this way?

**Comment by CyrusNajmabadi** [comment]
>  is Roslyn an API that can be leveraged programatically in this way?

Yes.

**Comment by CreatorVilius** [comment]
> @CreatorVilius new syntax doesn’t usually require a new runtime.

But this proposal would make old code uncompileable. I think there's no reason to add such "TypeScript"y syntax C#. Instead, they/you can use F#, or even better, somehow get compiler which compiles TypeScript to .NET Assemblies and then use `var`, `let`, `const` with `: Type` static type.

There's just no reason to add it. I don't like it either. Besides, `var` is already used in C#, so it's quite stupid to use that syntax.

**Comment by RUSshy** [comment]
I see you are closed minded..

**Comment by CreatorVilius** [comment]
No. You are basically trying to add new variable declaration which is already in C#, but in different syntax.
Let's say I propose
```cs
^"a{b}c"
// same as
$"a{b}"
```
It looks cleaner, but there's just no reason to add it.

**Comment by RUSshy** [comment]
it makes sense to add it, that is how you make a language ready for another few decades of longevity, when old developers retire, new gen of devs will be there, how you attract them when other languages offer better ? today there is insane choice, people don't always voice their issues since they can change on the fly

**Comment by canton7** [comment]
You certainly don't attract them by making the language twice as big, by introducing 2 ways of writing everything!

**Comment by Korporal** [comment]
@RUSshy - There are a host of things I dislike about the choices made for the C# grammar, but now that it's well established there is a natural reluctance to adjust it without a lot of justification. The team do and will push back a lot even for things that are relatively minor, so a new way to write constructors is just a non-starter. Many here have suggested things far less fundamental than this and found very limited if any support.

The entire world of languages is infected by the original feeble C grammar, even Rust a new language unhesitatingly followed this habit.

Until Microsoft decide to innovate more here we're stuck with what we have.

**Comment by cryolithic** [comment]
Perhaps I've graduated to greybeard, but I can't see how this would gain much, vs confuse and add an odd syntax.

I fail to see how 
`public var a: int = 5;`
is clearer or cleaner in any way than
`public int myInt = 5;`

**Comment by RUSshy** [comment]
it then becomes consistent with the way you can use var for local variable, there is also the let instead of readonly, and readability, look at the screenshot above

i think .net and c# need a huge cleanup, both language and project/build system, remove XML use C# directly instead like the Swift Package Manager or even Nim

but maybe it just needs a new language, https://github.com/stark-lang from xoofx looks nice, but sadly looks already abandoned

**Comment by YairHalberstadt** [comment]
> i think .net and c# need a huge cleanup

Any cleanup which involves such huge changes to the syntax merits a new language. A new language gets to choose such things in a vacuum.

> but maybe it just needs a new language

There's thousands of new languages being created each year. Many of them are very interesting. We're developers. We love to throw everything out and start from scratch. I'm sure most members of the LDM would be delighted if Microsoft gave them a clean sheet and said they would be given whatever resources they wanted to create a new language from scratch.

However the value of the ecosystem that C# has built up is in 99% of cases worth the warts that have built up with time. That's why people use C#, and why it will continue to be developed for the foreseeable future.

The feature requests that are most useful are ones that respect this, and guide C# gently in a direction which will help solve problems developers are experiencing today, rather than trying to force it into becoming the language they wish it was.

**Comment by HaloFour** [comment]
At the end of the day the syntax is probably the least important concern compared to how well the language accomplishes the job.  Style and preference is driven by fickle and constantly changing opinion.  The are dozens of languages that target .NET with a wide variety of syntaxes.  The C# team isn't remotely concerned with trying to win any popularity contests.

Brian Goetz once described the prospect of removing semicolons as a negative productivity language change because it leads an entire community of developers to feel the need to modify entire existing and working codebases just to meet the style du jour.  The changes proposed here fall squarely into that same category.

**Comment by Korporal** [comment]
If syntax was relatively unimportant then I wonder why the .Net team made the effort to stick with a grammar based on Java/C++/C...

**Comment by CyrusNajmabadi** [comment]
It's a familiar, time-tested basis to start a language off of.  But the decisions have been made.  Relitigating now will go nowhere.

**Comment by gafter** [comment]
> I wonder why the .Net team made the effort to stick with a grammar based on Java/C++/C rather than cleaning the whiteboard and considering it afresh

The premise of this question is that considering it afresh is less effort.  I cannot imagine your basis for that assumption.

**Comment by Korporal** [comment]
So I think you've answered the question - the team made the choice they did because basing the C# grammar on those predecessors was _less effort_ than designing a new grammar from scratch.

**Comment by canton7** [comment]
Don't forget the effort it takes developers to learn a completely new syntax, too.

**Comment by Korporal** [comment]
Well at some point we must _innovate_, that's my point here, at what point do we innovate with an OO language (whatever that may mean) to such an extent that we are willing to abandon the tired old C/C++/Java grammar.

**Comment by canton7** [comment]
F#?

**Comment by gafter** [comment]
> Well at some point we must _innovate_

No, there is no imperative to innovate in the syntax.  Hey, maybe we should make `+` higher precedence than `*`, that sure would be innovative, huh?  There is value in using familiar syntax.  Syntax was not intended to be C#'s value proposition.

> the team made the choice they did because basing the C# grammar on those predecessors was _less effort_ than designing a new grammar from scratch

For the designers and users, yes.  And also because it reduced the number of errors that might have been introduced during the effort of designing a new syntax from scratch.  C# may have been innovative, but there was no intent to be innovative in such core syntactic sensibilities.

**Comment by RUSshy** [comment]
There is an imperative to improve syntax, add new construct in order to match the expectations of todays people

- cleaner and refreshing syntax, helps write less and still stays readable

```c#
foreach (ref readonly var item : items)
{
}
```

could be simplified to this if ``let`` was allowed instead of the super long ``readonly var``

```c#
foreach (ref let item : items)
{
}
```

- Ability to write DSLs, good for UIs, no need separate/external xaml file

- AOT compilation, helps with distribution, serverless, mobile apps, IoT


If you stick to your foot, you end up like Java, 20 years to react (Valhalla for example) and dead at the arrival

**Comment by HaloFour** [comment]
> If you stick to your foot, you end up like Java

One of the most widely used languages in the world?

Changing syntax for the sake of changing syntax or chasing temporary style preferences will never happen.  Adding two ways to do the same thing in the language that offers zero benefits other than that you think it looks nicer today is not on the table.  If you have very specific language proposals which add actual value to the C# and improve the workflow of developers, feel free to open new proposals.  But suggesting that C# flip variable declaration around just because you prefer Swift or Rust or Kotlin or TypeSwift syntax, that is most certainly dead on arrival

**Comment by RUSshy** [comment]
>  sake of changing syntax

you refuse to listen, i don't want change for sack of change, i want change to help write less and become more readable

**Comment by CyrusNajmabadi** [comment]
> you refuse to listen, i don't want change for sack of change, i want change to help write less

As i pointed out here: https://github.com/dotnet/csharplang/issues/2615#issuecomment-504708173

"Your new syntax is more verbose than what C#'s has already. I don't see how it makes anything more concise."

> and become more readable

"More readable" is subjective.  Perhaps things are "more readable" when they're consistent with some of the most widely used languages in the world...

**Comment by CyrusNajmabadi** [comment]
> There is an imperative to improve syntax

No there is not.  If you want that imperative, you're using the wrong language.  The LDM gets to decide what it thinks what is of vital importance.  And only they have the authority to command things like improved syntax.  

At times it does happen.  Usually when there is an extremely good justification given, and hte pros outweigh the numerous cons brought up.  That is lacking here.

**Comment by CyrusNajmabadi** [comment]
>  to such an extent that we are willing to abandon the tired old C/C++/Java grammar.

Your subjective opinion there has just as much merit as someone saying "why would we abandon the well known, and viable syntax that have been used effectively across many languages for decades.  "old" is not a reason that something is bad, and "new" does not make something good.  My absolutely favorite languages are literally 50+ years old, with syntax that works exceptionally well.
