### ISSUE TITLE
Non-null test operator ?

### ISSUE THREAD

**Issue by babaloomer** [dotnet/csharplang#2634]
I think that a non-null test operator (?) should be introduced. This would simply be a test for a non-null value of a class type. It would basically check the reference and convert it into a boolean 'true' if non-null.

`bool nonNull = myNullableObj?;`

So instead of doing this to test for non-null:
`if ( myNullableObj != null ) { ... }`

You could simply do this:
`if ( myNullableObj? ) { ... }`

Simple, elegant and it fits naturally in the spirit of the the null conditional (?.) and null coalescing ()?? operators.

Also, instead of testing for null like this:
`if ( myNullableObj == null ) { ... }`

You should be able to do this:
`if ( !myNullableObj? ) { ... }`

I think that it's probably simple enough to implement in the language since the ?. operator already does something similar internally anyway.

Of course, there could be a little challenge to properly distinguish it from the ( ? : ) statement. But I think the solution for this is simple: if the left-operand is a nullable type, then the middle and right operands along with the ':' must not be present.

**Comment by Tom01098** [comment]
```C#
if (myNullableObj is null) 
{ 
    // Null here. 
}

if (myNullableObj is object)
{
    // Not null here.
}
```

I think how you propose to check for null is confusing because the important parts of the syntax are at both ends of the variable.

**Comment by babaloomer** [comment]
If it's confusing at the end of the variable, I'm all for putting it at the beginning of the variable instead:
`if ( ?myNullableObj ) { /* not null here */ }`
`if ( !?myNullableObj ) { /* null here */ }`

**Comment by canton7** [comment]
If I saw that syntax in someone else's code, I would have no idea what it meant. Add to that the fact that you're only saving a few characters...

**Comment by babaloomer** [comment]
> If I saw that syntax in someone else's code, I would have no idea what it meant. Add to that the fact that you're only saving a few characters...

@canton7
I don't think that it's any more confusing than the (?.) operator.

In my view, it feels like asking a question in a 'if' statement. It somewhat reads as follow:
'if my object not-null then' or 'if not null my object then' (depending on where we decide to put the operator ;)

**Comment by MillKaDe** [comment]
A non-null check operator has already been suggested and discussed.
See these threads:

- [#196: Discussion: `null` evaluation operator to boolean](https://github.com/dotnet/csharplang/issues/196)
- [#545: Proposal: `?obj` operator for real '!null' check on all nullable types](https://github.com/dotnet/csharplang/issues/545)
- [#833: Null check syntactic sugar; Make `foo?` equivalent to `foo != null` ](https://github.com/dotnet/csharplang/issues/833)

I still think it would be nice to have such a non-null check operator in C#, because it allows shorter checks (like in C and C++), but without the problems of auto-conversion to bool.

**Comment by babaloomer** [comment]
@MillKaDe Exactly! It's a shame that all the threads you linked are closed issues... :(
