### ISSUE TITLE
Deconstructing inside local variables with var

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/csharplang#2637]
I recently discovered how to deconstruct a record as local variables.

Current:
```csharp
(string a, string b) Method() => ("hello", "world");
void Main(string[] args)
{
    (string a, string b) = Method();
    Console.Write($"{a} {b}");
}
```

Why not pushing it a bit farther?

Expected:
```csharp
(string a, string b) Method() => ("hello", "world");
void Main(string[] args)
{
    var = Method();
    Console.Write($"{a} {b}");
}
```

**Comment by YairHalberstadt** [comment]
Remember, `Method` might not even exist in the same project as you are using it, never mind the same file. How on earth is anyone looking at that code meant to know where a and b come from? Especially if multiple such deconstructions are in the same method.

Naming variables is important. Plenty of languages do very extreme type inference, but I don't know of a single language that tries to do variable name inference. The aim of language syntax design is not brevity but clarity, which brevity can sometimes help. Over here the only advantage I can see is that you've saved a few characters, at the cost of making the code impossible to follow without outside information. Why do you think this is a suitable trade off?

**Comment by YairHalberstadt** [comment]
Note that the following is legal:

```csharp
(string a, string b) Method() => ("hello", "world");
void Main(string[] args)
{
    var (a, b) = Method();
    Console.Write($"{a} {b}");
}

```

**Comment by ufcpp** [comment]
The following is also legal:

```cs
(string a, string b) Method() => ("hello", "world");
(string, string) var;
void Main(string[] args)
{
    var = Method();
    Console.Write($"{a} {b}");
}
```

**Comment by YairHalberstadt** [comment]
I think the point @ufcpp is making is that Roslyn currently has to parse `var` as an identifier, not a type, as the parser is not context sensitive, and his code is legal.

The only way the compiler can tell that var isn't an identifier is by checking semantically whether var is a valid identifier at that point. That check occurs in the semantic stage of compiling. By the time that occurs it would be extremely complex to reinterpret this as a type identifier. There is currently no precedence in C# for such a syntactical construct, and the C# team specially used the `async` keyword, and `yield return` instead of `yield`, in order to avoid this complexity with iterators and async-await respectively.

**Comment by NicolasDorier** [comment]
I get it, I am spoiled C# kid, no variable name inference. :(

**Comment by KalleOlaviNiemitalo** [comment]
> Plenty of languages do very extreme type inference, but I don't know of a single language that tries to do variable name inference.

A related comp.lang.lisp thread from 2004: [Macroexpansion, bindings and information flow (Iterate package)](https://groups.google.com/d/topic/comp.lang.lisp/6ch3EYk3OTw/discussion).
