### ISSUE TITLE
Drop unsafe for higher safety to end user

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/csharplang#2650]
`unsafe` should be dropped, so that end users can have higher safety when they use C#.

**Comment by scalablecory** [comment]
Ultimately we'll need to get rid of `dotnet run` to ensure no malicious code can execute.

**Comment by CyrusNajmabadi** [comment]
Note: removing unsafe from c# won't actually make anything safer.  You can still trivially call or execute unsafe code.

My recommendation is that you write an analyzer for your own code to prevent your usage of unsafe if you don't want to use it.

**Comment by HaloFour** [comment]
Removing `unsafe` from the C# language would mean that the .NET runtime and framework itself could no longer be compiled.  It also doesn't remove the vector of calling other "unsafe" or even native code embedded in referenced assemblies.  Nor does it remove the vector of using reflection to emit arbitrarily unsafe IL that can be executed.

Removing any feature from the language is basically a non-starter due to the fact that it would break existing programs.  Removing a feature that is widely used and required in order to make .NET work at all would certainly never be considered.  It's not a goal of C# to be perfectly safe or to prevent developers from explicitly opting-in to doing potentially unsafe things.

If you don't want to use `unsafe` then don't enable it in your projects.  It's not enabled by default.  You don't even need an analyzer to enforce this.

**Comment by vladd** [comment]
I assume the TS wants to [be able to] prohibit `unsafe` and probably things like `Marshal.Copy` in the 3rd-party code (e. g. plugins).

**Comment by TheUnlocked** [comment]
The .NET Framework already has a way to limit the permissions of untrusted assemblies. This is admittedly trickier with .NET Core, though not impossible.

**Comment by vladd** [comment]
@TheUnlocked Is it indeed possible with .NET Core? Would you please share a document link? [Sorry for offtopic.]

**Comment by TheUnlocked** [comment]
@vladd [Sharplab](https://sharplab.io) uses a fancy library called [Unbreakable](https://github.com/ashmind/Unbreakable) that they made to safely run .NET Core code, though I have no idea how it works and it seems pretty involved. You can also call other non-Core code for the particular OS (e.g. with P/Invoke) to sandbox a process. It's certainly not pretty, and a non-horrible solution would be nice, but like I said, it's not _impossible_. Dropping `unsafe` is certainly not the solution.

**Comment by 0xF6** [comment]
@vladd 
>I assume the TS wants to [be able to] prohibit unsafe and probably things like Marshal.Copy in the 3rd-party code (e. g. plugins).

Why not use SecurityTransparent for configure access-level for 3rd-party code?

**Comment by YairHalberstadt** [comment]
Closing as removing a widely used language feature is not something C# can do
