### ISSUE TITLE
String IgnoreCase extension method

### ISSUE THREAD

**Issue by BluePositive** [dotnet/csharplang#2677]
How about to add a String extension method  EqualsIgnoreCase like in  [Java](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/String.html#equalsIgnoreCase(java.lang.String)l) .
I asked on [Stackoverflow](https://stackoverflow.com/questions/57101169/is-there-any-method-in-c-sharp-like-equalsignorecase-from-java) for reference and I was surprised that such an extension method does not exist.

**Comment by YairHalberstadt** [comment]
Requests to change the standard library belong in https://github.com/dotnet/coreFX

Why do you think writing your own extension method is insufficient, and this method has to be part of the standard library?

**Comment by BluePositive** [comment]
I think it's is a common use case (at least  Java thinks so ), and I don't know if writing my own extension method for such a class like the string class is a good practice.

**Comment by HaloFour** [comment]
I'd argue that the .NET approach via `StringComparison` or `StringComparer` is more appropriate as if gives you more control over how locale affects the comparison.  Java's method just brute forces by seeing if the zip of the character sequences happen to match if they match either lower or upper case, which doesn't work well with all locales (looking at you, Turkish).

Given that, if you wanted such an extension method it's probably better to exist in your project because the BCL team are going to have to consider locale issues which may dissuade them from considering such an addition.

**Comment by BluePositive** [comment]
@HaloFour I still think it will make it easier to use (and more likely to be noticed with a IDE )  if it would be a default EqualsIgnoreCase extension method and if you want to alter the default behavior you pass in a parameter to change it like now the default Equals method

**Comment by CyrusNajmabadi** [comment]
as @YairHalberstadt said, this request does not belong here.  Please move it to corefx.

**Comment by BluePositive** [comment]
I moved it to [coreFX](https://github.com/dotnet/corefx/issues/40421)

**Comment by CyrusNajmabadi** [comment]
Thanks very much @BluePositive !
