### ISSUE TITLE
Support NotNullIfNotNull on Task<T?> return type

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/csharplang#2793]
**Version Used**: .NET Core 3.0 preview 8

**Steps to Reproduce**:

```csharp
[return: NotNullIfNotNull("value")]
static Task<string?> PassThroughAsync(string? value) {
	return Task.FromResult(value);
}

static void Main(string[] args) {
	string s = PassThroughAsync("Hello World!").Result; // Warning CS8600  Converting null literal or possible null value to non - nullable type.
	Console.WriteLine(s);
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Warning CS8600  Converting null literal or possible null value to non - nullable type.

**Comment by jnm2** [comment]
Also, Dapper has `Task<T> QuerySingleOrDefaultAsync<T>(...)`. Should there be a way to apply `[MaybeNull]` to the usage of `T` in the return type?

Otherwise, you get no warnings if you forget to check a reference type for null:

```cs
var maybeNull = await QuerySingleOrDefaultAsync<string>(...);
maybeNull.IndexOf("foo");
```

In this particular instance, it would be nice if there was a way for `QuerySingleOrDefaultAsync` to constrain `T` to allow value types, nullable value types, and nullable reference types, but not non-nullable reference types.

**Comment by dotMorten** [comment]
I just hit this case too. I'll never return a null Task<T>, but the T will be null if the parameter is null.

This annotation says I won't return a task that's null, but I'm much more interested in saying that T won't be null.
```cs
        [return:System.Diagnostics.CodeAnalysis.NotNullIfNotNull("instance")]
        public static Task<MyType2?> ConvertObject(this MyType? instance)
        {
            if (instance == null)
                return Task.FromResult<MyType2?>(null);
            return Task.Result(ConvertObjectHelper(instance)); //Won't return null MyType2
        }
```
