### ISSUE TITLE
Discussion: namespace from directory structure

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#2908]
Keeping namespaces in sync with directory structure is usually a convention most of codebases follow. I think such feature would make that easier especially when public API contract is not an issue.

A simple syntax such as `namespace;` is needed to hint the compiler to choose a namespace based on directory structure.

Note: https://github.com/dotnet/csharplang/issues/2546 would only decrease nesting, but directory namespaces would make it entirely implicit.

**Comment by MgSam** [comment]
I'm not a fan of having code files have to be aware of the file system. It means moving a file around now becomes a breaking change. I write a lot of TypeScript as well as C#, and the fact that imports in TS/JS rely on file paths for correctness is one of the most painful and poorly designed things about the language, IMO.

**Comment by HaloFour** [comment]
I'm kind of with @MgSam on this one.  Aside from `CallerFilePathAttribute` I don't think that the location of the source impacts compilation at all.

A feature like this would require a companion feature to establish the root path of the project, as not everyone would want the namespaces hanging off of the root project directory.

**Comment by DanFTRX** [comment]
That being said this could easily be a plugin/setting on an IDE rather than a language feature

**Comment by DavidArno** [comment]
I'm torn on this one. 

I like the fact that R# warns/errors if the namespace doesn't match the file path (VS may do this natively now days; I've not checked). So I like the idea of not even having to specify the namespace, but to have it inferred by the file's location.

But I think @MgSam also raises some valid points against the idea.

So I've upvoted both the proposal and his counter argument. 😄

**Comment by MV10** [comment]
@HaloFour what, you don't look forward to using libraries like this? 🤣 

```
namespace Users.JohnDoe.Source.Repos.Foo.Bar
```

**Comment by ronnygunawan** [comment]
Creating a new .cs file already generates namespace based on directory structure. What you need is an analyzer with code fix to apply `Refactor namespace to match directory structure` fix to all files.

**Comment by MV10** [comment]
@ronnygunawan 
> Creating a new .cs file already generates namespace based on directory structure.

The request is to do this without explicitly specifying the namespace in the code file _at all_. The namespace would be _derived_ from the file location only at compile time.

Bugs galore...

**Comment by HaloFour** [comment]
@ronnygunawan 

> Creating a new .cs file already generates namespace based on directory structure. What you need is an analyzer with code fix to apply `Refactor namespace to match directory structure` fix to all files.

I like this idea.  An analyzer can warn that the namespace doesn't match the directory structure given a configured source root, and can offer a fix to update the namespace to match the location of the file.  This would work similarly to how many IDEs deal with the package names of Java files.

**Comment by jagalves** [comment]
Some comments are really going overboard with the source root configuration. There's already a \<RootNameSpace\> configuration in the .csproj and the root can be the project file itself. No need to overcomplicate things. I mean, the new project type already automatically picks up .cs files under its path, why not automatically assign namespaces as well?

In my opinion this is how it should be:

* namespace declaration (and scope) not set: use the project's default + relative path to .csproj as namespace
* namespace declaration present: as it is today, don't break existing code and allow customization

Example:
* Project: c:\\users\\jagalves\\projects\\Stuff\\MyProject.csproj (RootNamespace "MyProject")
* File: c:\\users\\jagalves\\projects\\Stuff\\Utils\\DateUtils.cs

If the file DateUtils.cs doesn't have a namespace{ } declaration, its namespace shall be "MyProject.Utils".

Today most people just do this but keep the redundant namespace declaration in every file.

**Comment by miloush** [comment]
> If the file DateUtils.cs doesn't have a namespace{ } declaration, its namespace shall be "MyProject.Utils".

You do not have to specify namespace currently, and this change would break such existing code.

**Comment by jagalves** [comment]
Hmm, it's global. I can see now why the OP suggested "namespace;" to trigger the feature.

Still think my suggestion should be considered for the next time .csproj gets breaking changes. Whenever it may be. ;)

**Comment by jingle1000** [comment]
I would love to see this. I'm not sure if it is possible but it would be nice if the namespace could be an **optional** statement. If no namespace is provided, the compiler will determine the namespace based on directory structure. This would (hopefully) solve the issue of backwards compatibility.

**Comment by miloush** [comment]
@jingle1000 as just noted namespace is already an optional statement

**Comment by ssg** [comment]
This sounds practical at first but I find it more problematic than [file-scoped directives](https://medium.com/@ssg/a-pledge-for-namespace-directives-in-c-15a322504a15?), because:

- Directories are both used for semantic (aka public facing) grouping and logical (aka internal) grouping. For example: Controllers/Models/Views structure in an ASP.NET Core project which share the same namespace. If we separate them, that means we have to litter the source code with multiple using statements for even small, logical groups like these rather than a single line of namespace directive per file. It would become annoyingly verbose and people would be discouraged to layout the source directory to their liking. This is my greatest issue with this proposal that it lumps semantic and logical grouping into a single scheme.

- There are many hardcoded directories in .NET projects which don't imply a namespace like App_Code, App_Data, App_Resources etc. This would cause confusion, problems.

- It's impossible to deduce if a project uses namespaces or the global namespace by viewing the source code. You have to browse through csproj file, evaluate if macros if needed, just to assess this. It's unnecessarily vague. 

Even Java, which assumed a file corresponded to one class, never assumed that a namespace would correspond to a directory.

**Comment by michalczerwinski** [comment]
As an author of the duplicated item I would like to fill in some things:
* it's nice to be able to opt in within specific file
* it would be nice to be able to override namespace for folder in VS (F4 for folder, then property Custom Namespace, similar to existing "Custom Tool Namespace" for items)
* I think this might be a better syntax (but might be a matter of taste)
```csharp
namespace default;
```  
And please mind that this feature is available currently for razor files and it's really convenient!

**Comment by ssg** [comment]
I thought I mentioned that before but couldn't find it. There is also the issue of FS/language discrepancy: Namespaces are case-sensitive in C#, while the filesystems of MacOS and Windows are not. They are case-preserving only. So you can have two namespaces in C# called "A" and "a" but you can't have two separate folders like that.

It might also cause other issues, like not being able to correct the casing in a namespace because source control doesn't care about renames that changes only letter casing. Case in point: https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git 

I also find migration path difficult as opposed to file-level namespace directives, which can be a simple refactor option in StyleCop.

**Comment by hez2010** [comment]
C# code can be compiled without file using Roslyn API. What if there's no actual .cs file but only C# code text?

**Comment by Trayani** [comment]
I'd have an option to declare containing namespace without braces and indentation.

**Comment by Joe4evr** [comment]
@Trayani #137
