### ISSUE TITLE
Compile Time Reflection

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#2939]
Sometimes reflection is really nice

But unfortunatly with C# it comes with a HUGE HUGE cost since it is done at runtime, is really slow, and it prevents sane use of AOT compilers..

Would be nice if reflection could be done at compile time

**Comment by HaloFour** [comment]
Could you expand on that?  What would it look like?  Are there syntax changes?  What IL would be emitted?

**Comment by RUSshy** [comment]
I lack technical knowledge to answer these questions sorry, i wanted initiate debate on the concept itself 

I'm using D, and they use ``__traits`` in order to access several stuff  https://dlang.org/spec/traits.html at compile time, and i love it

for ex:

```d
import std.stdio;
import std.conv;

enum Color
{
    black,
    blue,
    red
}

struct Colored
{
    Color color;
}

struct Person
{
    @Colored(Color.blue) string name;
    @Colored(Color.blue) string lastName;
    @Colored(Color.red) string address;
}

void main()
{

    // attributes
    writeln("# Print Attributes");
    foreach (attr; __traits(getAttributes, Person.name))
    {
        writeln("\t", attr);
    }

    // members
    writeln("# Print Members");
    foreach (memberName; __traits(allMembers, Person))
    {
        writef("\tThe attributes of %-8s:", memberName);

        foreach (attr; __traits(getAttributes, __traits(getMember, Person, memberName)))
        {
            writef(" %s", attr);
        }

        writeln();
    }

    // serialize    
    writeln("# Serialize");
    auto person = Person();
    person.name = "This";
    person.lastName = "Someone";
    person.address = "Somewhere";
    serialize(person);
}

void serialize(Person object)
{
    {
        string value = object.name.to!string;
        writefln(`	<%1$s color="%2$s">%3$s</%1$s>`, "name", Color.blue, value);
    }
    {
        string value = object.lastName.to!string;
        writefln(`	<%1$s color="%2$s">%3$s</%1$s>`, "lastName", Color.black, value);
    }
    {
        string value = object.address.to!string;
        writefln(`	<%1$s color="%2$s">%3$s</%1$s>`, "address", Color.red, value);
    }
}
```

will print:

```
# Print Attributes
	Colored(blue)
# Print Members
	The attributes of name    : Colored(blue)
	The attributes of lastName: Colored(blue)
	The attributes of address : Colored(red)
# Serialize
	<name color="blue">This</name>
	<lastName color="black">Someone</lastName>
	<address color="red">Somewhere</address>
```

Without runtime reflection, all at compile time, easy to use, no garbage, 0 cost, fast

**Comment by RUSshy** [comment]
To set value of a member:

```d
import std.stdio;

struct S
{
    int x;
    int y;
}

auto setValue(ref S s, string field, int value)
{
    foreach (fieldName; __traits(allMembers, S))
    {
        if (fieldName == field)
        {
            __traits(getMember, s, fieldName) = value;
            break;
        }
    }
}

void main()
{
    S s;
    s.setValue("x", 5);
    s.setValue("y", 25);
    writeln(s);
}
```

will print:

```
S(5, 25)
```

**Comment by HaloFour** [comment]
Sounds like some kind of macro-like metaprogramming where the compiler executes code which generates code compiled by the compiler.  How does this work when the compiler doesn't know the type of `S` or where the members are discovered at compile time?  How does the compiler prevent this from being abused to lock the compilation process or to execute arbitrary/malicious code?

**Comment by RUSshy** [comment]
> How does this work when the compiler doesn't know the type of S or where the members are discovered at compile time?

Well, if they managed to do it for D, i assume C# compiler could do the same

> How does the compiler prevent this from being abused to lock the compilation process or to execute arbitrary/malicious code?

That's not an issue in C++/D why should it be an issue with C#?

**Comment by HaloFour** [comment]
@RUSshy 

I can't speak to D but abusing compiler evaluation is a thing in C++.  You can cause exceptionally long compile times or break the compiler.  C++ has a lot of limitations around `constexpr` to try to reign that in by forcing you to use recursion which at least can be limited to a maximum depth.

`__traits` exists in D because reflection doesn't, so you need some mechanism to access the compiler internal state.  That problem doesn't exist in C#.

**Comment by jmarolf** [comment]
This sounds like similar to `constexpr` for C++.  Essentially a mini-language that is evaluated at compile-time and baked into the assembly as constants. We could do this. I think @agocke has thought about it. We would need to specify the exact set of expressions that would be in the `constexpr`.  

As this proposal stands I don't understand the use case for this feature. What is the situation where I want to annotate types with constant meta-data? @RUSshy is there some docs on d-lang about what this feature is mostly used for?

**Comment by DaZombieKiller** [comment]
Would this be solved by source generators?

**Comment by agocke** [comment]
`constexpr` is possible but a ton of work. Someone with a deep knowledge of the spec would need to write out exactly what each operation does, and I think a lot of the results would be non-obvious.

Some of what's mentioned here might be possible with source generators e.g., have a generator look over the code, generate a method that does what you want, then you call that method in your own code. The only thing that wouldn't be possible would be the generator modifying your own code.

**Comment by RUSshy** [comment]
I should have used better examples, but my personal use-case is being able to use some sort of basic reflection (Inspect game entity properties name / value and some other stuff) in reflection-free mode of CoreRT, this mode reduce the size of the executable by A LOT by completely removing run-time reflection features

But it can be useful for many other stuff, cli tools for command line processing, no need overhead of doing the reflection stuff for attributes etc, same for serialization, and can be used in cases where speed/size is needed (wasm) etc

> __traits exists in D because reflection doesn't, so you need some mechanism to access the compiler internal state. That problem doesn't exist in C#.

Sure C# has run-time reflection but at a big and non negligible cost

> Would this be solved by source generators?

I doubt it can be as simpler as using ``_traits`` without bloating the project

**Comment by HaloFour** [comment]
@agocke 

> Some of what's mentioned here might be possible with source generators e.g., have a generator look over the code, generate a method that does what you want, then you call that method in your own code. The only thing that wouldn't be possible would be the generator modifying your own code.

If `original`/`replace` are also added to the language could a generator theoretically interpret the syntax tree of a C# DSL within a method and emit a replaced version of the method with the compile-time evaluated source?

@RUSshy 

> I doubt it can be as simpler as using `__traits` without bloating the project

You need a _lot_ more than just `__traits`, you need all of the metaprogramming that ends up translating all of that source at compile-time.  The compiler would need to interpret the loop over the names and the conditionals within that loop and the access of the member all at compile time.  If you're talking about expanding this to helper "functions" that can accept an arbitrary game entity and inspect its properties you need an entirely new flavor of generics as well for passing these variables of compile-time reflection data.  You end up with a language within a language.

**Comment by agocke** [comment]
> If original/replace are also added to the language could a generator theoretically interpret the syntax tree of a C# DSL within a method and emit a replaced version of the method with the compile-time evaluated source?

Probably. In this case it seems hard to justify that since it looks like what this code does is basically just generate an enumerator for enums.

**Comment by RUSshy** [comment]
@HaloFour 

Implementation detail is another story
Feature wise, the benefits are not negligible, and it would make reflection much better than what it is today
I'd love if it was a thing, even if it was limited to basic stuff (attributes, get/set members)

**Comment by HaloFour** [comment]
@RUSshy 

Those two use cases would seemingly eliminate much of the metaprogramming concerns I would have.  But I also question how useful they would be.  For example, the ability to get and set members would require knowing the concrete type as well as a constant of the member name in question, perhaps something like this:

```cs
Point pt = new Point(2, 2);
int x = __traits(getMember, pt, "X");

// compiler translates into
int x = pt.X;
```

Which to me does not seem to be an improvement.

Attributes could be a little bit more interesting in that the compiler could resolve the custom attribute at compile time and embed a cached version:

```cs
Point pt = new Point(2, 2);
var converter = __traits(getAttribute, pt, "TypeConverter");

// compiler translates into
if (this._cachedTypeConverter == null) {
    this._cachedTypeConverter = new TypeConverter(typeof(System.Drawing.PointConverter));
}
var converter = this._cachedTypeConverter;
```

Neither case seems that particularly compelling to me.  I think that without the metaprogramming aspect that you'd be more or less limited to what you can already express much more concisely with regular code, or through manually embedding those values in your source.

**Comment by RUSshy** [comment]
Of course i'd prefer to have the whole package, that would make my life much easier

I don't know the details on how it works in the compiler, but yeah i'm using some of it in D and i'm happy with the result and performance compared to the run-time reflection of stuff like C#/Java

**Comment by benaadams** [comment]
Related to fast reflection for field access https://github.com/dotnet/coreclr/pull/23783

**Comment by RUSshy** [comment]
i'm not sure that is related, what i propose is everything at compile time, nothing to do at run-time, i don't having to deal with creating these "expensive?" stuff, or maybe i don't understand

**Comment by jmarolf** [comment]
@RUSshy is your scenario some kind of dependency injection? A compile time reflection api and/or an effort to reduce how expensive metadata is in .NET may be worth doing. However, I wonder if there is a specific use case that you have that would be easier to address.

**Comment by RUSshy** [comment]
Context:

game engine + game, AOT compiled using CoreRT in reflection-free mode to get the smallest possible executable

Use Cases:

- Organization of packets for networking using attributes
- Inspection of entities and their property name / name
- Serialization of packets, entities, game data, config files
- Scripting Language binding

That's the feature i would like to have to make my life easier, run-time reflection is a no go because i'd loose the benefits i currently have with CoreRT reflection free mode, and i don't want to have to pay for the cost of the run-time reflection 

Cecil and generating other stuff from other projects is a no go because it adds to much complexity

Again i don't know the details under the hood of how that works in the compiler, but the ``__traits`` stuff from D is what i would like to be able to do with C#, suits my use cases well

**Comment by gleblebedev** [comment]
@RUSshy 

> __traits(getAttribute, pt, "TypeConverter")

This won't work in compile type as the assembly where type is defined can be replaced with a new one. The only place where this optimization could happen is JIT compilation.

**Comment by jmarolf** [comment]
talked with @terrajobst about this. It would be rather hard, but possible.

**Comment by agocke** [comment]
@jmarolf I don't see what CoreFX would have to do with this. If it's supposed to run at compile time, it would need to be in the compiler.

**Comment by RUSshy** [comment]
So.. what's the next step? are you guys interested in this feature?
Is there something i should do?

**Comment by agocke** [comment]
Personally I think source generators will address most of these scenarios and I don't think we need to add anything to the language. I don't think I'll be convinced otherwise until source generators have been shown to be inadequate for some vital scenario.

**Comment by RUSshy** [comment]
Source generator is bad, it is bloated, not automatic, complex, add clutter to project, only just to do such a trivial task

It is sad to see that nobody wants basically free reflection built into the language

**Comment by RUSshy** [comment]
Not only it solve performance issues for reflection heavy programs, but it is also helpful for the upcoming new scenarios in .NET 5 (aot, wasm), and even mobile apps will benefits from this

**Comment by agocke** [comment]
To be clear, this isn't even a proposal. You don't even know what D does, the statement is just to do something like what D does.

For a real proposal you should go learn how D specs traits, as well as the actual code generation strategy, then figure out what that would mean for C#, and write a spec for that.

Until then this is just a discussion, not a proposal.

**Comment by RUSshy** [comment]
This is what i said at the beginning, i want initiate discussion about the feature, i am not planning to make a proposal

> You don't even know what D does

Of course i do

> the statement is just to do something like what D does.

One thing i know is C# run-time reflection is SLOW, generates useless garbage; so yes, doing what D does is much better

You seems hostile to the feature because it is too hard to implement

If your only argument is "you can do it with source generators" then i give up

**Comment by mcosmin222** [comment]
Aren't there some AOT compilers that support reflection just fine?

**Comment by orthoxerox** [comment]
@RUSshy 

> You seems hostile to the feature because it is too hard to implement

Given that Andy Gocke is one of the actual implementors of the C# compiler, it is only natural for him to be hostile towards new features that

- cover the same problem space as other planned features
- lack a concrete spec
- are too hard to implement

> Is there something i should do?

- read or reread https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/
- come up with a use case that isn't solved by source generators, but is solved by compile time reflection (for an example of what is possible with source generators *right now*, take a look at https://github.com/louthy/language-ext/releases)
- work out what changes to C# will be necessarry to support CTR for your use case, at least a high-level view of them

**Comment by RUSshy** [comment]
@mcosmin222

disabling run-time reflection decreases the executable size by a lot, so if you want to target something like wasm, or care about size at all, then having some sort of free reflection is a huge, non negligible, plus

@orthoxerox 

Source generators is not a solution, the point is everyone should be able to have free reflection without having to do complex stuff, that is the work of the compiler, do not delegate the annoying stuff to your users, other languages solved this issue, take their idea, and implement it

.NET 5 will bring AOT compilation and WASM target, better design stuff for it now

**Comment by HaloFour** [comment]
@RUSshy 

> Source generators is not a solution

You have to explain _why_ this is.

**Comment by gleblebedev** [comment]
> the point is everyone should be able to have free reflection without having to do complex stuff

Why this could not be handled at machine code generation point (AOT or JIT)? From my understanding you are focused on AOT scenario. All that needed in this case is a piece of code that would replace GetAttribute and other similar method calls with evaluated value. No change to language required and everyone wins.

**Comment by RUSshy** [comment]
People don't want free reflection, so i guess i'm closing this issue

**Comment by CyrusNajmabadi** [comment]
> People don't want free reflection,

Nothing is free.  Any language feature requires a lot of work.   And any new feature adds complexity to the language.  Furthermore, this sort of work may be subsumed by *other* work.  So investing in multiple ways to accomplish the same thing can be a misuse of resources.

In order to be done, a feature not only has to be something you need, but it has to be something that *demonstrates* it is valuable enough to be worth the very significant costs that come along with it.

**Comment by gleblebedev** [comment]
> it has to be something that _demonstrates_ it is valuable enough to be worth the very significant costs that come along with it

I still propose to make it with Mono.Cecil first by replacing reflection code with evaluated constant value. Then this could be moved into AOT if it gets enough traction.

**Comment by RUSshy** [comment]
well i reopen, maybe some other people will find it interesting and provide more arguments

i still believe my arguments are still solid to have some sort of metaprogramming or some sort of "introspection in the type system"

but maybe that is useless, if dotnet keep rely on heavy useless runtime reflection https://github.com/dotnet/corert/pull/7889

all these stuff make program startup longer, good luck when wasm will be a thing and people will complain about dotnet for being again too heavy for the task and switch to something lighter like rust or go

**Comment by gleblebedev** [comment]
@RUSshy welcome back :-)

So would you accept a build step that modifies bytecode as a first step towards what you are proposing?

**Comment by RUSshy** [comment]
i don't know what you mean, or how that would look like, my goal is to have something like __traits, without having to create a separate project

**Comment by RUSshy** [comment]
i just thought about this:

what about a new block, called ``meta`` just like the ``unsafe`` block

```c#
public void something()
{
    meta
    {
        // do some metaprogramming
    }
}

public meta void something()
{
    // do some metaprogramming
}
```

this new block could help with IDE/analysers, so they know this is metaprogramming and code is fully known at compile time only

```

**Comment by DaZombieKiller** [comment]
What would code within this `meta` block look like?

**Comment by RUSshy** [comment]
I have no idea

**Comment by Rubenisme** [comment]
I think is a great idea. I had an issue today where I wanted to know how many properties a class had at compile time. That's almost like a 'nameof()' function that gives a constant, I'd like to have the same for properties count for example. I can do it with reflection but my coworker doesn't like it because of the performance cost. I just made a constant but should probably make a unit test so that it fails when someone adds a property to the class. Could have been solved easily by something like this.

**Comment by CyrusNajmabadi** [comment]
@Rubenisme can you not just accomplish taht with source-generators?

i.e.:

```c#
[GenerateHowManyPropertiesAClassHas(typeof(ThatClass))]
public partial int GetPropertyCount();
```

Then your source generator runs, finds out how many properties ThatClass has and spits out the partial method that just does `return thatAmount;`.

No runtime cost at all.

Of course, this is only accurate at compile time.  If ThatClass ever changes, your'll have to recompile.  But that's teh idea if you're doing this now instead of actually at runtime when the real values are known.

**Comment by YairHalberstadt** [comment]
> I can do it and did do it with reflection but my coworker didn't like it because of the performance cost

You can do this once at runtime and cache the results. That's a total of a few milliseconds of time at most and 4 bytes of ram. The performance argument really didn't add up.

**Comment by GeraudFabien** [comment]
There is a lot of solution for reflection performance. Even if you don't want to use third party framework :
https://www.c-sharpcorner.com/article/boosting-up-the-reflection-performance-in-c-sharp/

The problem with reflection is that the code easly become a total unmaintanable mess  and reflection as a lot of unexpected behavior.
I had to maintain an asp application entirely made with reflexion. It was a mess there were bug everywhere and it was nearly impossible de debug. 

In my mind only framework should use reflexion (And if they could avoid using it it would be great). A program should avoid using it as much as possible. 

I see a lot of dev who thinks they gonna win time by not writing test, use reflection, make the simplest architecture possible, ... . And at first they earn day of work to release they first feature. But after that they start loosing so much time.  The basic convention exist to make you gain time for most of case. Yes they seems heavy but they are here to help you be faster.

The thinks that bother me the most with reflexion is not it's speed but i read that because they need to store more info on each instance and for all class it slow down the nearly every call to new and a lot of information. Also CoreCLR cannot implement reflexion. So it's a problem to implement some language feature.

**Comment by bugproof** [comment]
https://github.com/dotnet/csharplang/issues/107

**Comment by RUSshy** [comment]
the point of this issue is to have it as a language feature
no external work, even if done once, you still have to carry it (Source Generator), nothing to maintain, it's built into the language
a reflection/type introspection done at compile time, free and transparent
easy to use, standardized, everyone lean the same concept, and everyone uses the same syntax

there is a lot to gain from it

**Comment by HaloFour** [comment]
@RUSshy 

> the point of this issue is to have it as a language feature

Adding something as a language feature is usually the last resort.  If it can be added through other means, like a library or through tooling, there's generally little reason to add it to the language itself.

> there is a lot to gain from it

And a _huge_ amount of effort required to make it happen.  You can't have the compile time reflection you suggest without a compile time macro dialect of the language, which itself would be a massive undertaking.

Languages like D require compile time reflection because they don't have any form of runtime reflection.

**Comment by Dimension4** [comment]
Throwing my two cents in here. C# already has the ability to do reflection and even injection and generation. Why don't we use those but make a guarantee that they are executed at compile time? [Zig](https://ziglang.org), for example, originated from C but made some very interesting additions. In Zig there is a [`comptime` keyword](https://ziglang.org/documentation/master/#Compile-Time-Expressions). This keyword can be used in parameter declarations, variable declarations and expressions. Zig has some other features that make this whole comptime concept integrate even better with the language (types are compile time values there).

Basically, whenever the compiler encounters the `comptime` keyword it switches into interpreter mode and runs the code. Without restriction. When the code throws an exception, or reaches a point that can't be run at compile time, for example an expression that depends on runtime behavior, the compiler stops and emits a compiler error. 

Now this obviously has benefits and drawbacks. The biggest drawback is compile time. Excessive use of that feature will harm your compilation times, obviously. On the other hand, you get compile time errors rather than runtime errors. Personally, I'll always prefer compiler errors over runtime exceptions.

One example coming from production C++ that I've written recently: compile time parsing of guids. Using `constexpr` and literal operators I can now write

```c++
constexpr auto SomeStaticId = "e2468ef4-3f4c-4949-8ac9-b35ca02adc11"_guid;
constexpr auto SomeStaticId2 = "e2468ef4-3f4c-49498ac9b35ca02adc11"_guid; // compiler error, missing '-'
constexpr auto SomeStaticId3 = "pxadddef-3f4c-4949-8ac9-b35ca02adc11"_guid; // compiler error, invalid characters "px"
```

I know this is a small thing, but small things also add up. I'd also argue that there is quite a bit of code out in the wild that uses runtime reflection or runtime code generation because it's either their only option or just the most convenient one, not because they want to use it.

Another construct, which isn't so much reflection but code generation, are type providers in F#. Let's assume C# supports those and type aliases (i.e. `using MyType = Dictionary<string, int>;`). One could write code like this:

```C#
using MyApi = SwaggerProvider.Load<"my-web-service.com">; // <...> are used to indicate compile time execution here

var api = MyApi.Connect("https://my-webservice.com"); // connect to web service at runtime
api.Endpoint1(1, 2, 3); // does a POST to https://my-webservice.com/Endpoint1 (or whatever has been specified in the swagger config)
```

This snippet queries "my-web-service.com" during compilation and fetches the swagger config. That config is parsed and a type is generated from it. Since this is a normal type, we get full intellisense and compiler support for parameters and endpoints.

Going back to Zigs `comptime` again, another use case are complex computations or compile time resource loading:

```C#
class ParamSet
{
    public int MinTemperature { get; }
    public int MaxTemperature { get; }
    public double Scale { get; }

    public void Validate()
    {
        if (MinTemperature > MaxTemperature)
            throw new ArgumentException(...);   // This exception would trigger a compiler error
        
        if (double.IsNanOrInfinity(Scale))
            throw new ArgumentException(...);
    }
}

static class ResourceLoader
{
    public static T Read<T>(string file)
    {
        var obj = Json.Deserialize<T>(file);
        obj.Validate();
        return obj;
    }
}

class Program
{
    // const implies that the method is executed at compile time, no IL code is generated. 
    // Rather, the resulting object is directly embedded into the assembly.
    const var Params = ResourceLoader.Read<ParamSet>("/my_repo/prebuild_computations/params.json");
    ...
}
```

This last snippet hasn't much to do with reflection either. I just want to point out that the potential compile time features could be much more than just reflection.

**Comment by HaloFour** [comment]
@Dimension4 

Source generators will support a lot of those scenarios without requiring syntax changes to the language.  They don't run code within the current project, but they can interpret the syntax tree of the current project and emit additional source that is to be compiled with the project at compile time and without requiring additional tools.  Scenarios like F# type providers or generating client code from a local OpenAPI spec seem like prime targets source generators.

**Comment by Dimension4** [comment]
@HaloFour Oh I'm not arguing against that. I just wanted to shine some light on different approaches. Although I personally would prefer some lanugage extesions for slef mutating code (like D, Zig or Rusts macro system). On the other hand, looking at some of the upcoming language changes like Records and Roles I can see why we don't want even more syntax changes. Either way, I'm glad we get proper compile time code gen.

**Comment by GeraudFabien** [comment]
I don't see any link with performence of reflexion (the problem of the issue), the solution proposed here and source generation at [build/run]time. As i understand the solution propose here is to use kind of a source generator to bring all the data the reflection api will consume into directly into the variable. This way all the reading become instant. For exemple :
```
Console.Write(typeof(DateTime).FullName);

// Would generate exactly the same IL code than
Console.Write("System.DateTime");
```
I'm not sure i really understand everythinks about the solution since it raise a lot of question on how you manage random access through string or runtime code generation (Fall back to the legacy method/Raise exception ?).
    
But if it's on the subject Reflection to generate source (Compiletime or runtime) against Source generators have the following default:
  - Unmaintainable : No documentation no autocompletion by default the IDE as to do some specific work to generate the documentation. Which may also lead to security, performance an inconsistency (environment) concern. 
  - Do not bring anythinks more than source generators.
  - Slow, hard to debug you don't know the version that was build and you may have a caching policy because it take compile time...
  - Complex to configure : You're CI should be correctly configure (Have access to you're api descriptor...)
  - Séparation of concern, 
  - Work only on the target plateform (for Source generators once the code is generated you don't really care if another dev as an environment where it didn't work).
  - ...

I know it work well in the condition that you want to develop, build and run in the same time (in a nutshell you do scripting) like Jupyter notebook...

FYI :I bieleve the .Net team biggest mistake is adding Reflection on .Net core. To me reflection is just a big stream of problems to everyone even to the one who don't use it (a lot) and block the entire ecosystem. So i'm not very happy that anyone take time to improve this bug generator.

**Comment by Dimension4** [comment]
@GeraudFabien Without reflection a lot of things in .Net wouldn't work. 

- ASP needs it to configure routing and wire up the web service. 
- Serialization wouldn't work, you would have to manually serialize everything all the time (like in C++).
- UI frameworks like WPF rely heavily on reflection to work.

Reflection definitely has its purposes and I'm glad we have it in C#.

**Comment by GeraudFabien** [comment]
I don't want to talk about that it's not the point of the thread and it's hard to have a definitive answer. Reflection bring some powerful feature but also bring a lot of  problem with it. I do not agree with you're exemple ASP, Serialization and WPF as 
some framework does the same thinks without reflection with source generator and/weaver/architecture.  In fact if you want a real example that work you can talk about Entity Framework or Dynamic assembly loading they're way to make them without reflection but it's very very complex.
   
Reflection is a runtime feature that allow the code to analyse itself. It not only just a way to generate source. For exemple 'Type' class. Code generator, Weaving like serializer aren't reflection.
   
I'm so sorry my reply was about the fact that you're discussion was out of the topic of the thread. I shoudn't have talk about that and bring myself off topic too.

**Comment by sighoya** [comment]
The more interesting part in D are templates. Although limited, they are much simpler to deal with:
```D
int test(int x)
{
    int r = -1;
    switch(x)
    {
        static foreach(i; 0 .. 100)
        {
            case i:
                r = i;
                break; // error
        }
        default: break;
    }
    return r;
}

static foreach(i; 0 .. 200)
{
    static assert(test(i) == (i < 100 ? i : -1));
}
```

`static foreach` duplicates code fragments with counter substitution and `static if` is a form of conditional compilation. See [condittional compilation](https://dlang.org/spec/version.html).

**Comment by RUSshy** [comment]
> The more interesting part in D are templates. Although limited, they are much simpler to deal with:
> 
> ```d
> int test(int x)
> {
>     int r = -1;
>     switch(x)
>     {
>         static foreach(i; 0 .. 100)
>         {
>             case i:
>                 r = i;
>                 break; // error
>         }
>         default: break;
>     }
>     return r;
> }
> 
> static foreach(i; 0 .. 200)
> {
>     static assert(test(i) == (i < 100 ? i : -1));
> }
> ```
> 
> `static foreach` duplicates code fragments with counter substitution and `static if` is a form of conditional compilation. See [condittional compilation](https://dlang.org/spec/version.html).

Exactly, as i use the language more and more, i discover new things and i am amazed how good the language is
