### ISSUE TITLE
Proposal: Overload for TryParse() to assign value of Type T if parsing fails

### ISSUE THREAD

**Issue by asmarkis** [dotnet/csharplang#2942]
Hi. I was reading through another feature request for ternary operator without the else condition when working with TryParse, but it raises a concern on what should happen by default, especially when assigning variables. This brings me to propose an enhancement to TryParse that can save time in assignment if the parsing fails.

Take this example:
```
int value;
if (!int.TryParse(stringValue, out value))
value = 42;
```

This can be simplified currently as such:
`int value = int.TryParse(stringValue, out value) ? value : 42;`

But my proposal would be the ability to handle this situation within a TryParse overload itself:
`int.TryParse(stringValue, out int value, 42);`

Where `42` is the value assigned if parsing could not determine a value to assign. Essentially a default value overload:
`bool T.TryParse(string s, out T result, T default)`

In many cases, I'm sure, models are created with default values within them to ensure good practices; in my case I am just using the code above to parse configuration strings and providing other methods with the parameters.

Interested in what the experts think about this one 😃

**Comment by theunrepentantgeek** [comment]
Why pass a default? `TryParse()` could take a **ref** parameter and only overwrite if the value was successfully parsed. 

``` csharp
bool T.TryParse(string s, ref T result)
```

*But* ... I don’t think either is actually a good idea. Using default values when parsing fails might be convenient, but my experience is that it’s a code smell that often points to a security risk or configuration bug. 

If you do want to pursue this, head over to the CoreFx repo, as it’s a library design issue, not a language one.

**Comment by HaloFour** [comment]
@asmarkis 

While `TryParse`-like methods are common in the framework the compiler has no special knowledge of them or that the `out` parameter has any relationship with the return value.  This proposal would require that special knowledge so that the compiler can assign the default value, otherwise the variable would be assigned to whatever the method assigned the variable to, which is `0` in the case of `int.TryParse`.

@theunrepentantgeek 

The BCL couldn't add overloads that took a `ref` instead of an `out` because to the CLR `ref` and `out` are the same thing.  C# uses metadata on the parameter to enforce the `out` behavior, but it's completely optional.

IMO, _if_ CoreFX were to consider a new method I might suggest taking a page from LINQ and going with `ParseOrDefault`:

```cs
public struct Int32 {
    public static int ParseOrDefault(string value, int defaultValue);
}

int value = int.ParseOrDefault(stringValue, 42);
```

**Comment by 333fred** [comment]
This is not a language request, but a request for adding a new function to corefx. If you still want it, please open an issue on that repo.
