### ISSUE TITLE
Allow struct local method to use 'this'

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#2979]
The following code produces error CS1673 "Anonymous methods, lambda expressions, and query expressions inside structs cannot access instance members of 'this'. Consider copying 'this' to a local variable outside the anonymous method, lambda expression or query expression and using the local instead":

```c# 
public struct SomeValueType
{
    bool _writeWithDiagnostics;
    private ItemWriter _writer;

    public void Write<T>(T value)
    {
        if (!_writeWithDiagnostics)
            _writer.Write(value);
        else
            WriteWithDiagnostics(value);

        void WriteWithDiagnostics(T value)
        { 
            // extra diagnostics stuff
            _writer.Write(value); // throws error here for trying to access 'this' field _writer
        }
    }
}
```

This error makes sense for anonymous methods, lambdas, etc, but not for local methods which should just get translated to normal instance methods and method calls and thus should be able to access 'this' without any problems.

**Comment by Joe4evr** [comment]
> This error makes sense for anonymous methods, lambdas, etc, but not for local methods which should just get translated to normal instance methods and method calls and thus should be able to access 'this' without any problems.

That's not strictly speaking true, since local functions can still be "saved for later" by method-group conversion to a delegate type.
Anyway, the fix for this is easy, declare your local method as:
```cs
void WriteWithDiagnostics(T value, ItemWriter writer)
```
Bonus: You can now declare this as a *static* local function so the compiler will enforce that it doesn't capture any outside state.

**Comment by mikernet** [comment]
This is a simplified example. There are 2 other locals plus a couple of instance methods on the current struct that are called inside the local method. I know what the fix is, it just reduces the usefulness of local methods in structs.

Any instance method can be "saved for later" with a delegate conversion as well, still has access to "this". The reason structs don't allow this by default is that "this" operates on a copy of the struct inside an anonymous method. That's not the case with a local function.

**Comment by mikernet** [comment]
The "real fix" for the situation above requires me to pass "this" by ref to the local function but that just shouldn't be necessary.

**Comment by mikernet** [comment]
If there's no way for me to access "this" in the method anyway then the compiler should be optimizing the method as a static regardless.

**Comment by huoyaoyuan** [comment]
Unlike reference types, struct methods must be boxed when used as delegate, because of the `object` member. And for mutable structs, there are question about whether write changes back to the source.
Currently there's no distinguish between "capture this" and "capture local". **Only** for local functions on readonly structs that's not converted into delegate, I'm confidential that capturing `this` won't introduce problem.

**Comment by mikernet** [comment]
Yes, I pointed that out above. I think a local method should behave the same as any other instance method in terms of "this". It's just a way of scoping an instance method within another method. So for a mutable struct it should be able to mutate the value just like any other instance method. Capturing it in a delegate should be no different than capturing any other instance method - it would operate on a copy.

**Comment by huoyaoyuan** [comment]
> Capturing it in a delegate should be no different than capturing any other instance method in a delegate - it would operate on a copy due to boxing.

That's the key difference - the boxed value is copied, and changes are not written back to source. Providing a "callback" to write it back is nearly impossible.

**Comment by mikernet** [comment]
I'm not suggesting it should provide a callback, I was saying exactly the opposite. Let me revise my last statement though as I just played around with a couple things - local methods should be allowed to use "this" as long as they aren't converted to a delegate. The point of error should be where it is used as a delegate, not where "this" is used inside the local method.

Local methods have a wider purpose than delegates and there are often situations where the local method is never used as a delegate.

**Comment by huoyaoyuan** [comment]
I think the language team thinks it's too complicated to give correct decision of structs. Structs have variations of readonly, mutable, ref readonly, ref mutable. Even if you can give a precise if-then condition, it will be not easy to implement in constructor: the local function context model must contain these extra information.

However, workaround for users is very simple. So they decide to leave less work to the user, rather than making the compiler data model a mess.

**Comment by mikernet** [comment]
Nevermind, I was getting an error before because I was messing around with a `ref struct` which has more restrictions, so I retract my last statement. C# is perfectly fine with letting you assign an instance method in a struct to delegate, so why should an instance local method be any different?

**Comment by huoyaoyuan** [comment]
> C# is perfectly fine with letting you assign an instance method in a struct to delegate, so why should an instance local method be any different?

Instance methods differ from local methods with capturing. Local methods is more likely aligned with lambdas.
https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0AZAlgOwI4G5ZYQBmRAZwBcAnAVwGNLEBlWAb1kS+TJ0oG0AuogAehGN0SdupZBDCIAsgAoAlNK4cJkmQHZEaxAF4AfIkoALTOVQjUAYQD2tbJTXjJAX1iegA
C# has already disabled such `this` usages in lambdas.

**Comment by mikernet** [comment]
If this works:

```c#
public struct Test
{
	int _value;
	
	public void Method()
	{
		Action x = Method2;
                x();
	}
		
	private void Method2() 
	{
		Console.WriteLine(_value);
	}
}
```

Then there's really no reason why this shouldn't work:

```c#
public struct Test
{
	int _value;
	
	public void Method()
	{
		Action x = Method2;
		x();

		void Method2() 
		{
			Console.WriteLine(_value);
		}
	}
}
```

I know it's more closely aligned internally and shares some capture logic but logically a local instance method should be treated just like an instance method. It makes sense to disallow "this" in lambdas because of struct copy issues but that simply isn't the case with local methods being used as methods.

The workaround isn't terrible so I'm not that invested in this, just pointing out an area where restrictions carried over from lambdas don't necessarily make sense with local methods.

**Comment by HaloFour** [comment]
> This error makes sense for anonymous methods, lambdas, etc, but not for local methods which should just get translated to normal instance methods and method calls and thus should be able to access 'this' without any problems.

The implementation of a local function depends a great deal on exactly what the containing method does, not just what the local function does.  If the containing method also contains a capturing delegate then the compiler will also emit the local function as a capturing delegate because the cost has already been incurred, and in those cases it would be illegal to capture `this`.  It's safer to always disallow such a capture rather than have it disallowed for what would seem to be inexplicable reasons which would have to be spelled out in the specification and would lock the C# compiler into that implementation for all time.

Also note that when working with structs that `this` is a `ref` type.

**Comment by mikernet** [comment]
Hmm...interesting. Alright, closing this issue as the workaround to just pass `ref this` as a parameter is simple enough and I didn't realize the degree of difficulty this will apparently cause.
