### ISSUE TITLE
XML docs are so 1999. Let's replace them with something less verbose.

### ISSUE THREAD

**Issue by ekolis** [dotnet/csharplang#2987]
Ironically enough, this is one thing that Java has always done better than C# - its code comment documentation is much cleaner looking than C#'s XML docs! I don't know what to replace XML docs with but maybe look to Java for inspiration?

**Comment by sharwell** [comment]
Related to:

#878
#891
#2394

**Comment by miloush** [comment]
While "do something with the comment documentation" appears to be a popular suggestion, I would argue that something being "so 1999" is not a valid argument. An impactful change like this should be solving an actual problem (e.g. verbosity) so bad, that it is worth for the compiler to keep two separate implementations of the comment parser, practically forever. Adding a new syntax every 5 or 10 years just because it is popular at the time isn't very sustainable.

**Comment by sharwell** [comment]
@miloush I've updated my proposal to clarify that I'm proposing delegating processing to a "documentation analyzer" that can be updated similar to code analysis analyzers.

https://gist.github.com/sharwell/ab7a6ccab745c7e0a5b8662104e79735#language-and-compiler

**Comment by MgSam** [comment]
> While "do something with the comment documentation" appears to be a popular suggestion, I would argue that something being "so 1999" is not a valid argument. An impactful change like this should be solving an actual problem (e.g. verbosity) so bad, that it is worth for the compiler to keep two separate implementations of the comment parser, practically forever. Adding a new syntax every 5 or 10 years just because it is popular at the time isn't very sustainable.

Keeping bad syntax around "because that's the way we've always done it" is not sustainable. If we used that reasoning, we should all be writing Fortran or Pascal. Using XML for code documentation was as bad of an idea in 1999/2000 as it is today, and vastly inferior to the documentation syntax used most other mainstream modern languages. 

What is true is that the language team has shown zero interest in making any changes here. I chalk that up to no one in Redmond outside of documentation teams ever actually having to **write** XML docs.

**Comment by tannergooding** [comment]
>Using XML for code documentation was as bad of an idea in 1999/2000 as it is today, and vastly inferior to the documentation syntax used most other mainstream modern languages.

XML is a decent final format for documentation. It is unambiguous, well-defined, fast to parse, and easily serializable. It is already supported on all major platforms, by most tooling/IDEs, and even browsers. It is fairly trivial to convert from XML to another format (such as HTML, doxygen syntax, markdown, etc) and can be compressed very well using binary XML.

One of the biggest flaws around it is verbosity. It just isn't as nice to be human written or read as something like Markdown or Doxygen comments.

> Keeping bad syntax around "because that's the way we've always done it" is not sustainable

I would say, in the same vein, changing the format of documentation every 'x' years (even if only every 20 years) is equally unsustainable. Documentation comments are, for better or worse, part of the language spec and directly understood by the compiler.

> What is true is that the language team has shown zero interest in making any changes here.

I don't think this is a language problem. It is instead likely a tooling problem. People don't want to read/write XML. This could be solved, without revving the language, by providing a language service API or IDE feature that displays XML comments in a well-rendered format (such as we do for IntelliSense) and only switching back to XML when editing (https://github.com/dotnet/roslyn/issues/39991).

Likewise, a language service API or IDE feature could be provided that allows you to write your comments in a desired format (say Markdown) but ultimately stores it as the recognized XML format when you finish editing.

Such a path would likely be more sustainable/extensible long-term, would let developers write documentation in their "favorite" format, and would require no changes to the actual language (which would be more broadly impactful in terms of tooling, code consistency, etc).

**Comment by MgSam** [comment]
As an output, I agree, XML is fine. Honestly, I couldn't care less what the output format of the docs is. But reading/writing XML in source code is horrible. It is overly verbose to read and write. It requires escaping common characters. It is such a poor user experience that it almost actively encourages developers to not use.

I'm not a fan of using IDE solutions as a kludge around poor language features. Modern C# can be written in many different IDEs, not just Visual Studio. Trying to improve the editing experience in all of them is unlikely to happen. Not to mention, Microsoft hasn't improved the editing experience for XML docs in VS in 20 years, seems unlikely that they'd do so anytime soon. 

I don't see how improving the doc syntax is any different from the many other feature evolutions that take place in C#, or any other language, over time. Anonymous delegates were almost immediately made obsolete via lambda syntax. Array type inference made array initialization inference obsolete and confusing (`var a = new[] { 1, 2, 3}` vs `var a = {1, 2, 3}`. Switch expressions may soon make switch statements largely obsolete.

**Comment by sharwell** [comment]
> Such a path would likely be more sustainable/extensible long-term, would let developers write documentation in their "favorite" format, and would require no changes to the actual language (which would be more broadly impactful in terms of tooling, code consistency, etc).

It's not possible to address some of the parts of my proposal without language/compiler changes. The main issue that needs a language change is the ability to create a semantic reference from a comment *within a method* to some other code element such that it participates correctly with Find All References and Rename scenarios.

**Comment by tannergooding** [comment]
> I don't see how improving the doc syntax is any different from the many other feature evolutions that take place in C#, or any other language, over time. 

I think one of the differences is that documentation and comments in general are very stylistic in nature. Once is all said and done, documentation isn't really a language problem. You aren't trying to tell a computer how to accomplish a particular task. Instead, you are trying to explain to another developer what a given thing does and the contract it follows.

If we stick with XML some people will not like it due to verbosity. If we choose 'x', some people will complain that it isn't 'y' instead. If we choose 'z' today, people might be complaining about how it is outdated 5, 10, or 20 years from now. Even today, there are plenty of people that complain about 'x', 'y', 'z', and even 'w' (whether it is verbosity, or readability, or number of syntax variations, etc).

I also don't think we want to end up in a scenario where we have to support exposing syntax for multiple documentation variations: XML documentation and future documentation format 'x' or where we get "locked" in because 'x' was converted to XML as 'y' and now its potentially a language breaking change to modify that.

> I'm not a fan of using IDE solutions as a kludge around poor language features.

The language feature itself isn't poor, it's just verbose. This is good, IMO, since you are taking generally unrestricted input and trying to map it to a well-defined parsable format. People don't like typing, even with the existing IntelliSense completion, which is the primary reason people don't like the existing format (another is it can be hard to read when you start getting into lists, tables, etc).

When people don't like typing or reading, it really becomes a tooling problem and how it can be better presented to the user. Multiple IDEs needing to support a feature is also already a problem (VS, VS Code, VS for Mac, 3rd party IDEs, etc) and one that is at least partially solved by having Roslyn as the base language service. This, in general, makes it simpler to support certain features across a range of tools.

**Comment by tannergooding** [comment]
> It's not possible to address some of the parts of my proposal without language/compiler changes. The main issue that needs a language change is the ability to create a semantic reference from a comment within a method to some other code element such that it participates correctly with Find All References and Rename scenarios.

I think that is just a language service problem, not necessarily even a compiler/language service problem.

We already validates and exposes relevant information for symbols within the relevant XML documentation tags. The language service could likewise (similarly to how it does with regex and json string literals now) independently validate arbitrary comments and expose additional information from them.

I don't think its a good idea for the compiler itself to try and otherwise parse out arbitrary comment text and it certainly shouldn't be spec'd in the language.

**Comment by sharwell** [comment]
> The language service could likewise ... independently validate arbitrary comments and expose additional information from them.

The minimum required change to support this is:

1. Relaxing CS1587 (XML comment is not placed on a valid language element) to only report a warning if the first non-whitespace character of the comment is `<`
2. Updating the parser to not analyze the contents of such a comment as XML (which can result in warnings for incorrect syntax)

This provides validation, navigation, and refactoring support, but leaves us in the unpleasant situation where documentation comments can be clean and simple if and only if they aren't trying to document a code element.

I agree that the language shouldn't be providing the detailed functionality here. My proposal focuses on a shared interop format based on the current XML syntax, and an extensibility mechanism where users can provide their documentation interpretation of choice.

**Comment by tannergooding** [comment]
> and an extensibility mechanism where users can provide their documentation interpretation of choice.

Could you elaborate on that bit? It sounds like we are basically proposing the same thing 😄 

I think the difference here comes from your point 2, where it sounds like you are suggesting it be allowed to actually store the cs file with non-xml (hence requiring language changes) and where I am suggesting it be entirely a tooling experience and it is ultimately saved to disk as the existing XML documentation format (thereby requiring no language changes, only tooling changes).

**Comment by sharwell** [comment]
> Could you elaborate on that bit? It sounds like we are basically proposing the same thing 😄

@tannergooding Yes I linked to it above in https://github.com/dotnet/csharplang/issues/2987#issuecomment-557828062

> ... it sounds like you are suggesting it be allowed to actually store the cs file with non-xml ...

Yes. To me it seems unnecessary to store the C# file with XML comments since the final rendered AssemblyName.xml file is going to be the source-of-truth for consuming features. I always found the C# language specification for documentation comments to be sorely lacking (meaning it is incomplete with respect to a large number of cases, as opposed to a statement on verbosity). Rather than try and fill in that specification to address the holes, I would prefer to build a more complete specification for the shared documentation output files and allow users to work at a level more comfortable to a specific team.

**Comment by miloush** [comment]
> The minimum required change to support this is

Couldn't you just use standard, non-XML comments instead?

**Comment by FiniteReality** [comment]
I might sound weird for saying this, but I honestly prefer the C# XML doc format to alternatives, such as Javadoc. It feels more rigid and less sensitive to e.g. whitespace changes and frankly, IMHO, it's actually easier to read.

As a compromise, making the `summary` element the "default" and supporting Markdown in place of XML in this case could work. For example:
```cs
/// This is a *markdown* summary. It contains some
/// `cool` inline text, and [links!](example.com)
/// <param name="param1">The parameter</param>
/// Text after the first valid XML element is an error. It must be wrapped in XML tags.
public void MyMethod(int param1) { throw null; }
```

**Comment by HaloFour** [comment]
I work with a lot of C#, Java, Scala and Python.  All of which have different documentation comment formats.  And for any code that has non-trivial documentation they're all about equally as awful.  They're just giant walls of text with assorted different forms of markdown and quirks that you need to know to get them to be interpreted correctly.  _None_ of them are designed to be read by a human.  It's a failure of the tooling that they're displayed as verbatim source rather than as something machine digested and human readable.

IMO, the writing experience between them is also about equivalent given that the IDE will autocomplete most of the markdown for you.

I'm not arguing against these features because I think that XML is better or that other formats will be worse, I just think that they're all just different shades of lipstick on the same pig.  To be honest the idea of removing documentation comments from the language entirely and making it a separate analyzer-like extension sounds the best to me, although I'd want whatever supports that to be able to provide the same tooling experience as we have today, if not better.

**Comment by nanoant** [comment]
> As a compromise, making the `summary` element the "default" and supporting Markdown in place of XML in this case could work. For example:

Couldn't agree more on that. And this is my biggest problem reported in https://github.com/dotnet/csharplang/issues/2394 that C# code is drowning with `<summary>`-ies, which is depending on your style consumes 2 lines, without much added value.

We can get into endless discussion about next fine documentation syntax, and bounce the ball between those who hate XML doc and these who don't, but I dare to say there is none that can defend need for `<summary>`. I have once seen some compilation of the most common (key)words in C# and guess which word was the most popular?

How about removing necessity for `<summary>` ASAP, before we continue any other activities in XML doc area, so everything that is not wrapped by top level tag becomes summary by default? Seriously, this would transform XML doc into something I (and probably many others) can live with.

Btw. even .NET runtime itself does not always use XML doc, see:
* https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections/src/System/Collections/BitArray.cs
* https://github.com/dotnet/runtime/blob/master/src/libraries/System.Collections/src/System/Collections/Generic/Queue.cs

I'd love to hear why is it so.

**Comment by branko-d** [comment]
For what it's worth, Resharper has a nice renderer for XML docs.
