### ISSUE TITLE
Shorthand for generic Task

### ISSUE THREAD

**Issue by VilemProchazka** [dotnet/csharplang#3017]
With most of codebases being almost entirely async, the Task<> type seems increasingly like an unwanted boilerplate that decreases the readability of code.

I propose a compiler sugar for specifying generic task types. The goal would be to shift focus from the fact that the type is Task<> (which it almost always is for example for return types) to the specific type itself.

**Example:**
Instead of:
`public async Task<List<int>> GetIds()`

We'd write:
`public async $List<int> GetIds()`

**Nested example:**
Instead of:
`Task<IEnumerable<Task<SomeType>>>`

We'd write:
`$IEnumerable<$SomeType>`

This proposal is only about a quality of life improvement. The end result would be better readability and a couple of saved keystrokes.

**Comment by HaloFour** [comment]
@VilemProchazka 

> The end result would be better readability and a couple of saved keystrokes.

I disagree, the end result would be less readability and a couple of saved keystrokes.  The fact that method returns `Task<T>` is very important, particularly to callers of the method, particularly because an `async` method can return types other than `Task<T>`.  The compiler supports a pluggable task-like model where many different types can be returned, including `ValueTask<T>` and custom types.

**Comment by VilemProchazka** [comment]
> @VilemProchazka
> 
> > The end result would be better readability and a couple of saved keystrokes.
> 
> I disagree, the end result would be less readability and a couple of saved keystrokes. The fact that method returns `Task<T>` is very important, particularly to callers of the method, particularly because an `async` method can return types other than `Task<T>`. The compiler supports a pluggable task-like model where many different types can be returned, including `ValueTask<T>` and custom types.

Thank you for your feedback. 

The syntax still makes it clear the value is a Task of something, it just puts more emphasis on the something. You are not just saving 3 keystrokes on the Task but also remove a nesting level which does help with readability. It also does not prevent you from using the original style for the different task-like types. It just tries to solve the most common annoyance.

**Comment by theunrepentantgeek** [comment]
🤔 I see two problems with this.

_Problem the first ..._ 

The nesting you're proposing to remove is standard generic type notation that we've all been learning and getting used to since .NET 2.0 was released in 2006. Introducing an arcane piece of punctuation as syntactic sugar for syntax we're all familiar with already doesn't seem like a readability improvement to me, just yet another special case that needs to be memorized and recognized.

Readability isn't significantly affected by a minor change the number of characters present - as your eye saccades across the line of code, you'll read `$List<int>` in one glance just as you'll read `Task<List<int>>` in one glance. The overhead comes when your brain needs to do the semantic analysis to understand what the characters mean - and having multiple alternative approaches doesn't make things faster.

_Problem the second ..._

This elevates a particular type - `Task` - to an elevated position in the language. It's effectively saying that while the language _supports_ many different kinds of _awaitable_ type, there's this one sacred type that's held up as the best one that people should use.

If this had been done with the original feature release of **async**, performance enhancing innovations like [`ValueTask`](https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/) would have been impossible.

**Comment by VilemProchazka** [comment]
Fair enough. 

The prevalence of Task is a source for major annoyance for me. It does feel like it has an elevated position in the language. Realistically, the real underlying problem is likely different and unsolvable at this point given the gradual evolution of the language.

Thank you all for taking your time to give feedback.
