### ISSUE TITLE
Syntax to silence 'CS8606: possible NRE' when casting a foreach iteration variable

### ISSUE THREAD

**Issue by jnm2** [dotnet/csharplang#3045]
There doesn't seem to be any way to place a `!` to silence the nullability warning:

([SharpLab](https://sharplab.io/#v2:D4YgdgrgNlCGBGUCmACJYHILAChcAEAmFAYRVwG9cUaV8AWFAWQAp8BGAOhIHsYkAxgBcAljzABnThwDMKMOIDi6JACcRA3v2FiwASnI5aKKkeO0A9BdIBlABwA2AAwOAXCgAKPCRJGJUkDAoqkgAZmroAqiwPiIA5mAAtuhCKEI8KCJCarCi4igAbrDqmEjU5jRWFbSAyYR1NeUVoTwhsAIAFigsZFlIiZlg8koq6pp8yDrieo3mptUoAL4zSzgrQA=))

```cs
using System.Windows.Forms;

#nullable enable

void M(Control control) 
{
    // CS8606: Possible null reference assignment to iteration variable
    //               ↓↓↓↓↓↓↓↓↓↓↓↓
    foreach (Control childControl in control.Controls) // ControlCollection is non-generic
    {
        // Use `childControl`
    }
}
```

### Suggestion

Since the warning is on the iteration variable name token, I expected this to work:

```cs
using System.Windows.Forms;

#nullable enable

void M(Control control) 
{
    foreach (Control childControl! in control.Controls) // ControlCollection is non-generic
    {
        // Use `childControl`
    }
}
```

### Workarounds

A pragma around the `foreach` line seems uncouth.

I begrudgingly declared the iteration variable as nullable and moved the assertion into the body of the loop, but this is misleading at first read and I had to explain it:

```cs
using System.Windows.Forms;

#nullable enable

void M(Control control) 
{
    foreach (Control? childControl in control.Controls)
    {
        // Use `childControl!`
    }
}
```

This adds a bit of overhead, but I could give up on iterating over the actual collection and wrap it with Cast:

```cs
using System.Windows.Forms;

#nullable enable

void M(Control control) 
{
    foreach (var childControl in control.Controls.Cast<Control>())
    {
        // Use `childControl`
    }
}
```

**Comment by JohanLarsson** [comment]
Should it warn at all?
I'm thinking that specifying explicit non-nullable type for the iteration variable is already an override. Problem is with legacy code I guess.

**Comment by jeroen-mostert** [comment]
The implicit conversion behavior of `foreach` is a wart from when we had no generics, but since, for better or worse, it applies even today for things other than the non-generic `IEnumerable` (`foreach (int i in new object?[] { null }) {}`), accepting `foreach (T t in Collection)` as valid regardless of the type of `enumerator.Current` would be a step backwards -- it hides what may well be a valid nullability warning, as there are plenty of enumerables that do allow `null`s.

`Cast` solves the problem from a practical POV (and has been my preferred approach to dealing with non-generic collections even before NREs) but extending the syntax to allow a minimally intrusive solution has some force of elegance in completeness behind it. After all, a `foreach` is just syntactic sugar for a more elaborate block where such an override could be added explicitly, if we wrote it out ourselves (`Control control = (Control) enumerator.Current!`).

**Comment by jnm2** [comment]
This would be solved by the proposal to stop warning for the existing syntax: https://github.com/dotnet/csharplang/issues/3214

**Comment by RikkiGibson** [comment]
@jnm2 it looks like we have merged the change to make IEnumerator.Current oblivious, is this issue still relevant?

**Comment by jnm2** [comment]
Not for me, thanks!
