### ISSUE TITLE
Compatible signature delegate type implicit cast

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3068]
I know this has been discussed in several issues before, i.e. https://github.com/dotnet/csharplang/issues/149 and https://github.com/dotnet/csharplang/issues/470, but there is one approach that I believe hasn't been considered yet, which is using `Unsafe.As` which I wanted to raise here for consideration:

```c#
public delegate void MyAction();

Action x = () => Console.WriteLine("Delegate invoke success!");

// Current approach, chaining calls to invoke, has performance impact on delegate invocations:
MyAction y = x.Invoke;

// New approach, "MyAction y = x;" effectively compiles to the line below:
MyAction y = Unsafe.As<Action, MyAction>(ref x);

y.Invoke(); // Outputs: "Delegate invoke success!"
```

From what I can tell this works fine for equivalent signature delegates. Is there a reason this approach couldn't be adopted for implicit delegate conversions in C# without the overhead of chaining calls to `Invoke`?

**Comment by mikernet** [comment]
The only issue I can see is if at the CLR level subclassing `Delegate` isn't constrained to the standard implementation so it might be possible that a delegate defined in an assembly originally written in IL or another language might not be compatible with this kind of unsafe reference reinterpretation, but I don't know exactly how that side of things works.

**Comment by KalleOlaviNiemitalo** [comment]
If you unsafely cast to a different delegate type, then I think `GetType` will reveal the original type anyway. If you add such a delegate as an event handler, and the same event has other handlers, then the `Delegate.Combine` call in the accessor is likely to throw `ArgumentException`.

> Worst case scenario, perhaps the compiler could make sure that both delegate types directly subclass System.MulticastDelegate and don't introduce any new fields before allowing this implicit cast?

ECMA-335 6th ed. §I.8.9.3 does not allow additional fields in delegate types, and §II.14.6 does not even allow additional methods. However, I tested that .NET Framework 4.8 allows constructing and using an instance of a type that derives from `System.MulticastDelegate` and has an instance field and a property with a getter and a setter, in addition to the members that delegate types normally have.

CoreCLR refuses to load:
- delegate types that implement a constructor, instead of letting the runtime provide it <https://github.com/dotnet/runtime/blob/f23e2796ab5f6fea71c9fdacac024822280253db/src/coreclr/src/vm/methodtablebuilder.cpp#L3220-L3231>
- user-defined classes that derive from `Delegate` rather than `MulticastDelegate` <https://github.com/dotnet/runtime/blob/f23e2796ab5f6fea71c9fdacac024822280253db/src/coreclr/src/vm/methodtablebuilder.cpp#L12201-L12219>
- delegate types that are not sealed <https://github.com/dotnet/runtime/blob/f23e2796ab5f6fea71c9fdacac024822280253db/src/coreclr/src/vm/methodtablebuilder.cpp#L12221-L12229>
- delegate types that have both fields and covariant or contravariant type parameters <https://github.com/dotnet/runtime/blob/f23e2796ab5f6fea71c9fdacac024822280253db/src/coreclr/src/vm/methodtablebuilder.cpp#L12330-L12336>

**Comment by 333fred** [comment]
@mikernet this seems like a BCL request, not a C# request. If you would like a new API added to `Unsafe`, please open an issue on dotnet/runtime.

**Comment by mikernet** [comment]
@333fred This is a C# request. This is not a request for a new `Unsafe` API, the above code words today.

**Comment by mikernet** [comment]
@KalleOlaviNiemitalo Thanks for pointing out some of the current issues that would need to be addressed for this to work. In my quick test, an `InvalidCastException` gets thrown when I try to add the "casted" delegate to an event of a different type. I'm guessing that might be a bit of a pain to overcome.

**Comment by HaloFour** [comment]
@mikernet 

Have you tried combining delegates that you've used `Unsafe` to convert?  IIRC, that will fail at runtime, because the type header of the delegate still reflects it's original type, and it won't match that of the other delegate.  To my understanding there's no way to do this in C# without chaining the delegates or completely reconstructing it from the original targets, both of which will certainly incur overhead.

**Comment by mikernet** [comment]
@HaloFour Haha, I think you were typing that at the same that I replied just above. I just did now, and I can see how that would be a challenging issue with the way delegates are currently implemented.

**Comment by 333fred** [comment]
> @333fred This is a C# request. This is not a request for a new Unsafe API, the above code words today.

I misunderstood. Sorry about that.

**Comment by mikernet** [comment]
@333fred Thanks for the reopen but given the issues above it seems that we're run into similar roadblocks as the other proposals linked to in the OP so I don't anticipate this is really going to go anywhere. I think this can stay closed.
