### ISSUE TITLE
Respect DoesNotReturn on methods in conditional code

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/csharplang#3078]
**Steps to reproduce**

```csharp
#nullable enable
private static string? Method(object? value)
{
    if (value is null)
        ThrowException();

    return value.ToString(); // warning CS8603: Possible null reference return.
}

[DoesNotReturn]
private static void ThrowException() =>
    throw new Exception();
```

**Expected behavior**
No warning reported by the compiler.

**Actual behavior**
While `ThrowException` never returns under any circumstance the compiler thinks that `value` could be `null`.

**Compiler version:** '3.3.1-beta4-19462-11 (66a912c9)'.
**Language version:** preview.

**Comment by Scott-Caldwell** [comment]
This issue is probably more relevant on [dotnet/roslyn](https://github.com/dotnet/roslyn), but:

I'm not getting any warnings with the sample code.

The only way I'm able to get your code to report `CS8603: Possible null reference return.` is by changing `Method`'s return type to `string` instead of `string?`. And in that situation, the warning makes sense, because `object.ToString()` returns a `string?`, not a `string`.

I'm using Visual Studio 16.5.0 Preview 1.0, compiler version 3.5.0-beta1-19571-01 (fb3f812a).

**Comment by canton7** [comment]
[SharpLab link](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABATARgFgAobABgAJt8A6AERgEMBzAOwHsBnYGAY05oBhdiggBBVowA2CTjE4BuEgGJWAVylTGAIykQKESbogkS2AMxVcFQSQDeJCk4oAHWGEbB91AGxV8ZAD8FACyEMAAFiIAFOzaAFYQvMDBHlJqEACUjs4OxM4FFPAU0WkZRZwU6prZ+YX1ACoRUOwA7gCiAB68EC487KzRmUrEOfXYAOwUZRA0DewAysCwrMxDChQA9JsUrYxQrDCrNgsAHD5k5iAUAApccsZVGlIUUBBw0IY9VBM0YxQAX1MdScAG06OwIJwAHLsYAAJXCagOAF1/m4YB4vP4/NgACwUJotDrdXr9QaZCgAXgAfP8CpFiVUIK0KF0en0YAN1iQAUA=): cannot reproduce either.

**Comment by YohDeadfall** [comment]
Yep, looks like the error mentioned by @Scott-Caldwell was an issue. Found this after opening the ticket.
