### ISSUE TITLE
Bug in nullability flow analysis of non-nullable parameters

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3083]
The compiler seems to be assuming that if the item is not null inside the `if` block then it must be nullable outside of it, but that's not the case - the parameter is already not nullable:

```c#
public static T[] SomeMethod<T>(this T[] items)
{
    if (items != null) {
        // logic that falls through when finished
    }

    return items; // Error: items may be null here
}
```

If I remove the `if` block then it happily lets me return items.

**Comment by mikernet** [comment]
I guess with this method definition I should be throwing on a null `items` parameter which would fix this issue, but the nullability analysis still seems incorrect to me.

**Comment by jmarolf** [comment]
By checking for null you indicate to the compiler that you believe that this value can be null. The method signature does not allow for nulls to be returned yet you've indicated to the compiler that you think that case is possible, so it warns.

Essentially: either the check is superfluous, or there is an actual safety issue. Either way we want to issue a warning here because this is a code smell.

There was some discussion recently about additional changes to this behavior that might be made [here](https://github.com/dotnet/csharplang/blob/f2b71591befc64299a0a513633aeab04ae6d6a54/meetings/2019/LDM-2019-12-18.md#pure-null-checks). 

I assume you would want to compiler to not consider pure null checks as relevant for flow analysis?

**Comment by ufcpp** [comment]
```cs
public static T[] SomeMethod<T>(this T[] items)
{
    if (items == null)
    {
        DoesNotReturn();
    }

    return items; // Error: items may be null here
}

[System.Diagnostics.CodeAnalysis.DoesNotReturn]
private static void DoesNotReturn()
{
    // logic that falls through when finished
}
```

**Comment by mikernet** [comment]
@jmarolf Hmm...that's an interesting perspective. It could make sense if you look at it like that. I guess I'm a bit torn about it now but I can see the reasoning.
