### ISSUE TITLE
Local functions doesn't support method overloading

### ISSUE THREAD

**Issue by saxus** [dotnet/csharplang#3112]
Method overloading is part of C#. But local functions doesn't support it. IMHO the following code should compile and work:

```cs
static void Main(string[] args)
{
    A("1");
    A(2);           // Argument 1: cannot convert from 'int' to 'string'

    void A(string a) {} ;
    void A(int a) { }; // A local variable or function named 'A' is already defined in this scope
}
```

**Comment by HaloFour** [comment]
This was the [decision](https://github.com/dotnet/csharplang/blob/master/meetings/2015/LDM-2015-05-20.md#scope-and-overloading) back in 2015:

> For now, for prototyping purposes, we'll say that local functions are more like local variables: there can only be one of a given name, it shadows same-named things in outer scopes, and it cannot be called from a source location that precedes its declaration. We can consider loosening this later.

So I can assume that the team would be open to it given enough use cases.  But I personally disagree that it should be done because method overloading exists.  Method overload resolution is probably the most complicated part of the C# compiler and it's even difficult for developers to follow given the breadth of the rules when it comes to potential implicit conversions.  It's trivial to give each local function a distinct name and it makes it much easier to follow that code.  It's not like you can expose those functions in a public surface where overloading might provide improved ergonomics.

I'd have to see actual use cases where overloading on local functions makes an actual difference but I suspect that such code would have various design smells and be overly complicated.

**Comment by saxus** [comment]
The current situation when I found this: I had some conversion methods in local functions. The output was the same (int), and the input was ISomething or a Guid which identifies one kind of ISomething. Why? Because the business and speed requirements. 

The conversions was unique in context of the whole project even in the class. It belonged to one specific method. 

Something like this:

`cs
IEnumerable<SomeResult> GenerateResult(
  ISomething object
  IReadOnlyDictionary<Guid, IOtherThing> related) // Guid was identifier of ISomethings
)
{
  // some peraparations and other operations
  foreach (var relatedItem in related /* not necessary directly iteration*/)
  {
    // ...other code
    yield return new SomeResult(
      // ...
      something1: GetSomeDerivatedInfo(object),
      something2: GetSomeDerivatedInfo(relatedItem),
      // ...
    )
  }

  int GetSomeDerivatedInfo(Guid)
  {
    // call some external stuffs and do things
  }

  int GetSomeDerivatedInfo(IOtherThing)
  {
    // works with IOtherThing, different error handling, etc.
  }
}`

Yes, pattern matching can be used here too, but then I've lost the strict typing instantly because the common type between Guid and ISomething is object.
