### ISSUE TITLE
Put local methods into chained constructor argument scope

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3118]
Local methods would be a great way to do complex validation/manipulation of arguments inside the scope of the current constructor before passing them into a chained constructor, i.e.:

```c#
public StringProcessor(string encodingName) : this(GetEncoding(encodingName)) 
{
    static Encoding GetEncoding(string encodingName)
    {
        try
        {
            return Encoding.GetEncoding(encodingName);
        }
        catch (ArgumentException ex)
        {
            throw new ArgumentException(ex.Message, nameof(encodingName));
        }
    }
}

public StringProcessor(Encoding encoding)
{
    Encoding = encoding;
}
```

Given that you currently only allow `static` members to be in scope of the chained constructor call then we can limit this to static local methods.

I run into these kinds of one-use methods for dealing with constructor arguments alllllllllll the time and it would be nice if they didn't have to pollute the type space and could be placed closer to where they are actually needed.

**Comment by Leemyy** [comment]
Does this proposal also include `: base ()` constructor chaining?
Because I find myself wanting that rather frequently.

Small addition: It should probably be an error to use a non-static local method in that way. Otherwise you'd run into all the same issues that this restriction is there to prevent. (E.g. attempting to acces base members before they are initialized)

**Comment by mikernet** [comment]
@Leemyy Yes, it includes chained base constructors. I mentioned the static issue above :)

**Comment by YairHalberstadt** [comment]
Closing as championed at https://github.com/dotnet/csharplang/issues/3980
