### ISSUE TITLE
Method group delegates with default parameters produce arbitrary results

### ISSUE THREAD

**Issue by dasblinkenlight** [dotnet/csharplang#3207]
When I invoke a method that has default parameters through a delegate constructed using method group, the value of the default parameter is ignored, and an arbitrary value is passed instead. Switching to full-lambda syntax fixes the problem.

Use this code to reproduce the bug:

```
using System;
using System.Linq;
namespace Bug20200214 {
    class Program {
        // Sample method Foo ignores its first argument, and returns the value
        // of its optional second argument if it is supplied.
        // When invoked with a single argument, Foo always returns 1.
        public static int Foo(int _, int number = 1) => number;

        static void Main(string[] args) {
            // Invoke Foo 100 times, and add up the results.
            // When full-lambda syntax is used, we get 100 as expected:
            var correct = Enumerable.Range(0, 100).Select(i => Foo(i)).Sum();
            Console.WriteLine(correct); // Prints 100

            // When "shorthand" method group syntax is used, we don't get 100:
            var wrong = Enumerable.Range(0, 100).Select(Foo).Sum();
            Console.WriteLine(wrong); // A number other than 100 is printed
        }
    }
}
```
Both calls should produce the same value (100). However, method group invocation results in an arbitrary number.

Originally filed against Mac OS implementation [here](https://developercommunity.visualstudio.com/content/problem/919007/passing-default-parameter-to-method-group-delegate.html). According to [Matt Wart](https://developercommunity.visualstudio.com/users/18698/79cd982d-10be-48a0-bb0f-475248b181a4.html), the problem can also be reproduced on these platforms:

- Mono on the Mac,
- .NET Core on the Mac
- .NET Framework in Visual Studio for Windows.

**Comment by svick** [comment]
This is the correct behavior. The result of 4950 is not arbitrary, it's the sum of the numbers from 0 to 99. And it's the result, because the code that uses a method group actually calls [the overload of `Select` that gives you an index along with the item](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?view=netframework-4.8#System_Linq_Enumerable_Select__2_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Int32___1__), which is why the code is actually summing up those indexes.

While I understand that this might be confusing, I don't think there's anything to do here.

**Comment by canton7** [comment]
Bang on. Try this but replace Select with a method that only has one overload (which takes a single int parameter), and you should get a compiler error.

**Comment by dasblinkenlight** [comment]
Nice catch, thank you very much. Closing the issue.
