### ISSUE TITLE
[Proposal] Add overload for Dictionary.TrytGetValue() to get ref value types.

### ISSUE THREAD

**Issue by hurleybird** [dotnet/csharplang#3217]
Eg:

```cs
public bool TryGetValue(TKey key, ref TValue value) where TValue : ValueType
```

Idea here is to avoid a currently necessary second access for value types that exists in a number of scenarios.

For example, say you have a dictionary of type <string, int> and an int i which you either want to add to an existing value, or assign as a new item if a key does not already exist.

Currently, this looks like:

```cs
if (dict.ContainsKey(key))
    dict[key] += i;
else
   dict[key] = i;
```

If the key exists we need to perform a second dictionary access, which isn't ideal. However, if we can use the ref keyword on the second TryGetValue parameter we're able to avoid the second access altogether. Eg:

```cs  
if (dict.TryGetValue(key, ref int value))
    value += i;
else
    dict[key] = i;
```

**Comment by dotjpg3141** [comment]
I don't think you proposed API would work.
What would happen if you delete the key while holding a reference to the value?

```cs
if (dict.TryGetValue(key, ref int value)) {
    dict.Remove(key);
    value += i;
} else {
    dict[key] = i;
}
```

**Comment by benaadams** [comment]
Would be a .NET library proposal rather than a C# specific one; here's one for you 😉 

https://github.com/dotnet/runtime/issues/27062

**Comment by svick** [comment]
The proposed API wouldn't work, because that's not how `ref` parameters work: you use them to pass a reference to a variable you provided into a method, you can't use them to get a reference to another variable back.

For that, you need `ref` return and there is already a proposal to do this using that feature: https://github.com/dotnet/runtime/issues/27062.

@dotjpg3141 You're right that this feature would be dangerous, the proposal I linked to above resolved that by "hiding" the method in a different class in an obscure namespace, in an attempt to ensure that you only use it if you understand those limitations.

**Comment by pinkfloydx33** [comment]
There's a [DictionarySlim](https://github.com/dotnet/corefxlab/blob/master/src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/DictionarySlim.cs) in experimental collections that provides something similar to what you want through `GetOrAddValueRef` though as a whole it's got some limitations

**Comment by hurleybird** [comment]
That's right, that's not how ref paramters work. Total brain fart on my part!
