### ISSUE TITLE
[Proposal] fill an array, without Array Fill

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#3233]
Today to fill an array with some default value, you need to call one method

```c#
var normals = new Vector3[128];
Array.Fill(normals , Vector3.UnitY);
```

What about:
```c#
var normals = new Vector3[128];
normals[] = Vector3.UnitY;
```

**Comment by HaloFour** [comment]
Why add a language feature for something already handled perfectly fine by a single method call?

**Comment by RUSshy** [comment]
Well i find it more elegant and natural to write, having to rely on a method is more typing and it breaks the layout when reading stuff, it adds noise

**Comment by EgorBo** [comment]
```csharp
var normals = Enumerable.Repeat(128, Vector3.UnitY);
```

**Comment by DaZombieKiller** [comment]
> Well i find it more elegant and natural to write, having to rely on a method is more typing and it breaks the layout when reading stuff, it adds noise

Having code that is easy to read is far more important than code that is easy to write (imo `Array.Fill` has no negative effects on either of those).

If I see `Array.Fill` I can _instantly_ tell what the code intends to do, with no ambiguity.

If I see `array[] = value;`, my immediate thoughts are:
* Somebody could have forgotten to provide a parameter for the indexer.
* Perhaps the parameter was removed by accident through a find+replace.
  * The `array[] = value` syntax would prevent this from producing a compiler error, adding further confusion.

I would need to look at all of the surrounding code to find out whether it was intentional or not.

**Comment by RUSshy** [comment]
> Having code that is easy to read is far more important than code that is easy to write (imo Array.Fill has no negative effects on either of those).

This is exactly what i said:
>  it breaks the layout when reading stuff, it adds noise

It's like saying:

```c#
var a= new Vector(0,0,1);
var b= new Vector(0,0,1);
var c= new Vector(0,0,1);

var d = a + b + c;
```

is harder to read than

```c#
var a = new Vector(0,0,1);
var b = new Vector(0,0,1);
var c = new Vector(0,0,1);

var d = Vector3.Add(a, b, c);
```

So when you read from up to bottom, your eyes are forced to be shifted by X amount of characters the method have

You need to read where the class is, Array. then what it does .Fill then what you fill 2 times

Then if you are picky
```c#
var normals = new Vector3[128];
normals[*] = Vector3.UnitY;
```

or maybe another solution, to use ranges

```c#
var normals = new Vector3[128];
normals[..] = Vector3.UnitY;
```

**Comment by RUSshy** [comment]
> Why add a language feature for something already handled perfectly fine by a single method call?

To make the language less noisy and more practical, for same reasons operator overloading was added

**Comment by HaloFour** [comment]
If you don't like the look of that method, write your own.  You could even write a single method that creates and fills the array, further reducing the code:

```cs
var array = CreateArray(128, Vector3.UnitY); // done and done
```

Stylistic preference is a poor reason for adding a language feature that is managed perfectly fine by a single method call.  There are no other benefits for doing this.

> for same reasons operator overloading was added

Operator overloading was added very specifically to improve the ergonomics of using mathematic operators with numeric-type types because the alternative is well known to be a very poor experience.  This proposal isn't remotely in the same category.
