### ISSUE TITLE
Proposal: allow "stackalloc" class references' array when using span

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#3294]
Currently the following code is disallowed:
```C#
span<object> arr = stackalloc object[10];
```
But I think that this should be allowed, `stackalloc object[10]` should not mean to allocate 10 objects on the stack, it should mean to allocate 10 object references on the stack (all initialized to null).

**Comment by huoyaoyuan** [comment]
This is a runtime issue, because the corresponding IL instruction only supports struct now.
I'm sure there's a duplication but can't find it.

**Comment by Enderlook** [comment]
Since the runtime doesn't support reference stackalloc and the mentioned issue doesn't have any update the compiler could do a few tricks to emulate this feature without runtime support.

For constant sized stack allocations the compiler could generate a compiler made struct and allocate that on the stack:
```cs
span<object> arr = stackalloc object[4];
```
Becomes:
```cs
_span_object_4 arr_ = default;
Span<object> arr = MemoryMarshal.CreateSpan(ref arr_.field0, 4);

[CompilerGenerated]
[StructLayout(LayoutKind.Sequential)]
private struct _span_object_4
{
    public object field0;
    public object field1;
    public object field2;
    public object field3;
}
```

Sadly, no trick is possible to stack allocate spans of managed types.
However, as a possible fallback `ArrayPool` could be used:

```cs
span<object> arr = stackalloc object[n];
```
Becomes:
```cs
object[] arr_ = ArrayPool<object>.Shared.Rent(n);
Span<object> arr = arr_.AsSpan(0, n); // We don't need to bother in cleaning the span since stackalloc doesn't guaranted zeroed memory AFAIK.
// Rest of method code...
arr.Clear(); // Prevent holding objects in the pool.
ArrayPool<object>.Shared.Return(arr_);
```
