### ISSUE TITLE
Allow the keyword 'let' as synomym of 'var'

### ISSUE THREAD

**Issue by Javaman2** [dotnet/csharplang#3315]
A convenience for Typescript and JavaScript folks is to allow the let keyword to be synonym for var.

 I know this was rejected already, but don't understand why as a synonym of var wouldn't work.  We are not asking for any different function than var already has.

It could even be an opt-in option.

**Comment by CyrusNajmabadi** [comment]
>I know this was rejected already, b

Closing this out as this was rejected.

> but don't understand why as a synonym of var wouldn't work. 

We don't especially want synonyms.

> We are not asking for any different function than var already has.

Yes, that's a problem.  We'd have two identical ways to do the same thing.  That's just confusing.

> A convenience for Typescript and JavaScript folks is to allow the let keyword to be synonym for var.

Note: i was a TS language designer.  This would not be a good thing IMO.  Because TS/JS people would expect this to have 'let' semantics and would expect 'var' to have 'var' semantics.  And that would not be the case.

--

Finally, we may want to use 'let' in the future for another purpose.  Making it a synonym of 'var' would prevent that.

**Comment by Javaman2** [comment]
As poweful as C# is, it's losing ground to Typescript and Javascript. The more C# adopts constructs of Typescript the closer it gets to the most popular languages. 

Without doing that, the Isomorphic concept of Typescript for frontend and backend makes more sense. Node makes that possible today which will,over time; make c# just another legacy language. 

Electron makes c# desktop apps. Legacy too. That and the fractured .net desktop environment puts another nail into .net.

The future is node, angular and electron to give us one time one place for apps.
The reason? They adopted whereas .net did not all the while MSFT desk top solutions were destroyed by bad MSFT corporate descisions.

To not allow c# developers the option to allow new features they desire via configs; is to shut out the concept of open source.

Razor is 20 years too late. It will never equal npm reposities. C# is getting stale..

**Comment by svick** [comment]
@Javaman2 I don't see how inaccurately mimicking one tiny part of the syntax of TypeScript is going to help with any of that.

**Comment by CyrusNajmabadi** [comment]
>is to shut out the concept of open source.

This is an open source project.  If you'd like to make these changes, you are welcome to fork it and do just that.  Nothing about open source though says that the project maintainers will make the cahnges you in particular want.

**Comment by HaloFour** [comment]
Not that this is relevant at all to any decisions around language design, but per the [tiobe index](https://www.tiobe.com/tiobe-index/) neither JavaScript nor TypeScript are making ground on C#.  The languages are used for very different projects.

C# is not a popularity contest.  Syntax isn't going to be added just because some other language has that syntax, especially if that syntax duplicates an existing feature with zero added benefits.
