### ISSUE TITLE
Allow multiple "=" signs in initialization statement to allow us align expressions

### ISSUE THREAD

**Issue by Denis535** [dotnet/csharplang#3440]
I mean next:

> 
> var sqrt_2 ===== Math.Sqrt( 2 );
> var sqrt_100500 = Math.Sqrt( 100500 );
>

**Comment by theunrepentantgeek** [comment]
There are IDE tools that will do this automatically for you (using spaces or tabs), though even those are limited because of a non-trivial minority of developers who [choose to use proportional fonts for code](http://www.nichesoftware.co.nz/2016/01/24/why-monospaced-fonts.html).

Butchering the language in this way would make it significantly harder to read.

It's also worth noting that this would be a breaking change, given that `==` already has well established (as in 50+ _years_ ) semantics as _equality_ not _assignment_ in C family languages. One of the strengths of C# is the excellent error reporting, which would be impaired by this change.

**Comment by Denis535** [comment]
Usually formatting removes extra spaces.
I understand that I can change the spacing settings, but I would prefer not to rely on the settings.

**Comment by ViIvanov** [comment]
ReSharper and Rider has an options for code like this: [Aligning code in columns with ReSharper and Rider](https://blog.jetbrains.com/dotnet/2017/11/28/aligning-code-columns-resharper-rider/).

**Comment by HaloFour** [comment]
`=` and `==` mean two very different things, so clearly this already doesn't work.

Use spaces for formatting.  That's what trivial whitespace is for.

**Comment by Enderlook** [comment]
> Usually formatting removes extra spaces.
> I understand that I can change the spacing settings, but I would prefer not to rely on the settings.

So, you want to add a whole new feature to the compiler (interpret several `=` symbols as an assignment instead of equality check when using as a statement) just because you don't want to rely on a setting?... Do you think that develop that feature is worth more than a setting?

**Comment by Denis535** [comment]
> Do you think that develop that feature is worth more than a setting?

Let the developers decide it.
I did not find such issue and decided to open this. Why not?

**Comment by theunrepentantgeek** [comment]
Compiler features are extraordinarily expensive - because their development involves not only careful design considerations for now, but ongoing maintenance and testing of that feature for the rest of the lifetime of the language. Every existing feature interacts with every future feature, so the bar for adding new features is quite high - they have to demonstrate considerable value.

This is why [every feature starts at -100 points](https://docs.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points).

@Denis535 you asked
> Why not?

A better question is _Why?_ 

Language development isn't about adding every possible feature to the language. It's about carefully  selecting the right additional features to increase the power and expressiveness of the language in ways that help developers.

**Comment by 333fred** [comment]
We cannot do this: `==` means something today, and we cannot break that. If you would like a formatting option to align variable assignments in the IDE, that seems reasonable to me, and is best requests at dotnet/roslyn.
