### ISSUE TITLE
[Proposal] cleaning up the issues in this repo

### ISSUE THREAD

**Issue by dersia** [dotnet/csharplang#3509]
There are many many issues in this repo and it is getting harder every day to keep overview of what is still relevant and interesting and considerable and what not.

Please either create a label "unlikely", "ready for clean up" or so and promote some of the contributers/community members to be able to add these labels, or get at least a few ppl to clean this repo a little bit. 

That being said I will probably still look into every new issue and some day I will have (hopefully) seen all 2008 issues 😅

**Comment by quinmars** [comment]
Related: #459 and #1317

**Comment by dersia** [comment]
> Related: #459 and #1317

Thanks for making mine (our) point

**Comment by 333fred** [comment]
Generally speaking, we only close issues that we can't ever, for any reason, ever possibly want to implement in C#. Otherwise, it's a suggestion, and we'll keep it around just in case it either becomes relevant or sparks some other ideas. Myself and a few others do close issues when it's pointed out that they're duplicates of existing issues, but while I can keep up with new issues I haven't had time to go through the backlog to close out older duplicates.

That being said: closing as a duplicate :wink:

**Comment by dersia** [comment]
I would have closed this one tomorrow anyway, I just wanted it to stay at least 24h 😅

Thanks for the reply, really appreciated it.
