### ISSUE TITLE
Easier boolean handling?

### ISSUE THREAD

**Issue by BichSuckCock** [dotnet/csharplang#3585]
When using bools and setting them true/false, it is unnecessarily slightly more complicated than with for eg. integers and bytes. Would it be possible to allow bools to be changed using `++` to set bool `true` and `--` to set bool `false`. It would also be practical to set bool true by using only the bools name (for example: `boolean;` or `value;`).

Example 1:
bool value = false;
Console.WriteLine(value); //returns false
value++; //now the value is true
Console.WriteLine(value); //returns true
value--; //now the value is false
Console.WriteLine(value); //returns false

Example 2:
bool value = false;
Console.WriteLine(value); //returns false
value; //now the value is true
Console.WriteLine(value); //returns true

**Comment by CyrusNajmabadi** [comment]
Dear user.  I've closed this issue because your user name is in violation of our code of conduct: https://dotnetfoundation.org/about/code-of-conduct

Especially the sections on:

> Examples of unacceptable behavior include:
> - The use of sexualized language or imagery, and sexual attention or advances of any kind 
> - Other conduct which could reasonably be considered inappropriate in a professional setting 

You are welcome to use a new account that can appropriate follow thees rules to open up new issues.  Thanks very much.
