### ISSUE TITLE
Proposal: Warn if NRT attribute is misused

### ISSUE THREAD

**Issue by betty-crokker** [dotnet/csharplang#3595]
If I write this code:

```
public class MyClass<T>
{
    [MaybeNull]           // no compiler warning
    public T Value;
    MyClass() { Value = default; }   // compiler warning
}

```
the compiler warns of a "possible null reference assignment" where a better warning would be "MaybeNull doesn't make sense where you wrote it"

**Comment by HaloFour** [comment]
Sounds like a good use case for an analyzer.

**Comment by 333fred** [comment]
If you update your compiler, you'll find that there are no warnings at all, because this attribute is not redundant.
https://sharplab.io/#v2:D4AQDABCCMB0AiBLAhgcwHYHsDOAXRAxtrAMKYAmApgILrIA2AntotgNwCwAUNyAMwACkACYBAWUYl6ybNgA8AFQB83AN7cBmgQG0xyRgCNKAOQCu9egF0tNmwHo7ArAIKYAtgAdE9SgCcBAO7IvuiI6KgaWvwCCgIAagymlJxcNhJSMtgAFACUAqrxiZQCALwCVABmyOa4bAIAvloOLu5ePv5BIWERXPVAA

**Comment by betty-crokker** [comment]
With the latest Visual Studio (16.6.2), the warnings are unchanged.

**Comment by 333fred** [comment]
Hmm, it might have helped if I had enabled nullable in my example. I know there's an open bug here somewhere: the attribute is not redundant. It's saying that if T is substituted with a reference type, it could be null, no matter what the reference type is. That's why we're going to be adding the ability to put a ? on unconstrained type parameters in 9, because that's a thing you want to be able to express.
