### ISSUE TITLE
[Proposal] abstract constraints

### ISSUE THREAD

**Issue by LegoCylon** [dotnet/csharplang#3597]
I'd like to be able to constrain that a generic type parameter is or is not abstract in where clauses.

This came up recently when implementing a "factory" for Unity types. Since Unity doesn't permit you to overload the constructor of anything that derives from MonoBehaviour, the factory wraps a call to a type-specific setup method that injects dependencies based on whatever that type needs. The factory initialization method is constrained on classes deriving from an abstract type. However, this means that theoretically you can pass in the abstract type, too.

Since I think the abstract exclusion syntax is more tricky than abstract requirement, I'll focus on what that might look like:
```void Initialize<T> (T obj) where T : SomeAbstractType, not abstract;```
or
```void Initialize<T> (T obj) where T : SomeAbstractType, !abstract;```
or
```void Initialize<T> (T obj) where T : SomeAbstractType, is not abstract;```
or
```void Initialize<T> (T obj) where T : SomeAbstractType, nonabstract;```

This avoids the caller having to switch on typeof(T) and having to pass in different dependencies for each type.

While I could throw an exception if typeof(T) == typeof(SomeAbstractType), this becomes a runtime error instead of a compile-time error.

**Comment by huoyaoyuan** [comment]
Currently, generic constraints are mostly about enabling you to do more things on the type. For example, struct constraint enables `T?`, class constraint enables assigning `null`, base type/interface constraint enables you to call their members.

Preventing misusage can always be done by analyzers.

**Comment by Joe4evr** [comment]
You're going to hear the same response as #3579 got: Write an analyzer.

I've already been working on a package that includes an analyzer for both cases (since I also have a strong desire for a non-abstract constraint).

**Comment by PathogenDavid** [comment]
You can sort-of get this already with the `new()` constraint since it requires the type to be non-abstract. Your types must all have parameterless constructors, which I assume they do since you're in Unity land working with subtypes of `UnityEngine.Object`. (Types with no explicit constructor have an implicit parameterless one.)

[For example](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQ64GYAEBDAIwGdgw8BjYHRHAQWNIuACE8iBTdAb3Rz+tyESZStQAsOAArswAMwD2YALYBJKAEtg6vABt1ALzxb5UABQBKANzoAvuky4aAYRPkw7YOxVKADjpwgdAwiLGycaDxo/AI48gBuMmDqACbs4lIyCspqmtp6hsZm5rzR/AC8AHzUSACcpgBEOVq6BkbqJjg+mYpK7MkAdPVWtvZoiFjcJXyICFM4kaX8cXhgOJ4kOGU4UOwA7jguUG4eXr46FtZRizhNeQbsADyHx57efhWm68DDV4u3LfpHvRhExWBwPl8rDgAPTQg4AZQADFgkIjAgByYGMShg9jonBKCAbAhpPDbEwAWiE2KowAAnl0cLtNAALfAxHwrPC9TxgHTsIhEHDkEzCCCURQ4dRQWJgVKrYDyHBEtKafBCzlkHkyHDogAq+OlaxZaQA5uwdklyGsGWlJTyWfJkrq4EgAOz9PUC4APPUfPXmdFzOy/HBzbDVABs6X++UeftMetiBAAVsVQ9Fdib3Dgk4EsSFcQAabZ7CxzaKVZMp/rSOQ9WOtQoXWxAA):

```csharp
using System;

public abstract class AbstractBase
{
    public abstract void PerformInitialization();
}

public class ConcreteImpl : AbstractBase
{
    public override void PerformInitialization()
        => Console.WriteLine("Initialization performed.");
}

public static class Program
{
    public static void Main()
    {
        var test = new ConcreteImpl();
        Initialize<ConcreteImpl>(test);
        Initialize<AbstractBase>(test); // CS0310: 'AbstractBase' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'Program.Test<T>(T)'
    }
    
    public static void Initialize<T>(T obj)
        where T : AbstractBase, new()
        => obj.PerformInitialization();
}
```

**Comment by LegoCylon** [comment]
@PathogenDavid I really appreciate the suggestion and can confirm that it does work for Unity types since they all have an implicit parameterless constructor.

If the language maintainers are discouraging an expansion of constraints to ensure correctness, I think that's a shame but I'll close this request.
