### ISSUE TITLE
[suggestion]  Summary Comments for Class Access Modifiers

### ISSUE THREAD

**Issue by attrib75** [dotnet/csharplang#3608]
It would be useful to have summary comments appear when hovering over access modifiers for a class, to remind us what each access modifier is meant for:

public, private, protected, etc.

Example: 

`public class MyClass{}`

Hover over the "public" access modifier --> tooltip shows "The type or member can be accessed by any other code in the same assembly or another assembly that references it."

**Comment by HaloFour** [comment]
This would be a tooling issue and not impact the language itself, could you file over at the [Roslyn repo](https://github.com/dotnet/roslyn/issues)?

**Comment by attrib75** [comment]
Good point.  Sure!

**Comment by CyrusNajmabadi** [comment]
Note: `f1` on these keywords should take you to rich documentation about them.

**Comment by attrib75** [comment]
This is true, and I'm being nit picky here, but that process is disruptive.  Faster and easier to hover.

**Comment by CyrusNajmabadi** [comment]
The problem here is that these topcis are large.  For example, the following is not true:

> Hover over the "public" access modifier --> tooltip shows "The type or member can be accessed by any other code in the same assembly or another assembly that references it."

It's an approximation, but can fall over very quickly.  That's why teh docs are really appropriate here so that you can actually get a real sense of what the modifier means, not just a brief (and innacurate) summary.  Note; in doc form, i think summaries are fine, since they are explained more later.  

So, i'm ok with this proposal, if the quickinfo appears with a link to the docs so people can read teh full description to understand what's really going on.

**Comment by attrib75** [comment]
For sure, a link to the full docs would be intuitive from a user experience.  Not surprisingly I suppose, I didn't think all that deeply on the implications that you address above.  I thought the access modifier definitions were a universal truth in any scenario.  Maybe some indicator in the one liner could hint that the definition may not apply in all cases.

**Comment by 333fred** [comment]
Closing out as https://github.com/dotnet/roslyn/issues/45432 has been filed.
