### ISSUE TITLE
Add operator break break;

### ISSUE THREAD

**Issue by pavlom1351** [dotnet/csharplang#3638]
```
while ( true )
{
    while ( true )
    {
        break break;
    }
}
```

**Comment by juliusfriedman** [comment]
We have goto In C# we don't need labeled switch or break break or otherwise.

**Comment by pavlom1351** [comment]
Goto is bad style

**Comment by mcosmin222** [comment]
```
while ( true )
{
    while ( true )
    {
        break break;
    }
}
```

Is arguably worse than goto. I don't see any reason to ever need 2 nested infinite while loops.

**Comment by LWChris** [comment]
@pavlom1351 

goto is bad style only if it can be written as a more clear statement such as if-then-else, try-catch-finally, or method calls. In rare special cases, goto may be a valid option.

@mcosmin222 I suppose `true` was an abstraction for any actual boolean expression.

That being said, depending on whether or not you have code _behind_ any of your loops, another approach might be

```
var breakAll = false;
while (!breakAll && condition1)
{
    PrepareSomething();
    while (!breakAll && condition2)
    {
        DoSomething();
        if (condition3)
        {
            breakAll = true;
            break;
        }
        DoSomethingElse();
    }
    // There must not be code here
}
```

Or, if there is code, maybe you can oursource the loops to a separate method and use `return` instead of `break`.

**Comment by Joe4evr** [comment]
dotnet/roslyn#5883
#869
#1597
#2024
#3511

**Comment by eyalsk** [comment]
Saying `goto` is a style is hilarious and saying it's bad it's ridiculous, it is a tool like any other and you should use whenever it's appropriate.
