### ISSUE TITLE
Simplify asynchronous programming

### ISSUE THREAD

**Issue by osamakawish** [dotnet/csharplang#3639]
The idea suggested here does seem to go against the [nature of a good proposal](https://github.com/dotnet/csharplang/tree/master/proposals):
> * Not introduce subtly alternate syntax for existing features.

However, I do think this is an important improvement, that would simplify a lot of the confusions beginners have with asynchronous programming.

This is to simplify the following code:

```c#
Task<T> task = Task.Run(() => func(a,b,c,...));
int x = await task;
```
to:
```c#
int x = async func(a,b,c,...);
```
or:
```c#
int x = await func(a,b,c,...);
```

I believe this will significantly simplify confused programmers that are new to asynchronous programming. They can then later learn to await tasks later on, rather than immediately.

**Comment by jnm2** [comment]
Prior discussion on how the C# language should not know about `Task.Run`: https://github.com/dotnet/csharplang/issues/3378#issuecomment-616905919

**Comment by leandromoh** [comment]
just reminding, user can do 
```c#
Func<Task<int>> task = async () => await Task.FromResult(6);
int x = await task();
```

**Comment by Frassle** [comment]
@leandromoh that won't run func in a new thread

**Comment by Joe4evr** [comment]
@Frassle Neither does `Task.Run`, it just adds the overhead of an additional Task allocation.

**Comment by HaloFour** [comment]
> However, I do think this is an important improvement, that would simplify a lot of the confusions beginners have with asynchronous programming.

A common confusion is that asynchronous programming means multithreading, but it doesn't, and to imply that it does only does a disservice to those same beginners.  Threads are expensive and spinning them up is very often the wrong thing to do, I don't think that developers should be encouraged to do that through language features, especially given that the savings can be measured in maybe a dozen or so keystrokes.

**Comment by osamakawish** [comment]
> > However, I do think this is an important improvement, that would simplify a lot of the confusions beginners have with asynchronous programming.
> 
> A common confusion is that asynchronous programming means multithreading, but it doesn't, and to imply that it does only does a disservice to those same beginners. Threads are expensive and spinning them up is very often the wrong thing to do, I don't think that developers should be encouraged to do that through language features, especially given that the savings can be measured in maybe a dozen or so keystrokes.

I raised a bit of a question regarding this over on [StackOverflow here](https://stackoverflow.com/questions/62728858/differences-between-multithreading-and-async). 

But as a a quick summary, this simply doesn't make sense. 

When async code does two things "asynchronously", it generally completes them in a similar amount of time as if the tasks were multithreaded. 

However, correct me if I'm wrong here, but I believe a single thread works on a single task at any given moment. 

As such, the total amount of time for two async tasks that would take 5s to complete synchronously should also take 5s to complete asynchronously (assuming no other tasks are present), since the thread can only work on one task at a given time. 

But the timing in any async function that runs two tasks asynchronously is often similar to the timing of a multithreaded task. 

So the idea that asynchronous programming doesn't rely on any additional threads simply doesn't make any sense.

**Comment by sharwell** [comment]
> However, correct me if I'm wrong here, but I believe a single thread works on a single task at any given moment.

This is not correct. Asynchronous programming typically relates to the ability to write _non-blocking_ code, as opposed to the ability execute code concurrently. Many types of asynchronous operations, ranging from I/O to delays, do not require a thread at all. As an obvious example, JavaScript execution is heavily asynchronous, but only uses one thread.

**Comment by osamakawish** [comment]
@sharwell I may be misunderstanding "non-blocking" here. 

But can you look back at my comment and the image I posted, and clarify what I've misunderstood? The async portion is "non-blocking" in that image, or maybe I'm misunderstanding something. But it still takes the same amount of time as the synchronous code, in spite of how it seems non-blocking to me.

**Comment by HaloFour** [comment]
@osamakawish 

That graphic is wrong.  Non-blocking I/O can continue in the background either on a separate pool of threads or via some other mechanism entirely while the current thread is working on something else.  You only need separate threads when you need to do CPU work simultaneously.  Most async work is I/O, and most I/O can be done in a non-blocking manner without wasting an additional 1 MB of stack space plus the costs of context switching on a thread.

**Comment by osamakawish** [comment]
@HaloFour That clarifies things a little more, though I'm still a bit confused.

So it uses separate existing threads? Isn't that more or less still "multithreading", but simply using existing threads rather than new ones?

Or is multithreading defined by using new threads rather than existing ones?

**Comment by HaloFour** [comment]
@osamakawish 

> So it uses separate existing threads? Isn't that more or less still "multithreading", but simply using existing threads rather than new ones?

It depends, different operating systems and frameworks offer different mechanisms and they're often somewhat abstracted away.  Often it involves a queue or channel to which a notification can be posted when a non-blocking operation has completed.  A small preallocated thread pool could be dedicated to block or poll on notifications to that queue.  In this way you can have a small number of threads managing a significantly larger number of simultaneous I/O operations.

**Comment by theunrepentantgeek** [comment]
I remembered an interesting post from [Stephen Cleary](https://stephencleary.com/) that clarifies this: [There is No Thread](https://blog.stephencleary.com/2013/11/there-is-no-thread.html).

The blog post is written from a Windows perspective (it was written in 2013, so at the time .NET == Windows), but things haven't changed that much.

**Comment by osamakawish** [comment]
This was overall, a pretty good discussion, and I learned quite a bit about the theory behind async. 

@theunrepentantgeek Too many buzzwords for me in that article, so it's a little confusing for my tastes.

Given the `Task.Run` criticisms above, I suppose I'll close this thread here.

**Comment by jmarolf** [comment]
`async` (from the C# languages perspective) does not mean "multi-threaded" it just means that the current thread is "not blocked" i.e. free to do other work. The way the language abstracts over this is with the concept of an "awaiter pattern". `Task`, `ValueTask`, and Window's `IAsyncOperation` are all types that implement the awaiter patterm (and can therefore be awaited).

the pattern for awaitable is essentially same as `yield return`. In `yield return` you exit the method when you `yield` and a compiler-generated state machine tracks where you were last time so when you call back in you continue from where the last `yield` statement was.

You can look at what the compiler generates for both cases:
- [await](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobABgAJt8BWAbhJOwGYrcKBhCgbxIv6qtsADioA2CgFkAFAEoefAUuwBOcQDoAInAA2EAJ7SyshsSUBfEuaA=)
- [yield return](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobABgAJt8AWAbhPKvwFYHjGBmK3CgYQoBvEhVFVu1TgB4AlgDsYAPgoBZABQBKISLG7q+KgHYKZdroC+Jc0A=)

Await is more complex in some ways as it has needs to pack up and restore more state, but the two features work very similarly (they even shared implementation details in the compiler for a while).

The point of all this is: how a type implements the awaiter pattern is completely unknown to the C# language. _Some_ awaiter types will use threads behind the scenes in order to satisfy the awaiter pattern, but as @HaloFour points out there are many situations where no threads need to be used. For reading a stream from the network the network-interface-controller (NIC) is tasked by the operating system to co-ordinate 
1. opening the connection
2. moving the bytes it receives into a location in system memory the OS told it to
3. notifying the OS that the work is done

The network card is the "thread" where all the work happens in this case. Except its a dedicated piece of hardware not the CPU. The OS may allocate internal threads to help co-ordinate this work, but no program threads will be involved. Almost all modern operating systems will use [hardware interrupts](https://en.wikipedia.org/wiki/Interrupt#Hardware_interrupts) to receive notifications about when this async work is done and pass it along without using additional threads at all. 

However even if is all true `Task` has traditionally represented work that would be done on a thread at some point. It signified the "promise" that the work would complete. `Task` being used in multi-threaded applications before `async` was introduced presented some problems. We didn't want to introduce a new type that was effectively the same thing but we also knew that `Task` now represented a lot of additional concepts which would be confusing.
