### ISSUE TITLE
"Hidden" Variables

### ISSUE THREAD

**Issue by osamakawish** [dotnet/csharplang#3675]
This idea generally came across my mind first when I learned about password encryption and felt that probably should be an easier way around it all.

But basically, I wondered about whether or not it's possible to implement "hidden" variables.

The general way these variables works is:

1. Hidden variables cannot be printed by a Stream (ie. such as by Console.WriteLine or Debug.WriteLine type methods).
2. Hidden variables can only "interact with" other hidden variables.

Because it can't be written by a stream, it's impossible to read it. And because it can only "interact with" other hidden variables, you cannot just take the value indirectly either to retrieve it.

What I mean by "interact with" is actually a little vague at the moment tbh. But at the very least, you cannot copy, assign, or given the new C++ semantics (for those with C++ background), "move" a hidden variable to a variable that is not hidden. Generally speaking, I want to avoid being able to indirectly get the content of the "hidden" variables. Like the following shouldn't be possible, as it defeats the purpose:

```c#
hidden string password;
string s = password;
Console.WriteLine(s);
```

Basically, when you input a password into a form, the form text input should be a "hidden" variable (and as a result, you cannot rewrite the inputted keyboard letters into the form, to show a preview of what's been typed - which is an admitted downside of this). 

Of course, going to the details of it all would require a database as a whole to be "hidden", but I feel like hidden variables would be a neat way to work around the need for encryption entirely.

I know only the basics of hacking and encryption, so this could very well be a completely ridiculous idea. 

Other downsides of this is that essentially anything could be hidden. Which could lead to whole separate world of issues. Though maybe we can restrict this somehow. 

I guess this is sort of more of discussion topic for now than anything else. Feel free to let me know your thoughts on this.

PS. I think this is a little different than private variables in that it guarantees the variables will never be read.

**Comment by yaakov-h** [comment]
`SecureString` kinda tried something similar but that didn't quite pan out in the end, and I don't see how this would overcome any of the issues encountered by it or its lack of adoption.

If I can do:
```csharp
hidden string password = "...";
var notHidden = password.AsSpan();
```

then its game over at a language level regardless. The same goes for `Clone`, `Substring`, the indexer, potentially `Length`...

Yet you would still need a way to "unhide" a variable so that I can pass it to an older API that doesn't support "hidden" variables, or even a new one that is oblivious to the concept. Once you have that, if you don't even have in-memory encryption like `SecureString` used to, I don't see any point to this whatsoever.

Probably the best compromise I can think of is an attribute plus analyzer, so if you mark a field, parameter, or method return value with `[HiddenVariable]` (or some other name) then you get a diagnostic error or warning if you pass it to any other API that isn't also marked with that attribute. And fortunately, exploring that option does not require any changes to the language.

**Comment by theunrepentantgeek** [comment]
I've used _semantic types_ as a solution for this kind of thing in the past - wrapping the sensitive value in a dedicated wrapper type (often a **struct**) that forces consumers to think about what they are doing when they unwrap the value.

You do have to think about compatibility issues with other APIs - but the value of having a sensitive value wrapped up so that you _simply cannot_ pass it as a string is extraordinary.

**Comment by osamakawish** [comment]
@theunrepentantgeek Yeah, I guess it's generally better to ensure that only comparison and equality operators are involved. I think to a large part, I guess I wasn't thinking too differently from those semantic types.

Always end up learning a lot when my ideas go wrong lol...
