### ISSUE TITLE
null operator

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/csharplang#3692]
```c#
public static operator null(MyType) => SomeNoneNulLValue;
```

So dealing with null becomes easy and a first class explicit thing, when you handle null you should never have a null reference exception.

## Examples

```c#
public class MyClass {
static readonly MyClass Null = new MyClass();
public static operator null(MyClass myClass) => Null
}
```

```c#
public struct MyStruct {
static readonly MyStruct Null = default;
public static operator null(MyClass myClass) => Null
}
```

```c#
public ref struct RefMyStruct 
{
    const RefMyStruct Null = nullptr;
    
    public static operator null(RefMyStruct myRefStruct) => Null
    
    //CS8156
    ref RefMyStruct GetNull(){
        return ref Null;
    }
}
```

## Alternative syntax
Thanks @Flutterish for the suggestion!
`default operator`
```c#
public class MyClass {
static readonly MyClass Null = new MyClass();
public static operator default(MyClass myClass) => Null
}
```

Could also have both `default` and `null` operators because in C# we do like to be as specific as possible...

This also makes implementing reference counting easy without a finalzier when combined with something like https://github.com/dotnet/csharplang/issues/3687

**Comment by yaakov-h** [comment]
This seems quite antithetical to recent changes such as NRT, `??`, `?.` and `??=`.

**Comment by juliusfriedman** [comment]
But I believe it's purer and works with all types not just reference types.

**Comment by yaakov-h** [comment]
How is "silently convert not-a-value to a value" in any way, shape, or form, "pure"?

**Comment by juliusfriedman** [comment]
I misunderstand you please rephrase so I can understand.

**Comment by yaakov-h** [comment]
Your proposals are very lacking in detail, but you appear to be trying to define an operator that replaces nulls with values.

That is literally converting to something (a value) from nothing (null).

**Comment by juliusfriedman** [comment]
how is `nullptr` a different `value`? how it is different from `null` other than the semantics we give it?

It's better than `null` when `null` would convert to an actual type which was initialized don't you agree?

**Comment by canton7** [comment]
When would `operator null` for a struct be invoked? You can't do `MyStruct s = null`.

Are you referring to `MyString? s = null`? But then `s.HasValue` would be inexplicably `true`, which I think would confuse a great many people.

**Comment by huoyaoyuan** [comment]
> So dealing with null becomes easy and a first class explicit thing

This **never helps** dealing with null, **and will make things worse**.

When using newly created types, you can always use `SomeClass c = SomeClass.Null`. It's just a few more characters, and you won't type too much more (typically `S` `C` `.` `N` is enough).

`null` is a very special thing. It's all zero. It's the result of "cleaning the memory". Without `null`, many operations will be horrible. You can never avoid dealing it totally, but just limit the scenes it can occur.

Moreover, most types can't provide a meaningful default value. **If there's something taking the `default` semantics, there will be more code dealing with the invalid default value.** This is what *non-defaultable struct* is facing with. **Instead of checking `null`, you will be always checking the invalid instance. Calling methods on it won't throw NRE, but will throw otherwise because the invalid default instance can't provide any valid action.**

**Comment by canton7** [comment]
That's a good point. What's the value of `result` in each of these:

```cs
MyClass result = default;
```

```cs
MyClass[] arr = new MyClass[1];

MyClass result = arr[0];
```

```cs
public T M<T>() => default(T);

MyClass result = M<MyClass>();
```

```cs
public MyClass M(MyClass foo = default) => foo;

MyClass result = M();
```

```cs
public class C
{
    public MyClass Foo;
}

MyClass result = new C().Foo;
```

```cs
public struct S
{
    public MyClass Foo;
}

MyClass result = default(S).Foo; // or new S().Foo
```

**Comment by juliusfriedman** [comment]
> When would `operator null` for a struct be invoked? You can't do `MyStruct s = null`.
> 
> Are you referring to `MyString? s = null`? But then `s.HasValue` would be inexplicably `true`, which I think would confuse a great many people.

on the return from an invalid in parameter the caller can always instantiate correctly and call again.

**Comment by juliusfriedman** [comment]
> That's a good point. What's the value of `result` in each of these:
> 
> ```cs
> MyClass result = default;
> ```
> 
`null`
> ```cs
> MyClass[] arr = new MyClass[1];
> 
> MyClass result = arr[0];
> ```

`IndexOutOfBounds`
> 
> ```cs
> public T M<T>() => default(T);
> 
> MyClass result = M<MyClass>();
> ```
> 
`null`
> ```cs
> public MyClass M(MyClass foo = default) => foo;
> 
> MyClass result = M();
> ```
> 
`null `
> ```cs
> public MyClass M<T>() where T : new() => new T();
> 
> MyClass result = M<MyClass>();
> ```
`new MyClass`
> 
> ```cs
> public void M<T>()
> {
>    T result = default; // or new T()
> }
> 
> M<MyClass>();
> ```

`Depends on type` T

> 
> ```cs
> public class C
> {
>     public MyClass Foo;
> }
> 
> MyClass result = new C().Foo;
> ```
`NRE`
> 
> ```cs
> public struct S
> {
>     public MyClass Foo;
> }
> 
> MyClass result = default(S).Foo; // or new S().Foo
> ```

`Works`
> 
> ```cs
> object obj = 3;
> 
> MyClass result = obj as MyClass;
> ```
> 
`null`
> ```cs
> object obj = null;
> 
> MyClass result = (MyClass)obj;
> ```
`null`

**Comment by canton7** [comment]
So essentially your proposal doesn't affect any of my examples?

What *are* you proposing, then?

**Comment by juliusfriedman** [comment]
> So essentially your proposal doesn't affect any of my examples?
> 
> What _are_ you proposing, then?

Dear sir, did you override / implement the `null` operator on any of your examples? If so I missed where, if not how would you expect to observe a difference?

**Comment by yaakov-h** [comment]
None of those examples even _defined_ the class `MyClass`. They all rely upon your definition in your original post, which quite clearly implements the proposed/fictional `null` operator.

**Comment by juliusfriedman** [comment]
I did not observe that, I took your example verbatim I apologize I will add the expected behavior with my operators below shortly, forgive my nearsightedness.

**Comment by juliusfriedman** [comment]
> That's a good point. What's the value of `result` in each of these:
> 
> ```cs
> MyClass result = default;
> ```
> 
MyClass.Null, as given by operator.

> ```cs
> MyClass[] arr = new MyClass[1];
> 
> MyClass result = arr[0];
> ```


MyClass.Null, as given by operator.

> 
> ```cs
> public T M<T>() => default(T);
> 
> MyClass result = M<MyClass>();
> ```
> 
MyClass.Null, as given by operator.
> ```cs
> public MyClass M(MyClass foo = default) => foo;
> 
> MyClass result = M();
> ```
> 
MyClass.Null, as given by operator.
> ```cs
> public MyClass M<T>() where T : new() => new T();
> 
> MyClass result = M<MyClass>();
> ```
`new MyClass`
> 
> ```cs
> public void M<T>()
> {
>    T result = default; // or new T()
> }
> 
> M<MyClass>();
> ```

MyClass.Null, as given by operator.

> 
> ```cs
> public class C
> {
>     public MyClass Foo;
> }
> 
> MyClass result = new C().Foo;
> ```
`NRE` not thrown result = MyClass.Null, as given by operator.
> 
> ```cs
> public struct S
> {
>     public MyClass Foo;
> }
> 
> MyClass result = default(S).Foo; // or new S().Foo
> ```

MyClass.Null, as given by operator.
> 
> ```cs
> object obj = 3;
> 
> MyClass result = obj as MyClass;
> ```
> 
MyClass.Null, as given by operator.
> ```cs
> object obj = null;
> 
> MyClass result = (MyClass)obj;
> ```
MyClass.Null, as given by operator.

**Comment by juliusfriedman** [comment]
> > So dealing with null becomes easy and a first class explicit thing
> 
> This **never helps** dealing with null, **and will make things worse**.
> 
> When using newly created types, you can always use `SomeClass c = SomeClass.Null`. It's just a few more characters, and you won't type too much more (typically `S` `C` `.` `N` is enough).
> 
> `null` is a very special thing. It's all zero. It's the result of "cleaning the memory". Without `null`, many operations will be horrible. You can never avoid dealing it totally, but just limit the scenes it can occur.
> 
> Moreover, most types can't provide a meaningful default value. **If there's something taking the `default` semantics, there will be more code dealing with the invalid default value.** This is what _non-defaultable struct_ is facing with. **Instead of checking `null`, you will be always checking the invalid instance. Calling methods on it won't throw NRE, but will throw otherwise because the invalid default instance can't provide any valid action.**

I don't always have to return the same value do i? isn't that up to the impl?

**Comment by canton7** [comment]
@juliusfriedman Thanks, this is looking something that would be very complicated to implement. There are some problems in there (some of them are simply impossible), but I'll come to those shortly.

I'm deliberately ignoring `MyStruct`, because structs can't be null, so the operator doesn't make any sense with structs.

Let's try some more, if you don't mind. What's the value of `result` in each of these?

```cs
MyClass[] arr = new MyClass[1];
object[] objectArr = arr;

bool result = objectArr[0] is null;
```

```cs
public void M<T>()
{
    T foo = default;
    bool result = foo is null;
}

M<MyClass>();
```

```cs
// For this one, we need our MyClass to have a base class
public class MyClassBase { }
public class MyClass : MyClassBase
{
    static readonly MyClass Null = new MyClass();
    public static operator null(MyClass myClass) => Null;
}

public interface IS
{
    MyClassBase M { get; }
}

public struct S : IS
{
    private readonly MyClass foo;
    public MyClassBase M => foo;
}

bool result = default(S).M is null;
```

**Comment by juliusfriedman** [comment]
> @juliusfriedman Thanks, this is looking something that would be very complicated to implement. There are some problems in there (some of them are simply impossible), but I'll come to those shortly.
> 
> I'm deliberately ignoring `MyStruct`, because structs can't be null, so the operator doesn't make any sense with structs.
> 
> Let's try some more, if you don't mind. What's the value of `result` in each of these?
> 
> ```cs
> MyClass[] arr = new MyClass[1];
> object[] objectArr = arr;
> 
> bool result = objectArr[0] is null;
> ```
> 
> ```cs
> public void M<T>()
> {
>     T foo = default;
>     bool result = foo is null;
> }
> 
> M<MyClass>();
> ```
> 
> ```cs
> // For this one, we need our MyClass to have a base class
> public class MyClassBase { }
> public class MyClass : MyClassBase
> {
>     static readonly MyClass Null = new MyClass();
>     public static operator null(MyClass myClass) => Null;
> }
> 
> public interface IS
> {
>     MyClassBase M { get; }
> }
> 
> public struct S : IS
> {
>     private readonly MyClass foo;
>     public MyClassBase M => foo;
> }
> 
> bool result = default(S).M is null;
> ```

I dont think so and I dont follow your example to the slightest.

Its just like the proposed ref operator.. and structs have ref which can point to null

**Comment by canton7** [comment]
What's the value of `result` in each of my examples above, true or false?

C# (the language) does not allow ref variables to point to null.

**Comment by juliusfriedman** [comment]
> What's the value of `result` in each of my examples above, true or false?
> 
> C# (the language) does not allow ref variables to point to null.

That means nothing when the code is verifiable in CIL

**Comment by juliusfriedman** [comment]
``cs
MyClass[] arr = new MyClass[1];
object[] objectArr = arr;
 
bool result = objectArr[0] is null;
```
 
 
```cs
 public void M<T>()
{
    T foo = default;
     bool result = foo is null;
 }
 
 M<MyClass>();
 ```
 
 
 ```cs
 // For this one, we need our MyClass to have a base class
 public class MyClassBase { }
 public class MyClass : MyClassBase
 {
    static readonly MyClass Null = new MyClass();
     public static operator null(MyClass myClass) => Null;
 }
 
 public interface IS
 {
     MyClassBase M { get; }
 }
 
 public struct S : IS
 {
    private readonly MyClass foo;
     public MyClassBase M => foo;
 }
 
 bool result = default(S).M is null;
 ```

**Comment by Flutterish** [comment]
```cs
if ( 3 is MyClass nonNull ) {
    // nonNull == MyClass.Null
} else {
    // 3 is not MyClass
}
```
How does this make sense given that `3 as MyClass == MyClass.Null`?
`3` is clearly not `MyClass`.

**Comment by juliusfriedman** [comment]
> ```cs
> if ( 3 is MyClass nonNull ) {
>     // nonNull == MyClass.Null
> } else {
>     // 3 is not MyClass
> }
> ```
> 
> How does this make sense given that `3 as MyClass == MyClass.Null`?
> `3` is clearly not `MyClass`.

1) Search this page for that text, you will find your the only person with that syntax here 
2) How does this not make sense:
```c#
if ( 3 is MyClass nonNull and nonNull == MyClass.Null) {
    // nonNull == MyClass.Null
} else {
    // 3 is not MyClass.Null
}
```

**Comment by Flutterish** [comment]
You forgot the part where "[...] given that `3 as MyClass == MyClass.Null`? `3` is clearly not `MyClass`."

**Comment by Flutterish** [comment]
`3 is MyClass == false`. `3 as MyClass == MyClass.Null`. Therefore `3 as MyClass is MyClass == true` so `3 is MyClass == true`. `false == true`. Clearly contradicts itself.

**Comment by Flutterish** [comment]
I understand what you are saying but it only makes sense as a `default value`, not as a `null operator`. `null` has to exist.

**Comment by canton7** [comment]
> > ```cs
> > MyClass[] arr = new MyClass[1];
> > 
> > MyClass result = arr[0];
> > ```
> 
> MyClass.Null, as given by operator.

This one's a bit tricky: arrays in C# are just zero'd, there's no mechanism for going through and setting each element to the result of the null operator. However, you *could* do this if you added a test when *retrieving* an array element, i.e.:

```cs
MyClass[] arr = new MyClass[1];
MyClass tmp = arr[0];
if (tmp == null)
    tmp = MyClass.op_null()
MyClass result = tmp;
```

However, this means that accessing `arr[0]` twice will call the null operator twice. If the null operator doesn't happen to return a singleton instance, then `ReferenceEquals(arr[0], arr[0])` will be `false`, which is very weird.

This does however mean `result` can never be true here:

```cs
MyClass[] arr = new MyClass[1];
object[] objectArr = arr;
 
bool result = objectArr[0] is null;
```

The compiler doesn't know that it should insert this special check when accessing `objectArr[0]`, since the array is of type `object`. So `objectArr[0]` *must* be `null` and not `MyClass.Null`. That's very unintuitive to me.

---------------------

> > ```cs
> > public T M<T>() => default(T);
> > 
> > MyClass result = M<MyClass>();
> > ```
> 
> MyClass.Null, as given by operator.

In a generic method, the compiler doesn't know that the null operator exists, since it doesn't know at compile-time that `T` could be `MyClass` (this is the same reason why other user-defined operators/conversions don't work with generics). Therefore:

```cs
public T M<T>()
{
    T ret = default(T); // Must be null
    return ret;
}

MyClass result = M<MyClass>();
```

`ret` has to be `null` -- there's no way for the compiler to insert a call to the null operator. Therefore, in order for `result` to be `MyClass.Null`, the compiler would have to insert a check whenever an instance of `MyClass` is returned from a generic method, like:

```cs
MyClass tmp = M<MyClass>();
if (tmp == null)
    tmp = MyClass.op_null();
MyClass result = tmp;
```

However, this does mean that:

>> ```cs
>> public void M<T>()
>> {
>>      T foo = default;
>>      bool result = foo is null;
>>  }
>>  
>>  M<MyClass>();
>> ```
> 
> by reference right? true otherwise false

`result` has to be `true` here, for the same reason I gave above. There's simply no way for the compile to know to invoke `MyClass.op_null` on a generic type.

----------------------

> 
> > ```cs
> > public MyClass M(MyClass foo = default) => foo;
> > 
> > MyClass result = M();
> > ```
> 
> MyClass.Null, as given by operator.

Default parameter values have to be consts. Therefore the compiler would have to do something like:

```cs
public MyClass M(MyClass foo = default)
{
    if (foo == null)
        foo = MyClass.Null;
    return foo;
}
```

This means that if you did explicitly pass `null`, i.e. `M(null)`, that would silently get converted to `MyClass.Null`.

-----------------------------

> > ```cs
> > public void M<T>()
> > {
> >    T result = default;
> > }
> > 
> > M<MyClass>();
> > ```
> 
> MyClass.Null, as given by operator.

This is similar to earlier: it's simply impossible, because the doesn't know that it should call `MyClass.op_null` for a generic type. `result` *has* to be `null`.

-------------------------

> > ```cs
> > public class C
> > {
> >     public MyClass Foo;
> > }
> > 
> > MyClass result = new C().Foo;
> > ```
> 
> `NRE` not thrown result = MyClass.Null, as given by operator.

So the compiler would have to insert an initializer:

```cs
public class C
{
    public MyClass Foo = MyClass.op_null();
}
```

----------------------
 
> > ```cs
> > public struct S
> > {
> >     public MyClass Foo;
> > }
> > 
> > MyClass result = default(S).Foo; // or new S().Foo
> > ```
> 
> MyClass.Null, as given by operator.

However, the compiler *can't* insert an initializer for `Foo` here, because the struct is zero-initialized. So if you do `default(S)`, its `Foo` field *has* to be `null`, no ifs, no buts.

The only way this could work is if the compiler inserted a null-check every time it accessed a field of type `MyClass`:

```cs
MyClass tmp = default(S).Foo;
if (tmp == null)
    tmp = MyClass.op_null();
MyClass result = tmp;
```

As with arrrays, if the null operator didn't return a singleton instance, accessing a field twice might yield two different instances, so `S s = default(S); ReferenceEquals(s.Foo, s.Foo)` could be `false`, which is really messed up.

----------------------

> > ```cs
> > object obj = 3;
> > 
> > MyClass result = obj as MyClass;
> > ```
> 
> MyClass.Null, as given by operator.

@Flutterish has done a good job of picking this one up.

-----------

> > ```cs
> > object obj = null;
> > 
> > MyClass result = (MyClass)obj;
> > ```
> 
> MyClass.Null, as given by operator.

So all cast operations would have to insert a null-check. As before, `ReferenceEquals((MyClass)null, (MyClass)null)` could be false, which is broken.

**Comment by juliusfriedman** [comment]
> > > ```cs
> > > MyClass[] arr = new MyClass[1];
> > > 
> > > MyClass result = arr[0];
> > > ```
> > 
> > 
> > MyClass.Null, as given by operator.
> 
> This one's a bit tricky: arrays in C# are just zero'd, there's no mechanism for going through and setting each element to the result of the null operator. However, you _could_ do this if you added a test when _retrieving_ an array element, i.e.:

Yes there is, its called `SkipLocaslInit`
> 
> ```cs
> MyClass[] arr = new MyClass[1];
> MyClass tmp = arr[0];
> if (tmp == null)
>     tmp = MyClass.op_null()
> MyClass result = tmp;
> ```
> 
> However, this means that accessing `arr[0]` twice will call the null operator twice. If the null operator doesn't happen to return a singleton instance, then `ReferenceEquals(arr[0], arr[0])` will be `false`, which is very weird.

for 1) It's up to the impl to decide.
for 2) no it will not as the location of arr[0] didn't change only the reference to it did and this is not a by reference operator.
> 
> This does however mean `result` can never be true here:
> 
> ```cs
> MyClass[] arr = new MyClass[1];
> object[] objectArr = arr;
>  
> bool result = objectArr[0] is null;

If by reference it certainly can be, by reference doesn't invoke the null operator, you need `null` explicitly somewhere for the operator to work on.

> ```
> 
> The compiler doesn't know that it should insert this special check when accessing `objectArr[0]`, since the array is of type `object`. So `objectArr[0]` _must_ be `null` and not `MyClass.Null`. That's very unintuitive to me.
> 
> > > ```cs
> > > public T M<T>() => default(T);
> > > 
> > > MyClass result = M<MyClass>();
> > > ```
> > 

Don't overload the operator then.

Lost at about here....

> > 
> > MyClass.Null, as given by operator.
> 
> In a generic method, the compiler doesn't know that the null operator exists, since it doesn't know at compile-time that `T` could be `MyClass` (this is the same reason why other user-defined operators/conversions don't work with generics). Therefore:
> 
> ```cs
> public T M<T>()
> {
>     T ret = default(T); // Must be null
>     return ret;
> }
> 
> MyClass result = M<MyClass>();
> ```
> 
> `ret` has to be `null` -- there's no way for the compiler to insert a call to the null operator. Therefore, in order for `result` to be `MyClass.Null`, the compiler would have to insert a check whenever an instance of `MyClass` is returned from a generic method, like:
> 
> ```cs
> MyClass tmp = M<MyClass>();
> if (tmp == null)
>     tmp = MyClass.op_null();
> MyClass result = tmp;
> ```
> 
> However, this does mean that:
> 
> > > ```cs
> > > public void M<T>()
> > > {
> > >      T foo = default;
> > >      bool result = foo is null;
> > >  }
> > >  
> > >  M<MyClass>();
> > > ```
> > 
> > 
> > by reference right? true otherwise false
> 
> `result` has to be `true` here, for the same reason I gave above. There's simply no way for the compile to know to invoke `MyClass.op_null` on a generic type.
> 
> > > ```cs
> > > public MyClass M(MyClass foo = default) => foo;
> > > 
> > > MyClass result = M();
> > > ```
> > 
> > 
> > MyClass.Null, as given by operator.
> 
> Default parameter values have to be consts. Therefore the compiler would have to do something like:
> 
> ```cs
> public MyClass M(MyClass foo = default)
> {
>     if (foo == null)
>         foo = MyClass.Null;
>     return foo;
> }
> ```
> 
> This means that if you did explicitly pass `null`, i.e. `M(null)`, that would silently get converted to `MyClass.Null`.
> 
> > > ```cs
> > > public void M<T>()
> > > {
> > >    T result = default;
> > > }
> > > 
> > > M<MyClass>();
> > > ```
> > 
> > 
> > MyClass.Null, as given by operator.
> 
> This is similar to earlier: it's simply impossible, because the doesn't know that it should call `MyClass.op_null` for a generic type. `result` _has_ to be `null`.
> 
> > > ```cs
> > > public class C
> > > {
> > >     public MyClass Foo;
> > > }
> > > 
> > > MyClass result = new C().Foo;
> > > ```
> > 
> > 
> > `NRE` not thrown result = MyClass.Null, as given by operator.
> 
> So the compiler would have to insert an initializer:
> 
> ```cs
> public class C
> {
>     public MyClass Foo = MyClass.op_null();
> }
> ```
> 
> > > ```cs
> > > public struct S
> > > {
> > >     public MyClass Foo;
> > > }
> > > 
> > > MyClass result = default(S).Foo; // or new S().Foo
> > > ```
> > 
> > 
> > MyClass.Null, as given by operator.
> 
> However, the compiler _can't_ insert an initializer for `Foo` here, because the struct is zero-initialized. So if you do `default(S)`, its `Foo` field _has_ to be `null`, no ifs, no buts.
> 
> The only way this could work is if the compiler inserted a null-check every time it accessed a field of type `MyClass`:
> 
> ```cs
> MyClass tmp = default(S).Foo;
> if (tmp == null)
>     tmp = MyClass.op_null();
> MyClass result = tmp;
> ```
> 
> As with arrrays, if the null operator didn't return a singleton instance, accessing a field twice might yield two different instances, so `S s = default(S); ReferenceEquals(s.Foo, s.Foo)` could be `false`, which is really messed up.
> 
> > > ```cs
> > > object obj = 3;
> > > 
> > > MyClass result = obj as MyClass;
> > > ```
> > 
> > 
> > MyClass.Null, as given by operator.
> 
> @Flutterish has done a good job of picking this one up.
> 
> > > ```cs
> > > object obj = null;
> > > 
> > > MyClass result = (MyClass)obj;
> > > ```
> > 
> > 
> > MyClass.Null, as given by operator.
> 
> So all cast operations would have to insert a null-check. As before, `ReferenceEquals((MyClass)null, (MyClass)null)` could be false, which is broken.

**Comment by IllidanS4** [comment]
One of the defining aspects of CLI has been the fact that every type has a default value, and this value is always zero-initialized. This is so that accessing an uninitialized storage obtains a (by definition) valid value and all that is necessary is zeroing out the memory. More recently, C# has realized that not all types actually have a meaningful (albeit still valid in the eyes of the CLI) value, giving need to non-nullable reference types (addressing the issue externally) and non-defaultible value types (addressing the issue internally).

What I like about this proposal is that there are cases where the default value is non-trivial, so perhaps `default` for those types could be modified to mean something else. There is however an issue for reference types:

```cs
object a = null; // a is null
var b = (MyClass)a; // b is MyClass.Null
a = b; // a is MyClass.Null
```

I think it would be better to mark a special field as the default value, which could then be used as the default value for value types. Not sure about reference types though, `Object.ReferenceEquals` for `null` should be true only for another `null`.

**Comment by Flutterish** [comment]
If we do something like this, then it should rather be a `default operator`
```cs
object a = null; // a is null
var b = (MyClass)a; // b is null
a = b; // a is null

MyClass c = default; // c is MyClass.Default
object d = c; // d is MyClass.Default

object e = default; // e is null
MyClass f = e; // f is null

void MyMethod ( MyClass g = default ) {
    ...
}
// translated to
void MyMethod ( MyClass g = null ) {
   if ( g is null ) g = MyClass.Default;
   ...
}
// Of course this means if you pass a null to this method it will get eaten and changed to default
// I dont know how desireable that is

void SecondMethod ( object h = default ) { // Compiler error, not specific enough to use default ( use null instead )
    ...
}

void ThirdMethod<T> ( T i = default ) where T : class {
    ...
}
// translated to
void ThirdMethod<T> ( T i = null ) where T : class {
    if ( i is null ) i = default( T ); 
    // default( T ) would need to return T.Default or we would need virtual statics
    // or just use reflections
    ...
}
```

**Comment by juliusfriedman** [comment]
> If we do something like this, then it should rather be a `default operator`
> 
> ```cs
> object a = null; // a is null
> var b = (MyClass)a; // b is null
> a = b; // a is null
> 
> MyClass c = default; // c is MyClass.Default
> object d = c; // d is MyClass.Default
> 
> object e = default; // e is null
> MyClass f = e; // f is null
> 
> void MyMethod ( MyClass g = default ) {
>     ...
> }
> // translated to
> void MyMethod ( MyClass g = null ) {
>    if ( g is null ) g = MyClass.Default;
>    ...
> }
> // Of course this means if you pass a null to this method it will get eaten and changed to default
> // I dont know how desireable that is
> 
> void SecondMethod ( object h = default ) { // Compiler error, not specific enough to use default ( use null instead )
>     ...
> }
> 
> void ThirdMethod<T> ( T i = default ) where T : class {
>     ...
> }
> // translated to
> void ThirdMethod<T> ( T i = null ) where T : class {
>     if ( i is null ) i = default( T ); 
>     // default( T ) would need to return T.Default or we would need virtual statics
>     // or just use reflections
>     ...
> }
> ```

I can't disagree with that seeing how we call defaults what they are in the CLR.

I could live with that.

Thank you for your input!

**Comment by canton7** [comment]
> > > > ```cs
> > > > MyClass[] arr = new MyClass[1];
> > > > 
> > > > MyClass result = arr[0];
> > > > ```
> > > 
> > > 
> > > MyClass.Null, as given by operator.
> > 
> > 
> > This one's a bit tricky: arrays in C# are just zero'd, there's no mechanism for going through and setting each element to the result of the null operator. However, you _could_ do this if you added a test when _retrieving_ an array element, i.e.:
> 
> Yes there is, its called `SkipLocaslInit`

`SkipLocalsInit` is about skipping the zero-initialization of locals (as the name suggests): if you apply it, then the CLR won't zero out your local slots, and you rely on the compiler to make sure that you initialize them. 

It has nothing to do with initializing array elements (which are not locals: `arr` is a local, but the elements of `arr` are not). It has nothing to do with doing *extra* initialization: it's to do with *skipping zero-initialization*.

Arrays are always zero-initializated, and *only* zero-initialized. This is not going to change.

------------------

> > ```cs
> > MyClass[] arr = new MyClass[1];
> > MyClass tmp = arr[0];
> > if (tmp == null)
> >     tmp = MyClass.op_null()
> > MyClass result = tmp;
> > ```
> > 
> > 
> > However, this means that accessing `arr[0]` twice will call the null operator twice. If the null operator doesn't happen to return a singleton instance, then `ReferenceEquals(arr[0], arr[0])` will be `false`, which is very weird.
> 
> for 1) It's up to the impl to decide.

Yes, we're talking about the implementation. A proposal needs to discuss possible implementations, and identify implementation issues. If your proposal cannot work because it cannot be implemented, then it is dead in the water.

> for 2) no it will not as the location of arr[0] didn't change only the reference to it did and this is not a by reference operator.

I think you didn't understand what I said. You cannot get the compiler/runtime to initialize `arr[0]` by calling `MyClass.op_null()`, because array elements are zero-initialized. So the only option is to add checks to any *access* of `arr[0]`, and replace any `nulls` you find with `MyClass.op_null()`. Accessing an array element should not cause it to be changed however, so you need to do this check each and every time `arr[0]` (or any other array element) is accessed.

------------------

> > This does however mean `result` can never be true here:
> > ```cs
> > MyClass[] arr = new MyClass[1];
> > object[] objectArr = arr;
> >  
> > bool result = objectArr[0] is null;
> > ```
> 
> If by reference it certainly can be, by reference doesn't invoke the null operator, you need `null` explicitly somewhere for the operator to work on.

I don't understand what you mean by "by reference doesn't invoke the null operator". 

-----------------

> > The compiler doesn't know that it should insert this special check when accessing `objectArr[0]`, since the array is of type `object`. So `objectArr[0]` _must_ be `null` and not `MyClass.Null`. That's very unintuitive to me.
> > 
> > > > ```cs
> > > > public T M<T>() => default(T);
> > > > 
> > > > MyClass result = M<MyClass>();
> > > > ```
> > > 
> > ```
> 
> Don't overload the operator then.

I don't follow. This discussion is about implementing the `null` operator: that is what we're talking about.

--------------

> Lost at about here and can't argue anymore.

If you need help understanding the problems with your proposal, please explain what's confusing you and perhaps we can help. Otherwise, the problems will remain unsolved and will stop the proposal progressing.

**Comment by canton7** [comment]
@Flutterish 

> If we do something like this, then it should rather be a `default operator`

Why not do `MyClass c = MyClass.Default`, rather than changing what `MyClass c = default` does? IMO that's much clearer.

> ```cs
> void SecondMethod ( object h = default ) { // Compiler error, not specific enough to use default ( use null instead )
>     ...
> }
> ```

This is a breaking change, and so it's a no-go.

> ```cs
> void ThirdMethod<T> ( T i = default ) where T : class {
>     ...
> }
> // translated to
> void ThirdMethod<T> ( T i = null ) where T : class {
>     if ( i is null ) i = default( T ); 
>     // default( T ) would need to return T.Default or we would need virtual statics
>     // or just use reflections
>     ...
> }
> ```

Using reflection is a no-go: this would add reflection any time that `default(T)` is used for any `T` in any generic method. That's going to be an unacceptable perf hit.

Shapes / etc would be a possibility, but then presumably you'd need to opt in with something like `void M<T>() where T : SDefaultable` or something. If you're going to do this, why not use `T.Default` rather than changing what `default(T)` does?

**Comment by IllidanS4** [comment]
What if instance methods/properties could instead be marked "nullable" meaning `this` can actually be `null`? This would solve the same area of problems without relying on this null polymorphism.

**Comment by Flutterish** [comment]
> Shapes / etc would be a possibility, but then presumably you'd need to opt in with something like void M<T>() where T : SDefaultable or something. If you're going to do this, why not use T.Default rather than changing what default(T) does?

I absolutely agree, given shapes can have statics like
```cs
shape SDefaultable<T> {
    static readonly T Default; // = new MyClass( default parameters );
}
```
It would guarantee that `T.Default == T.Default`. If a singleton is not desireable just use `where T : new()`.

> What if instance methods/properties could instead be marked "nullable" meaning this can actually be null? This would solve the same area of problems without relying on this null polymorphism.

That is called a static method. If you need an optional maybe-yes-maybe-not-null `this`, it's called an extension method. The only difference I see is that you can't rely on `private` props.

**Comment by Unknown6656** [comment]
@jaredpar  or @333fred
You can close this issue as the OP has been banned from this repository.

**Comment by IllidanS4** [comment]
Sad, the posts were quite entertaining.

**Comment by Unknown6656** [comment]
@IllidanS4 : Yeah, I know what you mean ... his rudeness however, was kinda unbearable and non-constructive.
