### ISSUE TITLE
Inferencing of nullability for var declarations 

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/csharplang#3821]
Nullability of 'var' type declarations is not always inferred when it could be. Consider the following: 

        private void TVI_RightTapped(object sender, RightTappedRoutedEventArgs args)
        {
                var tvi = (sender as TreeViewItem) ?? throw new InvalidOperationException();
                ...
        }
         
Expected: type of tvi should be TreeViewItem.

Actual: type of tvi is TreeViewItem?.

**Comment by canton7** [comment]
This is a deliberate design decision: `tvi` is nullable, but the null flow state is `NotNull`. This means that you won't get a warning if you try to access its members.

This is actually a change to the original design, because users were saying they wanted to be able to write:

```cs
SomeType? SomeMethod() { ... }

var foo = new SomeType();
if (condition)
{
    foo = SomeMethod();
}
```

If `foo` were inferred as a `SomeType` rather than `SomeType?`, then line `foo = SomeMethod()` would raise a nullable warning.

See #3591 and #3662 for further discussion.

**Comment by 333fred** [comment]
As canton linked, this is intentional design. The issues linked are available for further discussion of this, so I'm going to close this.
