### ISSUE TITLE
passing 'this' from constructor to antoher method

### ISSUE THREAD

**Issue by pav1un** [dotnet/csharplang#3825]
why does the compiler allow passing 'this' to another type from constructor?
```
using System;
	
public class A
{
	public object o;
	
	public A()
	{
		Program.P(this);  // current object is not fully initialized here 
                o = new oject();
		// initializing
	}
}

public class Program
{
	public static void P(A a)
	{
		Console.WriteLine(a.o);
	}
	
	public static void Main()
	{
		new A();
	}
}
```

**Comment by CyrusNajmabadi** [comment]
> why does the compiler allow passing 'this' to another type from constructor?

Because nothing in the language specification disallows it.  Note: this has been allowed since C# 1.0 so it is not something that could ever change (as it would break existing customers badly).  If you want to prevent this in your own code, the appropriate solution is to write an analyzer that checks your constructors and flags cases like this so you can decide waht to do about them.
