### ISSUE TITLE
Auto dispose

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3860]
I wanted:

``` csharp
void Foo()
{
    var o = new SomeClass();
    // do some with o
    // auto release o immediately
}
```

When I first learned csharp from c++ many years ago, I was confused why c# do not support **distructor** ? And why csharp use IDisposable? At that time I had no idea, and think about that It's maybe the cost to use GAC. 

However,  when I am starting to learn Rust，I think that It's the time to make change. Rust will release **variable heap memory** when outof variable scope, acting just like **stack memory**。Why c# can not do it? 

We can provide a compile option **“Auto dispose”**，when the compiler meat the code，the compiler will build codes like：

``` csharp
void Foo()
{
    var o = new SomeClass();
    // do some with o
    // compiler will generate this code to release o immediately
   if (o is IDisposable)
       o.Dispose();
}
```

It' s good to avoid memory leak and make codes shorter. And don't need to write `Dispose()` or `Using`  any more.

**Comment by yaakov-h** [comment]
This assumes very narrow ownership semantics, which is generally not viable in non-trivial codebase.

**Comment by svick** [comment]
>  I was confused why c# do not support distructor ?

C# does support finalizers (which are sometimes confusingly called destructors), which in some ways were supposed to replace destructors. But it turned out that most of the time, relying on them is not a good idea, due to their non-deterministic nature.

> However, when I am starting to learn Rust，I think that It's the time to make change. Rust will release variable heap memory when outof variable scope, acting just like stack memory。Why c# can not do it?

Because C# does not have any concept of ownership, which is critical to make this work in Rust. Consider this simplified version of `StreamReader`:

```c#
class StreamReader : IDisposable
{
    private Stream stream;
    private bool leaveOpen;

    public StreamReader(Stream stream, bool leaveOpen)
    {
        this.stream = stream;
        this.leaveOpen = leaveOpen;
    }

    public string ReadLine()
    {
        var s = stream;
        ...
    }

    public void Dispose()
    {
        if (!leaveOpen)
             stream.Dispose();
    }
}
```

How would you implement that using auto-dispose?

> We can provide a compile option “Auto dispose”

That would create a dialect of C# and the Language Design Committee considers doing that only when absolutely necessary.

> It' s good to avoid memory leak

That's what the GC is for.

**Comment by theunrepentantgeek** [comment]
A compiler option to "Auto dispose" would introduce another dialect of C#, something that the LDM has very clearly indicated they're not going to do. (Yes, Nullable Reference Types are a dialect - but are a special case because of the extraordinarily high expected return in bug detection/elimination.)

Further, not every type should be automatically disposed - so the language would need some way of indicating which locals should be disposed, and which should not.

I'd suggest reusing an existing keyword to separate the two cases.

``` csharp
void Foo()
{
    using var o = new SomeClass();
    // do some with o
    // auto release o immediately
}
```

Oh, wait. Look. This [already exists in C# 8](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations). 😁 😉

**Comment by msedi** [comment]
Is this something that is maybe related to #3450.

**Comment by Youssef1313** [comment]
`using var o = new SomeClass();` is just simple. Only one extra keyword to your code and the compiler will do the disposal.

Automatic dispose won't be desired in some certain cases. Take HttpClient as an example.

As for "avoid memory leak", there is a CA rule that detects where you may unintentionally missed a dispose.

**Comment by msedi** [comment]
@Youssef1313 : This is not true in all cases. Assume you have a struct Image

``` CS
public readonly struct Image
{
  public readonly float[] Data;
  public int SizeX,SizeY;

  public IMage (float[] data, int sizeX, int sizeY)
  {
    Data = data;
    SizeX = sizeX;
    SizeY = sizeY;
  }
}
```

that is returned by the method 

``` CS
public class Volume
{
int SizeZ;

public Image GetData(int index)
{
  int SizeX = 512;
  int SizeY = 512;
  var data=  ArrayPool<float>.Shared.Rent(Size*SizeY);
  return new Image(data,SizeX,SizeY);
}
}
```

and in some routine you simply use it:

``` CS
public float[] Add(Volume A, Volume B)
{
  for (int i=0; i<A.SizeZ;  i++)
  {
    Image a = A.GetData(i);
    Image b = B.GetData(i);

    Image c  = a+b;
  }
}
```

This is a simple example if you forget to use `using `you are causing severe memory leaks. In the situation above classes are used where you could argue you don't need it. But it might be a bit different for structs. I understand that the general rule suggests to rely on the analyzers, but I really prefer that problems  are prevented and not create a report to prevent them if the language could easily prevent it. There is of course the discussion for heap types. But a deterministic finalizer would be of great help for high-performance scenarios where you want to have a deterministic behavior.

I have a current scenario where I currently don't do things as described in the code above since none of my colleagues will realize that they have to call Dispose on the struct. At the moment I'm solving this with regular allocations and here the finalizer runs like hell. The pipeline we have produces are around 10GB per step where each image is around 1MB, so for each image one allocation and a following GC event because it's extremely short living but still in the LOH which causes additional troubles).

Furthermore the 10GB is only for one stepp, but we have 50 of them. So you can imagine something more deterministic would be of great help.

**Comment by 333fred** [comment]
Thanks for submitting this proposal. Unfortunately, the team does not feel that this proposal is in line with the current or future direction of the C# language. As such we are closing it. This is not a change that we will ever be able to make. Unlike Rust, C# does not have ownership semantics, and there is no guarantee that the thing that would be disposed _should_ be disposed at the end of the method. https://blog.paranoidcoding.com/2019/12/02/borrowing.html describes Jared's experience on midori, which had such annotations, and why such a system is not directly portable to C#.

Aside from our simple inability to make such a feature work, this would also be a massive breaking change. We generally don't like magic like this, where changing something in one assembly can change the behavior of methods 3 assemblies down the chain silently. You can never completely avoid it, but we try as much as possible. We aren't even able to add pattern-based Dispose because the breaking change around foreach behavior is to big, where things that aren't disposed today would get disposed then.
