### ISSUE TITLE
Add official format and formatter for C#

### ISSUE THREAD

**Issue by wanton7** [dotnet/csharplang#393]
Please add official C# format and formatter similar to what golang has with gofmt.

It would help c# readability between multiple projects if some official formatting rules would be available. Something like "csfmt" command line formatter should be included with msbuild & coreclr. Visual Studio should also be do this formatting on save if you want.

I know https://github.com/dotnet/codeformatter exists. But it only formats whole solution and can't format single file.

**Comment by orthoxerox** [comment]
There's no single standard for writing C# code. VS2017 [supports different settings for different projects](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options) and you can reformat on save with [this extension](https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave).

If you want to move the formatter to coreclr, you should probably raise the issue in https://github.com/dotnet/coreclr instead.

**Comment by wanton7** [comment]
> @orthoxerox There's no single standard for writing C# code

This is exactly why we need one official format.

**Comment by svick** [comment]
[The .Net Core CLI has the notion of tools.](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/extensibility) So if you wanted, you could write your own `dotnet csfmt` and distribute it using NuGet.

**Comment by wanton7** [comment]
@svick How would that make it official?

**Comment by jnm2** [comment]
Obligatory xkcd:
![](https://imgs.xkcd.com/comics/standards.png)

Humor aside, I don't see a problem with the way things are. I'd guess that trying to make one of the diverse sets of formatting standards the only blessed standard would be at best a waste of time and possibly lead to more conflicts.

**Comment by sharwell** [comment]
@wanton7 The format for Go code you refer to is a *de facto* standard and recommended practice, but it's not actually mandated by the language specification. A subset of the Roslyn team is currently working on compiler infrastructure which will allow coding standards to be more easily enforced. The GitHub project where many of the related issues are being tracked can be found here:
https://github.com/dotnet/roslyn/projects/4

It's important to us that users with a variety of different but well-established practices (i.e. styles) be able to benefit from improved productivity of automated enforcement and correction of style issues while you work. There are two approaches available when trying to accomplish that:

1. Pick a style, and make it easy to switch to that style so it's as painless as possible
2. Pick a set of settings that allows a variety of styles to be used, and provide a default style

In practice, option 2 turns out to be the only real option for us. Many users are working on large projects with policies that would prevent them from *ever* using the new tools if we went with option 1. To make it easier for users like yourself to view option 2 *as* option 1, one thing we'd like to do is make it possible for users to distribute pre-configured styles as NuGet packages. In other words, if you create a single NuGet package containing standards for a well-~liked~ *adopted* style, users around the world could install that NuGet package for an experience similar to `gofmt`, except that it could also (optionally) be enforced with warnings or errors at compile time.

If you have questions, suggestions, feedback, or simply want to participate in our efforts to make coding style headaches a thing of the past, feel free to reach out to me or others over at [dotnet/roslyn](https://github.com/dotnet/roslyn), or in the Gitter room for Roslyn.

**Comment by wanton7** [comment]
@sharwell Thanks i'll do that, sounds awesome.

**Comment by gilescope** [comment]
"provide a default style ." <-- This please, just need a 'default' style that everyone agrees is not right in different directions.

Obviously opinionated no options is great for standardisation ( https://github.com/ambv/black ), but you get a standard by people just opting for the default.

**Comment by jrr** [comment]
For anyone happening upon this today, check out https://github.com/dotnet/format

**Comment by kendrahavens** [comment]
There is also a [default EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019#example-editorconfig-file) template now included in Visual Studio for .NET. The styles captured there and applied with the [dotnet format tool](https://github.com/dotnet/format#how-to-install) at the command-line or with the `Format Document` or `Code cleanup` commands in Visual Studio should achieve this experience.
