### ISSUE TITLE
[Proposal]: New expression for access backing field of auto-implemented property

### ISSUE THREAD

**Issue by Flithor** [dotnet/csharplang#4146]
# New expression for access backing field of auto-implemented property: **fieldof()**

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary
Make programmer to access the backing field of auto-implemented property when necessary to be use it with ref param.

## Motivation
[motivation]: #motivation
We cannot use property with ref param. If I want to use a property value in some place, I should to write a full property.

## Detailed design
[design]: #detailed-design
```
//auto-implemented property
public int MyProp { get; set; }

//method with ref param:
pubic void MyMethod(ref int param) { ... }

//error:
MyMethod(ref MyProp);
=========
//use it:
MyMethod(ref fieldof(MyProp));

//equals:
private int myProp;
public int MyProp
{
    get => myProp;
    set => myProp = value;
}
MyMethod(ref myProp);
```

## Drawbacks
[drawbacks]: #drawbacks
May will make readonly property be modifiable.
But can limit it cannot use fieldof on readonly propery. 

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by CyrusNajmabadi** [comment]
> Make programmer to access the backing field of auto-implemented property when necessary to be use it with ref param.

At this point i would say that you shouldn't have an auto-prop.  

> ```MyMethod(ref fieldof(MyProp));```

This is particularly concerning, because it makes how a property works no longer an implementation detail.  For example, you couldn't change your property from an auto-prop to a completely computed prop as that would break anyone that did `fieldof` on it.  

The reason to use a property in the first plcae, and not just use a field, is entirely because the impl should be hidden and can be updated/replaced in the future without breaking anything that would change this.

If you want ot be able to pass as a ref, and you want people to be able to use the field directly, then there is no value in usign a property.  Just replace the property with a field.  Now it will all work, and will have all the same limitations as you'd have if you used `fieldof()`
