### ISSUE TITLE
Checked Exceptions

### ISSUE THREAD

**Issue by pedrobfernandes** [dotnet/csharplang#429]
What about Checked Exceptions in C# like Java?

I think it would be helpful to expect all behaviors of the method/object.

```csharp
public class FileUtils
{
    public void Write(string content)
        throws : DirectoryNotFoundException
    {
        ...
    }

    public void WriteGeneric<T>(string content)
        throws : DirectoryNotFoundException
        where T: class
    {
        ...
    }
}
```
It will enforce that every method who calls FileUtils.Write should do it within a try..catch.. statement.

**Comment by zippec** [comment]
I believe checked exceptions are generally bad.

I recommend reading this interesting discussion with Anders Hejlsberg explaining why C# does not have them. http://www.artima.com/intv/handcuffs.html

**Comment by gafter** [comment]
It is unlikely we'd reverse ourselves on such a longstanding and deep design issue.

**Comment by Flash3001** [comment]
You should also read http://joeduffyblog.com/2016/02/07/the-error-model/

**Comment by juwens** [comment]
I have to support the ticket author.

When I read articles and comments arguing against checked exceptions, they remind me much of the arguments of dynamic typing vs static typing.

When I call a method in C# it’s obvious what it’s return type will be. But I have no idea if it may raise an exception. So to be 100% sure I would need to put a try catch statement araound a lot of calls.

Checked exception and static typing have a lot similarities.

Pro
- provides more information to the compiler and developer
- help to reason about the behaviour 
Con
- make api evolution more difficult

A good practise is to write code, which is easy to reason about it’s behaviour.
And I see a big benefit if we introduce (maybe optional) checked exceptions, which outweighs the disadvantages (IMO). 

I respect mr Heilsbergs opinion a lot, but C# was designed a long time ago and apparently a design goal was to make it easier for people switching to C#.

That shouldn’t hinder us today to think about possibilities to make our code more expressive and therefore our work easier. And maybe also have a different opinion than a very smart person.

PS: I remember the days when (also smart) people where arguing against static typing and emphasising the benefits of dynamic typing.

**Comment by HaloFour** [comment]
@juwens 

Checked exceptions as they are implemented in a language like Java don't make API evolution difficult, they make it impossible.  The exceptions are a part of the contract and it's impossible to add any others without breaking all existing consumers.  So that forces implementers to group exceptions in weird ways, or just default to throwing everything as unchecked, which is insanely common.  Forcing every consumer of every method to either catch/handle all of the possible exceptions or explicitly propagate them up doesn't scale.  And the entire concept of checked exceptions breaks down very painfully when you start to program in a more functional manner.  I think it's telling that nearly every other language on the JVM just ignores checked exceptions outright.

If C# were to ever get something like checked exceptions I could only ever see them handled like NRTs.  External metadata that can be used to drive analyzers which might warn, but never anything stricter.

A much better solution would be DUs and `Result<T>`-like types.  If an error mode is a part of the contract, encode it into the return type.
