### ISSUE TITLE
[Proposal]: Error handling or Result<T, E>

### ISSUE THREAD

**Issue by molor824** [dotnet/csharplang#5293]
# Error handling or Result<T, E>

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
Return Result<T, E> and make programmer handle the error instead of throwing exception

## Motivation
Instead of throwing exception in the middle of the process which could cause confusion on wheter if its your error or the library error, making the programmer handle the error allows for the programmer to understand the error more easily.

## Detailed design
Simular to rust, `Result<T, E>` will have many ways to handle the error, either by unwrapping which panics if the Result is Error, or through if/switch statement. Unwrapping could possibly be a `.` operator instead of function to allow programmers to completely ignore it. For example `SomeFunc().foo` instead of `SomeFunc().unwrap().foo`

## Drawbacks
Might remove the purpose of exception

## Alternatives
Could return nullable value but then you'll only get null exception when used. `Result<T, E>` throws `E` as its exception making it more clear to understand

## Design meetings
The idea was from rust programming language's error handling https://doc.rust-lang.org/book/ch09-00-error-handling.html

**Comment by svick** [comment]
For a new language, I think the choice between exceptions and something like `Result<T, E>` is a good topic for discussion, since both have their pros and cons and neither choice is clearly better.

For a decades old language, I think there is no choice: the only reasonable approach is to stick with the error-handling strategy you already have. That's because retrofitting a new strategy onto an existing language would lead to a lot of friction (e.g. what happens to all the existing code that uses exceptions?). And if you add the cons of the new approach to that, they significantly outweigh its pros.

**Comment by HaloFour** [comment]
This should be moved to a discussion.

See: https://github.com/dotnet/csharplang/issues/113

Also, in my opinion, while I do think that there's value in the language adding support for discriminated unions that would make it easier to work with `Option`/`Maybe`/`Result`/`Try`/etc. types, I believe that it is _exceptionally_ unlikely (pun intended) for the BCL to consider splitting the ecosystem and introducing a complete new set of APIs that would favor DUs (or anything else) over the existing idiomatic C# approaches of throwing exceptions or following the `Try*` pattern.  Those expecting that the BCL will all of a sudden adopt functional idioms are likely to be very disappointed.
