### ISSUE TITLE
Proposal: Class with automatic reference count

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#547]
C# 8.0 should allow users to define classes with automatic reference count, which would be collected once their reference count becomes zero.
For example:
```C#
[ARC] public class A //class A with automatic reference count
{
    int n;
    A(){......}
    ~A(){......}
}
int main(......)
{
    A a=new A(); //RC(a)=1
    ......
    a=null; //RC becomes zero, call finalizer and collect memory
}
```

**Comment by yaakov-h** [comment]
Why?

**Comment by svick** [comment]
I find it really hard to imagine there would be sufficient justification for this:

1. Performance? Reference counting does have different performance characteristics than tracing GC, but that does not necessarily mean better, especially if you compare it with a tracing GC that has been tuned for over a decade.
2. Determinism? `IDisposable` mostly works well for that.

So, what are the huge benefits that would justify the likely huge costs?

**Comment by HaloFour** [comment]
This is a CLR feature, not a language feature.  You're not asking for any syntax changes and as far as I can tell the behavior of ARC would still fit into the relatively vague discussion of memory management in the C# specification.

**Comment by ygc369** [comment]
@HaloFour 
Actually, this feature need a new syntax to indicate whether a user-defined class should be managed by ARC or tracing GC.

**Comment by yaakov-h** [comment]
@ygc369 I don't see any new syntax in your example code above.

**Comment by ygc369** [comment]
@yaakov-h
"[ARC]" as an attribute.

**Comment by yaakov-h** [comment]
@ygc369 a new attribute class is not a new syntax.

**Comment by fanoI** [comment]
So if I forget to do ```a=null``` I have a memory leak? It would be a little more acceptable if the ```a=null``` would be added automatically by the compiler when the stack unwinds as in the example it could be in some way similar to create objects into the stack.

**Comment by ygc369** [comment]
@fanoI 
I just gave an example. What you said is right, reference count should be decreased automatically when going out of scope.

**Comment by sharwell** [comment]
@ygc369 It sounds like this could be a special case of #114.

❓ What do you do about cycles (a classic problem in the area of reference-counted garbage collection)?

**Comment by ygc369** [comment]
@sharwell 
All people know that RC has cycle ref problem, but why so many languages still use it? 
If C# must be absolutely "safe", why it has "unsafe" syntax? 
In my opinion, tracing GC should be able to work together with RC.
If a RC-object has ref cycle, it can still be collected by tracing GC.

**Comment by sharwell** [comment]
@ygc369 My point was this: we already have a GC which is capable of non-deterministic cleanup of both managed and unmanaged resources. We also have scoped resource blocks (using statements) which are capable of deterministic cleanup within a targeted scope. It sounds like the purpose of this proposal is to extend the reach of deterministic cleanup to also cover targeted objects without limiting users to scoped statements. In specific terms, we want to provide deterministic cleanup of resources at the specific point in time where the GC would otherwise first be able to clean up those objects, whenever that point may be. However, while this is a fairly straightforward feature to provide (through reference counting) in many cases, a simple implementation of the feature would still be falling back to non-deterministic cleanup in the event a cycle exists.

There are many potential directions a proposal like this could take in response:

* We could ignore this downside, and silently allow non-deterministic cleanup in the event a cycle is introduced
* We could find some specific way to account for cycles while still providing deterministic cleanup at the ideal point
* We could in some way eliminate the ability to represent cycles for these data types
* We could fall back to non-deterministic cleanup, but offer an event somewhere (e.g. on the `GC` class) which can be used to trace cases where cycles exist, so users can work to mitigate the problems through weak references of some form (which might or might not have the same representation as `WeakReference` and `WeakReference<T>`)

Also, if we go with an approach that allows non-deterministic GC fallback in the event of a cycle, we need to find a way to define the relative execution order of cleanup of reference counted objects, [`CriticalFinalizerObject`](https://msdn.microsoft.com/en-us/library/system.runtime.constrainedexecution.criticalfinalizerobject.aspx), and other objects with finalizers.

**Comment by ygc369** [comment]
@sharwell 
> We could fall back to non-deterministic cleanup, but offer an event somewhere
What does this mean? Could you give some example code?

**Comment by sharwell** [comment]
@ygc369 Sure, two examples of a similar pattern are [`AppDomain.UnhandledException`](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception.aspx) and [`TaskScheduler.UnobservedTaskException`](https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler.unobservedtaskexception.aspx). These are two cases where the application probably did something unexpected (wrong), but the application may still be allowed to continue running.

**Comment by ygc369** [comment]
@sharwell 

> We could fall back to non-deterministic cleanup, but offer an event somewhere (e.g. on the GC class) which can be used to trace cases where cycles exist, so users can work to mitigate the problems through weak references of some form (which might or might not have the same representation as WeakReference and WeakReference<T>)

I think this would be the final solution. Do not try to find a better solution any more, just do it! There's no time to waste. If C# can't catch the last chance, it would lose the ability to compete with other languages, such as Swift, Rust and so on. If we run our program on a device with very little memory or in a situation disallowing pause, GC might be unacceptable. That's why reference count is so important.

To mitigate ref cycle problem, I have an idea. We need a light-weight version of weak reference, which does not increase ref count, and has no extra cost. This kind of light-weight weak reference can only be used to reference "back" to the object which references the container of the weak ref. So we need new syntax to represent reference "direction"----"forward" for strong ref, and "backward" for weak ref.
For example:
```C#
[ARC] public class LinkList
{
    forward LinkList next; //strong reference to next list node
    backward LinkList prev; //weak reference to previous list node
    int data;
    ......
}
static int main(......)
{
    LinkList L=new LinkList(); // rc(L)=1, rc means reference count
    L.next=new LinkList(); // rc(L.next)=1
    {
        LinkList tmp=L.next; // rc(tmp)=2
        tmp.prev=L; // rc(L)=1, not increase because "prev" is a weak ref. 
       /*before assignment to a "backward" field, the runtime should check whether the "right-value" object has a "forward" field referencing the "backward" field's container object. If not, throw an exception. */
    
        L.next=null;  // rc(tmp)=1, tmp.prev=null
       /*Before reassignment to a "forward" field, the runtime should automatically update the "backward" field of the object that the "forward" field is referencing, to be null. */
    } // tmp goes out of scope, rc becomes zero, free memory.
} // L goes out of scope, rc becomes zero, free memory.
```

**Comment by yaakov-h** [comment]
> I think this would be the final solution.

Please don't use that term.

Why the `forward` and `backward` - why not use `WeakReference<T>`?

**Comment by ygc369** [comment]
@yaakov-h 
Because WeakReference<T> has extra cost, we should not use it too much. If I want to create a LinkList with 100000 nodes, do you think I should alloc 100000 WeakRefence<T>?

**Comment by yaakov-h** [comment]
I'm pretty sure an ARC-compatible JIT would be able to handle `WeakReference` differently for ref-counted types.

I'd also suggest that you really don't need weak refs to implement a simple linked list.

**Comment by ygc369** [comment]
@yaakov-h 
If an ARC-compatible JIT would be able to handle `WeakReference` differently for ref-counted types, that would be very good.
---
If I don't use weak refs to implement an ARC linked list, it would fall back to GC, as cycles exist.
Of course, I can break cycles manually, but I think that using weaf refs is a better way.

**Comment by yaakov-h** [comment]
@ygc369 your proposal seems to be painting itself into a corner.

If I have the following object graph, where all references are strong references:


```
                     ------------------------------------
                    |                                   V
SomeObject -----> List ----> Node ------> Node ------> Node
                                  <------      <------

```

then I see no reason any of those items should be GC'ed or have their reference count drop to 0, assuming that *something* has a strong reference to `SomeObject`.

**Comment by ygc369** [comment]
@yaakov-h 
What you said is right, if something keeps a strong ref to `SomeObject`, nothing should be freed, no matter using ARC or GC. But what would happen if you remove the strong ref to `SomeObject`? I think even if all the objects in your graph are managed by ARC, they would not be collected until GC.

**Comment by sharwell** [comment]
> If we run our program ... in a situation disallowing pause, GC might be unacceptable.

@ygc369 Note that deterministic cleanup in reference counting schemes is necessarily non-deterministic in the amount of time it takes to complete. Reference counting in and of itself does not provide a solution for real-time systems (i.e. systems where memory-related operations are required to complete in a bounded amount of time). On the other hand, Metronome is a non-reference-counted garbage collector which does meet this property.

**Comment by fanoI** [comment]
But instead of have to add attributes it will not be possible to have an ARC GC in .NET maybe pluggable via configuration? So all Objects will benefit of it automatically and the problem to resort to a normal Garbage Collection will be again a GC problem not needed to add "Forward" and "Backward" qualifiers (?).

**Comment by ygc369** [comment]
@sharwell 
Would C# 8.0 have ARC?

**Comment by HaloFour** [comment]
@ygc369 
C# can't get ARC until the CLR supports ARC, so I'd suggest opening an issue on the [CoreCLR](https://github.com/dotnet/coreclr/) for the purposes of exploring that.

**Comment by sharwell** [comment]
@ygc369 While recent advancements have been made in the area of reference counting, I couldn't confidently say that the implementation of reference counting in the CLR or in C# specifically would represent an improvement over the current GC behavior. Also I would expect such a change to have a negative impact on some workloads (which may or may not be obvious before such a change shipped).

This falls into a category which I would call a risky undertaking for an uncertain outcome. It's certainly not the type of path one would head down for a production project without a great deal more information. On the other hand, I would very much encourage efforts to enable the CLR to be used in ongoing research related to this area. The system I see used most often, Jikes RVM, has been fairly stale for a while and doesn't allow researchers to investigate the impact of things like value types and pointers which Java bytecode cannot represent.

**Comment by HaloFour** [comment]
More than ARC, what I'd like to see is a mechanism in the CLR for pluggable GCs so that you can target and tweak to a specific workload.  I like how the JVM exposes a lot of those kinds of details.  If on top of that the CLR could also provide mechanisms through which the JIT and/or compilers could hint to the pluggable GCs how certain objects should behave, perhaps a degree of escape analysis, live tracking of root references and/or hooks into method returns then perhaps something like ARC could be plugged into the CLR possibly without any changes to the language at all.

**Comment by svick** [comment]
@HaloFour 

> a mechanism in the CLR for pluggable GCs

I believe CoreCLR uses [the `IGCHeap` interface](https://github.com/dotnet/coreclr/blob/1c28080/src/gc/gcinterface.h#L455) to communicate with the GC. So switching to a custom GC or even adding a mechanism for selecting which GC to use shouldn't be that hard.

**Comment by ygc369** [comment]
@HaloFour 
The [Local GC project](https://github.com/dotnet/coreclr/projects/3) seems to be what you want.

**Comment by ygc369** [comment]
@sharwell 
I think many people misunderstand my idea.
I never want to replace GC with ARC. I like GC too.
I only want an **optional** ARC to work together with GC, reducing workload of GC. They can help each other, ARC deal with most cases of freeing memory while GC deal with ref cycles and compact heap.
GC should never be turned off, no matter whether ARC is on or off. 
ARC should be optional. Programmers should have the right to decide whether to turn it on. (default off)
I think a complete memory management mechanism should have the following three key features:
1. EA (escape analysis). Allocate obviously short-lived objects on the stack, instead of heap.
2. ARC (automatic reference count). This should be optional, but once turned on, it should be able to collect most of garbage.
3. GC (garbage collect). It should collect the rest of garbage which EA and ARC can not deal.

**Comment by sharwell** [comment]
@ygc369 What happens in this case?

1. Does the finalizer run before or after `string.Format`? Why?
2. Does ARC now mean we need a write barrier for object references that checks the object type in order to handle reference counts? How do we implement atomic primitives with reference counted objects?

```
[ARC] public class A //class A with automatic reference count
{
    int n;
    A(){......}
    ~A(){......}
}
int main(......)
{
    object a=new A();
    string.Format("{0}", Interlocked.Exchange(ref a, null));
}
```

**Comment by ygc369** [comment]
@sharwell 
1. I think the finalizer should run after `string.Format`.
2. I don't know.

**Comment by sharwell** [comment]
@ygc369 This breaks one of the fundamental reasoning lines of most C# developers:

```csharp
object obj = GetSomeObject();

// This is trivially fast and doesn't take locks
obj = null;
```

However, with this proposal, the assignment to null now becomes a point where _anything_ could happen, including the possibility of cross-thread dependencies, locks, or an exception getting thrown.

**Comment by ygc369** [comment]
@sharwell 
You are right. I ignored too many things.
Maybe ARC is really not fit for C#. 
But what about escape analysis? In your example above, if `GetSomeObject()` only allocates a new object and does not store its reference on the heap, then the compiler should know that the object could be allocated on stack.

**Comment by sharwell** [comment]
Escape analysis definitely is useful for some things, but some of the other work being done (e.g. `Span<T>` and ref-like types) is even more powerful when it comes to addressing the performance concerns associated with types that are frequently used. It's like "forced" escape analysis in the language so you're guaranteed to get the performance benefits you're after in the places where you need them.

**Comment by ygc369** [comment]
@sharwell 
No more, thank you!

**Comment by jnm2** [comment]
@ygc369 You may be interested in this: https://www.microsoft.com/en-us/research/publication/project-snowflake-non-blocking-safe-manual-memory-management-net/#

**Comment by zachsaw** [comment]
Personally I think there's merit in using ref counting in C#. I've already been using this pattern for a long time, and it's especially useful in managing unmanaged resources where you don't necessarily know who is the last one still referencing it due to multi threading, but you can't wait for GC to call it's finaliser as it'll be too late (think Gen 2).

A lot of research has been going into this area where you mix managed and unmanaged memory. Ref counting is a good way to you baseline safety.

**Comment by tannergooding** [comment]
@zachsaw, when dealing with unmanaged resources, you can always force allocate/free completely outside of the GC. You can even do your own reference counting/etc. You just have to use `structs` (value types) and `pointers` or `ref`/`out` and cannot use `class` (reference types).

**Comment by zachsaw** [comment]
@tannergooding yeah that's exactly what I did. But it gets a little tedious and super verbose with the language not having copy constructor and RAII.

The verbosity is the thing C# should be good at keeping to a minimal but in this case it's wildly verbose.

**Comment by ygc369** [comment]
@sharwell @tannergooding 
>However, with this proposal, the assignment to null now becomes a point where anything could happen, including the possibility of cross-thread dependencies, locks, or an exception getting thrown.

This is true, but it doesn't break anything. 
C# developers should not assume any operation is fast, because GC may happen anywhere.
```C#
object obj = GetSomeObject();
obj = null; //with ARC, this assignment might be slower, but it must not be worse than GC happens here.
```
Another point, I never think that ARC should replace GC totally, they should work together.
Besides ref cycles, there's another problem that ARC can't solve alone----that's memory fragments, but GC can solve it, along with ref cycles.
ARC can collect memory more timely and reduce the pressure of GC, which means reducing the pause time of GC obviously.
So I think that ARC and GC should cooperate to make the program more efficient.

**Comment by HaloFour** [comment]
ARC with immediate collection only brings us back to the COM days when that release could trigger a recursive flurry blocking the current thread for a very noticeable amount of time across even moderately complicated object graphs or collection containers.  It's substantially worse than GC because at least GC delegates that accounting to other threads and you only have to deal with the much shorter pauses.

**Comment by cyraid** [comment]
Y'know.. Programming in C++ and Pascal, I remember the days where I could use Obj.Free(), and it would call "Obj.Destroy()" on the object (in Pascal case).

The thing is, in native compilable languages like that the statements get translated mostly linearly, and you can control what kind of asm gets generated most of the time. Calling Obj.Free() you know would jump in and call Obj.Destroy() etc, then free's the memory off the heap.

With a nice Heap Manager, you could have an objects list (memory list of pointers), and a freed objects list (a pointer into objects list), which you'd just push when you free a memory block, or pop when you add another one (moving of a pointer in the freed objects list).

What I would like to see though, is the control of being able to free an individual object and be guaranteed it's memory gone. This way it's simple, no confusing ref's and weak ref's, just plain ol' "I'm in control of when this object gets free'd".

**Comment by colejohnson66** [comment]
Those are all things a debugger is capable of helping with. Alternatively, if this is a common issue, your program's architecture needs work. ARC does nothing to prevent usage of an object when the reference count is 0 (a use-after-free bug).
