### ISSUE TITLE
[Proposal]: Disable CS0436 by default

### ISSUE THREAD

**Issue by stephentoub** [dotnet/csharplang#5528]
# Disable CS0436 by default

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Change the default setting for warning [CS0436](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0436) ("The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.") to be off by default.

## Motivation
[motivation]: #motivation

For features triggered off of attributes, source generators are able to inject the definition of said attribute into the compilation unit, and can also mark that attribute as being [Conditional(...)] on some compilation constant that no one will ever define.  This scheme enables developers to use attributes to key a source generator, have that attribute only be available when the source generator is in use, and not have any residue from the attribute persist into the assembly.

However, such attributes need to be injected as internal, and if multiple assemblies are using the source generator and one of them has [InternalsVisibleTo(...)] to the other, now CS0436 is fired to warn about the duplicate attribute.  This turns a reasonable approach into a really annoying approach.

## Detailed design
[design]: #detailed-design

Change the default level of the warning.

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

- Provide a mechanism to override [InternalsVisibleTo], e.g. [NotVisibleViaInternalsVisibleTo], that can be put on internal types to hide them from other assemblies using [InternalsVisibleTo] to access internals.

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by stephentoub** [comment]
cc: @jaredpar

**Comment by 333fred** [comment]
Is this a language request or a roslyn request? Feels more like the latter to me.

**Comment by stephentoub** [comment]
You tell me. :-) Jared suggested language.

**Comment by 333fred** [comment]
@jaredpar? Is this a warning mandated by the specification?

**Comment by jaredpar** [comment]
The language specification generally doesn't refer to warnings, only errors. This is core to type resolution though hence I tend to think of it more as a language issue vs. a compiler one. Or said differently, I can't see disabling this warning without first discussing in C# LDM hence I landed on the csharplang side of the fence.

**Comment by svick** [comment]
I think this warning is useful to diagnose issues that are otherwise hard to figure out. And disabling it by default is almost as bad as removing it outright: once you think of enabling this warning, you almost certainly already know what the problem is.

I'm not against somehow limiting this warning in a way that is useful for source generators. But I do think disabling it goes too far.

**Comment by stephentoub** [comment]
> I'm not against somehow limiting this warning in a way that is useful for source generators

FWIW, it's impactful for other scenarios as well.  For example, code that includes internal copies of attributes for downlevel scenarios, e.g. nullability attributes, hit the exact same problem.

**Comment by sab39** [comment]
Couldn't source generators that do this kind of injection just inject a `#pragma warning disable` in the file where they put the attribute definition?

**Comment by sab39** [comment]
> No, the warning is triggered at the usage site, not the declaration site, and source generators can't modify the usage site.

Ah, in that case I see why disabling it makes sense - but perhaps adding a warning at the declaration site instead would be a good idea? That way real problems would still get flagged, and the scenarios where it's intentional could put in a `#pragma` to make that intention explicit.

**Comment by jaredpar** [comment]
The idea I've been tossing around in my head is the following:

1. Change CS0436 so that it doesn't fire when the chosen type is defined in source. Essentially do not warn if one of the types in conflict is defined in source. It is reasonable to assume that if the customer defined the type in the current assembly then they likely wanted it to be chosen. 
2. Add a new warning which triggers on the declaration of a type that conflicts with other assemblies. 

That leaves customers with the same level of protection they have today but also provides a way for generators, down level attributes, shared source files, etc ... a method for avoiding the unnecessary warnings. All of those cases can put a `#pragma warning disable` in their code because they are aware of the possibility of conflicts and it's deliberate.

**Comment by stephentoub** [comment]
I'm going to close this.  We're not able to use attribute injection for our source generators (without trimming applied, it'll leave behind the attribute in every .NET assembly), so this issue is moot.

**Comment by pakrym** [comment]
As a data point, this is still valuable for other source generator authors: https://github.com/pakrym/jab/issues/122 https://github.com/andrewlock/StronglyTypedId/issues/38

**Comment by alexrp** [comment]
This NBGV issue also seems like a completely reasonable case where CS0436 gets in the way: https://github.com/dotnet/Nerdbank.GitVersioning/issues/555
