### ISSUE TITLE
Open question for semi-auto properties

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#5563]
Should semi-auto properties be treated as auto properties for the purpose of definite assignment?

```csharp
struct Program
{
    // causes CS0843:
    // Auto-implemented property must be fully assigned before control is returned to the caller.
    int P1 { get; set; }

    int P2 { get => field; set => field = value; } // CS0843?
    int P3 { get => field; set; } // CS0843?
    int P4 { get; set => field = value; } // CS0843?
    

    public Program(int dummy)
    {
    }
}
```

There is also this scenario:

```csharp
struct Program
{
    struct S1
    {
        public int AutoProp { get; }
        public int SemiAutoProp { get => field; }
        public int ManualProp { get => throw null; }
    }

    S1 x { get; set; }
    S1 x2 { get; set; }
    S1 x3 { get; set; }

    public Program(int dummy) // Error that x must be assigned, no error on x3. What should x2 do?
    {
        _ = x.AutoProp;
        _ = x2.SemiAutoProp;
        _ = x3.ManualProp;
    }
}
```

The above scenario is a bit related to https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfAZwXQFcBjBAAgAEBGAdgFgAoAbxcs8qNIsoGVaHLu2ZdxNAMyVYVAAq1KrSgHNUCANyUAvsIlSZMeQCYlq9ZQC8APkoAGLbrFcnegYoAeZtZu7qNrs6c1NJ09AAUspQAJiRgYDgAlG6i+pwA9OmUAEQAwvx2ABwALJIglACCJAgA9gC0UGAADgA2qGCoRqjRlE3oNU0YCDiUAORhAHQeo5RgJERu4pmUwKiUWCQtLSMQBARQKjDdK6hYNehrZDVG/S0yBDT0x7WLXMsIABaXEFsYE9n3SjXbbcD41ADuMBkWEonzWZy2ENgKkoLVgaygDyu8U6CG6E1ewVoEzoAE5wh4JnJjIkNITKMsAHI1PGwj4QKjUOyUBSGIioCA9Gow6mUcFQLaUH7giA4B4EMHgyj5IqlenLC4qCDoaJtPZir5w9BstZoo6A7EdLrRAlBHQsFjaIA===

**Comment by RikkiGibson** [comment]
> Should semi-auto properties be treated as auto properties for the purpose of definite assignment?

That's an interesting question. Because only the property can see `field`, I think the answer is yes, and additionally the requirement must be introduced that the property setter definitely assigns `field`.

**Comment by vladd** [comment]
@RikkiGibson 
Is assigning the `field` really enough? Consider this case:

```csharp
public int SemiAutoProp { set; get => field + someOtherUnrelatedField; }
```

**Comment by Youssef1313** [comment]
@vladd I think this example would be acceptable.

**Comment by RikkiGibson** [comment]
I think that specific example is not a concern, but a similar example with a setter could be. Because the setter could be called before everything is definitely assigned, we would probably need to assume that every field is unassigned, yet only a force definite assignment of the "owned" field.

I feel like a little thought and experimentation will be needed to ensure that we can get the required safety, as well as sufficient usability, and a coherent explanation for why the restrictions work the way they do. The net effect of what I've described is that adding a reference to 'field' in a setter causes all fields to be considered not definitely assigned, which could be an unpleasant surprise for users.

Depending on the perceived cost and benefit of supporting all this we might want to consider punting on supporting semi-auto properties within structs until we feel confident in what the right way is for it to work.

It would be good if LDM could weigh in. @CyrusNajmabadi @333fred.

**Comment by 333fred** [comment]
> It would be good if LDM could weigh in. @CyrusNajmabadi @333fred.

This issue was opened for precisely that reason 😉.

**Comment by RikkiGibson** [comment]
Too true!

**Comment by Youssef1313** [comment]
See also https://github.com/dotnet/csharplang/pull/5573

cc @AlekseyTs

**Comment by Youssef1313** [comment]
Spec need to address https://github.com/dotnet/csharplang/pull/5582#discussion_r775642113.

**Comment by 333fred** [comment]
Closing as having been addressed by LDM
