### ISSUE TITLE
Discussion:  Non-nullable Value Types

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#561]
This discussion follows some of the championed changes for nullable reference types (#36) and seeks to explore how they might apply to nullable value types.  This is purely for the sake of achieving a degree of symmetry between nullable value types and nullable reference types.

#### Flow analysis:

> A flow analysis tracks nullable reference variables. Where the analysis deems that they would not be null (e.g. after a check or an assignment), their value will be considered a non-null reference.

I think that this could also apply to nullable value types.  Flow analysis could similarly be used to ensure that the nullable value type could not be `null` at a specific point and allow it to be used as the normal value type.

For backwards compatibility this could only apply in those cases where the nullable value type would not currently produce legal code.

```cs
using System;

static class Program {
    public struct Foo {
        public static implicit operator Foo(int? x) => return default(Foo);
    }

    static void M1(int x) => Console.WriteLine("M1(int)");
    static void M2(int x) => Console.WriteLine("M2(int)");
    static void M2(int? x) => Console.WriteLine("M2(int?)");
    static void M3(int x) => Console.WriteLine("M3(int)");
    static void M3(Foo x) => Console.WriteLine("M3(Foo)");

    static void Main() {
        int? x = GetValue();
        if (x != null) {
            M1(x);
            M2(x);
            M3(x);
        }
    }

    static int? GetValue() => 123;
}
```

would print:

```
M1(int)
M2(int?)
M3(Foo)
```

#### "Dammit" postfix operator `!`

> A nullable reference can also explicitly be treated as non-null with the postfix `x!` operator (the "dammit" operator), for when flow analysis cannot establish a non-null situation that the developer knows is there.

This operator could also apply to nullable value types where the developer believes that the value could not be `null`.

There could be two potential behaviors if the value is actually `null`.  It could immediately throw, or it could return the default value of the value type.  This would be equivalent to using either the `Value` property or the `GetValueOrDefault()` method.

```cs
using System;

static class Program {
    static void Main() {
        int? x = GetValue();
        string value = new string('*', x!);
        Console.WriteLine(value);
    }

    static int? GetValue() => 5;
}
```

**Comment by lachbaer** [comment]
>  It could immediately throw, or it could return the default value of the value type. 

My opinion is to throw. The intent of this discussion is whether reference types and nullable value types shall be treated the same. Reference types would throw upon a null reference. So should nullable value types. Their usage in code should look and behave similar. For every other contingencies, there still is `GetValueOrDefault()`.

#### Question
After an explicit "Dammit" postfix should the compiler assume that the variable is not-null for the rest of the flow, thus making further dammits expendable? Or should the programmer be forced to repeat the operator every next time, so that the non-nullness is explicitly clear for every line of code?

**Comment by YaakovDavis** [comment]
> This is purely for the sake of achieving a degree of symmetry between nullable value types and nullable reference types

Except that nullable value types are actual *types*, while nullable ref "types" are lost at compilation.
I don't like the flow-analysis route the compiler takes here, (there might be an alternative way of achieving the proposal's goals).
Regardless of ref-types, I'm for limiting this, unless it can be done in a consistent, encompassing way.

Consider the following code:
```
int x;
...
if(x > 10)
{
   ...
   if(x < 5)
   {
   }
}
```
The inner `if` can't be reached, yet the compiler doesn't care, because it considers types, not values. As said in the other discussion, I'd vote for *consistency*, not single-shot tricks that handle trivial cases.

**Comment by alrz** [comment]
>Non-nullable Value Types

I'm triggered here. value types are already non-nullable.

I think the other thread on dammit operator also cover this case. no?

**Comment by DavidArno** [comment]
The issue I have with the flow analysis argument is that it simply isn't necessary as the `x is T y` pattern already covers this use-case, and it covers it in a more consistent fashion:
```cs
static void Main() 
{
    var x = GetValue();
    if (x is int y) 
    {
        M1(y);
        M2(y);
        M3(y);
    }
}
```
would print:
```
M1(int)
M2(int)
M3(int)
```
Rather than the simple "*if x is an int, then create an int value, y, and use that*", you are wanting the flow to be "*if x isn't null then, if an int value is needed then convert x to an int and use that value, otherwise carry on treating it as an int?*". To my mind, the fact that it is harder to describe shows this proposed solution isn't as good. I think it would lead to lots of confusion and wouldn't really offer any benefits over `x is int y`.

**Comment by HaloFour** [comment]
@alrz 

> I'm triggered here. value types are already non-nullable.

That they are.  This is purely for exploring symmetry in behavior and syntax between nullable reference types and nullable value types.  I'm not proposing anything as much as I am throwing spaghetti against the wall.

> I think the other thread on dammit operator also cover this case. no?

Yes, but I closed that other thread as it was primarily about discussing the "dammit" operator in relation to nullable reference types.  I hadn't realized that it was already included in the proposal due to the different in spelling.

**Comment by Thaina** [comment]
I prefer to have it being compile time feature. Like @DavidArno present. We should just do anything to have it being compile time error

**Comment by YairHalberstadt** [comment]
Closing as a 'duplicate' of https://github.com/dotnet/csharplang/issues/1865

This was opened first, but seeing as that one is by @MadsTorgersen and championed, I think it makes sense to move discussion there :-)
