### ISSUE TITLE
Discussion/Proposal:  multiple "when" clauses for a single switch case

### ISSUE THREAD

**Issue by bondsbw** [dotnet/csharplang#581]
This is a proposal to extend `switch` expressions to allow multiple `when` clauses for each individual `case` in a `switch` block.

Keeping with the DRY principle, consider [this example](https://github.com/dotnet/csharplang/issues/579#issuecomment-301515835) from the discussion at #579:

```c#
switch (foo)
{
    case Foo.Value1 when bar == Bar.Value1:
        // do something
        break;
    case Foo.Value1 when bar == Bar.Value2:
        // do something else
        break;
    case Foo.Value2 when bar == Bar.Value1:
        // do something
        break;
    case Foo.Value2 when bar == Bar.Value2:
        // do something else
        break;
    default:
        throw new NotSupportedException();
}
```

With multiple `when` clauses per `case`, this could be updated to the following:

```c#
switch (foo)
{
    case Foo.Value1
        when bar == Bar.Value1:
            // do something
            break;
        when bar == Bar.Value2:
            // do something else
            break;
    case Foo.Value2
        when bar == Bar.Value1:
            // do something
            break;
        when bar == Bar.Value2:
            // do something else
            break;
    default:
        throw new NotSupportedException();
}
```

**Comment by DavidArno** [comment]
Sorry, but I think [your original `case when` example](https://github.com/dotnet/csharplang/issues/579#issuecomment-301515835) is easier to read and it already works.

**Comment by alrz** [comment]
>DRY 

I find tuple pattern more readable for that example,
```
switch ((foo, bar)) {
    case (Foo.Value1, Foo.Value1): ... break;
    case (Foo.Value1, Foo.Value2): ... break;
    case (Foo.Value2, Foo.Value1): ... break;
    case (Foo.Value2, Foo.Value2): ... break;
}
```
though I can see how multiple `when` clauses can be useful.

**Comment by bondsbw** [comment]
No need to be sorry, it's a discussion.  FWIW the original example was simplistic and of course there are better ways to do it.

**Comment by MovGP0** [comment]
@bondsbw you are reinventing the 'Arrow Antipattern' here. Consider using the Strategy Pattern from the Gang-of-Four book.

**Comment by bondsbw** [comment]
@MovGP0 There are only 2 levels.  Every `case ... when ... :` statement naturally represents 2 levels.

But some of them share the same `case` clause, so why repeat it?  Seems that would be worse to me than any resemblance to Arrow.

**Comment by MovGP0** [comment]
@bondsbw I simply prefer @alrz pattern matching on tuples version. There is repetition, but the code is cleaner to read.

**Comment by bondsbw** [comment]
I like the tuple pattern better as well, but it doesn't cover general 'when` patterns.

**Comment by DavidArno** [comment]
@bondsbw,

And that is why we need recursive patterns, so something like the following is possible:
```cs
switch ((foo, bar)) 
{
    case (Foo.Value1, var bar) when bar == Bar.Value1 || bar == Bar.Value2: ... break;
    case (Foo.Value1, _): ... break;
    case (Foo.Value2, var bar): DoSomethingWith(bar) ... break;
    ...
} 
```

**Comment by bondsbw** [comment]
@DavidArno I don't find your example to be very compelling, compared with

```c#
switch (foo)
{
    case Foo.Value1
        when bar == Bar.Value1 || bar == Bar.Value2: ... break;
        when bar is _: ... break;
    case Foo.Value2:
        DoSomethingWith(bar); break;
    ...
}
```

The tuples don't add clarity; just the opposite.

**Comment by DavidArno** [comment]
@bondsbw,

We shall just have to disagree here then as I think tuples definitely make things clearer. 😀

**Comment by MgSam** [comment]
What's wrong with using an `if` statement? 

Personally, I find `when` to be very disconcerting- I'd much rather they hadn't buried the lead and just allowed you to put in a logical `&&`.

``` C#
switch(foo)
{
    case Foo.Value1 && bar == 5

        break;
}
```

**Comment by svick** [comment]
@MgSam Right now, `&&` is in a way symmetric: the left and right operand work the same, the only difference between them is the order of evaluation. Does that mean you would want `case bar == 5 && Foo.Value1` to work too? How? How does the compiler (and the person reading the code) differentiate between a pattern and a condition?

**Comment by MgSam** [comment]
@svick The ship has already sailed, so I don't think there should be any syntax changes at this point, but conceptually `case` is just another equality operator. So more like `case 5 && Foo.Value1`. 

When you're actually reading the code these are the mental translations you need to do anyway- it seems a shame that the syntax actively works against that in a manner inconsistent with how logical ands are written anywhere else in the language. 

And unfortunately `when` will significantly hamper adoption because most developers do not like learning new ways of doing the same tasks they can already do. For instance, I've never seen someone actually use an exception filter outside of Microsoft or a blog post.

**Comment by jnm2** [comment]
@MgSam `when` is no more of a new way of doing things than pattern matching in a switch statement, and people are happy with such new things.

Data point, I use exception filters in 22.6% of my catch clauses.

**Comment by MgSam** [comment]
@jnm2 Ok, and you actively participate in C# language discussions on Github and so are not a representative sample of a typical C# developer. 

Of the 5 other C# devs I work with, I doubt any of them have even *heard* of exception filters. 

New syntax should be reserved for extremely compelling use cases that enable scenarios not previously possible. In my opinion, lambdas fit this description, async fit this description, iterators fit this description, but I don't believe having an alternative way of writing "and" but instead spelling it `when` rather than `&&` met the bar. 

Yes, the semantics of `when` are slightly different than `&&`. But it's subtle enough as to be trivial in the vast majority of cases. Of course, as I said, it's too late now.

**Comment by HaloFour** [comment]
Supporting multiple `when` clauses is ultimately minor but I think it has some value.  I also believe that it would be relatively easy to add it to the supported grammar without affecting the current behavior.  This value will become more apparent with more complex recursive patterns:

```cs
switch (person) {
    case Student { GPA is var gpa, Name is var name }
        when gpa >= 4.0:
            Console.WriteLine($"{name} is a perfect student!");
            break;
        when gpa >= 3.0:
            Console.WriteLine($"{name} is a pretty good student!");
            break;
        when else: // or _ or whatever
            Console.WriteLine($"{name} needs to work harder.");
}
```

Sure, that could just as easily be solved with a nested `if` statement, but there is something elegant to this syntax.

@MgSam 

I don't think `&&` would have made sense as the expression in the `case` clause isn't a condition.  How would the compiler consider such things as overloadable operators?

Education is a constant issue in computer science.  Most of the C# programmers I know barely understand generics.  Lambdas are weird voodoo syntax that they're forced to use but don't understand.  Iterators, async, etc., it's amazing how infrequently I come across them in external projects.  If I didn't incorporate these technologies into the projects I work on it's quite doubtful that anyone else on my teams would.

Exception filters do provide a lot of value, but they also don't solve anything that couldn't already be solved with some nasty code.  I see that nasty code relatively frequently and I educate on the better syntax where I can.  That's our role here.  Otherwise most devs would just keep pounding away with that hammer blissfully unaware that someone invented screwdrivers.

**Comment by jnm2** [comment]
> Ok, and you actively participate in C# language discussions on Github and so are not a representative sample of a typical C# developer.

Fair. 😄 

> Of the 5 other C# devs I work with, I doubt any of them have even heard of exception filters.

I have a difficult time believing this. It doesn't ring true anecdotally with the C# developers I know.

**Comment by mattwar** [comment]
Now I'm just tempted to carry this further.  If DRY principle leads you to multiple when's, why stop at just one level?

```cs
switch (person) {
    case Student { GPA is var gpa, Name is var name }
        when gpa >= 4.0:
              when name == "Bob":
                    Console.WriteLine("Okay, Bob, you win.");
                    break;
             when else:
                    Console.WriteLine($"{name} is a perfect student!");
                    break;
        when gpa >= 3.0:
            Console.WriteLine($"{name} is a pretty good student!");
            break;
        when else: // or _ or whatever
            Console.WriteLine($"{name} needs to work harder.");
}
```

**Comment by jnm2** [comment]
> Now I'm just tempted to carry this further. If DRY principle leads you to multiple when's, why stop at just one level?

Because the nesting rules can't rely on whitespace.

**Comment by tannergooding** [comment]
You could just add the braces (and the colon and fix some spacing and don't forget the missing `break`) 😄 
```C#
switch (person)
{
    case Student { GPA is var gpa, Name is var name }:
    {
        when gpa >= 4.0:
        {
            when name == "Bob":
            {
                Console.WriteLine("Okay, Bob, you win.");
                break;
            }
            when else:
            {
                Console.WriteLine($"{name} is a perfect student!");
                break;
            }
        }
        when gpa >= 3.0:
        {
            Console.WriteLine($"{name} is a pretty good student!");
            break;
        }
        when else: // or _ or whatever
        {
            Console.WriteLine($"{name} needs to work harder.");
            break;
        }
    }
}
```

**Comment by jnm2** [comment]
Again, how is this better than `if` statements?

**Comment by mattwar** [comment]
@tannergooding is just trying to rain on my parade.  What's a little whitespace nonsense when we are bike shedding?

**Comment by tannergooding** [comment]
@jnm2, its "better" because some people prefer the syntax, probably (switch...when sounds better then switch...if -- but maybe only if you squint your ears) 💃

**Comment by jnm2** [comment]
I'm trying to tell if whether you're serious and it's just lost in translation to text :D
Who is going to refactor this

```c#
        if (gpa >= 4.0)
        {
            if (name == "Bob")
                Console.WriteLine("Okay, Bob, you win.");
            else
                Console.WriteLine($"{name} is a perfect student!");
        }
        else if (gpa >= 3.0)
            Console.WriteLine($"{name} is a pretty good student!");
        else
            Console.WriteLine($"{name} needs to work harder.");
        break;
```

To this?

```c#
        when gpa >= 4.0:
        {
            when name == "Bob":
            {
                Console.WriteLine("Okay, Bob, you win.");
                break;
            }
            when else:
            {
                Console.WriteLine($"{name} is a perfect student!");
                break;
            }
        }
        when gpa >= 3.0:
        {
            Console.WriteLine($"{name} is a pretty good student!");
            break;
        }
        when else: // or _ or whatever
        {
            Console.WriteLine($"{name} needs to work harder.");
            break;
        }
```

**Comment by tannergooding** [comment]
The same people who proposed this, most likely.

I personally prefer the former syntax (using `if..else`). But maybe that is because, the only time I use switch tables is when I know it will (could) get optimized to a jump table behind the scenes.

Maybe this is because I prefer new language features that make interop and performant code easier to write, rather than new syntax sugar that cuts down a few keystrokes.

**Comment by HaloFour** [comment]
@tannergooding 

> the only time I use switch statements is when I know it will (could) get optimized to a jump table behind the scenes.

The concept of extending pattern matching to `switch` came from the LDM so I'd suggest that said specific viewpoint on the statement is quite outdated.

In my opinion allowing for multiple `when` clauses has two benefits.  The first I already mentioned: it avoids having to repeat the pattern in subsequent `case` clauses.

The second is that it allows for the evaluation of the expression to continue matching against subsequent patterns if none of the guard clauses match:

```cs
class StudentAndProfessor : IStudent, IProfessor {
    public string Name { get; set; }
    public double Gpa { get; set; }
    public bool Tenured { get; set; }
}

var person = new StudentAndProfessor {
    Name = "Billy",
    Gpa = 2.8,
    Tenured = true
};

switch (person) {
    case IStudent { Gpa is var gpa, Name is var name }
        when gpa >= 4.0:
            Console.WriteLine($"{name} is a perfect student!");
            break;
        when gpa >= 3.0:
            Console.WriteLine($"{name} is a pretty good student.");
            break;
    case IProfessor { Name is var name, Tenured is var tenured}
        when tenured:
            Console.WriteLine($"{name} is a tenured professor.");
            break;
        when else:
            Console.WriteLine(${name} is an associate professor.");
            break;
}

// outputs: Billy is a tenured professor.
```

**Comment by mattwar** [comment]
There is one thing that is for certain:  Billy is doing better than Bob.

**Comment by tannergooding** [comment]
@HaloFour, my thinking is probably different (it generally is) :)

There are definitely benefits to new syntactic sugar and there are use cases for (mostly) all of the proposals that get put on the repo.

I'm just more interested (personally, and that doesn't matter much to anyone else) in things that actually benefit my code more than just new ways to write code.

I'm looking forward to `ref readonly`, `blittable`, and `static delegate` because they will improve the performance and reliability of my code.

I'm not so interested in things like this, because the IL (and even the actual native code) generated will be the same for the when pattern as for an if...else with pattern matching

**Comment by gafter** [comment]
Closing, as we're not going to do this. Please use if statements. Despite a claim to the contrary, folding this into the grammar is not simple, and the value is marginal.

**Comment by AustinBryan** [comment]
@MgSam 
> And unfortunately when will significantly hamper adoption because most developers do not like learning new ways of doing the same tasks they can already do.

C# adding new ways to do things we can already do is literally why it's hands down my favorite language, because the new ways are always *better* than the original way. Just look at all the ways properties evolves, and they just keep getting better and better. Speak for yourself.

> Of the 5 other C# devs I work with, I doubt any of them have even heard of exception filters.

What kind of argument is that? You only know 5 C# developers and you're just *assuming* they've never heard of exception filters? For all you know, they use them all the time, or they can't wait to find a chance to use them because they think they're a great idea.
