### ISSUE TITLE
[Proposal]: Relax restrictions on braces on interpolated raw strings.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/csharplang#5960]
The current interpolated raw string spec says:

> Here, the `{{...}}` matches the requisite count of two braces specified by the `$$` delimiter prefix. In the case of a single `$` that means the interpolation is specified just as `{...}` as in normal interpolated string literals. Importantly, this means that an interpolated literal with N `$` characters can have a sequence of `2*N-1` braces (of the same type in a row). The last `N` braces will start (or end) an interpolation, and the remaining `N-1` braces will just be content. For example:

This disallows strings like:

```C#
Console.WriteLine($"""{{3 + 4}}""");    // Error!
Console.WriteLine($"""{{{3 + 4}}}""");  // Error!
```

However, we could support both of those by just saying that the $ indicates the count of *innermost* braces needed for an interpolation.  Any additional braces would always be considered content.  In the above cases that would both legal and they would mean:

```C#
Console.WriteLine($"""{{3 + 4}}""");    // `{7}`
Console.WriteLine($"""{{{3 + 4}}}""");  // `{{7}}`
```

**Comment by 333fred** [comment]
Note that the original reason we didn't do this was potential conflicts with https://github.com/dotnet/csharplang/issues/3086, which is called out in the proposal.

**Comment by CyrusNajmabadi** [comment]
SO i'm not sure that applies here.  Expression blocks will need special handling no matter what either with raw-interpolated strings as they exist today, or with teh proposed change here.  In both cases, the block needs to be separated out (either with whitespace, or with parens).  (Or maybe i'm missing something.  please let me know!).

**Comment by CyrusNajmabadi** [comment]
@jnm2 can you add your case you thought was relevant?  Thanks!

**Comment by jnm2** [comment]
Sure.

1. Inserting whitespace between content braces and interpolation holes feels like a small thing to do, but under this new rule, the act of inserting a space or a newline would make the string stop compiling until you add more dollar signs.
   Starting with the proposed simplified form:
   ```
   $"""
   {{{expr}}}
   """
   ```
   Adding a content space causes a compile failure:
   ```
   $"""
   {{ {expr} }}
   """
   ```
   
   Conversely, if you remove characters so that all braces are immediately surrounding interpolation holes, tooling might prompt you to simplify by removing dollar signs. This sets you up for compile failures if you evolve the content back and forth. It also causes fluctuations in the git line history and takes your attention in both directions, the "simplify" prompt and the compile failure.
   
   The principle of being able to represent any content without escaping means that we are already satisfied with very similar situations that do require this many braces, such as:
   
   ```
   $$$"""
   {{ {{{expr}}} }}
   """
   ```

2. The current rule is that any time a run of braces appear in content, there must be a greater number of dollar signs. Changing this rule means placing an 'or' in the mental branch when I see braces around an interpolation hole. I have to look at it in potentially two different ways each time to interpret it. It's hard to know how much of a cost this will be without experiencing it.

3. How often will this really come up? The moment you have a content brace anywhere other than immediately surrounding an interpolation hole, you are forced to use a greater number of dollar signs and can't take advantage of this fewer-dollar-signs simplification. For example, cases like this can't make use of it due to the outer braces:

   ```
   $$"""
   {
       "foo": {{{expr}}}
   }
   """

I don't have an opinion about how these factors weigh out, but I assume the use case would have to be considered common enough *and* well worth it.

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks!

**Comment by 333fred** [comment]
Discussed in [LDM](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-11.md#relax-restrictions-on-braces-on-raw-interpolated-strings). This relaxation is rejected, the existing rules will stand as written.
