### ISSUE TITLE
[Proposal]: Self-constraint stopgap attribute

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#6000]
# Self-type stopgap attribute

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Introduce a `[SelfType]` attribute on type parameters. When instantiated as part of a base type or implemented interface, the corresponding type argument must be the deriving type itself.

## Motivation
[motivation]: #motivation

In [LDM-2022-03-28](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-03-28.md) we decided not to pursue a full-fledged self-type mechanism (such as [#5413](https://github.com/dotnet/csharplang/issues/5413)) for now, since we didn't have a fleshed out design and implementation strategy that would fully provide the expected semantics.

This leaves us with the challenge that the generic math interfaces will ship without being able to make use of a self-type feature, and all else equal will not be able to adopt one later without serious breaking changes.

This proposal anticipates a future self-type feature in the form of self *constraints* on type parameters. Such a feature would impose some requirements on deriving and implementing types in return for providing some expressiveness benefits (e.g. `this` would be implicitly convertible to a self-constrained type parameter).

The proposal allows an API to impose the expected requirements of a future self-type feature without providing the benefits. This may not seem like a good trade-off, but the idea is that application of the attribute *now* has a good chance of protecting current deriving and implementing types from a later break. Or in other words a new API (such as generic math) that uses the attribute now is likely to be able to adopt a future self-type feature without breaking its users.

## Detailed design
[design]: #detailed-design

We introduce the following attribute:

``` c#
[AttributeUsage(validOn: AttributeTargets.GenericParameter)]
public class SelfTypeAttribute : Attribute { }
```

It is applied to type parameters to signal that they are intended to function as a "self type" - i.e. be instantiated with the implementing type:

``` c#
public interface IAddable<[SelfType] TSelf> where TSelf : IAddable<TSelf>
{
    public static abstract TSelf Zero { get; }
    public static abstract TSelf operator +(TSelf o1, TSelf o2);
}
```

The attribute restricts derived and implementing types to only pass either themselves or a `[SelfType]`-marked type parameter of their own, as the type argument for the marked type parameter.

Specifically, if a type parameter `T` of a generic type `A<..., [SelfType] T, ...>` is marked with the `[SelfType]` attribute, then a type `B` that derives from or implements `A` must provide a type argument for `T` that is either

- one of `B`'s own type parameters that is also marked with `[SelfType]`, or
- the "instance type" of `B` itself, that is `B` with its own type parameters (if any) given as the corresponding type arguments.

``` c#
public interface ISubtractable<[SelfType] TSelf> : IAddable<TSelf> where TSelf : ISubtractable<TSelf> { ... } // Correct
public interface IDetractable<TSelfish>  : IAddable<TSelfish> where TSelfish : IDetractable<TSelfish> { ... } // Error
public class MyNumber : IAddable<MyNumber> { ... }    // Correct
public class WrongNumber : IAddable<MyNumber> { ... } // Error
```

In the above example, `ISubtractable<...>` passes a type parameter that is marked with `[SelfType]` and `MyNumber` passes itself. Both are allowed. On the other hand, `IDetractable<...>` passes a type parameter that is *not* marked with `[SelfType]` and `WrongNumber` passes a type that is *not* itself. Both are errors.

Other valid examples would include:

``` c#
public interface ICopyable<[SelfType] TSelf> { ... }
public interface IPerson : ICopyable<IPerson> { ... } // derived interface itself used as type argument
public abstract class Copyable<[SelfType] TSelf> : ICopyable<TSelf> { ... } // [SelfType] in non-interface type
public class Wrapper<T> : Copyable<Wrapper<T>> where T : Copyable<T> { ... }  // Instance type is itself generic
```

The attribute only has effect when the constructed type occurs as a base type or implemented interface. In all other places, the type argument is restricted only by the corresponding constraint.

A future full-fledged self-type feature may use the attribute as its metadata encoding,  add the attribute *in addition* to its metadata encoding, or leave it to APIs to manually apply the attribute if they want down-level protection.

## Drawbacks
[drawbacks]: #drawbacks

This is a half-measure. We hope it will protect current APIs for future self-type designs, but we can't be sure when we don't yet have those designs.

Down-level compilers will not respect the attribute (but the corresponding framework will not offer it either).

Other languages may not respect the attribute, and could circumvent the protection.

## Alternatives
[alternatives]: #alternatives

### Attribute name
The actual attribute name is ultimately a decision for API review.

### More relaxed rules for construction

The rules as described above cover the core scenarios, but may have some annoying edge cases. For instance, a derived class cannot reimplement an interface from a base class if that interface has a `[SelfType]`-marked type parameter:

``` c#
public class MySpecialNumber: MyNumber, IAddable<MyNumber> { ... } // Error
```

We could relax the rule so that the type argument only has to be something that the newly declared type *derives* from, not necessarily the newly declared type itself. In the above example, `MySpecialNumber` derives from `MyNumber` and would therefore be allowed to reimplement `IAddable<MyNumber>`.

### Restrictions on attribute application

As described above, `[SelfType]` can be applied to any type parameter, but we could choose to restrict it more narrowly around the scenarios where we plan to use it ourselves in the generic math interfaces. Specifically we could limit it to:

- only type parameters on types (not methods)
- only type parameters on interfaces (not other types)
- only type parameters that are constrained to the enclosing type (the "instance type")
- only the first type parameter

Of these, the first one is the only one that prevents something truly useless: A method is never inherited or implemented from, so the attribute would never have effect.

The other three all seem to limit possibly useful scenarios (self types on classes, self types that are more weakly constrained, self types that don't occur first in the type parameter list). The only reason to limit them would be to deliberately prevent broader use of the attribute: To make it more of a specific stopgap hack for our purposes, and less of a generally useful language feature in its own right.

### Analyzer

Instead of enforcing the self-type behavior of the attribute in the language and compiler, we could do it as an analyzer. The downside is that this may not provide sufficient confidence that all API users are protected by it.

## Unresolved questions
[unresolved]: #unresolved-questions

Which namespace should the attribute live in? Should it be more or less hidden away (as in `CompilerServices`)?

## Design meetings

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-03-28.md

**Comment by TahirAhmadov** [comment]
Re. "More relaxed rules for construction" section, I'm not sure that scenario is a valid one; my initial reaction is, do not relax the rules that way. 
Re. "Restrictions on attribute application", I think limits 1 and 3 make sense, and 2 and 4 don't.
Re. the attribute itself, since it's designed to be used directly, I think it should be under `System` namespace, and the name `SelfType` is perfect.

**Comment by tannergooding** [comment]
> I think it should be under System namespace, and the name SelfType is perfect.

Putting it in the `System.Diagnostics.CodeAnalysis` or `System.Runtime.CompilerServices`, where we put all the other compiler attributes, probably makes the most sense. I don't see API review putting this in `System` and which of the two previous namespaces it goes in probably depends on how "permanent" this feature is expected to be.

> Re. "Restrictions on attribute application", I think limits 1 and 3 make sense, and 2 and 4 don't.

If this isn't meant to be more permanent, then locking it down to the scenarios that are "core" for .NET 7 is likely "best" as it prevents accidental misuse or over-scoping.

The primary scenario for this proposal is specifically around some of the `generic math` APIs shipping in .NET 7. We want this so that the BCL can ship these interfaces before proper self type support exists and in a way that can allow the shipped BCL types to transition over to proper self types when the come. This specifically impacts `interfaces` with `static abstract` members. We will only have a single "self" type, named `TSelf`, and that is currently always the first parameter.

Ideally this only exists for 1-2 language versions and then we get "proper" self types and the attribute becomes a historical nuance that mostly just impacts the BCL and the handful of libraries doing the earliest adoption.

-------------

It's worth noting that .NET 7 isn't getting support for declaring `static abstract` in classes and you can't override a `static abstract` in a derived class (only directly in the class/struct that implements the interface). This somewhat limits the scenarios where a `TSelf` type parameter "makes sense" for .NET 7 and a good chunk of it comes down to operators and the CRTP (Curiously Recurring Template Pattern). 

This extends to interfaces dealing with `static abstracts` more broadly as well and doesn't apply to `instance` methods per-say (for .NET 7). When you consider `IEquatable<T>`, it exposes `Equals(T other)` and the `self ` type is (and always will be) restricted to `this`. Where-as for `IEqualityOperators<TSelf, TOther>` you get `static bool operator ==(TSelf left, TOther right)` where `TSelf` takes the concept of "this" for the `static method`.

There is of course some nuance, overlap, etc. However, the key is that we need to be able to expose these kinds of generic interfaces for .NET 7 as part of generic math and want to be able to extend them to support `self types` when that happens to come in the future. This means we need to be able to put some restrictions in place such as `MyInt32 : IAdditionOperators<int, int, int>` being invalid.

**Comment by 333fred** [comment]
Discussed in [LDM](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-11.md#self-type-stopgap-attribute). Language support for this attribute is rejected, and we will look at a standard BCL analyzer to prevent API misuse for the generic math interfaces.
