### ISSUE TITLE
Add m@ operator to C#

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/csharplang#608]
See http://mattwarren.org/2017/05/19/Adding-a-new-Bytecode-Instruction-to-the-CLR/ for more context.  Given that there are two @mattwar'ens, and the language is in core need of specialized support for this operator, we should add ```m@``` to the language.

**Comment by mattwar** [comment]
Would that be the tail-call operator?

**Comment by orthoxerox** [comment]
Make it an SBNZ, then you will be able to write Turing complete programs using only your own personal opcode.

**Comment by mattwarren** [comment]
> Would that be the tail-call operator?

Unfortunately it's nothing as fancy as that 😀

**Comment by mattwarren** [comment]
Nice,  @marcinjuraszek has already started work in it! 

See [Adding Matt operator to Roslyn - Syntax, Lexer and Parser](http://marcinjuraszek.com/2017/05/adding-matt-operator-to-roslyn-part-1.html)

**Comment by AdamSpeight2008** [comment]
Could we include this as tutorial in the Roslyn repo, as it provide example of how to extend the roslyn based languages. Rather than utilizing Roslyn to to analyze the language.

**Comment by MillKaDe** [comment]
Umm, no !

.. at least not in this incomplete, halfbaked and disharmonic way which contradicts decades if not centuries of musical notation. After all, this is about C# (sharp) and not about Db (flat).

Since the new `matt` bytecode instruction computes the maximum of its both operands, the correct operator is of course `M@` (major), while `m@` (minor) should compute the minimum of its operands.

*Adding the required other bytecode instruction is left as an exercise to the reader.*

For symmetry reasons, there should be left and right associative forms:

Operator|Example|Meaning
---|---|---
`M@`|`a M@ b M@ c`|`((a M@ b) M@ c)` // left associative maximum
`m@`|`a m@ b m@ c`|`((a m@ b) m@ c)` // left associative minimum
`@M`|`a @M b @M c`|`(a @M (b @M c))` // right associative maximum
`@m`|`a @m b @m c`|`(a @m (b @m c))` // right associative minimum

It also should be considered, whether implementing this would delay implementation of **really** important bytecode instructions like swapping the endianess of the CLR at runtime !

;-P

**Comment by svick** [comment]
@MillKaDe Why do you think associativity matters, considering that maximum and minimum are associative operations?

**Comment by mattwarren** [comment]
I know this issue was *tongue-in-cheek*, but it actually got me thinking:

- What's the criteria for adding binary operators to the language? Would a *real* Max/Min operator ever be considered (not `m@`), or does it not provide enough benefit over `x < y ? x : y` or `Math.Max(x, y)` 
- From a syntax point-of-view, could `m@` *actually* be added to the language (again, not saying it should :smile:) or does the presence of the `@` symbol cause some issues?

**Comment by svick** [comment]
> Would a *real* Max/Min operator ever be considered (not `m@`), or does it not provide enough benefit over `x < y ? x : y` or `Math.Max(x, y)`?

Well, how would you type it? If you wanted e.g. `` `max` ``, then have a look at https://github.com/dotnet/csharplang/issues/594. Also don't forget about `using static System.Math;`, which lets you write `Max(x, y)`.

> From a syntax point-of-view, could `m@` actually be added to the language […] or does the presence of the `@` symbol cause some issues?

I'm not sure. `m@w;` is already valid statement (declaring variable `w` of type `m`), but I don't know if there would actually be any ambiguity with binary operator `m@`.

**Comment by mattwar** [comment]
To get a new binary operator you'd have to get most of the design team very drunk.

**Comment by orthoxerox** [comment]
@mattwar what if we get them drunk and swap you with @mattwarren? By the time they notice the difference he'll implement m@ and push it to master.

**Comment by mattwar** [comment]
Except for PR check-ins needing code reviews with at least two other C# devs to sign off, that's almost a workable plan.

**Comment by alrz** [comment]
@mattwar thought the same when the scope leaked. but turns out it wasn't that bad. score!

**Comment by mattwarren** [comment]
> To get a new binary operator you'd have to get most of the design team very drunk.

@mattwar does that mean that check-ins are disabled during your Christmas party, just in case :smile:

**Comment by mattwar** [comment]
@mattwarren and every Friday afternoon.

**Comment by YairHalberstadt** [comment]
😆
