### ISSUE TITLE
Has the csharplang repo failed?

### ISSUE THREAD

**Issue by DavidArno** [dotnet/csharplang#621]
> Welcome to the official repo for C# language design. This is where new C# language features are developed, adopted and specified.
...
> If you want to suggest a feature, discuss current design notes or proposals, etc., please open a new issue, and it will be tagged Discussion.

In the last two weeks, 35 discussion issues have been opened.  Just three have been tagged.

Being the "official repo for C# language design", one might reasonably expect active participation by the LDT in those discussions. @CyrusNajmabadi is definitely an active participant and enthusiastically discusses many issues. @gafter and a couple of others very occasionally pop in and comment. But that's it really. So it appears that the LDT don't really have much interest in this repo. Whilst lots of folk come here and post their ideas on how C# could be changed and approved, these suggestions largely appear to be ignored by the team. This seems odd given it's supposed to be the official repo for their language. 

The team regularly hold language design meetings and this repo is supposed to be the place where those meetings are recorded. Yet there have been no meeting updates for over a month and even then, the newer commits are self-declared rough notes that still need updating.

But the thing for me that really makes me wonder what the point to this repo is the pull requests. I noticed a broken link in the version history page and submitted a PR for it. Out of curiosity I then looked at the other open PR's. Over a week ago, @mshahrouri submitted the same tiny-change PR, yet it remains open, with no comments from the team. There is even a simple PR from @gafter from nine days ago sitting there ignored by the rest of the team.

All of this leads me to ask the obvious question: has the team abandoned this repository?

**Comment by yaakov-h** [comment]
"abandoned" implies they were here in the first place. Were they? I don't think I've seen anyone beyond Cyrus and Neal.

**Comment by orthoxerox** [comment]
Well, I've seen Matt as well as a few more team members, but their presence was rather low-key compared to Cyrus and Neal.

**Comment by alrz** [comment]
I think we won't see anything more than already championed proposal for the next couple of years (which is fair because that's quite a list on its own). Absent of proposals for the said features, I don't really see anything else to discuss at this point.

**Comment by MgSam** [comment]
Build just happened and from following the language design since it was open sourced my impression is that no work seems to happen immediately before Build (preparing for the conference) or for a few months after (LDM members go on vacation and they cancel most of the meetings).

As for team members participating here- we've complained about that before but it's pretty clear that's not going to change. Whether we like it or not, 99% of the language design process has and always will occur in Redmond behind closed doors. From talking to the language guys at Build, I don't think most of them read community suggestions at all, to be honest.

To be fair to the language team, this is pretty standard across all the teams at Microsoft that are supposedly open-source and community driven. I think they're more interested in the positive PR of being open-source than actually implementing it.

On the positive side, I'm very happy the team is finally going to increase the cadence of language releases and am looking forward to 7.1. I'm hopeful the plan is for C# 8.0 to come out in 2018 rather than waiting 3 more years. C# needs a faster release cadence if its going to remain relevant.

**Comment by whoisj** [comment]
I think it is very successful, it moved the noise out of the development repositories to here. 😏

**Comment by MgSam** [comment]
> I think it is very successful, it moved the noise out of the development repositories to here. 😏

:laughing: At least you're honest about it!

**Comment by CyrusNajmabadi** [comment]
As Mads said explicitly:

> We will continue to empower the broader ecosystem and grow its role in C#’s future, while maintaining strong stewardship of design decisions to ensure continued coherence.

We actually read and review a lot of the stuff here.  But we still make the decisions ourselves as to what we'll do about it.

-

Also note: we don't develop the language in a vacuum.  i.e. the LDM isn't an independent body that just goes and continually revs things and publishes a new spec as fast as we can.  We keep pace with the compiler and IDE and the releases therein.  That means we spend our time on the issues that are currently highest priority for those products as we don't want to block them.  Other things will not get attention because, guess what, our attention is fully booked on the substantial and serious issues we're trying to get through with existing language features we're taking on.

-

Also note: people take vacations.  We just had build.  There was a ton of preparation and work that had to happen for that.  Most LDM members are engineers (including myself).  Every engineer is booked completely solid on actually being able to finish and deliver the features and work that we've signed up for.  

-

Finally, i think the csharplang repo is awesome.  Tons of great ideas and discussions going on.  But please recognize that focus and priorities wax and wane over a product cycle.  Right now we are not 'deep in language design mode'.  We're deep in 'ship the product that people want yesterday' mode.  When pressure for that lightens up you'll see much more of the swing toward discussion/prototyping/picking-features/etc.

**Comment by shaggygi** [comment]
@CyrusNajmabadi thank you and team for the work you do.
