### ISSUE TITLE
Overloading local function with same name as enclosing function

### ISSUE THREAD

**Issue by dotjpg3141** [dotnet/csharplang#633]
Overloading local function with same name as the enclosing function gives a compiler error:

```cs
class Program
{
	static int Sum(int value)
	{
		int Sum()
		{
			return Sum(value - 1);
		}
		return value + Sum();
	}
}
```

**Expected behaviour:**
It compiles

**Actual behaviour:**
CS1501: No overload for method 'Sum' takes 1 arguments.

If I rename the local function to something other than `Sum` it will compile.

**Comment by jnm2** [comment]
Also: if you can name the function the same as the enclosing function, why can't you name a parameter or local the same as a parameter or local in the enclosing function?

I'm already running into this. I think shadowing local and parameter names from the enclosing function should be just as possible as shadowing class field names. It's more convenient, especially for those times when you want to explicitly pass locals into the local function rather than magically referencing them via a closure.

**Comment by svick** [comment]
I believe this is the expected behavior right now. Local functions don't behave like methods that can be overloaded, they behave like local variables. And if you have a local variable that has the same name as the enclosing method, only the local variable can be directly referenced.

If you're looking for a workaround, you could use `Program.Sum(value - 1)`.

**Comment by DavidArno** [comment]
A simpler work-around is to use camelCase for local function names:
```cs
class Program
{
    static int Sum(int value)
    {
        int sum()
        {
            return Sum(value - 1);
        }
        return value + sum();
    }
}
```
