### ISSUE TITLE
Locals and parameter shadowing in local functions

### ISSUE THREAD

**Issue by jnm2** [dotnet/csharplang#634]
I'm running into a need to name a local function parameter the same as a local from the containing method. Shadowing local and parameter names from the enclosing function should be just as possible as shadowing class field names.

It's more convenient than having to make up new names when there is legitimately nothing to add to the name in that context, especially for those times when you want to explicitly pass locals into the local function rather than magically referencing them via a closure.

It's also an amazing safeguard preventing you from accidentally referring to the outer local instead of the local function parameter, which can change the meaning of the program.

**Comment by svick** [comment]
Previous discussion about this: https://github.com/dotnet/roslyn/issues/15793. It was closed by @gafter:

> The LDM […] are concerned that permitting this may make it too easy to introduce bugs, so we do not intend to move forward with this as a championed proposal. The original motivaring example can be [re]written [in a way that] does not cause any additional allocation compared to the requested feature.

**Comment by jnm2** [comment]
Thanks @svick.

**Comment by alrz** [comment]
Revised for C# 8.0. ([notes](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-09-10.md))

**Comment by agocke** [comment]
Yup, this is officially back on the table. I'll champion it.

**Comment by CyrusNajmabadi** [comment]
Small piece of feedback.  this was one of the rules we had to turn off in our TypeScript linter because it just blocked such a useful coding pattern. i.e. you'd have:

```typescript:
const users = getUsers();
const prices = getPrices();
await Promise.all([users, prices]).then(([users, prices]) => {
    // ...
});
```

Here we want the inner lambda (which contains a deconstruction), to just be able to reuse those names inside the body.  And, we actually do want the inner lambda to hide the outer values.  Having to name these things differently is actually just annoying, and unhelpful.  i.e.

```typescript:
const usersPromise = getUsers();
const pricesPromise = getPrices();
await Promise.all([usersPromise, pricesPromise]).then(([users, prices]) => {
    // ...
});
```

it's just so unweildy and non-idiomatic. 

--

So, tldr, i def support this because i actually think it's a reasonable and sensible coding pattern to *want* to hide the locals (to prevent captures) and to want to name the parameters the exact same as the passed in variables.

**Comment by CyrusNajmabadi** [comment]
Note: i know the above is aobut local functions, not lambdas.  But the same arguments applied for us for local functions as well.  So definitely 👍 on this.

**Comment by alrz** [comment]
> i know the above is about local functions, not lambdas.

This has been considered under static local functions but notes state that if it gets implemented it should be applied to lambdas as well as local functions whether it's static or not, precisely because the inconsistency doesn't do any good.

**Comment by alrz** [comment]
Ah right, thanks for clarifying.
