### ISSUE TITLE
adding a base record for exception

### ISSUE THREAD

**Issue by Mr0N** [dotnet/csharplang#6670]
I suggest adding a base record for exception
Similar to this https://github.com/Mr0N/CustomExceptionRecords

**Comment by Mr0N** [comment]
> 



> The limitation is that C# does not allow records to extend from non-records (other than `System.Object`), but all exceptions must extend from `System.Exception`. I would imagine that if the language team were to revisit this they would do so through lifting the limitation on inheritance in general vs. doing something general purpose for exceptions.
> 
> See: https://github.com/dotnet/csharplang/blob/f856ab390d974896079905ef38479e00a54c5025/meetings/2020/LDM-2020-06-22.md#inheritance-between-records-and-classes

The limit as it is now is normal, it is not easier to just write it in the il code as it is now, this is one class that will not change

**Comment by Mr0N** [comment]
And for one thing, add the il code project to the studio.

**Comment by Mr0N** [comment]
> This is why I'm suggesting that if this is considered that it would be addressed by lifting the limitation, allowing records to extend from other arbitrary classes. Then a record could extend from `System.Exception` directly. It wouldn't be trivial, but it's much more likely to happen than to have a new base exception class.

It's bad, it's better to change the programming language, or to write one class in il, which is easier?

**Comment by HaloFour** [comment]
Either way the programming language would change because `RecordException` would have to derive from `Exception`, which is not legal in C#.  But by adding that one class all you've done is split the exception hierarchy since these record exceptions cannot extend from any of the common base exceptions defined in the BCL, like `ArgumentException` or `IOException`.

**Comment by Mr0N** [comment]
> 



> Either way the programming language would change because `RecordException` would have to derive from `Exception`, whic

Yes, but from this record, only records will be followed, it will have a base class Exception, the programming language at the C# level is not affected, because it is written in il code, a basic record for errors just appears.

**Comment by Mr0N** [comment]
> extend from any of the common base exceptions defined in the BCL, like `ArgumentException` or `IOException`.

I don't see the point of them imitating records, in fact a base class for records is needed to reduce the routine of writing classes for errors

**Comment by HaloFour** [comment]
> Yes, but from this record, only records will be followed, it will have a base class Exception, the programming language at the C# level is not affected, because it is written in il code, a basic record for errors just appears.

The BCL is written in C#, if C# doesn't allow it then it won't end up in the runtime.  They have already closed your suggestion of adding a new base exception class as something they won't do.

> I don't see the point of them imitating records, in fact a base class for records is needed to reduce the routine of writing classes for errors

Which just makes them that much less useful.

**Comment by Mr0N** [comment]
> The BCL is written in C#, if C# doesn't allow it then it won't end up in the runtime. They have already closed your suggestion of adding a new base exception class as something they won't do.
> 
> >

![image](https://user-images.githubusercontent.com/61237140/200610444-723ef6bc-58d2-494b-99b6-36af951e102c.png)

**Comment by HaloFour** [comment]
@Mr0N 

You'll also notice this:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/10102290/200610781-a3fa1130-477c-46e5-9987-1100f4159658.png">

They've already stated that this is a language concern, and as a language concern the possible solution would be to lift the limitation on extending non-records.

The runtime team has expressed being not interested in writing custom IL for specific APIs that cannot be expressed in C#, such as defining helper methods that used `System.Delegate` or `System.Enum` constraints.

**Comment by Mr0N** [comment]
https://github.com/dotnet/runtime/blob/d459c65324aa3387252d480781e9c7ea6f934231/src/tests/JIT/opt/JitMinOpts/Perf/BBCnt1.il

**Comment by Mr0N** [comment]
> 



> @Mr0N
> 
> You'll also notice this:
> 
> <img alt="image" width="441" src="https://user-images.githubusercontent.com/10102290/200610781-a3fa1130-477c-46e5-9987-1100f4159658.png">
> 
> They've already stated that this is a language concern, and as a language concern the possible solution would be to lift the limitation on extending non-records.
> 
> The runtime team has expressed being not interested in writing custom IL for specific APIs that cannot be expressed in C#, such as defining helper methods that used `System.Delegate` or `System.Enum` constraints.

well, I don't know, well, maybe it's a problem of the programming language that needs to be implemented on the il code, just tell me to allow them to do it.

**Comment by stephentoub** [comment]
You're trying to use a feature of the C# language: records.  You don't like a limitation of that C# feature: records currently can't derive from non-records.  The fix isn't to special-case a single base type in the core libraries and hack it outside of C# to work-around the designed C# constraint for that one case.  You're asking for a custom Exception base type, but there are thousands and thousands of other classes that folks might similarly want as a base type for a record; Exception is not special in that regard.  Thank you for your suggestion, but we're not going to add such a type to the base libraries.

In the meantime, you've hacked up an approach in IL that works for you, since you're asking us to replicate what you've done.  You're obviously free to use that as a helper in your own projects, and even to publish a NuGet package for others to consume if you believe it's so impactful.  In the meantime, I'd encourage you to have the conversation at the language level about lifting the constraint, and more importantly, how to address the holes that constraint is there to prevent.

Thanks.

**Comment by Mr0N** [comment]
> You're asking for a custom Exception base type, but there are thousands and thousands of other classes that folks might similarly want as a base type for a record;

well, they won't be able to do it (it's good, because these are fundamentally different things, I just don't see the second solution), this record will be an ordinary record, besides, it will be accepted by throw
