### ISSUE TITLE
[Proposal]: Make generated `Program` for top-level statements public by default

### ISSUE THREAD

**Issue by captainsafia** [dotnet/csharplang#6769]
At the moment, when users leverage top-level statements that generated assembly contains a `Program` class that is `internal` by default.

```csharp
Console.WriteLine("Hello world!");
// produces

[CompilerGenerated]
partial class Program
{
    private static void <Main>$(string[] args)
    {
      Console.WriteLine("Hello world!");
    }
}
```

This default behavior presents a cliff when users building apps using top-level statements try to:

- Reference their entry point from an assembly containing integration tests (`public class IntegrationTests: IClassFixture<TestWebApplicationFactory<Program>>`)
- Loading the program from a library or CLI tool like the [swagger-gen tool](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/src/Swashbuckle.AspNetCore.Cli))

To workaround this limitation, users can either:

- Add `public partial Program {}` to their application to override the default visibility
- Configure accessibility to the `Program` type via IVT

The workarounds add friction to the experience, especially considering that [most people are using the `public` modifier](https://grep.app/search?q=public%20class%20Program&filter[lang][0]=C%23) in apps that use Program.Main, compared to the use of the [`internal` access modifier](https://grep.app/search?q=internal%20class%20Program&filter[lang][0]=C%23). Also, a majority of the templates use configure visibility for the `Program` class to public when `--use-program-main` is enabled.

AFAIK, there are no technical gotchas with making the type public by default so it seems like a sensible quality-of-life improvement.

### Discussions

https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-12-14.md#program-as-internal-by-default
https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-10-09.md#make-generated-program-for-top-level-statements-public-by-default

**Comment by CyrusNajmabadi** [comment]
> AFAIK, there are no technical gotchas with making the type public by default so it seems like a sensible quality-of-life improvement.

There's definitely a gotcha that this now may expose things to the public surface area of the binary that weren't exposed before.  I'm not personally comfortable with that.  I think top level programs are opinionated. If you want to break out of that, being explicit seems appropriate to me :-)

**Comment by yaakov-h** [comment]
Personally, I feel that since something outside of this assembly's code is invoking the `Main()` function, it's effectively public anyway and should be marked as such. It feels odd that the OS/runtime gets to call Main but my own tests can't.

I would hope though that only the class and method become public, and anything else declared remains at its current effective visibility.

**Comment by HaloFour** [comment]
@yaakov-h 

> Personally, I feel that since something outside of this assembly's code is invoking the `Main()` function, it's effectively public anyway and should be marked as such. It feels odd that the OS/runtime gets to call Main but my own tests can't.

I don't think an entry point is the same as an explicitly public API.  The former is more an implementation detail, and doesn't imply that the assembly should be referenced externally and have that member invoked directly by an arbitrary assembly.  That said, if that's what _you_ want to do, you could always declare them as `public`.

**Comment by 333fred** [comment]
> ```cs
> Console.WriteLine("Hello world!");
> // produces
>
> [CompilerGenerated]
> internal class Program
> {
>     private static void <Main>$(string[] args)
>     {
>       Console.WriteLine("Hello world!");
>     }
> }
> ```

Not quite. What it produces is

```cs
class Program
{
    private static void <Main>$(string[] args)
    {
      Console.WriteLine("Hello world!");
    }
}
```

We did this very intentionally, so that user can control the accessibility of the type. If we instead said that produced `public class`, that partial part has now explicitly changed the visibility of the type and other partial parts can't change it. We'd then have to make special rules for the default accessibility handling of top-level statements, and we didn't want to do that. See https://github.com/dotnet/csharplang/blob/8b16686a5355241bbad7c1797b2fd4359d28c7c2/meetings/2021/LDM-2021-07-12.md#speakable-names-for-top-level-statements

**Comment by yaakov-h** [comment]
Does this actually need a language change, or could the SDK (optionally, or default-on) emit a new file that contains `public partial class Program { }`, like it emits many attributes?

**Comment by HaloFour** [comment]
I could be controlled via a source generator that spits out `partial class Program` with the desired accessibility level.

**Comment by pinkfloydx33** [comment]
I personally don't find the motivating examples especially compelling. 

> `WebApplicationFactory`

`WebApplicationFactory<TEntryPoint>` only uses the generic argument to retrieve the `Assembly` (or things derived from the assembly). One can use _any_ type in their project; it's not required to use the entry point class.

I suppose if you are using minimal APIs and stuff *everything* into the entry point without declaring _any_ types in the project that this can be a problem. Outside of samples and the most basic apps, is that the common case? 

> CLI tool like the swagger-gen tool

Swagger CLI is already using `HostFactoryResolver`. Sure, they support other models that involve specially named methods whose implementations would likely need to invoke code in the Program class... but that's a relic of a time when the Resolver wasn't available. While it does allow you to customize the host specially for swagger, I'd argue if you _really_ needed it then it's truly a special case and you shouldn't use top-level statements. We were in this bucket and found a way to migrate.

Are impacted CLI tools interested in anything other than the Host/Services? If so, I guess I can see a need... but otherwise making it easier to consume the resolver sources seems like the better plan (but an issue for elsewhere). 

An SDK option to set accessibility, while not a language change, doesn't seem like a gain of any sort. Take this hypothetical SDK property:

```xml
<PropertyGroup>
   <EntryPointAccessibility>public</EntryPointAccessibility>
</PropertyGroup>
```
How's that any better than this:

```csharp
var bldr = WebApplication.CreateBuilder();
// ... rest of top-level statements 

public partial class Program { }
```

If you need to add attributes (`SuppressMessage` for example), you're going to have to do this anyways. Even if you don't, I'd still prefer the latter so that all the code was _in code_ and not a magical property I might have to be aware of or take into account.

**Comment by davidfowl** [comment]
> An SDK option to set accessibility, while not a language change, doesn't seem like a gain of any sort. Take this hypothetical SDK property:

We'd add it by default in ASP.NET Core projects.

**Comment by captainsafia** [comment]
To close the loop on this, the ASP.NET Core is shipping a source generator in .NET 10 that implements the alternative solution of emitting the `public partial class Program { }` declaration without polluting user code.

The most notable limitations with this solution are that it is only supported for ASP.NET Core projects that will target net10 and above. Alternative solutions will still be required for non-ASP.NET Core projects and those that don't target .NET 10.

Since .NET 10 won't be released for another year, workarounds will still be necessary but for now there's no requirement to change compiler behavior to solve this problem.

I'll close the issue out for now but we can re-kick this discussion if newer scenarios come up that don't have accessible alternatives.
