### ISSUE TITLE
property_initializer clause is missing the ; token at the end

### ISSUE THREAD

**Issue by gzak** [dotnet/csharplang#684]
I've recently had to implement some logic to generate a class with a `property_initializer` clause in some of its `property_declaration`s, and I noticed that there's no way to close out the clause with a `;` token with the Roslyn `SyntaxFactory.PropertyDeclaration` API. I came back here to the spec, and sure enough, there's no `;` in the language spec at the end of a `property_initializer` clause, which is actually required.

Or am I just going crazy? Halp!

**Comment by gzak** [comment]
Actually I found my answer, there's one more overload for that API which takes the semicolon token as the final parameter.

That said, the point still stands: according to the spec, I don't see the required `;` called out.

**Comment by svick** [comment]
I think there are two separate issues:

1. [The spec](https://github.com/dotnet/csharplang/blob/dcabca1/spec/classes.md#properties) says that `property_initializer` does not require semicolon. I think that's a bug in the spec and that fixing it by creating a Pull Request on this repo would be fine. Do you want to create that PR?
2. When using the Roslyn API and creating a `PropertyDeclarationSyntax` with `initializer`, you have to explicitly specify the semicolon token. If you think this is a problem, you should open an issue on [the Roslyn repo](https://github.com/dotnet/roslyn) and not here. But I doubt this is going to improve, since it would be a breaking change.

**Comment by gzak** [comment]
I'd be more than happy to submit that PR, just as soon as I get some time.

**Comment by BillWagner** [comment]
The standard text has the correct grammar (including the necessary semicolon.)

@333fred I think this should be closed.  Unless you think something should happen for (2) above that @svick commented on.

**Comment by 333fred** [comment]
I don't believe there's anything to do, so I'll close this out.
