### ISSUE TITLE
Expand lambdas and method body definitions to allow any block like statements

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/csharplang#6887]
### Discussed in https://github.com/dotnet/csharplang/discussions/6885

<div type='discussions-op-text'>

<sup>Originally posted by **br3nt** January 15, 2023</sup>
This proposal has come about because @CyrusNajmabadi has pointed out that the proposal from #6870 can be generalised to include all blocks.

The proposal is that lambdas and method body definitions be expanded to include block like statements such as selection statements (`if`, `switch`), iteration statements (`while`, `do`, `for`, `foreach`), `try`/`catch`/`finally` statements, `checked` and `unchecked` statements, `lock` statements, and `using` statements, and anything else that may fit in this category.

The general pattern being considered is:

```c#
public void Example() =>
    <block-statement>
```

and

```c#
public void Example()
{
    var list = new List<int>();

    var mapped = list.Select(i =>
        <block-statement>
    );
}
```

and

```c#
Func<int> example = () =>
    <block-statement>
```

Lets consider some examples using some of the block statement keywords just to get an idea...

#### `if/else`

Or,
```c#
public void MethodIf() =>
    if (condition)
    {
        // code
    }
    else
    {
        // ...
    }
```

Or, 

```c#
public void MethodIf() => if (condition) // code
```

Or,

```c#
collection.Select(innerArray =>
    if (condition)
    {
        // code
    }
    else
    {
        // ...
    });
```

Or,

```c#
Func<int> example = () =>
    if (condition)
    {
        return 1;
    }
    else
    {
        return 2;
    });
```

#### `for`

```c#
public IEnumerable<string> MethodForEach() =>
    for (var i = 0; i < 10; i++)
    {
        yield return i * 2;
    }
```

Or,
```c#
public IEnumerable<string> MethodForEach() => for (var i = 0; i < 10; i++) yield return i * 2;
```

Or,
```c#
Func<int> example = (count) =>
    for (var i = 0; i < count; i++)
    {
        yield return i * 2;
    }
```

Or,
```c#
Func<int> example = (count) => for (var i = 0; i < count; i++) yield return i * 2;
```

Hopefully, that's enough examples to get the idea.

It might be worthwhile to also consider implicit returns, like what is being done with the switch expression, but I'm not sure if that would work in all cases. I think the return and yield return works just fine.
</div>

**Comment by TheUnlocked** [comment]
This looks weird to me. For the `finally` case I would prefer #513, and for the general case I just don't really see the value in saving two characters, sometimes. Unless there's an even broader change to expression-ify everything that something like this would naturally fall out of (though given that the switch statement and expression don't look the same, I suspect there won't be).

**Comment by br3nt** [comment]
@TheUnlocked Here are some discussion points copied from https://github.com/dotnet/csharplang/discussions/6885 that I think are relevant to your comments.

> Is the sole point of this just saving 2 brackets solely in case of single statement?

Sure, but it's more nuanced than that. It's about the nicer development experience that comes from that. That je ne sais quoi. https://youtu.be/gls09kO-8DE.

This adds subtle flexibility, to existing language features that could help to improve how code is written. Some other benefits are discussed below.

> Since it's introduction I've seen developers write convoluted code in order to needlessly make a [expression body] method a single expression.
> If the plan is to make C# a more functional language they maybe focus on more functional feature (like discriminated unions) rather than needless changes like this.

This proposal isn't making C# more functional, rather it's enhancing and improving the current functionality.

"Since it's introduction I've seen developers write convoluted code in order to needlessly make a method a single expression" is a really good answer to why this isn't just a "needless change".

It adds the something that is missing from expression-bodied members. It adds a nice syntax that brings many more language structures to lambdas and method body expressions.

Sure, we can already use any of all these structures by introducing a block with { and }, but as you said, why would a dev prefer this over "reformat from an expression-bodied member to a regular method"? So they make a choice to either refactor or make the statement more complex and convoluted to fit.

This proposal is a nuanced and subtle improvement, rather than in your face. It's an obvious evolution that improves the dev experience and enhances the existing language features. It will likely have a big impact on how devs write code because as you said, currently, "developers write convoluted code in order to needlessly make a method a single expression". This proposal will go a long way to help alleviate that issue.

> For the finally case that originally inspired this I would prefer https://github.com/dotnet/csharplang/discussions/513

In the original discussion, https://github.com/dotnet/csharplang/discussions/6870, it was made clear that the community prefers explicitness.  Also, a more generalised solution was requested.  So this new proposal is the more generalised solution and suggests a nicer syntax compatible with existing code.

I could be wrong, but I think the discussion of "expressionifying" all the existing block statements should be a separate discussion to this.  Also, it is not incompatible.  It seems like this process of expressionification would need to be a case-by-case process, otherwise, this would have been done at the same time as the `switch` expression.  @CyrusNajmabadi CC's a couple of people in the discussion to weigh in on that.

The benefit this proposal has is that it can easily apply to all existing blocks without needing to change the syntax of the block or without requiring an expression form of the block.

**Comment by TheUnlocked** [comment]
@br3nt 
> Here are some discussion points copied from https://github.com/dotnet/csharplang/discussions/6885 that I think are relevant to your comments.

I know, I've skimmed through those discussions already. I just disagree that it makes anything more readable or will encourage people to write more readable code. Rather, I think it makes it harder to read (plus it introduces weirdness around expression-bodied members being able to take either expressions or statements, but _not_ blocks).

>> For the finally case that originally inspired this I would prefer #513
> 
> In the original discussion, #6870, it was made clear that the community prefers explicitness.

Huh? I don't see #513 or the `defer` statement mentioned anywhere there.

> I could be wrong, but I think the discussion of "expressionifying" all the existing block statements should be a separate discussion to this.

I agree. I was saying that I would only want this if it naturally fell out of a feature like that since not allowing it would be weirder (like how `void Foo() => {};` should be legal if expression blocks were implemented, even though writing code that way would be silly).

**Comment by br3nt** [comment]
> I just disagree that it makes anything more readable or will encourage people to write more readable code

Sure.

> plus it introduces weirdness around expression-bodied members being able to take either expressions or statements, but not blocks

What is your meaning of "block" here?  When I say "block", I think of code between `{` `}`, as per the first dot point mentioned [here](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#statements).

In this regard, lambdas and expression body members already support blocks.  So, it just seems natural, to me at least, to also to extend this to include "block-like" statements.

>>> For the finally case that originally inspired this I would prefer https://github.com/dotnet/csharplang/discussions/513
>> In the original discussion, https://github.com/dotnet/csharplang/discussions/6870, it was made clear that the community prefers explicitness.

> Huh? I don't see https://github.com/dotnet/csharplang/discussions/513 or the defer statement mentioned anywhere there.

Sorry, I wasn't meaning that as an isolated statement.  I was just trying to provide context the the following statements.  I wasn't trying to respond directly to your comment about the `defer` keyword, as I think that discussion fits better in the "expressionify statements" discussion.

But, I was also tying to make the point that this discussion and "expressionify statements" discussion aren't inherently incompatible or mutually exclusive.

**Comment by CyrusNajmabadi** [comment]
> to also to extend this to include "block-like" statements.

I'm operating under the view this would support any statements

**Comment by TheUnlocked** [comment]
> In this regard, lambdas and expression body members already support blocks.

Expression-bodied members do not support blocks. E.g. this is not legal code today:

```cs
int Foo() => { return 1; };
int Bar => { return 1; };
```

> So, it just seems natural, to me at least, to also to extend this to include "block-like" statements.

I don't view if/for/foreach/while as being "block-like," I view them as being ordinary statements like any others, except that they can contain a child statement (which could be a block, if desired).

**Comment by br3nt** [comment]
> Expression-bodied members do not support blocks. E.g. this is not legal code today

Oh, silly me!  I thought they were already supported.  Then yes, this proposal should include blocks too, at least from my perspective.  @CyrusNajmabadi probably has an opinion on this, and the agility  update the description if needed.

> I don't view if/for/foreach/while as being "block-like," I view them as being ordinary statements like any others, except that they can contain a child statement (which could be a block, if desired).

Semantics... it's just my language not matching yours (or the technical terms).

I think its clear enough what the proposal is suggesting, both through the description and the examples given.  Basically to support as many things in this list [here](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#statements) as is possible.  As @CyrusNajmabadi say, "I'm operating under the view this would support any statements".

The issue description  can easily be updated by @CyrusNajmabadi to be more clear if it is a common source or issues and misunderstandings.

**Comment by MgSam** [comment]
I'm confused about this example:

``` C#
Func<int> example = () =>
    if (condition)
    {
        return 1;
    }
    else
    {
        return 2;
    });
```

What is the the closing parenthesis doing there? Is that a typo or am I missing something? 

And how could you possibly parse this unambiguously without curly brackets? 

``` C#
int Foo() {
    Func<int> bar = () =>
        if (condition) return 1;
        Console.WriteLine("baz");
    return 3;
    return 0;
}
```
Does Foo() return 3 or return 0?

**Comment by CyrusNajmabadi** [comment]
@MgSam there's no 'else' in your example. So the 'if' finishes at 'return 1;'

**Comment by MgSam** [comment]
Ah, ok, so this allows exactly one non-expression statement.

**Comment by HaloFour** [comment]
@CyrusNajmabadi 

> there's no 'else' in your example. So the 'if' finishes at 'return 1;'

Should that even be allowed to compile?

**Comment by MgSam** [comment]
This seems like it will exacerbate the "dangling if" problem- eg, the reason many teams require all `if`s to be blocks. 

I'd much prefer just allowing blocks everywhere expressions are currently allowed and possibly having an implicit return on the final statement.

**Comment by 333fred** [comment]
The completely ambiguous version;
```cs
int Foo(bool b) {
    if (b) 
        Func<int> bar = () =>
            if (condition) return 1;
                Console.WriteLine("baz");
    else
        return 0;
}
```

**Comment by CyrusNajmabadi** [comment]
Sure. But we'd certainly handle dangling-else consistently here (like we do in a normal block). It always parses into the immediately preceding 'if'

**Comment by HaloFour** [comment]
I have to agree with Bjarne here:

> There seems to be no reason to allow these ambiguities even if there is a trivial and systematic way for a
parser to chose one interpretation over another.

**Comment by CyrusNajmabadi** [comment]
We're not going to go ahead with this.
