### ISSUE TITLE
Allow 'not' generic type constraints

### ISSUE THREAD

**Issue by bgribaudo** [dotnet/csharplang#707]
Looking at this repository's list of issues, there are a lot of ideas relating to generics. Here’s another one to add to the mix.

## Motivation
If a developer wants to provide method overloads handling specific type parameter cases along with a more general ‘catch all’ overload, it can be tricky to get the complier to resolve to the intended specific type case overload.

For example, the intention below is that the `AsSomething()` call on the nested array be resolved to the first extension method. However, the C# complier resolves it to the second method.

```
static class MyExtensions
{
  public static void AsSomething<T>(this IEnumerable<IEnumerable<T>> arg) { }
  public static void AsSomething<T>(this IEnumerable<T> arg) { }
}


// Intention: Resolves to AsSomething<T>(this IEnumerable<IEnumerable<T>> arg)
// Actuality: Resolves to AsSomething<T>(this IEnumerable<T> arg)
new[] { new[] { 1 } }.AsSomething();

// Intention & Actuality: Resolves to AsSomething<T>(this IEnumerable<T> arg)
new[] { new { FirstName = "Joe", LastName = "Smith" } }.AsSomething();
``` 

(Based off a real-world situation adapting `IEnumerable<T>`s to `IDataReader`. Each item in the enumerable became a data reader record. If `T` was itself an `IEnumerable<>`, the items in the inner enumerable become the values of the data reader’s fields. Otherwise, `T`'s publicly readable instance properties become the data reader’s field values. Unfortunately, using a pair of overloads similar to the above didn’t work due to the way the complier handled resolution.)

## Idea 
Allow more influence over the overload resolution process by indicating that a certain type parameter must not match a given constraint. This could be achieved by allowing the type constraint list to contain `not` constraints. 
```
static class MyExtensions
{
  public static void AsSomething<T>(this IEnumerable<IEnumerable<T>> arg) { }
  public static void AsSomething<T>(this IEnumerable<T> arg) where T : not IEnumerable<> {} // <-- use of not constraint
}


// Resolves to AsSomething<T>(this IEnumerable<IEnumerable<T>> arg)
new[] { new[] { 1 } }.AsSomething();

// Resolves to AsSomething<T>(this IEnumerable<T> arg) where T : IEnumerable<> {}
new[] { new { FirstName = "Joe", LastName = "Smith" } }.AsSomething(); 
```  
If this were implemented:

*  `not` constraints should allow open (e.g. `IEnumerable<>`) and partially open (e.g. `Dictionary<int,>`) types.
* Multiple `not` constraints should be allowed in a type constraint list (e.g. `where T : not IComparable, T : not IConverable`).

**Comment by Happypig375** [comment]
I think `!` could be used instead of `not`. `!` is already the boolean "not" operator and introducing a new `not` keyword will lead to inconsistency.

`public static void AsSomething<T>(this IEnumerable<T> arg) where T : not IEnumerable<> { }`
will become
`public static void AsSomething<T>(this IEnumerable<T> arg) where T : !IEnumerable<> { }`

P.S. The curly braces should come after the where clause. Please fix the code.

**Comment by bgribaudo** [comment]
Thanks, @Happypig375. Curly braces typos fixed.

**Comment by Joe4evr** [comment]
Aside from being utterly confused as to how *exclusive* constraints are even useful, this is not even remotely the solution to the problem that you describe.
> If a developer wants to provide method overloads handling specific type parameter cases along with a more general ‘catch all’ overload, it can be tricky to get the compiler to resolve to the intended specific type case overload.

It's really not tricky, because your problem isn't about the constraints at all; it's all about overload resolution.
```cs
// Intention: Resolves to AsSomething<T>(this IEnumerable<IEnumerable<T>> arg)
// Actuality: Resolves to AsSomething<T>(this IEnumerable<T> arg)
new[] { new[] { 1 } }.AsSomething();
```
What is actually happening is the compiler not inserting an implicit conversion from `T[]` to `IEnumerable<T>` for the inner array, because using the array as a `T` directly is more favorable, so your proposed "not constraint" still wouldn't help you get the right overload. If instead you did
```cs
new[] { new[] { 1 }.AsEnumerable() }.AsSomething();
```
*then* it would pick your `IEnumerable<IEnumerable<T>>` overload just fine.

**Comment by bgribaudo** [comment]
Hi @Joe4evr! Thanks for your comments!

Yes, the desired overload resolution can be achieved if explicit casting is done—but I'm trying to find a way to avoid requiring that casting.

## Real-Life Scenario
I authored a [library](https://www.bengribaudo.com/blog/2017/06/16/3612/introducing-datareaderadapter) that adapts an `IEnumerable<T>` to `IDataReader` (primary use: streaming data to `SqlBulkCopy` without requiring that the data first be loaded into a `DataTable`). Each item in the input enumerable becomes a data reader row. If the input enumerable is itself made up of `IEnumerable<T>`s, then each item in the inner enumerable becomes a field on the data row. Otherwise (that is, if the input enumerable contains something other than `IEnumerable<T>`s), the publicly-readable properties of `T` become the data row's fields.

To me, the ideal interface would be a pair of extension methods named `AsDataReader`, where the library user simply needs to call `myEnumerable.AsDataReader()` without needing to worry about explicit casting. 

Of course, as we've been discussing, this doesn't work as C# stands today. Instead, either in some circumstances the library user is required to manually add a cast or separate method names must be used for the two variations of possible input. (My library went with the latter approach, using `AsDataReader` for nested enumerables and `AsDataReaderOfObjects` for the rest.)

## How Resolution Would Work

If this proposal were implemented, I'd envision resolution working as follows:

To resolve:
```
`new[] { new { FirstName = "Joe", LastName = "Smith" } }.AsSomething();` 
```

Against:

```
static class MyExtensions
{
  public static void AsSomething<T>(this IEnumerable<IEnumerable<T>> arg) { }
  public static void AsSomething<T>(this IEnumerable<T> arg) where T : not IEnumerable<> {} // <-- use of not constraint
}
```

1. First, existing overload resolution rules are be used, ignoring the `not` constraint. Based on this, the second overload would be chosen as the resolution candidate (i.e. `AsSomething<T>(this IEnumerable<T> arg)`). 
1. Next, the `not` constraint on that overload is evaluated. 
    1. In this case, the complier determines that `T` is an `IEnumerable<>` (because it can be implicitly cast to that type), so the complier realizes that it can't resolve to this overload. 
    1. It then moves to what previously was the second best resolution candidate (`AsSomething<T>(this IEnumerable<IEnumerable<T>> arg)`), evaluates it, determines that it is qualified, and uses it.

**Comment by HaloFour** [comment]
I'm not sure how well this really works as a generic constraint.  What you seem to want is explicitly a way to influence overload resolution, and (as you mention) the C# compiler doesn't consider generic constraints as a part of overload resolution.  That has been suggested as a part of "bestest betterness".

Otherwise constraints have a very different purpose, namely in limiting the behavior of the generic type argument so that the generic method may use it in a particular manner.  The suggested `not` constraint doesn't fit in this mold at all.  Considering that generic type constraints are always a whitelist of functionality it doesn't make much sense to also apply a blacklist.  How does that work given overlap?  Is it possible to have a constraint of `IEnumerator<T>, not IDisposable`?  What does that even do?

While I understand the frustration in writing the generic methods for your library I think trying to manipulate the CLR (for the constraint) and the language specifically to support that case seems a little bit overkill.

I don't know the implementation details of your library or what those two methods accomplish but what I might have done is have the one method interrogate the `T` generic argument at runtime to determine if it was `IEnumerable` and treat it differently.

**Comment by bgribaudo** [comment]
Hello @HaloFour! 

I didn't realize that generic type arguments currently are not considered during the overload resolution process. Based on that, my `not` constraint wouldn't help with the use case I presented—at least, not until something like ["bestest betterness"](https://github.com/dotnet/csharplang/issues/98) is implemented. 

Even if that proposal makes it into the language (which would open the door for my `not` to help with my use case), you have a good point about `not` blacklisting diverging from the current _generic type constraints are always a whitelist of functionality_ behavior. Diverging like that might not be the best idea.

**Comment by dazinator** [comment]
I have an an additional use case for "not constraints".

I'm developing an extension for `Microsoft.Extensions.DependencyInjection` where I want to provide an API where the consumer can register transient services similar to how they do it already, except I want to disallow them from registering services that implement `IDisposable` as transient. 

For example I want this to cause a compilation error if `FooService` implements IDisposable:

```
services.AddTransient<FooService>();
```

For motivations as to why I would want to create such an Api, there are numerous issues like this one https://github.com/dotnet/aspnetcore/issues/5496 and it is basically because any instance of a transient service that the container creates automatically gets owned by the container and tracked for disposal.. but disposal doesn't happen until the container itself is disposed. Now consider you are resolving many transient instances from a root container or a scope that lives a long time - they accrue and you get memory leak.

Much better imho to prevent transients that implement IDisposable from being registered at all but we need the compiler to enforce that with some kind of feature like this.
