### ISSUE TITLE
Proposal: Built in Decorator pattern

### ISSUE THREAD

**Issue by kogoia** [dotnet/csharplang#730]
It would be nice to have an implementation Decorator Pattern at the level of language.

The syntax can be done something like this or better:
```cs
    public interface IFoo
    {
        int Method1(int a, int b);
        string Method2();
    }

    public class Foo : IFoo
    {
        public int Method1(int a, int b)
        {
            return a + b;
        }
        public string Method2()
        {
            return "Foo";
        }
    }
    public decorator class A : B
    {
        public decorate int Method1(int a, int b)
        {
            before
            {
                // do something and return tuple with same type as method except
                return (a, b);
            }
            after
            {
                // do something and return result with same type as method returns
                return value;
            }
        }
    }
```

- Do not allow the announcement of public methods, except those specified in the interface
- Automatically create default constructor which expects type of decorating class

```cs
    var bar = new Bar(
                new Foo()
              );
   bar.Method1(1,2);
   bar.Method2();
```

**Edited:**
```cs

public decorator class A of IFoo
{
	public decorate int Method(int a, int b)
	{
		before 
		{
			return (a,b);
		}
		after 
		{
			return value;
		}
	}
}
```

**Comment by amis92** [comment]
That's four (!) new keywords. It's also not immensely helpful. What do you save? A constructor.

Because the two before/after sub methods are actually more bloated than a single override. You'd also have to make the method in Foo virtual anyway, there's no way to skip that.

The only "benefit" with that separation of before and after is just that, a much more visible separation. Not very exciting if you ask me, and definitely not something worth language feature.

If I'm missing something that makes it very valuable, please correct me.

**Comment by kogoia** [comment]
Yes you right it's not immensely helpful. But in case when we have class with many method and we must want override only one of them, I think in this case it will be valuable.

Imagine we have this case:

```cs
    public interface IText
    {
        string Body();
        string Title();
        int Words();
        //
        // and some methods
        //
    }

    public class Title
    {
        private readonly string _str;

        public Title(string str)
        {
            _str = str;
        }
        public override string ToString()
        {
            return new SplitedByLines(_str).First();
        }
    }

    public class Text : IText
    {
        private readonly string _str;

        public Text(string str)
        {
            _str = str;
        }
        public string Content()
        {
            return new Title(_str); // notice text will be decorator for String
        }

        public string Body() { ... }
        public int Title() { ... }
    }


    new TrimmedText(
        new UpperCaseText(
            new UTF8Text(
                 new Text()
            )
        )
    )
```

**Comment by kogoia** [comment]
We can improve this idea and make the implementation more elegant. Use many decorators pushes write more declarative code, and this is good realization of SRP principle. Many classes with few responsibilities.

I think this part is most of the valuable then decrease code lines. 
Let's do C# more suitable for true OOP:)

**Comment by svick** [comment]
I think this is another case where code generators would be useful, see https://github.com/dotnet/csharplang/issues/107 and https://github.com/dotnet/csharplang/issues/341.

**Comment by kogoia** [comment]
Mhh, interesting approach, but I against of the code generation, if this not on Language level as keyword. Code generation always hide realization, I mean it's to hard find this snippet of code which add another behavior. Only if you don't write some documentation for it. I think code will be self-describing.

AOP is very powerful and great idea, but I don't like available ways it implementation. e.g. through Attributes.

When I see attributes I don't know which snippet of code look at this and do extra work for me, I would like have some way of control this. I think decorators are one of the best way achieve this result and C# should give us make this things simpler.

Maybe, that way of implementation as I suggest are not appropriate, but we must go for this direction. I feel so :) Maybe I'm wrong.

**Comment by bgribaudo** [comment]
Hi @kogoia! Thanks for proposing this! I remember wanting something like this a while back on a project. 

I wonder if you would consider amending your proposal to cover more use cases. For example, some people might want their decorators to inherit from a base class (e.g. `BaseDecorator`), so maybe decorators should be able to support inheritance. It could be helpful to remove the restriction that decorators can't introduce new public methods as this restriction might be limiting in some cases (e.g. say `BorderDecorator` holds a collection of borders for left, right, top and bottom—it might be appropriate for the decorator to have a `ClearAllBorders()` method). Also, some folks might find not want a default, single-argument constructor as their decorators require certain configuration values at the time of construction (e.g. maybe a `BorderDecorator` must be passed border color and border thickness when it is created). I could also see value in providing a way to access the decorated object from inside the decorator.

I wonder if the essence of language support for the decorator pattern would look something like this:

- Provide a way to indicate that a class is a decorator for a certain interface or type. For example: `class BorderDecorator : decorates IShape`. 
  - Since a decorator is just a class with special behavior, all normal aspects of a class are still supported (inheritance, defining constructors & public methods, etc.).
- Provide a way to indicate that a particular property or field of the class holds the object instance being decorated. For example: `[Decorated(typeof(IShape))]protected IShape decorated`.
  - This object instance is known as the _decorated instance_. 
- Add the following functionality to the language: Attempts to access a member of the decorated interface/type that are not implemented in the decorator are forwarded to the decorated instance. For example, if `IShape` has a `GetSize()` method and `BorderDecorator` does not contain an override `GetSize()`, calling `GetSize()` on a `BorderDecorator` instance results in `decorated.GetSize()` being called.

Realistically, I'm not sure if language-level support for the decorator pattern has much chance of being added, in light of the fact that decorating can already be done using the language as it stands today—albeit in a more verbose way. Still, I'm glad this idea was proposed—because it gives the community the opportunity to weigh in on it.

**Comment by kogoia** [comment]
@bgribaudo thank you for response. It's clear for me. 
I close this issue

**Comment by kogoia** [comment]
@bgribaudo thank you for response. It's clear for me. 
I close this issue
