### ISSUE TITLE
Proposal: temp allocation

### ISSUE THREAD

**Issue by ygc369** [dotnet/csharplang#757]
C# should allow people to allocate temp objects which would be freed soon.
For example:
```C#
static void foo()
{
    string str;
    TempAllocationBlock  //may use other syntax
    { //all objects allocated within this block are temp objects.
        string s=new string(' ', 1000); //s is a temp string
        ...... //do something with s, but s can't escape out of this block
        str=s; //compile error or throw exception! temp object is trying to escape!
    }//free the memory of s here! 
    /*When the code runs out of this block, all the memory allocated within this block should be freed at once, need not wait for GC!*/
}
```

**Comment by Joe4evr** [comment]
And how would you expect the runtime to clear that memory without doing a GC?

**Comment by ygc369** [comment]
@Joe4evr 
.Net managed heap has free memory list too, just like C/C++, although it is not used as frequently as C/C++. For example, if there is pinned memory during GC, then the free heap memory after GC might be incontinuous, so a free memory list is needed to manage the incontinuous free memory.
So the answer to your question is to use the free memory list.

**Comment by svick** [comment]
@Joe4evr I think that's the easy part. If you know for sure that a group of objects can be safely freed at a specific point of time, you can use an [arena](https://en.wikipedia.org/wiki/Region-based_memory_management) to manage their memory.

@ygc369 The general idea might sound enticing, but I have a hard time understanding how exactly would it work and how useful would it be in practice. For example, consider this code:

```c#
Person[] GetAllPersonsByName(string name)
{
    return this.persons.Where(p => p.Name == name).ToArray();
}
```

* Would I be able to use your proposal to make the closure, the delegate and the `IEnumerable` returned from `Where` temporary, while keeping the array returned from `ToArray` not temporary?
* How would the compiler/runtime figure out that the returned array does not reference any of the temporary objects? I think this pattern of using temporary objects to produce a result object is fairly common. And other patterns would probably have similar issues of interactions between temporary and non-temporary objects.

**Comment by ygc369** [comment]
@svick 
The compiler/runtime can check whether the returned object references any of the temporary objects before return.

**Comment by HaloFour** [comment]
In my opinion this belongs on the list of potential optimizations of the JIT, not of the language.  C# has no concept of a free memory list.

**Comment by ygc369** [comment]
@HaloFour 
But C# should provide a syntax to express temp allocation block.

**Comment by eyalsk** [comment]
@ygc369 Why should it provide a syntax for it?

**Comment by ygc369** [comment]
@eyalsk 
Because people must tell the compiler/runtime which allocations are temp.
Do you mean that the compiler should find temp allocations by itself without people's help? Can it be so smart? I doubt.

**Comment by CyrusNajmabadi** [comment]
@ygc369 How would this work?

**Comment by CyrusNajmabadi** [comment]
Specifically: what would the compiler actually do differently with this sort of code?

**Comment by HaloFour** [comment]
@ygc369 

> But C# should provide a syntax to express temp allocation block.

I disagree.  Such a thing, if it would exist, is an implementation detail of a CLR.  As of now it doesn't exist in the CLR at all, let alone officially supported with public metadata in a manner that can be influenced by any of the CLR languages, let alone C#.

> Because people must tell the compiler/runtime which allocations are temp.

I'd suspect that the JIT would be more than capable of detecting when a local never escapes and could be safely collected upon exiting a method (blocks don't exist in IL and local slots are always scoped to the method).  However, exactly what use is a variable that doesn't escape?  What useful code could you possibly execute on `s` in your code that doesn't involve the reference being passed somewhere outside of that method?

**Comment by ygc369** [comment]
@HaloFour 
Many algorithms need temp space to store intermediate results, but once they get final results, the temp space would be useless and should be freed at once. This is the usage of the proposal.

**Comment by eyalsk** [comment]
@ygc369 If you can't mutate something and you can't get anything in and out of the block why do you need to allocate memory to begin with? can you name few of these algorithm? what's the problem with the following approach:

```
void Main()
{
	using (Scope s = new Scope())
	{
// Can't really do anything with s... 
	}
}


class Scope : IDisposable
{
	public void Dispose()
	{
		// Do something...
	}
}

```

**Comment by svick** [comment]
@ygc369 

> The compiler/runtime can check whether the returned object references any of the temporary objects before return.

That sounds a lot like generational garbage collection: You have a small set of objects (Gen 0) and a subset of those objects that shouldn't be collected (roots). You walk references from the objects that shouldn't be collected to check which objects they reference (mark stage) and then deallocate the rest (sweep stage).

Are you basically asking for explicitly delimited "gen -1"?

**Comment by Joe4evr** [comment]
Also, remember that in designing the CLR, the GC flow is *intentionally* left as an implementation detail. If you don't like that the GC is non-deterministic like that, then go to C/C++/any other unmanaged language where you can control literally every allocation and de-allocation yourself.

But please just stop [proposing](https://github.com/dotnet/coreclr/issues/9963) [all](https://github.com/dotnet/coreclr/issues/2470) [these](https://github.com/dotnet/coreclr/issues/8313) [silly](https://github.com/dotnet/coreclr/issues/11586) micro-optimizations just because the GC doesn't behave in the way that *you* imagine it should.

At the very least follow what you've been told time and again by now: Provide real-world performance data that shows beyond a shadow of a doubt that your proposed changes are worth the amount of time, effort, and money for Microsoft to change the existing system.

**Comment by SunnyWar** [comment]
@Joe4evr I take issue with your tone. It's not constructive. Please stop. Personally, I think the proposal is worth some thought. Just because the GC works in a certain way _today_ doesn't preclude it from working different (better) in the future. I've had apps that have no choice but to call a function that allocates a block of memory and then throws it away a few instructions later, and this in a long-running tight loop. In this scenario the GC goes crazy with Gen 0 collections for millions of objects that logically have no reason to live so long. Explicitly setting them to null and forcing a collection just makes it worse. I've also heard is said, "if you need it faster, write it C/C++". This is great practical advise in the short term but my assumption is that these discussion about finding way to make .Net better. In which case such statements are not helpful.

**Comment by CyrusNajmabadi** [comment]
Again: what is the proposal here?  What are you asking the C# compiler to actually do?

**Comment by CyrusNajmabadi** [comment]
> Many algorithms need temp space to store intermediate results, but once they get final results, the temp space would be useless and should be freed at once. 

You can usually accomplish this with pooled objects.  That way you can have your temp values that you work with, but you don't churn the GC heavily as you can take those intermediate objects and put them in your pool instead of needing to have them be collected.

**Comment by CyrusNajmabadi** [comment]
>  Just because the GC works in a certain way today doesn't preclude it from working different (better) in the future. 

GC proposals are probably not great to be here.  This is the repo for the C# language.  Details of the GC aren't really under our purview.

**Comment by CyrusNajmabadi** [comment]
> This is great practical advise in the short term but my assumption is that these discussion about finding way to make .Net better.

In your example, i woudl advise changing that function that you are calling to behave differently.  For example, instead of allocating data that then needs to be freed, it could be passed in the location to place or fill results.  Then you could allocate once and it would not have to worry about that detail.  

If you can't change that function then it's highly unlikely that any proposal here would actually help with this.

**Comment by SunnyWar** [comment]
@CyrusNajmabadi 

> i woudl advise changing that function that you are calling to behave differently

Ya. I'll get right on that...getting the .Net Framework and dozens of third party libraries to change their functions to behave differently. Ha!

**Comment by SunnyWar** [comment]
@ygc369 Note this issue was closed, I think, not because you idea has no merit but because it's not a language issue. Be sure to post you ideas to the coreclr for recommendations on better garbage collection.

**Comment by CyrusNajmabadi** [comment]
> Ya. I'll get right on that...getting ... functions to behave differently. Ha!

I don't understand what the proposal is.  What do you think the .net framework could do differently here.  Presumably if you wanted to use these constrained regions, you'd have to code in a very particular way (in order to participate properly with whatever restrictions it puts on your code).  But... in the example given... you're calling out to 3rd party code.  Code that expects to be run in a GC environment and would very likely not behave properly in such a new restrictive system.  So *again* can someone  please tell me what the request is, and how it would work, and how it would solve the problems laid out here?

> getting the .Net Framework functions to behave differently

Actually, this is definitely something you can do.  Take a look at Stephen's post here https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/   See how many performance improvements have been provided by the community.  If you are having problems with .Net perf, then *definitely* put in the effort to address the issues.  The PRs will get accepted, and it will be far more likely to happen, and far more likely to help than trying to get the language and runtime to change significantly here.

--

Now, if you do want the language/runtime to change, it absolutely *must* be with a clearer description of what the proposal would be.  I still can't tell what is being asked for here, so there's no way to make any forward progress on something like this.

**Comment by ygc369** [comment]
@SunnyWar 
Thank you. But I don't dare to open new issue now, could you post similar ideas to the coreclr repo if you need it? I was hurt by Joe4evr's words. If I open new issue in the coreclr repo, he might ridicule me again. I don't like that.

**Comment by CyrusNajmabadi** [comment]
@ygc369 @SunnyWar Could you provide information about your actual proposal?  I"ve looked at the links to other proposals that you've made and they all seem to be lacking any sort of data or detail.  To make a change or introduce a new .net memory model or programming model you absolutely must provide more information or else none of these issues are going to go anywhere.

**Comment by ygc369** [comment]
@CyrusNajmabadi 
The idea is to use some syntax to tell the compiler/runtime which allocations are temp and can be deallocated once going out of scope. Thus these memory can be reused before next GC.

**Comment by CyrusNajmabadi** [comment]
how would this work in your example of calling into some other function?  How do you ensure that what you are doing would not be unsafe?

**Comment by ygc369** [comment]
@CyrusNajmabadi 
The purpose of this idea is to reduce the GC pressure and the garbage living time.
If the compiler/runtime is so smart that it can find temp allocations without people's help, then no new syntax is needed and that's OK too.

**Comment by CyrusNajmabadi** [comment]
Can you explain your proposal more (and answer my question).  What is the way that you would accomplish this?

**Comment by ygc369** [comment]
@CyrusNajmabadi 

> how would this work in your example of calling into some other function? How do you ensure that what you are doing would not be unsafe?

The JIT/CLR should ensure that. The rule is that non-temp objects can't reference any temp objects. Throw an exception when the rule is broken.

**Comment by CyrusNajmabadi** [comment]
Ok.  let me try a different tactic.  Imagine if i said "i want the runtime to do some sort of analysis and not allocate when it isn't necessary".  Sure... that sounds great.  But how does it do that?  It's not enough to ask for these types of things, you have to actually explain how it would work.  Be specific.  What does the compiler and language do differently?  How does the runtime actually implement this?  How do we ensure that this doesn't break stuff.

**Comment by CyrusNajmabadi** [comment]
> The rule is that non-temp objects can't reference any temp objects.

So you can't pass any of this data to anything else?  For example, any method out there might end up taking any parameters and passing it to some referencing non-temp object.

**Comment by ygc369** [comment]
@CyrusNajmabadi 
The non-temp objects can't reference any temp objects, but temp objects can reference each other and non-temp objects.

> So you can't pass any of this data to anything else? For example, any method out there might end up taking any parameters and passing it to some referencing non-temp object.

I can pass value type at least.

**Comment by HaloFour** [comment]
These "temp" objects are just instances of normal reference types.  Literally any method you could call, either instance or static, in literally any library anywhere, could take that reference and assign it somewhere.  There's no way that the compiler nor the runtime can prevent another root from being established on these references and that would prevent the "temp" object from being collectable.

**Comment by alrz** [comment]
I think this is related to https://github.com/dotnet/roslyn/issues/161. It does actually propose to "destruct" objects once they're out of scope. and that in itself require some kind of ownership as safety rules -- partly https://github.com/dotnet/csharplang/issues/421though that doesn't propose to actually free memory once out of scope, just that we make sure that every object has a single owner to enforce immutability across aliases.

**Comment by Joe4evr** [comment]
@SunnyWar @ygc369 
> I take issue with your tone. It's not constructive.
> I was hurt by Joe4evr's words.

I do apologize for that, and I should've chosen my words a bit more carefully. Cyrus' posts have said it a lot better: If you only say "I want X!" without any clear explanation of exactly *how* that should be accomplished, it just feels like you're being this guy:
![](http://i.imgur.com/jEPmI28.png)
Don't be this guy.

**Comment by SunnyWar** [comment]
I'm temped to address the jerks on this thread but instead I'll try to get it back on track.

@ygc369  Please take a look at these discussion on CoreCLR.

[https://github.com/dotnet/coreclr/issues/1784](url)
and
[https://github.com/dotnet/coreclr/issues/430](url)

**Comment by tannergooding** [comment]
@SunnyWar, @ygc369 

If I understand the proposal you are making, you are essentially asking for a form of `stack allocated objects` that are scoped to a specific block.

There are several proposals on the topic already of `stack allocated objects` already (including one filed by @ygc369: https://github.com/dotnet/csharplang/issues/240) and I think (if I understood the proposal) that this is merely an extension on top of that.

@CyrusNajmabadi could confirm, but I believe this is one of the issues where C# cannot do anything actionable until the CLR is modified to provide basic support for this functionality (e.g. more PRs like https://github.com/dotnet/coreclr/pull/6653 need to be done).

**Comment by ygc369** [comment]
@tannergooding 
Your understanding is generally right. But this proposal is a bit different from `stack allocated objects`, because stack can't store large objcets. Temp objects in this proposal could be stored on the heap if they are big, but they can be collected before GC, just like stack allocated objects.

**Comment by CyrusNajmabadi** [comment]
@ygc369 How would this work?  How does your proposal make sure that it's safe to collect these objects?  For example, if you wanted to "temp allocate" an object, then how would that work?  First, how do you ensure that the constructor of the object doesn't leak 'this' to anything?  Second, how do you ensure that any of the method you might pass this object to, or any of the methods you might call on this object, don't capture the object?  

Can you give an example of how this would work and how you could ensure it would be safe?

**Comment by CyrusNajmabadi** [comment]
For example, in your code, you have this:

> //do something with s, but s can't escape out of this block

What can you actually do with 's'?  Any method call on 's' could cause it to escape.  Can you provide an actual scenario where this would be useful and actually explain the proposal in more detail?  So far i have not really seen any answers (sufficient or otherwise) for the questions i've asked you.

**Comment by SunnyWar** [comment]
@tannergooding I'm not suggesting anything. I'm only trying to get the jerks on this thread to open their minds a bit and consider the possibility of improving the status quo. That's why I pointed people at various proposals on the coreclr, so that they can familiarize themselves with other, similar, discussions.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi could confirm, but I believe this is one of the issues where C# cannot do anything actionable until the CLR is modified to provide basic support for this functionality

We'd need an actual proposal specifying how this would work.  It would need to be clear about what changes to the language would be wanted, and how they would map to any underlying CLR functionality for the compiler implementation.  I've now looked through each and every issue linked from this issue and i can't find anything actually concrete or actionable.  It appears to be a lot of very high level request (like "we should support reference counting") without actually providing any sort of additional detail past that.  

These types of issues will not go anywhere in their current form.  It would be akin to me saying "i want C# to be a cloud computing language" and then providing no detail on what that actually means or what it would actually entail to get there.  

@ygc369 If you are interested in this space (which certainly seems like the case given several messages from you asking if there has been any progress), then i would recommend supplying a little more information and design to help move things forward.  Right now, opening an issue, and then hoping others will pick it up and figure it out isn't really going to be effective.

**Comment by ygc369** [comment]
@CyrusNajmabadi 
Now I try to answer your core question----"how would this work?"
I think it need a write barrier to check whether temp objects escape.
In my example, when the code goes into `TempAllocationBlock`, a write barrier should start to work, checking every reference assignment. 
I know that write barriers impact performance, so whether to do it needs tradeoff.

**Comment by ygc369** [comment]
@CyrusNajmabadi 
Some people are more radical than me. They don't want to use a syntax to tell the compiler/runtime which allocations are temp, but they want the compiler/runtime to find temp allocations by itself automatically. It's a bit like escape analysys. 
I support this idea too. But if you ask me how to do this, I really don't know. Java has escape analysys feature, why not to look at Java's implemention?

**Comment by CyrusNajmabadi** [comment]
> Java has escape analysys feature, why not to look at Java's implemention?

Can you point to the java *language* feature that relates to escape analysis?

**Comment by ygc369** [comment]
@CyrusNajmabadi 
>Can you point to the java language feature that relates to escape analysis?
I can only find Chinese documents about it. 
As you know, the GFW(Great Firewall of China) makes it difficult to search English documents in China. I can't even use Google.

**Comment by HaloFour** [comment]
@ygc369 

@CyrusNajmabadi's claim is that escape analysis is not a part of the Java *language* in that there is no syntax to opt-into using it or to influence it directly.  It's an optional optimization feature of the runtime.

**Comment by eyalsk** [comment]
@CyrusNajmabadi Wiki says this:

> The popularity of the Java programming language has made escape analysis a target of interest. Java's combination of heap-only object allocation, built-in threading, and the Sun HotSpot dynamic compiler creates a candidate platform for escape analysis related optimizations (see Escape analysis in Java). Escape analysis is implemented in Java Standard Edition 6. Some JVMs support a stronger variant of escape analysis called partial escape analysis that makes scalar replacement of an allocated object possible even if the object escapes in some paths of a function.

```
class Main {
  public static void main(String[] args) {
    example();
  }
  public static void example() {
    Foo foo = new Foo(); //alloc
    Bar bar = new Bar(); //alloc
    bar.setFoo(foo);
  }
}

class Foo {}

class Bar {
  private Foo foo;
  public void setFoo(Foo foo) {
    this.foo = foo;
  }
}
```

> In this example, two objects are created (commented with alloc), and one of them is given as an argument to a method of another. The method setFoo() stores a reference to a received Foo object. If the Bar object was on the heap then the reference to Foo would escape. But in this case a compiler can determine, with escape analysis, that the Bar object itself does not escape the invocation of example(). Which implies that a reference to Foo cannot escape either. So the compiler can safely allocate both objects on the stack.

But really the only thing that baffles me here is why we need a syntax? a new form of block that I still don't understand why the need to allocate memory if nothing gets in and out of it, maybe someone, smarter than me can explain it to me, do I miss anything?

**Comment by ygc369** [comment]
> But really the only thing that baffles me here is why we need a new syntax for it? a new form of block that I still don't understand why the need to allocate memory if nothing gets in and out of it, maybe someone, smarter than me can explain it to me, do I miss anything?

Value types can get out of it.
For example:
```C#
static float GetInputSpeed()
{
    int char_num=0;
    Stopwatch sw = new Stopwatch();
    sw.Start();
    TempAllocationBlock
    {
        string s;
        do {
            s=Console.ReadLine(); //allocate temp strings
            char_num += s.Length;
        } while(s!="exit");
    } //should free all temp strings here!
    sw.Stop();
    return ((float)char_num*1000*60)/(float)sw.ElapsedMilliseconds;
}
```

**Comment by CyrusNajmabadi** [comment]
> I support this idea too. But if you ask me how to do this, I really don't know. Java has escape analysys feature, why not to look at Java's implemention?

Sorry, that's not how proposals work :)  It doesn't suffice to just come, say you want something, and then say the onus is on us :)

And, again, as mentioned by others, Java did this without the need for language changes.  So why do we need language changes here?

> Value types can get out of it.

Why does this require any language changes?  The runtime already knows what is/isn't a value type.  If it was doing escape analysis, surely it would only care about doing that for heap allocated instances.

**Comment by CyrusNajmabadi** [comment]
i don't understand how this works:

```c#
    TempAllocationBlock
    {
        string s;
        do {
            s=Console.ReadLine(); //allocate temp strings
            char_num += s.Length;
        } while(s!="exit");
    } //should free all temp strings here!
```

Are you saying that because we're in this TempAllocationBlock that any allocatoin in this block of execution will just get cleaned up once the block is exited?  How do you ensure safety for that?  What if Console.ReadLine does something internally like causing a segment to be allocated in some low level console stream that it's buffering from.  Will that now get freed once you go out of this scope?

**Comment by ygc369** [comment]
@CyrusNajmabadi 
Your concerns are quite reasonable. I had realized these problems, and closed this issue days ago. I had given it up then. But you asked questions about this issue after I closed it, so I tried to answer. But that doesn't mean I want to reopen this issue. So discussions about this can stop here.

**Comment by eyalsk** [comment]
@ygc369 So if you knew about it days ago why didn't you post your conclusions about it back then? could have saved yourself and others some time. 😉

**Comment by ygc369** [comment]
@eyalsk 
So I closed this issue. I thought that closing an issue means no more discussions needed. I might be wrong. Others don't think so.

**Comment by eyalsk** [comment]
@ygc369 You don't get to decide when a discussion is over and closing an issue doesn't really mean it can't be discussed, otherwise, it was locking an issue and you don't get to do that, you didn't have to participate in the discussion but obviously, you **chose** to do so and that's good but I really find it strange that you knew about the issues @CyrusNajmabadi and other brought up and didn't bother to write about it but instead went on and closed the issue.

It's like two people having a good conversation, one is trying to explain something, the other is trying to understand it, so the second person bringing up all sorts of questions and the moment the first person realizes he has no answers, he turns his back to the second person and yet the second person don't mind it and insists of getting answers so they continuing their conversation and throughout the discussion the first person realizes how wrong he is but instead of admitting it he says aye.... I knew that through the whole discussion but didn't bother to say anything about it this is why I turned my back to you

It just doesn't make sense to me, sorry. 😄 

Anyway, I really write this with the best intention so you will understand why it feels strange to me.

**Comment by CyrusNajmabadi** [comment]
@ygc369 

>  I had realized these problems, and closed this issue days ago. I had given it up then. But you asked questions about this issue after I closed it, so I tried to answer. But that doesn't mean I want to reopen this issue. So discussions about this can stop here.

I see.  In the future could you make that clearer when closing the bug.  Your followup statements did not reveal that you had come to this conclusion and i simply thought you were going to open a new issue.  I wanted to get clearer understanding of the design here before that happened.

If you do want to continue pursuing something here, please provide more detail in the future to help things go more smoothly.  Thanks!
