### ISSUE TITLE
Add pre-2015 meeting notes

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#8]
LDM meeting notes from 2015 onward are being added to this repository in #7. However, meeting notes from October 2013 through the end of 2014 are (linked) in 

- http://roslyn.codeplex.com/wikipage?title=CSharp%20Language%20Design%20Notes&referringTitle=Documentation

and

- http://roslyn.codeplex.com/wikipage?title=Visual%20Basic%20Language%20Design%20Notes&referringTitle=Documentation

Although their source is in markdown form, only the author can easily see the markdown source. So can I please have some help, either from an administrator, or from @MadsTorgersen and Lucian, on getting the markdown source for those?

**Comment by scottdorman** [comment]
When these older LDM notes are pulled in from CodePlex, will just the original notes be pulled or will it be the notes and all of the comments? If the comments are coming too (which I'd suggest), there needs to be a good way to identify it is a comment rather than part of the original LDM notes (and also who it was from).

It also looks like most of these earlier LDM notes are for both C# and VB, so would that mean they're duplicated in both the csharplang and [dotnet/vblang](http://github.com/dotnet/vblang) repos?

Also, it looks like the original markdown source is actually included as a `data-markdown` attribute  on the respective `td` elements in the source, so a screen-scraper should be able to parse the data out. I may have some time to throw something together this weekend to extract the markdown and turn it in to a single document.

**Comment by scottdorman** [comment]
I have a rough working prototype of a converter. Here is a sample of what the converted output looks like. This is directly from the tool I wrote and I've done no manual cleanup on it, which would definitely be needed, but it's at least a starting point for all of the older LDM notes.

https://gist.github.com/scottdorman/f07611c1f11aa13d5a4c3854b6220683
