### ISSUE TITLE
Proposal: Shorthand for simple expression lambdas

### ISSUE THREAD

**Issue by HaloFour** [dotnet/csharplang#91]
Copied from https://github.com/dotnet/roslyn/issues/3561

This has come up a few times on CodePlex as well as here but I've not seen any formal proposal for it so I thought I'd post one just to track it and get some conversation going about it.

Many of the LINQ extension methods accept a single argument and return a value, most often the result of a simple expression stemming from that argument.  In those simple cases the developer is still required to assign the parameter value to a name that cannot shadow a name used in the current scope and then immediately reference that name in the body of the closure.

``` cs
var query = db.Orders
    .Where(order => order.Value > 50.0m)
    .Select(order => order.Employee)
    .OrderBy(employee => employee.Name);
```

I propose that a short-hand version of this common pattern where the value of the argument can be accessed through a specific sigil which must be referenced in the method body.  The following uses the sigil `@` and is the same as the query above:

``` cs
var query = db.Orders
    .Where(@.Value > 50.0m)
    .Select(@.Employee)
    .OrderBy(@.Name);
```

**Comment by orthoxerox** [comment]
Where does a shorthand lambda expression begin or end?

**Comment by HaloFour** [comment]
@orthoxerox 

It would be a single expression.  The sigil would effectively expand out to `$temp => $temp`, so `(@.Value > 50.0m)` would be `($temp => $temp.Value > 50.0m)`.

I'd be curious to hear other opinions and interpretations, but I'm personally not all that interested in another full-fledged syntax for lambdas.

**Comment by eyalsk** [comment]
I don't mind having something like this but I think that the idea can be expanded to `$1.*`, `$2.*`, `$3.*`, ... and then as a syntactic sugar we can have `$.*` as a shorthand for `$1.*` or even in place of it.

**Comment by alrz** [comment]
@HaloFour Do you think this is necessary with method references in mind? I admit that they are more limited than something like this but I don't see how this is an improvement over proper lambdas.

**Comment by eyalsk** [comment]
@alrz I actually thought about this so thanks for bringing this up, I prefer this mostly because currently, we have to come up with letters that don't make sense or do but in many cases the variable isn't the subject and so using the position to access the object make more sense.

**Comment by HaloFour** [comment]
@alrz 

I'd evaluate the two independently.  Method references can certainly make the expressions less verbose (depending on the syntax that might be adopted), but they can only represent a narrow set of those expressions.  It's fine for simple `Select` where you intend to extract a single property, but doesn't help with `Where` or `OrderBy` where you'd want an adhoc filter/expression.

**Comment by alrz** [comment]
@eyalsk 


>we have to come up with letters that don't make sense 

Underscore is *still* an identifier and yet, not a letter. And how `@` makes *more*  sense than `_`?

>so using the position to access the object make more sense,

Mathematica has this but conciseness often wins out the readability in that context as there is an operator for most of functions. I think, if you have more than one or two parameters, you *should* be using meaningful names, no?

@HaloFour 

>But doesn't help with Where or OrderBy where you'd want an adhoc filter/expression.



I'd prefer method references over lambda because (1) they avoid double invocation (2) they infer overloaded members (3) syntax is a nice-to-have after all. On the other hand, shorthand lambda (1) doesn't avoid double invocation because probably it's not a double invocation if you can't use method references as you mentioned, (2) doesn't provide any advantage in terms of type inference compared to lambda expressions, they are practically the same, (3) the syntax is confusing. with any choice of token, I can't imagine what language grammar you have in mind for this.

The question is, why would you want to squeeze such an expression (that is admittedly not considered straightforward) to that form? I mean, if it's already in the simplest form, we probably shouldn't try to make it simpler.™

**Comment by HaloFour** [comment]
@alrz 

I don't disagree.  My statement is that method references *can't* fit in many of these scenarios.  Java has both and I use method references where possible but I'm still using simple lambda expressions the vast majority of the time.

**Comment by eyalsk** [comment]
@alrz 

> Underscore is still an identifier and yet, not a letter. And how @ makes more sense than _?

Well, I'm suggesting to use `$<position>`, however, it's not just having `@` it's also eliminating the need to use the lambda operator, I mean between `f((_) => _.Value)` vs `f(@.Value)` the latter seems more attractive.

> Mathematica has this but conciseness often wins out the readability in that context as there is an operator for most of functions. I think, if you have more than one or two parameters, you should be using meaningful names, no?

Well, maybe, I mean sometimes you may want to do f(($1.A+ $2.B) + $3.C) and might not care so much about the parameters.

The question is why we need to choose this feature over the other or vice-versa? 

p.s. I think I need to write a different proposal about it because it's slightly different than this one.

**Comment by HaloFour** [comment]
@eyalsk 

My concern about such syntax is that it seems to largely intend to replace proper lambdas.  I don't think that C# needs another full-fledged syntax for lambdas.  It also seems like a nightmare to parse since there is no obvious place that the lambda begins.  You could have a nested set of statements several levels deep and all of a sudden smack into a `$` and the compiler would have to know which  expression is a lambda and which positional argument is associated with which parameters.

What does the following mean?  I can think of at least two perfectly valid interpretations.

```cs
f1(f2($1.A + $2.B) + $3.C)
```

**Comment by alrz** [comment]
Also two perfectly valid interpretations here:
```cs
f1(f2(@.A + @.B) + @.C)
```

**Comment by HaloFour** [comment]
@alrz 

My proposal doesn't permit for the use of the sigil `@` arbitrarily within the expression, only at the beginning.  That eliminates such ambiguities.  I would argue that if you're using the parameters in such a way that the parameter itself is important and should be named accordingly.  My proposal is more about capturing the scenarios where the parameter is of virtually no importance, only the expression dotted off of the parameter is.

**Comment by orthoxerox** [comment]
@HaloFour

So `1 + @` will be parsed as `1 + x=>x`?

Even with that restriction the parsing will be rather convoluted.

**Comment by alrz** [comment]
Beginning of what? `@.C` is also at the beginning of the RHS of the second `+` operator. If you're going to say "parameter" I don't think that would make much sense as I don't know any other expression form that is restricted in certain contexts.

**Comment by HaloFour** [comment]
@orthoxerox @alrz 

Perhaps not, but if `@.Foo` were to expand specifically into `($temp => $temp.Foo)` then it severely limits where you can use the expression which should railroad it into the intended scenarios.  Sure, you could use it outside of an argument, e.g.:

```cs
Func<Foo, string> func = @.Name;
```

But I think that's fine.  But the expression `1 + @` would be a compiler error, just as `1 + x=>x` is today despite being perfectly legal syntax.

**Comment by orthoxerox** [comment]
Scala spec 6.23 outlines a more complex approach to parsing shorthand lambdas, but the definition's really terse and I'm not sure if Roslyn can implement it without reparsing the whole subtree during binding, which opens a whole can of worms.

**Comment by alrz** [comment]
> if @.Foo were to expand specifically into ($temp => $temp.Foo) then it severely limits where you can use the expression


Unless it is expanded by regex I don't see who compiler would understand from the *source* code that is not legal. AFAIK the compiler doesn't rewrite syntax tree to see what's legal and what's not. It operators directly on the source  and would look no further if there is an error.

**Comment by alrz** [comment]
> if @.Foo were to expand specifically into ($temp => $temp.Foo) then it severely limits where you can use the expression


Unless it is expanded by regex I don't see who compiler would understand from the *source* code that is not legal. AFAIK the compiler doesn't rewrite syntax tree to see what's legal and what's not. It operates directly on the source  and would look no further if there is an error.

**Comment by HaloFour** [comment]
@alrz 

By "expands" I mean in effective behavior, not that the compiler is transforming the source in any way.

The intention of the proposal above is to put the focus on the member used in the expression above the lambda argument.  To that end I'd go so far as to amend the proposal that `@` is only legal when immediately followed by `.` to denote member access.  The `@.Foo` expression is evaluated as a lambda expression and binds exactly as lambda expressions do today.

Trying to expand this out to support any shape of lambda and any permutation of expressions seems to defeat the purpose.  C# has a fully-capable lambda expression syntax today.  Sure, you have to name the arguments, but if you're doing anything more complicated than just simple member access or a very brief expression I don't think that implicitly-named or positional lambda arguments makes a lot of sense.

@orthoxerox 

Scala's underscore operator does look interesting but it does absolutely look like a parsing nightmare due to the various ways in which it can be interpreted.  That probably explains the questions on stackoverflow regarding when and why it fails to compile.

**Comment by alrz** [comment]
>put the focus on the member used in the expression

I believe the language design team has considered that very use case when they had introduced `=>` syntax for lambdas. RE "To that end I'd go so far as to amend the proposal that @ is only legal when immediately followed by ." seems a pretty narrow use case to deserve a new syntax. Furthermore, most of that would be covered by method references. Would you prefer this over method references? I'm asking because you've worked with Java and are aware of the trade-offs.

Aside: I can think of an IDE feature to convert `@.` to `x => x.` when you press `.` after `@`. In fact, R# has a similar feature for null checks, try `if(ident.null`.

**Comment by alrz** [comment]
Also, you specifically mentioned Where and OrderBy. C# has a fully fledged syntax which will remove *all* the clutter around those methods including the lambda syntax.

**Comment by orthoxerox** [comment]
`@.` is extremely restrictive, it excludes useful patterns like `list.Where(@ <= limit)` or `list.Select($"foo {@} bar")`.

**Comment by HaloFour** [comment]
@alrz 

It might be too narrow, in which case it can be declined.  Seems interesting enough to get some attention, though.

I don't propose this in lieu of method references.  They have their place for simple selection based on an existing member, but my experience in Java is that this doesn't occur all that often (and I have IntelliJ set to automatically replace simple lambdas with method references).

**Comment by orthoxerox** [comment]
You could go the way of Swift and use `{}` to delimit the lambda.

```c#
var query = db.Orders
    .Where({@.Value > 50.0m})
    .Select({@.Employee})
    .OrderBy({@.Name});
```

**Comment by eyalsk** [comment]
@HaloFour, @alrz 

> f1(f2($1.A + $2.B) + $3.C)

Just wanted to demonstrate an operation that takes 3 parameters and that the name of the parameters can be less important than the result so dunno _associativity_ just came to mind out of nowhere, really, not that it matters but I actually wanted to type this `$1.A + $2.B + $3.C`... 

In my initial example the parenthesis around A + B didn't imply a function call but are you guys referring to function composition? or you mean how it's interpreted in terms of the compiler? if it's the latter than I was referring to the following `f1((x, y, z) => (x + y) + z)` as opposed to `f1(z => f2((x, y) => x + y) + z)`, again, ofc that there's no need for the parenthesis in the former (unless it's overloaded or something and it has a different meaning), anyway, it was a typo. :)

**Comment by HaloFour** [comment]
@eyalsk 

I know, and I took liberty with your example by embedding the method call.  My point was to illustrate the complexity that syntax would cause given nested lambdas.  Currently that's easy to deal with since each lambda would have its own unique set of argument names.

**Comment by orthoxerox** [comment]
@HaloFour I've been thinking about this proposal for a while and I now think it's possible to parse freeform shorthand lambdas if we restrict their use to invocation arguments.

1. We parse `@` as `PlaceholderExpression`, just like in #74 
2. Somewhere around `BindArgumentExpression` we do the recursive check for placeholders in the `argumentExpression`
3. If there are any, we invoke `BindAnonymousFunction` instead of `BindValue`
4. `BindAnonymousFunction` is either modified to support expressions with placeholders, or we transform the syntax node into a regular lambda.

Does this idea look good to you?

### Open questions

1. I have to come up with a way to harmonize it with #74, or `"foo" |> bar("baz", @)` will be incorrectly bound as `"foo" |> bar("baz", x => x)`. The unified algorithm depends on the answer to question # 2 below.
2. Should we do this in the outermost call or the innermost call (I think both are equally feasible)? I.e., is `Foo(Bar(@))` equivalent to `Foo(x => Bar(x))` or `Foo(Bar(x => x))`. I think the former is the better option, since it will support things like `items.Where(IsGood(@))`. Are there any counterexamples you can think of?

**Comment by orthoxerox** [comment]
On the other hand, nested lambdas become too complex if we rewrite the outermost argument:

```c#
IEnumerable<Option<T>> Foo(IEnumerable<T> source, Option<T> right, Func<T, T, T> func)
    => source.Select(l => right.Select(r => func(l, r)));
```

can be rewritten as 

```c#
//option A
IEnumerable<Option<T>> Foo(IEnumerable<T> left, Option<T> right, Func<T, T, T> func)
    => left.Select(right.Select(r => func(@, r)));
```

but that's not a huge improvement. On the other hand, this looks more natural, but doesn't compile under my binding rules from the previous comment:

```c#
//option B
IEnumerable<Option<T>> Foo(IEnumerable<T> source, Option<T> right, Func<T, T, T> func)
    => source.Select(l => right.Select(func(l, @)));
```

The rules can be adjusted, of course: in step 2 we can check if the argument is a lambda and bind it as is if it is. This should make both option A and B compile correctly, which is great.

I wonder if something scarier can be made to work:

```c#
IEnumerable<Option<T>> Foo(IEnumerable<T> source, Option<T> right, Func<T, T, T> func)
    => source.Select(right.Select(func(@, @@)));
```

**Comment by MgSam** [comment]
I don't think this is remotely worth it. It doesn't make code any clearer (probably less clear), saves only a few keystrokes, and opens a whole can of worms about people wanting to extend it for multiple parameters, how to disambiguate it for parsing in this or that situation.

**Comment by HaloFour** [comment]
@MgSam 

> It doesn't make code any clearer (probably less clear)

Well, we can disagree on that point.  I think it brings the accessed member into focus, which is the intent.

> and opens a whole can of worms about people wanting to extend it for multiple parameters, how to disambiguate it for parsing in this or that situation.

Indeed, the issue with any kind of proposed keystroke-saving feature like this is that it immediately attracts secondary proposals seeking to extend it sometimes trying to effectively replace the existing syntax entirely.  Auto-implemented properties, primary constructors, etc., it's a common trend.  I wouldn't let that concern alone torpedo a proposal such as this.  Especially since the keystroke savings are so incredibly minor that expanding to full form is far from an onerous task.

**Comment by orthoxerox** [comment]
Implemented a prototype (no IntelliSense) in https://github.com/orthoxerox/roslyn/tree/features/shorthand-lambdas

**Comment by orthoxerox** [comment]
Pah, my second try wasn't that successful either, I picked the wrong binder to subclass. I just need to untangle proper changes from erroneous ones...

Also, `Console.Write(Foo(@+1))` won't compile, since it thinks `Foo(@+1)` is a lambda. That's the counterexample I was looking for. I am not sure how I can support both this and `items.Where(IsGood(@))` at the same time.

@HaloFour do you have any suggestions as the proposal starter on how to resolve this issue? Roslyn binds the arguments first and only then looks for a fitting overload, so I cannot check if the enclosing function accepts a delegate.

**Comment by orthoxerox** [comment]
Okay, the prototype finally works. https://github.com/orthoxerox/roslyn/tree/features/shorthand-lambdas

I still have no idea how to resolve the nested call case, though. Both options feel unsatisfactory.

**Comment by TonyValenti** [comment]
Hi All,
I wanted to pass in a few other ideas for shorthand lambdas.  I've noticed that most lambdas seem to accept either zero or one parameters and they seem to either be single-line or multi-line.  In this case, I suggest shorthand for both:

````
//Single-line "Quick" lambda:
var Data = List.Where(_.Name > 32);

//Single-line "Quick" lambda that doesn't reference the current item:
var GetItems = true;
//Equivalent to List.Where(x => GetItems);
var Data = List.Where(GetItems)

//Multi-line "Quick" lambda:
var Data = List.Where({
  if(_.Name > 32){
    return true;
  } else {
    return false;
  }
});

````

**Comment by HaloFour** [comment]
@TonyValenti 

Both of those suggestions are already legal syntax.  How would the compiler unambiguously determine that you intend do use a lambda vs. a simple expression?

**Comment by TonyValenti** [comment]
@halofour -
It should use the type of the function’s parameters to disambiguate it. For example, if I have:

Public static ... Where<t>(func<t, bool> condition));

Then simply calling where(true) should expand to:
Where(_=>true)

If there are multiple overloads, such that I have a where(bool), passing true would result in the bool method being called instead of the func overload being called.

**Comment by HaloFour** [comment]
@TonyValenti 

IIRC the C# compiler needs to be able to resolve the type of the expression in isolation, so for this to work the compiler would have to support an implicit coercion between `bool` and `Func<T, bool>`, or really between any scalar type `TR` and an arbitrary delegate that returns `TR`.  I personally think that this adds a bit too much voodoo and I can't imagine that there are enough use cases where you'd want to pass a delegate that returns a static value.

I am also quite opposed to the idea of overloading `_` to mean a third thing.  I think that it's messy enough having to be able to discern between when `_` is a variable and when it is not.  Having to additionally figure out that expressions off of `_` might be a lambda expression I think is too much of a cognitive burden.  The `_` character could literally mean all three things in the span of a single method.  And given that the recent design decisions are that `_` indicates a throw-away value it doesn't make a lot of sense to actually be able to reference it.  I'd rather a new syntax to clearly disambiguate the intent.

**Comment by jamesqo** [comment]
What does everyone think about my idea at https://github.com/dotnet/csharplang/issues/1264?

```cs
class Person { string Name; }

IEnumerable<string> names = people.Select(.Name);
```

**Comment by orthoxerox** [comment]
@jamesqo it's fine, but it shortens only one use case.

**Comment by jamesqo** [comment]
@orthoxerox It's a very common use case, though.

**Comment by TonyValenti** [comment]
I was thinking that perhaps we should also allow the syntax:
Method((x,y)=>x.First + Y.Last);

To be shortened to:
Method($0.First + $1.Last);

**Comment by DerpMcDerp** [comment]
How about `=>` with no lhs and which takes an expression or block on the rhs and scans for all literals with `$<digits>` and treats them as implicit parameters, e.g.

```C#
var foo = bar.Something(=> $1.Bar + $2.Bar);
// means:
// var foo = bar.Something((gensym1, gensym2) => gensym1.Bar + gensym2.Bar);
```

Also to further save typing, `.Foo` means the same as `$1.Foo`:

```C#
var names = people.Select(=> .Names);
// means:
// var names = people.Select(gensym => gensym.Names);
```

**Comment by orthoxerox** [comment]
@DerpMcDerp Hm... Looks interesting. The prefix should help to find the start of the lambda. Why is $1 the first parameter, though?

Also, I wonder if `=>` is the best token for it.

**Comment by orthoxerox** [comment]
ECMAScript proposal that is partially related: https://github.com/tc39/proposal-partial-application

**Comment by bandleader** [comment]
Related: there is a Babel plugin to do this for JavaScript. The source code of the plugin looks very simple. Might be useful.
https://github.com/xtuc/babel-plugin-transform-scala-lambda/tree/master/src

Also related: the part from the Scala spec which describes this -- though it's in mathematical language:
https://www.scala-lang.org/files/archive/spec/2.11/06-expressions.html#placeholder-syntax-for-anonymous-functions

**Comment by AndreasHassing** [comment]
I wonder if it would make sense to make this work for instance methods as well?

```csharp
class Person
{
    public bool IsNice()
    {
        // TODO calculate whether a person is nice or not
        return false; // assume the worst for now...
    }
}

void HandThemKeysToTheKingdom(IEnumerable<Person> people)
{
    foreach (var nicePerson = people.Where($.IsNice))
    {
        // give them the keys!
    }
}
```

**Comment by AlexAtNet** [comment]
This proposal just comes to my attention.

After thinking for a while about it and think that if the compiler would be smart enough then no new syntax is required for lambdas to simplify this case.

If the compiler interpreters expression with undefined variables as function of these variables, placing them in the order of appearance, then writing lambda expressions will be very easy. But perhaps the readability of this would be an issue... Anyway, example:

    var strs = points.Select($"{p.x}, {p.y}"));

p is not defined. The expected argument of the select is `Func<T, V>`.

So why not interpret  `$"{p.x}, {p.y}"` as a function with one parameter `p`?

Similarly, the example from the initial post becomes

```
var query = db.Orders
    .Where(order.Value > 50.0m)
    .Select(order.Employee)
    .OrderBy(employee.Name);
```

assuming that both `order` and `employee` are not defined in the upper scope.

**Comment by bandleader** [comment]
@AndreasHassing If this suggestion is implemented, your example should work with no problem; not sure why you wouldn't think so?

@AlexAtNet Interesting, but having undefined variables do anything at all is a big no-no since the advent of Option Strict. Partly because it could be problematic e.g. if you misspell the name.

Also, while I understand your thinking, it doesn't actually solve the parsing difficulty we were talking about. The difficult part is not making `_` valid as an identifier -- it's deciding at what depth in an expression tree the lambda starts. (It turns out this is not actually hard to get right, as the Scala spec is very clear, and there's even a very simple Babel plugin.) [See the links in my last post.](https://github.com/dotnet/csharplang/issues/91#issuecomment-437199300)

Thank you everyone for your suggestions and enthusiasm! This would be a great upgrade, and it fits so perfectly with VB.

**Comment by bandleader** [comment]
See also my post in vblang where I describe the simple rules that Scala uses for parsing this:
https://github.com/dotnet/vblang/issues/256#issuecomment-439633648

**Comment by AlexAtNet** [comment]
@bandleader Thank you for comments. Yes, you are right - parsing difficulty is another issue and I do not intend to solve it. I rather exploring the boundaries of the problem of compact syntax, leaving implementation out. I'm not considering it unimportant, I just do not know it good enough.

I do not see a problem with misspelling the name, because the algorithm (the one that replaces expression with unknown variables with Func) could be invoked only in the right place - where the function argument is Func<>. If the overload exists that accepts scalar value then yes, mistake in the name might led to use different function.

```
class Test {
  void M1(Func<int, int> f) { ... }
  void M1(int) { ... }
}

var value = 10;
new Test().M1(vale); // typo here, the algorithm will generate identity function instead of scalar value
```

The _ (underscore) does not need to be magical, I think. I mean that if it is just an identifier, then any identifier that is not used before can serve the same purpose. It is more magical in Scala though (I understood that it is kind of a new parameter every time).

**Comment by bandleader** [comment]
@AlexAtNet I hear that, but your approach (to only allow this where a `Func<>` is expected) is usually considered a bad idea by compiler writers, because it requires waiting until the binding stage (as opposed to the parsing stage). This means that identical parse trees can have two different meanings depending on binding, etc. I mentioned this briefly in the [same comment on vblang](https://github.com/dotnet/vblang/issues/256#issuecomment-439633648).

I'm curious also why you prefer using an undefined variable name to a symbol like `_` (Scala) or `$1` (Swift)? (Or `it` (Python))

**Comment by AlexAtNet** [comment]
@bandleader I do know know much on the compilation stages. Thanks for explaining this.

> I'm curious also why you prefer using an undefined variable name to a symbol like _ (Scala) or $1 (Swift)? (Or it (Python))

Mostly readability. `.Select($"{name}{index}")` as equivalent to `.Select((name, index) => $"{name}{index}")` looks a bit better to me than `.Select($"{_}{_}")` or `.Select($"{$1}{$2}")`.

**Comment by gilmishal** [comment]
Would using `$name` and `$order` simplify parsing? as opposed to `order` and `name` they can't be mistaken to other variables. However I think the functionality of `$"{$2}{$1}"` is more useful than readability in the shorthand case, since it shouldn't be used for more complex lambda's IMO and you could always add hover functionality and see the type in VS. 
The `$order` and `$name` don't allow for ordering based on the numbers like swift does, and I would still rather go with $1 and $2.

**Comment by AndreasHassing** [comment]
> @AndreasHassing If this suggestion is implemented, your example should work with no problem; not sure why you wouldn't think so?

@bandleader: I never implied that I wouldn't think it should work 🙂.

**Comment by bellagita** [comment]
In # 3075 I proposed another solution for lambda expressions that seems more effective to me: deriving names from the delegate. Instead of having a delegate defined like this: 

`Func <int, int, int> sum = (x, y) => x + y;`

it could be defined as:

`Func <int, int x, int y> sum => x + y;`

Or:

`Func <int, int fast, int furious> andbit => $fast & $furious;`

If you want, otherwise the traditional call always remains:

`Func <int, int x, int x> mult = (realy, good) => realy * good;`

**Comment by HaloFour** [comment]
@bellagita 

Who defines those names?  A lot of LINQ methods in particular use generic names which wouldn't be particularly useful.  You'd end up with a lot of those names being the equivalence of `arg1`, etc..  IMO the name of the argument itself is the least important part of the expression and I'd rather a way to omit it entirely, not drive it based on the definition that is outside of my control.

**Comment by bellagita** [comment]
@HaloFour 

The name hare defined in the delegate. From:
Func<int, int, int> 
to 
Func<int **X**, int **Y**, int>. 

This is the new idea! 
The name in the delegate is only suggested!
The supplier of the delegate can suggest names with the best meanings for each individual case!
Example: where of linq!
`Where<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate);`
to 
Where<TSource>(this IEnumerable<TSource> source, Func<TSource **_item_**, bool> predicate);

**Comment by HaloFour** [comment]
@bellagita 

Indeed, and I see zero value in having LINQ methods defining those names.  `item` is just as pointless as `arg1`.  It's already shorter to use a single-letter lambda argument anyway.

**Comment by alexrp** [comment]
For what it's worth, here's what Elixir does for shorthand lambdas: https://hexdocs.pm/elixir/Kernel.SpecialForms.html#&/1-anonymous-functions

In C#, perhaps that could look something like `@(... reference parameters as @1, @2, ...)`. That would allow multi-parameter shorthand lambdas. The language could then define that parameter references of the form `@n` always refer to the parameters of the innermost shorthand lambda expression, eliminating ambiguity and vastly simplifying the implementation effort. That does mean you can't capture variables from an outer shorthand lambda, but I would seriously how readable such code would have been anyway; I think you should probably reach for regular lambda expressions in that case.

(In Elixir's case, nested shorthand lambdas are actually outright illegal, though I personally think it's unnecessary to go that far as long as you clearly define how parameter references work.)

So the example in the original proposal would look like this:

```csharp
var query = db.Orders
    .Where(@(@1.Value > 50.0m))
    .Select(@(@1.Employee))
    .OrderBy(@(@1.Name));
```

Admittedly not *quite* as short, but it's something to consider.

**Comment by CyrusNajmabadi** [comment]
`@(@1.Value > 50.0m)`
`i=>i.Value > 50.0m)`

These are identical in length.

**Comment by alexrp** [comment]
Just to be clear, my previous comment was meant mainly as food for thought since multiple parameters and nesting (and the issues with those) were brought up here a while back; it wasn't meant as a counter-proposal in and of itself.

---

In the interest of fairness, it's worth pointing out that the above shorthand form would be shorter (regardless of spacing) the more lambda parameters you have, where you're using those parameters in more elaborate expressions such as member access:

```csharp
x=>x.Value
@(@1.Value)

(x,y)=>x.Value+y.Value
@(@1.Value+@2.Value)

(x,y,z)=>x.Value+y.Value+z.Value
@(@1.Value+@2.Value+@3.Value)
```

I imagine you could simultaneously allow the form originally proposed for the probably more common case of a single lambda parameter. There's arguably some precedent for that in how lambda expressions allow you to write `x => ...` as a shorter form of the more general syntax `(x) => ...`.

---

There's also another thing to consider regarding multi-parameter lambdas. This could just be a 'me' issue, but sometimes when I'm typing out lambda expressions with multiple parameters, I might only realize halfway through writing the expression itself that I forgot to declare, say, a trailing parameter in the parameter list, so I have to move the cursor back and add in the missing parameter. The advantage of the shorthand syntax here is that if you've used, say, 2 parameters in the expression and you realize you need a 3rd, you just literally type `@3` and you're done. It's not just about shortening the resulting code.

**Comment by CyrusNajmabadi** [comment]
```
(x,y,z)=>x.Value+y.Value+z.Value
@(@1.Value+@2.Value+@3.Value)
```

That seems to be almost no savings at all to me :)

**Comment by theunrepentantgeek** [comment]
In fact, the number of characters saved is exactly the number of parameters, at the cost of obfuscating the whole thing. 

When I see this
```
(x,y,z)=>x.Value+y.Value+z.Value
```
I can infer from the problem domain what `x`, `y`, and `z` might mean ... perhaps they're 3D point coordinates? Hard to tell from a single line of code.

Quoting the OP, I can rewrite the query as this:
```
var query = db.Orders
    .Where(o => o.Value > 50.0m)
    .Select(o => o.Employee)
    .OrderBy(e=> e.Name);
```
And I don't need much insight to recognize that `o` means `order`, and `e` means `employee`.

With positional parameters like `@`, `@1`, `@2`, and `@3` not only are they inherently meaningless, but each one might have a different meaning on each line:
```
var query = db.Orders
    .Where(@.Value > 50.0m)
    .Select(@.Employee)
    .OrderBy(@.Name);
```
The first `@` is an `order`, the second `@` is also an `order`, but the third `@` is an employee.

Code is read many many times more often than it is written; saving a few moments of the writers time _once_ at the cost of costing a few moments of the readers time _many many times_ seems a Faustian bargain.

**Comment by gilmishal** [comment]
>Code is read many many times more often than it is written; saving a few moments of the writers time once at the cost of spending a few moments of the readers time many many times seems a Faustian bargain.

@theunrepentantgeek 
I generally agree with the issue you are raising - I do think however that with the right tooling, this issue can be solved. If in VS hovering over the `@` would show which type it is, this won't be an issue really.
Just like `var` isn't an issue to most c# programmers anymore - and even though the recommendation was to use `var` when the type is obvious, vars are everywhere and it's not causing any issues for most readers, because they can just see the type.

Sure there are cases where this entire thing can be confusing and will require a little more time from the reader, but those cases are a small minority, and I like the idea of giving programmers the freedom and the responsibility of choosing the more fitting syntax.

**Comment by darrenoakey** [comment]
while I'd love this feature, can I argue for a slightly different syntax?

```c#
var query = db.Orders
    .Where( .Value > 50.0m)
    .Select( .Employee)
    .OrderBy( .Name);
```

I believe that having nothing in front of the "." makes it more intuitive, cleaner and easier to read?
