### ISSUE TITLE
Proposal: Pipe-forward operator

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#96]
Ported from dotnet/roslyn#5445

# Pipe-forward operator 

## Summary

Lets you pass an intermediate value onto the next method, in the same order that they will be evaluated.

## Proposal

When you are chaining multiple methods to one another you might end up with something like this:

``` C#
Console.WriteLine(BitConverter.ToString(SHA1.Create().ComputeHash(File.ReadAllBytes(Console.ReadLine()))));
```

Using pipe-forward operator it can be written as (in the same order that they will be executed):

``` C#
Console.ReadLine()
|> File.ReadAllBytes()
|> SHA1.Create().ComputeHash()
|> BitConverter.ToString()
|> Console.WriteLine();
```

Since C# is not exactly a functional language, forwarding to the last parameter wouldn't be useful most of the time, because not every method parameters are written with a sensible order for currying purposes. Also, in functional languages we don't have overload resolution, that is, functions are often numbered like `iter1`, `iter2`, etc. In C#, however, we can utilize overload resolution and optional/named arguments, to be able to use this in a wide variety of use cases without introducing any other mechanism.

### Argument Lists

Applicability of the argument list in the RHS is roughly defined as follow:

#### Empty argument list

 It's a compile-time error if the method in the RHS doesn't accept any arguments. 

``` cs
Action<int> a = q => {};
arg |> a;       // ERROR

void M() {}
arg |> M();     // ERROR

void M(int a) {}
arg |> M();     // OK
```

#### Positional arguments

Each positional argument will be matched in order to the list of method parameters. If there was more positional arguments than number of parameters **minus one** and the last parameter was not `params`, the method is not applicable. Otherwise, the LHS goes to the last element in the expanded form.

``` cs
void M(int a) {}
arg |> M();     // M(arg);

void M(params int[] a) {}
arg |> M();     // M(new[] { arg });
arg |> M(1);    // M(new[] { 1, arg });
arr |> M();     // M(arr);
```
#### Optional arguments

In case of optional arguments, LHS goes to the leftmost unspecified parameter which has the identical or implicitly convertible type of LHS. If there was a more specific parameter, then we skip other less specific ones.

``` cs
void M(int a, int b, double c = 0, int d = 0) {}
4d |> M(2, 3);  // M(2, 3, 4d, 0);
4  |> M(2, 3);  // M(2, 3, 0, 4);
```

#### Named arguments

 Each named argument will be matched to a parameter with the given name. If one of the named arguments failed to match, or matches an argument already matched with another positional or named argument, the method is not applicable. Otherwise, we'll do as above.

``` cs
void M(int a, int b, int c) {}
void M(int a, double b, int c) {}
1  |> M(2,  c: 3);      // M(2, 1, 3);
1d |> M(a: 2,  c: 3);   // M(2, 1d, 3);

```

The method is not applicable (1) if more than one of non-optional parameters are not specified, (2) LHS was not implicitly convertible to its type (3) or it's a `ref` or `out` parameter.

### Evaluation order

 The LHS will be evaluated in the lexical order, i.e. first.

``` cs
F() |> M(G());  // var t = F(); M(G(), t);
```

### Null-conditional forwarding

(From dotnet/roslyn#8593)

``` cs
var r = Foo.Bar?.Baz ?> F() ?? false;
var r = ((temp = Foo.Bar?.Baz) != null ? F(temp) : null) ?? false;
```

Function `F` won't get executed if the forwarded value was `null`, and also, `Foo.Bar?.Bar` only evaluates once. Note that the value forwarded to the target function `F` is of a "non-nullable type".

Just like `?.` operator, you don't need to use `?>` if the target function doesn't return a nullable value, so for chaining you should use the regular `|>` operator to not perform an additional null-checking.

## Syntax

 _relational-expression:_
 &emsp;_forward-expression_
 
_statement-expression:_
 &emsp;_forward-expression_
 
 _forward-expression:_
&emsp;_relational-expression_ `|>` _shift-expression_
&emsp;_relational-expression_ `?>` _shift-expression_

The expression on the right-hand-side must be one of the kinds that a value can be forwarded to, namely, *invocation-expression*, *object-creation-expression*, an *await-expression* that contains any of applicable expressions (recursively), etc.

## Examples

``` cs
var r = nullable?.Foo.Bar ?? value;
var r = (nullable != null ? nullable.Foo.Bar : null) ?? value;

var r = value |> F() ?> G() ?? value;
var r = ((temp = F(value)) != null ? G(temp) : null) ?? value;

var r = nullable ?> F() |> G() ?? value;
var r = (nullable != null ? G(F(nullable)) : null) ?? value;

var r = nullable ?> F() ?> G() ?? value;
var r = (nullable != null ? (temp = F(nullable)) != null ? G(temp) : null : null) ?? value;

var r = value |> foo?.F();
var r = foo?.F(value);

var r = nullable ?> foo?.F();
var r = nullable != null ? foo?.F(nullable) : null;
```

**Comment by a1n1** [comment]
Is this issue acceptable for pull request ?

**Comment by chrisaut** [comment]
What's the difference between this and https://github.com/dotnet/csharplang/issues/74 ?

**Comment by alrz** [comment]
@a1n1 Not sure, but supposedly, there will be a "champion" issue once this passes the first stage.

@chrisaut This has the input parameter added to the argument list. That proposal requires there be no argument list i.e. the LHS would be forwarded to the "value" of the RHS, hence, it would not permit forwarding to methods with more than a single (formal) parameter.

**Comment by AlexanderMorou** [comment]
I don't understand what actual **problem** this solves.

Sure, it unwraps the call chain so it places the methods in their actual execution order, but it doesn't make the code any shorter.  There are few (if any?) cases I've encountered where I couldn't follow nested parameters.  You could turn the example into:
```
Console.WriteLine(
  BitConverter.ToString(
    SHA1.Create().ComputeHash(
      File.ReadAllBytes(
        Console.ReadLine()))));
```
And it's just as easy to read, as the parenthesis make the execution order clear.  It's also crystal clear, within which parameter an argument will actually be placed, without worrying about implicit conversions coercing the actual parameter you're specifying.

What implications does this have for IntelliSense, would it provide context on what parameter it goes into by hovering over the |> characters? Wouldn't you also have to ensure the right-hand side of the operator, within the intellisense that it's accepting one forwarded operator in some manner?

The only thing I do like is the argument-level short-circuiting, though that sounds like it could be a feature request of its own for standard calling conventions.

**Comment by alrz** [comment]
>but it doesn't make the code any shorter.

that's not the intention here.

>And it's just as easy to read

It's not as easy to write since you should be writing the methods in the reverse order. Using locals however, can help with that but then you have to leave the expression context.

>The only thing I do like is the argument-level short-circuiting, though that sounds like it could be a feature request of its own for standard calling conventions.

What syntax are you imaging for that as an separate feature?

**Comment by AlexanderMorou** [comment]
@alrz : The biggest gripe I have with the feature is the disconnect between what you're writing and where the data actually goes.  The notion that it would bind differently based on the type of the parameter: overload resolution is already complicated enough as it is, if there was some way to explicitly stipulate which parameter was the target of the forwarded pipe, through say a special character combination of some sort:
```
Console.ReadLine()
|> File.ReadAllBytes(|<)
|> SHA1.Create().ComputeHash(|<)
|> BitConverter.ToString(|<)
|> Console.WriteLine(|<);
```
This way if it were targeting a specific parameter, the notion of overload resolution wouldn't be a concern, if you wanted parameter `z` of type `U` to be the target, and optional parameters were in play, you could simply go: `A() |> B(z:|<);`

That would make the binding of the operation much simpler to understand, and I think the reader would benefit, as well.

> What syntax are you imagining for that as a separate feature?

Probably something like: ?? prefixing the argument
?? alone would probably be sufficient because it is evident that it's not a nullable coalescing operator as there's only one operand.

As for weaving it into the language spec as it is today, it would probably be something like:
```
argument_value
    : '??'? expression
    | 'ref' '??'? variable_reference
    | 'out' variable_reference
    ;
```
It wouldn't be allowed on the out parameter because it's implicitly unassigned within the scope of the called method, so it wouldn't really make sense.

The default value of the method would be the result of the expression if it short-circuited.

If you were to take the two ideas **together**, you would only need one pipe-forward operator: `|>`, the `?>` would be replaced by: `?? |<` on the parameter you intended it to be for.   So instead of: 
```
if (args != null)
{
   format
   ?> String.Format(args: args)
   ?> Console.WriteLine();
}
```
You'd end up with:
```
String.Format(?? format, ?? args)
|> Console.WriteLine(?? |<);
```

**Comment by MorleyDev** [comment]
C# being a language that lacks currying-by-default, the 
`Console.ReadLine()
|> File.ReadAllBytes()
|> SHA1.Create().ComputeHash()
|> BitConverter.ToString()
|> Console.WriteLine();`

seems really confusing to me. I'd expect the pipeline to be executed against a function returned by File.ReadAllBytes(), not to be turned into File.ReadAllBytes(Console.ReadLine). 

The following seems more intuitive to me for C# code:
`Console.ReadLine()
|> File.ReadAllBytes
|> SHA1.Create().ComputeHash
|> BitConverter.ToString
|> Console.WriteLine;`

Lambda functions allow you to bypass the lack of currying without generating too much noise, and leaving room for potentially implementing currying in the future without needing to address the topic now:
`10 
|> x => x * 10
|> x => Console.WriteLine($"Hello: {x}")`

Incidentally, this can already be implemented in C# as it currently stands via an extension method, though as a method call instead of the special |> operator:

`public static U Pipe<T, U>(this T self, Func<T, U> next) => next(self);`

Which would result in the code instead being written as
`Console.ReadLine()
    .Pipe(File.ReadAllBytes)
    .Pipe(SHA1.Create().ComputeHash)
    .Pipe(BitConverter.ToString)
    .Pipe(Console.WriteLine)`

**Comment by alrz** [comment]
@MorleyDev 

Here I suggested to just "add the LHS as an argument to the method invocation on the right." (other than some cases with optional arguments which can be excluded if seen as rather unreliable than helpful). that doesn't require you to fallback to lambda when there is more than a single parameter (which I've found very likely). There's a discussion on the other variation here: #74

**Comment by MorleyDev** [comment]
@alrz I read further on the other discussion and saw it talks about this suggestion so deleted my post. Seems you got in there right before, sorry about that :)

Since it's too late and I've been replied to now, I guess I'll sum up what you were replying to: This doesn't look to me like it fits the established expectations and design of the C# language, unfortunately. The basic pipe operator part of #74 fits closer, and if a form of currying gets added in the future appears that it would behave similar to the above does anyway. Tackling the two problems together seems pointless when an intermediate lambda solves the issue in the short term.

Interestingly, I've seen the usage of an intermediate lambda has cited as a reason for a lack of motivation in introducing currying to ECMAScript nowadays as well.

**Comment by IgorX2** [comment]
@alrz: It would be cool to be able to pipe tuples as arguments, but the argument order could be a problem.

```
void F(int a, int b) {}
(arg1, arg2) |> F();     // F(arg1, arg2);
```

**Comment by vbodurov** [comment]
Can we have pipe aliases? For example:
`
Console.ReadLine()
:ReadBytesAndComputeHash
|> File.ReadAllBytes(<|)
|> SHA1.Create().ComputeHash(<|)
:ConvertToStringAndOutput
|> BitConverter.ToString(<|)
|> Console.WriteLine(<|);
`

Now I would have ReadBytesAndComputeHash method defined in the class that I can reuse it elsewhere.

The advantage of this is that I achieve 2 goals at the same time:

1. I have the entire pipeline of operations defined in one sequence
2. I can still reuse different parts of it elsewhere

Otherwise it would be impossible to see the entire pipeline with all steps in one place, but at the same time be able to reuse parts of it.

The same could apply for linq:
`
GetPersons()
:PeoplesNamesStartingWithA
.Select(p => p.Name)
.Where(name => name.StartsWith("A"))
:SomeOtherGroup
.Select....
`

**Comment by masaeedu** [comment]
Sorry if I missed it in the discussion, but why is it:

```c#
Console.ReadLine()
|> File.ReadAllBytes()
```

instead of the following?

```
Console.ReadLine()
|> File.ReadAllBytes
```

Isn't the function here `File.ReadAllBytes`?

**Comment by theunrepentantgeek** [comment]
I think it's because simply naming a method (as `File.ReadAllBytes`) returns a *method group* - which might include multiple overloaded methods.

Including the `()` at the end provides a way to specify *which overload* should be called - in the example, it should call `File.ReadAllBytes(string)`.

**Comment by masaeedu** [comment]
Isn't the overload determined by the LHS of the expression? `"foo" |> x` desugars to `x("foo")`, which is unambiguous for `x = File.ReadAllBytes`.

**Comment by theunrepentantgeek** [comment]
It's unambiguous for `File.ReadAllBytes` right now - in the current version of the framework. 

But, what happens if that changes in the future?

For example, and purely for illustration, what if a future version of the framework adds a new overload: `File.ReadAllBytes(string, Encoding)` ?

The method group would then return two methods, which isn't unique. If the parenthesis were not permitted for the *single parameter case*, then we'd end up with a disconnect.

For the original overload:

```
Console.ReadLine()
|> File.ReadAllBytes
|> SHA1.Create().ComputeHash()
```

But for the new overload:

```
Console.ReadLine()
|> File.ReadAllBytes(new UTF7Encoding())
|> SHA1.Create().ComputeHash()
```

I think it's substantially cleaner to require the `()` to always be there.

Also, and quite separate from my argument above, I suspect that leaving out the `()` and allowing a *method group* to be specified would make things ambiguous in some way (though I haven't quite been able to put an example together).

**Comment by masaeedu** [comment]
To my mind 

```c#
Console.ReadLine() |> File.ReadAllBytes
```

always just means:

```c#
File.ReadAllBytes(Console.ReadLine())
```

`Console.ReadLine() |> File.ReadAllBytes(new UTF7Encoding())` is an error because there's no overload of `ReadAllBytes` that takes an `Encoding` and returns a `Func<string, byte[]>`. This doesn't have anything to do with the pipeline operator, it's the same error you'd get from trying to do:

```c#
File.ReadAllBytes(new UTF7Encoding())(Console.ReadLine())
```

If we want to deal with a two argument function, we can just do `Console.ReadLine() |> (x => File.ReadAllBytes(x, new UTF7Encoding()))`, come up with some other independent feature for making partial application more convenient (e.g. `File.ReadAllBytes(?, new UTF7Encoding())`), or mitigate it at the library level.

**Comment by hickford** [comment]
Some C# code I wrote today that I think would be more readable with a F#-style pipe operator:

Before:

	prefixes.Any(header.StartsWith)

After:

	header.StartsWith |> prefixes.Any

**Comment by rosenbjerg** [comment]
I think it would benefit the language a lot as it would make it much easier to write composeable code. The fluent pattern is very verbose to implement, and is much less flexible than writing several pure functions/static methods and using them in a pipeline fashion, just list in F#.
I would like the C# pipe operator to be as close to the syntax of F#, which I find very useful.

**Comment by 2jacobtan** [comment]
I'm doing pipe-forward using extension methods.

`    static class FunctionChaining
    {
        internal static U _<T,U>(this T input, Func<T,U> fun) => fun(input);
        internal static void _<T>(this T input, Action<T> fun) => fun(input);
    }
`
Sample code:
https://github.com/2jacobtan/CSharp-experiment/blob/master/Function%20chaining/Program.cs

**Comment by vbodurov** [comment]
Thanks Jacob, I like that

**Comment by omidkrad** [comment]
Here's another example of using extension methods to pipe-forward:

Article: https://dev.to/tomydurazno/pipe-in-c-1aga
Code: https://github.com/TomyDurazno/PipeExtensions
