### ISSUE TITLE
Proposal: General acquire/release syntactic sugar (similar to lock and using)

### ISSUE THREAD

**Issue by DavesApps** [dotnet/csharplang#966]
**Acquire/release syntactic sugar**

There are some great sugary syntax around.
Think 
```
lock(obj) {}
using (obj2) {}
```

Those are great because the allow ensuring releasing of a resource even handling any exceptions.  While those are great one only works for Monitor sync objects and the other requires being a truly IDisposable object or subverting the IDisposable syntax/ pattern that’s so well known to do something else. (Many of us I know have used IDisposable not to dispose of an object with the standard well known dispose pattern but just for the purpose of being able to use the using clause)

What if instead we had a new interface (don’t get too caught up with the names we can pick better ones).

```
Interface IAcquireRelease
{
       void Acquire();
       void Release();
}

IAcquireRelease myobj;

acquire(myobj)
{
  // IAcquireRelease.Acquire would be called before the code block starts
}
  // IAcquireRelease.Release would be called after the code block ends (even if an exception was thrown in the block)
```

**Why do this?**
-	This allows us a cleaner syntax rather than subverting the IDisposable/using clause pattern.  (I don’t necessarily like the acquire release names.  Could potentially add this support to the using clause and it would be backward compatible since this interface previously did not exist.  )
-	Doesn’t duel purpose IDisposable interface to do something different than was originally intended.
-	Allows us to use this pattern can create wrappers around things like synchronization objects (Readerwriter locks, etc.) In a way they doesn’t feel subverted.

Yes we can keep dual purposing IDisposable patterns and manually do the acquire ourselves to get the free using syntactic sugar, but this seems pretty low cost to make a more generalized pattern.

**Comment by jnm2** [comment]
The opinion that `using` and `IDisposable` are for anything other than generic acquire/release, or that it's ‘subvertion’ using them for non-‘heavy’, non-‘resource’ or non-unmanaged purposes, is outdated and the horse has bean beaten to death here. It's too exhausting right now but hopefully someone links some of the previous discussion.

(Part of the problem is MSDN misleads people by connecting the IDisposable pattern with finalizers and unmanaged resources. Since SafeHandles were introduced in .NET 4.0, you should never use IDisposable with finalizers or unmanaged resources. You should implement a SafeHandle instead and dispose that just like all your other generic acquire/release disposals and usings.)

**Comment by jnm2** [comment]
That was intended to be helpful rather than overly dismissive. I wasn't looking forward to hashing it all out again, but I'm sorry for the potentially-not-very-warm-welcome and I do hope you stay and continue to share ideas, as well as search for existing ones to comment on! 😃

**Comment by dmitriyse** [comment]
While it's already closed this issue shows, that there is demand of IDisposable/using improvement. See https://github.com/dotnet/csharplang/issues/3025

**Comment by sharwell** [comment]
The primary takeaway of the other discussions would be this:

> Doesn’t duel purpose IDisposable interface to do something different than was originally intended.

The use of IDisposable for unmanaged resources is one example of the use of IDisposable semantics. Other operations that need the same semantics are equally valid. It is not "subverting" the intent of this interface, because the intent of the interface is providing exactly the semantics you want to use.
