### ISSUE TITLE
DebuggerStepThrough for partial classes? [DebuggerStepIn]

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#978]
I have set of classes that are auto generated by tool. but all classes are marked with `DebuggerStepThrough` attribute

the classes are partial, so I can write my code for that class in separate file, however `DebuggerStepThrough` in auto generated part of partial class will affect entire class.

How can I disable this behavior for `DebuggerStepThrough`, removing `DebuggerStepThrough` is obvious solution but that's not the answer I'm looking for. I don't want to touch auto generated code. also skipping from auto generated code is ok, but  I want to be able to debug my own code.

```
[DebuggerStepThrough] partial class Foo 
{    
    // auto generated 
}  
// how to exclude this part from DebuggerStepThrough? 
partial class Foo 
{   
     // user code 
}
```

**Proposal:** please add an option to disable DebuggerStepThrough for part of partial class.

```
[DebuggerStepThrough(disable: true)] 
partial class Foo 
{   
     // user code 
}
```

This will cause the compiler to generate attributes for each member, rather that for entire class. so if `disable: true` is specified, compiler will generate this attribute for each member individually in order to have part of class skipped, but part of class debug-able.

**Proposal 2:**

introduce new attribute, `[DebuggerStepIn]`, this attribute can not be marked together with `[DebuggerStepThrough]` but it can be marked in nested member like this.

```
[DebuggerStepThrough] 
class Foo 
{
    [DebuggerStepIn]
    public void Method() {}
}  
```

**Comment by sharwell** [comment]
My preferred solution is the one you don't want: avoid using `[DebuggerStepThrough]` altogether.

The solution for people who do want the attribute's behavior applied to the generated code, the solution is applying the attribute to the individual members in the generated code instead of applying the attribute to the entire class. Naturally this results in some duplication, but since the duplication is entirely generated it should not be a problem.

**Comment by MkazemAkhgary** [comment]
but I think this isn't a big deal for Microsoft to enhance this attribute just to be more usable.

I don't have access to tool for code regeneration with new settings, and I don't really want to touch that code, its 15K lines of code. a big blob of classes. @sharwell

**Comment by MkazemAkhgary** [comment]
or maybe introduce new attribute, `[DebuggerStepIn]`, we can not have both attributes for a class or member, but we can have them nested like this.
```
[DebuggerStepThrough] 
class Foo 
{    
    [DebuggerStepIn]
    public void Method() {}
}  
```

**Comment by sharwell** [comment]
:memo: The `DebuggerStepThroughAttribute` is not defined by the C# language specification. It's only used by the debugger implementation. If you are specifically looking for improvements to the debugging experience, I would recommend filing an issue in [dotnet/roslyn](https://github.com/dotnet/roslyn), since the debugger team there would be able to act on improvements in less time.

**Comment by sharwell** [comment]
> or maybe introduce new attribute, [DebuggerStepIn]

You have a compelling argument here; very good example.

**Comment by MkazemAkhgary** [comment]
Thank you for the link. @sharwell
